feat: use npm as the default frontend pacakge manager
vaadin/docs pull request #1018
Opened 2022-01-07 09:11 UTC by haijian-vaadin

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2022-01-07 11:32 UTC, jouni commented on articles/upgrading/common/_22-23.adoc
> +pass:[<!-- Vale Vaadin.CrossReference = YES -->]
```suggestion
pass:[<!-- Vale Vaadin.Versions = NO -->]

- Starting from Vaadin 23, `npm` is used as the default frontend package manager, since the performance of `npm` has been improved and it is possible to lock dependency versions with npm https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides[overrides feature].
`pnpm` is still supported.
To continue using pnpm, set the <<{articles}/shared/guide/configuration/_npm-pnpm, pnpm.enable flag>> to true.

pass:[<!-- Vale Vaadin.Versions = YES -->]
```

2022-01-07 11:32 UTC, jouni commented on articles/shared/guide/install/_npm.asciidoc
> +Vaadin uses the npm https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides[overrides feature] (sicne npm 8.3.0) to lock the transitive platform dependencies versions.
```suggestion
Vaadin uses the npm https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides[overrides feature] (since npm 8.3.0) to lock the transitive platform dependencies versions.
```

2022-01-09 11:33 UTC, dougjewsbury reviewed
Looks fine from an AsciiDoc point of view.

2022-01-11 08:30 UTC, Lodin requested changes

2022-01-11 08:30 UTC, Lodin commented on articles/shared/guide/configuration/_npm-pnpm.asciidoc
> +It's still possible to use pnpm. To switch to pnpm you can set the `vaadin.pnpm.enable` system property to `true`.
I guess, for new users it is better to mention that we just support `pnpm`.
```
https://docs.npmjs.com/cli/v8/commands/npm[_npm_] is used as the default frontend package manager.

The framework also supports using https://pnpm.io[_pnpm_] (also known as _performant npm_). To switch to pnpm you can set the `vaadin.pnpm.enable` system property to `true`.
```

2022-01-11 08:30 UTC, Lodin commented on articles/shared/guide/install/_npm.asciidoc
> +npm is the recommended and default package manager for Vaadin projects.
We could add a link to [https://docs.npmjs.com/cli/v8/commands/npm](npm CLI) here.

2022-01-11 08:30 UTC, Lodin commented on articles/shared/guide/install/_npm.asciidoc
> +npm is the recommended and default package manager for Vaadin projects.
We need to NOTE here that the minimal required npm version is `8.3.0`, and the user should upgrade if they do not have it yet.

2022-01-11 10:47 UTC, haijian-vaadin commented on articles/shared/guide/configuration/_npm-pnpm.asciidoc
> +It's still possible to use pnpm. To switch to pnpm you can set the `vaadin.pnpm.enable` system property to `true`.
Good point, fixed

2022-01-11 10:48 UTC, haijian-vaadin commented on articles/shared/guide/install/_npm.asciidoc
> +npm is the recommended and default package manager for Vaadin projects.
Good point, done

2022-01-11 10:49 UTC, haijian-vaadin commented on articles/shared/guide/install/_npm.asciidoc
> +npm is the recommended and default package manager for Vaadin projects.
It has a NOTE section down below. Users actually don't need 8.3.0, if they don't have duplicated dependencies.

2022-01-11 11:50 UTC, Lodin approved these changes

2022-01-11 11:51 UTC, merged