[WIP] CE - Add documentation for CollaborationList new operations
vaadin/docs pull request #1035
Opened 2022-01-19 14:17 UTC by heruan

## Description

This mentions lists, not just maps, when referring to low-level Topic API. Also, it adds documentation for `CollaborationList` new operations.

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

2022-01-20 10:45 UTC, dougjewsbury commented on articles/ce/advanced/collaboration-list.asciidoc
> +Once you have the list instance, you can insert values at the end of the list with the [methodname]#inserLast# method.
```suggestion
Once you have the list instance, you can insert values at the end of the list with the [methodname]#inserLast()# method.
```

2022-01-20 10:48 UTC, dougjewsbury commented on articles/ce/advanced/collaboration-list.asciidoc
> +Since the insertion is asynchronous, the method returns a result object from which you can get a [classname]#CompletableFuture# that you can use to know when the insertion has been done.
```suggestion
Since the insertion is asynchronous, the method returns a result object from which you can get a [classname]#CompletableFuture# that you can use to determine when the insertion has been done.
```

2022-01-20 10:50 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
> +Build your own collaborative experiences by sharing data in a [classname]#CollaborationMap# and [classname]#CollaborationList# data structures.
```suggestion
Build your own collaborative experiences by sharing data in [classname]#CollaborationMap# and [classname]#CollaborationList# data structures.
```

2022-01-20 10:52 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
>  A topic can be compared to a chat room - it has an identifier (topic id) that is unique in the context of the application and participating members will receive all updates made to any topic that the
```suggestion
A topic can be compared to a chat room; it has an identifier (topic ID) that is unique in the context of the application, and participating members will receive all updates relating to any topic that they are participating in.
```

2022-01-20 10:53 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
>  Topic ids are freeform strings that the developer may choose, like "app" or "contract-126-address".
```suggestion
Topic IDs are free-form strings that the developer may choose, such as "app" or "contract-126-address".
```

2022-01-20 10:59 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
>  When building a topic for a work item, it is a good convention to have the name of the entity, and the identifier for the entity in the topic id.
```suggestion
When building a topic for a work item, it is a good convention to have the name of the entity and the identifier for the entity in the topic ID.
```

2022-01-20 10:59 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
> +For example, if you are making a form for editing a [classname]#Person# entity, and the [classname]#Person# has the id 120, a good topic name would be "person/120".
```suggestion
For example, if you are making a form for editing a [classname]#Person# entity, and the [classname]#Person# has the ID 120, a good topic name would be "person/120".
```

2022-01-20 11:00 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
>  Collaboration Engine includes several high-level APIs that enable the specific use cases of editing a form together and having real-time discussions.
```suggestion
Collaboration Engine includes several high-level APIs that enable the specific use cases of collaboratively editing a form and having real-time discussions.
```

2022-01-20 11:02 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
> +[classname]#CollaborationAvatarGroup# is a component that shows the avatar of each user who is present in a given topic, for example, all the users currently looking at or editing the same item.
```suggestion
[classname]#CollaborationAvatarGroup# is a component that shows the avatar of every user who is present in a given topic, for example all the users currently looking at or editing the same item.
```

2022-01-20 11:05 UTC, dougjewsbury commented on articles/ce/overview.asciidoc
>  It is strongly recommended that shared values are immutable instances since subscribers are notified only when the shared value is replaced with another instance but not when the contents of an exist
```suggestion
It is strongly recommended that shared values should be immutable instances, as subscribers are notified only when the shared value is replaced with another instance, but not when the content of an existing value is updated.
```

2022-01-20 11:14 UTC, dougjewsbury reviewed
Made a few suggestions. Apart from that, it looks good from an AsciiDoc point of view.

2022-01-24 07:36 UTC, heruan commented
Thanks @dougjewsbury for the suggestions! We're waiting for the latest V23 alpha update to finish this.

2022-02-08 09:35 UTC, MatthewVaadin requested changes

2022-02-08 09:35 UTC, MatthewVaadin commented on articles/ce/overview.asciidoc
> +[classname]#CollaborationAvatarGroup# is a component that shows the avatar of every user who is present in a given topic, for example all the users currently looking at or editing the same item.
"item" is a bit vague for an example. Consider replacing with "form".

2022-02-08 09:35 UTC, MatthewVaadin commented on articles/ce/overview.asciidoc
> +Collaboration Managers provide a middle-level API to handle collaborative data in the most common use cases and let developers build their own collaborative logic and custom components:
Consider: Collaboration Managers provide a mid-level API to handle collaborative data for the most common use cases and lets developers build their own collaborative logic and custom components:

2022-02-08 09:35 UTC, MatthewVaadin commented on articles/ce/overview.asciidoc
> +The entry point to using the Topic API is by opening a [classname]#TopicConnection# through [methodname]#CollaborationEngine.getInstance()#.
CollaborationEngine.getInstance() is not directly how you open a TopicConnection. Replace this with a reference to CollaborationEngine.getInstance().openTopicConnection().

2022-02-09 12:37 UTC, heruan commented on articles/ce/overview.asciidoc
> +The entry point to using the Topic API is by opening a [classname]#TopicConnection# through [methodname]#CollaborationEngine.getInstance()#.
Right, changed to `CollaborationEngine::openTopicConnection` which is the correct method reference 👍

2022-02-09 13:12 UTC, MatthewVaadin requested changes

2022-02-09 13:12 UTC, MatthewVaadin commented on articles/ce/overview.asciidoc
> +CollaborationCollaboration Managers provide a mid-level API to handle collaborative data for the most common use cases and lets developers build their own collaborative logic and custom components:
I think something went wrong here - CollaborationCollaboration should just be Collaboration. Also the change from "let" to "lets" is a typo in my review (sorry).

2022-02-09 13:23 UTC, heruan commented on articles/ce/overview.asciidoc
> +CollaborationCollaboration Managers provide a mid-level API to handle collaborative data for the most common use cases and lets developers build their own collaborative logic and custom components:
Yeah, also my bad with copy/paste 😅 Fixed!

2022-02-09 13:24 UTC, MatthewVaadin approved these changes

2022-02-10 18:38 UTC, merged

2022-02-10 18:39 UTC, jouni commented
There seems to be some problem with the preview build, at least occasionally, so I merged this regardless of it.