Update tutorial for V19 which includes CE by default
vaadin/docs pull request #104
Opened 2021-01-13 07:21 UTC by pekam

Porting https://github.com/vaadin/collaboration-engine-internal/pull/481

2021-01-13 13:04 UTC, jouni requested changes

2021-01-13 13:04 UTC, jouni commented on articles/ce/tutorial.asciidoc
> +you need to add Collaboration Engine as a dependency to your project.
I would like to change the content here so that it does not explicitly state any Vaadin versions (applies to the previous “Set Up a Vaadin Project” section as well).

Write it in the way that this feature has always worked with the current latest major version, and that it will always keep working with it. That said, we should annotate new features with the versioning badges: https://github.com/vaadin/docs/wiki/Authoring-articles#indicating-new-and-deprecated-features

If there are some additional things a user needs to do when combined with Vaadin 14, include those in the v14 branch of docs.

In this case, when CE is not part of Vaadin 18, which is still supported for a while, we could keep the installation instructions but mark them as deprecated since V19.

2021-01-18 09:21 UTC, pekam commented on articles/ce/tutorial.asciidoc
> +you need to add Collaboration Engine as a dependency to your project.
Done. Thanks for the great advice!

2021-01-18 11:59 UTC, jouni approved these changes

2021-01-18 12:49 UTC, merged

2021-01-18 12:52 UTC, pekam commented
Normally I'd have waited for someone from the CE team to review as well, but after the latest update there's really nothing CE-specific in these changes.