Docs/map sources docs
vaadin/docs pull request #1064
Opened 2022-02-09 10:49 UTC by sissbruecker

## Description

Adds sections for map sources, markers, as well as the respective demos.

2022-02-09 10:54 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +| https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/component/map/configuration/source/OSMSource.html[OSM]
23.0.0.beta1 API docs are not published yet, so these links are broken for now

2022-02-09 10:54 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/map/MapMarkers.java
> +        Span title = new Span("Map showing Vaadin office locations");
Not very creative, let me know if you have better ideas 🤷

2022-02-09 10:54 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/map/MapSources.java
> +    private static final String WMS_SOURCE = "WMS (using topographical map via mundialis.de)";
Could not find a well-known service that would host a full map (rather than overlay layers) with a WMS. Seems most use XYZ or vector tiles.

2022-02-10 08:50 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +Map provides various sources for loading map data in a specific format from a map service.
Should we be using the phrase _"The map component"_ rather than just _"Map"_ when referring to the component, to distinguish it from other uses in this same doc? (not just in reference to this particular line but other places where _"Map"_ is used to refer to the component)

2022-02-10 08:52 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +Map provides various sources for loading map data in a specific format from a map service.
Perhaps this is less of an issue in the middle of sentences where the capitalization might be sufficient to avoid misunderstandings, but in the beginning of sentences we don't have that distinction either.

2022-02-10 08:53 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +Markers can be displayed on top of a map to indicate something of note.
would suggest the more common _"points of interest"_ rather than _"something of note"_

2022-02-10 08:56 UTC, rolfsmeds requested changes
Very good overall, but see my comments for improvement suggestions.

2022-02-10 09:44 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +Map provides various sources for loading map data in a specific format from a map service.
Makes sense, I also stumbled over this section. Changed this instance. Checked other places, I think it's not as problematic there, and it's consistent with other component docs.

2022-02-10 09:44 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +Markers can be displayed on top of a map to indicate something of note.
Sounds good, changed

2022-02-10 10:35 UTC, jouni commented on articles/ds/components/map/index.asciidoc
> +.Performance Considerations
Heading formatting doesn’t apply to admonition titles.

```suggestion
.Performance considerations
```

2022-02-10 10:35 UTC, jouni commented on articles/ds/components/map/index.asciidoc
> +Icons can be configured either as a URL or a xref:{articles}/flow/advanced/dynamic-content#using-streamresource[StreamResource].
Even though both work, let’s keep the format of cross references consistent.

```suggestion
Icons can be configured either as a URL or a <<{articles}/flow/advanced/dynamic-content#using-streamresource,StreamResource>>.
```

2022-02-10 13:40 UTC, DiegoCardoso approved these changes
LGTM

2022-02-10 14:28 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/map/Icons.java
> +    // For now duplicate all required icons with base64 encoded URL
Considering that we would need an alternative for the default marker anyway, I think it's good enough as it is. It's a super isolated workaround, and it's not hard to comprehend.

2022-02-14 10:12 UTC, merged