feat: v22 to v23 upgrade document
vaadin/docs pull request #1067
Opened 2022-02-10 07:37 UTC by caalador

Closes #1051

2022-02-15 10:28 UTC, tarekoraby commented
To see the changes in the upgrade tool, I believe this PR still needs a couple of lines added to [upgrading/index.adoc](https://github.com/vaadin/docs/edit/latest/articles/upgrading/index.adoc).

Specifically, towards the end of the document, at line 192, the following should be added:
```
[.flow]
--
include::flow/_22-23.adoc[]
--
```

2022-02-16 10:42 UTC, joheriks requested changes

2022-02-16 10:42 UTC, joheriks commented on articles/upgrading/flow/_22-23.adoc
> +To keep using pnpm the configuration pnpm.enable should be set.
Could mention here that the initial run of `npm` without a `package-lock.json` is slow. See https://github.com/vaadin/flow/issues/12825

2022-02-17 07:43 UTC, joheriks commented on articles/upgrading/flow/_22-23.adoc
> +Coming from a project on pnpm will not have a npm package-lock.json as it uses a package-lock.yaml
```suggestion
Coming from a project on pnpm will not have an npm `package-lock.json` as it uses `package-lock.yaml`
```

2022-02-17 10:47 UTC, joheriks commented on articles/upgrading/flow/_22-23.adoc
> +Coming from a project on pnpm will not have an npm `package-lock.json` as it uses `package-lock.yaml`
```suggestion
Coming from a project on pnpm will not have an npm `package-lock.json` as it uses `pnpm-lock.yaml`
```

Sorry, one more.

2022-02-17 14:01 UTC, joheriks approved these changes

2022-02-17 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=1067) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=1067) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: caalador<br/>:x: joheriks<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=1067) it.</sub>

2022-02-24 08:31 UTC, merged