Add note about `vaadin.launch-browser`
vaadin/docs pull request #1096
Opened 2022-02-21 07:32 UTC by tarekoraby

2022-02-21 17:41 UTC, dougjewsbury commented on articles/flow/integrations/spring/configuration.asciidoc
>  The default set of packages does not cover everything that we should not be interested in.
This is rather an uncomfortable double negative. Could we say:
"The default set of packages includes some packages that we are not interested in."?

2022-02-21 17:42 UTC, dougjewsbury commented on articles/flow/integrations/spring/configuration.asciidoc
>  You can set properties for Spring Boot in your [filename]#application.properties`# file.
```suggestion
You can set properties for Spring Boot in your [filename]#application.properties# file.
```

2022-02-22 06:39 UTC, tarekoraby commented on articles/flow/integrations/spring/configuration.asciidoc
>  The default set of packages does not cover everything that we should not be interested in.
The sentence is ambiguous indeed. I rewrote it. Hopefully, it's better now.

2022-03-08 14:28 UTC, joheriks requested changes

2022-03-08 14:28 UTC, joheriks commented on articles/flow/integrations/spring/configuration.asciidoc
> +To speed up the build of projects, Flow automatically excludes a number of packages (such as the ones belonging to the `java` and `springframework` packages) from being scanned.
```suggestion
To decrease the startup time during development as well as the build time for the production bundle, Flow automatically excludes a number of packages (such as the ones belonging to the `java` and `springframework` packages) from being scanned for annotations.
```

2022-03-08 14:28 UTC, joheriks commented on articles/flow/integrations/spring/configuration.asciidoc
> +You can extend this list using the `blacklisted-packages` property, which is a comma-separated string that can be used to blacklist packages from being scanned in npm-mode projects.
```suggestion
You can extend this list using the `vaadin.blacklisted-packages` property, which is a comma-separated string that can be used to exclude packages from being scanned.
```

2022-03-08 14:29 UTC, joheriks commented
Needs rebase.

2022-03-09 09:37 UTC, merged