docs: add layers section for map component
vaadin/docs pull request #1108
Opened 2022-02-22 14:19 UTC by sissbruecker

## Description

Adds a section about layers to the map component docs.

2022-02-22 17:11 UTC, rolfsmeds requested changes

2022-02-22 17:11 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +Invisible layers are simply not rendered.
"Invisible layers are simply not rendered" feels a bit superfluous

2022-02-22 17:11 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +Note that some map services already use a lowered opacity in the map images that they provide, meaning that lowering the opacity of the layer is not needed in this case.
Propose to rephrase this simply as

> Note that map services may provide some layers with a lowered opacity by default.

2022-02-22 17:11 UTC, rolfsmeds commented on articles/ds/components/map/index.asciidoc
> +It is possible to replace the background layer. Custom layers can be added to the map, for example to display overlays.
Proposal to rephrase as:

> The default background layer can be replaced, and additional layers added on top of it, for example to display overlays.

2022-02-22 17:21 UTC, dougjewsbury commented on articles/ds/components/map/index.asciidoc
> +For more fine-grained control of the layer rendering order, a `z-index` can be defined for each layer.
```suggestion
For finer-grained control of the layer rendering order, a `z-index` can be defined for each layer.
```

2022-02-23 09:05 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +It is possible to replace the background layer. Custom layers can be added to the map, for example to display overlays.
Done

2022-02-23 09:05 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +For more fine-grained control of the layer rendering order, a `z-index` can be defined for each layer.
Done

2022-02-23 09:05 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +Invisible layers are simply not rendered.
Yeah, I wanted to hint at the fact that invisible layers do not impact performance, but I guess it's obvious. Removed.

2022-02-23 09:05 UTC, sissbruecker commented on articles/ds/components/map/index.asciidoc
> +Note that some map services already use a lowered opacity in the map images that they provide, meaning that lowering the opacity of the layer is not needed in this case.
Simplified the wording a bit, but used `map data` instead of `layers`, as map services technically don't provide layers, and the map data term is consistent with a previous explanation in the document.

2022-02-23 09:41 UTC, DiegoCardoso requested changes

2022-02-23 09:41 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/map/MapLayers.java
> +        });
I think the snippet can be more focused on the feature. Right now, I believe that there's more than needed to show feature API, like configuring the `RadioButtonGroup`. Maybe only the listener is enough. Same for the second radio button group to configure the layer visibility.

2022-02-23 09:58 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/map/MapLayers.java
> +        });
True, I split up the snippet into multiple ones. However I kept the section in the middle that shows how to add the custom overlay layers.

2022-02-23 10:07 UTC, DiegoCardoso approved these changes
LGTM

2022-02-23 10:07 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/map/MapLayers.java
> +        });
Looks better, now 👍🏻

2022-02-23 10:23 UTC, dougjewsbury reviewed
AsciiDoc looks good.

2022-02-23 17:17 UTC, merged