Add examples for Accordion
vaadin/docs pull request #113
Opened 2021-01-18 09:49 UTC by DiegoCardoso

2021-01-18 10:01 UTC, tomivirkki requested changes

2021-01-18 10:01 UTC, tomivirkki commented on frontend/demo/component/accordion/accordion-summary.ts
> +          @opened-changed="${(e: CustomEvent) => (this.openedPanelIndex = e.detail.value ? 0 : -1)}"
Wouldn't it work to have this for the `<vaadin-accordion>` element instead:
```
.opened=${this.openedPanelIndex}
@opened-changed=${(e: CustomEvent) => (this.openedPanelIndex = e.detail.value)}
```

2021-01-22 11:58 UTC, DiegoCardoso commented on frontend/demo/component/accordion/accordion-summary.ts
> +  ];
Moved to a const.

2021-01-22 11:58 UTC, DiegoCardoso commented on frontend/demo/component/accordion/accordion-summary.ts
> +          @opened-changed="${(e: CustomEvent) => (this.openedPanelIndex = e.detail.value ? 0 : -1)}"
Yeah. It works. Done.

2021-01-22 11:58 UTC, DiegoCardoso commented on frontend/demo/component/accordion/accordion-summary.ts
> +  private items: Country[] = [];
Changed to `countries`.

2021-01-22 15:25 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        ComboBox<Country> countries = new ComboBox<>("Country");
This only shows empty items for some reason.

2021-01-22 15:25 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        TextField lastName = new TextField("Last Name");
nit: Casing is different between the examples.

2021-01-22 15:25 UTC, tomivirkki commented on frontend/demo/component/accordion/accordion-summary.ts
> +  private personBinder = new Binder(this, PersonModel);
nit: Looks like the TS example shows the fields as required while the Java example doesn't.

2021-01-22 15:37 UTC, tomivirkki reviewed
The `section-nav: incomplete` should be removed from the accordion index page's front matter to make the item look enabled in the menu

2021-01-22 18:31 UTC, jouni requested changes
All example UI texts should be using sentence case, not title case. For example: ~~First Name~~ → First name
~~Billing Address~~ → Billing address

2021-01-25 09:08 UTC, DiegoCardoso reviewed
Removed the incomplete tag and adjusted the case.

2021-01-25 09:08 UTC, DiegoCardoso commented on frontend/demo/component/accordion/accordion-summary.ts
> +  private personBinder = new Binder(this, PersonModel);
Removed required from fields.

2021-01-25 09:08 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        ComboBox<Country> countries = new ComboBox<>("Country");
Finally noticed that I forgot to add the connector import at the TS example.

2021-01-25 09:08 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        TextField lastName = new TextField("Last Name");
Fixed.

2021-01-25 09:15 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        ComboBox<Country> countries = new ComboBox<>("Country");
Ah, right. These can be really tricky to catch...I wonder if we could somehow make it more obvious that a Flow-specific client-side import is missing.

2021-01-25 09:25 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        ComboBox<Country> countries = new ComboBox<>("Country");
Yeah. It may affect DX quite badly.

2021-01-25 09:27 UTC, tomivirkki commented on articles/ds/components/accordion/index.asciidoc
> -section-nav: incomplete
The "Work In Progress" box should be removed

2021-01-25 09:28 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        Button paymenButton = new Button("Continue", (e) -> paymentPanel.setOpened(false));
typo "paymenButton"

The Button label should be "Finish"

2021-01-25 09:44 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/accordion/AccordionSummary.java
> +        Button paymenButton = new Button("Continue", (e) -> paymentPanel.setOpened(false));
Done.

2021-01-25 09:44 UTC, DiegoCardoso commented on articles/ds/components/accordion/index.asciidoc
> -section-nav: incomplete
Done.

2021-01-25 09:49 UTC, tomivirkki commented on articles/ds/components/accordion/index.asciidoc
> -section-nav: incomplete
It's still there. Sorry for using this same line (regarding another change) for the comment.

2021-01-25 09:59 UTC, DiegoCardoso commented on articles/ds/components/accordion/index.asciidoc
> -section-nav: incomplete
My bad. I mistakenly thought it was about this line only, but now I got it right (hopefully)

2021-01-25 10:19 UTC, tomivirkki commented
The default snippets in the code examples should contain a minimal amount of source code to highlight the feature being demonstrated.

For example, in the very first TS example, the snippet should only wrap the `<vaadin-accordion>...</vaadin-accordion>`, the summary example should only show the `setSummary` / `slot="summary"` of a single panel (sould we also include the `<vaadin-accordion-panel>` tag in the snippet?)...

2021-01-25 13:39 UTC, DiegoCardoso commented
Changed the code snippets tags.

2021-01-25 14:33 UTC, jouni commented
> Changed the code snippets tags.

Does it actually work like that? I wouldn’t have thought you can use the same name for multiple tags.

In the future, I suggest we use tag exclusions instead, like so:

example.ts
```typescript
// tag::snippet[]
Include me

// tag::inner-snippet[]
Exclude me
// end::inner-snippet[]

Include me as well
// end::snippet[]
```

article.adoc
```asciidoc
[source, TypeScript]
----
include::example.ts[tags="snippet;!inner-snippet"]
----
```

2021-01-26 11:07 UTC, DiegoCardoso commented
> Does it actually work like that? I wouldn’t have thought you can use the same name for multiple tags.

Yeah, it works. I asked Tomi about it and he said it is already being used elsewhere.

2021-01-26 13:03 UTC, tomivirkki commented
> Yeah, it works. I asked Tomi about it and he said it is already being used elsewhere.

I wasn't talking about using the same tag name. I mentioned there are examples with multiple snippets in one file but I think they're all using separate tag names.

2021-01-26 13:53 UTC, DiegoCardoso commented
Ah, okay. I see now.

2021-01-26 13:54 UTC, tomivirkki commented
But if it works, no problem.

2021-01-26 14:28 UTC, tomivirkki approved these changes

2021-01-26 15:49 UTC, jouni approved these changes

2021-01-26 15:50 UTC, merged