Add source control instructions
vaadin/docs pull request #1187
Opened 2022-03-17 11:37 UTC by tarekoraby

Close #1179.

2022-03-17 11:43 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +types.d.ts
I don't know what is the description of `types.d.ts`.

2022-03-17 13:03 UTC, jouni commented on articles/flow/configuration/source-control.adoc
> +====
Is an admonition really needed? I think the content would work fine just as a plain paragraph.

2022-03-18 08:39 UTC, Artur- requested changes

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +└── themes/           <2>
I wonder if it would be clearer to show the actual theme directory inside `themes`?

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +types.d.ts
It can contain additional type definitions used in the project.


Right now it defines that css files are imported as `CSSResultGroup` but that is not important to the user and it will also probably change at some point. It should in almost all Flow cases be considered auto generated on demand and gitignored, just like `tsconfig.json`

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +<6> Holds the metadata related to the project's frontend configuration and dependencies.
Maybe this could say "defines version ranges for frontend dependencies" and <7> would say "Defines the exact versions for frontend dependencies in this project" as "locks the frontend dependencies" is not super clear

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +<8> Project and configuration details used by Maven to build the project.
+ Java dependencies?

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +<10> An auto-generated file holding Flow's default webpack configuration.
```suggestion
<10> An auto-generated file containing the webpack configuration needed for all applications.
```

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +<11> An auto-generated file used to compile the TypeScript code in the project if Lit templates are used.
```suggestion
<11> An auto-generated file that defines the configuration for  compiling TypeScript code in the project, when needed.
```

2022-03-18 08:39 UTC, Artur- commented on articles/flow/configuration/source-control.adoc
> +----
I think `tsconfig.json` and `types.d.ts` could be in this list as they are hardly ever customized and newer Vaadin versions might bring changes. Maybe with a comment to remove from gitignore if you want to customize them

2022-03-18 08:48 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +└── themes/           <2>
Yeah, I thought about that. It would be clearer but also make it more crowded.

2022-03-18 08:59 UTC, joheriks commented on articles/v14-23-upgrade/final-steps/index.adoc
> +Vaadin 23 involves some minor changes in the layout and content of Vaadin projects.
Perhaps say here also that you the migrator is expected to see new files/folder generated in the project (`tsconfig.json`, `types.d.ts`, `frontend/index.html` and `frontend/generated`), then refer to the other section.

2022-03-18 09:00 UTC, joheriks commented on articles/flow/configuration/source-control.adoc
> +└── index.html
Could also say that `index.html` is auto-generated but can be customized (and only in the latter case would we recommend adding it to source control.)

2022-03-18 09:21 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +<8> Project and configuration details used by Maven to build the project.
I'll leave the description on this one as it is. People should know what is a pom.xml. And if they don't, this is not going to be the page to teach them on the topic.

2022-03-18 11:11 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +====
I don't have a strong opinion on this, but I feel that an admonition is more easily noticeable as it highlights the content compared to the above description of the directory structure.

![image](https://user-images.githubusercontent.com/42799254/158992987-b07d45f0-81ea-4064-a09e-24472f0aca33.png)

2022-03-18 11:14 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +└── themes/           <2>
Added the themes substructure

2022-03-18 11:14 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +<6> Holds the metadata related to the project's frontend configuration and dependencies.
Done

2022-03-18 11:20 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +└── index.html
Done. I added a description of `index.html`, and added it to gitignore with a note.

2022-03-18 11:20 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +----
done

2022-03-18 11:21 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +types.d.ts
Description added

2022-03-18 11:22 UTC, tarekoraby commented on articles/v14-23-upgrade/final-steps/index.adoc
> +Vaadin 23 involves some minor changes in the layout and content of Vaadin projects.
>expected to see new files/folder generated in the project (tsconfig.json, types.d.ts, frontend/index.html and frontend/generated)

Are those the only new files in v23 project? What about the `frontend/themes`?

2022-03-18 11:23 UTC, tarekoraby commented on articles/v14-23-upgrade/final-steps/index.adoc
> +Vaadin 23 involves some minor changes in the layout and content of Vaadin projects.
I prefer to keep the note in the upgrade guide not so tightly coupled with the content on the source control page.

2022-03-18 12:24 UTC, joheriks commented on articles/v14-23-upgrade/final-steps/index.adoc
> +Vaadin 23 involves some minor changes in the layout and content of Vaadin projects.
Alright, maybe no need to list the new files. But something concrete reasons why I should go and check this article need to be mentioned here, otherwise I may just skip it.

2022-03-18 12:39 UTC, tarekoraby commented on articles/v14-23-upgrade/final-steps/index.adoc
> +Vaadin 23 involves some minor changes in the layout and content of Vaadin projects.
Eh, apparently I messed above a rebase earlier so I lost what I've added to this page. I pushed a new note just now that says

> Vaadin 23 involves some minor changes in the layout and content of Vaadin projects. Be sure to visit the [Source Control section](http://localhost:8000/flow/configuration/source-control) to check the directory layout of a Vaadin 23 application, and update your version control settings accordingly.

How does that sound?

2022-03-21 07:03 UTC, tarekoraby commented on articles/flow/configuration/source-control.adoc
> +====
Do you have a strong opinion @jouni?

2022-03-21 07:37 UTC, joheriks approved these changes

2022-03-21 09:06 UTC, jouni commented on articles/flow/configuration/source-control.adoc
> +====
No, not a strong opinion. Only that in general, try to keep the number of admonitions low per article.

2022-03-22 06:31 UTC, merged