Move embedded web component theming to embedded docs
vaadin/docs pull request #120
Opened 2021-01-19 15:36 UTC by tanbt

Fixes https://github.com/vaadin/flow/issues/9829

2021-01-19 19:12 UTC, jouni requested changes

2021-01-19 19:12 UTC, jouni commented on articles/flow/embedding/webcomponent-theming.asciidoc
> +include::src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java[tags=embeddedTheme, indent=0, group=Java]
```suggestion
include::{root}/src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java[tags=embeddedTheme, indent=0]
```

Start include paths with `{root}` so that they work no matter where the article is placed in the folder hierarchy. I assume this file does exist, but I didn’t check.

Don’t use `group` unless you have two separate implementations for the same end result (think of a component example, how to create a Text Field, for example).

2021-01-19 19:12 UTC, jouni commented on articles/theming/creating-a-custom-theme.asciidoc
> +See <<{articles}/flow/embedding-flow-applications/tutorial-webcomponent-theming#assigning-a-theme,Theming Embedded Applications>>.
```suggestion
See <<{articles}/flow/embedding/webcomponent-theming#,Theming Embedded Applications>>.
```

2021-01-19 19:12 UTC, jouni commented on articles/theming/creating-a-custom-theme.asciidoc
>  == Theming Embedded Web Components
```suggestion
== Theming Embedded Applications
```

2021-01-19 20:19 UTC, jouni commented on articles/flow/embedding/webcomponent-theming.asciidoc
> +include::src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java[tags=embeddedTheme, indent=0, group=Java]
Ah, actually, this include path was correct before, as it is indeed within the `articles/theming` folder. Should eventually remove those files (during the rewrite of the theming docs).

2021-01-20 06:39 UTC, tanbt commented on articles/theming/creating-a-custom-theme.asciidoc
> +See <<{articles}/flow/embedding-flow-applications/tutorial-webcomponent-theming#assigning-a-theme,Theming Embedded Applications>>.
Ok, so the path is file system path instead of the URL.

2021-01-20 07:38 UTC, jouni requested changes

2021-01-20 07:38 UTC, jouni commented on articles/flow/embedding/theming.asciidoc
> +include::src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java[tags=embeddedTheme, indent=0, group=Java]
```suggestion
include::src/main/java/com/vaadin/flow/tutorial/theme/ThemedComponentExporter.java[tags=embeddedTheme, indent=0]
```

Accidentally reverted this suggestion yesterday. No need to declare a group unless you have two separate implementations for the same use case (e.g. a component example that works the same if you implement it using the Java API or the TypeScript/HTML API).

2021-01-20 07:38 UTC, jouni commented on articles/theming/creating-a-custom-theme.asciidoc
> +See <<{articles}/flow/embedding/webcomponent-theming#,Theming Embedded Applications>>.
```suggestion
See <<{articles}/flow/embedding/theming/#,Theming Embedded Applications>>.
```
The path changed in master yesterday.

2021-01-20 10:38 UTC, jouni approved these changes

2021-01-20 10:42 UTC, merged