docs: document migrating from PolymerTemplate
vaadin/docs pull request #1237
Opened 2022-03-28 08:20 UTC by tomivirkki

Closes #1190

2022-03-28 14:20 UTC, dougjewsbury commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +In trivial cases, it is enough to replace the [classname]`PolymerTemplate` superclass with [classname]`LitTemplate` and then to migrate the `PolymerElement` based client view to base on `LitElement`
```suggestion
In trivial cases, it is enough to replace the [classname]`PolymerTemplate` superclass with [classname]`LitTemplate` and then to migrate the `PolymerElement` based client view to be based on `LitElement` instead.
```

2022-03-28 14:21 UTC, dougjewsbury commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +For example, the [methodname]`getElement().setProperty("propertyName", value)` method can be used for setting primitive property values for the client side view.
```suggestion
For example, the [methodname]`getElement().setProperty("propertyName", value)` method can be used for setting primitive property values for the client-side view.
```

2022-03-28 14:23 UTC, dougjewsbury commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +For this, you can use a <<{articles}/flow/element-api/client-server-rpc#clientcallable-annotation, [classname]`@ClientCallable`>> method.
```suggestion
For this, you can use a <<{articles}/flow/element-api/client-server-rpc#clientcallable-annotation, [annotationname]`@ClientCallable`>> method.
```

2022-03-29 08:00 UTC, joheriks requested changes

2022-03-29 08:55 UTC, tomivirkki commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +----
Done

2022-03-29 08:58 UTC, tomivirkki commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +
Not sure if we want to recommend two different ways of doing this? @Artur- ?

2022-03-29 09:14 UTC, joheriks commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +
I was thinking of it more as a hint than a recommended way. For example, a project may already have some DTOs that could be reused for this purpose (as was the case for Taskmob).

2022-03-29 09:15 UTC, jouni commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +If you use `@Id` for <<{articles}/flow/templates/components#, binding to template components>>, note that the package name should be changed from `com.vaadin.flow.component.polymertemplate.Id` to `co
Feel free to use the recently added `[annotationname]` style when appropriate.

```suggestion
If you use [annotationname]`@Id` for <<{articles}/flow/templates/components#, binding to template components>>, note that the package name should be changed from `com.vaadin.flow.component.polymertemplate.Id` to `com.vaadin.flow.component.template.Id` for [classname]`LitTemplate`.
```

2022-03-29 09:42 UTC, tomivirkki commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +
Ah, got it. Added a note about using DTO.

2022-03-29 10:01 UTC, joheriks commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +    getElement().setProperty("propertyName", value);
Would this actually be a typical case? If the property was updated on the client's initiative, I would think the server wants to do something else than just setting it again on the client. Perhaps something like 
```java
@ClientCallable
public void setProperty(String value) {
    // handle updated property on the server
}
```
so it doesn't look like something one "should do".

2022-03-29 10:36 UTC, tomivirkki commented on articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
> +    getElement().setProperty("propertyName", value);
Done

2022-03-29 11:32 UTC, joheriks approved these changes

2022-03-29 11:32 UTC, merged