Suggest useDeprecatedV14Bootstrapping in essential v14-23 upgrade steps
vaadin/docs pull request #1242
Opened 2022-03-28 12:34 UTC by tarekoraby

Close #1183

2022-03-28 14:36 UTC, dougjewsbury commented on articles/v14-23-upgrade/final-steps/index.adoc
> +see <<{articles}/flow/advanced/modifying-the-bootstrap-page#java-annotations, set of annotations to modify the Bootstrap page>> for more details.
```suggestion
See <<{articles}/flow/advanced/modifying-the-bootstrap-page#java-annotations, set of annotations to modify the Bootstrap page>> for more details.

```

2022-03-29 09:27 UTC, joheriks requested changes

2022-03-29 09:27 UTC, joheriks commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +However, to quickly get your application up and running in Vaadin 23, you can enable the deprecated server-side bootstrapping using the `useDeprecatedV14Bootstrapping` flag.
```suggestion
However, to quickly get your application up and running in Vaadin 23, you can enable the Vaadin 14 server-side bootstrapping using the `useDeprecatedV14Bootstrapping` flag. We describe later in this guide the code changes required to use the new bootstrapping mode.
```

2022-03-29 09:30 UTC, joheriks commented on articles/v14-23-upgrade/final-steps/index.adoc
> +This new model requires that several annotations typically placed on the `MainLayout` / `MainView` class must be moved to a class that implements the `AppShellConfigurator` interface, for example:
As @jouni hinted [here](https://github.com/vaadin/docs/pull/1237#discussion_r837247254), we could use [annotationname]`@PWA` here.

2022-03-29 09:54 UTC, joheriks approved these changes

2022-03-29 09:57 UTC, merged