Feat: Add java constants to utility classes
vaadin/docs pull request #1248
Opened 2022-03-31 08:43 UTC by krissvaa

Add java constants to utility classes from LumoUtility class

For: [flow-components/#2927](https://github.com/vaadin/flow-components/issues/2927)

2022-03-31 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=1248) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=1248) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=1248) it.</sub>

2022-04-01 08:00 UTC, rolfsmeds requested changes
Just some minior nitpicks, otherwise looks good!
(The rewritten usage instructions for Flow are also good to see – much better than the old!)

2022-04-01 08:16 UTC, krissvaa commented on articles/ds/foundation/utility-classes.asciidoc
> +[WARNING,role=small]
Changed to NOTE as that is the closest to Info level:
![image](https://user-images.githubusercontent.com/101052651/161223699-0fe0151e-7932-43e7-aa89-e417000f32fa.png)

2022-04-01 08:32 UTC, rolfsmeds approved these changes

2022-04-01 08:34 UTC, jouni commented on articles/ds/foundation/utility-classes.asciidoc
> +[WARNING,role=small]
IMPORTANT is another alternative, if we want to make it more prominent.

2022-04-04 07:10 UTC, merged