Docs/v23 upgrade guide miscellaneous changes section
vaadin/docs pull request #1250
Opened 2022-03-31 12:16 UTC by rolfsmeds

2022-03-31 12:31 UTC, tomivirkki commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +-  Positive tabindex values (such as `setTabIndex(5)`) are no longer supported on input fields. Doing this will not cause errors, but will simply not have any effect on tab order.
nit: this is already mentioned [here](https://vaadin.com/docs/latest/v14-23-upgrade/essential-steps/#replace-api-usage)

2022-03-31 14:08 UTC, joheriks requested changes

2022-03-31 14:08 UTC, joheriks commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +- Opening a Dialog when a modal Dialog is already open automatically makes the new Dialog a child of the modal Dialog.
Would it make sense to add a sentence of context here in the beginning of this paragraph?. E.g., "Vaadin 23 introduces some changes in how modal components behave" (could later add a link to the page introduced in [this PR](https://github.com/vaadin/docs/pull/1236) further describing the server-side modality concept).

2022-03-31 14:08 UTC, joheriks commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +Closing the modal also closes all its children.
```suggestion
Closing the modal Dialog also closes all its children.

```

2022-04-01 05:24 UTC, tarekoraby commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +-  Positive tabindex values (such as `setTabIndex(5)`) are no longer supported on input fields. Doing this will not cause errors, but will simply not have any effect on tab order.
I think it was removed from the "Replace API Usage" section and moved here.

2022-04-01 05:24 UTC, tarekoraby approved these changes

2022-04-01 05:54 UTC, tarekoraby reviewed
This would close #1178. But I can do it in a separate PR as well.

2022-04-01 05:54 UTC, tarekoraby commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +
```suggestion

- For Vaadin Charts, if [classname]`XAxis` or [classname]`YAxis` are added to a chart, then the ticks of those axes are now hidden by default.
To display the ticks, provide the axes with a tick width greater than 0 using [methodname]`XAxis.setTickWidth()` and [methodname]`YAxis.setTickWidth()`.

```

2022-04-01 06:51 UTC, rolfsmeds commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +-  Positive tabindex values (such as `setTabIndex(5)`) are no longer supported on input fields. Doing this will not cause errors, but will simply not have any effect on tab order.
yup

2022-04-01 07:05 UTC, rolfsmeds commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +- Opening a Dialog when a modal Dialog is already open automatically makes the new Dialog a child of the modal Dialog.
Yes. Rewrote this bullet entirely in a new commit.

2022-04-01 07:40 UTC, tomivirkki commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> +-  Positive tabindex values (such as `setTabIndex(5)`) are no longer supported on input fields. Doing this will not cause errors, but will simply not have any effect on tab order.
Ah, yes, so it seems. The wording was also changed so I didn't realize it was a move. Nevermind.

2022-04-01 08:17 UTC, tarekoraby commented on articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
> ++
```suggestion


```

2022-04-01 09:42 UTC, joheriks approved these changes

2022-04-01 09:43 UTC, merged