feat: Add Vaadin Portlet documentation
vaadin/docs pull request #1283
Opened 2022-04-07 13:43 UTC by mshabarov

Fixes https://github.com/vaadin/portlet/issues/199

2022-04-07 13:57 UTC, jouni requested changes
- Remove the `tutorial-portlet-` prefix from all file names.
- Remove `section-nav: commercial` from all other pages than `index.asciidoc`
- ~~Remove the `overview.asciidoc` page, and move its contents to `index.asciidoc` instead.~~ (edit: didn't notice that this was targeting v14).
- The main page heading in `index.asciidoc` can be "Portlet Support" (instead of "Vaadin Portlet Support").
- `index.asciidoc`: replace the content in the "Topics" section with the `section_outline::[]` macro. Move the summary texts to the `description` front matter attribute of the corresponding page.
  - For example, in `creating-vaadin-portlets.asciidoc`, add `description: Instructs the reader on how to build their own Vaadin Portlets and how to run it.`.
- Address Vale errors and warnings, for example, add `Liferay` to [`accept.txt`](https://github.com/vaadin/docs/blob/latest/.github/styles/Vocab/Docs/accept.txt)

2022-04-07 14:36 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +- Your objective is to integrate the new Vaadin Portlet module into the target project, so that you can build and deploy all Vaadin Portlet modules as separate wars together with a shared static asse
```suggestion
- you have an existing Vaadin Portlet multi-module project containing a bundle module and one or more Vaadin Portlet modules, as described in <<tutorial-portlet-creating-multi-module-portlet-project.asciidoc#,Creating Multi-Module Portlet Project>>; and
- you have a Vaadin Portlet module (either built from scratch or based on `base-starter-flow-portlet`); and
- your objective is to integrate the new Vaadin Portlet module into the target project, so that you can build and deploy all Vaadin Portlet modules as separate `WARs` together with a shared static asset `WAR`.
```

2022-04-07 14:40 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +Then register `myproject-newportlet` as a submodule in `myproject/pom.xml`:
```suggestion
Then register `myproject-newportlet` as a submodule in [filename]#myproject/pom.xml#:
```

2022-04-07 14:41 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +Also update the parent property in the portlet module's `pom.xml` to refer to the target project:
```suggestion
Also, update the parent property in the portlet module's [filename]#pom.xml# to refer to the target project:
```

2022-04-07 14:42 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +In the `pom.xml` of your bundle module (here `myproject/myproject-bundle/pom.xml`), add the new Portlet Module artifact under `<dependencies>` with classifier `classes`:
```suggestion
In the [filename]#pom.xml# of your bundle module (here, [filename]#myproject/myproject-bundle/pom.xml#), add the new Portlet Module artifact under `<dependencies>` with classifier `classes`:
```

2022-04-07 14:44 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +First remove the entire `vaadin-maven-plugin` section from `pom.xml` (`artifactId` may alternatively be `flow-maven-plugin` depending on your configuration):
```suggestion
First, remove the entire `vaadin-maven-plugin` section from [filename]#pom.xml# (`artifactId` may alternatively be `flow-maven-plugin`, depending on your configuration):
```

2022-04-07 14:44 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +Next, under the `maven-war-plugin` of `pom.xml`, remove the entire execution with id `static-files`:
```suggestion
Next, under the `maven-war-plugin` of [filename]#pom.xml#, remove the entire execution with id `static-files`:
```

2022-04-07 14:45 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +In the `pom.xml` of the added portlet module, enable `<attachClasses>`:
```suggestion
In the [filename]#pom.xml# of the added portlet module, enable `<attachClasses>`:
```

2022-04-07 15:13 UTC, dougjewsbury reviewed
The AsciiDoc looks generally good, except for:
formatting using [filename]#...#, [classname]`...`, etc.
using `WAR`, rather than war
avoiding using directional terms such as "above" and "below", in the interests of accessibility for screen-reader users.

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +. Add `@Inject`, scope annotations and other CDI features in your code
```suggestion
. Add an empty [filename]#beans.xml# configuration file
. Use the [classname]`VaadinCdiPortlet` class as the base class for your portlet
. Add [annotationname]`@Inject`, scope annotations and other CDI features in your code
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +Add the following to your portlet project's `pom.xml`:
```suggestion
Add the following to your portlet project's [filename]#pom.xml#:
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The second step is to add the file `/src/main/webapp/WEB-INF/beans.xml` in your Vaadin Portlet application with the following contents:
```suggestion
The second step is to add the file [filename]#/src/main/webapp/WEB-INF/beans.xml# in your Vaadin Portlet application with the following contents:
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +For a quick overview about the `bean.xml` read "What is bean.xml and why do I need it" in http://www.cdi-spec.org/faq[CDI's frequently asked questions].
```suggestion
For a quick overview of the [filename]#bean.xml#, read "What is bean.xml and why do I need it?" in http://www.cdi-spec.org/faq[CDI's frequently asked questions].
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The first step in enabling CDI is to replace the base class of your Vaadin Portlet (`VaadinPortlet`) with `VaadinCdiPortlet`.
```suggestion
The first step in enabling CDI is to replace the base class of your Vaadin Portlet ([classname]`VaadinPortlet`) with [classname]`VaadinCdiPortlet`.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +For example, updating `BookListPortlet`:
```suggestion
For example, updating [classname]`BookListPortlet`:
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The CDI framework allows injection of objects with a well-defined, container-managed lifecycle (called *managed beans*) into any class (including Vaadin components) by simply annotating the correspon
```suggestion
The CDI framework allows injection of objects with a well-defined, container-managed lifecycle (called *managed beans*) into any class (including Vaadin components) by simply annotating the corresponding field with [annotationname]`@Inject`.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The root Vaadin component of your Vaadin Portlet application is the one passed as a type parameter to the `CdiVaadinPortlet` when subclassing it  (`BookListView` above).
```suggestion
The root Vaadin component of your Vaadin Portlet application is the one passed as a type parameter to the [classname]`CdiVaadinPortlet` when sub-classing it  ([classname]`BookListView` in this example).
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +In the above example, the child component of type `BookGrid` is injected the root component `BookListView`.
```suggestion
In this example, the child component of type [classname]`BookGrid` is injected the root component [classname]`BookListView`.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +Initialization code that depends on bean resolution should be placed in a `@PostConstruct`-annotated method, not in the constructor.
```suggestion
Initialization code that depends on bean resolution should be placed in a [annotationname]`@PostConstruct`-annotated method, not in the constructor.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +In the above case, the type of each field determines which predefined bean gets injected.
```suggestion
In the example case, the type of each field determines which predefined bean gets injected.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +`I18NProvider` is Vaadin's mechanism for introduction localization object into your application.
```suggestion
[classname]`I18NProvider` is Vaadin's mechanism for introducing a localization object into your application.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +You can have your own `I18NProvider` subclass automatically instantiated as a managed bean when using Vaadin Porlet CDI.
```suggestion
You can have your own [classname]`I18NProvider` subclass automatically instantiated as a managed bean when using Vaadin Porlet CDI.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +As with Vaadin CDI for servlet applications, the class also needs to be annotated with `@VaadinServiceEnabled` for the Vaadin service to pick it up.
```suggestion
As with Vaadin CDI for servlet applications, the class also needs to be annotated with [annotationname]`@VaadinServiceEnabled` for the Vaadin service to pick it up.
```

2022-04-07 15:13 UTC, dougjewsbury commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The scope ensures that there will be only one `I18NProvider` shared amongst all the views of your portlet application.
```suggestion
The scope ensures that there will be only one [classname]`I18NProvider` shared amongst all the views of your portlet application.
```

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +In the new portlet module, ensure that the file `src/main/resources/META-INF/VAADIN/config/flow-build-info.json` exists and has the following contents:
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +For portlets running in Liferay 7, it shall be:
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +As this is a relative url it will target 127.0.0.1:8080.
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +This should use the correct known url of the bundle. For instance localhost on port 80 would be
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +=== Package and Deploy the war Files
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +After the Maven build, a war file is created in the target folder of each portlet module as well as in the bundle module: `myproject-bundle/target/myproject-bundle.war`, `myproject-oldportlet/target/
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +== 2. Adding a New Vaadin Portlet Module to Non-Vaadin Multi-Module Project
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +- Your objective is to integrate the Vaadin Portlet module into the target project, so that you can build a portlet war and a static asset war for the Vaadin Portlet module.
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +=== Ensure that the New Portlet Module Builds Bundle and Portlet war Files
Done

2022-04-08 06:01 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +Ensure that the Vaadin Portlet `pom.xml` contains the `vaadin-maven-plugin` and two executions in the `maven-war-plugin` for building both the static asset bundle war and the portlet war.
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +To use a custom bundle name, you must add a `flow-build-info.json` file containing the static asset URL as explained in <<module-configuration>>.
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +=== Package and Deploy the war Files
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-adding-portlet-module.asciidoc
> +After the Maven build, two war files are created: `myproject-bundle/target/vaadin-portlet-static.war` and  `myproject-newportlet/target/myproject-newportlet.war`.
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +. Add `@Inject`, scope annotations and other CDI features in your code
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +Add the following to your portlet project's `pom.xml`:
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The second step is to add the file `/src/main/webapp/WEB-INF/beans.xml` in your Vaadin Portlet application with the following contents:
Done

2022-04-08 06:02 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +For a quick overview about the `bean.xml` read "What is bean.xml and why do I need it" in http://www.cdi-spec.org/faq[CDI's frequently asked questions].
Done

2022-04-08 06:05 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The first step in enabling CDI is to replace the base class of your Vaadin Portlet (`VaadinPortlet`) with `VaadinCdiPortlet`.
Done

2022-04-08 06:05 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +For example, updating `BookListPortlet`:
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The CDI framework allows injection of objects with a well-defined, container-managed lifecycle (called *managed beans*) into any class (including Vaadin components) by simply annotating the correspon
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The root Vaadin component of your Vaadin Portlet application is the one passed as a type parameter to the `CdiVaadinPortlet` when subclassing it  (`BookListView` above).
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +In the above example, the child component of type `BookGrid` is injected the root component `BookListView`.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +Initialization code that depends on bean resolution should be placed in a `@PostConstruct`-annotated method, not in the constructor.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +In the above case, the type of each field determines which predefined bean gets injected.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +`I18NProvider` is Vaadin's mechanism for introduction localization object into your application.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +You can have your own `I18NProvider` subclass automatically instantiated as a managed bean when using Vaadin Porlet CDI.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +As with Vaadin CDI for servlet applications, the class also needs to be annotated with `@VaadinServiceEnabled` for the Vaadin service to pick it up.
Done

2022-04-08 06:06 UTC, mshabarov commented on articles/flow/integrations/portlet/tutorial-portlet-cdi-support.asciidoc
> +The scope ensures that there will be only one `I18NProvider` shared amongst all the views of your portlet application.
Done

2022-04-08 06:08 UTC, mshabarov commented
@dougjewsbury thanks a lot for suggestions! I've addressed them all, however, since I pushed earlier updates, commit button was unavailable, so I applied them manually. Sorry for inconvenience.

2022-04-08 07:36 UTC, caalador commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +`VaadinPortlet` and `VaadinLiferayPortlet` are a generic classes and take the selected view class as a type parameter.
```suggestion
* A **portlet class**, which `VaadinPortlet` or `VaadinLiferayPortlet` (when running in Liferay)
+
The portlet class acts as the entry point for our Vaadin Portlet application.
It serves a similar function to a Servlet, but in portlet context.
* A portlet **view class**, which extend `Component`
+
The view class, that can be any normal Vaadin component, contains the contents of our Vaadin Portlet.
You could use an existing component through extension, composition, or as-is.
Or just create an entirely new component for your Vaadin Portlet.
`VaadinPortlet` and `VaadinLiferayPortlet` are a generic classes and take the selected view class as a type parameter.
```

2022-04-08 07:36 UTC, caalador commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +This allows for more complex scenarios where multiple portlets come from separate war files.
Add link to `multi-module-portlets`?

2022-04-08 07:36 UTC, caalador commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +* Pass the value `/vaadin-static-resources/` (for *Liferay Portal*, it would be `/o/vaadin-portlet-resources/`) via the application property to the Vaadin application, that is, on TomCat web server y
```suggestion
* Pass the value `/vaadin-static-resources/` (for *Liferay Portal*, it would be `/o/vaadin-portlet-resources/`) via the application property to the Vaadin application, that is, on Tomcat web server you would:
```

2022-04-08 11:14 UTC, mshabarov commented on articles/flow/integrations/portlet/cdi-support.asciidoc
> +The value of `vaadin.portlet.version` property should match the version of the used `vaadin.portlet` dependency.
Do you mean the case when in multi-module project some of the modules use CDI and some of them not?

2022-04-08 11:17 UTC, mshabarov commented on articles/flow/integrations/portlet/cdi-support.asciidoc
> +The value of `vaadin.portlet.version` property should match the version of the used `vaadin.portlet` dependency.
Would this be better:
In the multi-portlet projects, the value of `vaadin.portlet.version` property should match the version of the used `vaadin.portlet` dependency.

2022-04-08 11:20 UTC, mcollovati commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +We can both register event listeners and mutate the portlet's state through `PortletView` object.
Should it be `through PortletViewContext object`?

2022-04-08 11:20 UTC, mcollovati commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +`PortletView`'s method `onPortletViewContextInit(PortletViewContext)` provides the implementing class a reference to a `PortletViewContext` object, which allows us to register listeners and change th
Seems like first code block does not end completely. Maybe a space is needed before **'s** in "`PortletView`'s method" ?
![image](https://user-images.githubusercontent.com/4648894/162425142-421a7e67-8708-4953-a4bf-564d3250f1ad.png)

2022-04-08 11:20 UTC, mcollovati commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +    // we check that the event name is correct and that the contact exists.
"event name"? Do you mean "parameter name"?

2022-04-08 11:28 UTC, mshabarov commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +    <version>1.0.0</version>
For v14 it won't be added. For v23 it will, but it would be a separate forward port work/PR

2022-04-08 11:30 UTC, mshabarov commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +The portlet.xml serves the same purpose as servlet.xml does for servlets.
Yes, should be `web.xml`, thanks

2022-04-08 11:33 UTC, jouni approved these changes
Approving the changes based on my request (file names, overview section outline, etc.)

2022-04-08 11:35 UTC, mshabarov commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +This allows for more complex scenarios where multiple portlets come from separate war files.
Added

2022-04-08 11:47 UTC, jouni commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +`PortletView`'s method `onPortletViewContextInit(PortletViewContext)` provides the implementing class a reference to a `PortletViewContext` object, which allows us to register listeners and change th
Yeah, that is a special syntax in AsciiDoc to create an apostrophe character. 
```suggestion
The [methodname]`onPortletViewContextInit(PortletViewContext)` in the [interface]`PortletView` interface provides the implementing class a reference to a [classname]`PortletViewContext` object, which allows us to register listeners and change the portlet's state.
```

2022-04-11 08:38 UTC, mshabarov commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +`VaadinPortlet` and `VaadinLiferayPortlet` are a generic classes and take the selected view class as a type parameter.
Done

2022-04-11 08:44 UTC, mshabarov commented on articles/flow/integrations/portlet/creating-vaadin-portlets.asciidoc
> +
Done

2022-04-11 08:45 UTC, mshabarov commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +We can both register event listeners and mutate the portlet's state through `PortletView` object.
Yes, done

2022-04-11 08:48 UTC, mshabarov commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +    // we check that the event name is correct and that the contact exists.
Should be contact id apparently

2022-04-11 08:54 UTC, mshabarov commented on articles/flow/integrations/portlet/demo-address-book.asciidoc
> +    // we check that the event name is correct and that the contact exists.
Done

2022-04-11 09:12 UTC, mcollovati approved these changes

2022-04-11 09:36 UTC, merged