docs: add Dialog header/footer sections
vaadin/docs pull request #1307
Opened 2022-04-13 12:03 UTC by DiegoCardoso

- Update Dialog documentation page to add sections for header and
footer.
- Refactor other examples to use the new API

2022-04-13 12:05 UTC, DiegoCardoso reviewed
Keeping it as draft since we need the next alpha release.

2022-04-13 12:05 UTC, DiegoCardoso commented on articles/ds/components/dialog/index.asciidoc
> +It is recommended to make non-modal Dialogs draggable so that the user can interact with content that might otherwise be obscured by the Dialog.
There's one item here under discussion on the draft doc that was not added yet.

2022-04-13 13:49 UTC, jouni reviewed
I’m unsure if we want to capitalize all occurrences of "Dialog" and "Dialogs". Seems a bit excessive and distracting to me. I’d try to limit that to places where we explicitly say "the Dialog component".

2022-04-13 13:49 UTC, jouni commented on articles/ds/components/dialog/index.asciidoc
>  = Dialog
Never put any content/attributes/config before the main page heading. That messes up the placement of the TOC in the website. Might be worth a lint error…

```suggestion
= Dialog
:experimental:
```

2022-04-13 13:49 UTC, jouni commented on articles/ds/components/dialog/index.asciidoc
> +----
This file is unnecessary now, isn't it?

2022-04-13 14:00 UTC, DiegoCardoso commented on articles/ds/components/dialog/index.asciidoc
> +----
Good catch! Removed.

2022-04-13 14:42 UTC, dougjewsbury commented on articles/ds/components/dialog/index.asciidoc
> +Modal Dialogs don't benefit from being draggable as their modality curtain (the dark overlay behind the dialog) obscures the underlying user interface.
```suggestion
Modal Dialogs do not benefit from being draggable, as their modality curtain (the dark overlay behind the dialog) obscures the underlying user interface.
```

2022-04-13 14:43 UTC, dougjewsbury commented on articles/ds/components/dialog/index.asciidoc
> +Buttons for closure actions such as _Save_, _Cancel_, _Delete_ etc should be placed in the footer.
```suggestion
Buttons for closure actions, such as _Save_, _Cancel_, _Delete_, etc., should be placed in the footer. 
```

2022-04-14 05:58 UTC, rolfsmeds approved these changes
LGTM. I presume the parts about server-side modality were excluded since they don't have anything to do with header + footer?

2022-04-14 05:58 UTC, rolfsmeds commented on articles/ds/components/dialog/index.asciidoc
> +It is recommended to make non-modal Dialogs draggable so that the user can interact with content that might otherwise be obscured by the Dialog.
Which is that?

2022-04-14 07:50 UTC, DiegoCardoso commented on articles/ds/components/dialog/index.asciidoc
> +It is recommended to make non-modal Dialogs draggable so that the user can interact with content that might otherwise be obscured by the Dialog.
It's not exactly here, but before the paragraph which starts with "Any component...". to add this:

> The default areas from which a Dialog can be dragged depend on whether the built-in header is used:
> - If the built-in header or footer is used, they function as the Dialog’s default drag handles
> - Without the built-in header, any empty space within the dialog functions as a drag handle

2022-04-14 07:52 UTC, DiegoCardoso commented
> LGTM. I presume the parts about server-side modality were excluded since they don't have anything to do with header + footer?

Yeah, I didn't add it because I wasn't sure if it should be added here or later. But I can add it, if it's ok.

2022-04-14 08:09 UTC, rolfsmeds commented
> > LGTM. I presume the parts about server-side modality were excluded since they don't have anything to do with header + footer?
> 
> Yeah, I didn't add it because I wasn't sure if it should be added here or later. But I can add it, if it's ok.

No strong opinion either way :)

2022-04-14 08:14 UTC, rolfsmeds commented on articles/ds/components/dialog/index.asciidoc
> +It is recommended to make non-modal Dialogs draggable so that the user can interact with content that might otherwise be obscured by the Dialog.
I think it's good enough as it is now. But I think I would move the examples down a bit, just before the paragraph starting with "It is recommended to make non-modal Dialogs draggable..."

2022-04-14 08:31 UTC, DiegoCardoso commented on articles/ds/components/dialog/index.asciidoc
> +It is recommended to make non-modal Dialogs draggable so that the user can interact with content that might otherwise be obscured by the Dialog.
Done.

2022-04-14 08:40 UTC, web-padawan requested changes

2022-04-14 08:40 UTC, web-padawan commented on frontend/demo/component/dialog/dialog-draggable.ts
> +      <!-- tag::snippet1[] -->
The build fails with an error, please fix:

```
warn /Users/serhii/vaadin/docs/articles/ds/components/dialog/index.asciidoc, line 3 - detected unclosed tag 'snippet1' starting at line 29 of include file: /Users/serhii/vaadin/docs/frontend/demo/component/dialog/dialog-draggable.ts
```

2022-04-14 08:55 UTC, DiegoCardoso commented on frontend/demo/component/dialog/dialog-draggable.ts
> +      <!-- tag::snippet1[] -->
Done.

2022-04-14 09:00 UTC, web-padawan commented on frontend/demo/component/dialog/dialog-footer.ts
> +  };
This seems to be unused - as the `.renderer` is set to inline arrow function. Should it be removed?

2022-04-14 09:01 UTC, web-padawan commented on frontend/demo/component/dialog/dialog-no-padding.ts
> +import '@vaadin/button';
There is an import for '@vaadin/button' above, so this one can be removed.

2022-04-14 09:12 UTC, DiegoCardoso commented on frontend/demo/component/dialog/dialog-footer.ts
> +  };
Good catch. Removed.

2022-04-14 09:12 UTC, DiegoCardoso commented on frontend/demo/component/dialog/dialog-header.ts
> +    console.log('got here', this.user, this.dialogOpened);
🤦🏻‍♂️  removed.

2022-04-14 09:12 UTC, DiegoCardoso commented on frontend/demo/component/dialog/dialog-no-padding.ts
> +import '@vaadin/button';
Removed.

2022-04-14 09:33 UTC, web-padawan approved these changes

2022-04-14 09:33 UTC, merged