chore: remove unnecessary suffix from @vaadin/flow-frontend imports
vaadin/docs pull request #131
Opened 2021-01-22 21:33 UTC by haijian-vaadin

The flow-frontend has an [index.ts](https://github.com/vaadin/flow/blob/master/flow-client/src/main/resources/META-INF/resources/frontend/index.ts) file which exports the content from `Flow`, `Connect`, `Authentication` and `ConnectionIndicator`. So these suffixes are not necessary.

Related to https://github.com/vaadin/flow/issues/7419

2021-01-25 10:41 UTC, jouni commented on articles/fusion/advanced/client-middleware.asciidoc
> +NOTE: If you modify the middlewares array, only calls initiated after the modification use the new middlewares array.
```suggestion
.Modifying middleware at runtime
[CAUTION]
If you modify the middlewares array, only calls initiated after the modification use the new middlewares array. 
```

Always try to provide a summarizing title for admonitions (I’m not sure my suggestion is correct). Also, here I think "caution" could be used to give it more emphasis.

2021-01-25 10:41 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +Now `my-view` is accessible via the root path, that is `http://localhost:8080/`. All the other routes are handled by the server-side router.
```suggestion
Now `my-view` is accessible via the root path, that is `http://localhost:8080/`.
All the other routes are handled by the server-side router. 
```

2021-01-25 10:41 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +NOTE: When adding `index.ts` or `index.html` for the first time, the application server needs to be restarted to update the entry point and the bootstrap template.
```suggestion
.Server restart is required
[NOTE]
When adding `index.ts` or `index.html`, the application server needs to be restarted to update the entry point and the bootstrap template.
```

I’m not sure the use of admonition/note here is needed. If you feel it is, please add a summarizing title.

I don’t “for the first time” is needed, as you can’t add those files more than once, can you? Or is there more nuance in this, like that if you first add `index.ts` and then restart the server, and if you then add `index.html` server restart is not needed?

2021-01-25 10:41 UTC, jouni commented on articles/fusion/routing/nested-views.asciidoc
> +You can use the `<vaadin-app-layout>` component:
```suggestion
You can use the <<{articles}/ds/components/app-layout#,App Layout>> component:
```

2021-01-25 19:13 UTC, haijian-vaadin commented on articles/fusion/application/basics.asciidoc
> +NOTE: When adding `index.ts` or `index.html` for the first time, the application server needs to be restarted to update the entry point and the bootstrap template.
very good observation! Thanks for the suggestion, I think it's better.

2021-01-26 15:10 UTC, platosha approved these changes

2021-01-26 19:43 UTC, jouni requested changes

2021-01-26 19:43 UTC, jouni commented on articles/fusion/advanced/typescript-client.asciidoc
> +Along with the default TypeScript client, the Vaadin maven plugin is capable of generating specific modules for each Vaadin endpoint defined in the backend part.
```suggestion
Along with the default TypeScript client, the Vaadin Maven plugin is capable of generating specific modules for each Vaadin endpoint defined in the backend part.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +Refreshing browser is enough to get the updates.
```suggestion
Refreshing the browser is enough to see the updates in the application.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +During the development time, Vaadin scans the backend code and generates TypeScript code which can call corresponding Java methods.
```suggestion
Vaadin scans the backend code during development and generates TypeScript code which can call the corresponding Java methods.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +The generated code are processed through the same build chain as other TypeScript views.
```suggestion
The generated code is processed through the same way as other TypeScript views.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/basics.asciidoc
> +Only necessary code are bundled for your application in production mode. See <<accessing-backend#, Accessing backend from TypeScript>> for more information.
```suggestion
Only the necessary code is included in the production application bundle. See <<accessing-backend#, Accessing backend from TypeScript>> for more information.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +A default `index.html` / `index.ts` pair is generated during the build, and loads the server-side `UI` when the app starts.
```suggestion
A default `index.html` / `index.ts` pair is generated during the build, and loads the server-side `UI` when the application starts.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +If there is a need to add a client-side view to the application later, you can do it incrementally, with minimal modifications.
```suggestion
Client-side views can be added incrementally to the application later, with minimal modifications.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +This might reduce the first-loading time compared to the Vaadin 10–14 bootstrapping method which loads a full Vaadin application on the first request.
```suggestion
Client-side routing can improve the first load/startup of the application, by minimizing the content delivered to the browser on initial load.
```
I don’t think we need to talk negatively about Vaadin 10–14 bootstrapping. Let’s just point out the benefit of using client-side routes.

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +As a result, the first request loads promptly and that improves the first interaction experience.
```suggestion
```
Redundant

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +When using client-side bootstrapping, Vaadin servlet uses the `frontend/index.html` file as a template to generate the bootstrap page response.
```suggestion
When using client-side bootstrapping, the Vaadin servlet uses the `frontend/index.html` file as a template to generate the bootstrap page response. 
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +It processes the template and injects the following information:
```suggestion
The servlet processes the template and injects the following information:
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +  That is required for relative links in the app view templates to work correctly.
```suggestion
  That is required for relative links in view templates to work correctly.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +  It uses a pre-configured link:https://webpack.js.org/[Webpack^] instance that's included together with `vaadin-maven-plugin` as a module bundler.
```suggestion
  It uses a pre-configured link:https://webpack.js.org/[webpack^] instance that's included together with `vaadin-maven-plugin` as a module bundler. 
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +  Therefore, in the `frontend/index.html` template there is no need to include the `index.ts` (or `index.js`) script manually.
```suggestion
  Therefore, the `frontend/index.html` template does not need to include the `index.ts` (or `index.js`) script explicitly.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +The generated files starts the application so that it uses only server-side routing.
```suggestion
In that case the application uses server-side routing only.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +NOTE: The auto-generated bootstrap template works best for server-side applicaitons.
```suggestion
.The defaults are best for Flow applications
[NOTE]
The autogenerated bootstrap template works best for server-side applications. 
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/application/starting.asciidoc
> +To add client-side views into the app, please follow the  <<quick-start-guide#step-3, Quick Start Guide>>.
```suggestion
To add client-side views into the application, follow the <<quick-start-guide#step-3, Quick Start Guide>>.
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/routing/nested-views.asciidoc
> +With server-side main layout in Java, these are automatically applied for convenience.
```suggestion
With a server-side main layout in Java, these are automatically applied for convenience. 
```

2021-01-26 19:43 UTC, jouni commented on articles/fusion/routing/nested-views.asciidoc
> +With TypeScript main layout, though, they need to be imported manually to make sure consistent styling between server-side and client-side views.
```suggestion
With a client-side main layout in TypeScript, they need to be imported manually to get consistent styling between server-side and client-side views.
```

2021-01-27 07:17 UTC, haijian-vaadin commented on articles/fusion/application/starting.asciidoc
> +This might reduce the first-loading time compared to the Vaadin 10–14 bootstrapping method which loads a full Vaadin application on the first request.
good point

2021-01-27 16:06 UTC, platosha approved these changes

2021-01-28 12:32 UTC, jouni approved these changes

2021-01-28 12:32 UTC, merged