feat: add spreadsheet documentation
vaadin/docs pull request #1333
Opened 2022-04-25 06:41 UTC by yuriy-fix

2022-04-25 08:26 UTC, jouni reviewed
The main `spreadsheet.png` image looks like it’s still using the FontAwesome icons.

2022-04-25 11:28 UTC, jouni commented on articles/ds/components/spreadsheet/index.asciidoc
> +You can create popup buttons for a row of cells in a cell range by defining a table, as described in link:https://vaadin.com/docs/v8/spreadsheet/spreadsheet-table#spreadsheet.table[Tables Within Spre
Are these popups supported yet? At least the link to Vaadin 8 docs needs to be removed.

2022-04-27 09:01 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +If you have an Apache POI workbook created otherwise, you can wrap it toSpreadsheet with the respective constructor.
Can the meaning be made clearer?

2022-04-27 09:02 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +However, if you make modifications to the workbook, you must allow the spreadsheet update itself by calling appropriate update methods for the modified element or elements.
```suggestion
However, if you make modifications to the workbook, you must allow the spreadsheet to update itself by calling appropriate update methods for the modified element or elements.
```

2022-04-27 09:04 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +If you have an Apache POI workbook created otherwise, you can wrap it toSpreadsheet with the respective constructor.
Can the meaning of this sentence be made clearer?

2022-04-27 09:04 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +However, if you make modifications to the workbook, you must allow the spreadsheet update itself by calling appropriate update methods for the modified element or elements.
```suggestion
However, if you make modifications to the workbook, you must allow the spreadsheet to update itself by calling appropriate update methods for the modified element or elements.
```

2022-04-27 09:05 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +You can define panes of rows and columns that are frozen in respect to scrolling.
```suggestion
You can define panes of rows and columns that are frozen when scrolling.
```

2022-04-27 09:07 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +For a detailed example for managing cell comments, we refer to the `InsertDeleteCellCommentAction` and `EditCellCommentAction` classes employed by the default action handler.
Can the meaning of this sentence be made clearer?

2022-04-27 09:10 UTC, dougjewsbury commented on articles/ds/components/spreadsheet/index.asciidoc
> +You can add a popup button with any of the `setPopup()` methods for different cell addressing forms.
Can it be made clearer what "different cell addressing forms" refers to?

2022-06-02 10:10 UTC, manolo requested changes

2022-06-02 10:10 UTC, manolo commented on articles/ds/components/index.asciidoc
> +include::spreadsheet/index.asciidoc[tag=description]
does the `spreadsheet/index.asciidoc` exist? at leas not in this branch

2022-09-07 11:16 UTC, jouni commented
Closing as stale (keeping the branch available for now).

2022-09-07 11:16 UTC, closed without merging