Suggest to cache the requestAccess result
vaadin/docs pull request #136
Opened 2021-01-25 11:16 UTC by heruan

Suggest to cache the requestAccess result.

2021-01-25 12:31 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +TIP: To avoid calling this method multiple times per user, it is suggested to cache the result during the login process (e.g. in the servlet session).
Is admonition really necessary here? I would make it a regular paragraph.

2021-01-26 07:55 UTC, pekam commented on articles/ce/going-to-production.asciidoc
> +TIP: To avoid calling this method multiple times per user, it is suggested to cache the result during the login process (e.g. in the servlet session).
I think it's fine. It's technically a "tip". By using the tip admonition, it becomes something that can be easily skipped.

2021-01-26 07:58 UTC, pekam commented on articles/ce/going-to-production.asciidoc
> +TIP: To avoid calling this method multiple times per user, it is suggested to cache the result during the login process (e.g. in the servlet session).
```suggestion
TIP: To avoid calling this method multiple times per user, it is suggested to cache the result during the login process (e.g. in the session).
```

2021-01-26 08:06 UTC, pekam approved these changes

2021-01-26 13:16 UTC, pekam commented
@jouni can you merge this? I guess it's hanging because of the forked repo.

2021-01-26 19:04 UTC, jouni commented
Yeah, the vale-action has a limitation (it’s a limitation for all GH actions), that it’s doesn’t work with PRs from forks: https://github.com/errata-ai/vale-action#limitations

2021-01-26 19:05 UTC, jouni requested changes

2021-01-26 19:05 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +TIP: To avoid calling this method multiple times per user, it is suggested to cache the result during the login process (e.g. in the session).
```suggestion
.Cache the results
[TIP]
To avoid calling this method multiple times per user, it is suggested to cache the result during the login process, for example, in the session.
```

2021-01-27 13:40 UTC, pekam approved these changes

2021-01-27 14:27 UTC, pekam commented
@jouni, in case you didn't notice, you are blocking this PR.

2021-01-28 12:45 UTC, jouni commented
Yeah, sorry for taking a while to get back to this. Too many reviews to attend to 😅

2021-01-28 12:45 UTC, jouni approved these changes

2021-01-28 12:45 UTC, merged

2021-01-28 12:50 UTC, pekam commented
No worries, thanks! :)