CE: Mention that you can use ValueChangeMode for eagerness
vaadin/docs pull request #137
Opened 2021-01-25 11:49 UTC by Peppe

2021-01-25 12:13 UTC, jouni commented on articles/ce/collaboration-binder.asciidoc
> +You can configure how eagerly the data should be sent through the text fields own API, `TextField.setValueChangeMode(ValueChangeMode);`.
```suggestion
You can configure how eagerly Text Field sends data through its own API, using `TextField.setValueChangeMode(ValueChangeMode);`.

pass:[<!-- vale Vaadin.Weasel = YES -->]
```

2021-01-25 12:13 UTC, jouni commented on articles/ce/collaboration-binder.asciidoc
> +== Propagate Values Eagerly in Text Fields
```suggestion
pass:[<!-- vale Vaadin.Weasel = NO -->]

== Propagate Values Eagerly in Text Fields
```

2021-01-26 15:17 UTC, pekam requested changes

2021-01-26 15:17 UTC, pekam commented on articles/ce/collaboration-binder.asciidoc
> +On text fields, the default and recommended mode for propagating values from one user to others are when the user blurs the field.
```suggestion
On text fields, the default and recommended mode for propagating values from one user to others is when the user blurs the field or presses the enter key.
```

2021-01-26 15:17 UTC, pekam commented on articles/ce/collaboration-binder.asciidoc
> +textField.setValueChangeMode(ValueChangeMode.EAGER);
```suggestion
TextField textField = new TextField();
textField.setValueChangeMode(ValueChangeMode.EAGER);
```

2021-01-26 15:17 UTC, pekam commented on articles/ce/collaboration-binder.asciidoc
> +You can configure how eagerly Text Field sends data through its own API, using `TextField.setValueChangeMode(ValueChangeMode);`.
The first sentence seems redundant.
The API exists on most fields, so I would be more generic here and leave `TextField` to the example code.
```suggestion
You can configure how eagerly the field sends data through its own API, using the `setValueChangeMode(ValueChangeMode)` method.
```

2021-01-26 15:17 UTC, pekam commented on articles/ce/collaboration-binder.asciidoc
> +Modes like `ValueChangeMode.LAZY` and `ValueChangeMode.TIMEOUT` can also be used together with `textField.setValueChangeTimeout(int);` to reduce the amount of traffic.
```suggestion
Modes like `ValueChangeMode.LAZY` and `ValueChangeMode.TIMEOUT` can also be used together with the `setValueChangeTimeout(int)` method to reduce the amount of traffic.
```

2021-01-27 09:57 UTC, pekam approved these changes

2021-01-27 16:34 UTC, jouni approved these changes

2021-01-27 16:34 UTC, merged