feat: Add FormManager documentation
vaadin/docs pull request #1375
Opened 2022-05-10 11:25 UTC by MatthewVaadin

Adds a new page and code sample for the `FormManager` class in Collaboration Engine.

2022-05-10 11:58 UTC, heruan requested changes
Looks good! I would add a general introduction on how this is connected to the `CollaborationBinder` (with a link to its documentation), so that it's clear that when they're connected to the same topic the changes are reflected there and viceversa.

2022-05-10 11:58 UTC, heruan commented on articles/ce/managers/form-manager.asciidoc
> +Collaboration Engine includes a manager to set property values and editor highlighting in a form, and to react to changes in these.
I would say `field highlighting` since we use _field_ to describe the form components.

2022-05-10 11:58 UTC, heruan commented on articles/ce/managers/form-manager.asciidoc
> +<2> The [methodname]`highlight()` method is used to mark the local user as editing a property.
Let's also explain what would happen to fields bound to the same property with a `CollaborationBinder`, e.g.

> […] a field component bound to the same property via a `CollaborationBinder` connected to the same topic will be highlighted and show the name of the user.

2022-05-10 11:58 UTC, heruan commented on articles/ce/managers/form-manager.asciidoc
> +<3> The [methodname]`setHighlightHandler()` method sets a callback to handle a user editing a property.
Same here, e.g.

```suggestion
<3> The [methodname]`setHighlightHandler()` method sets a callback to handle a user editing a property, for example focusing a field component bound to the same property via a [classname]`CollaborationBinder` instance connected to the same topic.
```

2022-05-10 11:58 UTC, heruan commented on articles/ce/managers/form-manager.asciidoc
> +<5> The [methodname]`setValue()` method is used to set the value of a property.
Also here, something like

> the value will be set on all field components bound to the same property […]

2022-05-11 12:47 UTC, heruan submitted a review, later dismissed

2022-05-11 12:50 UTC, jouni commented
I added the "Language not checked" label as that is the process we use for any new content introduced in the docs. I realize this was written by a native English speaker, so I doubt there are many issues.

2022-05-11 12:50 UTC, heruan commented
This needs next platform pre-release to remove the explicit dependency added to the POM (for the Java example to compile).

2022-05-11 12:52 UTC, jouni commented
@dougjewsbury, perhaps you want to review this when you do a full review of the whole CE section in docs, instead of separately now? Your choice.

2022-05-17 10:22 UTC, dougjewsbury reviewed
AsciiDoc looks good.

2022-05-18 09:16 UTC, heruan approved these changes

2022-05-23 09:21 UTC, merged