docs: Review package scan instructions after refactoring
vaadin/docs pull request #1432
Opened 2022-06-03 13:41 UTC by mcollovati

Classpath scan restriction are now defined with annotation
instead of overriding scanPackage method.

Part of vaadin/testbench#1420

2022-06-03 13:42 UTC, mcollovati commented
Draft until vaadin/testbench#1420 is closed

2022-06-06 05:47 UTC, caalador requested changes

2022-06-06 05:47 UTC, caalador commented on articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
>  [source,java]
```suggestion
.Package scan examples
[source,java]
```

2022-06-06 05:47 UTC, caalador commented on articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
> +If the annotation is used without providing [methodname]`classes()` and [methodname]`packages()`, it acts a shortcut for using the test class package
```suggestion
```

2022-06-06 05:47 UTC, caalador commented on articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
> +Using the annotation without providing [methodname]`classes()` and [methodname]`packages()`, acts as a shortcut for restricting scan to current test class package and sub-packages.
```suggestion
Using the annotation without providing [methodname]`classes()` or [methodname]`packages()`, acts as a shortcut for restricting scan to current test class package and sub-packages.
```

2022-06-07 17:50 UTC, dougjewsbury commented on articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
> +To restrict the scan to specific packages and their sub-packages, annotate the test class with [annotationname]`ViewPackages` and specify the package by filling the [methodname]`classes()` array with
```suggestion
To restrict the scan to specific packages and their sub-packages, annotate the test class with [annotationname]`ViewPackages` and specify the package by filling the [methodname]`classes()` array with classes that are members of the desired packages, or by providing the packages with fully qualified names in the [methodname]`packages()` property.
```

2022-06-07 17:51 UTC, dougjewsbury commented on articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
> +Using the annotation without providing [methodname]`classes()` or [methodname]`packages()`, acts as a shortcut for restricting scan to current test class package and sub-packages.
```suggestion
Using the annotation without providing [methodname]`classes()` or [methodname]`packages()` acts as a shortcut for restricting the scan to the current test class package and sub-packages.
```

2022-06-08 08:54 UTC, dougjewsbury reviewed
AsciiDoc looks good.

2022-06-09 03:39 UTC, caalador approved these changes

2022-06-09 10:27 UTC, merged