Migrate badge text and create example files
vaadin/docs pull request #146
Opened 2021-01-27 10:51 UTC by alkali47

2021-01-27 10:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=146) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=146) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=146) it.</sub>

2021-01-28 13:34 UTC, jouni requested changes
Writing style improvements.

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +Badges should generally always contain a label.
```suggestion
Badges should contain a label.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +Labels should be clear, concise and written using sentence case.
```suggestion
Labels should be clear, concise, and written using sentence case.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +Aim for 1-2 words.
```suggestion
Aim for 1 to 2 words.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +The benefit of icons in addition to a label should be weighed against the additional visual noise it creates.
```suggestion
The benefit of icons should be weighed against the visual noise it adds.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +=== Icon-only
```suggestion
=== Icon-Only
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +You can combine any theme variants freely.
```suggestion
You can combine any theme variants together.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +There are two different sizes you can use for badges: the default (normal) and `small`.
```suggestion
Badges have two different sizes you can use: the default (normal) and `small`.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +In addition, they can be paired with the `primary` theme variant for additional emphasis.
```suggestion
The color variants can be paired with the `primary` theme variant for additional emphasis.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +|Highlight positive outcomes, such as when a task or operation is successfully completed.
```suggestion
|Highlight positive outcomes, such as when a task or operation is completed.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +If you’re using colors and icons to convey information, provide the same info via `aria-label` to ensure screen readers can interpret the info correctly.
```suggestion
If you’re using colors and icons to convey information, provide the same info via `aria-label` to ensure screen readers can interpret the info.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +Badges and Buttons are very similar in appearance. This might lead users to think badges are interactive.
```suggestion
Badges and Buttons are similar in appearance.
This might lead users to think badges are interactive.
```

2021-01-28 13:34 UTC, jouni commented on articles/ds/components/badge/index.asciidoc
> +Placement, language, shape and color can all help mitigate any confusion.
```suggestion
Placement, language, shape, and color can all help mitigate any confusion.
```

2021-01-29 08:07 UTC, jouni requested changes
All Java examples seem to be missing `// end::snippet[]`

2021-01-29 08:07 UTC, jouni commented on src/main/java/com/vaadin/demo/component/badge/BadgeBasic.java
> +        add(badge);
```suggestion
        // tag::snippet[]
        Span badge = new Span("Badge");
        badge.getElement().getThemeList().add("badge pill contrast");

        add(badge);
        // end::snippet[]
```

2021-02-22 14:29 UTC, alkali47 reviewed
Looks like this pull request is ready, I have added the end tags for the snippets to all java files.

2021-02-22 15:06 UTC, jouni approved these changes

2021-02-22 15:07 UTC, merged