Feature/cookie consent
vaadin/docs pull request #148
Opened 2021-01-27 13:44 UTC by alkali47

2021-01-27 13:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=148) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=148) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=148) it.</sub>

2021-01-27 14:12 UTC, jouni commented
@alkali47, please sign the Contributor License Agreement (CLA).

2021-01-27 14:18 UTC, alkali47 commented
![Screen Shot 2021-01-27 at 16 17 54](https://user-images.githubusercontent.com/1915337/106003866-4b18cf00-60bb-11eb-92c5-3fb20d12914a.png)

Can't seem to sign the CLA, no agree button or anything like that

2021-01-28 11:59 UTC, jouni requested changes

2021-01-28 11:59 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +Cookie Consent is fully customisable.
```suggestion
Cookie Consent is fully customizable.
```
Use en_US

2021-01-28 11:59 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +You can customise the message, the "Learn More" link, the "Dismiss" button, as well as the component’s position.
```suggestion
You can customize the message, the "Learn More" link, the "Dismiss" button, as well as the component’s position.
```

2021-01-28 11:59 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +
```suggestion
```

2021-01-28 11:59 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +|===
Use built-in Asciidoc table cell alignment features.

```suggestion
[cols="<,>"]
|===
|Top left
|Top right

|Bottom left
|Bottom right
|===

[cols="^"]
|===
|Top (stretch, default)
|Bottom (stretch)
|===
```

2021-01-28 11:59 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::../../../../frontend/demo/component/cookieconsent/cookie-consent-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
Change this for all code example includes.

```suggestion
include::{root}/frontend/demo/component/cookieconsent/cookie-consent-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-02-22 15:04 UTC, jouni approved these changes

2021-02-22 15:07 UTC, merged