Documenting the usage of return type for programmatic navigation
vaadin/docs pull request #1480
Opened 2022-06-14 17:33 UTC by mstahv

Also added instructions how to maintain URL parameters manually in the view (already valid and more relevant after the new API addition)

https://github.com/vaadin/flow/pull/13906

2022-06-14 18:42 UTC, jouni reviewed
I’m not sure why the preview build has failed. Need to try this locally or ask Mikael to check the logs.

2022-06-14 18:42 UTC, jouni commented on articles/routing/navigation.asciidoc
> +[role="since:react-dom@v23.2"]
Define the Maven artifact ID (we are not interested in the version of the `react-dom` npm dependency), and use an uppercase `V` since that will appear as is in the production site (and we use that instead of lowercase `v`).

```suggestion
[role="since:com.vaadin:vaadin@V23.2"]
```

2022-06-14 18:42 UTC, jouni commented on articles/routing/route-parameters.asciidoc
> +== Maintaining Route Parameters manually
```suggestion
== Maintaining Route Parameters Manually
```

2022-06-14 18:42 UTC, jouni commented on articles/routing/navigation.asciidoc
> +The optional may be empty if the target view is not immediately available for some reason. This may happen for example because of security constraints or if the navigation was cancelled or posponed i
Not sure I understand the last part of this paragraph with the `TODO link` mention.

```suggestion
The optional may be empty if the target view is not immediately available for some reason.
This may happen, for example, because of security constraints or if the navigation was cancelled or postponed in navigation lifecycle events `TODO` link.
```

2022-06-14 21:01 UTC, mstahv commented on articles/routing/navigation.asciidoc
> +[role="since:react-dom@v23.2"]
Eh. I was wondering that that react-dom ment, just copy-pasting as I have no idea what this docs site does 😂 Still don't understand the version. Is that required to be a full maven version or something else? What is production site? (for further reference, I assume your suggestion is correct).

2022-06-14 21:02 UTC, mstahv commented on articles/routing/navigation.asciidoc
> +The optional may be empty if the target view is not immediately available for some reason. This may happen for example because of security constraints or if the navigation was cancelled or posponed i
I'll add a link to different part of docs there, forgot to do that there.

2022-06-15 05:42 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Switching between routes/views can be initiated in two ways: programmatically using [methodname]`UI.navigate()` methods or using links. The navigate method is more agile for Java programmer, as the v
```suggestion
Switching between routes/views can be initiated in two ways: programmatically using [methodname]`UI.navigate()` methods or using links.
The navigate method is more agile for a Java programmer, as the view change can be issued from anywhere in your code and you can interact with the target view.
Using links, on the other hand, is the native web way of moving from one view to another, allowing you for example to share the direct link to a specific view with your colleague and they work even if the session has expired.
```

2022-06-15 05:42 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Switching between routes/views can be initiated in two ways: programmatically using [methodname]`UI.navigate()` methods or using links. The navigate method is more agile for Java programmer, as the v
```suggestion
Switching between routes/views can be initiated in two ways: programmatically using [methodname]`UI.navigate()` methods or using links.
The navigate method is more agile for a Java programmer, as the view change can be issued from anywhere in your code and you can interact with the target view.
Using links, on the other hand, is the native web way of moving from one view to another, allowing you for example to share the direct link to a specific view with your colleague and they work even if the session has expired.
```

2022-06-15 05:48 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +        "Navigate to company");
```suggestion
Button button = new Button("Navigate to company");
```

2022-06-15 05:48 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +        "Navigate to company");
```suggestion
Button button = new Button("Navigate to company");
```

2022-06-15 05:49 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +        "Edit user details");
```suggestion
Button editButton = new Button("Edit user details");
```

2022-06-15 05:49 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +        "Edit user details");
```suggestion
Button editButton = new Button("Edit user details");
```

2022-06-15 05:56 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +*Example*: Navigation to the `user/123/edit` route target when clicking a button:
Would the example be clearer if we use a simpler URL? How about `user-view/id1234`? If we do that, then also instead of using `UserProfileEdit.class`, we can use the more obvious `UserView.class`.

2022-06-15 05:56 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +*Example*: Navigation to the `user/123/edit` route target when clicking a button:
Would the example be clearer if we use a simpler URL? How about `user-view/id1234`? If we do that, then also instead of using `UserProfileEdit.class`, we can use the more obvious `UserView.class`.

2022-06-15 05:58 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +The navigate methods where you give the target view class as a parameter returns the actual target view as [classname]`Optional`. This allows you to further configure the new view with native Java AP
> new view with native Java API
As a reader, I'm not sure what "native" is supposed to mean here.

2022-06-15 05:58 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +The navigate methods where you give the target view class as a parameter returns the actual target view as [classname]`Optional`. This allows you to further configure the new view with native Java AP
> new view with native Java API
As a reader, I'm not sure what "native" is supposed to mean here.

2022-06-15 05:59 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +This may happen, for example, because of security constraints or if the navigation was cancelled or postponed in <<lifecycle#, navigation lifecycle events>>.
```suggestion
This may happen, for example, because of security constraints or if the navigation was canceled or postponed in a <<lifecycle#, navigation lifecycle events>>.
```

2022-06-15 05:59 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +This may happen, for example, because of security constraints or if the navigation was cancelled or postponed in <<lifecycle#, navigation lifecycle events>>.
```suggestion
This may happen, for example, because of security constraints or if the navigation was canceled or postponed in a <<lifecycle#, navigation lifecycle events>>.
```

2022-06-15 06:12 UTC, tarekoraby requested changes

2022-06-15 06:12 UTC, tarekoraby commented on articles/routing/route-parameters.asciidoc
> +== Maintaining Route Parameters Manually
First, I think this is a separate topic from documenting programmatic navigation. So let's create a separate PR for it. 

That aside, I must say that I read this section three times, and I'm still struggling to understand the solution it's describing or even the problem that it's intended to solve. But as far as I can tell, this is an esoteric use case that should be covered in an "advanced section" somewhere (I don't think it's suitable for people who are just starting to learn about how to add parameters to a Vaadin route). I suggest either creating a new article for that under `routing/additional-guides` or adding it to the History API guide.

2022-06-15 06:19 UTC, mstahv commented on articles/routing/navigation.asciidoc
> +        "Navigate to company");
Was about to make other improvement in an other commit, but suits me...

2022-06-15 06:21 UTC, mstahv commented on articles/routing/navigation.asciidoc
> +*Example*: Navigation to the `user/123/edit` route target when clicking a button:
Yes, I had a note about this part as well. Getting to advanced example, when explaining the basics. But I'd favour doing this (and others) change separately, as this patch is related to new functionality and supporting areas.

2022-06-15 06:27 UTC, mstahv commented on articles/routing/route-parameters.asciidoc
> +== Maintaining Route Parameters Manually
The example could indeed be better. Think of a search view where you want to maintain the deep linking URL in the browser. You don't want to use our somewhat clumsy routing/navigating API to navigate to a new search view with new parameters. Will be much better with this approach (or with query parameters).

2022-06-15 10:26 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +You can trigger navigation from the server side code using various [methodname]`UI.navigate()` methods.
```suggestion
You can trigger navigation from the server-side code using various [methodname]`UI.navigate()` methods.
```

2022-06-15 10:28 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +In the browser, navigate methods triggers a location update and the addition of a new history state entry, but does not issue a full page reload.
```suggestion
In the browser, the [methodname]`navigate()` method triggers a location update and the addition of a new history state entry, but does not issue a full page reload.
```

2022-06-15 10:29 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +The navigate methods where you give the target view class as a parameter returns the actual target view as [classname]`Optional`. This allows you to further configure the new view with its Java API.
```suggestion
The [methodname]`navigate()` method where you give the target view class as a parameter returns the actual target view as [classname]`Optional`.
This allows you to further configure the new view with its Java API. 
```

2022-06-15 10:32 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +In many use cases this is fine, but if you expect to share links to the target view, the target view must maintain enough details in the URL and add de-serialise the parameters, as described in <<rou
```suggestion
Note that, with this code, Vaadin does not have the data to maintain a deep link to edit the very same user. 
In many use cases, this is fine, but if you expect to share links to the target view, the target view must maintain enough details in the URL and deserialize the parameters, as described in <<route-parameters#, Route Parameters>>.
```

2022-06-15 10:35 UTC, dougjewsbury commented on articles/routing/route-parameters.asciidoc
> +In this case developer can use the History object to maintain the RouteParameters.
```suggestion
In certain cases, a developer might want to maintain the parameters in the browser URL, such as if the edited entity in a form changes via an instance method instead of via passing URL parameters.
In this case, the developer can use the [classname]`History` object to maintain the [classname]`RouteParameters`.
```

2022-06-15 10:37 UTC, dougjewsbury commented on articles/routing/route-parameters.asciidoc
> +*Example*: A view that is updating the deep linking parameters based on a parameter given in a public API. The view also implements HasUrlParameter to de-serialise the parameter in case a user arrive
```suggestion
*Example*: A view that updates the deep linking parameters based on a parameter given in a public API.
The view also implements [interfacename]`HasUrlParameter` to deserialize the parameter in case a user arrives at the page directly:
```

2022-06-15 12:07 UTC, mstahv commented on articles/routing/route-parameters.asciidoc
> +== Maintaining Route Parameters Manually
Changed the title and added a bit more context why using Router for everything isn't the best way to make the world a better place.

2022-06-16 06:47 UTC, tarekoraby commented on articles/routing/index.asciidoc
> +In fact, if deep linking is not needed, even a large Vaadin application can ignore routing and navigation for simplicity and only route the entry view to the root URL of the application.
The message that these two sentences attempt to convey could be clarified more. Do you here mean that user interaction in Vaadin applications is often better achieved by dynamically adding and removing components/views (instead of routing between different views)?

2022-06-16 06:50 UTC, tarekoraby commented on articles/routing/index.asciidoc
> +However, Routing and Navigation APIs in Vaadin help you achieve a decent level of deep linking relatively easily. Thus, we suggest routing at least the top-level views to different URLs and then util
> and then utilizing more advanced features for views where you need a better deep linking

It's not clear here what "more advanced features" is referring to.

2022-06-16 06:58 UTC, tarekoraby commented on articles/routing/index.asciidoc
> +In most non-trivial applications, views also need to interact with each other and share data. When initiating navigation, the previous view can <<navigation#passing-data-using-route-parameters,submit
```suggestion
In most non-trivial applications, views also need to interact with each other and share data. When initiating navigation, the previous view can <<navigation#passing-data-using-route-parameters,submit trivial data>> as route or query parameters to the new view. The easiest, safest, and performant way to share data between views is to <<navigation#interacting-directly-with-the-target-view,call their Java API directly>>.
```

The caveat that starts with _"Doing this, however, will not automatically ...."_  is many steps ahead (it assumes the reader has already a good understanding of the Java API for navigation). I think it's better to remove this since the same caveat (with the link to `route-parameters#maintaining-route-parameters-without-navigation`) is already mentioned in the linked Java API for navigation.

2022-06-16 07:11 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Note that, with this code, Vaadin does not have the data to maintain a deep link to edit the very same user.
> Vaadin does not have the data to maintain a deep link to edit the very same user

Do you mean that "Vaadin would not automatically update the URL to include information about the edited user"? 

Also, does this sentence presuppose that the target view accepts parameters? If so, then this should be stated.

2022-06-16 07:16 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Note, in previous versions, a similar mechanism has been widely used, but the reference of the target view has been fetched using dependency injection, searched from the [classname]`UI` internals, or
I'm not sure which previous versions are being referred to here. But in any case, is this information useful and actionable for our existing users? If so, then let's mention it in the upgrade guide and keep the main guides optimized for our new users. That is, I think this sentence should be removed from this guide.

2022-06-16 07:37 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +If your target view implements HasRouteParameters, you can submit trivial data to the target view as RouteParameters. Compared to directly interacting with the target views Java API, this method auto
> automatically maintains the URL for deep linking

To my mind, the term "deep linking" is not widely used. I would just get rid of it wherever possible and explain it in plain English. Here for example I think it would be clearer to say something like: _Compared to directly interacting with the target views' Java API, this method automatically updates the URL to include the Route Parameter._

2022-06-16 13:29 UTC, jouni commented on articles/routing/navigation.asciidoc
> +If your target view implements HasRouteParameters, you can submit trivial data to the target view as RouteParameters. Compared to directly interacting with the target views Java API, this method auto
“Deep linking” is fairly common language in my opinion. For example, Apple is using that in their developer-focused communication.

2022-06-16 13:37 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +If your target view implements HasRouteParameters, you can submit trivial data to the target view as RouteParameters. Compared to directly interacting with the target views Java API, this method auto
Let's keep it then.

2022-06-17 10:43 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +They are typically composed of other smaller components and help you structure and re-use your UI code.
```suggestion
They are typically composed of other smaller components and help you structure and reuse your UI code.
```

2022-06-17 10:45 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +Directly changing the state of components and adding/removing them from the UI using Java API is easier and more efficient.
```suggestion
Directly changing the state of components and adding/removing them from the UI using Java APIs is easier and more efficient.
```

2022-06-17 10:46 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +Thus, we suggest routing at least the top-level views to different URLs and then utilizing more advanced features like parameters and <<layout#,nested routes>> for views where you need a better deep
```suggestion
Thus, we suggest routing at least the top-level views to different URLs and then utilizing more advanced features like parameters and <<layout#,nested routes>> for views where you need better deep linking.
```

2022-06-17 10:46 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +Sometimes a proper deep linking requires developer to manually <<updating-url-parameters#,maintain the URL parameters>>.
```suggestion
Sometimes proper deep linking requires the developer to manually <<updating-url-parameters#,maintain the URL parameters>>.
```

2022-06-17 10:47 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +Also, other views can be <<navigation#interacting-directly-with-the-target-view,passing data directly>> using Java API, instead of using URL parameters.
```suggestion
Also, other views can be <<navigation#interacting-directly-with-the-target-view,passing data directly>> using Java APIs, instead of using URL parameters.
```

2022-06-17 10:48 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +In these cases the routing mechanism can't update the URL automatically.
```suggestion
In these cases, the routing mechanism cannot update the URL automatically.
```

2022-06-17 10:51 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +If deep linking is required, the target view must <<updating-url-parameters#,maintain enough details about the UI state in the URL>> or developer must use Route Parameters to pass the data instead of
```suggestion
If deep linking is required, the target view must <<updating-url-parameters#,maintain enough details about the UI state in the URL>>, or the developer must use RouteParameters to pass the data, instead of the direct Java API.
```

2022-06-17 10:52 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +If your target view implements HasRouteParameters, you can submit trivial data to the target view as RouteParameters.
```suggestion
If your target view implements [interfacename]`HasRouteParameters`, you can submit trivial data to the target view as [classname]`RouteParameters`. 
```

2022-06-17 10:53 UTC, dougjewsbury commented on articles/routing/navigation.asciidoc
> +However, you can't pass more complex objects as route parameters as such and you always need to consider data safety parameters that end up to URLs.
```suggestion
However, you cannot pass more complex objects as route parameters as such, and you always need to consider data safety parameters that end up in URLs.
```

2022-06-17 10:55 UTC, dougjewsbury commented on articles/routing/updating-url-parameters.asciidoc
> +description: To preserve deep linking developer must sometimes maintain the Route parameters and Query parameters manually
```suggestion
description: To preserve deep linking, the developer sometimes needs to maintain the Route parameters and Query parameters manually
```

2022-06-17 10:56 UTC, dougjewsbury commented on articles/routing/updating-url-parameters.asciidoc
> +Route parameters, Route templates and Query Parameter are most often defined in a link pointing to a specific view with the desired state and when navigating to view the Router calls the view's [meth
```suggestion
Route parameters, Route templates and Query parameters are most often defined in a link pointing to a specific view with the desired state, and when navigating to a view, the Router calls the view's [methodname]`setParameter()` method.
```

2022-06-17 10:57 UTC, dougjewsbury commented on articles/routing/updating-url-parameters.asciidoc
> +A good example of such a use case could be a search view that maintains the search parameters in the URL but doesn't want to build its UI logic around the Router usage.
```suggestion
A good example of such a use case could be a search view that maintains the search parameters in the URL but does not want to build its UI logic around the Router usage.
```

2022-06-17 10:58 UTC, dougjewsbury commented on articles/routing/updating-url-parameters.asciidoc
> +Another case would be passing a more complex object to a view via Java API instead of serializing the object somehow into the URL and passing the value via Router.
```suggestion
Another case would be passing a more complex object to a view via a Java API instead of serializing the object somehow into the URL and passing the value via Router.
```

2022-06-17 10:59 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +Routing in Vaadin means mapping views into specific URLs and maintaining a meaningful https://en.wikipedia.org/wiki/Deep_linking[deep linking].
```suggestion
Routing in Vaadin means mapping views into specific URLs and maintaining meaningful https://en.wikipedia.org/wiki/Deep_linking[deep linking].
```

2022-06-17 11:04 UTC, dougjewsbury commented on articles/routing/index.asciidoc
> +URLs can also contain <<route-parameters#,Route Parameters>> or <<additional-guides/query-parameters#,Query Parameters>> that views can utilize to configure their internal state further.
```suggestion
URLs can also contain <<route-parameters#,route parameters>> or <<additional-guides/query-parameters#,query parameters>> that views can utilize to configure their internal state further.
```

2022-06-17 14:13 UTC, mstahv commented
@tarekoraby I guess we are ready now with this?

2022-06-20 06:15 UTC, tarekoraby approved these changes

2022-06-20 06:15 UTC, merged