refactor: update docs after naming changes in UI Unit Testing
vaadin/docs pull request #1488
Opened 2022-06-16 10:02 UTC by mcollovati

Part of vaadin/testbench#1487
Part of vaadin/testbench#1488

2022-06-16 10:10 UTC, caalador requested changes

2022-06-16 10:10 UTC, caalador commented on articles/tools/testbench/ui-unit-testing/searching-components.asciidoc
>  TextFieldWrap nameField_ = $view(TextField.class)
```suggestion
TextField nameField = $view(TextField.class)
```

2022-06-16 11:32 UTC, caalador approved these changes

2022-06-17 07:51 UTC, mcollovati commented
I was thinking to merge this PR even if language is not checked, so the documentation is in sync with the changes on latest testbench alpha released yesterday

2022-06-17 09:27 UTC, merged