hilla: add an article to explain how to cancel endpoint requests
vaadin/docs pull request #1514
Opened 2022-06-22 12:38 UTC by cromoteca

This PR contains a new article about endpoint request cancellation and modifies the error handling page to mention `AbortError`s related to cancellation.

Fixes #1477

2022-06-23 10:55 UTC, tarekoraby requested changes

2022-06-23 10:55 UTC, tarekoraby commented on articles/advanced/cancelling-endpoint-requests.asciidoc
> +description: TODO
Let's remember to add the description before merging.

2022-06-23 10:55 UTC, tarekoraby commented on articles/advanced/cancelling-endpoint-requests.asciidoc
> +or they are standing in queue despito no longer being needed. Hilla allows developers to cancel those
```suggestion
or they are standing in queue despite no longer being needed. Hilla allows developers to cancel those
```

2022-06-27 17:04 UTC, dougjewsbury commented on articles/advanced/cancelling-endpoint-requests.asciidoc
> +allow to cancel them.
```suggestion
All endpoint requests support an optional `init` parameter that can be used to pass an `AbortSignal` which will allow them to be cancelled.
```

2022-06-27 17:10 UTC, dougjewsbury commented on articles/application/error-handling.asciidoc
> +happens when you explicitly cancel request as explained in <<../advanced/cancelling-endpoint-requests#,this article>>.
```suggestion
When a request is cancelled programmatically, the endpoint call promise will resolve with an `AbortError`.
This happens only when you explicitly cancel a request, as explained in <<../advanced/cancelling-endpoint-requests#,this article>>.
```

2022-06-28 06:26 UTC, tarekoraby approved these changes

2022-06-28 06:26 UTC, tarekoraby commented
I think it would be good for someone for the Hilla team to also review this, if they haven't already.

2022-06-28 09:50 UTC, platosha commented on articles/advanced/cancelling-endpoint-requests.asciidoc
> +All endpoint requests support an optional `init` parameter that can be used to pass an `AbortSignal` which will allow them to be cancelled.
Should probably mention the new name, or remove the name entirely. It’s not much useful anyway.

```suggestion
All endpoint requests support an optional last object parameter, that can be used to pass an `AbortSignal`, which will allow them to be cancelled.
```

2022-06-28 09:56 UTC, cromoteca commented on articles/advanced/cancelling-endpoint-requests.asciidoc
> +All endpoint requests support an optional `init` parameter that can be used to pass an `AbortSignal` which will allow them to be cancelled.
Good idea. The name can even change when using the multi-module generator. What if I skip it altogether?

```suggestion
All endpoint requests support an optional parameter that can be used to pass an `AbortSignal` which will allow them to be cancelled.
```

2022-06-28 09:58 UTC, platosha approved these changes

2022-08-05 07:02 UTC, tarekoraby requested changes

2022-08-05 07:02 UTC, tarekoraby commented on package.json
> -  "scripts": {
@cromoteca is this intended? Are those changes really needed for this PR?

2022-08-05 07:03 UTC, tarekoraby approved these changes

2022-08-05 07:18 UTC, merged