Create Selenium guide draft
vaadin/docs pull request #1537
Opened 2022-07-04 16:48 UTC by dmitrilc

2022-07-04 16:52 UTC, dmitrilc commented
Here is my example test https://github.com/dmitrilc/vaadin-selenium-example

2022-07-28 11:11 UTC, tarekoraby requested changes

2022-07-28 11:11 UTC, tarekoraby commented on articles/testing/selenium.adoc
> +== Verify the URL After Navigation Action
To me, the most important point that I, as the reader, have learned from the test included in this section is that I can:
. Find elements on the page 
. and, interact with those elements, say, via clicking

I think the title should reflect the most important aspects of this section (which, to my mind, is not the very specific use case of verifying the URL after navigation)

2022-07-28 11:11 UTC, tarekoraby commented on articles/testing/selenium.adoc
> +== Add User to Master Detail Template
Here again, the title (and the first couple of sentences) of this section could be rewritten to clarify the most important learning points that people will gain after reading this section. Only a very small subset of developers will have a very specific interest in creating a test that adds a user to a master-detail template that is generated from start.vaadin.com. However, many more readers would benefit from learning how to implement a more advanced testing scenario that involves finding and interacting with different elements.

I suggest, thus, renaming this section's title to something like "Advanced Testing Scenario" (and mention in the first couple of sentences in the section that this example demonstrates a more complex use case that involves using APIs like `By.id` and `By.xpath`.

2022-07-28 11:11 UTC, tarekoraby commented on articles/testing/selenium.adoc
> +<5> Finally, we test whether all of the information in the table cells match our original data.
Let's finish this page with a link to Selenium docs so that people can read more if they want to.

2022-07-28 13:20 UTC, tarekoraby commented on articles/testing/selenium.adoc
> +   <version>5.1.1</version>
Also the latest version is `5.2.1`: https://search.maven.org/artifact/io.github.bonigarcia/webdrivermanager. Let's use that.

2022-08-04 10:43 UTC, tarekoraby commented on articles/testing/selenium-testing.adoc
> +public void addUser(){
@dmitrilc this test doesn't pass in the repo you created. Can you please check?

2022-08-08 22:15 UTC, dmitrilc commented on articles/testing/selenium-testing.adoc
> +public void addUser(){
@tarekoraby I was able to reproduce it on an old Windows machine with the error below.

```
ElementClickIntercepted element click intercepted

element click intercepted: Element <vaadin-grid-sorter path="col3" aria-label="Sort by ...">Phone</vaadin-grid-sorter> is not clickable at point (788, 83). Other element would receive 
the click: <div class="editor">...</div>
```

I was not able to reproduce it on my MBP M1 16" screen because the field `Phone` is still in view, so Selenium was able to click on it. On the 15" 1080p Windows laptop screen though, the field `Phone` was not in view, so Selenium couldn't click on it.

Because screen size, resolution, and scaling settings can affect the tests, I will make the browser maximized just for that test, which should reduce flakiness.

2022-08-08 22:23 UTC, dmitrilc commented on articles/testing/selenium-testing.adoc
> +public void addUser(){
Can you update your project from my repo and run the test again? Thanks.

2022-08-10 13:30 UTC, alvarezguille requested changes
Went through the guide and tested it locally, in general it looks good, I still added some comments that I hope are helpful.
Some of them might be a bit opinionated and not require a change like the `WebDriverWait` one.
But others should be addressed so that the guide stays valid.

2022-08-10 13:30 UTC, alvarezguille commented on articles/testing/selenium-testing.adoc
> +<dependency>
Latest version now is 4.4.
But for start (spring-boot) projects the version shouldn't be explicit as it's defined in `selenium.version` property in pom, that is used in the bom of spring-boot-starter-parent.
If we add 
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>4.3.0</version>
</dependency>
```

We end up with inconsistent versions in dependency:tree which might lead to issues in the future

>[INFO] +- org.seleniumhq.selenium:selenium-java:jar:4.3.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-api:jar:4.2.1:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-chrome-driver:jar:4.2.1:compile

User should add the following instead
```
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
</dependency>
```

2022-08-10 13:30 UTC, alvarezguille commented on articles/testing/selenium-testing.adoc
> +       new FluentWait<WebDriver>(driver)
Steps 4-7 can be shortened to
```
    new WebDriverWait(driver, Duration.ofSeconds(30), Duration.ofSeconds(1))
        .until(ExpectedConditions.titleIs("Hello World"));
```
I would use the title to make sure that it loaded but make the test about asserting something different.
WebDriverWait is a specialized type of FluentWait that makes things simpler, especially with combined with ExpectedConditions

2022-08-10 13:30 UTC, alvarezguille commented on articles/testing/selenium-testing.adoc
> +import org.junit.Test;
>import org.junit.Test;
import org.junit.jupiter.api.Assertions;

Mixing junit 4 and junit 5 imports can result in unexpected outcome (no test run, no assert executed, ...)

2022-08-10 13:30 UTC, alvarezguille commented on articles/testing/selenium-testing.adoc
> +  driver.findElement(By.linkText("About")) // <1>
`driver.findElement(By.linkText("About"))` is not compatible with the new AppNavItem used in start projects, this selector failed when using the the guide in a new project
>org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"link text","selector":"About"}

2022-08-10 13:30 UTC, alvarezguille commented on articles/testing/selenium-testing.adoc
> +  driver.quit();
Having `driver.quit();` as part of the test flow will leave browser windows open in case that a test fail. 
This could be added to a finally clause. Or ideally handle the creation and end of the session in setup and teardown methods that are executed before and after each test.

2022-08-10 13:39 UTC, tarekoraby commented on articles/testing/selenium-testing.adoc
> +public void addUser(){
Yes, it works now with the screen resize. Thanks!

2022-08-10 16:44 UTC, dmitrilc commented on articles/testing/selenium-testing.adoc
> +       new FluentWait<WebDriver>(driver)
This is an interesting case because you again readability on the `until` condition and gets to skip the `ignoring` call, but loses the information on which duration is timeout and which is polling.

This method still comes out with one extra benefit, so I will be switching to it. Thanks for bringing it up.

I will see what I can do about asserting something else as well.

2022-08-10 17:27 UTC, dmitrilc commented on articles/testing/selenium-testing.adoc
> +  driver.quit();
I somehow prefer `try/finally` over `before/after` for the doc because the tests can appear as individual examples. And we are not really sharing the whole repo with the readers anyway. Though in real code, I would use before/after.

2022-08-10 20:47 UTC, dmitrilc commented
@tarekoraby I have resolved all of Alvarez's concerns. You can update your repo and see whether all is good on your side.

2022-08-11 07:35 UTC, tarekoraby commented on articles/testing/selenium-testing.adoc
> +We can skip the version number here because it has already been declared by the `<selenium.version>` property in the `pom.xml` file.
```suggestion
In a https://start.vaadin.com/[Vaadin Start] generated project, we can skip the version number here because it has already been declared by the `<selenium.version>` property in the `pom.xml` file.
You can find the latest version of Selenium https://search.maven.org/artifact/org.seleniumhq.selenium/selenium-java[here].
```

We should clarify that the version number is not needed in a Start-generated project because not all projects are generated from Vaadin Start. It would also still be useful to include a link to the latest version (even for a Start generated project) so that people can update it if needed.

2022-08-11 07:40 UTC, tarekoraby commented on articles/testing/selenium-testing.adoc
> +== Long Selenium Test
Why "Long"? Why would the user be interested in reading something that is long? What will they gain?

2022-08-15 11:58 UTC, tarekoraby commented on articles/testing/selenium-testing.adoc
> +.`SimpleTestIT.java`
Would it be better to remove the word "Test" from the class name since it is implicit in the "IT" posfix?

2022-08-16 08:54 UTC, tarekoraby approved these changes

2022-08-16 09:00 UTC, alvarezguille approved these changes
Content looks good 👍

2022-08-16 09:28 UTC, merged