Create docker.adoc
vaadin/docs pull request #1538
Opened 2022-07-05 00:30 UTC by dmitrilc

2022-07-05 11:55 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
Yes, I think so. Good catch @knoobie. This should be fixed in Start generated projects too.

2022-07-06 12:49 UTC, tarekoraby commented on articles/production/docker.adoc
> +== Add The Dockerfile Manually
```suggestion
== Adding a Dockerfile to Existing Vaadin Applications
```

2022-07-06 16:47 UTC, dmitrilc commented on articles/production/docker.adoc
> +. To run your container on localhost.
Hi @tarekoraby, Docker `Desktop` is a simple solution for laptops and `desktops`, but I actually don't use it. Whenever possible, I prefer to install docker engine in Linux VMs instead. 

Do you think I should mention both, only Docker Desktop, or only Docker Engine?

2022-07-08 06:03 UTC, tarekoraby commented on articles/production/docker.adoc
> +Building a Docker image requires creating a Dockerfile, a text document containing all the commands needed to assemble and run that image.
```suggestion
Building a Docker image requires creating a [filename]#Dockerfile#, a text document containing all the commands needed to assemble and run that image.
```

2022-07-08 06:04 UTC, tarekoraby commented on articles/production/docker.adoc
> +For a Vaadin application, you can easily generate a Dockerfile by selecting the `Docker` option in https://start.vaadin.com/[Vaadin Start].
```suggestion
For a Vaadin application, you can easily generate a [filename]#Dockerfile# by selecting the `Docker` option in https://start.vaadin.com/[Vaadin Start].
```

2022-07-08 06:04 UTC, tarekoraby commented on articles/production/docker.adoc
> +. To run your container on localhost.
Yes, let's mention both with links.

2022-07-08 06:06 UTC, tarekoraby commented on articles/production/docker.adoc
> +If your Vaadin project did not come with a Dockerfile previously, you should copy and paste the Dockerfile from a fresh Vaadin Start project into your project.
```suggestion
If your Vaadin project was not generated with a Dockerfile, you can copy and paste the Dockerfile from a fresh Vaadin Start project into your project.
```

2022-07-08 06:16 UTC, tarekoraby commented on articles/production/docker.adoc
> +While we will not be teaching you how to create your own Dockerfile, let us quickly inspect the Dockerfile generated by Vaadin Start, to help you with customizing it in your own application.
```suggestion
While we will not here cover all the commands you can use in a [filename]#Dockerfile#, let us quickly inspect the Dockerfile generated by Vaadin Start to help you customize it in your application.
```

2022-07-08 06:20 UTC, tarekoraby requested changes

2022-07-08 06:20 UTC, tarekoraby commented on articles/production/docker.adoc
> +# Stage that builds the application, a prerequisite for the running stage
Let's remove the comments from the file, and instead use only the callouts (the things we define using `<1>`, `<2>`, etc.). Using both the comments in the file and the callouts is confusing and makes the whole text difficult to read.

2022-07-08 06:24 UTC, tarekoraby commented on articles/production/docker.adoc
> +<13> Coping files.
Let's combine all of these callouts into one.

2022-07-08 06:31 UTC, tarekoraby commented on articles/production/docker.adoc
> +[source,dockerfile]
I think having `dockerfile` as a source is not rendering correctly. Maybe it could be `terminal` 🤔 

@jouni where to find the list of acceptable source types?

2022-07-20 15:05 UTC, dmitrilc commented on articles/production/docker.adoc
> +[source,dockerfile]
It looks like `dockerfile` is one of the supported languages. https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

GH confirms that they are using Linguist https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-languages

2022-07-28 11:42 UTC, tarekoraby commented on articles/production/docker.adoc
> +[source,dockerfile]
But the issue is not how the page is rendered in the preview here on GitHub. The problem is how the application that builds the docs' pages renders this class, and how the reader will ultimately see it on vaadin.com/docs. In the preview it currently looks broken: 

![image](https://user-images.githubusercontent.com/42799254/181496879-6b8e8d3c-b0df-43ad-b092-1fa20766ad00.png)

2022-07-28 11:46 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
@dmitrilc please remove this line from the `Dockerfile`. (that is, remove
```
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
```
Vaadin will automatically download the appropriate Node version anyways. (new projects from start.vaadin.com now have this line removed).

2022-07-28 11:56 UTC, knoobie commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
I would suggest to let this here or change it to a comment as alternative way to acquire nodejs. This curl call could be changed to something within the own network for example.

Reasoning: Having build container or maven-plugins downloading stuff from internet is dangerous and close to impossible in restricted environments. Showing the developer that node is needed and can be installed like this without the maven-plugin automation sounds like a good thing.

2022-07-28 12:05 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
But in which scenarios would Vaadin automatic Node installation fail, whereas using curl would succeed?

2022-07-28 12:07 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
What would replace curl in restricted environments?

2022-07-28 12:17 UTC, knoobie commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
I've seen corporate environments where an internal URL was used to download node from a secured server with only specific node versions allowed, e.g. `curl https//my-internal-url./nodejs/custom_setup_14.x `

2022-07-28 13:37 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
Then I suggest still removing the two lines that install Node:
```
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update -qq && apt-get install -qq --no-install-recommends nodejs
```
And add a note at the end of the guide (outside the `Dockerfile`) that says something like:


_Creating a production build of the application inside the `Dockerfile` involves an implicit step by which Vaadin automatically downloads and installs a suitable Node.js distribution. In restricted environments with no (or limited) internet access, this automatic Node installation might fail. In such environments, make sure to install Node from a secured server as a separate step inside the `Dockerfile`. For example (and depending on your setup), the first few lines of your `Dockerfile` could look something like the following:_
```
FROM maven:3-openjdk-17-slim as build
curl https//my-internal-url./nodejs/custom_setup_16.x
RUN apt-get update -qq && apt-get install -qq --no-install-recommends nodejs
```

2022-07-28 14:13 UTC, knoobie commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
I really like that suggestion! :+1:

2022-07-29 06:01 UTC, tarekoraby commented on articles/production/docker.adoc
> +RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
Done! Pushed in a new commit. Thanks for the feedback ❤️

2022-07-29 06:03 UTC, tarekoraby commented on articles/production/docker.adoc
> +[source,dockerfile]
It seems that `dockerfile` works with asciidoc alright. Thee issue was that there was wrong dash characters used to delimit the source code block. I fixed this in a new commit.

2022-07-29 06:03 UTC, tarekoraby approved these changes

2022-07-29 06:52 UTC, merged