Create async-tasks.adoc
vaadin/docs pull request #1553
Opened 2022-07-12 15:07 UTC by dmitrilc

Working on ticket https://github.com/vaadin/docs/issues/1511

2022-07-29 13:49 UTC, tarekoraby commented
@dmitrilc I rewrote the guide extensively as the original draft
- assumed the reader has already a lot of knowledge about async tasks, and 
- seemed to mainly aim to show people how to add a progress bar to long-running tasks

These, however, are not the main aims of https://github.com/vaadin/docs/issues/1511. Rather, this ticket mainly aims to show users how to handle long-running tasks. Specifically, we have to take the user by hand and let them know why a poorly designed handling of long-running tasks is a problem in the first place. Then we need to tell them how they can transform a poor implementation of long-running tasks into a good one that uses `@Async` and Vaadin Push. Only then we can add the extra nice thing of showing them how to inform the user of the progress of the long-running task (say, via the `ProgressBar` component).

2022-07-29 13:50 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +TO DO (by adjusting the MainView.java file above)
@dmitrilc if you can, please complete this section.

2022-07-30 00:23 UTC, dmitrilc commented on articles/advanced/async-tasks.adoc
> +TO DO (by adjusting the MainView.java file above)
Sure, I just added the guide for ProgressBar

2022-07-30 00:29 UTC, dmitrilc commented
@tarekoraby 
Do you not need `@SpringBootApplication` in this code?

```java
@Push
@EnableAsync
public class Application extends SpringBootServletInitializer implements AppShellConfigurator
```

2022-08-01 07:15 UTC, tarekoraby commented
> @tarekoraby Do you not need `@SpringBootApplication` in this code?

Yes, fixed. Thanks for noticing.

2022-08-01 12:56 UTC, mcollovati commented on articles/advanced/async-tasks.adoc
> +            Thread.sleep(6000);
I would use the same timeout in all snippets to avoid confusion

2022-08-01 12:58 UTC, mcollovati commented
In the introduction we say that the guide shows how to `Allows the user to continue interacting with the application while the task is running, possibly allowing the user to cancel the task.`

It would be nice to add an example on how to cancel the task

2022-08-01 13:03 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +            Thread.sleep(10000);
```suggestion
            Thread.sleep(6000);
```

2022-08-01 13:04 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +            Thread.sleep(6000);
fixed

2022-08-01 13:06 UTC, tarekoraby commented
> In the introduction we say that the guide shows how to `Allows the user to continue interacting with the application while the task is running, possibly allowing the user to cancel the task.`
> 
> It would be nice to add an example on how to cancel the task

@dmitrilc can you please evaluate how to demonstrate the canceling of a task? It would indeed be good to have as @mcollovati point out (assuming that it can be done minimally without adding too much complication).

2022-08-02 01:25 UTC, dmitrilc commented
@tarekoraby It is possible and does not seem to be that involved. Please check [#94dfbfd3](https://github.com/vaadin/docs/pull/1553/commits/94dbfd36bb8d338cf0d50a1095ed9e24b5626de3) for how it might look like.

2022-08-02 11:29 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +            var cancelButton = new Button("Cancel", _e -> {
```suggestion
            Button cancelButton = new Button("Cancel", _e -> {
```

There is nothing inherently wrong with using `var`, but let's just not use it in this guide for consistency.

2022-08-02 11:30 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +<3> When the task is cancelled, we remove the [classname]`Button`.
```suggestion
<3> When the task is completed or canceled, we remove the cancel [classname]`Button`.
```

2022-08-02 17:01 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +For example, a task that requires fetching a large amount of data from the database can take a long time until it is finished.
```suggestion
For example, a task that requires fetching a large amount of data from the database can take a long time to finish.
```

2022-08-02 17:03 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +This happens because Vaadin is waiting for the long-running task to finish before it sends back the response to the user, at which point the user can continue interacting with the application.
```suggestion
This happens because Vaadin is waiting for the long-running task to finish before it sends the response back to the user, at which point the user can continue interacting with the application.
```

2022-08-02 17:04 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +From the side of Vaadin UI, a response to the user request is immediately sent back to the browser, and thus the user can continue interacting with the application right away without being blocked by
```suggestion
From the Vaadin UI side, a response to the user request is immediately sent back to the browser, and thus the user can continue interacting with the application right away without being blocked by the long-running task.
```

2022-08-02 17:06 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +This is how [filename]#MainView.java# could look like now:
```suggestion
This is how [filename]#MainView.java# could look now:
```

2022-08-02 17:07 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +We can do both changes in the same class as illustrated in the following [classname]`Application` class (which both extends [classname]`SpringBootServletInitializer` and implements [interfacename]`Ap
```suggestion
We can make both changes in the same class as illustrated in the following [classname]`Application` class (which both extends [classname]`SpringBootServletInitializer` and implements [interfacename]`AppShellConfigurator`):
```

2022-08-02 17:08 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +<5> We need to modify the `updateUi()` method to additionally receive the [classname]`ProgressBar` argument.
```suggestion
<5> We need to modify the [methodname]`updateUi()` method to additionally receive the [classname]`ProgressBar` argument.
```

2022-08-02 17:10 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +. The running task must be https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/concurrent/Future.html#cancel(boolean)[interuptable].
```suggestion
. Your [annotationname]`@Async` method must return a [interfacename]`Future`.
. The running task must be https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/concurrent/Future.html#cancel(boolean)[interruptable].
```

2022-08-02 17:11 UTC, dougjewsbury commented on articles/advanced/async-tasks.adoc
> +The modified [classname]`MainView` class below shows how to add a [classname]`Button` to cancel the long running task.
```suggestion
The modified [classname]`MainView` class below shows how to add a [classname]`Button` to cancel the long-running task.
```

2022-08-03 06:34 UTC, mshabarov requested changes

2022-08-03 06:34 UTC, mshabarov commented on articles/advanced/async-tasks.adoc
> +                    s -> updateUi(ui, "Task finished: " + s), // <2>
I would suggest to not use of the single character names for variables in lambdas (and for method parameters as well).
Let's use meaningful names: `message`, `click`, `event`, `exception`, `progressBar` and so on.

2022-08-03 06:34 UTC, mshabarov commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
Would it be better to use `event.getSource().getUI()` instead?

2022-08-03 06:34 UTC, mshabarov commented on articles/advanced/async-tasks.adoc
> +image::images/async-progress-bar.gif[Long-Running ProgressBar, width=50%]
This gif doesn't show the click onto another button, i.e. that the UI is not blocked during the long running task. Could you add that?

2022-08-03 06:59 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +                    s -> updateUi(ui, "Task finished: " + s), // <2>
Agreed. @dmitrilc can you please fix.

2022-08-03 07:05 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
What is the advantage of doing so? I like to mention `UI.getCurrent()` in examples because it's something that people can use even outside of event listener.

2022-08-03 07:05 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +image::images/async-progress-bar.gif[Long-Running ProgressBar, width=50%]
@dmitrilc is it possible to create a new gif?

2022-08-03 09:09 UTC, mshabarov commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
`getUI` API signals that the UI might be not available, for example when it is being invoked before the component is attached. And it's a part of events API, so designed to be called instead.
`UI.getCurrent` relies on a different logic with thread locals and bound to the Vaadin Request lifecycle and is not available outside of it.
IMHO `UI.getCurrent` is more error prone if used everywhere.
Not insist, but I would use `getUI` if the current context allows to do it.

2022-08-03 09:51 UTC, tarekoraby commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
@dmitrilc kindly update the examples to use `e.getSource().getUI()` too.

2022-08-03 11:49 UTC, dmitrilc commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
@tarekoraby then should we also modify the cookbook recipe https://cookbook.vaadin.com/long-running-task? It uses `UI.getCurrent()` as well.

While you are at it, you can update the `addCallback()` call to use the lambdas to improve readability as well.

2022-08-03 14:12 UTC, dmitrilc commented on articles/advanced/async-tasks.adoc
> +image::images/async-progress-bar.gif[Long-Running ProgressBar, width=50%]
Done

2022-08-03 14:12 UTC, dmitrilc commented on articles/advanced/async-tasks.adoc
> +                    s -> updateUi(ui, "Task finished: " + s), // <2>
Done with https://github.com/vaadin/docs/pull/1553/commits/c75dd9e88ebadf369768d76824ccf65b6dd325a0

2022-08-03 14:13 UTC, dmitrilc commented on articles/advanced/async-tasks.adoc
> +            UI ui = UI.getCurrent(); // <1>
@tarekoraby Because that method call returns an Optional, I have decided to change a code a little more to improve readability https://github.com/vaadin/docs/pull/1553/commits/c75dd9e88ebadf369768d76824ccf65b6dd325a0

2022-08-04 07:52 UTC, tarekoraby approved these changes

2022-08-04 07:58 UTC, jouni reviewed
Just a thought, but I was wondering if a live, rendered code example would be better than gif animations?

At least from a maintenance perspective rendered examples are preferred, so we know if the code is actually working or not. 

But perhaps from a reader perspective the animations are nicer, as you can just watch without interacting with the UI?

2022-08-04 08:48 UTC, tarekoraby commented
@jouni I thought about that, but then for these specific examples to work, we will need to add some annotations to the `SpringBootServletInitializer` of the docs (specifically, `@Push` and `@EnableAsync`).

2022-08-05 08:25 UTC, mshabarov approved these changes

2022-08-05 11:36 UTC, tarekoraby commented
I tried and failed to implement the code snippets here as a rendered code example. I'll merge this for now, and the rendered code can be implemented in a separate PR.

2022-08-05 11:48 UTC, merged