Backport view path parameter improvements docs
vaadin/docs pull request #156
Opened 2021-02-01 15:02 UTC by mshabarov

Related-to: https://github.com/vaadin/flow/issues/9850

2021-02-02 21:05 UTC, jouni commented
Is this basically a cherry-pick from `latest`? Or are there some additional modifications?

If it’s just a cherry-pick, I won’t spend time reading through, just blindly accept and merge.

2021-02-03 08:31 UTC, mshabarov commented
>Is this basically a cherry-pick from latest? Or are there some additional modifications?

Yes, this is a cherry pick from master.

2021-02-05 11:54 UTC, mshabarov commented
Url parameters template feature has been backported and released in flow `2.5.0.alpha2`.

2021-02-09 13:04 UTC, jouni requested changes

2021-02-09 13:04 UTC, jouni commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +
```suggestion
```
Add as a "since" annotation on the `= Route Templates` heading instead.
```asciidoc
[role="since:com.vaadin:vaadin@V14.5"]
= Route Templates
```

2021-02-09 13:35 UTC, jouni commented
@mshabarov, the last commit did not include the [role="..."] annotation.

2021-02-09 13:58 UTC, jouni reviewed
I’ll let @taefi check that the content is okay.

2021-02-09 13:58 UTC, jouni approved these changes

2021-02-09 16:44 UTC, taefi requested changes

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Route template parameters are defined as segments within `@Route`, `@RouteAlias` and `@RoutePrefix` annotation values.
```suggestion
Route template parameters are defined as segments within `@Route`, `@RouteAlias`, and `@RoutePrefix` annotation values.
```

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Parameter values are strings, and convenience methods (described later) exist for converting them to numeric and Boolean types.
```suggestion
Parameter values are strings, and convenient methods (described later) exist for converting them to numeric and Boolean types.
```

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +The final route template is the result of the value composition from the `@Route`, `@RouteAlias` and `@RoutePrefix` annotations as explain in <<tutorial-router-layout#,Router Layouts and Nested Route
```suggestion
The final route template is the result of the value composition from the `@Route`, `@RouteAlias`, and `@RoutePrefix` annotations as explained in <<tutorial-router-layout#,Router Layouts and Nested Router Targets>>.
```

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Optional parameters are greedily matched from left to right.
```suggestion
Optional parameters are eagerly matched from left to right.
```

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Regarding optional parameters which are greedily matched from left to right, giving the template `path/to/:param1?([0-9]\*)/:param2?([a-z]*)` following urls match it:
```suggestion
Regarding optional parameters which are eagerly matched from left to right, giving the template `path/to/:param1?([0-9]\*)/:param2?([a-z]*)` following urls match it:
```

2021-02-09 16:44 UTC, taefi commented on articles/flow/routing/tutorial-router-url-parameters.asciidoc
> +A `Location` object represents a relative URL made up of path segments and query parameters, but without the hostname, for example `new Location ("book/search?keyword=Vaadin")`.
```suggestion
A `Location` object represents a relative URL made up of path segments and query parameters, without the hostname, for example `new Location ("book/search?keyword=Vaadin")`.
```

2021-02-09 19:52 UTC, jouni commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +* `_modifier_` is optional and may be one of the following:
The original, "one of the following" is correct.

2021-02-09 19:53 UTC, jouni commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +** `_?_` defines an optional parameter which might be missing from the url being resolved,
"url" should be uppercase, "URL"

2021-02-09 19:55 UTC, jouni commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Parameter values are strings, and convenience methods (described later) exist for converting them to numeric and Boolean types.
Not sure about this. I think both are acceptable, but I prefer "convenience methods", it feels like common terminology in programming.

2021-02-10 08:36 UTC, mshabarov commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Route templates define the mean of including parameters into a route.
Possibility/feature

2021-02-10 08:44 UTC, mshabarov commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +* `_modifier_` is optional and may be one of the following:
Let keep it as it is

2021-02-10 08:45 UTC, mshabarov commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Parameter values are strings, and convenience methods (described later) exist for converting them to numeric and Boolean types.
Let's keep it as it is

2021-02-10 11:48 UTC, taefi commented on articles/flow/routing/tutorial-router-templates.asciidoc
> +Route templates define the mean of including parameters into a route.
Then I suggest: 
```suggestion
Route templates define the possibility of including parameters into a route.
```

2021-02-10 11:56 UTC, taefi approved these changes

2021-02-15 07:42 UTC, jouni reviewed
Not a blocker (with the “Delete this file” notes). The entire `/articles/flow/src` folder should be removed eventually. Those files should not be used for anything anymore. They are still there in case some existing articles reference them using `include::[]` at the moment. But we should not introduce more files there.

If you want to validate that a certain code example works, that source needs to go under `/src`, and then use `include::[]` in the articles to pull in the relevant parts from it.

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-router-dynamic-routes.asciidoc
> +Two available targets are available:
```suggestion
Two targets are available:
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-router-url-parameters.asciidoc
> +The url defined in the `@Route` annotation must not include the parameter template placeholder.
```suggestion
The URL defined in the `@Route` annotation must not include the parameter template placeholder.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-router-url-parameters.asciidoc
> +It is automatically added internally to the url template.
```suggestion
It is automatically added internally to the URL template.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-annotation.asciidoc
> +It includes support for nested routes, access to route parameters and more.
```suggestion
It includes support for nested routes, access to route parameters, and more.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-annotation.asciidoc
> +For example, MyEditor becomes "myeditor", PersonView becomes "person" and MainView becomes "".
```suggestion
For example, `MyEditor` becomes `"myeditor"`, `PersonView` becomes `"person"` and `MainView` becomes `""`.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-exception-handling.asciidoc
> +* This returns a 404 http response and displays the `setText` to the user.
```suggestion
* This returns a 404 HTTP response and displays the `setText` to the user.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-navigation.asciidoc
> +*Example*: Using `RouterLink` for a simple navigation targets.
```suggestion
*Example*: Using `RouterLink` for a simple navigation target.
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-navigation.asciidoc
> +== Using Standard "href" Links
```suggestion
== Using Standard Links
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/routing/tutorial-routing-url-generation.asciidoc
> +== Navigation Target with HasUrlParameter
```suggestion
== Navigation Target With HasUrlParameter
```

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/QueryParameterTutorial.java
> +/*
Delete this file

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/RouteTemplatesBasics.java
> +/*
Delete this file

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/RouteTemplatesConfiguration.java
> +/*
Delete this file

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/RouteTemplatesModifier.java
> +/*
Delete this file

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/RouteTemplatesRegex.java
> +/*
Delete this file

2021-02-15 07:42 UTC, jouni commented on articles/flow/src/main/java/com/vaadin/flow/tutorial/routing/RouterNavigation.java
>  /*
Delete this file

2021-02-15 07:44 UTC, jouni commented on articles/flow/routing/tutorial-routing-url-generation.asciidoc
> +== Navigation Target with URL Templates
```suggestion
== Navigation Target With URL Templates
```

2021-02-15 10:16 UTC, merged