Add guide on storing sensitive data
vaadin/docs pull request #1562
Opened 2022-07-19 17:32 UTC by dmitrilc

Fix #1547.

2022-08-01 12:40 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +layout: page
```suggestion
layout: page
order: 250
```

2022-08-01 20:24 UTC, dmitrilc commented
@tarekoraby I added the instructions for Windows as well. It doesn't seem that long.

2022-08-02 11:18 UTC, tarekoraby requested changes

2022-08-02 11:18 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +If your `application.properties` file contains sensitive information, such as database URL, username, or password,
This appears to be an incomplete sentence.

2022-08-02 11:18 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +It is often a bad practice to put sensitive information, such as database URL, username, or password in your `application.properties` files. One of the easiest way to externalize sensitive informatio
> It is often a bad practice to put sensitive information ... in your `application.properties` files.

We should say a word or two about why is it a bad practice to do so. It is also not just about `application.properties` file: it is a bad practice to store sensitive info and git commit them anywhere in the project.

2022-08-02 11:18 UTC, tarekoraby commented on articles/integrations/databases/mariadb.adoc
> +It is bad practice to store database uri, username, and passwords in the `application.properties` file.
I think "uri" should be capitalized.

2022-08-05 12:06 UTC, tarekoraby requested changes

2022-08-05 12:06 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +For example, a Vaadin Start project configured to use PostgreSQL might contain the sensitive information below in the `application.properties` file.
```suggestion
For example, a https://start.vaadin.com/[Vaadin Start] project configured to use PostgreSQL might contain the sensitive information below in the `application.properties` file.
```

2022-08-05 12:06 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +
```suggestion

This guide demonstrates two ways to externalize sensitive data:
* Using system environment variables
* Using an external properties file

```

2022-08-05 12:06 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +On Linux and MacOS, to temporarily set the environment variables, you can use the commands below in your IDE's terminal.
```suggestion
On Linux and macOS, to temporarily set the environment variables, you can use the commands below in your IDE's terminal.
```

2022-08-05 12:06 UTC, tarekoraby commented on articles/security/advanced-topics/external-configuration.adoc
> +Assuming that you have a file called `db.properties` to hold your database secrets,
```suggestion
Assuming that you have ab external file called `db.properties` to hold your database secrets,
```

2022-08-09 07:22 UTC, jouni commented on articles/integrations/databases/mariadb.adoc
> +====
Since this content is repeated in multiple pages, I would extract that into a single place and include it from there.

2022-08-09 16:45 UTC, dmitrilc commented on articles/integrations/databases/mariadb.adoc
> +====
@tarekoraby jouni's suggestion is similar to [mine](https://github.com/vaadin/docs/pull/1562#issuecomment-1201539189). How would you like to proceed?

2022-08-09 17:40 UTC, tarekoraby commented on articles/integrations/databases/mariadb.adoc
> +====
Jouni's suggestion is to have the same text in one place, then to import this same "source of truth" in the three different articles. Your earlier suggestion (if I understood it correctly) involves combining the three database articles into one (which I'm against).

2022-08-09 17:47 UTC, tarekoraby commented on articles/integrations/databases/mariadb.adoc
> +====
@dmitrilc check for example how the same ascidoc file: https://github.com/vaadin/docs/blob/latest/articles/components/ds-resources/foundation/_shared.asciidoc
is being imported in multiple pages:

- https://github.com/vaadin/docs/blob/bedcaa0dca00e56dc7007f81f6cefbefe989d60b/articles/components/ds-resources/foundation/color/index.asciidoc
- https://github.com/vaadin/docs/blob/f859b5bfb0a2dc3488fcaf13e8b35aef335fde1a/articles/components/ds-resources/foundation/typography/material.asciidoc
- And others

That's what Jouni is rightly suggesting.

2022-08-09 21:47 UTC, dmitrilc commented on articles/integrations/databases/mariadb.adoc
> +====
> 

Gotcha! I didn't know that importing was a thing. I like that idea, too.

2022-08-15 20:22 UTC, dmitrilc commented on articles/integrations/databases/mariadb.adoc
> +====
This is done. Tarek created `_shared.adoc` and used "include" directives.

2022-08-22 11:15 UTC, tarekoraby approved these changes

2022-08-22 11:52 UTC, merged