Add note about external icon sets
vaadin/docs pull request #1586
Opened 2022-08-03 12:30 UTC by tarekoraby

Related to #721.

2022-08-03 17:16 UTC, dougjewsbury commented on articles/components/icons/index.asciidoc
> +Other than the built-in Lumo and Vaadin icons, you can also use icons from other icon sets.
```suggestion
Apart from the built-in Lumo and Vaadin icons, you can also use icons from other icon sets.
```

2022-08-03 17:17 UTC, dougjewsbury commented on articles/components/icons/index.asciidoc
> +Sill, as an example, you can consider how projects generated from https://start.vaadin.com[Vaadin Start] use the icons from the https://icons8.com/line-awesome/[Line Awesome] icon set.
```suggestion
Unfortunately, this implies that there are no standard, simple steps to follow that would work for all icon sets.
Nevertheless, as an example, you can consider how projects generated from https://start.vaadin.com[Vaadin Start] use the icons from the https://icons8.com/line-awesome/[Line Awesome] icon set.
```

2022-08-04 06:08 UTC, rolfsmeds requested changes

2022-08-04 06:08 UTC, rolfsmeds commented on articles/components/icons/index.asciidoc
> +However, different icon sets tend to be implemented rather differently.
```suggestion
However, icon sets come in many different formats, which means that there is no standard way to integrate and use them with Vaadin that would work for all icon sets.
```

2022-08-04 06:08 UTC, rolfsmeds commented on articles/components/icons/index.asciidoc
> +== External Icon Sets
```suggestion
== Third-party Icon Sets
```

2022-08-11 10:45 UTC, jouni commented
Added a similar note in #1612

2022-08-11 12:20 UTC, tarekoraby commented
Closing in favor of https://github.com/vaadin/docs/pull/1612.

2022-08-11 12:20 UTC, closed without merging