docs: added note about new RouterLink constructors (#1587)
vaadin/docs pull request #1588
Opened 2022-08-04 07:34 UTC by MarcinVaadin

2022-08-04 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=1588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=1588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=1588) it.</sub>

2022-08-04 07:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=1588) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=1588) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=1588) it.</sub>

2022-08-04 07:56 UTC, jouni commented on articles/routing/navigation.asciidoc
> +
Always define a title for admonitions. It’s usually quite easy by promoting the most important information from the admonition to be the title.

Break sentences on new lines. This makes editing slightly easier (to move lines) and also more easily indicates if you have really long sentences (which are usually harder for the reader to understand).

I think a `CAUTION` admonition is in order (vs a more discrete `NOTE`), as this warns about build errors.

Avoid version specific text if possible, to keep the documentation texts “evergreen”.

```suggestion
.Using ambiguous constructor calls will cause build errors
[CAUTION]
For example, [methodname]`new RouterLink(null, viewClass)` can refer to both [methodname]`public RouterLink(String text, Class<? extends Component> navigationTarget)` and [methodname]`public RouterLink(Router router,
Class<? extends Component> navigationTarget)`.

```

2022-08-04 08:16 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> +
Yes, thanks for remarks, suggestion committed.

2022-08-05 09:44 UTC, mshabarov requested changes

2022-08-05 09:44 UTC, mshabarov commented on articles/routing/navigation.asciidoc
> +.Using ambiguous constructor calls will cause build errors
The idea behind implemented feature was to provide a constructor without text.
Thus, I propose to just mention this possibility here in the docs: developers don't need to call `RouterLink(String text, Class<? extends Component> navigationTarget)` and pass `""` or `null` there, but instead call the constructor with only class as a parameter. I don't think we have to tell readers about ambiguous constructors.

2022-08-05 12:17 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> +.Using ambiguous constructor calls will cause build errors
> I don't think we have to tell readers about ambiguous constructors. 

so maybe that docs change could be dropped?

2022-08-05 12:21 UTC, mshabarov commented on articles/routing/navigation.asciidoc
> +.Using ambiguous constructor calls will cause build errors
Yes.
Only mention that the text parameter is optional and there is a constructor available without it.

2022-08-05 13:00 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> +.Using ambiguous constructor calls will cause build errors
How about:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/106965834/183082459-2349b413-0e2b-4c12-9239-b4d5a71a2a59.png">

2022-08-09 06:25 UTC, MarcinVaadin commented
Update simplified to:
<img width="916" alt="Screenshot 2022-08-09 at 08 24 32" src="https://user-images.githubusercontent.com/106965834/183579204-b71bb122-8b3e-4887-833b-f78558daeb3c.png">

2022-08-09 06:33 UTC, mshabarov commented on articles/routing/navigation.asciidoc
> +Create [classname]`RouterLink` without text using [methodname]`new RouterLink(viewClass)`.
```suggestion
Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
```

2022-08-09 06:33 UTC, mshabarov approved these changes

2022-08-09 07:15 UTC, mshabarov commented
Need to resolve conflicts with master

2022-08-09 07:18 UTC, jouni commented on articles/routing/navigation.asciidoc
> +Create [classname]`RouterLink` without text using [methodname]`new RouterLink(viewClass)`.
I don't think there’s a need to use an admonition here. The sentence works just fine as part of the regular flow of content.

```suggestion
You can create a [classname]`RouterLink` without providing an explicit label using the [methodname]`new RouterLink(viewClass)` method.
```

2022-08-09 07:23 UTC, tarekoraby requested changes

2022-08-09 07:23 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
We need to indicate to the reader that this feature is only available from V23.2. @jouni is there a way to attach the since tag to the note?

(Btw, I wonder if this is better as a "TIP", not a "NOTE").

2022-08-09 07:25 UTC, jouni commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
> is there a way to attach the since tag to the note?

`[since:com.vaadin:vaadin@V23.2]#Some sentence here that only applies for V23.2#`

2022-08-09 07:26 UTC, jouni commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
> (Btw, I wonder if this is better as a "TIP", not a "NOTE").

Like I posted before, I don't think this needs to be an admonition at all.

2022-08-09 08:16 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
```suggestion
[since:com.vaadin:vaadin@V23.2]#Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.#

*Example*: Using [classname]`RouterLink` with an icon instead of text.
[source,java]
----
void buildMenu() {
    Icon vaadinIcon = new Icon(VaadinIcon.HOME);
    RouterLink link = new RouterLink(HomeView.class);
    link.add(vaadinIcon);
    menu.add(link);
}

@Route(value = "")
public class HomeView extends Component {
}
----
```

2022-08-09 08:16 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
Agreed.

2022-08-09 08:18 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> +Create [classname]`RouterLink` without text using [methodname]`new RouterLink(viewClass)`.
I like my suggestion below better as it includes an example and the since tag.

2022-08-10 05:49 UTC, mshabarov approved these changes

2022-08-10 05:54 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> +Use [methodname]`new RouterLink(viewClass)` if you want to embed other elements into [classname]`RouterLink` without text, for example images or icons.
Second review comments applied

2022-08-10 07:07 UTC, merged

2022-08-10 07:08 UTC, tarekoraby commented on articles/routing/navigation.asciidoc
> -
@MarcinVaadin @mshabarov why were these lines removed?

2022-08-10 08:57 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> -
There was a conflict during merge, maybe I've resolved it wrongly, let me check.

2022-08-10 09:00 UTC, mshabarov commented on articles/routing/navigation.asciidoc
> -
When I was checked, they were removed and moved few lines below...Let's fix it in another PR

2022-08-10 09:09 UTC, MarcinVaadin commented on articles/routing/navigation.asciidoc
> -
Revert PR created https://github.com/vaadin/docs/pull/1609