add v15+ upgrading guide
vaadin/docs pull request #159
Opened 2021-02-02 11:56 UTC by haijian-vaadin

2021-02-03 08:15 UTC, jouni commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +=== Ignore The `sw-runtime-resources-precache.js` File
Not sure if this is the most accurate title. Feel free to rephrase if needed, but avoid using code formatting and file names in headings.
```suggestion
=== Ignore Service Worker Resources Precache File
```

2021-02-03 13:29 UTC, joheriks requested changes

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/index.asciidoc
> +pass:[<!-- vale Vaadin.Versions = NO -->]
This content seem to cause an empty page to be shown when clicking on "Upgrading from Vaagin 15+ to Latest" in the sidebar (instead of just expanding the tree as for the other upgrade sections).

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +Upgrading from a Vaadin 15+ version to the latest is in general straightforward, nevertheless, a few breaking changes need to take into account when upgrading:
Maybe "[...] breaking changes need to *be* taken into account [...]" or "[...] breaking changes to take into account [...]". The colon at the end looks misplaced , should end with period.

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +A field with `@Id` annotation in Java is now optional in the generated TypeScript code.
From the first reading understood this as the field being optional, i.e., may not be generated. Perhaps "[...] is now of optional type [...]" to clarify.

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +The Spring Security configuration requires some changes for the service worker related files.
"[...] to the service worker related files".

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +----
It seems too verbose to have this code snippet twice. Can it be done with only the latter version.

2021-02-03 13:29 UTC, joheriks commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +Now you need to ignore the service worker initiated requests, otherwise the access attempts will be overridden by the service worker requests and Spring cannot redirect you to the intended page.
Could be good to add a sentence here that this can be done by inspecting the `Referer` header as an explanation to the below code.

2021-02-04 06:26 UTC, Haprog requested changes

2021-02-04 06:30 UTC, Haprog requested changes

2021-02-04 06:30 UTC, Haprog commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +Upgrading from a Vaadin 15+ version to the latest is in general straightforward, nevertheless, a few breaking changes to take into account when upgrading.
```suggestion
Upgrading from a Vaadin 15+ version to the latest is in general straightforward, however, there are some breaking changes to consider when upgrading.
```

2021-02-04 06:31 UTC, Haprog commented on articles/guide/upgrading/v15-upgrade/overview.asciidoc
> +Upgrading from a Vaadin 15+ version to the latest is in general straightforward, nevertheless, a few breaking changes need to take into account when upgrading:
Updated suggestion based on latest version below.

2021-02-04 07:53 UTC, joheriks approved these changes

2021-02-04 08:05 UTC, Haprog approved these changes

2021-02-04 08:40 UTC, merged

2021-02-04 08:42 UTC, jouni commented
In the future, `OneLinePerSentence` should not get triggered on source code block titles (e.g. `.SecurityConfiguration.java`).