Fix typos and clarifying lazy data binding
vaadin/docs pull request #1604
Opened 2022-08-09 17:47 UTC by dmitrilc

This PR attempts to improve clarity of the lazy data binding documentation.

2022-08-09 17:48 UTC, dmitrilc commented
This is a work in progress.

2022-08-09 22:12 UTC, dmitrilc commented
Next step: explains how the component creates the Query and which method does it call when it needs more data

2022-08-10 08:50 UTC, tarekoraby requested changes

2022-08-10 08:50 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +Items can be basic objects, such as strings, numbers, plain old Java objects (POJOs), data transfer objects (DTOs) or Java Persistence API (JPA) entities.
I don't think that this reformulation is correct. The original text was more accurate as it says that items can be either:
- Basic objects (such as string or numbers)
- Or, POJOs (such as DTOs and JPA entities)

With the proposed reformulation, the text will (wrongly in my opinion) say that items can only be _basic objects_, and that examples of basic objects include:
- strings
- numbers
- POJOs (which to my mind, are not _basic objects_)
- DTOs (also not basic objects, and they are a subset POJOs)
- JPA entities (also better described as POJOs, not basic objects).

2022-08-10 08:50 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
As these four points are very much related, I suggest combining them into just one point with four sentences.

2022-08-10 08:50 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +<7> The back end returns a [classname]`List`, so we need to convert it to a [classname]`Stream`.
```suggestion
<7> In this example, it is assumed that the back end returns a [classname]`List`, so we need to convert it to a [classname]`Stream`.
```

Backends do not always have to return `List`. Our language should clarify that this is just an example.

2022-08-10 15:59 UTC, dmitrilc commented on articles/binding-data/data-provider.asciidoc
> +Items can be basic objects, such as strings, numbers, plain old Java objects (POJOs), data transfer objects (DTOs) or Java Persistence API (JPA) entities.
You have a good point, and your comment just gave me an idea. I will change it to

> Items can be basic objects (such as string or numbers), or POJOs (such as DTOs and JPA entities).

instead.

2022-08-10 16:03 UTC, dmitrilc commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
One point with four sentences would be too hard to follow. I prefer them as separate points instead.

2022-08-11 07:28 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
If we don't combine the four points, then we have to do something about callouts number 3 and 6. Callout 3 is placed next to `fetchPersons(` but it's not really describing anything specific about this method. Callout 6 is weirdly placed next to the closing bracket.

Let's also keep in mind that we don't have to mention every detail in the callouts. It is also okay to mention some advanced notes and caveats in the text after/before the code snippet.

2022-08-15 21:28 UTC, dmitrilc commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
I see your points now. 

I intended callout 3 to signify to developers that they should only fetch what they need. Perhaps the language was not obvious enough. What do you think of the version below?

```suggestion
<3> When fetching for more data, you should utilize the [classname]`Query`'s properties to litmit the amount of data to fetch.
<4> The link:https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/data/provider/Query.html#getOffset()[_offset_] refers to the first index of the item to fetch.
<5> The link:https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/data/provider/Query.html#getLimit()[_limit_] refers to the number of items to fetch.
```

You have a good point about callout 6. What do you think about rephrasing it a little and moving it to right after the sentence
> When more data is needed, the component passes a link:https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/data/provider/Query.html[[classname]`Query`] object as a parameter to your callback methods, where you can check what part of the data set is needed.

This is how it would look like after
> When more data is needed, the component passes a link:https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/data/provider/Query.html[[classname]`Query`] object as a parameter to your callback methods, where you can check what part of the data set is needed. 
The component will set the properties of the [classname]`Query` when it creates the [classname]`Query` object.

2022-08-17 06:12 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
> <3> When fetching for more data, you should utilize the [classname]`Query`'s properties to litmit the amount of data to fetch.

I like the wording as it clarifies the meaning, but then isn't this sentence better placed next to ` query.getLimit()` (which is currently point number 5)?

> You have a good point about callout 6. What do you think about rephrasing it a little and moving it to right after the sentence

Yes, I think your suggestion makes sense.

2022-08-17 13:28 UTC, dmitrilc commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
Thank you for the reminder. I totally forgot `Query.getLimit()` literally mean **limit**.

2022-08-17 13:44 UTC, dmitrilc commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
I have committed the changes. Can you please check?

2022-08-22 12:43 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
>  Currently, only `Grid` and `ComboBox` properly support lazy data binding.
```suggestion

Currently, only `Grid` and `ComboBox` properly support lazy data binding.

Lazy data binding works as follows:

. The user performs an action that requires the component to display more data.
For example, the user might be scrolling down the list of items in a `Grid` component.
. The component automatically detects that more data is needed, and it passes a link:https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/flow/data/provider/Query.html[`Query`] object as a parameter to your callback methods.
This object contains the necessary information about the data that should be displayed next to the user.
. Your callback methods use this [classname]`Query` object to fetch only the required data (usually from the back end) and return it to the component, which displays it automatically once the data is available.
```

2022-08-22 12:44 UTC, tarekoraby commented on articles/binding-data/data-provider.asciidoc
> +<6> The properties of a [classname]`Query` object are determined by the component when it creates the [classname]`Query` object.
It works now, thanks.
I added another suggestion to expand a bit on how the whole lazy data binding process works.

2022-08-23 06:54 UTC, tarekoraby approved these changes

2022-08-23 07:08 UTC, merged