feat: add iconset generator
vaadin/docs pull request #1612
Opened 2022-08-10 13:53 UTC by jouni

Allow users to generate `<vaadin-iconset>` definitions by “uploading” a folder of `.svg` icons. The files are not actually uploaded anywhere, the generator works completely in the browser.

The generator code is of prototype quality, but it does what it needs to do. No proper error handling yet, so there’s no helpful error messages if someone tries to upload something else than `.svg` files.

2022-08-11 07:52 UTC, tarekoraby commented
Note that #1586 is aiming to add a caveat about the complexity of adding external icon sets. Is such caveat still valid in light of this iconset generator? Should we have the caveat for non-SVG iconsets?

2022-08-11 08:23 UTC, jouni commented
Good point. 

Yeah, I think this generator makes the use of SVG icons easy. Font icons are still more complicated to use, and the Start templates offer an example for that.

If you think it’s okay, I could move the caveat text to this PR instead.

2022-08-11 08:25 UTC, jouni commented
Would be nice to get the preview build fixed…

2022-08-11 08:42 UTC, tarekoraby commented
> If you think it’s okay, I could move the caveat text to this PR instead.

@jouni please do that.

2022-08-11 12:18 UTC, tarekoraby commented
This PR should fix https://github.com/vaadin/docs/issues/721.

2022-08-11 12:22 UTC, tarekoraby commented on articles/components/icons/index.asciidoc
> +== Creating a Custom Icon Set
A nitpick, but is it "Creating" or something like "Using" or "Importing" a custom icon set?

2022-08-11 12:30 UTC, jouni commented on articles/components/icons/index.asciidoc
> +== Creating a Custom Icon Set
Right, “creating” might indeed give the wrong impression. How about:

```suggestion
== Using a Third-Party Icon Set
```

2022-08-11 12:40 UTC, tarekoraby commented on articles/components/icons/index.asciidoc
> +You can then download them and place them in your project.
This sounds a bit abstract. I personally have some experience creating addons for another icon set. Yet, reading this doesn't make it clear to me where to place those files, nor how to use them in my project. Could we clarify this with some specific instructions?

2022-08-11 13:01 UTC, jouni commented on articles/components/icons/index.asciidoc
> +You can then download them and place them in your project.
I try to explain it here: https://github.com/vaadin/docs/pull/1612/files#diff-6173ef28a9a9f1df3042809fc52b9384cd19405135f48a6300b035974795e448R290-R292

2022-08-11 13:02 UTC, jouni commented on articles/components/icons/index.asciidoc
> +You can then download them and place them in your project.
For using the icons, perhaps there could be more instructions, but I thought the earlier content on the page would suffice.

2022-08-12 09:08 UTC, jouni commented
Finally we have the preview build 🥳

2022-08-12 09:35 UTC, dougjewsbury commented on articles/components/icons/index.asciidoc
> +Third-party icon sets come in many different formats, and there is not a single integration method that works for every format.
```suggestion
Third-party icon sets come in many different formats, and there is no single integration method that works for every format.
```

2022-08-12 11:07 UTC, jouni commented on articles/components/icons/index.asciidoc
> +You can then download them and place them in your project.
I tried to improve this a little bit in https://github.com/vaadin/docs/pull/1612/commits/2054809864f518358b2d99ace1863dbbb6a2a09a

2022-08-13 16:42 UTC, tarekoraby commented
This PR looks good to me. But maybe someone who knows a bit more than me about icon sets can be a better judge.

2022-08-16 07:39 UTC, jouni commented
Summoning the great @web-padawan for the task – can you spot some grand issues with this? Please ignore the poor code quality, all the `// @ts-ignore` and such. Could surely be better, but I didn't think it would be worth the effort to make this much cleaner. Might make it easier to maintain, but it smells a bit like premature optimization.

2022-08-24 11:36 UTC, web-padawan requested changes
There are way too many `@ts-ignore` comments. We could just use JS instead.  
Let me try to fix at least some of them before I can approve this PR.

2022-08-24 11:36 UTC, web-padawan commented on frontend/demo/component/icons/iconset-generator.ts
> +    input.addEventListener('change', this.handleFiles.bind(this));
Why don't we use `@change=${this.handleFiles}` listener in the template?

2022-08-24 11:36 UTC, web-padawan commented on frontend/demo/component/icons/iconset-generator.ts
> +  async handleFiles() {
We could probably use `event.target` here to get a reference to the `<input>` element.

2022-08-24 11:36 UTC, web-padawan commented on frontend/demo/component/icons/iconset-generator.ts
> +    const nameInput = this.shadowRoot?.querySelector('.name') as HTMLInputElement;
```suggestion
    const nameInput = this.renderRoot.querySelector('.name') as HTMLInputElement;
```

2022-08-26 09:05 UTC, jouni commented
> There are way too many @ts-ignore comments. We could just use JS instead.

I implemented this generator in JavaScript initially, and then copied it to the docs project. But DSP has this limitation that only `.ts` or `.java` files can be “rendered”, so I had to use TypeScript: https://github.com/vaadin/docs-app/blob/master/src-node/asciidoc.js#L156-L164

2022-08-26 09:07 UTC, jouni commented on frontend/demo/component/icons/iconset-generator.ts
> +    input.addEventListener('change', this.handleFiles.bind(this));
I had trouble getting browsers to accept files via drag'n'drop on the file input, and I believe this had an accept on it. Not 100% sure.

2022-08-26 10:06 UTC, web-padawan commented on frontend/demo/component/icons/iconset-generator.ts
> +    input.addEventListener('change', this.handleFiles.bind(this));
Tested and it works for me in Chrome, Firefox and Safari.

2022-08-26 10:06 UTC, web-padawan approved these changes

2022-08-26 10:06 UTC, merged