Improve theming documentation
vaadin/docs pull request #1615
Opened 2022-08-11 13:27 UTC by tarekoraby

2022-08-19 13:37 UTC, rolfsmeds requested changes

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/importing-stylesheets.adoc
> +The `@CssImport` annotation can also be used to import component-specific style sheets.
I wonder if we should use a different term here than _"component-specific style sheets"_? I'm worried this can be a bit ambiguous and not sufficiently distinct from e.g. using component-specific selectors in global stylesheets etc. Not sure what would be better, maybe _"component shadow dom style sheets"_ or _"styles injected into components"? Just throwing the thought out there.

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/importing-stylesheets.adoc
> +Use the `@CssImport` annotation to import style sheets which are in your application source folder.
```suggestion
Use the `@CssImport` annotation to import style sheets in the application's source code folder.

```

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/importing-stylesheets.adoc
> +External style sheets need to be accessible from a URL, and should be placed in the public resource folder in your web application.
maybe an example of where you'd typically find that folder?

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/importing-stylesheets.adoc
> +There is nothing to prevent the CSS rules in external style sheets from overriding component or view styles.
Is this really a concern worth pointing out?

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
I'd like to remove references to Material Design, since the theme has not been aligned with MD for years now. Maybe @jouni has an idea of how to describe it without referring to MD?

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/advanced/material-theme/index.adoc
> +Material is a theme inspired by the https://material.io[Material Design guidelines].
Same here

2022-08-19 13:37 UTC, rolfsmeds commented on articles/styling/custom-theme/custom-component-variants.adoc
> +Many Vaadin components have built-in <<{articles}/styling/lumo/variants/component-variants#, theme variants>> that provide different styles for the component.
```suggestion
Many Vaadin components have built-in <<{articles}/styling/lumo/variants/component-variants#, theme variants>> that provide different styles for the component.
Theme variants are similar to CSS class names, but are automatically inherited by sub-components within the component to which they're applied.

```

2022-08-20 07:52 UTC, tarekoraby commented on articles/styling/advanced/importing-stylesheets.adoc
> +The `@CssImport` annotation can also be used to import component-specific style sheets.
How about?
_The `@CssImport` annotation can also be used to import CSS style sheets that target the shadow DOM of the components._

2022-08-20 08:34 UTC, tarekoraby commented on articles/styling/advanced/importing-stylesheets.adoc
> +External style sheets need to be accessible from a URL, and should be placed in the public resource folder in your web application.
👍 added

2022-08-20 08:36 UTC, tarekoraby commented on articles/styling/advanced/importing-stylesheets.adoc
> +There is nothing to prevent the CSS rules in external style sheets from overriding component or view styles.
Maybe not. Removed.

2022-08-20 08:40 UTC, tarekoraby commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
Isn't it good enough that we are saying that it's "inspired"? To my mind, that doesn't imply that we are strictly adhering to the Material Design.

2022-08-22 06:28 UTC, rolfsmeds commented on articles/styling/advanced/importing-stylesheets.adoc
> +The `@CssImport` annotation can also be used to import component-specific style sheets.
that's good yeah!

2022-08-22 06:30 UTC, rolfsmeds commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
It probably is, I'd just like to entirely remove that association 😬

2022-08-22 06:31 UTC, rolfsmeds commented on articles/styling/advanced/material-theme/index.adoc
> +Material is a theme inspired by the https://material.io[Material Design guidelines].
Actually maybe let's just remove this link so remove any expectations that it has anything to do with the MD that now lives on that url.

2022-08-22 07:26 UTC, tarekoraby commented on articles/styling/advanced/material-theme/index.adoc
> +Material is a theme inspired by the https://material.io[Material Design guidelines].
I removed the link.

2022-08-22 07:36 UTC, tarekoraby commented on articles/styling/advanced/importing-stylesheets.adoc
> +The `@CssImport` annotation can also be used to import component-specific style sheets.
Fixed.

2022-08-22 10:55 UTC, jouni commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
Maybe just this minor addition is enough of a disclaimer?

```suggestion
description: A theme inspired by the original Material Design guidelines.

```

2022-08-22 11:19 UTC, tarekoraby commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
I'm not sure that adding "original" would make it obvious. How about: `A theme _loosely_ inspired by the Material Design guidelines.`?

2022-08-22 19:35 UTC, rolfsmeds commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
I prefer "original", or maybe "the first generation of Google's Material Design". "Guidelines" is kind of weird too since it's really more of a visual design than a guideline.

(Although frankly we're spending way too much time fine-tuning this 😁 )

2022-08-23 06:46 UTC, tarekoraby commented on articles/styling/advanced/material-theme/index.adoc
> +description: A theme inspired by the Material Design guidelines.
Ok, I added "original" before "Material Design guidelines".

2022-08-23 06:46 UTC, tarekoraby commented on articles/styling/advanced/material-theme/index.adoc
> +Material is a theme inspired by the https://material.io[Material Design guidelines].
Added "original" before "Material Design guidelines"

2022-08-24 12:38 UTC, tarekoraby commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
```suggestion
        Button toggleButton = new Button("Toggle dark theme", click -> {
            getElement().executeJs("return document.documentElement.getAttribute('theme')"). // <1>
                    then(String.class, result -> {
                        if (result == null || result.equals("light")) { // <2>
                            getElement().executeJs("document.documentElement.setAttribute('theme', 'dark')");
                        } else {
                            getElement().executeJs("document.documentElement.setAttribute('theme', 'light')");
                        }
                    });
        });
        
        add(toggleButton, h1);
    }
}
----
<1> Execute a JavaScript call to return the `theme` attribute value from the browser.
<2> Toggle between the light and dark themes depending on the returned `theme` attribute value.

```

@jouni like this?

2022-08-25 09:47 UTC, rolfsmeds approved these changes

2022-08-25 14:01 UTC, jouni commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
If it works, sure. I didn't consider reading the current value from the DOM, I might’ve just stored that as a variable in the Java class instead, and toggle based on that.

I think this solution results in two server round trips / HTTP request. First the button click, which goes to the server, which then sends back the JS execution snippet. That executeJs callback then results in another HTTP request with the results of the script, and then the server sends back another JS execution snippet.

If we store the value in the Java class, then it would just be one HTTP request to the server.

2022-08-25 14:21 UTC, jouni reviewed
Please check the Figma libraries images. They are not showing correctly in the preview:
![Screenshot 2022-08-25 at 17 20 14](https://user-images.githubusercontent.com/66382/186690358-3a2a0a90-6fc1-4548-b1eb-94eda12a6b98.png)
 

The Figma Libraries page could also have a description, that shows in section outlines.

2022-08-25 14:21 UTC, jouni commented on articles/styling/getting-started.adoc
> +. <<styling.get-started.sub-component-styling, Selectively styling sub-components of a Vaadin component>> (for example, the overlay of a DatePicker or a ComboBox).
I don't think list items should be terminated with a period in this case. Maybe it’s just a personal preference, not sure if there’s a rule/guideline in the English writing style that periods should be used.

```suggestion
. <<styling.get-started.lumo-theme, Lumo theme and its variants>>, including its dark-mode variant
. <<styling.get-started.declaring-custom-theme, Declaring a custom theme on top of the Lumo theme>>
. <<styling.get-started.location-to-add-css, Where to place the CSS files of a custom theme>>
. <<styling.get-started.overriding-lumo, Styling by overriding the default Lumo values>>
. <<styling.get-started.selective-styling-light-dom, Selectively styling views and components>>
. <<styling.get-started.shadow-dom-styling, Styling elements in the shadow DOM>>
. <<styling.get-started.shadow-dom-styling-selectively, Selectively styling elements in the shadow DOM>>
. <<styling.get-started.sub-component-styling, Selectively styling sub-components of a Vaadin component>> (for example, the overlay of a DatePicker or a ComboBox)

```

2022-08-25 14:57 UTC, dougjewsbury commented on articles/advanced/loading-resources.asciidoc
> +The [filename]#custom-css.js# uses the technique for wrapping CSS into JavaScript presented in <<{articles}/styling/advanced/importing-stylesheets#importing, Importing Style Sheets>>.
```suggestion
The [filename]#custom-css.js# code uses the technique for wrapping CSS into JavaScript presented in <<{articles}/styling/advanced/importing-stylesheets#importing, Importing Style Sheets>>.
```

2022-08-25 15:00 UTC, dougjewsbury commented on articles/styling/_shared.adoc
> +Specifically, we can add the following inside the `styles.css` file in order to increase the default roundedness value:
```suggestion
Specifically, we can add the following inside the [filename]#styles.css# file in order to increase the default roundedness value:

```

2022-08-25 15:01 UTC, dougjewsbury commented on articles/styling/_shared.adoc
> +For example, if one wants to override the rounded corner defaults for only the TextField and ComboBox components, then the following should be added inside the `styles.css` file:
```suggestion
For example, if one wants to override the rounded corner defaults for only the TextField and ComboBox components, then the following should be added inside the [filename]#styles.css# file:

```

2022-08-25 15:03 UTC, dougjewsbury commented on articles/styling/advanced/importing-stylesheets.adoc
> +For example, in a Spring Boot application, if the style sheet file is called `shared-styles.css`, then it should be placed in the `src/main/resources/META-INF/resources` folder, and it can be importe
```suggestion
For example, in a Spring Boot application, if the style sheet file is called [filename]#shared-styles.css#, then it should be placed in the `src/main/resources/META-INF/resources` folder, and it can be imported using the `@StyleSheet` annotation as follows:

```

2022-08-25 15:05 UTC, dougjewsbury commented on articles/styling/advanced/notheme-annotation.adoc
> +If needed, you can disable Lumo theme for your application using the `@NoTheme` annotation.
```suggestion
If needed, you can disable the Lumo theme for your application using the `@NoTheme` annotation.

```

2022-08-25 15:06 UTC, dougjewsbury commented on articles/styling/advanced/notheme-annotation.adoc
> +The `@NoTheme` annotation must be added on a class that implements the `AppShellConfigurator` interface.
```suggestion
The `@NoTheme` annotation must be added on a class that implements the [interfacename]`AppShellConfigurator` interface.

```

2022-08-25 15:07 UTC, dougjewsbury commented on articles/styling/custom-theme/creating-custom-theme.adoc
> +. If the `com.vaadin.flow.theme.lumo.Lumo` class is available in the classpath, the Lumo theme is used
```suggestion
. If the [classname]`com.vaadin.flow.theme.lumo.Lumo` class is available in the classpath, the Lumo theme is used
```

2022-08-25 15:08 UTC, dougjewsbury commented on articles/styling/custom-theme/custom-component-variants.adoc
> +Theme variants are similar to CSS class names, but are automatically inherited by sub-components within the component to which they're applied.
```suggestion
Theme variants are similar to CSS class names, but are automatically inherited by sub-components within the component to which they are applied.

```

2022-08-25 15:09 UTC, dougjewsbury commented on articles/styling/custom-theme/custom-component-variants.adoc
> +These are inherited to sub-components similarly to the built-in variants.
```suggestion
These are inherited to sub-components in a similar way to the built-in variants.

```

2022-08-25 15:10 UTC, dougjewsbury commented on articles/styling/custom-theme/styling-components.adoc
> +See <<{articles}/styling/custom-theme/creating-custom-theme#, Creating a Custom Theme>> for instructions how to import the above styles into the local style scope of the Text Field component.
```suggestion
See <<{articles}/styling/custom-theme/creating-custom-theme#, Creating a Custom Theme>> for instructions on how to import the above styles into the local style scope of the Text Field component.
```

2022-08-25 15:11 UTC, dougjewsbury commented on articles/styling/custom-theme/styling-components.adoc
> +The `:host` selector also accepts a simple selector as an argument for it, scoping the selector to match the host only if the added selector matches it as well. It is useful, for example, for matchin
```suggestion
The `:host` selector also accepts a simple selector as an argument, scoping the selector to match the host only if the added selector matches it as well. It is useful, for example, for matching specific <<states>> and <<{articles}/styling/lumo/variants/component-variants#,Theme Variants>> of a component (using an attribute selector).
```

2022-08-25 15:11 UTC, dougjewsbury commented on articles/styling/custom-theme/styling-components.adoc
> +As an overlay is considered as a sub-component of the main component, <<{articles}/styling/lumo/variants/component-variants#, sub-component variants>> apply to them as well.
```suggestion
As an overlay is considered to be a sub-component of the main component, <<{articles}/styling/lumo/variants/component-variants#, sub-component variants>> apply to them as well.
```

2022-08-25 15:13 UTC, dougjewsbury commented on articles/styling/custom-theme/styling-components.adoc
> +Same as <<overlays>>, an Input Container is considered as a sub-component of the main component, <<{articles}/styling/lumo/variants/component-variants#, sub-component variants>> apply to them as well
```suggestion
In the same way as <<overlays>>, an Input Container is considered to be a sub-component of the main component.
<<{articles}/styling/lumo/variants/component-variants#, Sub-component variants>> apply to them as well.
```

2022-08-25 15:14 UTC, dougjewsbury commented on articles/styling/custom-theme/styling-components.adoc
> +You can also use the `theme` attribute (see <<{articles}/styling/custom-theme/custom-component-variants#,custom component variants>>) as a scoping selector for your style overrides, as shown in the e
```suggestion
You can also use the `theme` attribute (see <<{articles}/styling/custom-theme/custom-component-variants#,custom component variants>>) as a scoping selector for your style overrides, as shown in the example that follows.
```

2022-08-25 15:16 UTC, dougjewsbury commented on articles/styling/lumo/design-tokens/index.adoc
> +description: The design tokens, such as colors, typography and other visual styles that defines the Lumo theme.
```suggestion
description: The design tokens, such as colors, typography and other visual styles that define the Lumo theme.

```

2022-08-25 15:18 UTC, dougjewsbury commented on articles/styling/lumo/design-tokens/styling-using-design-tokens.adoc
> +The basic building blocks of the Lumo theme is a set of _design tokens_, which are essentially a set of CSS custom properties for things like colors, font sizes, and other typographic and layout sett
```suggestion
The basic building blocks of the Lumo theme are a set of _design tokens_, which are essentially a set of CSS custom properties for things like colors, font sizes, and other typographic and layout settings.

```

2022-08-25 15:18 UTC, dougjewsbury commented on articles/styling/lumo/design-tokens/styling-using-design-tokens.adoc
> +Lumo theme combines these design tokens to provide Vaadin applications and components with their default look and feel.
```suggestion
The Lumo theme combines these design tokens to provide Vaadin applications and components with their default look and feel.

```

2022-08-25 15:19 UTC, dougjewsbury commented on articles/styling/lumo/design-tokens/styling-using-design-tokens.adoc
> +For example, you can use Lumo dark mode variant to create a dark theme for your application.
```suggestion
For example, you can use the Lumo dark mode variant to create a dark theme for your application.

```

2022-08-25 15:20 UTC, dougjewsbury commented on articles/styling/lumo/design-tokens/styling-using-design-tokens.adoc
> +For instance, you can add a small margin around all views and components in your application by adding the following to a CSS stylesheet:
```suggestion
You can, for instance, add a small margin around all views and components in your application by adding the following to a CSS stylesheet:

```

2022-08-25 15:22 UTC, dougjewsbury commented on articles/styling/lumo/index.adoc
> +Lumo is the default theme for all Vaadin applications and components, which can be customized to fit your visual style requirements.
```suggestion
Lumo is the default theme for all Vaadin applications and components, and can be customized to fit your visual style requirements.
```

2022-08-25 15:23 UTC, dougjewsbury commented on articles/styling/lumo/index.adoc
> +In addition to the custom properties, Lumo includes a light and dark mode variants, as well as a compact mode variant.
```suggestion
In addition to the custom properties, Lumo includes light and dark mode variants, as well as a compact mode variant.
```

2022-08-25 15:23 UTC, dougjewsbury commented on articles/styling/lumo/index.adoc
> +However, this is not recommended for most applications as it is easier to extend Lumo theme than to start from scratch.
```suggestion
However, this is not recommended for most applications as it is easier to extend the Lumo theme than to start from scratch.
```

2022-08-25 15:24 UTC, dougjewsbury commented on articles/styling/lumo/utility-classes.adoc
> +description: Describes the the set of CSS utility classes included in that enable building any UI without custom CSS.
```suggestion
description: Describes the the set of CSS utility classes included in Lumo that enable building any UI without custom CSS.
```

2022-08-25 15:25 UTC, dougjewsbury commented on articles/styling/lumo/utility-classes.adoc
> +To use the classes, make sure that `"utility"` is added to the `"lumoImports"` entry in your application theme's <<{articles}/styling/custom-theme/custom-theme-configuration#,configuration>> [filenam
```suggestion
To use the classes, make sure that `"utility"` is added to the `"lumoImports"` entry in your application theme's <<{articles}/styling/custom-theme/custom-theme-configuration#,configuration>> [filename]#theme.json# file.
```

2022-08-25 15:25 UTC, dougjewsbury commented on articles/styling/lumo/variants/compact.adoc
> +The compact variant is applied by importing an additional style sheet, which sets new values for the Typography, Sizing and Spacing CSS properties.
```suggestion
The compact variant is applied by importing an additional style sheet, which sets new values for the typography, sizing and spacing CSS properties.

```

2022-08-25 15:26 UTC, dougjewsbury commented on articles/styling/lumo/variants/compact.adoc
> +<2> Unlike the `@Theme` annotation, the `@JsModule` annotation does not have to be added to a class that implements the `AppShellConfigurator` interface.
```suggestion
<2> Unlike the `@Theme` annotation, the `@JsModule` annotation does not have to be added to a class that implements the [interfacename]`AppShellConfigurator` interface.

```

2022-08-25 15:29 UTC, dougjewsbury commented on articles/styling/lumo/variants/light-dark.adoc
> +For this we cannot use the `@Theme` annotation as it sets the variant permanently for the whole application.
```suggestion
For this, we cannot use the `@Theme` annotation, as it sets the variant permanently for the whole application.

```

2022-08-25 15:30 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +* The annotation should be present only once for an app, in a class implementing the `AppShellConfiguration` interface.
```suggestion
* The annotation should be present only once for an app, in a class implementing the [interfacename]`AppShellConfiguration` interface.

```

2022-08-25 15:31 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +However, this is not recommended for most applications as it is easier to extend Lumo theme than to start from scratch.
```suggestion
However, this is not recommended for most applications, as it is easier to extend the Lumo theme than to start from scratch.

```

2022-08-25 15:31 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +The `@Theme` annotation must be added on a class that implements the `AppShellConfigurator` interface.
```suggestion
The `@Theme` annotation must be added on a class that implements the [interfacename]`AppShellConfigurator` interface.

```

2022-08-25 15:32 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +For example, in a Spring Boot application, you can explicitly enable Lumo's dark variant by implementing the `AppShellConfigurator` interface in the main `Application` class, and then adding the `@Th
```suggestion
For example, in a Spring Boot application, you can explicitly enable Lumo's dark variant by implementing the [interfacename]`AppShellConfigurator` interface in the main [classname]`Application` class, and then adding the `@Theme` annotation to it:

```

2022-08-25 15:32 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +<2> The `@Theme` annotation can only be added once in the application on top of a class that implements the `AppShellConfigurator` interface.
```suggestion
<2> The `@Theme` annotation can only be added once in the application on top of a class that implements the [interfacename]`AppShellConfigurator` interface.

```

2022-08-25 15:33 UTC, dougjewsbury commented on articles/styling/theme-annotation.adoc
> +<2> The `@Theme` annotation must always be used on a class implementing `AppShellConfigurator`.
```suggestion
<2> The `@Theme` annotation must always be used on a class implementing [interfacename]`AppShellConfigurator`.

```

2022-08-25 15:34 UTC, dougjewsbury commented on articles/tools/designer/using-designer/layout.asciidoc
> +NOTE: When Lumo theme is in use, the margin, padding and spacing properties accept t-shirt sizes which translate to the corresponding <<{articles}/styling/lumo/design-tokens/size-space#space, spacing
```suggestion
NOTE: When the Lumo theme is in use, the margin, padding and spacing properties accept t-shirt sizes which translate to the corresponding <<{articles}/styling/lumo/design-tokens/size-space#space, spacing properties>>.
Otherwise, the property values map directly to the corresponding CSS properties.
```

2022-08-25 15:35 UTC, dougjewsbury commented on articles/tools/designer/using-designer/theming.asciidoc
>  The default component theme is `Lumo`. `Material` component theme is also available.
```suggestion
The default component theme is `Lumo`. The `Material` component theme is also available.
```

2022-08-25 15:36 UTC, dougjewsbury commented on articles/tools/designer/using-designer/theming.asciidoc
>  User should provide all styling through the application theme, if `None` component theme was selected.
```suggestion
The user should provide all styling through the application theme, if the component theme `None` was selected.
```

2022-08-25 15:37 UTC, dougjewsbury commented on articles/tools/designer/using-designer/theming.asciidoc
> +Vaadin Designer supports theming the same way as Flow (see <<{articles}/styling/custom-theme/creating-custom-theme#, Custom Theme>> for more information).
```suggestion
Vaadin Designer supports theming in the same way as Flow (see <<{articles}/styling/custom-theme/creating-custom-theme#, Custom Theme>> for more information).
```

2022-08-25 15:37 UTC, dougjewsbury commented on articles/tools/designer/using-designer/theming.asciidoc
>   * Modifies `package.json` file to add utility libraries. These changes should be committed to your version control system.
```suggestion
 * Modifies the [filename]#package.json# file to add utility libraries.
 These changes should be committed to your version control system.
```

2022-08-25 15:38 UTC, dougjewsbury commented on articles/tools/dspublisher/customization.asciidoc
> +See <<{articles}/styling/custom-theme/creating-custom-theme#,Applying a Custom Application Theme>> for instructions how to apply a theme which is used in <<ui-examples#,UI examples>>.
```suggestion
See <<{articles}/styling/custom-theme/creating-custom-theme#,Applying a Custom Application Theme>> for instructions on how to apply a theme which is used in <<ui-examples#,UI examples>>.
```

2022-08-25 15:39 UTC, dougjewsbury commented on articles/upgrading/recommended-changes/index.adoc
> +While importing styles using `@CssImport` still works, the recommended way to apply CSS to Vaadin applications is using <<{articles}/styling/custom-theme/creating-custom-theme#,the theme folder forma
```suggestion
Although importing styles using `@CssImport` still works, the recommended way to apply CSS to Vaadin applications is using <<{articles}/styling/custom-theme/creating-custom-theme#,the theme folder format>> introduced in Vaadin 19.

```

2022-08-25 16:01 UTC, dougjewsbury commented on articles/styling/getting-started.adoc
> +. <<styling.get-started.sub-component-styling, Selectively styling sub-components of a Vaadin component>> (for example, the overlay of a DatePicker or a ComboBox).
I think it's a question of judgement whether to terminate list items with a period or other punctuation. For me, it depends first on whether the list is grammatically a continuation of the preceding text, in which case I would punctuate the items by ending each one with a comma or a semi-colon. I would terminate the last item in the list with a period (assuming it's the end of the complete sentence - preceding text + list).
If the list isn't a grammatical continuation (as in this example), it depends on whether each item is a grammatically complete sentence, in which case I would punctuate the items by ending each one with a period.
If that's not the case (again, as in this example), I wouldn't put any terminating punctuation.
But, of course, there are often boundary cases, which is where the judgement comes in.

2022-08-26 03:58 UTC, tarekoraby commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
Yes, you are right about the number of client/server trips. But isn't it more robust to read the value from the DOM because the Java class might not be aware of what has been set in other places in the application?

2022-08-26 04:01 UTC, tarekoraby commented on articles/styling/lumo/index.adoc
> +description: Description of the built-in Lumo theme that is used by default in Vaadin apps and components.
🤔 what do you mean by that?

2022-08-26 06:46 UTC, tarekoraby commented
@jouni the Figma images are fixed, and a description is added. About the broken images, it's strange that it is not throwing an error during the build. In fact, the images are currently broken in production: https://vaadin.com/docs/latest/components/ds-resources/figma.

2022-08-26 06:48 UTC, jouni commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
Sure, that can happen, if client-side logic updates the value as well. I’ll let you decide. Maybe you can explain that tradeoff in the text?

2022-08-26 06:49 UTC, jouni commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
The client-side logic could of course call some server-side method to keep it in sync.

2022-08-26 06:49 UTC, jouni commented on articles/styling/lumo/index.adoc
> +description: Description of the built-in Lumo theme that is used by default in Vaadin apps and components.
The description sounds like a placeholder.

2022-08-26 07:31 UTC, tarekoraby commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
I feel that the overhead with two client-server roundtrips is so small that my current solution is ok. I mean, people don't constantly keep toggling dark and light themes.

2022-08-26 07:31 UTC, tarekoraby commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
So my vote goes to keeping the current solution as it is.

2022-08-26 07:32 UTC, tarekoraby commented on articles/styling/lumo/index.adoc
> +description: Description of the built-in Lumo theme that is used by default in Vaadin apps and components.
Ah, ok. No, I didn't intend it to be a placeholder. What could be a better description of the Lumo theme?

2022-08-26 08:56 UTC, jouni commented on articles/styling/lumo/variants/light-dark.adoc
> +<2> Toggle between the light and dark themes.
Alright then 👍

2022-08-26 08:56 UTC, jouni approved these changes

2022-08-26 10:14 UTC, merged