make vite as the default frontend build tool
vaadin/docs pull request #1635
Opened 2022-08-18 15:05 UTC by taefi

Fixes #1630

2022-08-19 06:39 UTC, tarekoraby commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
```suggestion
```

Do we want to continue to mention things that are using the deprecate V14 Bootstrapping and the possibly soon-to-be-deprecated webpack? Can we just remove all these lines altogether since people can just use the `IndexHtmlRequestListener`?

2022-08-19 06:45 UTC, tarekoraby commented on articles/components/ds-resources/customization/custom-theme.asciidoc
> -* The file being removed is a component style sheet in the [filename]#my-theme/components# folder, or the whole [filename]#my-theme/components# folder.
If this bullet point is removed, then we should remove the bullet point from the previous sentence and just merge it with the sentence before it. So that it becomes:

_Sometimes, compilation throws an error ("`no such file or directory`") when files or folders are removed from the theme folder while the application is running.
This might happen if the file being removed is a style sheet referenced from [filename]#my-theme/styles.css#, or from other style sheet in the theme folder.
In that case, to avoid re-compilation errors, remove the style sheet import first, and then remove the file._

2022-08-19 06:51 UTC, tarekoraby commented on articles/configuration/properties.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index#webpack-feature-flag, here>>.
I assume that "this" here is referring to `useDeprecatedV14Bootstrapping`. Right? If so, I suggest adding the note to the  `useDeprecatedV14Bootstrapping` description directly as follows:

_`useDeprecatedV14Bootstrapping`::
This flag can be used to enable the server-side bootstrapping mode which was used in Vaadin 14 and earlier versions. Note that this option is only supported if Webpack is used as the frontend build tool and not if the application uses Vite (which is the default).
Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index#webpack-feature-flag, here>>._

2022-08-19 07:10 UTC, taefi commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
Thanks for the review @tarekoraby, I believe as long as the `useDeprecatedV14Bootstrapping` is usable (while it is not removed), we need to prevent the confusion as much as possible since upgrading to 23.2 would change the default to Vite and if the users need to still use `useDeprecatedV14Bootstrapping` for some reason, it must be clear how to enable Webpack again. I guess the best time to remove these lines altogether is when we either remove `useDeprecatedV14Bootstrapping` or Webpack. Please let me know if I misunderstood something.

2022-08-19 07:17 UTC, mcollovati requested changes

2022-08-19 07:17 UTC, mcollovati commented on articles/configuration/source-control.adoc
> +vite.generated.js        <14>
```suggestion
vite.config.ts           <13>
vite.generated.ts        <14>
```

2022-08-19 07:17 UTC, mcollovati commented on articles/guide/start/gradle.asciidoc
> +  Checks that Node.js and `npm` are installed, copies front-end resources, and creates or updates the [filename]#package.json# and [filename]#vite.config.json# files.
It seems  `vite.config.json` is not something we create. Should it be `vite.config.ts` or simply `vite configuration files`, since prepare frontend also creates the `vite.generated.ts` file?

2022-08-19 07:17 UTC, mcollovati commented on articles/guide/start/gradle.asciidoc
> +  Cleans the project and removes [filename]#node_modules#, [filename]#package-lock.json#, [filename]#vite.generated.js#, [filename]#tsconfig.json#, [filename]#types.d.ts#, [filename]#pnpm-lock.yaml#
```suggestion
  Cleans the project and removes [filename]#node_modules#, [filename]#package-lock.json#, [filename]#vite.generated.ts#, [filename]#tsconfig.json#, [filename]#types.d.ts#, [filename]#pnpm-lock.yaml# and [filename]#pnpmfile.js#.
```

2022-08-19 07:17 UTC, mcollovati commented on articles/integrations/portlet/creating-vaadin-portlets.asciidoc
> +. Add a `build-frontend` goal to `vaadin-maven-plugin`, as Vaadin Portlet does not work in development mode running `vite-dev-server`.
Artifact in flow repo is `vaadin-dev-server`. Should it use that name here?

```suggestion
. Add a `build-frontend` goal to `vaadin-maven-plugin`, as Vaadin Portlet does not work in development mode running `vaadin-dev-server`.
```

2022-08-19 07:17 UTC, mcollovati commented on articles/integrations/spring/spring-boot.asciidoc
> +            vite.config.js if does not exist yet.
```suggestion
            vite.config.ts if does not exist yet.
```

2022-08-19 07:17 UTC, mcollovati commented on articles/production/production-build.adoc
> +It also creates or updates the [filename]#package.json#, [filename]#vite.config.json# and [filename]#vite.generated.json# files.
```suggestion
It also creates or updates the [filename]#package.json#, [filename]#vite.config.ts# and [filename]#vite.generated.ts# files.
```

2022-08-19 07:17 UTC, mcollovati commented on articles/production/production-build.adoc
> +- create [filename]#vite.config.js# if not found, or update it if some project parameters have changed.
```suggestion
- create [filename]#vite.config.ts# if not found, or update it if some project parameters have changed.
```

2022-08-19 07:17 UTC, mcollovati commented on articles/production/troubleshooting.asciidoc
> +The compatibility mode is explicitly set to 'false', but there are neither 'flow-build-info.json' nor 'vite.config.js' files
```suggestion
The compatibility mode is explicitly set to 'false', but there are neither 'flow-build-info.json' nor 'vite.config.ts' files
```

2022-08-19 07:29 UTC, taefi commented on articles/guide/start/gradle.asciidoc
> +  Checks that Node.js and `npm` are installed, copies front-end resources, and creates or updates the [filename]#package.json# and [filename]#vite.config.json# files.
Good catch! Probably it was supposed to be `webpack.config.js` before the change. Will change it to:

> vite configuration files (`vite.config.ts` and `vite.generated.ts`)

2022-08-19 07:41 UTC, taefi commented on articles/components/ds-resources/customization/custom-theme.asciidoc
> -* The file being removed is a component style sheet in the [filename]#my-theme/components# folder, or the whole [filename]#my-theme/components# folder.
Done.

2022-08-19 07:42 UTC, taefi commented on articles/configuration/properties.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index#webpack-feature-flag, here>>.
Done.

2022-08-19 07:58 UTC, mcollovati approved these changes

2022-08-19 08:07 UTC, tarekoraby commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
I'm fine with adding a note for people still using `useDeprecatedV14Bootstrapping` telling them to explicitly enable webpack. But the place for such warning IMO is in the [configuration properties](https://vaadin.com/docs/latest/configuration/properties) page, which is done in this PR.

This page is, however, about _Modifying the Bootstrap Page at Runtime_, and the section is talking about using `IndexHtmlRequestListener` to modify the body class dynamically. What I worry about is that it now seems that we are offering the `useDeprecatedV14Bootstrapping` as a valid alternative approach to modifying the body class dynamically, which is a bad idea given that `useDeprecatedV14Bootstrapping` and webapck will soon be removed.

2022-08-19 11:15 UTC, tarekoraby commented on articles/production/production-build.adoc
> +The vite server integration and live reload features, which are available only in development builds, are contained in the module `com.vaadin:vaadin-dev-server`.
```suggestion
The Vite server integration and live reload features, which are available only in development builds, are contained in the module `com.vaadin:vaadin-dev-server`.
```

2022-08-19 12:57 UTC, taefi commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
Ah OK, so the discussion is about whether the `useDeprecatedV14Bootstrapping` should be even mentioned in this specific documentation or not, the rest would be the side effect of keeping or removing this property from this documentation. It's kinda hard to tell since if we remove it here, we are un-documenting something we still support (although it is not recommended to use it anymore). I would postpone deleting it to some time in the future when the deprecated feature is deleted as well.

2022-08-19 15:12 UTC, tarekoraby commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
It's your call. But then I'd also suggest removing the separate admonition and just have the note inline with the previous sentence: 

```
This can also be achieved using a servlet container deployment property with the name `useDeprecatedV14Bootstrapping`.
Note, however, that this option is only supported if Webpack is used as the frontend build tool and not if the application uses Vite (which is the default).
Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
```

2022-08-19 15:15 UTC, tarekoraby requested changes

2022-08-19 15:15 UTC, tarekoraby commented on .github/styles/Vocab/Docs/accept.txt
> +[wW]ebpack
```suggestion
webpack
```

If I'm not mistaken, "webpack" is not in upper case: https://webpack.js.org/.

2022-08-19 15:15 UTC, tarekoraby commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Note that this option is only supported if Webpack is used as the frontend build tool and not if the application uses Vite (which is the default).
```suggestion
Note that this option is only supported if webpack is used as the frontend build tool and not if the application uses Vite (which is the default).
```

2022-08-19 15:15 UTC, tarekoraby commented on articles/configuration/live-reload/index.asciidoc
> +3. Enable the [guilabel]`Use Webpack for front-end builds (Deprecated)` feature
```suggestion
3. Enable the [guilabel]`Use webpack for front-end builds (Deprecated)` feature
```

2022-08-20 09:18 UTC, taefi commented on articles/advanced/modifying-the-bootstrap-page.asciidoc
> +Webpack can be enabled using its associated feature flag. Learn more about how to enable it <<{articles}/configuration/live-relaod/index/#webpack-feature-flag, here>>.
Done.

2022-08-20 09:20 UTC, taefi commented on .github/styles/Vocab/Docs/accept.txt
> +[wW]ebpack
Then I have no idea how to start an English sentence with "webpack" in lowercase, and if start it with uppercase, Vale will shout out.

2022-08-20 09:31 UTC, taefi commented on .github/styles/Vocab/Docs/accept.txt
> +[wW]ebpack
But, let's try it out again.

2022-08-20 12:16 UTC, tarekoraby commented
I'm not 100% sure, but after some googling, it seems to be acceptable _not_ to capitalize the start of a sentence if the first word is a brand that is not capitalized. (see, for example, this [thread](https://www.reddit.com/r/grammar/comments/339bvz/if_a_product_or_company_name_begins_with_a_lower/)). I thus suggest using the lower case "webpack" even in titles and the beginning of a sentence.

2022-08-20 12:17 UTC, tarekoraby commented on articles/configuration/live-reload/index.asciidoc
> +See the <<Webpack Feature Flag>> section to know how to do this.
```suggestion
See the <<webpack Feature Flag>> section to know how to do this.
```

2022-08-20 12:17 UTC, tarekoraby commented on articles/configuration/live-reload/index.asciidoc
> +== Webpack Feature Flag
```suggestion
== webpack Feature Flag
```

2022-08-20 12:17 UTC, tarekoraby commented on articles/configuration/properties.asciidoc
> +Webpack can be enabled using its associated feature flag.
```suggestion
You can enable webpack using its associated feature flag.
```

2022-08-20 15:24 UTC, dougjewsbury commented on articles/configuration/live-reload/index.asciidoc
> +See the <<webpack Feature Flag>> section to know how to do this.
```suggestion
See the <<webpack Feature Flag>> section for how to do this.
```

2022-08-20 15:25 UTC, dougjewsbury commented on articles/configuration/live-reload/index.asciidoc
> +Note that, the support for webpack will end when the next major release (Vaadin 24) is out.
```suggestion
Note that support for webpack will end with the next major release (Vaadin 24).
```

2022-08-20 15:40 UTC, dougjewsbury commented
With regard to whether or not to use a capital letter for a non-capitalised brand that occurs at the beginning of a sentence, I'd say that it's optional and depends on the preferences of the publisher - in this case, us. We just need to be consistent about it. I guess, if we opt to go for following the brand-owner's styling at all times, we create a little more work for ourselves in keeping Vale happy, but it's not a big deal. We haven't currently got anything in the style guide about this, but we could add it in.

2022-08-22 08:52 UTC, tarekoraby approved these changes

2022-08-22 08:54 UTC, tarekoraby commented
@taefi @mshabarov I should we wait with merging this until 23.2 is out?

2022-08-22 09:32 UTC, mshabarov commented
@tarekoraby Yes, that makes sense. We could highlight that it is since Vaadin 23.2, but there are so many places mentioning build tool in the articles, thus it would be messy to repeat it many times.

2022-08-22 11:22 UTC, tarekoraby requested changes
Merge closer to V23.2 release date.

2022-08-22 11:23 UTC, tarekoraby commented
I just added a request change so that no one would merge it accidentally.

2022-09-06 12:27 UTC, mshabarov commented
@taefi could you please resolve the conflicts. This is ready to merge since V23.2 is out.

2022-09-06 12:43 UTC, tarekoraby approved these changes

2022-09-06 13:20 UTC, taefi commented
The lint is failing with a weird error as follows and I have no idea how to resolve it:
```
panic: runtime error: index out of range [-1]
```

2022-09-06 13:30 UTC, jouni commented
We can ignore that error now. Some issue with the Vale action.

2022-09-06 13:31 UTC, merged