docs: ConfigurerAdapter to component-based security configuration
vaadin/docs pull request #1653
Opened 2022-08-25 06:27 UTC by MarcinVaadin

Information about new component-based security configuration instead of ConfigurerAdapter

Fixes: #1632

2022-08-26 08:41 UTC, mshabarov requested changes

2022-08-26 08:41 UTC, mshabarov commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
I propose to keep the `configure(WebSecurity web)` method in the code snippet to highlight the opportunity to override it and explain to devs for what it is. And you kept the point <3> below the code snippet.

2022-08-26 08:41 UTC, mshabarov commented on articles/security/enabling-security.adoc
> +`VaadinWebSecurityConfigurerAdapter` is still available for Vaadin 23.1 users but has been marked as deprecated and will be removed in the future.
```suggestion
`VaadinWebSecurityConfigurerAdapter` is still available for Vaadin 23.2 users but has been marked as deprecated and will be removed in the future.

```

2022-08-26 08:41 UTC, mshabarov commented on articles/security/enabling-security.adoc
> +Spring Security 5.7.0-M2 deprecates the `WebSecurityConfigurerAdapter` and encourages users to move towards a component-based security configuration.
```suggestion
Spring Security 5.7.0 deprecates the `WebSecurityConfigurerAdapter` and encourages users to move towards a component-based security configuration.

```

2022-08-26 08:46 UTC, mshabarov commented on articles/security/enabling-security.adoc
> +.Component-based security configuration
I would also suggest to not use a note for this paragraph. Just place it before `This is how the view-based access control mechanism ...`.
Probably start the paragraph with ``VaadinWebSecurityConfigurerAdapter` is still available ...` is better, to make readers relax that they can still use the old class.

2022-08-26 08:53 UTC, mshabarov commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
For example, this user mentions migration guide for custom security implementation https://github.com/vaadin/flow/issues/14427#issue-1350521477 even.

2022-08-29 06:02 UTC, MarcinVaadin commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
TBH we don't use that method anymore as marking static resources using `ignoring()` is not proper way. Static resources have been moved to default `HttpSecurity` filter. I can leave that method empty:
```
/**
     * Allows customization of WebSecurity configuration.
     */
    @Override
    public void configure(WebSecurity web) throws Exception {
        // Vaadin by default does not customize WebSecurity.
        super.configure(web);
    }
```
But for me it pointless...

I don't fully understand your remark about point <3> - it is next to calling super.configure(HttpSecurity) as it was previously and there is matching explanation below.

2022-08-29 06:16 UTC, MarcinVaadin commented on articles/security/enabling-security.adoc
> +.Component-based security configuration
I would reorganize those paragraphs like:
![image](https://user-images.githubusercontent.com/106965834/187134978-77e0f0cb-1d33-422e-9b54-b3d92d3df655.png)

2022-08-30 07:28 UTC, mshabarov commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
Vaadin abstract class doesn't use it, indeed. But it doesn't mean that the extension classes wouldn't use `WebSecurity` API for their purposes. I would add this method as you showed in your comment above.

About <3> - my only concern was that you deleted the <3> next to the code line, but kept it in the description block.

2022-08-30 08:42 UTC, MarcinVaadin commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
There are 2 occurrences of <3>, there is one more in `configure(HttpSecurity)`

2022-08-30 08:43 UTC, mshabarov commented on articles/security/enabling-security.adoc
> -        super.configure(web); // <3>
Ah, okay, I didn't notice that.

2022-08-30 11:02 UTC, mshabarov requested changes
Looks good to me, but I set "request changes" to merge it after V23.2 GA is out.

2022-09-06 12:28 UTC, mshabarov approved these changes

2022-09-06 12:41 UTC, merged