Docs: Add Avatar doc and TS examples
vaadin/docs pull request #168
Opened 2021-02-05 12:31 UTC by DiegoCardoso

2021-02-06 07:12 UTC, jouni commented
Build error:

```
9:09:58 AM: ERROR in [at-loader] ./node_modules/@vaadin/vaadin-avatar/vaadin-avatar-group.d.ts:2:15
9:09:58 AM:     TS2307: Cannot find module './@types/interfaces' or its corresponding type declarations.
9:09:58 AM: ERROR in [at-loader] ./frontend/demo/component/avatar/avatar-menu-bar.ts:8:1
9:09:58 AM:     TS6133: 'Person' is declared but its value is never read.
9:09:58 AM: ERROR in [at-loader] ./frontend/demo/component/avatar/avatar-sizes.ts:18:11
9:09:58 AM:     TS6133: 'person' is declared but its value is never read.
```

2021-02-08 08:38 UTC, DiegoCardoso commented
> 9:09:58 AM: ERROR in [at-loader] ./node_modules/@vaadin/vaadin-avatar/vaadin-avatar-group.d.ts:2:15
9:09:58 AM:     TS2307: Cannot find module './@types/interfaces' or its corresponding type declarations.

This needs to wait until [this fix](https://github.com/vaadin/vaadin-avatar/pull/102), which is released at [vaadin-avatar@2.0.0](https://github.com/vaadin/vaadin-avatar/releases/tag/v2.0.0), gets on the platform.

> 9:09:58 AM: ERROR in [at-loader] ./frontend/demo/component/avatar/avatar-menu-bar.ts:8:1
9:09:58 AM:     TS6133: 'Person' is declared but its value is never read.
9:09:58 AM: ERROR in [at-loader] ./frontend/demo/component/avatar/avatar-sizes.ts:18:11
9:09:58 AM:     TS6133: 'person' is declared but its value is never read.

Fixed.

2021-02-17 09:18 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-basic.ts
> +  private person!: Person;
There's some misalignment in using the non-null assertion operator (!) here and optional chaining (?) in the template. The non-null operator should only be used if you're sure, the value exists. In this case, the `person` is initially `undefined`, so it doesn't apply (that's why you needed to use optional chaining in the template to mitigate the runtime error).

Since you don't really need the full `person` object in the view, but only the URL for the user image, you could change this to `private userPictureUrl = '';` or such, set it as `people[0].pictureUrl` in `firstUpdated ` and then use the property in the template directly.

2021-02-17 09:22 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-basic.ts
> +  private person!: Person;
Ok looks like another example needs the full person object. In that case, it's probably better to have the examples aligned and use:
1. `private person?: Person`
2. `.img=${this.person?.pictureUrl}`

2021-02-17 09:29 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-group-bg-color.ts
> +      <!-- end::snippet[] -->
The snippet should show the "beef" of the example, in this case, the code with `colorIndex`

2021-02-17 09:30 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-group-internationalisation.ts
> +      <!-- end::snippet[] -->
The snippet should show the "beef" of the example, in this case, also the code with AvatarGroupI18n

2021-02-17 09:48 UTC, tomivirkki requested changes

2021-02-17 09:48 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-sizes.ts
> +@customElement('avatar-basic')
Conflicting custom element name
```suggestion
@customElement('avatar-sizes')
```

2021-02-17 09:48 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +@customElement('avatar-basic')
Conflicting custom element name
```suggestion
@customElement('avatar-menu-bar')
```

2021-02-17 09:48 UTC, tomivirkki commented on frontend/demo/component/avatar/avatar-group-max-items.ts
> +@customElement('avatar-group-basic')
Conflicting custom element name
```suggestion
@customElement('avatar-group-max-items')
```

2021-02-17 12:47 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-basic.ts
> +  private person!: Person;
Done.

2021-02-17 12:47 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-group-bg-color.ts
> +      <!-- end::snippet[] -->
Changed.

2021-02-17 12:47 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-group-internationalisation.ts
> +      <!-- end::snippet[] -->
Changed.

2021-02-17 12:47 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-group-max-items.ts
> +@customElement('avatar-group-basic')
Done.

2021-02-17 12:47 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +@customElement('avatar-basic')
Done.

2021-02-17 12:59 UTC, tomivirkki approved these changes

2021-02-17 17:26 UTC, merged