Add an article about reactive endpoints
vaadin/docs pull request #1696
Opened 2022-09-08 10:23 UTC by cromoteca

Describes using [Reactor](https://projectreactor.io/) in Hilla endpoints. An example is provided. I haven't rendered the example as it generates a connection each second, so I wasn't sure it is agood idea.

Closes #1476

2022-09-09 14:40 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +While traditional server calls work fine in most cases, sometimes you need different tools for your job. https://projectreactor.io/[Reactor] is one of those. It can help you streaming data to clients
```suggestion
Although traditional server calls work fine in most cases, sometimes you need different tools for your job.
https://projectreactor.io/[Reactor] is one of these.
It can help you in streaming data to clients and fits well into a non-blocking application.
Whenever the simple request-response pattern does not suit your needs, you might want to consider Reactor. 
Multi-user applications, infinite data streaming, and retries, are all good examples of what you can do with it.
```

2022-09-09 14:41 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +While getting comfortable with creation of streaming, non-blocking applications requires some effort, Hilla allows you to take advantage of Reactor literally in minutes. We have an excellent https://
```suggestion
Although getting comfortable with creation of streaming, non-blocking applications requires some effort, Hilla allows you to take advantage of Reactor in literally minutes.
We have an excellent https://hilla.dev/blog/interactive-applications-with-server-push/[blog article on reactive endpoints] for you to get the basics.
```

2022-09-09 14:42 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +Before describing the API details, let's try to write a basic application that can stream server time to the client. The purpose of this simple example will be to send the server time to all subscrib
```suggestion
Before describing the API details, let us try to write a basic application that can stream server time to the client.
The purpose of this simple example will be to send the server time to all subscribed clients, with an interval of one second between each message.
```

2022-09-09 14:43 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +Please not the presence of the `--push` flag: this will enable Push support, which is currently an experimental feature in Hilla. You can also enable that later, for example if you want to add it to
```suggestion
Note the presence of the `--push` flag; this will enable push support, which is currently an experimental feature in Hilla.
You can also enable it later, for example if you want to add it to an existing application.
```

2022-09-09 14:45 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +Then click on the `Dev Tools` icon in the bottom right corner and then on `Experimental features`. Double-check that `Push support in Hilla` is enabled, or enable it if necessary.
```suggestion
Then click on the `Dev Tools` icon in the bottom-right corner and then on `Experimental features`.
Double-check that `Push support in Hilla` is enabled, or enable it if necessary.
```

2022-09-09 14:47 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +First of all, create a new endpoint and name it `ReactiveEndpoint`. You can put it just aside `HelloWorldEndpoint.java` or in a package of your choice. This new endpoint will contain these two method
```suggestion
First of all, create a new endpoint and name it `ReactiveEndpoint`.
You can just put it inside [filename]#HelloWorldEndpoint.java# or in a package of your choice.
This new endpoint will contain these two methods:
```

2022-09-09 14:48 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +The first method, `getClock`, creates a https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Flux] that streams the server time each second. It uses https://projectreactor
```suggestion
The first method, [methodname]`getClock()`, creates a https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html[Flux] that streams the server time each second.
It uses https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#onBackpressureDrop--[onBackpressureDrop()] to avoid saturation in case some messages cannot be sent to the client in real time.
In this use case, it is perfectly fine to lose some messages.
```

2022-09-09 14:50 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +The second method, `getClockCancellable`, will return the same `Flux`, but wrapped in an `EndpointSubscription`, a Hilla-specific `Flux` wrapper which allows to execute something on the server side i
```suggestion
The second method, [methodname]`getClockCancellable()`, will return the same [classname]`Flux`, but wrapped in an [classname]`EndpointSubscription`, a Hilla-specific [classname]`Flux` wrapper which allows you to execute something on the server side if the subscription is cancelled by the client.
In this example, a log message is produced.
```

2022-09-09 14:53 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +Let's use those methods in our client application: create the `frontend/views/reactive/reactive-view.ts` file to add a new view. That will look like the default hello world example, customized with t
```suggestion
Let us use these methods in our client application.
Create the [filename]#frontend/views/reactive/reactive-view.ts# file to add a new view.
This will look like the default "Hello world" example, customized with the code that follows.
Again, you can expand it if you prefer to get the whole file.
You might have to fix some imports.
```

2022-09-09 14:54 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +You new view should now be available in the application page. When clicking on the `Toggle server clock` button, time will appear in the text field and will update each second. You can stop it by cli
```suggestion
You new view should now be available in the application page.
When the `Toggle server clock` button is clicked, the time will appear in the text field and will update each second.
You can stop it by clicking again.
```

2022-09-09 14:54 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +The generated TypeScript endpoint methods return a `Subscription<T>` object, which offers these methods:
```suggestion
The generated TypeScript endpoint methods return a [classname]`Subscription<T>` object, which offers these methods:
```

2022-09-09 14:56 UTC, dougjewsbury commented on articles/advanced/reactive-endpoints.asciidoc
> +- `context` to bind to the context, which allows the application to automatically close it when the view is detached.
```suggestion
- [methodname]`cancel()` to cancel the subscription;
- [methodname]`onNext()` to get the next message in the Flux;
- [methodname]`onError()` to get errors that can happen in the Flux;
- [methodname]`onComplete()` to be informed when the Flux has no more messages to send;
- [methodname]`context()` to bind to the context, which allows the application to automatically close it when the view is detached.
```

2022-09-21 17:06 UTC, platosha requested changes
Should prominently mention that the feature is experimental and provide instructions on enabling the feature flag.

2022-09-21 17:06 UTC, platosha commented on articles/advanced/reactive-endpoints.asciidoc
> +- [methodname]`context()` to bind to the context, which allows the application to automatically close it when the view is detached.
```suggestion

== Feature Flag

In order to use Reactive Endpoints, they must be explicitly enabled with a feature flag.
There are two methods of doing this:

=== Using Vaadin Developer Tools

1. Click on the Vaadin Developer Tools icon button in your running application
2. Open the [guilabel]`Experimental Features` tab
3. Enable the [guilabel]`Push support in Hilla` feature
4. Restart the application.

=== Adding a Feature Flags Properties File

1. Create a [filename]#src/main/resources/vaadin-featureflags.properties# file in your application folder
2. Add the following content: `com.vaadin.experimental.hillaPush=true`
3. Restart the application.
```

2022-09-21 17:06 UTC, platosha commented on articles/advanced/reactive-endpoints.asciidoc
> +
```suggestion

.Experimental Feature
[IMPORTANT]
====
Reactive Endpoints are an experimental feature, which means that its behavior, API, and look and feel might still change.
In order to use Reactive Endpoints, they must be explicitly enabled with a feature flag.
See the <<Feature Flag>> section for how to do this.
====

```

2022-09-22 07:46 UTC, cromoteca commented on articles/advanced/reactive-endpoints.asciidoc
> +- [methodname]`context()` to bind to the context, which allows the application to automatically close it when the view is detached.
Is it OK to remove the `context()` description?

2022-09-22 09:59 UTC, platosha commented on articles/advanced/reactive-endpoints.asciidoc
> +- [methodname]`context()` to bind to the context, which allows the application to automatically close it when the view is detached.
oh no, we should not remove, of course. That was accidental from me, sorry, thanks for spotting.

2022-09-23 08:36 UTC, platosha approved these changes

2022-09-23 08:37 UTC, merged