Swing Kit Docs
vaadin/docs pull request #1730
Opened 2022-09-20 14:12 UTC by dpizzagalli

Basic initial overview of dependencies and usage of Swing-Kit APIs

2022-09-20 14:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=1730) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=1730) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=1730) it.</sub>

2022-09-21 12:56 UTC, jouni commented
I’ll do a small file structure update, then @russelljtdyer can do the language check.

2022-09-27 15:29 UTC, russelljtdyer approved these changes
I made several minor edits to the text -- not the examples -- and left some notes for future improvements.  But otherwise it all looks fine.

2022-09-28 09:37 UTC, jouni commented
@russelljtdyer, could you also sign the CLA:
<img width="554" alt="Screenshot 2022-09-28 at 12 37 01" src="https://user-images.githubusercontent.com/66382/192745333-f59b3053-619c-49ae-83af-99a25b1586d1.png">

2022-09-28 09:42 UTC, jouni commented on articles/tools/swingkit/setup/flow-configuration.asciidoc
> += Vaadin Flow Configuration
@russelljtdyer, I see this as potentially confusing. If viewed without proper context, it could mean configuring Vaadin Flow itself, for which we have a whole section in the docs: https://vaadin.com/docs/configuration

2022-09-28 10:47 UTC, jouni reviewed
Sorry for the amount of notes, but I wanted to make them easily visible for everyone (to learn from), instead of just committing them directly to the branch.

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/setup/swing-configuration.asciidoc
> +This file will be downloaded from the Internet, if not already present. This will likely happen silently the first time the Swing application is executed.
The second sentence mentions just one file, so I assume that’s more accurate. Also, I’m not sure what “native files” means, please correct me if that makes a difference to the reader.


```suggestion
The rendering process stores a file in the home folder of the system, which is downloaded from the internet, if not already present.
This will likely happen silently the first time the Swing application is executed.
```

Why “likely”? Don't we know for sure? I would rather avoid this “weasel word” here if possible.

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/callable.asciidoc
> +layout: page
```suggestion
description: The [interfacename]`SwingVaadinCallable` interface makes it possible to query a Vaadin Flow view directly from Swing using it's representation.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/callable.asciidoc
> +
A couple of typos in this sentence, fixed when moved to the page description.

```suggestion
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/callable.asciidoc
> +The methods to be published by your view must be exposed using an interface that extends `SwingVaadinCallable`.
```suggestion
The methods to be published by your view must be exposed using an interface that extends [interfacename]`SwingVaadinCallable`.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/index.asciidoc
> +Swing Kit to integrate Vaadin views in deskop application
Keep these descriptions in sync with the actual page description.

```suggestion
Swing Kit is a tool designed to render Vaadin applications inside Swing clients, instead of stand-alone browsers.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/callable.asciidoc
> +The best way to achive this is to have the interface built in an artifact, which is then added as a dependency of both.
```suggestion
The best way to achieve this is to have the interface built in an artifact, which is then added as a dependency of both.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/callable.asciidoc
> +While rendering a view as a `JVaadinPanel`, it is possibile to use the interface using the `as` method, as you can see here:
```suggestion
While rendering a view as a `JVaadinPanel`, it is possibile to use the interface using the [methodname]`as()` method, as you can see here:
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/exception.asciidoc
> +layout: page
```suggestion
description: How exceptions are handled when using Swing Kit, and how to configure it.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/exception.asciidoc
> +As a default behaviour, Swing will show the exception in a JOptionPane`.
```suggestion
By default, any exception not handled by the remote View, is handled by Swing.
As a default behaviour, Swing shows the exception in a [classname]`JOptionPane`.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/exception.asciidoc
> +The behaviour can be changed to catch any Vaadin exceptions from Swing, directly.
```suggestion
This behaviour can be configured to catch any Vaadin exceptions from Swing, directly.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/exception.asciidoc
> +You would add a custom handler for the exception by added this:
```suggestion
Add a custom exception handler by adding the following:
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/exception.asciidoc
> +This is to avoid serialization errors due to different classpaths from the Vaadin server and the Swing application.
```suggestion
Notice, that the event contains only [classname]`String` values instead of the original [classname]`Exception`.
This is to avoid serialization errors due to different classpaths from the Vaadin server and the Swing application.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/flowapis.asciidoc
> +layout: page
```suggestion
description: How to make Vaadin Flow views usable together with Swing Kit.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/flowapis.asciidoc
> +To enable your views to be used from Swing, you will need to add the annotation `@Bridge`. You can see an example of this here:
```suggestion
To enable your views to be used from Swing, you need to add the [annotationname]`@Bridge` annotation to them.
For example:
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/flowapis.asciidoc
> +It is possible to check if the UI is currently rendered in a normal browser or from a swing application by using the following:
```suggestion
It is possible to check if the view is rendered in a normal browser or inside a Swing application using the [methodname]`isSwingRendered()` method:
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/flowapis.asciidoc
> +You may send events to be handled from swing. This is done creating a new `VaadinSwingEvent`.
```suggestion
You can send events from your Vaadin application to the Swing application.
This is done by creating a new [classname]`VaadinSwingEvent` instance.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/flowapis.asciidoc
> +Note that the instances contained inside `VaadinSwingEvent` must always be `Serializable` to allow the Swing part to parse the data.
```suggestion

Note that the instances contained inside [classname]`VaadinSwingEvent` must always be [interfacename]`Serializable` to allow the Swing application to parse the data.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/index.asciidoc
> +title: Usage Guide
```suggestion
title: Usage Guide
description: Learn how to use all the capabilities of Swing Kit.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/index.asciidoc
> +section_outline::[]
```suggestion
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/swingbase.asciidoc
> +layout: page
```suggestion
description: How to add Vaadin views to your Swing applications and how to communicate between them.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/swingbase.asciidoc
> +A Vaadin view can be rendered as a Swing Component like so:
```suggestion
A Vaadin view can be rendered as a Swing component like so:
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/swingbase.asciidoc
> +This `JVaadinPanel` extends the `Panel`. It can be added using standard swing layouts.
```suggestion
The [classname]`JVaadinPanel` class extends the [classname]`Panel` component, and can be added to standard Swing layouts.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/swingbase.asciidoc
> +You can check when the page has been fully loaded by using the `isReady()` method.
```suggestion
You can check when the page has been fully loaded by using the [methodname]`isReady()` method.
```

2022-09-28 10:47 UTC, jouni commented on articles/tools/swingkit/usage/swingbase.asciidoc
> +Events emitted from the server can be handled with `addEventListener`, as you see here:
```suggestion
Events emitted from the Flow application can be handled with [methodname]`addEventListener()`.
For example:
```

2022-09-28 11:21 UTC, jouni commented
As a more general observation, the structure of these docs seems a bit less than ideal. 

The appropriate content is there, but for example, how to send and listen to events across the Flow–Swing bridge is split in two pages. The first one shows how events are send, and the other how they are listened to. I think that should be a single use case which is documented in one place.

A similar note could be made about the Setup Guide, which would probably make more sense as a single page rather than two.

Once the previous notes are handled, we could rework the structure.

2022-09-28 11:25 UTC, jouni requested changes
Explicitly blocking this PR until the structure is redone, to avoid adding any redirects if we’d first merge this and then do the restructure.

2022-09-29 08:49 UTC, dpizzagalli commented on articles/tools/swingkit/setup/flow-configuration.asciidoc
> +title: Vaadin Flow Server Configuration
Just a note / question here. This guide is supposed to instruct swing users about starting vaadin adoption. It is important that they keep in mind that Vaadin acts as a server in this achitecture, and that their application is splitted in 2 parts.
What do you think if we remove "Vaadin" but keep "Flow Server Configuration"?

2022-09-29 11:16 UTC, jouni commented on articles/tools/swingkit/setup/flow-configuration.asciidoc
> +title: Vaadin Flow Server Configuration
Thanks. I’m not sure I understand the difference. The page content goes on to say the following (emphasis mine): 

> In preparation for Maven, your **Vaadin application** will need to include the following dependency:

I assume, that if a developer has chosen our Swing Kit, they have at least baseline understanding of Vaadin/Flow, so I don't think we need to stress the part that Vaadin/Flow is a server-side framework.

2022-09-29 11:16 UTC, jouni commented on articles/tools/swingkit/setup/flow-configuration.asciidoc
> +title: Vaadin Flow Server Configuration
That said, I’ll try to keep this in mind when I restructure the content a bit.

2022-09-29 11:21 UTC, jouni commented on articles/tools/swingkit/setup/flow-configuration.asciidoc
> += Vaadin Flow Configuration
This is probably a non-issue, as I’m planning on combining both of these “configuration” pages into a single “setup” page.

2022-09-29 19:28 UTC, jouni approved these changes
Unblocking, now that I did the restructure/rewrite.

@dpizzagalli, please check the updated content and let me know if I misunderstood something in the content.

2022-09-30 04:31 UTC, jouni commented on articles/tools/swing/getting-started.adoc
> +:swing-kit-version: 1.0.0
@dpizzagalli, do we already have a version we can define?

2022-10-03 05:54 UTC, jouni commented on articles/tools/swing/getting-started.adoc
> +:swing-kit-version: 1.0.0
How about @bennewi or @heruan, do you know the version number?

2022-10-05 08:47 UTC, jouni commented on articles/tools/swing/getting-started.adoc
> +:swing-kit-version: 1.0.0
1.0.0 is now in Maven Central

2022-10-05 08:48 UTC, merged