[WIP] docs(fusion): add page State Management With MobX
vaadin/docs pull request #176
Opened 2021-02-11 07:30 UTC by Haprog

WIP. Example to be added.

2021-02-26 16:36 UTC, platosha approved these changes
LGTM overall

2021-02-26 16:36 UTC, platosha commented on articles/fusion/application/state-management.asciidoc
> +To be able to effectively use MobX and understand how it works, you should take a look at the official link:https://mobx.js.org/[MobX documentation] which is a great resource for learning the basic c
Feels like a comma before which is necessary here:

```suggestion
To be able to effectively use MobX and understand how it works, you should take a look at the official link:https://mobx.js.org/[MobX documentation], which is a great resource for learning the basic concepts as well as advanced usage.
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +Here we concentrate on an approach to store all shared front-end state in a central MobX state store
```suggestion
Here we concentrate on an approach to store all shared frontend state in a central MobX state store
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +Vaadin recommends to use the link:https://mobx.js.org/[MobX] library to manage front-end state in your apps.
```suggestion
Vaadin recommends to use the link:https://mobx.js.org/[MobX] library to manage frontend state in your apps.
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +link:https://start.vaadin.com/[start.vaadin.com] (or link:https://vaadin.com/labs/cli[Vaadin CLI])
```suggestion
link:https://start.vaadin.com/[Start Vaadin] (or link:https://vaadin.com/labs/cli[Vaadin CLI])
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +by providing a MobX store (named `AppState`) in addition to `View` and `Layout` helper base classes for your application views and layouts.
```suggestion
by providing a MobX store (named `AppState`) and `View` and `Layout` helper base classes for your application views and layouts.
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +MobX has experimental support for decorators (`@observable`, `@action`) but using them requires a special setting `"useDefineForClassFields": true` in `tsconfig.json`. Unfortunately having that setti
```suggestion
MobX has experimental support for decorators (`@observable`, `@action`) but using them requires a special setting `"useDefineForClassFields": true` in `tsconfig.json`. Using that setting link:https://github.com/Polymer/lit-element/issues/855[breaks LitElement decorators] (`@property`, `@query`) so you can't use both LitElement decorators and MobX decorators in the same app. We recommend not to use MobX decorators for now in projects that use LitElement.
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +.my-state.ts
```suggestion
.`my-state.ts`
```

2021-02-26 19:00 UTC, jouni commented on articles/fusion/application/state-management.asciidoc
> +.my-view.ts
```suggestion
.`my-view.ts`
```

2021-03-01 10:19 UTC, haijian-vaadin requested changes

2021-03-01 10:19 UTC, haijian-vaadin commented on articles/fusion/application/state-management.asciidoc
> +export class MyView extends View {
I think the `View` is from the starter wizard, not provided by Vaadin out-of-the-box. Maybe better to use `MobxLitElement` instead of `View`?

2021-03-02 09:25 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +To be able to effectively use MobX and understand how it works, you should take a look at the official link:https://mobx.js.org/[MobX documentation] which is a great resource for learning the basic c
Done. Thanks!

2021-03-02 09:25 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +Here we concentrate on an approach to store all shared front-end state in a central MobX state store
Done.

2021-03-02 09:25 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +Vaadin recommends to use the link:https://mobx.js.org/[MobX] library to manage front-end state in your apps.
Done.

2021-03-02 09:25 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +link:https://start.vaadin.com/[start.vaadin.com] (or link:https://vaadin.com/labs/cli[Vaadin CLI])
Done.

2021-03-02 09:26 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +by providing a MobX store (named `AppState`) in addition to `View` and `Layout` helper base classes for your application views and layouts.
Done.

2021-03-02 09:26 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +MobX has experimental support for decorators (`@observable`, `@action`) but using them requires a special setting `"useDefineForClassFields": true` in `tsconfig.json`. Unfortunately having that setti
Done.

2021-03-02 09:26 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +.my-state.ts
Done.

2021-03-02 09:26 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +.my-view.ts
Done.

2021-03-02 09:27 UTC, Haprog commented on articles/fusion/application/state-management.asciidoc
> +export class MyView extends View {
Good point. I updated this to use `MobxLitElement` but mention in the callout text that you may instead use `View` if the project is generated from Start Vaadin.

2021-03-02 10:22 UTC, Haprog commented
Rebased onto latest and force-pushed to see if it gets rid of the Vale issues for files that aren't changed in this PR.

2021-03-02 10:37 UTC, Haprog commented
Vale is happy/green now (except for some warnings that I think are probably ok). Needs a new approval for merging. The review suggestions were applied, PR was rebased and few other minor improvements were done (update to how `vaadin-text-field` is imported in the example).

2021-03-02 10:39 UTC, jouni approved these changes

2021-03-02 10:40 UTC, haijian-vaadin approved these changes

2021-03-02 11:12 UTC, merged