[WIP] Add documentation for the Azure Kit
vaadin/docs pull request #1819
Opened 2022-10-12 09:20 UTC by MatthewVaadin

Add documentation for the Azure Kit.

2022-10-12 10:21 UTC, jouni commented
Drop the `-kit` suffix from the folder name, to align with other kits.

2022-11-08 15:50 UTC, heruan requested changes

2022-11-08 15:50 UTC, heruan commented on articles/tools/azure/configuration.asciidoc
> +If you try to increment the counter again, your request is redirected to another pod but the session should be restored and the counter keeps incrementing.
This should be removed as it is already covered by the new `getting-started.asciidoc`.

2022-11-08 15:50 UTC, heruan commented on articles/tools/azure/update-version.asciidoc
> +----
This should be removed as it is already covered by the new `getting-started.asciidoc`.

2022-11-08 15:50 UTC, heruan commented on articles/tools/azure/index.asciidoc
> +
I don't think we need a download button for the Kit, since it can be added as a dependency as documented in `getting-started.asciidoc`.

2022-11-08 16:09 UTC, mcollovati commented on articles/tools/azure/getting-started.asciidoc
> +vaadin.serialization.include-packages=com.example.application
Should we mention to also set the `vaadin.devmode.sessionSerialization.enabled=true` property, to have session serialization debug tool active in development mode?

2022-11-09 09:48 UTC, gtzluis reviewed
Some grammar suggestions

2022-11-09 09:48 UTC, gtzluis commented on articles/tools/azure/index.asciidoc
> +Microsoft Azure is a cloud service provided by Microsoft for application management and related services: software as a service (SaaS); platform as a service (PaaS); and infrastructure as a service (
This looks a bit weird to me, should it instead be:
Microsoft Azure is a cloud service provided by Microsoft for application management and related services: software as a service (SaaS), platform as a service (PaaS), and infrastructure as a service (IaaS).

2022-11-09 09:48 UTC, gtzluis commented on articles/tools/azure/index.asciidoc
> +The Azure Kit enables teams to deploy seamlessly and operate Vaadin Java-based applications built using Flow on Azure Cloud. The Kit helps teams quickly to create Vaadin applications that are scalabl
it should probably be:
The Kit helps teams to quickly create Vaadin applications that are scalable
and:
cloud-provider -> cloud provider

2022-11-10 14:26 UTC, heruan requested changes

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/index.asciidoc
> +The Vaadin Azure Kit is used to integrate your applications with Azure, to be able to deploy your Vaadin Flow applications to the cloud.
Let's just use "Azure Kit" without "Vaadin", as we refer also to other kits in the docs and website.
```suggestion
Azure Kit is used to integrate your applications with Azure, to be able to deploy your Vaadin Flow applications to the cloud.
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +== Vaadin Session Replication Tips
Let's ditch "Vaadin" also from here, as it is implicit we're in Vaadin context.
```suggestion
== Session Replication Tips
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +For this reason, application code should be carefully written to be serializable for Vaadin session replication to succeed.
We replicate the whole session, not just Vaadin's.
```suggestion
For this reason, application code should be carefully written to be serializable for session replication to succeed.
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +In Spring projects, Vaadin Kubernetes Kit is able to detect this fields and re-inject them after deserialization.
Remove "Vaadin" also here.
```suggestion
In Spring projects, Kubernetes Kit is able to detect this fields and re-inject them after deserialization.
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +In non Spring project, transient fields should be handled manually either by implementing Java serialization hooks (https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/output.html#the-
And here.
```suggestion
In non Spring project, transient fields should be handled manually either by implementing Java serialization hooks (https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/output.html#the-writeobject-method[`writeObject`], https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/output.html#the-writereplace-method[`writeReplace`], https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/input.html#the-readobject-method[`readObject`], https://docs.oracle.com/en/java/javase/17/docs/specs/serialization/input.html#the-readresolve-method[`readResolve`], etc.) or the Kubernetes Kit [interfacename]`TransientHandler` interface.
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +In Spring projects using Vaadin Kubernetes Kit, you can rely on transient field handling, and simply add the field for the service instance.
And also here.
```suggestion
In Spring projects using Kubernetes Kit, you can rely on transient field handling, and simply add the field for the service instance.
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> + 		return item -> convertIfNotNull(item, /* (3) */ converter, () -> "");
Move `(3)` at the end of the line.
```suggestion
 		return item -> convertIfNotNull(item, converter, () -> ""); // (3)
```

2022-11-10 14:26 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +The user may notice a temporarily offline notification or the loading indicator spawn, but the browser page is not reloaded and work can continue without losing any data.
Rephrase this as discussed in the DX Test.

2022-11-10 15:04 UTC, mcollovati commented on articles/tools/azure/session-replication.adoc
> +The user may notice a temporarily offline notification or the loading indicator spawn, but the browser page is not reloaded and work can continue without losing any data.
Proposed a change as review comment

2022-11-11 08:10 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +Restrictions can be imposed by configuring `vaadin.serialization.include-packages` and `vaadin.serialization.exclude-packages` properties, to limit the inspection to classes whose packages matches th
Add a note explaining why `exclude-packages` would be used, maybe with an example.

2022-11-11 08:10 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +However, it is mandatory to do that on non UI components that may be referenced in the UI graph.
```suggestion
However, it is mandatory to do so on non UI components that may be referenced in the UI graph.
```

2022-11-11 08:10 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +It works only on `development mode` and only if session serialization is enabled setting the configuration property `vaadin.devmode.sessionSerialization.enabled` to `true`.
Add a code block for the properties file.

2022-11-22 09:43 UTC, tarekoraby requested changes

2022-11-22 09:43 UTC, tarekoraby commented on articles/index.asciidoc
> +Deploy your Vaadin applications to the cloud.
```suggestion
Deploy your Vaadin application to Kubernetes, enabling scalability, high availability, and rolling updates.
```

2022-11-22 09:43 UTC, tarekoraby commented on articles/tools/index.asciidoc
> +Deploy your Vaadin applications to the cloud.
```suggestion
Deploy your Vaadin application to Kubernetes, enabling scalability, high availability, and rolling updates.
```

2022-11-22 09:43 UTC, tarekoraby commented on articles/tools/kubernetes/index.asciidoc
> +The Kubernetes Kit is used to integrate your applications with Kubernetes, to be able to deploy your Vaadin Flow applications to the cloud.
```suggestion
The Kubernetes Kit is used to integrate your applications with Kubernetes to be able to deploy your Vaadin Flow applications on-premises or to the cloud.
```

2022-11-22 09:43 UTC, tarekoraby commented on articles/tools/kubernetes/index.asciidoc
> +The Kubernetes Kit enables teams to deploy seamlessly and operate Vaadin Java-based applications built using Flow. The Kit helps teams to quickly create Vaadin applications that are scalable, highly
```suggestion
The Kubernetes Kit enables teams to deploy seamlessly and operate Vaadin Java-based applications built using Flow.
The Kit helps teams to quickly create Vaadin applications that are scalable, highly available, and user-friendly.
Specifically, the enables the following:
- Non-disruptive rolling updates that don't interrupt user sessions, reducing the cost and inconvenience of after-hours deployments. 
- Horizontal scalability, saving on cloud costs by allowing your application to scale down without impacting active users' sessions, and scale up when needed.
- High availability, enabling users to keep their active sessions and continue using your application even if a server fails.
- “serialization helpers” that make it faster and easier to fully leverage horizontal scaling and fail-over.
```

2022-11-22 09:43 UTC, tarekoraby commented on articles/tools/kubernetes/getting-started.asciidoc
> + running in a Kubernetes cluster (including Azure).
```suggestion
Kubernetes Kit enables scalability, high availability, and non-disruptive rolling updates for Vaadin applications running in a Kubernetes cluster.
```

2022-11-23 13:32 UTC, tarekoraby approved these changes

2022-11-23 13:54 UTC, heruan approved these changes

2022-11-24 08:16 UTC, merged