feat: add docs on getting the browser url to Java
vaadin/docs pull request #182
Opened 2021-02-12 13:39 UTC by pleku

Part of vaadin/flow#1897

2021-02-12 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=182) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=182) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=182) it.</sub>

2021-02-12 14:44 UTC, jouni requested changes

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/accessing-data-from-the-browser.asciidoc
> +# Accessing Browser Details
```suggestion
= Accessing Browser Details
```

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/accessing-data-from-the-browser.asciidoc
> +## Getting the Window Location URL
```suggestion
== Getting the Window Location URL
```

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/accessing-data-from-the-browser.asciidoc
> +The `Page` object provides API to interact with the browser and retrieve data to the server side.
```suggestion
The `Page` object provides API to interact with the browser and retrieve data, for example, screen dimensions or device pixel ratio, to the server side. 
```

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/accessing-data-from-the-browser.asciidoc
> +To fetch the user browser current URL, you can use the method `Page.fetchCurrentURL`.
```suggestion
Use the [methodname]`Page.fetchCurrentURL` method to fetch the current URL from the browser.
```

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/accessing-data-from-the-browser.asciidoc
> +include::src/main/java/com/vaadin/flow/browser/BrowserDetail.java[tags=get-current-url, indent=0, group=Java]
```suggestion
include::src/main/java/com/vaadin/flow/browser/BrowserDetail.java[tags=get-current-url, indent=0]
```
Only use `group` if you have the same example implemented for both Flow and Fusion.

2021-02-12 14:44 UTC, jouni commented on articles/flow/browser/src/main/java/com/vaadin/flow/browser/BrowserDetail.java
> +/*
This is a source file from Flow, right (judging from the package name)? If so, then it should not be added to the docs project. Write the source code inline inside Asciidoc, as this is an exceptional case.

If this is a class that could be in a user project, then put it under `src` where you’d put it in a real project. All source files should always go either under `frontend` or `source`, never under `articles`.

2021-02-15 11:49 UTC, caalador commented on articles/flow/browser/src/main/java/com/vaadin/flow/browser/BrowserDetail.java
> +/*
This is just for the document. It's the same as was set into the theming tutorial which we based the file position and style on.

2021-02-15 13:38 UTC, jouni commented on articles/flow/browser/src/main/java/com/vaadin/flow/browser/BrowserDetail.java
> +/*
The “Theming” section contains “legacy” structure, with a nested `src` folder it it. I’m currently working on restructuring the whole section, and removing the source files under it.

2021-02-15 13:41 UTC, jouni commented on articles/flow/browser/src/main/java/com/vaadin/flow/browser/BrowserDetail.java
> +/*
The same should be done for `/articles/flow/src´ (delete it completely). I haven’t yet removed it because I haven’t checked if some of those files are used in `include::[]` directives somewhere in the Flow docs. If they aren’t, we could remove the `src` folder immediately.

So, I suggest we remove this file, and either create an example under `/src` (in the project root), or copy the snippet inside Asciidoc. The latter will add some amount of debt, which should be addressed later, so the former approach is recommended.

2021-03-17 13:31 UTC, pleku commented on articles/flow/browser/src/main/java/com/vaadin/flow/browser/BrowserDetail.java
> +/*
Done

2021-03-17 17:05 UTC, jouni approved these changes

2021-03-17 17:06 UTC, merged