docs: Add JUnit5 examples for TestBench9
vaadin/docs pull request #1865
Opened 2022-11-04 08:35 UTC by MarcinVaadin

Added JUnit5 examples to present new features of Testbench 9 that will be available with Vaadin 24.

2022-11-04 09:30 UTC, tomivirkki commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
Where possible, prefer writing code in a Java/ts/js file and then including it in the asciidoc file

2022-11-04 09:39 UTC, MarcinVaadin commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
All examples in Testing/* were just inline code snippets, should I refactor everything or is it just a notice for future changes?

2022-11-04 09:47 UTC, tomivirkki commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
No need to refactor now IMO, but just a general recommendation. Inline code snippets tend to age easily since they never break when the project is compiled.

2022-11-04 13:05 UTC, jouni commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
Yes, it would be preferable to keep code under the `src` and `frontend` folders when possible. Sometimes it isn't. I assume we could include test classes in the project as well without issues.

All the existing TestBench examples are obviously not extracted like that, so it’s convenient to continue the same approach. But perhaps we should start at some point to move to the better approach, so that as much of the example code as possible is compiled.

2022-11-04 13:08 UTC, jouni commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
An example where it's not possible to avoid writing examples inside the asciidoc content:

<img width="406" alt="Screenshot 2022-11-04 at 15 07 33" src="https://user-images.githubusercontent.com/66382/199979699-5432923f-e8b4-485e-a084-1ac20fff3d3b.png">

I assume it’s not possible to have both dependencies at once.

2022-11-04 14:05 UTC, mshabarov requested changes
We also need to put a general note in the first chapter of end-to-end part that since Vaadin 24 both JUnit 4 and JUnit 5 test framework versions are supported. Here maybe https://vaadin.com/docs/latest/testing/end-to-end/#features

2022-11-04 14:05 UTC, mshabarov commented on articles/testing/selenium.adoc
> +Combining TestBench with Selenium-Jupiter is straightforward, like in example:
```suggestion
Combining TestBench with Selenium-Jupiter is shown in the following example:
```

2022-11-07 06:36 UTC, MarcinVaadin commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
It is technically possible to use both in same time, but what do mean by "pulled from the pom.xml"?

2022-11-07 10:15 UTC, jouni commented on articles/testing/end-to-end/bdd.adoc
> +public class CalculatorSteps implements HasElementQuery {
> what do mean by "pulled from the pom.xml"?

Tag the region in the pom.xml file like this:

```xml
<!-- tag::junit5-dependency[] -→
<dependency>
  ...
</dependency>
<!-- end::junit5-dependency[] -->
```

The include that in the docs page like this:

```asciidoc
[source,xml]
----
include::{root}/pom.xml[tag=junit5-dependency,indent=0,group="JUnit 5"]
----
```

2022-11-07 14:03 UTC, mshabarov approved these changes

2022-11-08 06:42 UTC, MarcinVaadin commented on articles/testing/index.adoc
> +Since Vaadin 24 both JUnit 4 and JUnit5 test frameworks are supported on end-to-end tests.
I've unified naming everywhere to "JUnit 4" and "JUnit 5".

2022-11-08 11:08 UTC, MarcinVaadin commented
There will be updates related to testbench update.

2022-11-14 14:13 UTC, jouni commented on articles/testing/index.adoc
> +Since Vaadin 24 both JUnit 4 and JUnit 5 test frameworks are supported on end-to-end tests.
```suggestion
[since:com.vaadin:vaadin@V24]#Both JUnit 4 and JUnit 5 test frameworks are supported on end-to-end tests#.
```

2022-11-14 14:13 UTC, jouni commented on articles/testing/selenium.adoc
> +== Selenium-Jupiter extension
```suggestion
== Selenium-Jupiter Extension
```

2022-11-15 15:11 UTC, mshabarov approved these changes

2022-11-17 07:53 UTC, vursen reviewed
A few minor suggestions.

2022-11-17 08:19 UTC, MarcinVaadin commented on articles/testing/end-to-end/multiple-browsers.adoc
> +If your test class already creates `WebDriver` implementing `DriverSupplier` you can remove it in favor of automatic driver initialization by TestBench.
I've omitted that one and cannot apply it now :-/

2022-11-29 19:10 UTC, jouni commented
Actually, I’ll move Russell’s edits to another branch, so this PR stays focused on the original scope.

2022-11-29 19:10 UTC, merged