docs: Kubernetes Kit session replication
vaadin/docs pull request #1867
Opened 2022-11-04 12:15 UTC by mcollovati

2022-11-04 13:00 UTC, MatthewVaadin requested changes

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +The user may notice a temporarily offline notification or the loading indicator spawn, but browser page is not reload and his work can continue without losing any data.
```suggestion
The user may notice a temporarily offline notification or the loading indicator spawn, but the browser page is not reloaded and work can continue without losing any data.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +Speaking about HTTP session, this means that attributes must be constantly stored in a shared/distributed storage, so that newly created HTTP sessions may filled with the most recent user data.
```suggestion
This means that attributes must be constantly stored in a shared/distributed storage, so that newly created HTTP sessions may filled with the most recent user data.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +== Vaadin Kubernetes Kit Session Replication
```suggestion
== Kubernetes Kit Session Replication
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +Vaadin Kubernetes Kit helps with session replication, by transfer HTTP session data on a backed session storage (Hazelcast or Redis) at every request.
```suggestion
Kubernetes Kit helps with session replication, by transferring HTTP session data via a backend session storage (Hazelcast or Redis) at every request.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +When a server becomes unavailable, the one taking its place loads user data from the session storage and fills the new server side HTTP session object.
```suggestion
When a server becomes unavailable, the one taking its place loads user data from the session storage and fills the new server-side HTTP session object.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +This means that to have session replication working, the application code should be written in way that all object stored into HTTP session are eligible for Java serialization, meaning they must impl
```suggestion
This means that to have session replication working, the application code should be written in way that all objects stored in the HTTP session are eligible for Java serialization, meaning they must implement a special marker interface, [classname]`java.io.Serializable`.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +Objects that for any reasons cannot be serializable (e.g. third party classes) must be defined `transient`, so they are skipped by the serialization process.
```suggestion
Objects that for any reason cannot be serializable (e.g. third party classes) must be defined `transient`, so they are skipped by the serialization process.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +For Spring application, Vaadin Kubernetes Kit is also capable to overcome this limitation.
```suggestion
For Spring applications, Kubernetes Kit is also able to overcome this limitation.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +Transient fields referencing Spring beans are detected during serialization and metadata is stored along the session attributes.
```suggestion
Transient fields referencing Spring beans are detected during serialization and metadata is stored along with the session attributes.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +A Vaadin application is composed by UI objects that acts as root nodes of graphs of components composition that represents the web page the user interact with in through the browser.
```suggestion
A Vaadin application is comprised of UI objects that act as root nodes of graphs of components that represent the web page the user interacts with in through the browser.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +UIs are collected into [classname]`VaadinSession` that is stored in the HTTP session, to preserve the server side state across request.
```suggestion
UIs are collected into a [classname]`VaadinSession` that is stored in the HTTP session, to preserve the server-side state across requests.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +This means that to have session replication working, the application code should be written in way that all object stored into HTTP session are eligible for Java serialization, meaning they must impl
Repeated segment from line 25.

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +When writing a component make sure that all its non transient members implements [classname]`Serializable`.
```suggestion
When writing a component make sure that all its non-transient members implement [classname]`Serializable`.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +All Vaadin UI components and listeners are already marked as serializable, so if extending or implementing them it is not necessary to explicitly add the `Serializable` implementation statement.
```suggestion
All Vaadin UI components and listeners are already marked as serializable, so if a class extends or implements one of them, it is not necessary to explicitly add the `Serializable` implementation statement.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +For example, if a view is holding a reference to a DTO or a configuration object, it must be marked as serializable, and all its member must be serializable.
```suggestion
For example, if a view is holding a reference to a data transfer object or a configuration object, it must be marked as serializable, and all its members must be serializable.
```

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +    private Product product; // (2)
I don't think the label is meant to be here.

2022-11-04 13:00 UTC, MatthewVaadin commented on articles/tools/azure/session-replication.adoc
> +    private Category category; // (3)
I don't think the label is meant to be here.

2022-11-04 13:29 UTC, tarekoraby commented on articles/tools/azure/session-replication.adoc
> +=== Transient Fields for Not Serializable Objects
```suggestion
=== Transient Fields for Non-Serializable Objects
```

2022-11-04 14:02 UTC, mcollovati commented on articles/tools/azure/session-replication.adoc
> +    private Category category; // (3)
I put the label in two places because the related description covers both the lines of code
- Category is referenced by Product
- it also must be Serializable

Can this be expressed better using different labels?

2022-11-04 14:03 UTC, mcollovati commented on articles/tools/azure/session-replication.adoc
> +    private Product product; // (2)
I put the label in two places because the related description covers both the lines of code
- Product instance is referenced by ContactForm
- it must be Serializable

Can this be expressed better using different labels?

2022-11-04 14:40 UTC, tarekoraby commented on articles/tools/azure/session-replication.adoc
> +1. [classname]`Category` is referenced by [classname]`Product`, so it also must be [classname]`Serializable`.
```suggestion
class ContactForm extends VerticalLayout { // (1)

    private Product product; // (2)

}

class Product implements Serializable { // (3)

    private Category category; // (4)
}

class Category implements Serializable { // (5)

}
----

1. The [classname]`ContactForm` class extends a Vaadin component that is already serializable.
2. The [classname]`ContactForm` class has a field of type [classname]`Product`.
Therefore, the [classname]`Product` class must also be made serializable.
3. The [classname]`Product` class is made serializable by extending [interfacename]`Serializable`.
4. The [classname]`Product` class has a field of type [classname]`Category`.
Therefore, the [classname]`Category` class must also be made serializable.
5. The [classname]`Category` class is made serializable by extending [interfacename]`Serializable`.
```

2022-11-04 14:40 UTC, tarekoraby commented on articles/tools/azure/session-replication.adoc
> +    private Category category; // (3)
I made a suggestion to reorganize the callouts.

2022-11-04 14:40 UTC, tarekoraby commented on articles/tools/azure/session-replication.adoc
> +    private Product product; // (2)
I made a suggestion to reorganize the callouts.

2022-11-04 17:26 UTC, mcollovati commented on articles/tools/azure/session-replication.adoc
> +This means that to have session replication working, the application code should be written in way that all object stored into HTTP session are eligible for Java serialization, meaning they must impl
I tried to rephrase the sentence

2022-11-07 10:50 UTC, jouni commented on articles/tools/azure/session-replication.adoc
>  Usually the cause is a `self reference`, meaning that the lambda expression captures an object instance, but the expression is itself a member of the object graph of the captured object.
Would this be a better formatting? I wonder if monospace is the best one to use.
```suggestion
Usually the cause is a "self reference", meaning that the lambda expression captures an object instance, but the expression is itself a member of the object graph of the captured object.
```

2022-11-08 12:16 UTC, heruan commented on articles/tools/azure/session-replication.adoc
> +When facing exceptions on serialization phase, it may be useful set the `sun.io.serialization.extendedDebugInfo` system property to make Java serialization verbose.
Should we make this an AsciiDoc `TIP` to make it stand out?

2022-11-08 15:05 UTC, merged