chore: renamed transient field filter configuration properties
vaadin/docs pull request #1879
Opened 2022-11-09 07:50 UTC by mcollovati

Part of vaadin/azure-kit#38

2022-11-09 07:51 UTC, mcollovati commented
Draft until vaadin/azure-kit#42 is merged

2022-11-21 10:06 UTC, MatthewVaadin requested changes

2022-11-21 10:06 UTC, MatthewVaadin commented on articles/tools/kubernetes/session-replication.adoc
> +Restrictions can be imposed by configuring `vaadin.serialization.transients.include-packages` and `vaadin.serialization.exclude-packages` properties, to limit the inspection to classes whose packages
Missed rename.
```suggestion
Restrictions can be imposed by configuring `vaadin.serialization.transients.include-packages` and `vaadin.serialization.transients.exclude-packages` properties, to limit the inspection to classes whose packages matches the configured rules.
```

2022-11-21 10:19 UTC, mcollovati commented on articles/tools/kubernetes/session-replication.adoc
> +Restrictions can be imposed by configuring `vaadin.serialization.transients.include-packages` and `vaadin.serialization.exclude-packages` properties, to limit the inspection to classes whose packages
good catch! thanks

2022-11-21 10:20 UTC, MatthewVaadin approved these changes

2022-11-21 13:09 UTC, merged