Add crud TS examples (WIP)
vaadin/docs pull request #188
Opened 2021-02-16 17:30 UTC by yuriy-fix

2021-02-19 19:26 UTC, jouni commented
Something strange is happening when I browse the page on an iPhone. The editor dialog keeps opening automatically during scrolling. Probably related to the example being attached/detached when it enters/exits the viewport.

2021-02-19 19:28 UTC, jouni commented
Also, the grid columns are rendered somehow broken:

![image](https://user-images.githubusercontent.com/66382/108552035-71680e00-72f9-11eb-9971-7108ff8cd54a.png)

2021-02-19 19:40 UTC, jouni commented
Not seeing that kind of problems at https://cdn.vaadin.com/vaadin-crud/1.3.0/demo/#crud-basic-demos

2021-02-24 09:32 UTC, tomivirkki requested changes

2021-02-24 09:32 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +        edit-on-click
The example description says `you can have it open using double click:`, but this opens it with a single click

2021-02-24 09:34 UTC, tomivirkki commented
> The editor dialog keeps opening automatically during scrolling

This happens because at least one of the examples has the editor pre-opened. On mobile, the editor occupies the full screen.

2021-02-24 20:02 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-open-editor.ts
> +        edit-on-click
Have updated that one to use double click. Got confused as `edit-on-click` is also removing the edit column, but is opening on single click 😅

2021-02-24 20:06 UTC, yuriy-fix commented
![crud-example](https://user-images.githubusercontent.com/29372419/109058712-013bfc80-76ec-11eb-8dfc-7e7f0ae895c8.gif)
Have tried it out, it seems to be stuck in that position until scrolling is completed (not always). Probably something related to the scrolling in the docs app. Did it go to normal after some time for you, @jouni?

2021-02-26 07:39 UTC, jouni commented
Yeah, it's not persistent all the time.

2021-03-01 10:37 UTC, yuriy-fix commented
Editor is not visible by default anymore, it removes extra hacks to set edited items, combo-box values and trick with editor positioning.

2021-03-04 08:43 UTC, tomivirkki requested changes

2021-03-04 08:43 UTC, tomivirkki commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <div slot="toolbar" style="flex: 1;">Total: <b>${this.items.length}</b> employees</div>
I'd imagine the count here is expected to change if you delete / add items.

2021-03-04 08:43 UTC, tomivirkki commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <a slot="toolbar" new-button href="javascript:"
Why is an anchor used here (and not a tertiary button)?

2021-03-04 08:43 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
This is too hacky. Crud has `editedItem` property, that you should use instead
```suggestion
  onDblClick(e: MouseEvent) {
    this.editedItem = ((e.target as GridElement).getEventContext(e) as GridEventContext).item;
  }
```

2021-03-04 08:43 UTC, tomivirkki commented on frontend/demo/component/crud/crud-editor-actions.ts
> +    deleteBtn?.setAttribute('theme', 'primary error');
This can't be the way we want to promote styling the editor buttons. How would you do this in Java?

2021-03-04 12:29 UTC, jouni commented on frontend/demo/component/crud/crud-editor-actions.ts
> +    deleteBtn?.setAttribute('theme', 'primary error');
Oh, wow, yeah, this looks terrible 😆 Wasn’t there a way to slot in new buttons or something like that? Or maybe I remember that from Confirm Dialog. 

If there’s no nicer way of doing this, I think we should not customize the buttons then.

2021-03-04 12:42 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <div slot="toolbar" style="flex: 1;">Total: <b>${this.items.length}</b> employees</div>
Updated the logic to reflect the current number of items.
Using `size` property in order not to update the `innerHTML` as need to set **bold**, still not sure if it's the best way 🤔

2021-03-04 12:42 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <a slot="toolbar" new-button href="javascript:"
Was following existing example: https://vaadin.com/components/vaadin-crud/html-examples/crud-custom-demos#toolbar.
Have updated it, using `vaadin-button` now.

2021-03-04 12:42 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-editor-actions.ts
> +    deleteBtn?.setAttribute('theme', 'primary error');
Yeah, that's quite difficult to achieve. I have added `TODO commit` before: https://github.com/vaadin/docs/pull/188/commits/33afbfe6d54f33cc29b8a2e0eaaeb435a5660201.

There is [relevant issue](https://github.com/vaadin/vaadin-crud/issues/228) created some time ago, but I am not sure if we can implement that one or just skip this example. 

It looks like important stuff to show, probably can convert it to cookbook example instead.

2021-03-06 14:34 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
There is a problem with editing the same item. Unfortunately `editor-opened-changed` event cannot be used in this case either as it's fired before `editedItem` is changed on closing the editor.

Have created corresponding issue and attached a PR right away: https://github.com/vaadin/vaadin-crud/issues/241.
This is an enhancement, other option is to make sure `editedItem` is changed before emitting `editor-opened-changed`. Not sure which one is preferable.

2021-03-08 08:29 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
It's a shame that `editedItem` doesn't notify. Making it notify could almost be considered a bugfix as it's more like a missing event.

The following logic should work until we have the proper notify event available:
```js
@editor-opened-changed=${(e: CustomEvent) => {
  if (e.detail.value) {
    // The editor was opened
    this.editedItem = (e.currentTarget as CrudElement<Person>).editedItem;
  } else {
    this.editedItem = null;
  }
}}
```

or a shorter version:
```js
const editedItem = (e.currentTarget as CrudElement<Person>).editedItem;
this.editedItem = e.detail.value ? editedItem : null;
```

2021-03-08 10:14 UTC, tomivirkki commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <div slot="toolbar" style="flex: 1;">Total: <b>${this.items.length}</b> employees</div>
If you want to avoid adding another property to the class you could bind the length of the already existing `items` property instead:
`<b>${this.items.length}</b>`
and then request an update on size change:
`@size-changed=${() => this.requestUpdate()}`

2021-03-08 10:26 UTC, tomivirkki commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <a slot="toolbar" new-button href="javascript:"
👍  Why is the `style="margin: 0;"` override needed?

2021-04-12 12:26 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
The `editedItem` notifies now, example updated.

2021-04-12 12:26 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <a slot="toolbar" new-button href="javascript:"
It is getting default indent from button styles, it's not that big, so not overriding anymore.

2021-04-12 12:26 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-toolbar.ts
> +        <div slot="toolbar" style="flex: 1;">Total: <b>${this.items.length}</b> employees</div>
Good point! Updated.

2021-04-12 13:13 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
Seems to have an error

<img width="906" alt="Screenshot 2021-04-12 at 16 10 18" src="https://user-images.githubusercontent.com/1222264/114399794-fceb7600-9ba9-11eb-8c75-77d596593b5c.png">

2021-04-12 13:23 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +@customElement('crud-open-editor')
There's something odd about this example. Seems that you can only edit once. After that, none of the items can be edited:

![Kapture 2021-04-12 at 16 20 26](https://user-images.githubusercontent.com/1222264/114401093-425c7300-9bab-11eb-96aa-1d60395c0475.gif)

2021-04-13 12:59 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-open-editor.ts
> +  }
Fixed the error.

2021-04-13 12:59 UTC, yuriy-fix commented on frontend/demo/component/crud/crud-open-editor.ts
> +@customElement('crud-open-editor')
Good catch! The issue is created. Can we consider it as a non-blocker?
Will be fixed automatically be fixed in the example with bumping the version after the issue is fixed in the component.

2021-04-13 13:08 UTC, tomivirkki commented on frontend/demo/component/crud/crud-open-editor.ts
> +@customElement('crud-open-editor')
Yup, if it's a component bug and can't be worked around in this example then it's not a blocker

2021-04-13 14:24 UTC, vursen commented on frontend/demo/component/crud/crud-open-editor.ts
> +        <vaadin-grid slot="grid" @dblclick="${this.onDblClick}">
Is it possible to configure `eslint` or `prettier` so that it will format quotes around an expression in some consistent way?

Seems that it could look a bit better in terms of documentation.

2021-04-14 07:27 UTC, tomivirkki approved these changes

2021-04-14 08:04 UTC, merged

2021-04-14 09:13 UTC, jouni commented on frontend/demo/component/crud/crud-open-editor.ts
> +        <vaadin-grid slot="grid" @dblclick="${this.onDblClick}">
Yeah, would be great to have a lint rule for this. This was recently discussed in Slack: https://vaadin.slack.com/archives/C0168FAKA8H/p1617025824119800