Update going-to-production.asciidoc
vaadin/docs pull request #189
Opened 2021-02-16 20:10 UTC by kaviwe

@Peppe

2021-02-16 20:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=189) it.</sub>

2021-02-17 06:23 UTC, Peppe requested changes

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +Enabling production mode for a Vaadin app is described in <<{articles}/guide/production/production-overview#, Deploying to Production>>.
```suggestion
Enabling production mode for a Vaadin application is described in <<{articles}/guide/production/production-overview#, Deploying to Production>>.
```

Not better, but consistent with Vaadin's documentation in general

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +Enabling production mode for a Vaadin app is described in <<../flow/production/tutorial-production-mode-basic#, Deploying to Production>>.
```suggestion
Enabling production mode for a Vaadin application is described in <<../flow/production/tutorial-production-mode-basic#, Deploying to Production>>.
```

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +If your app uses Collaboration Engine, it requires some extra steps when you take your application to production. These steps are described here.
```suggestion
If your application uses Collaboration Engine, it requires some extra steps when you take your application to production.
These steps are described here.
```
Prefer application over app.
One sentence per line.

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +Prior to configuring your Vaadin app for production mode, you need to:
```suggestion
Before configuring your Vaadin application for production mode, you need to:
```

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +If you don't have a commercial Vaadin subscription (Pro, Prime or Enterprise), https://website.vaadin.com/hubfs/collaboration-engine/ce-license.json[click here] to download the universal license file
```suggestion
If you don't have a commercial Vaadin subscription (Pro, Prime, or Enterprise), https://website.vaadin.com/hubfs/collaboration-engine/ce-license.json[click here] to download the universal license file.
```

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +The universal license file cannot be upgraded to increase the quota of monthly end users.
```suggestion
You can upgrade to a commercial license to increase your monthly end user quota.
```

I think you do upgrade the license file, when you purchase a bigger one. It is the same process as going from a small commercial quota to a bigger commercial quota.

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +== Obtaining a commercial license file
```suggestion
== Obtaining a Commercial License File
```
All titles in Docs should be title case.

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +First, you need to have a commercial Vaadin subscription (Pro, Prime or Enterprise) in order to request this license. Each Vaadin subscription offers a bundled quota of end users per month, based on
```suggestion
First, you need to have a commercial Vaadin subscription (Pro, Prime, or Enterprise) to request this license.
Each Vaadin subscription offers a bundled quota of end users per month, based on the number of development seats.
Visit, https://vaadin.com/collaboration#pricing[the official feature page] to learn more about the bundled quotas. 
```

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +To obtain your license, https://vaadin.com/collaboration/#contact-us[click here to contact our team]. You can also request and purchase a larger quota of end users than provided by your commercial Va
```suggestion
To obtain your license, https://vaadin.com/collaboration/#contact-us[click here to contact our team]. 
You can also request and purchase a larger quota of end users than provided by your commercial Vaadin subscription. 
Additional end users above your bundled quota are billed at 1 USD (or 1 EUR) per month.
```

2021-02-17 06:23 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +The name of the license file will be `ce-license.json`.
```suggestion
The name of the license file is `ce-license.json`.
```

2021-02-17 06:45 UTC, kaviwe commented on articles/ce/going-to-production.asciidoc
> +The universal license file cannot be upgraded to increase the quota of monthly end users.
Ah, I see your point. That's not what I meant to say actually; maybe this is more reflective of my intent:

"You can upgrade to a commercial license to increase your monthly end user quota. However, a commercial license also requires an active Vaadin commercial subscription (Pro, Prime, or Enterprise)."

Not sure how to add a suggestion to your suggestion @Peppe

2021-02-17 07:13 UTC, Peppe commented on articles/ce/going-to-production.asciidoc
> +The universal license file cannot be upgraded to increase the quota of monthly end users.
Sounds good I changed the suggestion to match your text.

2021-02-17 10:07 UTC, Peppe approved these changes

2021-02-17 10:08 UTC, Peppe commented
This patch should be gotten into V14 and latest. Do I make a copy of the PR into latest, or can it be somehow cherry-picked?

2021-02-17 11:16 UTC, jouni requested changes

2021-02-17 11:16 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +All Vaadin apps receive a free 10 end-user per month quota with a universal license file.
```suggestion
All Vaadin applications receive a free 10 end user per month quota with a universal license file. 
```
“end user” was used in other parts of the article. Please double check that you use it consistently.

2021-02-17 11:16 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +If you don't have a commercial Vaadin subscription (Pro, Prime, or Enterprise), https://website.vaadin.com/hubfs/collaboration-engine/ce-license.json[click here] to download the universal license fil
```suggestion
If you don't have a commercial Vaadin subscription (Pro, Prime, or Enterprise), you can https://website.vaadin.com/hubfs/collaboration-engine/ce-license.json[download the universal license file].
```
Avoid “click here” links, those are bad for accessibility.

2021-02-17 11:16 UTC, jouni commented on articles/ce/going-to-production.asciidoc
>  . Get a license file with an end-user quota.
```suggestion
. Get a license file with an end user quota.
```

2021-02-17 11:16 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +To obtain your license, https://vaadin.com/collaboration/#contact-us[click here to contact our team].
```suggestion
To obtain your license, https://vaadin.com/collaboration/#contact-us[contact our team]. 
```

2021-02-17 11:16 UTC, jouni commented on articles/ce/going-to-production.asciidoc
> +Additional end users above your bundled quota are billed at 1 USD (or 1 EUR) per month.
```suggestion
End users above your bundled quota are billed at 1 USD (or 1 EUR) per month.
```

2021-02-17 13:24 UTC, jouni approved these changes

2021-02-17 13:25 UTC, merged