Update overview.asciidoc
vaadin/docs pull request #190
Opened 2021-02-16 20:11 UTC by kaviwe

@Peppe

2021-02-16 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=190) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=190) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=190) it.</sub>

2021-02-17 07:24 UTC, Peppe requested changes

2021-02-17 16:33 UTC, jouni commented
The preview build failed during Maven dependency download. We can ignore that, these changes only affect the text, so the build should be unaffected.

2021-02-18 06:28 UTC, Peppe approved these changes

2021-02-18 08:21 UTC, merged