Add Azure Kit Chapter
vaadin/docs pull request #1908
Opened 2022-11-22 11:41 UTC by tarekoraby

2022-11-29 14:52 UTC, heruan submitted a review, later dismissed

2022-11-29 14:52 UTC, heruan commented on articles/tools/azure/getting-started.adoc
> +Download the Azure Kit from https://github.com/vaadin/kubernetes-kit[github.com/vaadin/kubernetes-kit]. When you've done this, unzip it to a local directory.
This might be confusing, since Azure Kit and Kubernetes Kit are different products. Since Azure Kit repository is private, here we could say to contact sales via https://vaadin.com/acceleration to get the kit.

2022-11-29 14:52 UTC, heruan commented on articles/tools/azure/getting-started.adoc
> +Download the Azure Kit from https://github.com/vaadin/kubernetes-kit[github.com/vaadin/kubernetes-kit]. When you've done this, unzip it to a local directory.
@tarekoraby what do you suggest?

2022-11-30 08:39 UTC, tarekoraby commented on articles/tools/azure/getting-started.adoc
> +Download the Azure Kit from https://github.com/vaadin/kubernetes-kit[github.com/vaadin/kubernetes-kit]. When you've done this, unzip it to a local directory.
I pushed a commit that says 
> The Azure Kit is available in a private GitHub repository. If your commercial subscription includes the right to use the Azure Kit, or if you'd like to obtain a trial license, please contact us through this [form](https://pages.vaadin.com/contact), and we'll provide you access to the private GitHub repository. Once you have access, download the Azure Kit from [github.com/vaadin/azure-kit](https://github.com/vaadin/azure-kit). When you've done this, unzip it to a local directory.

2022-11-30 08:45 UTC, MatthewVaadin requested changes
Apart from the vale checks, this looks good. Could you address those?

2022-11-30 09:02 UTC, tarekoraby commented
@MatthewVaadin I believe those are okay, given that Russell has already reviewed the PR (which already included most of the same Vale errors/warnings).

2022-11-30 09:14 UTC, MatthewVaadin approved these changes

2022-11-30 13:28 UTC, merged