docs: added information on BrowserTestInfo
vaadin/docs pull request #2057
Opened 2023-01-25 13:39 UTC by MarcinVaadin

Added missing information on how to access WebDriver on JUnit 5 TestBench tests

2023-02-06 13:00 UTC, caalador requested changes

2023-02-06 13:00 UTC, caalador commented on articles/testing/end-to-end/advanced-concepts.adoc
> +Web pages load typically when immediately rendered by the browser. In such applications, you can test the page elements immediately after the page is loaded. In Vaadin and other Single-Page Applicati
```suggestion
Web pages are typically loaded and rendered immediately by the browser. In such applications, you can test the page elements immediately after the page is loaded. In Vaadin and other Single-Page Applications (SPAs), rendering is done by JavaScript code, asynchronously. Therefore, you need to wait until the server has given its response to an AJAX request and the JavaScript code finishes rendering the UI.
```
This was a bit confusing

2023-02-07 09:46 UTC, MarcinVaadin commented
@russelljtdyer - please check last commit [d6122ae](https://github.com/vaadin/docs/pull/2057/commits/d6122aee1a7123f3a70e51eaf27ad1bf72729067) and merge if ok

2023-02-07 09:49 UTC, caalador approved these changes

2023-02-15 12:15 UTC, jouni approved these changes

2023-02-15 12:16 UTC, jouni commented
Looks good to me. I don't think Russell needs to review this again.

2023-02-15 12:17 UTC, merged