docs: add Grid Pro text and TS examples
vaadin/docs pull request #206
Opened 2021-02-19 19:33 UTC by DiegoCardoso

2021-02-22 08:50 UTC, tomivirkki requested changes

2021-02-22 08:50 UTC, tomivirkki commented on src/main/resources/data/people.json
> +    "profession": "Software Engineer III"
The existing data shouldn't be changed this much since it affects existing examples also.

Wouldn't feel safe picking a "Software Engineer" as my doctor 😅  (from ComboBox examples)

![Screenshot 2021-02-22 at 10 41 35](https://user-images.githubusercontent.com/1222264/108684375-81e7d680-74fb-11eb-8c86-63307227833f.png)

2021-02-22 09:02 UTC, tomivirkki requested changes

2021-02-22 09:02 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-styling-editable-cells.ts
> +      <vaadin-grid-pro class="editableCustomEffect" .items=${this.items}>
By convention, we don't use camel case for class names. Use "editable-custom-effect" instad.

2021-02-22 14:30 UTC, DiegoCardoso commented on articles/ds/components/grid-pro/index.asciidoc
> +:experimental:
It is needed due to the use of the keyboard macro.

2021-02-22 14:31 UTC, DiegoCardoso commented on frontend/demo/component/gridpro/grid-pro-styling-editable-cells.ts
> +      <vaadin-grid-pro class="editableCustomEffect" .items=${this.items}>
Changed it to kebab-case.

2021-02-22 14:32 UTC, DiegoCardoso commented on src/main/resources/data/people.json
> +    "profession": "Software Engineer III"
Added only the `birthday` property to the existing people dataset instead.

2021-02-22 14:53 UTC, tomivirkki approved these changes

2021-02-22 14:57 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-editors.ts
> +            root.appendChild(datePicker);
Doesn't `lit-html`'s `render` work here?

2021-02-22 15:11 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-edit-column.ts
> +          }}
The column and model parameters shouldn't need to be optional. The optional `model`'s `item` is cast to `Person` and accessed later, so optional doesn't work here.
```suggestion
          .renderer=${(root: HTMLElement, _column: GridColumnElement, model: GridItemModel) => {
            const { firstName, lastName } = model.item as Person;
            render(
              html`
                ${firstName} ${lastName}
              `,
              root
            );
          }}
```

The renderers in `grid-pro-editors.ts` have the same issue.

2021-02-22 15:15 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-edit-column.ts
> +          }}
Well, interestingly `GridBodyRenderer` defines them as optional...not sure why.

2021-02-22 18:16 UTC, DiegoCardoso commented on frontend/demo/component/gridpro/grid-pro-editors.ts
> +            root.appendChild(datePicker);
I tried using it, but the second render won't work. My understanding is that the `render` helper adds two comments markers before and after the element to be attached to mark its position. But, when the cell leaves the editing mode, it removes all the content to place the plain text. The next time the cell enters edit mode, `render` is called, but the comment markers won't be attached anymore and it will not attach the field.

I guess it might've work if GridPro also uses `render` internally for the same purpose.

2021-02-23 08:19 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-editors.ts
> +            root.appendChild(datePicker);
Reported a grid pro issue here: https://github.com/vaadin/vaadin-grid-pro/issues/163

2021-02-23 08:55 UTC, tomivirkki commented on frontend/demo/component/gridpro/grid-pro-edit-column.ts
> +          }}
This is still an issue:
```js
const item = model?.item as Person; // Casting a possible undefined as a Person
item.firstName; // Accessing a property of the possibly undefined object
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +:experimental:
Yeah. We could set that attribute in docs-app already, but right now it’s needed in each article separately.

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +Grid Pro is an extension of the <<../grid#,Grid>> component and thus all of Grid’s features
```suggestion
Grid Pro is an extension of the <<../grid#,Grid>> component and all Grid’s features
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +kbd:[Enter] and kbd:[Shift+Enter] can be made to additionally focus the editable cell in the next and previous row, respectively, by using the Enter Next Row mode.
```suggestion
kbd:[Enter] and kbd:[Shift+Enter] can be made to focus the editable cell in the next and previous row, respectively, by using the Enter Next Row mode.
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +Grid Pro features three recommended built-in editors: Text Field, Checkbox and Select.
```suggestion
Grid Pro features three recommended built-in editors: Text Field, Checkbox, and Select.
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +Additionally or alternatively, you can suffix read-only columns with “(read-only)” and/or editable columns with “(editable)”.
```suggestion
For example, you can suffix read-only columns with “(read-only)” and/or editable columns with “(editable)”.
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +=== Inline vs Non-inline Editing
```suggestion
=== Inline vs Non-Inline Editing
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +- users typically need to edit only one particular item at a time
```suggestion
- users typically need to edit only one item at a time
```

2021-02-23 10:22 UTC, jouni commented on articles/ds/components/grid-pro/index.asciidoc
> +- any of the editors need to be bigger than a simple field, such as a Text Area or multiselect field of any kind
```suggestion
- any of the editors need to be bigger than a simple field, such as a Text Area or multi-select field of any kind
```

2021-02-23 14:44 UTC, DiegoCardoso commented on frontend/demo/component/gridpro/grid-pro-edit-column.ts
> +          }}
Added checks for undefined.

2021-02-24 09:05 UTC, merged