feat: add docs for NonNullApi and nullability annotation collision
vaadin/docs pull request #2097
Opened 2023-02-06 20:39 UTC by Lodin

Resolves vaadin/hilla#641

2023-02-08 09:32 UTC, cromoteca requested changes

2023-02-08 09:32 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +It makes any type non-nullable again.
I'd not disclose our priority numbers, they don't matter in the documentation, they are just an implementation detail. Saying the order is enough.

2023-02-13 15:52 UTC, cromoteca requested changes

2023-02-13 15:52 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +It makes any type that affected by `@NonNullApi` annotation nullable.
This sentence is not clear

2023-02-13 15:52 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +It makes any type non-nullable again.
I can't figure out the "again" case

2023-02-13 15:52 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +    public Short forcedNonNullNumber;
While this is useful to explain priorities, I'd not show it as it makes no sense to put both annotations on the same field. Or at least I'd add a comment to clarify that it is just to show the priority.

2023-02-13 16:14 UTC, Lodin commented on articles/lit/reference/type-nullability.adoc
> +It makes any type non-nullable again.
Hmm... Would it be more clear this way?
```
It makes any nullable type (either default or made nullable by `@Nullable` annotation) non-nullable. 
```
or it's better to make it as simple as possible? 
```
It makes any nullable type non-nullable.
```

2023-02-13 16:16 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +It makes any type non-nullable again.
I prefer the latter

2023-02-13 16:23 UTC, cromoteca commented on articles/lit/reference/type-nullability.adoc
> +It makes any type that affected by `@NonNullApi` annotation nullable.
Reading it again, I'm not sure that the whole collision section is needed: you already clarified at line 147 how to restore nullability under `NonNullApi`, and conflicts between `Nullable` and `Nonnull` are unlikely to happen.

2023-02-13 16:25 UTC, Lodin commented on articles/lit/reference/type-nullability.adoc
> +It makes any type that affected by `@NonNullApi` annotation nullable.
Hmm. You're right. I guess I just followed the implementation details.

2023-02-13 16:29 UTC, cromoteca approved these changes

2023-02-14 08:47 UTC, platosha approved these changes

2023-02-15 12:35 UTC, merged