Add context-menu TS examples and docs
vaadin/docs pull request #212
Opened 2021-02-22 15:43 UTC by yuriy-fix

2021-03-02 14:32 UTC, DiegoCardoso requested changes

2021-03-02 14:32 UTC, DiegoCardoso commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +      <!-- tag::snippethtml[] -->
I feel that separating the snippet like this makes the code shows a bit confusing:
![image](https://user-images.githubusercontent.com/262432/109659633-a28cdd80-7b46-11eb-8952-bc3e369e11fc.png)

2021-03-02 14:32 UTC, DiegoCardoso commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +      <!-- tag::snippethtml[] -->
Same issue as reported on the other comment.

2021-03-02 14:32 UTC, DiegoCardoso commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +            { component: this.createSearchField() },
The search field behavior feels a bit odd. Once you start typing, focus jumps to the item that matches the value (the Context Menu's default behavior).

2021-03-02 15:20 UTC, jouni commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +      <!-- tag::snippethtml[] -->
One option is to use two separate include::[] lines for the tags, and add ... between them. Here’s an example: 

```asciidoc
[source, html]
----
include::{root}/frontend/demo/component/combobox/combo-box-presentation.ts[render,tag=combobox,indent=0,group=TypeScript]

...

include::{root}/frontend/demo/component/combobox/combo-box-presentation.ts[render,tag=renderer,indent=0,group=TypeScript]
----
```

Result: https://vaadin.com/docs-beta/latest/ds/components/combo-box/#custom-item-presentation

2021-03-03 11:05 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +            { component: this.createSearchField() },
Yeah, I **have removed the search field**. Firstly, tried to workaround it with stopping the propagation of the event, but it turns out to be more complex on mobile, so it's definitely not a part of best practices.

2021-03-04 09:14 UTC, tomivirkki requested changes

2021-03-04 09:14 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-keyboard-shortcuts.ts
> +    this.grid && (this.grid.selectedItems = item ? [item] : []);
Instead of storing the grid element as a property and assigning its `selectedItems` programmatically, make the `selectedItems` an internal property and data-bind it to the grid in the template (just like you do with `gridItems`).

2021-03-04 09:14 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-keyboard-shortcuts.ts
> +    }
This goes really deep into the component internal details. Too much so to be in the official product documentation.

2021-03-04 09:22 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-dividers.ts
> +  @internalProperty()
Only use `@internalProperty` where it's meaningful

2021-03-04 09:29 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +    { text: 'Allison Torres', checkable: true, checked: true },
The `checked` property never changes here. `checkable` is not part of context-menu API as the documentation suggests. It was used in the demo logic of an [old example](https://cdn.vaadin.com/vaadin-context-menu/4.5.0/demo/#context-menu-items-demos) but you'd need to add similar app logic to have it do anything.

2021-03-04 09:37 UTC, tomivirkki commented on articles/ds/components/context-menu/index.asciidoc
> +=== Custom Items
```suggestion
== Custom Items
```

2021-03-04 09:42 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +    const contextMenu = this.shadowRoot?.querySelector('vaadin-context-menu');
No need to querySelector, use
```js
@internalProperty()
private items?: ContextMenuItem[];
```

and bind it to the context menu in the template, just like with the other examples.

2021-03-06 14:43 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +    const contextMenu = this.shadowRoot?.querySelector('vaadin-context-menu');
Updated, thanks for the hint!

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +    { text: 'Allison Torres', checkable: true, checked: true },
My bad, have updated that one.

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-dividers.ts
> +  @internalProperty()
Removed.

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-keyboard-shortcuts.ts
> +    }
True that, removed the example.

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-keyboard-shortcuts.ts
> +    this.grid && (this.grid.selectedItems = item ? [item] : []);
Example removed.

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-presentation.ts
> +      <!-- tag::snippethtml[] -->
Updated.

2021-03-06 14:44 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +      <!-- tag::snippethtml[] -->
Updated.

2021-03-08 11:46 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
Avoid magic numbers

```suggestion
  private selectedItem = this.items.find(item => item.checked);
```

2021-03-08 11:47 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
Even cleaner approach would be not to maintain the redundant/duplicate `checked` property in the items but map the context-menu specific `checked` property to context-menu at the point where the property is bound...something like:

```js
.items=${this.items.map(item => {
  return { ...item, checked: item === this.selectedItem };
})}
```

2021-03-08 11:54 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-dividers.ts
> +  @internalProperty()
Didn't mean only this instance...

2021-03-08 11:58 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <hint-badge message="Open the Context Meny by clicking a Grid row."></hint-badge>
Typo "Meny"
```suggestion
      <hint-badge message="Open the Context Menu by clicking a Grid row."></hint-badge>
```

2021-03-08 11:59 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
The example description says "Open the Context Menu by clicking a Grid row.". If you define the context menu like this, it allows you to open it anywhere, for example over the header. Same issue in some other examples also.

2021-03-08 12:19 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +    menuBar &&
This cannot be falsy

2021-03-09 14:52 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
Updated.

2021-03-09 14:52 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
Updated with workaround.
Haven't applied it for `left-click` example as it won't be working properly over there. (we cannot stop propagation of the `click` event)

2021-03-09 14:52 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +    menuBar &&
Removed redundant check.

2021-03-09 15:09 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
With the latter/cleaner approach, the `checked: true` shouldn't exist in the `items` (it's only mapped at the point where it'd bound). In that case `this.items[1];` makes sense (because the index isn't defined in 2 places).

2021-03-09 15:13 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
> Nit: have to compare text prop, because checked won't be in sync.

This will have them in sync and it guarantees that `selectedItem` is always one of the instances in `items`:
`this.selectedItem = this.items.find(item => item.text === e.detail.value.text);`

2021-03-09 15:20 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
> we cannot stop propagation of the click event

Why not?

2021-03-09 15:27 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
Closing of the Context Menu and text selection won't work on header and footer rows in that case 🤔

2021-03-09 15:38 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-checkable.ts
> +  private selectedItem?: ContextMenuItem = this.items[1];
Added `this.items[1]` back and updated listener.

2021-03-09 15:42 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
Text selection seems to work (it wouldn't work if you have the context menu opening on click).

Context-menu not canceling on header click doesn't sound too tragic, but if you will, you can improve the logic by not stopping propagation if the context-menu is already open (probably an overkill).

2021-03-09 19:46 UTC, jouni commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +    menuBar.items = [{ component: this.makeIcon('vaadin:ellipsis-dots-v'), children: this.items }];
```suggestion
    menuBar.items = [{ component: this.makeIcon('vaadin:ellipsis-dots-v'), children: this.items }];
    menuBar.theme = 'icon';
```

2021-03-09 19:51 UTC, jouni approved these changes
Apart from the weird grid scroll issue (see video, desktop Safari 14.0.3, Responsive Design Mode), and the global reset styles leaking to `<hr>` elements (dividers in the menus), looks good.


https://user-images.githubusercontent.com/66382/110529154-90500800-8121-11eb-8447-038a2db7037b.mov

2021-03-12 08:32 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
Have updated the example.

2021-03-16 14:08 UTC, tomivirkki commented
![Screenshot 2021-03-16 at 15 58 52](https://user-images.githubusercontent.com/1222264/111322055-309db380-8671-11eb-8dc1-df2cdded1149.png)

This dropdown was really unexpected. What I was looking after with context-awareness in the examples is that over some items the "Edit" and "Delete" could be disabled if they're considered read-only or such. Let's not add another example for this as it wasn't in the original designs.

2021-03-16 14:22 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +      ></hint-badge>
Why wouldn't the context-menu examples use admonition blocks for hints like this, like the other examples?

2021-03-16 15:48 UTC, tomivirkki commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
The workaround lgtm. It might take someone browsing the documentation a while to understand what the workaround is for. There could be a comment (in every workaround) explaining why it's there.

2021-03-17 08:57 UTC, jouni commented on articles/ds/components/context-menu/index.asciidoc
> +
Not sure, but you might be able to use `include::[]` from within the same article. Worth trying at least, so we don’t copy-paste the same thing multiple times.

```asciidoc
// tag::example-instructions[]
[IMPORTANT]
Open the Context Menu by right-clicking (desktop) or long-pressing (mobile) a Grid row.
// end::example-instructions[]
```

```asciidoc
include::index.asciidoc[tag=example-instructions]
```

2021-03-17 09:35 UTC, yuriy-fix commented on articles/ds/components/context-menu/index.asciidoc
> +
Seems to be working. Thank you! 🙇

2021-03-17 09:35 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +      ></hint-badge>
Replaced `hint-badge` with admonition.

2021-03-17 09:36 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-left-click.ts
> +      <vaadin-context-menu open-on="click" .items=${this.items}>
Added comment and removed `context-aware` example based on the comment below.

2021-03-17 14:06 UTC, tomivirkki commented
A couple of nits about this example:
- You can open two context menus at one
- The buttons with the icons look huge.
- Why not use "tertiary" theme as [suggested](https://docs.google.com/document/d/1o9Qxz8QojsxwoEZymj2MDgGT4gSb3sPleegknckVUTg/edit?disco=AAAALJdKM8c) in the design.

<img width="724" alt="Screenshot 2021-03-17 at 15 55 44" src="https://user-images.githubusercontent.com/1222264/111479489-aff6ba00-8739-11eb-992e-d329e525a3ce.png">

2021-03-18 19:37 UTC, DiegoCardoso commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +            .renderer="${this.menuBarRenderer.bind(this)}"
Instead of forcing the binding here, you can make the `menuBarRenderer` become a class property

(`menuBarRenderer = (root: HTMLElement) => {...}`)

2021-03-19 12:02 UTC, yuriy-fix commented on frontend/demo/component/contextmenu/context-menu-best-practices.ts
> +            .renderer="${this.menuBarRenderer.bind(this)}"
Thanks for the hint! Updated 🙇

2021-03-19 14:01 UTC, DiegoCardoso approved these changes

2021-03-23 11:50 UTC, merged