fix: update available properties
vaadin/docs pull request #2157
Opened 2023-02-14 12:36 UTC by caalador

Update properties that are available
and add default value for each property.

Fixes #2123

2023-02-14 14:03 UTC, mcollovati commented on articles/configuration/properties.asciidoc
> +|Returns whether sync ID checking is enabled. The sync ID is used to handle situations in which the client sends a message to a connector that has been removed recently from the server.
```suggestion
|Enables or disables the sync ID checking. The sync ID is used to handle situations in which the client sends a message to a connector that has been removed recently from the server.
```

2023-02-14 14:04 UTC, mcollovati commented on articles/configuration/properties.asciidoc
> +|Returns the number of seconds that a WebComponent will wait for a reconnect before removing the server-side component from memory.
```suggestion
|Defines the number of seconds that a WebComponent will wait for a reconnect before removing the server-side component from memory.
```

2023-02-15 05:41 UTC, caalador commented on articles/configuration/properties.asciidoc
> +|When set to `true`, the session is closed if no UI is active. From the servlet container's viewpoint, heartbeat requests are like any other request. This means that as long as there is an open UI, t
Yes. Also the description is a hard to follow so I updated it a bit.

2023-02-15 05:41 UTC, caalador commented on articles/configuration/properties.asciidoc
> +|This determines whether the [classname]`VaadinSession` instances of the users are serialized on server shutdown when running in development mode. When the parameter is set to `false`, only other HTT
Updated description

2023-02-15 05:41 UTC, caalador commented on articles/configuration/properties.asciidoc
> +|The permitted values are "disabled" or "manual". See <<{articles}/advanced/server-push#, Server Push>> for more information.
Added.

2023-02-15 06:15 UTC, mcollovati requested changes

2023-02-15 06:15 UTC, mcollovati commented on articles/configuration/properties.asciidoc
> +|Returns the servlet mapping that bidirectional ("push") client-server communication should use.
Sorry, missed that one on the previous review
```suggestion
|Sets the servlet mapping that bidirectional ("push") client-server communication should use.
```

2023-02-15 08:00 UTC, mcollovati approved these changes

2023-02-23 08:42 UTC, merged