docs: describe the difference between pattern and allowedCharPattern
vaadin/docs pull request #2191
Opened 2023-02-16 17:46 UTC by vursen

The PR hopes to improve the description of pattern and allowedCharPattern Text Field features so that the difference between them will be more clear.

2023-02-17 14:22 UTC, vursen commented on articles/components/text-field/index.asciidoc
> +Characters that you enter into Text Field can be restricted using a regular expression. When enabled, the user can't enter characters that match the regular expression. If they try to enter such char
```suggestion
Characters that you enter into Text Field can be restricted using a single-character regular expression. When enabled, the user can't enter characters that match the regular expression. If they try to enter such characters, the component gives visual feedback that the input was prevented.
```

2023-02-17 14:36 UTC, vursen commented on articles/components/text-field/index.asciidoc
> +Characters that you enter into Text Field can be restricted using a regular expression. When enabled, the entry of characters not matching the regular expression is prevented and gives the field a sh
Addressed in the recent version. Let me know if you think we should specifically highlight that full regular expressions won't work.

2023-02-19 15:35 UTC, rolfsmeds requested changes
Made some minor adjustments: I feel this is good enough for now – we can make it even more explicit if misunderstandings continue :)

2023-02-19 15:35 UTC, rolfsmeds commented on articles/components/text-field/index.asciidoc
> +The following examples invalidates any value that doesn't consist exclusively of numbers, parentheses, dashes, and the plus sign:
```suggestion
The following example invalidates any value that doesn't consist exclusively of numbers, parentheses, dashes, and the plus sign:
```

2023-02-19 15:35 UTC, rolfsmeds commented on articles/components/text-field/index.asciidoc
> +Pattern is a regular expression that Text Field's value is matched against during validation. Any value that doesn't match the pattern invalidates the field.
```suggestion
The pattern is a regular expression that Text Field's complete value is matched against during validation. Any value that doesn't match the pattern invalidates the field.
```

2023-02-19 15:35 UTC, rolfsmeds commented on articles/components/text-field/index.asciidoc
> +Characters that the user enters into Text Field can be restricted using a single-character regular expression. When enabled, the user can only enter characters that match the regular expression. If t
```suggestion
Individual characters that the user enters into Text Field can be restricted using a _single-character_ regular expression. When enabled, the user can only enter characters that match the regular expression. If they try to enter any other characters, the component gives visual feedback that the input was prevented.
```

2023-02-23 08:46 UTC, merged

2023-02-23 08:47 UTC, jouni commented
Merged based on Rolf’s comment, even though his review requested changes.