feat(hilla): add testing article
vaadin/docs pull request #2215
Opened 2023-02-20 21:21 UTC by Lodin

2023-03-22 12:54 UTC, jouni commented on articles/lit/guides/testing/end-to-end/playwright.adoc
> +.UsersEndpoint.java
You don't need to define the file name as the title when using in `include::[]`. The filename is picked up from the included file directly, and used as the source code block title by default.
```suggestion
```

2023-03-27 13:50 UTC, jouni commented on .asciidoctorconfig
Is this file specific to the IntelliJ plugin only? https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

What benefit does it have to add this file? Perhaps we should also set the `:articles: {asciidoctorconfigdir}/articles` attribute at the same time.

2023-03-27 14:15 UTC, Lodin commented on .asciidoctorconfig
> Is this file specific to the IntelliJ plugin only?
Probably, it is.
I have added that file to solve a problem in IDEA that it was unable to correctly resolve a `include::{root}/some/path` expressions. With that file, it can do that, which simplifies the searching for files and makes it less error-prone. 

If you ok to keep that file in the codebase, I will add `:articles:` variable in this file as well.

2023-03-27 16:10 UTC, cromoteca requested changes

2023-03-27 16:10 UTC, cromoteca commented on articles/lit/guides/testing/frontend.adoc
> +Note that Karma does not yet support EMS.
EMS/ESM?

2023-03-27 16:10 UTC, cromoteca commented on articles/lit/guides/testing/frontend.adoc
> +echo "" > karma.config.js
Must choose between JS and CJS in the example

2023-03-27 16:10 UTC, cromoteca commented on articles/lit/guides/testing/frontend.adoc
> +    "test": "karma start karma.config.cjs",
JS/CJS

2023-03-27 16:10 UTC, cromoteca commented on src/main/resources/hilla/testing/frontend/karma.config.js
> +        pattern: 'test/**/*.test.ts',
Should start with `frontend` and end with TS/TSX according to Lit/React

2023-03-27 16:10 UTC, cromoteca commented on src/main/resources/hilla/testing/frontend/react/Foo.test.tsx
> +import sinon from 'sinon';
Marked with error in VS Code:
> This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

2023-03-27 16:10 UTC, cromoteca commented on src/main/resources/hilla/testing/frontend/react/Foo.test.tsx
> +import Foo from './Foo.js';
`Foo.js` cannot be found, compilation is needed before testing

2023-03-27 16:10 UTC, cromoteca commented on src/main/resources/hilla/testing/frontend/react/Foo.tsx
> +export type FooProps = {
This type cannot be seen in the example included in the page. I cannot find the usual button to expand code.

2023-03-28 07:45 UTC, cromoteca commented on articles/lit/guides/testing/frontend.adoc
> +// end::content[]
I'd expect to read something more after the code example: it looks to me that this article misses an end, even if obvious.

2023-03-28 07:56 UTC, tarekoraby commented on src/main/java/com/vaadin/demo/hilla/testing/UsersPageTest.java
> +        Assertions.assertEquals(List.of("John Doe", "Jane Doe"), users);
This is not a TestBench API. Isn't the point is to show how to use TestBench?

2023-03-28 07:58 UTC, tarekoraby commented on src/main/java/com/vaadin/demo/hilla/testing/UsersPageTest.java
> +        Assertions.assertEquals(List.of("John Doe", "Jane Doe"), users);
We should instead use the `GridElement` API. Something like `$(GridElement.class).id("users").getRow(...)`.

2023-04-03 07:08 UTC, cromoteca commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +async function loginAgain() {
What about a formatting PR? Especially for this file which is being edited in https://github.com/vaadin/docs/pull/2274 and so will give conflicts. And to make it easier to review this PR.

2023-05-19 13:36 UTC, jouni commented
@platosha, please get someone to resolve the conflicts and address the review comments. We shouldn't keep this PR hanging in here for many more months.

2023-08-08 06:52 UTC, jouni commented
Closing as stale.

2023-08-08 06:52 UTC, closed without merging