Docs: add upgrade notes for Hilla 2.0
vaadin/docs pull request #2226
Opened 2023-02-24 16:43 UTC by platosha

Fixes vaadin/hilla#784
Fixes vaadin/hilla#777
Fixes vaadin/hilla#778

This adds the upgrade guide section for Hilla 2.0.

Much of the existing content in the guide applies to Hilla applications
as well, and the changes elsewhere in Vaadin 24.0 (in the base stack and Vaadin
components) have significant impact on migrating Hilla apps to 2.0.

It seems better to add a Hilla section here rather then an entirely separate
guide in Hilla docs, to avoid duplicated content and making it more
convenient for Hilla users to follow.

2023-02-27 13:11 UTC, platosha commented
Need to rewrite the article into a separate guide for Hilla. Marking as a draft for now.

2023-02-27 15:24 UTC, cromoteca commented on articles/upgrading/index.adoc
> +Maven and Node are required to be installed on the developer system, with the `mvn` and `node` executables available on the `PATH` environment variable. Follow the link:https://maven.apache.org/insta
Consider https://github.com/vaadin/hilla/pull/792

2023-03-01 10:07 UTC, cromoteca commented on articles/lit/guides/upgrading/_styling.adoc
> +The instructions below are based on the old approach, which is the faster route for upgrading.
```suggestion
The instructions below are based on the old approach, which is the fastest route for upgrading.
```

2023-03-01 10:34 UTC, cromoteca requested changes
As usual for documentation, changes requested are mostly suggestion, feel free to discard them.

2023-03-01 10:34 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +----
Isn't that misleading, given that Gradle is not supported?

2023-03-01 10:34 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +The new behavior of null type annotations (`@dev.hilla.Nonnull` and such) for arrays in endpoints and entity classes is:
```suggestion
The behavior of null type annotations (`@dev.hilla.Nonnull` and such) has been fixed according to the https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.7.4[Java Language Specification]. In particular, it means that for arrays in endpoints and entity classes is:
```

2023-03-01 10:34 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +- `byte @dev.hilla.Nonnull []` is non-null array type which items are nullable.
I'd use `String` rather than `byte` here, to highlight what is `null` and what is not.

2023-03-01 10:34 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +* Deprecated misspelled `vaadin-icons` removed: `buss`, `funcion`, `megafone`, `palete`, `trendind-down`
😮

2023-03-01 15:47 UTC, platosha commented on articles/lit/guides/upgrading/_styling.adoc
> +The instructions below are based on the old approach, which is the faster route for upgrading.
I got your point, but perhaps it would make even more sense to downplay the comparison here. Rephrased.

2023-03-01 15:54 UTC, platosha commented on articles/lit/guides/upgrading/_styling.adoc
> +The context menu's items, `vaadin-context-menu-item`, no longer extend the `vaadin-item` element, and as such no longer inherit styling from it.
Mind if I use “context menu” two separate words, unless we mean the `web-component` name? It feels common for me, even this very section header says it. This also helps to avoid confusing the UI concept name with the HTML tag name.

2023-03-01 15:57 UTC, cromoteca commented on articles/lit/guides/upgrading/_styling.adoc
> +The context menu's items, `vaadin-context-menu-item`, no longer extend the `vaadin-item` element, and as such no longer inherit styling from it.
I added the dash as in that case it looks like a [compound adjective](https://en.wikipedia.org/wiki/Compound_modifier#Compound_adjectives) to me.

2023-03-01 16:01 UTC, platosha commented on articles/lit/guides/upgrading/_styling.adoc
> +The context menu's items, `vaadin-context-menu-item`, no longer extend the `vaadin-item` element, and as such no longer inherit styling from it.
Ah, true that.

2023-03-01 16:14 UTC, platosha commented on articles/lit/guides/upgrading/index.adoc
> +* Deprecated misspelled `vaadin-icons` removed: `buss`, `funcion`, `megafone`, `palete`, `trendind-down`
What do you mean? I guess your reaction is related with removing the `**Element` web component classes, because it gets confusing with React components, right?

2023-03-01 16:16 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +* Deprecated misspelled `vaadin-icons` removed: `buss`, `funcion`, `megafone`, `palete`, `trendind-down`
Sorry, I was just surprised by the misspelled names! That's why I had marked the conversation as resolved. When pointing to a single line, GitHub doesn't highlight it correctly.

2023-03-01 17:19 UTC, cromoteca requested changes

2023-03-01 17:19 UTC, cromoteca commented on articles/react/guides/upgrading/index.adoc
> +`@vitejs/plugin-react` npm development dependency needs to be updated to a version compatible with Vite 4. Change the version the `package.json` file:
```suggestion
`@vitejs/plugin-react` npm development dependency needs to be updated to a version compatible with Vite 4. Change the version in the `package.json` file:
```

2023-03-01 17:19 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +    <version>3.0.0</version>
I see no reason to suggest version 3.0.0.

2023-03-01 17:19 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +* Number Field's default width now matches that of other text input components; the old default can be brought back with CSS `vaadin-number-field { width:8em; }`
Does Number Field look like another compound adjective here?

2023-03-01 17:19 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +* Number Field's default width now matches that of other text input components; the old default can be brought back with CSS `vaadin-number-field { width:8em; }`
I suppose that this document comes from Flow. Maybe the docs folks don't want to check language twice. You could ask them to first check the Flow version and then copy it.

2023-03-01 17:27 UTC, platosha commented on articles/lit/guides/upgrading/index.adoc
> +    <version>3.0.0</version>
The latest is `3.0.3`, let me use it.

```suggestion
    <version>3.0.3</version>
```

2023-03-02 07:27 UTC, jouni commented
If at all feasible, try to address as many Vale error and warning issues as possible. If “suggestions” seem easy to fix, please consider addressing those as well.

2023-03-02 10:49 UTC, platosha commented on articles/lit/guides/upgrading/index.adoc
> +    <version>3.0.3</version>
```suggestion
    <version>3.0.2</version>
```

2023-03-07 09:23 UTC, cromoteca requested changes

2023-03-07 09:23 UTC, cromoteca commented on articles/lit/guides/upgrading/index.adoc
> +<hilla.version>2.0.0.rc1</hilla.version>
Just a reminder to update to final

2023-03-08 08:31 UTC, cromoteca approved these changes

2023-03-08 10:31 UTC, platosha commented
@jouni I need your help. The last remaining Vale suggestion for inline CSS examples in the style migration doc blocks merging for me here. Muting it does not work for some reason, and extracting the examples seems infeasible. Any suggestions? Could you merge, perhaps?

2023-03-08 16:08 UTC, jouni commented
Yeah, source code suggestions can't be suppressed (a limitation with Vale rules that use `scope: raw`). 

I can merge. I assume this is urgently needed for anyone looking to upgrade to Hilla 2.

2023-03-08 16:09 UTC, merged

2023-03-08 16:15 UTC, platosha commented
@jouni thank you 🙏