New Okta tutorial
vaadin/docs pull request #2244
Opened 2023-03-02 10:49 UTC by Mikaelsu

Added a step-by-step tutorial on how to integrate Okta with SSO Kit

2023-03-03 10:05 UTC, tamasmak requested changes

2023-03-03 13:09 UTC, jouni commented on articles/tools/sso/integrations/okta.asciidoc
> +You can access your Okta workspace after signing up to Okta. A workplace includes an Authorization Server and administrator account. The workspace is behind a URL like [interfacename]_dev-12345678.ok
Yeah, I suppose it should be “workspace” there as well.

2023-03-03 14:02 UTC, tamasmak approved these changes

2023-03-13 09:55 UTC, merged

2023-03-14 07:13 UTC, jouni commented
Picked to `v23` in 8bf6c9100eac5a8febf61a5b6e4926deba820522