chore: add OSGi services tutorial
vaadin/docs pull request #227
Opened 2021-03-03 11:06 UTC by denis-anisimov

fixes #194

2021-03-03 14:03 UTC, jouni requested changes

2021-03-03 14:03 UTC, jouni commented on articles/flow/integrations/osgi-advanced.asciidoc
> +title: Advanced Using Vaadin with OSGi
I feel we should add this as a secondary tab under the main OSGi article. @magi42, would you agree?

Or, it could be a sub-article under the main one (visible in the sidebar navigation, nested under the current OSGi article).

2021-03-03 14:04 UTC, jouni commented on articles/flow/integrations/osgi-advanced.asciidoc
> +title: Advanced Using Vaadin with OSGi
In any case, the title needs work.

2021-03-03 14:43 UTC, magi42 commented on articles/flow/integrations/osgi-advanced.asciidoc
> +title: Advanced Using Vaadin with OSGi
Yes, either as a tab or in a section. Should Karaf also be there?
Tabs are good for similar items, and maybe "Basic" and "Advanced" are OK tabs as well.
Yes the title really needs work as all other articles under Integrations are very short.

2021-03-14 09:37 UTC, pleku commented on articles/flow/integrations/osgi-advanced.asciidoc
> +title: Advanced Using Vaadin with OSGi
This is done - I used the use case as the title as it is what the whole section is about - I think it is easier for people to discover services usage docs if it is directly in the title.

2021-03-16 08:51 UTC, jouni commented
There’s a broken cross reference, that’s why the preview build isn’t showing up. I’m figuring out with Netlify how to get the deploy to fail as well if the build fails, so that the PR check would not show that everything is okay.

    1:24:12 PM: error Broken cross reference ../routing/overview in flow/integrations/osgi/osgi-basic.asciidoc

2021-03-17 17:03 UTC, jouni commented
Another broken cross reference:

    error Broken cross reference osgi-basic in flow/integrations/osgi-karaf.asciidoc

It would be best if you run the development build yourself, then you can see all the broken references immediately (the preview build fails on the first one it encounters).

2021-05-24 06:24 UTC, jouni commented
@denis-anisimov and @pleku, what’s the status of this PR?

2021-06-22 12:28 UTC, pleku commented
@jouni now the broken links are fixed, this should IMO be merged.

2021-06-22 12:38 UTC, magi42 commented
Wait, I'm doing a review.

2021-06-22 15:40 UTC, magi42 commented
PLEASE check my changes. I removed one example, aiming to simplify the text. I thought that the MainView actually needs the check for the availability of the service (it's always available while the service may not be), so need to give that example right away. Somehow I feel that the text could be shortened to half the size, but I didn't go into that.

2021-06-23 06:30 UTC, jouni commented on articles/flow/integrations/overview.asciidoc
> +<<osgi/osgi-karaf#, Karaf>>::
The naming of the articles makes me wonder if these two articles ("OSGi" and "Apache Karaf") should be nested in a hierarchy. Can Karaf be seen as an extension/customization of OSGi?

2021-06-23 06:32 UTC, jouni commented on articles/flow/integrations/overview.asciidoc
> +<<osgi/osgi-karaf#, Karaf>>::
But the naming of the articles could be simplified. No need to keep the `osgi-` prefix in the file names.

2021-06-23 06:36 UTC, jouni reviewed
Up to @magi42 when it’s good to go.

2021-06-23 06:36 UTC, jouni approved these changes

2021-06-23 07:15 UTC, pleku requested changes
I think there are two broken links after the rename of files.

2021-06-23 07:15 UTC, pleku commented on articles/flow/integrations/overview.asciidoc
> +<<osgi/osgi-karaf#, Karaf>>::
```suggestion
<<osgi/karaf#, Karaf>>::
```

2021-06-23 07:15 UTC, pleku commented on articles/flow/integrations/overview.asciidoc
> +<<osgi/osgi-basic#, OSGi>>::
```suggestion
<<osgi/basic#, OSGi>>::
```

2021-06-23 07:18 UTC, magi42 approved these changes

2021-06-23 07:20 UTC, pleku approved these changes

2021-06-23 07:30 UTC, pleku approved these changes

2021-06-23 07:52 UTC, merged

2021-06-23 07:58 UTC, jouni commented
Ah, thanks for fixing the cross refs! Apologies for being completely thoughtless about that 🤦