Add Hilla SSO Kit Client documentation
vaadin/docs pull request #2274
Opened 2023-03-11 23:31 UTC by tamasmak

2023-03-13 06:22 UTC, tarekoraby commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +Add the `sso-kit-client-lit` library to the [filename]`packages.json` of a Hilla application like so:
Which is better, editing `packages.json` or doing `npm install --save`?

2023-03-13 09:58 UTC, cromoteca commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +import { singleSignOnContext } from '@sso-kit/sso-kit-client-lit/SingleSignOnContext.js';
I suggest to
```suggestion
import { singleSignOnContext as sso } from '@sso-kit/sso-kit-client-lit/SingleSignOnContext.js';
```
and then use `sso` instead of the long `singleSignOnContext` one in code.

2023-03-28 16:07 UTC, tamasmak commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +Add the `sso-kit-client-lit` library to the [filename]`packages.json` of a Hilla application like so:
`npm install --save` is much better and preferred, changed to use that.

2023-03-28 16:09 UTC, tamasmak commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +import { singleSignOnContext } from '@sso-kit/sso-kit-client-lit/SingleSignOnContext.js';
Now, `ssoContext` is used  for `SingleSignOnContext` and `user` for `User` classes.

2023-03-30 13:14 UTC, mcollovati commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +}, []);
Can we make explicit that this code should go inside the `MenuOnLeftLayout` function?

2023-03-30 15:37 UTC, mcollovati commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +                    </configuration>
As commented in the lit `getting-started`, perhaps there's no need to duplicate the configuration in the production profile

2023-03-31 07:04 UTC, tamasmak commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +}, []);
Yes, that would make it more clear.

2023-03-31 07:27 UTC, tamasmak commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
> +                    <!-- ... -->
Good point. To add it to `build` section only is enough.

2023-03-31 07:28 UTC, tamasmak commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +                    </configuration>
Same comment here as for the lit `getting started`.

2023-03-31 08:47 UTC, tamasmak commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +}, []);
Updated the comment part.

2023-03-31 08:49 UTC, tamasmak commented on articles/react/acceleration-kits/sso-kit/getting-started.adoc
> +</dependency>
Actually, non of the spring dependencies were required. Removed them in both docs.

2023-04-05 09:35 UTC, heruan requested changes

2023-04-05 09:35 UTC, heruan commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
>  </ConfirmDialog>
This example (and its React counterpart) suggests a confusing use case: it first calls `setLoggedOut(true)` when the logout happens, then opens the dialog and if it is canceled it calls `setLoggedOut(false)` while the user is no more authenticated.

This use case should be expressed with a consistent example, possibly changing the API (see https://github.com/vaadin/sso-kit/issues/93).

2023-04-11 07:50 UTC, tamasmak commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
>  </ConfirmDialog>
Changing the mentioned API simplified this part. Don't need to call the  `setLoggedOut(false)` anymore as the the new `logout()` function will make the page to reload and set the logged out state to its default value. Updated the documentation according to this.

2023-04-11 08:09 UTC, cromoteca commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
>  </ConfirmDialog>
If you reload the page in `onCancel`, that defeats the very reason to give the user a choice between logging in again immediately or not. The purpose of being able to cancel is to do something to save unfinished work. Imagine he was writing some long text, for example. He could at least copy that text and then relogin.

2023-04-11 11:45 UTC, heruan commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
>  </ConfirmDialog>
If we permit the user to stay on an inconsistent state, e.g. a form on a protected page, we give the false impression of being still logged in while we're actually unauthenticated. That means that if the user finishes their work and submits the form, they'll most probably get an error and lose their work anyways.

Saving the form content on a local cache so that you can recover if after logging in would be a better solution (e.g. like GitHub does), but that's out the scope of the SSO Kit documentation.

2023-04-11 13:32 UTC, cromoteca commented on articles/lit/acceleration-kits/sso-kit/getting-started.adoc
>  </ConfirmDialog>
Yes it should be clearly stated in the dialog text that the state will be inconsistent if staying on the page. Anyway, as the local state becomes unauthenticated, the developer still has the option to do actions like disabling the submit button. Our goal is to offer useful tools and reasonable defaults.

Another solution could be to implement, instead of a confirm dialog, a modal dialog with an iframe that loads the login form, so that the user can relogin without losing the page and its unsaved changes.

2023-05-19 12:54 UTC, jouni commented
I tried looking at the conflicts and merging them, but I’m not confident in deciding what the correct end result should be. 

@heruan, you need to get someone from the team to look at this to get it merged.

@russelljtdyer, there were new content additions after your previous commit, so this one would benefit from another language review round. But let’s wait for the conflicts to get resolved first.

2023-06-13 10:40 UTC, heruan commented
This is still pending since @tamasmak has local work and he's away this week, I expect this to be ready for final language-check once he's back on Monday 🙏

2023-06-21 06:44 UTC, heruan approved these changes

2023-06-21 06:46 UTC, heruan commented
@jouni 
> I tried looking at the conflicts and merging them, but I’m not confident in deciding what the correct end result should be.

Conflicts are resolved, this is now ready for final language-check and merge

2023-06-21 09:22 UTC, merged