docs: Documented front-end observability runtime configuration
vaadin/docs pull request #2313
Opened 2023-03-27 14:44 UTC by mcollovati

Closes vaadin/observability-kit#195

2023-03-31 08:16 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +The following properties can be used to tune frontend instrumentation
```suggestion
The following properties can be used to tune frontend instrumentation:
```

2023-03-31 08:17 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +Opposite, with dynamic configuration the instrumentation can be enabled or disabled at runtime, without restarting the server, and can be tuned for a specific browser tab. Changes are applied when th
```suggestion
With dynamic configuration, you can enable or disable the instrumentation at runtime, without restarting the server, and tune it for a specific browser tab. Changes are applied when the browser page is reloaded.
```

2023-03-31 08:18 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +With the static configuration the same settings are applied to all UI instances and to change the configuration a server restart is required.
```suggestion
With static configuration the same settings are applied to all UI instances. Changes to the configuration require a server restart.
```

2023-03-31 08:18 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +* dynamically, implementing [interfacename]`ObservabilityClientConfigurer` that applies changes at runtime.
```suggestion
* Dynamically, implementing the [interfacename]`ObservabilityClientConfigurer` interface that applies changes at runtime.
```

2023-03-31 08:20 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +Frontend observability is enabled by default, with all the client side instrumentation active.
```suggestion
Frontend observability is enabled by default, with all the client-side instrumentation active.
```

2023-04-04 09:44 UTC, MatthewVaadin requested changes

2023-04-04 09:44 UTC, MatthewVaadin commented on articles/tools/observability/configuration.asciidoc
> +For example, the following implementation shows how to set up observability based on a mutable configuration tight to the current logged user.
```suggestion
For example, the following implementation shows how to set up observability based on a mutable configuration tied to the currently logged in user.
```

2023-04-04 09:44 UTC, MatthewVaadin commented on articles/tools/observability/configuration.asciidoc
> +With the above implementation, the configuration can for example be fetched from a database table, allowing changes to be applied at runtime after a browser page reload.
```suggestion
With the above implementation, the configuration can (for example) be fetched from a database table, allowing changes to be applied at runtime after a browser page reload.
```

2023-04-04 09:44 UTC, MatthewVaadin commented on articles/tools/observability/configuration.asciidoc
> +The configurator is loaded through the Java ServiceLoader API, adding to [filename]`src/main/resources/META-INF/services/` the file [filename]`com.vaadin.observability.ObservabilityClientConfigurer`
```suggestion
The configurator is loaded through the Java ServiceLoader API, by adding the file [filename]`com.vaadin.observability.ObservabilityClientConfigurer` to the [filename]`src/main/resources/META-INF/services/` directory, with the content being the fully qualified name of the configurator class.

For this example, the file looks like this:
`com.vaadin.observability.ObservabilityClientConfigurer`
[source]
----
`org.example.UserBasedFrontendObservability`
----
```

2023-04-04 09:44 UTC, MatthewVaadin commented on articles/tools/observability/configuration.asciidoc
> +For details on observability client settings, consult the Javadocs of [interfacename]`ObservabilityClientConfiguration` interface.
```suggestion
For details on observability client settings, consult the Javadocs of the [interfacename]`ObservabilityClientConfiguration` interface.
```

2023-04-04 09:44 UTC, MatthewVaadin commented on articles/tools/observability/configuration.asciidoc
> +For Spring based project, the configurator can be loaded by exposing the implementation as a Spring managed [annotationname]`@Bean`, without the need to register the class for the ServiceLoader API.
```suggestion
For Spring based projects, the configurator can be loaded by exposing the implementation as a Spring managed [annotationname]`@Bean`, without the need to register the class for the ServiceLoader API.
```

2023-04-05 04:59 UTC, MatthewVaadin approved these changes

2023-04-06 08:48 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +With dynamic configuration, you can enable or disable the instrumentation at runtime, without restarting the server, and tune it for a specific browser tab. Changes are applied when the browser page
I wonder why you wanted to change from active to passive voice in the first sentence? Is it weird to say “you” when it’s the software enabling/disabling the instrumentation based on the configuration?

Splitting it into two standalone sentences is good, though 👍

2023-04-06 08:49 UTC, jouni commented on articles/tools/observability/configuration.asciidoc
> +With the above implementation, the configuration can for example be fetched from a database table, allowing changes to be applied at runtime after a browser page reload.
I would rather use commas than parenthesis here.

2023-04-20 11:06 UTC, merged