WIP Splitting layouts
vaadin/docs pull request #2315
Opened 2023-03-28 09:30 UTC by Mikaelsu

Moved Horizontal and Vertical Layouts to separate chapters and wrote new examples. 

Closes #2106 and #1616

2023-04-18 12:05 UTC, rolfsmeds requested changes
This PR should also
- Remove the Basic Layouts page and replace the links to it from:
- articles/components/index.asciidoc
- artitlces/components/scroller/index.asciidoc
- articles/styling/styling-other-elements.adoc
- articles/styling/styling-components/index.adoc
- articles/styling/styling-components/styling-component-instances.adoc
- articles/tools/designer/using-designer/layout.asciidoc

2023-04-19 09:20 UTC, Mikaelsu commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
> +        class="height-5xl" // hidden-source-line
Agreed! It looks better with `4xl`. Pushing an update...

2023-04-20 10:02 UTC, Mikaelsu commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
>          <vaadin-text-area label="Text area 2"></vaadin-text-area>
Thanks, @rolfsmeds ! I pushed an update, please review

2023-04-21 10:04 UTC, rolfsmeds commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
>          <vaadin-text-area label="Text area 2"></vaadin-text-area>
Looks good!

2023-04-21 10:07 UTC, rolfsmeds approved these changes

2023-04-24 06:52 UTC, merged