docs: add Tree Grid doc text and TS examples
vaadin/docs pull request #233
Opened 2021-03-04 18:30 UTC by DiegoCardoso

2021-03-04 20:47 UTC, jouni commented on articles/ds/components/treegrid/index.asciidoc
> +page-links: \
```suggestion
page-links:
```

2021-03-04 20:47 UTC, jouni commented on articles/ds/components/treegrid/index.asciidoc
> +https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-grid-flow}\[Flow {moduleMavenVersion:com.vaadin:vaadin-grid-flow}], \
```suggestion
  - https://github.com/vaadin/vaadin-flow-components/releases/tag/{moduleMavenVersion:com.vaadin:vaadin-grid-flow}[Flow {moduleMavenVersion:com.vaadin:vaadin-grid-flow}]
```

2021-03-04 20:47 UTC, jouni commented on articles/ds/components/treegrid/index.asciidoc
> +https://github.com/vaadin/vaadin-grid/releases/tag/v{moduleNpmVersion:vaadin-grid}\[Web Component {moduleNpmVersion:vaadin-grid}]
```suggestion
  - https://github.com/vaadin/vaadin-grid/releases/tag/v{moduleNpmVersion:vaadin-grid}[Web Component {moduleNpmVersion:vaadin-grid}]
```

2021-03-08 14:43 UTC, tomivirkki requested changes

2021-03-08 14:43 UTC, tomivirkki commented on articles/ds/components/treegrid/api.asciidoc
> +---
The directory name should be `tree-grid` (align with `split-layout`, `number-field` etc). The dir name directly affects the final URL of the examples.

2021-03-08 14:43 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-column.ts
> +  // }
Commented doce

2021-03-08 14:43 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-column.ts
> +            this.managers && this.managers.forEach(manager => this.grid.expandItem(manager))}
It's inefficient to toggle each item separately, change to:
```suggestion
          @click=${() => (this.expandedItems = this.managers)}
```

Needs local property:
```js
@internalProperty()
private expandedItems: unknown[] = [];
```

Some bindings to Grid:
```js
.itemIdPath=${'id'}
.expandedItems=${this.expandedItems}
@expanded-items-changed=${(e: CustomEvent) => (this.expandedItems = e.detail.value)}
```

2021-03-08 14:43 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-column.ts
> +            this.managers && this.managers.forEach(manager => this.grid.collapseItem(manager))}
Same comment as above
```suggestion
          @click=${() => (this.expandedItems = [])}
```

2021-03-08 14:43 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-column.ts
> +  async dataProvider(params: GridDataProviderParams, callback: GridDataProviderCallback) {
Using a bind in a template is discouraged (by eslint-plugin-lit). You can avoid having to `bind(this)` the data provider function by making this a class property
```suggestion
  private dataProvider = async (
    params: GridDataProviderParams,
    callback: GridDataProviderCallback
  ) => {
```

2021-03-08 15:12 UTC, tomivirkki commented on src/main/resources/data/people.json
> +    "managerId": "7"
`hasChildren` is redundant information and shouldn't exist in the raw data set, right? The data could easily get messed up (if the managerIds are changed without also carefully updating the hasChildren properties). 

Respectively, `managerId` doesn't need to exist in the bean class. The bean only needs to have `hasChildren`, which can be computed by the `dataService`, based on the `managerId`'s in the data set. `hasChildren`  should also be renamed in the bean because this is a manager-subordinate -relationship, not child-parent -relationship. I'd suggest `private boolean manager` which generates a sensible getter `public boolean isManager()`.

2021-03-08 15:32 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-rich-content.ts
> +              .level=${model.level!}
Using non-null assertion operator is discouraged (by typescript-eslint)
```suggestion
              .level=${model.level || 0}
```

2021-03-08 15:33 UTC, tomivirkki commented on frontend/demo/component/treegrid/treegrid-rich-content.ts
> +              .expanded=${model.expanded!}
Using non-null assertion operator is discouraged (by typescript-eslint)
```suggestion
              .expanded=${!!model.expanded}
```

2021-03-08 15:52 UTC, jouni commented on articles/ds/components/treegrid/api.asciidoc
> +---
Right. I thought I already changed the name, but maybe I was dreaming 😆

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-rich-content.ts
> +              .level=${model.level!}
Changed.

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-rich-content.ts
> +              .expanded=${model.expanded!}
Changed.

2021-03-09 13:08 UTC, DiegoCardoso commented on articles/ds/components/treegrid/api.asciidoc
> +---
Changed folders, files, and WC names to the right format.

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-column.ts
> +  // }
Removed.

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-column.ts
> +  async dataProvider(params: GridDataProviderParams, callback: GridDataProviderCallback) {
Refactored to use a class property instead.

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-column.ts
> +            this.managers && this.managers.forEach(manager => this.grid.expandItem(manager))}
Right. It's better this way. Changed.

2021-03-09 13:08 UTC, DiegoCardoso commented on frontend/demo/component/treegrid/treegrid-column.ts
> +            this.managers && this.managers.forEach(manager => this.grid.collapseItem(manager))}
Changed.

2021-03-09 15:03 UTC, tomivirkki approved these changes

2021-03-09 16:58 UTC, merged