feat(hilla): document Tree Grid and Multi-Select Combo Box
vaadin/docs pull request #2386
Opened 2023-04-25 15:41 UTC by cromoteca

Closes #2363

2023-04-26 10:20 UTC, platosha requested changes

2023-04-26 10:20 UTC, platosha commented on articles/react/components/tree-grid/index.adoc
> +const dataProvider = async (
It would be great to wrap using `useCallback` or something, otherwise re-assigning the data provider to the grid on every render causes unexpected side-effects, like this one: https://github.com/vaadin/react-components/issues/74

2023-04-26 10:22 UTC, platosha requested changes

2023-04-26 10:22 UTC, platosha commented on articles/react/components/tree-grid/index.adoc
> +    items={people}
AFAIK, the `dataProvider`  overrides the `items`, so perhaps we should not have them both in one example.

```suggestion
    items={people}
```

2023-05-17 12:44 UTC, cromoteca commented on articles/react/components/tree-grid/index.adoc
> +const dataProvider = async (
Done

2023-05-17 12:44 UTC, cromoteca commented on articles/react/components/tree-grid/index.adoc
> +    items={people}
It should, but it doesn't work if I remove it. Do we have a bug? Maybe the callback is not called for the root?

2023-05-17 13:01 UTC, platosha commented on articles/react/components/tree-grid/index.adoc
> +    items={people}
Typically this is caused by not informing the grid of the total number of items. There are several options to do so:
- Give the `items`, then `items.length` is what the grid uses as the total number.
- Give the `size` number, then the grid uses it. 
- The data provider callback provides the total size in the callback: `callback(requestedSlice, totalSize);`

The data provider here only provides the requested slice but not the total. I guess the grid happened to use the `items.length` number as a partial fallback, and this is why it requires `items` with this setup.

2023-05-17 13:06 UTC, cromoteca commented on articles/react/components/tree-grid/index.adoc
> +    items={people}
You're right, thanks for the insight.

2023-05-17 13:55 UTC, platosha commented on articles/react/components/tree-grid/index.adoc
> +    return callback(filtered, filtered.length);
One more caveat here on my mind. The data provider is supposed to take care of paged data, as well as applying sorting and filtering. Omitting sorting and filtering here is OK, as it these features are not used anyway, but taking care of supplying more than one page of data feels essential to me. Otherwise it might suddenly break when the number of items exceeds the page size (25 by default) on any level.

The expectation is that every data provider call retrieves the data only for the requested page number, but the size of the entire data on the current tree level. 

From [the lazy loading Web Component example](https://vaadin.com/docs/latest/components/grid/#lazy-loading), the relevant step missing here is:
```typescript
  // Pagination
  const count = result.length;
  result = result.slice(page * pageSize, pageSize);
```

The `page` and `pageSize` should be available from the data provider's `params`.

Should look something like this:

```suggestion
    const { page, pageSize } = params;
    const pageOffset = page * pageSize;
    return callback(filtered.slice(pageOffset, pageSize), filtered.length);
```

2023-05-17 15:34 UTC, cromoteca commented on articles/react/components/tree-grid/index.adoc
> +    return callback(filtered, filtered.length);
I understand, but I simplified the example as I don't have the same `getPeople` API here in place. I'll see if I can replicate everything from the main docs.

2023-05-19 10:52 UTC, platosha commented on articles/react/components/tree-grid/index.adoc
> +    console.log(pagedPeople);
Looks like the log line was left by accident.

```suggestion
```

2023-05-19 11:52 UTC, platosha approved these changes

2023-05-19 11:53 UTC, merged