docs: add Form Layout doc text and TS examples
vaadin/docs pull request #239
Opened 2021-03-05 19:28 UTC by DiegoCardoso

2021-03-08 13:33 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +[NOTE]
I couldn't come up with another heading to the note.

2021-03-08 13:33 UTC, DiegoCardoso commented on frontend/demo/component/formlayout/form-layout-custom-layout.ts
> +      </p>
I blocked this PR by #212 so I can reuse the WC created there for this kind of note inside an example.

2021-03-08 15:43 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +[NOTE]
I would remove the admonition. Let the text be a regular paragraph.

2021-03-08 16:55 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +[NOTE]
Removed.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +Form Layout sports two columns by default meaning it displays two input fields per line. On smaller viewports it adjusts to a single column layout.
Done.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +[source,typescript]
I disagree because of the TS code present on the example. I changed the first example to `html`, though.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +The only reason for wrapping labels in Form Items is to put the labels to the side of the input.
It was removed on purpose. See this [comment](https://github.com/vaadin/docs/pull/239#discussion_r589522535).

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +They do however result in vertically longer forms which is why sectioning is important.
Good catch. Done.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +Like the number of columns, the label position is configurable based on the viewport’s width.
Done. Thanks.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +For example, you can position the labels on the side when there’s ample horizontal space available, and on top on narrower screens.
Yes. There's a comment on the document from Rolf to skip it for now.

2021-03-10 16:57 UTC, DiegoCardoso commented on articles/ds/components/form-layout/index.asciidoc
> +Each section should consist of related content and/or fields.
It was decided to be skipped by Rolf.

2021-03-10 16:57 UTC, DiegoCardoso commented on frontend/demo/component/formlayout/form-layout-basic.ts
> +    { minWidth: '20em', columns: 2 }
Weird. Doesn't it show like this for you?
![image](https://user-images.githubusercontent.com/262432/110666594-3a727300-81a8-11eb-9fa5-293df14dff18.png)

If I remove the responsive steps, it shows with one column only.

2021-03-10 16:57 UTC, DiegoCardoso commented on frontend/demo/component/formlayout/form-layout-custom-layout.ts
> +          <vaadin-text-field label="First name"></vaadin-text-field>
I thought about it, but wasn't sure if I had to add it or not.

2021-03-12 09:52 UTC, jouni requested changes

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +A single column layout is generally preferable to a multi column one.
```suggestion
A single column layout is preferable to a multi column one.
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +For example, if you have a Form Layout with three columns and a component’s colspan is set to three, it will take up the entire width of the Form Layout.
```suggestion
For example, if you have a Form Layout with three columns and a component’s colspan is set to three, it takes up the entire width of the Form Layout.
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +Form Item allows you to set a label for any type of component that you want to use in a Form Layout. It supports both Vaadin components and native HTML components.
```suggestion
Form Item allows you to set a label for any type of component that you want to use in a Form Layout.
It supports both Vaadin components and native HTML components.
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +include::../../../../frontend/demo/component/formlayout/form-layout-native-input.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/component/formlayout/form-layout-native-input.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +include::../../../../frontend/demo/component/formlayout/form-layout-side.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::.{root}/frontend/demo/component/formlayout/form-layout-side.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +// include::../../../../src/main/java/com/vaadin/demo/component/formlayout/FormLayoutSide.java[render,tags=snippet,indent=0,group=Java]
```suggestion
// include::{root}/src/main/java/com/vaadin/demo/component/formlayout/FormLayoutSide.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +include::../../../../frontend/demo/component/formlayout/form-layout-colspan.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/component/formlayout/form-layout-colspan.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +// include::../../../../src/main/java/com/vaadin/demo/component/formlayout/FormLayoutColspan.java[render,tags=snippet,indent=0,group=Java]
```suggestion
// include::{root}/src/main/java/com/vaadin/demo/component/formlayout/FormLayoutColspan.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +// include::../../../../src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomLayout.java[render,tags=snippet,indent=0,group=Java]
```suggestion
// include::{root}/src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomLayout.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +include::../../../../frontend/demo/component/formlayout/form-layout-custom-layout.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/component/formlayout/form-layout-custom-layout.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +include::../../../../frontend/demo/component/formlayout/form-layout-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/component/formlayout/form-layout-basic.ts[render,tags=snippet,indent=0,group=TypeScript]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
>  // include::../../../../src/main/java/com/vaadin/demo/component/formlayout/FormLayoutBasic.java[render,tags=snippet,indent=0,group=Java]
```suggestion
// include::{root}/src/main/java/com/vaadin/demo/component/formlayout/FormLayoutBasic.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +====
```suggestion
Form Item suffers from two accessibility issues: required indicators cannot be displayed and screen readers are unable to announce a field’s label.
```
```suggestion
====
Form Item suffers from two accessibility issues: required indicators cannot be displayed and screen readers are unable to announce a field’s label.
====
```

2021-03-12 09:52 UTC, jouni commented on articles/ds/components/form-layout/index.asciidoc
> +// include::../../../../src/main/java/com/vaadin/demo/component/formlayout/FormLayoutNativeInput.java[render,tags=snippet,indent=0,group=Java]
```suggestion
// include::{root}/src/main/java/com/vaadin/demo/component/formlayout/FormLayoutNativeInput.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-12 09:53 UTC, jouni approved these changes

2021-03-17 08:59 UTC, jouni commented on frontend/demo/component/formlayout/form-layout-custom-layout.ts
> +      </p>
Yeah, we agreed that we can use admonitions. I somehow thought that @anezthes had explicitly wanted these to be within the example itself (not sure why, though).

So yes, let’s use asciidoc admonitions.

2021-03-17 13:53 UTC, yuriy-fix commented on frontend/demo/component/formlayout/form-layout-basic.ts
> +    { minWidth: '20em', columns: 2 }
For some reason it was showing me one column initially.
Seems to be working properly.

2021-03-17 14:02 UTC, yuriy-fix reviewed
Should be rebased and use `Frontend` root path (example: https://github.com/vaadin/docs/pull/212/commits/e5fa91499414d35ee6bb6d467fc1fc63c878a8b8)

2021-03-17 15:07 UTC, DiegoCardoso commented
> Should be rebased and use Frontend root path (example: e5fa914)

Done.

2021-03-18 11:14 UTC, yuriy-fix commented
PR is editing too many not related files, should be fixed. (probably because of incorrect merging of `latest` branch)
Would be good to fix Vale errors as well.
The demo page itself looks good :lgtm:

2021-03-18 20:49 UTC, DiegoCardoso commented
Now it should be fixed.

2021-03-22 08:42 UTC, yuriy-fix commented
Vale errors related to `colspan` are still there 😅

2021-03-22 17:02 UTC, DiegoCardoso commented
> Vale errors related to `colspan` are still there 😅

Fixed.

2021-03-23 10:15 UTC, yuriy-fix approved these changes

2021-03-23 12:37 UTC, merged