Observability V2.1 Release
vaadin/docs pull request #2393
Opened 2023-04-26 10:49 UTC by MatthewVaadin

This adds documentation for the Frontend Observability feature and the introduction of a maven dependency. These will be available in V2.1 of Observability Kit.

NOTE: This should not be merged until V2.1 of Observability Kit has been released.

2023-04-26 10:53 UTC, MatthewVaadin commented
This contains part of the previously closed PR #2357 as well as the Frontend Observability documentation removed in #2392 .

2023-05-19 14:40 UTC, jouni commented
I would still like to know if "front-end observability" is the thing we want to talk about, or if it’s "observability for the frontend" instead (or something similar). See the [related Slack discussion](https://vaadin.slack.com/archives/C0442FFN6H4/p1681208134478539), which didn't reach a conclusion (the discussion was more about the "front-end" adjective vs "frontend" noun).

2023-06-07 07:14 UTC, heruan requested changes

2023-06-07 11:21 UTC, heruan approved these changes

2023-06-07 11:21 UTC, merged