docs(Fusion): add Handling Events article to Fusion / Application section
vaadin/docs pull request #240
Opened 2021-03-05 19:56 UTC by platosha

Fixes #215

2021-03-08 10:51 UTC, haijian-vaadin reviewed
There is a minor Vale error that could be fixed.
Personally, would prefer to eliminate the empty View interface to make the examples simpler.
Are you still working on more content or should be marked as ready for review?

2021-03-08 16:15 UTC, platosha commented
> There is a minor Vale error that could be fixed.

Done.

> Personally, would prefer to eliminate the empty View interface to make the examples simpler.

Done.

> Are you still working on more content or should be marked as ready for review?

Marked as ready.

2021-03-08 16:18 UTC, jouni commented
Can it be? An article without any Vale warnings or suggestions?! 🙀 

If that is the case, well done! 🥇 😄

2021-03-08 18:59 UTC, haijian-vaadin approved these changes

2021-03-09 09:47 UTC, haijian-vaadin commented
Could you @jouni help to close merge the PR? The doc looks good, just some unrelated Vale errors from the base branch.

2021-03-09 10:32 UTC, jouni commented
Yeah, sure, I’ll take a look. I just noticed that the preview deployment hasn’t actually been successful. I’ll see what fails.

2021-03-09 10:40 UTC, jouni requested changes
Build error:

```
9:12:06 PM: error Generating JavaScript bundles failed
9:12:06 PM: Can't resolve '../../init' in '/opt/build/repo/frontend/demo/fusion/application/events'
9:12:06 PM: If you're trying to use a package make sure that '../../init' is installed. If you're trying to use a local file make sure that the path is correct.
9:12:06 PM: error Generating JavaScript bundles failed
9:12:06 PM: Can't resolve '../../init' in '/opt/build/repo/frontend/demo/fusion/application/events'
9:12:06 PM: If you're trying to use a package make sure that '../../init' is installed. If you're trying to use a local file make sure that the path is correct.
```

2021-03-09 10:40 UTC, jouni commented on articles/fusion/application/events.asciidoc
> +include::{root}/frontend/demo/fusion/application/events/value-changed-view.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/fusion/application/events/value-changed-view.ts[render,tags=snippet,indent=0]
```

2021-03-11 06:47 UTC, jouni approved these changes

2021-03-11 06:48 UTC, jouni requested changes
Oh, the build is still failing. That needs to be fixed first.

2021-03-11 11:34 UTC, haijian-vaadin commented
The second example only shows me the Label, I don't see the text field
![Screenshot 2021-03-11 at 13 33 12](https://user-images.githubusercontent.com/30408303/110781391-85ef5480-826e-11eb-9684-a988f367f4e0.png)

2021-03-11 12:33 UTC, haijian-vaadin approved these changes
now the demos on the page also work, really nice, good job

2021-03-11 12:34 UTC, haijian-vaadin commented
@jouni, now the build passes, can you help to take another look?

2021-03-11 15:25 UTC, jouni approved these changes

2021-03-11 15:28 UTC, jouni reviewed
I assume we would want to show the example code immediately without the need to click “Show code”.

2021-03-11 15:28 UTC, jouni commented on articles/fusion/application/events.asciidoc
> +[source,typescript]
```suggestion
[source,typescript, role=show-code]
```

2021-03-11 15:28 UTC, jouni commented on articles/fusion/application/events.asciidoc
> +[source,typescript]
```suggestion
[source,typescript, role=show-code]
```

2021-03-12 07:59 UTC, merged