initial draft
vaadin/docs pull request #2436
Opened 2023-05-22 14:35 UTC by taefi

2023-05-25 13:15 UTC, cromoteca requested changes
Huge effort! I made many comments, but most, if not all, of them, are just trivial syntax fixes.

2023-05-25 13:15 UTC, cromoteca commented on articles/lit/start/gradle.adoc
> +Thus, if you don't already have it in your project, create a plain text file called `settings.gradle` next to your [filename]#build.gradle# file, which is normally in the project root folder.
```suggestion
Thus, if you don't already have it in your project, create a plain text file called [filename]`settings.gradle` next to your [filename]`build.gradle` file, which is normally in the project root folder.
```

2023-05-25 13:15 UTC, cromoteca commented on articles/lit/start/gradle.adoc
> +- Your application class that is annotated with `@SpringBootApplication` should extend [classname]`SpringBootServletInitializer` and override the [methodname]`configure()` method:
```suggestion
- Your application class that is annotated with [annotationname]`@SpringBootApplication` should extend [classname]`SpringBootServletInitializer` and override the [methodname]`configure()` method:
```

2023-05-30 18:18 UTC, platosha commented on articles/lit/start/gradle.adoc
> +2. Directly downloading a
I think this should be preferred, it does contain initial frontend at least.

2023-05-30 18:25 UTC, platosha approved these changes
The amount of features covered is really good here. I have just one minor suggestion, otherwise LGTM.

2023-06-06 12:25 UTC, Mikaelsu approved these changes

2023-06-06 12:29 UTC, merged