Add LitElement basics article
vaadin/docs pull request #245
Opened 2021-03-08 15:35 UTC by Lodin

Resolves #223.

2021-03-08 15:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=245) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=245) it.</sub>

2021-03-08 19:11 UTC, platosha commented
Nice, I like the balance on level of detail here, and the technical accuracy is good.

Let me address the high-level structure though. The current sub-heading list in the “Contents” submenu kind of gives an impression that the first thing in the workflow is styling.

How about a high-level structure like this, with a bit more focus on of building application views in mind:

- Templates (how to declare the view class and define the view content — the first example covers that, so perhaps we could put the Templates subheader right before it)
- Properties (how to display data in my view, what is the template binding syntax)
- Lifecycle (when to populate data in properties, when it is safe to access content, etc...)
- Styling
- Shadow and Light DOM
- Using in Routes

2021-03-08 19:51 UTC, jouni commented
> Shadow and Light DOM

Regarding this, it would probably be a good idea to cross link to [Style Scopes](https://vaadin.com/docs-beta/latest/ds/customization/style-scopes/).

2021-03-09 06:57 UTC, Lodin commented
@platosha, thanks for review!

I have a question.

> Templates (how to declare the view class and define the view content — the first example covers that, so perhaps we could put the Templates subheader right before it)

Does it mean that the example should contain Light DOM creation? Probably, it affects all examples except the Shadow DOM vs Light DOM ones?

2021-03-09 08:59 UTC, platosha commented on articles/fusion/application/lit-element.asciidoc
> +The `render()` method should return a `TemplateResult` instance produced by the `html` tagged function. More about how to write templates in the link:https://lit-element.polymer-project.org/guide/tem
It is unfortunate that the `render()` method is explained that far in the article. It seems to be the key subject of this article, as it tells how to define the content that developers could then change dynamically with bindings, style, listen events on, etc...

I would rather move this section to be first in the article, so that it contains the first code example, and tells how to register a component and define its HTML content.

2021-03-09 09:02 UTC, platosha commented
@Lodin I think the first code example is good, it does not have to contain anything more specific details. I’m more concerned with the wording about it and having the section about the templates and `render()` too far late in the article. Made a [comment](https://github.com/vaadin/docs/pull/245#discussion_r590094206) for that matter.

2021-03-11 09:05 UTC, haijian-vaadin requested changes

2021-03-11 09:05 UTC, haijian-vaadin commented on frontend/demo/fusion/lit-basics/styling.ts
> +import styles from './my-view.css';
The build failed for me locally, looks like it's missing this my-view.css file?

2021-03-11 10:47 UTC, Lodin commented on frontend/demo/fusion/lit-basics/styling.ts
> +import styles from './my-view.css';
Hmm, I successfully run build without adding this file. What the command do you use?

2021-03-11 10:48 UTC, haijian-vaadin commented on frontend/demo/fusion/lit-basics/styling.ts
> +import styles from './my-view.css';
I run `npm start` on the doc-app project.

2021-03-11 11:48 UTC, Lodin commented on frontend/demo/fusion/lit-basics/styling.ts
> +import styles from './my-view.css';
Ok, I found the error. It was because `types.d.ts` is not included in the `tsconfig.json` for some reason. Fixed now.

2021-03-11 12:20 UTC, haijian-vaadin requested changes
Some additional information would be good to add:
1. The `@customElement` is used in all the examples, but not explained. Could maybe have a `Create a hello world web component with LitElement` section to explain the minimal essential part to define a web component
2. User could define (private) fields/functions.  

These might sound too basic, but for new users, especially the Java users, this might be helpful.

2021-03-11 15:36 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +=== Usage Advices
Plural is the same as singular for advice.
```suggestion
=== Usage Advice
```

2021-03-12 07:14 UTC, Lodin commented on articles/fusion/application/lit-element.asciidoc
> +=== Usage Advices
Fixed

2021-03-12 07:14 UTC, Lodin commented on articles/fusion/application/lit-element.asciidoc
> +The `render()` method should return a `TemplateResult` instance produced by the `html` tagged function. More about how to write templates in the link:https://lit-element.polymer-project.org/guide/tem
Fixed

2021-03-12 07:29 UTC, haijian-vaadin commented
Looks like a broken link?
![Screenshot 2021-03-12 at 9 28 32](https://user-images.githubusercontent.com/30408303/110906943-6101ec80-8315-11eb-97ac-7d09d701b651.png)

2021-03-12 07:38 UTC, haijian-vaadin requested changes

2021-03-12 07:38 UTC, haijian-vaadin commented on articles/fusion/application/lit-element.asciidoc
> +
at least one dash?

I think multiple dashes is also fine.

2021-03-12 07:38 UTC, haijian-vaadin commented on articles/fusion/application/lit-element.asciidoc
> +
Could have an example to show a field, a method, private field, private method etc?

2021-03-12 07:43 UTC, Lodin commented on articles/fusion/application/lit-element.asciidoc
> +
Yes, I put the common example at the end of the Data Binding section which also includes a `private _onClick()` method

2021-03-12 07:54 UTC, haijian-vaadin requested changes

2021-03-12 07:54 UTC, haijian-vaadin commented on frontend/demo/fusion/lit-basics/data-binding.ts
> +  // No `this` binding required
What does it mean? Did you mean _Note: `this` binding is required_?

2021-03-12 07:55 UTC, Lodin commented on frontend/demo/fusion/lit-basics/data-binding.ts
> +  // No `this` binding required
No, the opposite. I have added a note in the docs, and made smaller the note in the example (because it duplicates the note in docs). Probably, it is not clear. How can I say it in a more correct way?

2021-03-12 09:05 UTC, jouni requested changes

2021-03-12 09:05 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +Just like `firstUpdate`, it receives an object that contains all properties changed after the previous render.
- Use a definition list
- Proper admonitions with titles
- Cleanup Asciidoc formatting (single * and _)

```suggestion
.List of lifecycle callbacks
`constructor`::
+
*Specificity*: JavaScript class
+
The constructor is invoked when a class is instantiated.
For a component, it happens when `document.createElement('my-view')` is called.
+
In most cases, you don't need a `constructor` because LitElement handles everything important.
However, if you do, try to avoid performing any heavy work: the element might be discarded after invoking the constructor.
+
.The element needs to be connected to run the `render` callback.
[NOTE]
When the element is created, no render happens.

`connectedCallback`::
+
*Specificity*: Web Components
+
This callback is invoked each time the element is connected to the DOM.
+
In most cases, the `connectedCallback` is used for setting up component-level event listeners, etc.
+
.Use <<first-updated,`first-updated`>> callback to execute the code after the first render
[NOTE]
Since `render` is asynchronous it does not over when the `connectedCallback` finishes.
+
.Remember to call the `super.connectedCallback()`
[NOTE]
You must call `super.connectedCallback()` in your `connectedCallback` method.
Otherwise, you may lose the default LitElement lifecycle.

`disconnectedCallback`::
+
*Specificity*: Web Components
+
This callback is invoked each time the element is disconnected from the DOM.
+
The default role of the `disconnectedCallback` is to remove or close everything that is set up during the `connectedCallback`.
+
.No DOM access
[NOTE]
This callback is invoked _after_ the element is disconnected from the DOM.
+
.Remember to call the `super.disconnectedCallback()`
[NOTE]
You must call `super.disconnectedCallback()` in your `disconnectedCallback` method.
Otherwise, you may lose the default LitElement lifecycle.

[[first-updated]]`firstUpdated`::
+
*Specificity*: LitElement
+
This callback is invoked right after the first render is over and before the first `updated` callback.
It receives an object that contains all changed properties.

`updated`::
+
*Specificity*: LitElement
+
This callback is invoked after each render; for the first render, it is invoked right after the `firstUpdated` callback.
Just like `firstUpdate`, it receives an object that contains all properties changed after the previous render.
```

2021-03-12 09:30 UTC, jouni requested changes

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +You may use either a stylesheet imported from the `.css` file or define it in the component directly using the `css` tagged function.
```suggestion
You can use either a style sheet imported from a `.css` file or define an inline style sheet using the `css` tagged function.
```

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +Just use the array instead of a direct assigning.
```suggestion
The `styles` property also accepts an array of style sheets.
```

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +=== Usage Advice
We use this title/heading in the Design System docs, and it feels appropriate here as well.

```suggestion
=== Best Practices
```

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +It is recommended to use Shadow DOM only for design components (checkboxes, text fields, combo-boxes, etc.) and Light DOM for any other components like views or their parts.
```suggestion
Shadow DOM is recommended only for "leaf" components (checkboxes, text fields, combo boxes, etc.) and Light DOM for other components like views or their parts.
```

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +It would allow avoiding possible performance issues that might happen due to multiple nesting of shadow trees.
```suggestion
Deeply nested shadow trees can impact performance negatively.
```

2021-03-12 09:30 UTC, jouni commented on articles/fusion/application/lit-element.asciidoc
> +About how to use components in the Vaadin Router you can read in the <<{articles}/fusion/routing/router#,Vaadin Router>> documentation.
```suggestion
Read more about how to use components together with Vaadin Router in the <<{articles}/fusion/routing/router#,Vaadin Router>> documentation.
```

2021-03-15 12:29 UTC, Lodin commented on articles/fusion/application/lit-element.asciidoc
> +
Fixed

2021-03-15 12:29 UTC, Lodin commented on articles/fusion/application/lit-element.asciidoc
> +
Fixed

2021-03-15 12:32 UTC, Lodin commented on frontend/demo/fusion/lit-basics/data-binding.ts
> +  // No `this` binding required
Fixed

2021-03-15 13:00 UTC, haijian-vaadin approved these changes

2021-03-15 13:02 UTC, haijian-vaadin commented
The article now looks good to me. Can you @jouni help to take another look to see if it can be merged?

2021-03-16 08:38 UTC, jouni approved these changes

2021-03-16 08:38 UTC, jouni commented
Once the conflicts are fixed, you should be able to merge this yourself 👍

2021-03-16 11:02 UTC, merged