chore: Add vaadin. prefix to recently added config parameters
vaadin/docs pull request #2450
Opened 2023-05-26 10:12 UTC by mshabarov

`ci.build` and `force.production.build` parameters are used in the plugin classes, where vaadin. prefix is not added by Flow automatically. We need to follow the same rules for naming, so that developers can set these two parameters as `-Dvaadin.force.production.build=true` or `Dvaadin.ci.build=true`.

Related-to https://github.com/vaadin/flow/issues/16880

2023-05-29 10:50 UTC, caalador approved these changes

2023-05-29 10:54 UTC, caalador requested changes
Just noted that properties.asciidoc is missing the `skip.dev.bundle` property.
This can not be found in any documentation for some reason.

2023-05-29 10:55 UTC, mshabarov commented
> Just noted that properties.asciidoc is missing the `skip.dev.bundle` property. This can not be found in any documentation for some reason.

Thanks, I'll add it.

2023-05-29 10:55 UTC, Mikaelsu commented on articles/configuration/properties.asciidoc
> +|`vaadin.ci.build`
Probably a dumb question, but should this be `Dvaadin.ci.build`?

2023-05-31 14:28 UTC, mshabarov commented on articles/configuration/properties.asciidoc
> +|`vaadin.ci.build`
"D" is a JVM prefix for system properties, so it doesn't need to be specified for each particular parameter.

2023-05-31 14:30 UTC, mshabarov commented
I made the following modifications comparing to the initial version:

- added `skip.dev.bundle` parameter
- added missing description to 2 parameters where it is logical to place and mention it
- removed `vaadin.` in the properties list, because they all should contain this prefix anyway.

2023-06-01 04:06 UTC, caalador commented on articles/configuration/properties.asciidoc
> +|`force.production.bundle`
```suggestion
|`vaadin.force.production.bundle`
```
This is now complex as other parameters are usable from application.properties, but this is specifically only used in maven/gradle plugin and needs to have the vaadin prefix even if you are not using spring boot.

Feels like this should not be under configuration properties, but under a specific header `plugin properties` in this file.

Same goes for the CI build.

Also these are missing from the `Build Front-End Goal Parameters` in articles/configuration/maven.asciidoc

2023-06-01 06:55 UTC, Mikaelsu commented on articles/configuration/properties.asciidoc
> +|`vaadin.ci.build`
Gotcha, thanks for clarifying!

2023-06-05 10:48 UTC, mshabarov commented on articles/configuration/properties.asciidoc
> +|`force.production.bundle`
Moved them to a new section `Vaadin Plugin Properties` and added also to `Build Front-End Goal Parameters`.

2023-06-05 12:19 UTC, caalador approved these changes

2023-06-05 13:57 UTC, merged