Add TabSheet doc
vaadin/docs pull request #2470
Opened 2023-06-04 05:56 UTC by tarekoraby

2023-06-04 05:59 UTC, tarekoraby commented
Removed "language check" as it is a copy-paste from vaadin.com/docs.

2023-06-05 08:25 UTC, cromoteca requested changes

2023-06-05 08:25 UTC, cromoteca commented on articles/react/components/tabs/index.adoc
> +  <div tab="setails-tab">This is the Details tab content</div>
```suggestion
  <div tab="details-tab">This is the Details tab content</div>
```

2023-06-05 08:52 UTC, cromoteca commented
Looks like a duplicate of https://github.com/vaadin/docs/pull/2434

2023-06-05 09:54 UTC, tarekoraby commented
Close in favor of #2434.

2023-06-05 09:54 UTC, closed without merging