doc: using components in Fusion
vaadin/docs pull request #258
Opened 2021-03-11 20:40 UTC by joheriks

2021-03-12 08:20 UTC, jouni requested changes
Build error:

```
11:13:37 PM: [ERROR] Command `/opt/buildhome/.nvm/versions/node/v12.18.0/bin/npx --yes --quiet pnpm --shamefully-hoist=true install` failed:
11:13:37 PM: Using hooks from: /opt/build/repo/pnpmfile.jsreadPackage hook is declared. Manifests of dependencies might get overriddenLockfile is up-to-date, resolution step is skipped ERROR  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with package.json
11:13:37 PM: [ERROR] >>> Dependency ERROR. Check that all required dependencies are deployed in pnpm repositories.
11:13:38 PM: [INFO] ------------------------------------------------------------------------
11:13:38 PM: [INFO] BUILD FAILURE
11:13:38 PM: [INFO] ------------------------------------------------------------------------
11:13:38 PM: [INFO] Total time:  02:15 min
11:13:38 PM: [INFO] Finished at: 2021-03-11T21:13:38Z
11:13:38 PM: [INFO] ------------------------------------------------------------------------
11:13:38 PM: [ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:20.0.0.alpha2:build-frontend (default-cli) on project docs: Could not execute build-frontend goal: Pnpm install has exited with non zero status. Some dependencies are not installed. Check pnpm command output -> [Help 1]
11:13:38 PM: [ERROR]
11:13:38 PM: [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
11:13:38 PM: [ERROR] Re-run Maven using the -X switch to enable full debug logging.
11:13:38 PM: [ERROR]
11:13:38 PM: [ERROR] For more information about the errors and possible solutions, please read the following articles:
11:13:38 PM: [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +This article describes using Vaadin Components and/or third-party web components in your Fusion views.
```suggestion
This article describes using Vaadin components and/or third-party web components in your Fusion views.
```
Not a proper product name.

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +When bootstrapping a Fusion project from an https://start.vaadin.com/[official starter], all Vaadin Components frontend packages are automatically installed.
```suggestion
When bootstrapping a Fusion project from an https://start.vaadin.com/?preset=fusion[official starter], all Vaadin components frontend packages are automatically installed.
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +In the above example, the combo box and checkbox components with ids `greeting` and `custom` respectively are mapped to typed class variables of the same names via the `@query` decorator.
```suggestion
In the above example, the <<{articles}/ds/components/combo-box#,Combo Box>> and <<{articles}/ds/components/checkbox#,Checkbox>> components with IDs `greeting` and `custom` respectively are mapped to typed class variables of the same names via the `@query` decorator.
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +The checkbox event listener toggles the `allowCustomValue` attribute of the combo box, which defines whether the user can enter custom values into the box or is constrained to the alternatives in the
```suggestion
The Checkbox event listener toggles the `allowCustomValue` attribute of the Combo Box, which defines whether the user can enter custom values into the field or is constrained to the alternatives in the items overlay.
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +The following HTML attributes work as expected with all Vaadin Components:
```suggestion
The following HTML attributes work as expected with all Vaadin components:
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +
Give more space to the description.
```suggestion
[cols=1,2, opts=header]
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +There you can also find information on how to customize the look and feel of the components.
```suggestion
The <<{articles}/ds/customization#, Customization>> section describes how to customize the look and feel of the components.
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +To do this, you first need to install the component npm package from `npmjs.com` using the `pnpm` package manager.
```suggestion
To do this, you first need to install the component npm package from the https://npmjs.com[npm package registry] using the `pnpm` package manager.
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +The following example shows the hex triplet of the selected color in a `vaadin-text-field`:
Prefer using proper component names instead of class/element names.

```suggestion
The following example shows the hex triplet of the selected color in a <<{articles}/ds/components/text-field#,Text Field>>:
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +You can then use the `<vaadin-text-field>` element in your view's `render` method:
```suggestion
You can then use the <<{articles}/ds/components/text-field#,Text Field>> component (the `<vaadin-text-field>` element) in your view's `render` method:
```

2021-03-12 08:20 UTC, jouni commented on articles/fusion/application/components.asciidoc
> +The class name of a component `vaadin-_component_` follows the pattern `__Component__Element`
```suggestion
The class name of a `<vaadin-_component-name_>` element follows the pattern `__ComponentName__Element`
```

2021-03-15 08:29 UTC, haijian-vaadin requested changes
The 2 generated pnpm files could be left from the commit?

2021-03-15 08:59 UTC, haijian-vaadin requested changes

2021-03-15 08:59 UTC, haijian-vaadin commented on articles/fusion/application/components.asciidoc
> +pass:[<!-- vale Vaadin.ProductName = NO -->]
The Using Vaadin Components heading is showing incorrectly in the preview, it literally shows
`== Using Vaadin Components`

2021-03-15 08:59 UTC, haijian-vaadin commented on articles/fusion/application/components.asciidoc
> +
The table looks misformatted in the preview.
![Screenshot 2021-03-15 at 10 38 43](https://user-images.githubusercontent.com/30408303/111125768-a541f680-857a-11eb-96e1-7158c8bee07d.png)

2021-03-15 08:59 UTC, haijian-vaadin commented on articles/fusion/application/components.asciidoc
> +----
Is it possible to have the code example to show the live demo as well? as what @platosha  did in his [PR](https://github.com/vaadin/docs/pull/240). It has the benefit of being able to see the code and demo at the same time. https://vaadin.com/docs-beta/latest/fusion/application/events/.
Does @jouni have some tips on how to make that kind of include?

2021-03-15 10:21 UTC, joheriks commented on articles/fusion/application/components.asciidoc
> +----
Made both examples live using `render` tag in the `include`. Would there be some way to make the code appear before the live demo (as I feel in this context the code is more important than the running example itself).

2021-03-15 10:22 UTC, joheriks commented on articles/fusion/application/components.asciidoc
> +pass:[<!-- vale Vaadin.ProductName = NO -->]
Done. Changed the title instead of working around the linter.

2021-03-15 10:22 UTC, joheriks commented on articles/fusion/application/components.asciidoc
> +
Done.

2021-03-15 10:24 UTC, joheriks commented
> The 2 generated pnpm files could be left from the commit?

They should be deleted as the project uses npm, not pnpm.

2021-03-15 12:53 UTC, haijian-vaadin commented
There are build errors
```
ERROR in /opt/build/repo/frontend/demo/fusion/components/greeting-view.ts
1:23:36 PM: [tsl] ERROR in /opt/build/repo/frontend/demo/fusion/components/greeting-view.ts(34,7)
1:23:36 PM:       TS2322: Type 'unknown' is not assignable to type 'string'.
1:23:36 PM: ERROR in /opt/build/repo/frontend/demo/fusion/components/greeting-view.ts
1:23:36 PM: [tsl] ERROR in /opt/build/repo/frontend/demo/fusion/components/greeting-view.ts(34,29)
1:23:36 PM:       TS2532: Object is possibly 'undefined'.
```

2021-03-15 13:00 UTC, joheriks commented
> There are build errors
> 

Ups, fixed.

2021-03-15 13:23 UTC, haijian-vaadin commented on articles/fusion/application/components.asciidoc
> +----
could change [source, typescript] to [source, typescript, role=show-code], so it will always show the code without having to click the "show code".

2021-03-15 13:46 UTC, joheriks commented on articles/fusion/application/components.asciidoc
> +----
Thanks for the tip, fixed.

2021-03-15 14:37 UTC, haijian-vaadin commented on articles/fusion/application/components.asciidoc
> +----
just one more small thing, I learned from Jouni that the `group=TypeScript` is not needed unless we have the same example with both TypeScript and Java examples.

2021-03-15 14:56 UTC, joheriks commented on articles/fusion/application/components.asciidoc
> +----
Done.

2021-03-15 20:54 UTC, haijian-vaadin approved these changes

2021-03-15 20:55 UTC, haijian-vaadin commented
Looks good to me now, could @jouni help to merge it?

2021-03-16 08:28 UTC, jouni approved these changes

2021-03-16 08:29 UTC, merged