Add Java variants to Messages examples.
vaadin/docs pull request #261
Opened 2021-03-12 11:02 UTC by Peppe

- Remove Message example
- Add Java variations of each example
- Better example data

2021-03-12 11:04 UTC, Peppe commented
I'm having problems developing this locally, so I thought of doing a draft PR and verifying that it works similarly on Netlify as locally.

2021-03-17 13:00 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +        // end::snippet[]
Missing `add(chatLayout)` is a part of the problem not displaying the example

2021-03-18 06:33 UTC, Peppe commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +        // end::snippet[]
Done.

2021-04-01 08:06 UTC, pekam requested changes

2021-04-01 08:06 UTC, pekam commented on articles/ds/components/messages/index.asciidoc
> +Here is an example of an initialized `items` array with two messages, in Java and TypeScript:
I think that we shouldn't have source code as part of the text like this. We have the code examples for that purpose, and with those you only see them in your preferred language.

Looking at the other component demos, they mostly speak on a more general level about the component in the text part, and then let the code examples show the API.

2021-04-01 08:06 UTC, pekam commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +            newMessage.setUserAbbreviation("MS");
I don't think we need to use `setUserAbbreviation` just for the sake of covering all the APIs. It's just extra line of code which doesn't have any effect.

2021-04-01 08:06 UTC, pekam commented on articles/ds/components/messages/index.asciidoc
>  Messages is a collection of components to display messages and to build chats, comment sections and activity logs.
A bit outside the scope of this PR, but I would avoid saying that you can build activity logs until you actually can.
```suggestion
Messages is a collection of components to display messages and to build chats and comment sections.
```

2021-04-01 08:34 UTC, Peppe commented on articles/ds/components/messages/index.asciidoc
> +Here is an example of an initialized `items` array with two messages, in Java and TypeScript:
Is your suggestion to delete the the code snippets? 

I added it after in DX tests, people was looking on how to define `items`, and didn't know what all was possible to define in these objects (especially in JS). But yeah, the practice is not there in other components.

2021-04-01 08:35 UTC, Peppe commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +            newMessage.setUserAbbreviation("MS");
Okay. We should take it away from the TS version as well to have them match.

2021-04-01 08:38 UTC, Peppe commented on frontend/demo/component/messages/MessageListItem.ts
>  export default interface MessageListItem {
No we don't need it anymore, and it isn't used. Deleted.

2021-04-01 08:39 UTC, pekam commented on articles/ds/components/messages/index.asciidoc
> +Here is an example of an initialized `items` array with two messages, in Java and TypeScript:
Maybe the TS code example should be changed from:
```html
<vaadin-message-list .items=${this.items}></vaadin-message-list>
```
to:
```html
<vaadin-message-list .items=${[
  {
    text: "foo"
  }..,
]}></vaadin-message-list>
```

2021-04-01 08:40 UTC, Peppe commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +            newMessage.setUserAbbreviation("MS");
Done.

2021-04-01 15:55 UTC, jouni commented
Build failure:

```
11:55:34 AM: [ERROR] ERROR in /opt/build/repo/frontend/demo/component/messages/message-basic.ts
11:55:34 AM: [ERROR] [tsl] ERROR in /opt/build/repo/frontend/demo/component/messages/message-basic.ts(8,29)
11:55:34 AM: [ERROR]       TS2307: Cannot find module './MessageListItem' or its corresponding type declarations.
11:55:34 AM: [ERROR]
```

2021-04-06 05:22 UTC, Peppe commented on articles/ds/components/messages/index.asciidoc
> +Here is an example of an initialized `items` array with two messages, in Java and TypeScript:
I can see the point and I changed it. 

However, I'm not that much of a fan myself as inline defining messages is not what I would do in any real-world application and thus I don't consider this best practice. But I'm fine with it.

Done.

2021-04-06 11:14 UTC, pekam commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +            newMessage.setUserAbbreviation("MS");
```suggestion
```

2021-04-06 11:14 UTC, pekam commented on src/main/java/com/vaadin/demo/component/messages/MessagesBasic.java
> +        list.setItems(Arrays.asList(message1, message2));
```suggestion
        list.setItems(message1, message2);
```

2021-04-06 11:16 UTC, pekam commented on articles/ds/components/messages/index.asciidoc
> +Here is an example of an initialized `items` array with two messages, in Java and TypeScript:
Yeah, following best practices is of course a good idea, but it is just more important to easily see from the example what the property looks like.

And in any case, we're hard-coding the array in the code, so it's kinda impossible to really follow best practices. :sweat_smile:

2021-04-06 14:02 UTC, pekam approved these changes
These message demos are still standing out from other components as they go into API details in the descriptions, but changing those more is outside the scope of this PR.

2021-04-06 14:02 UTC, merged