Avatar: Java examples
vaadin/docs pull request #262
Opened 2021-03-12 13:27 UTC by anezthes

**Notes**:
- The `company-logo.png` example uses `StreamResource`. Couldn't get image to show using just its URL. Now it feels needlessly complicated though.
- `MenuBar` (Java) example is not working. Screenshot of the console output:
![menu-bar-errors](https://user-images.githubusercontent.com/7125728/110946372-72fc8300-8347-11eb-8f1b-e463cc0bec36.png)

2021-03-12 13:51 UTC, anezthes commented
@DiegoCardoso recommended using:
```
import '@vaadin/flow-frontend/menubarConnector'; // hidden-full-source-line
```
in `avatar-menu-bar.ts` which reduced the number of errors to:

![image](https://user-images.githubusercontent.com/7125728/110949017-c7edc880-834a-11eb-983f-2ae7a5c1343a.png)

2021-03-16 16:52 UTC, DiegoCardoso requested changes

2021-03-16 16:52 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +import '@vaadin/flow-frontend/menubarConnector'; // hidden-full-source-line
Adding `contextMenuConnector` seems fix the issue with the example:

```suggestion
import '@vaadin/flow-frontend/menubarConnector'; // hidden-full-source-line
import '@vaadin/flow-frontend/contextMenuConnector'; // hidden-full-source-line
```

2021-03-16 16:52 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/avatar/AvatarGroupMaxItems.java
> +  private List<Person> people = DataService.getPeople(6);
I noticed that this is different from the TS example and it makes sense to have more items than the maximum visible items value. I would suggest to align and use this same quantity on the TS example.

2021-03-16 17:56 UTC, DiegoCardoso commented
The "Working in progress" admonition can be removed.

2021-03-22 08:26 UTC, anezthes commented on src/main/java/com/vaadin/demo/component/avatar/AvatarGroupMaxItems.java
> +  private List<Person> people = DataService.getPeople(6);
Oversight. Fixed!

2021-03-22 08:26 UTC, anezthes commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +import '@vaadin/flow-frontend/menubarConnector'; // hidden-full-source-line
Fixed!

2021-03-22 14:10 UTC, DiegoCardoso requested changes
The branch needs to be rebased properly to fix the merging issues.

2021-03-22 14:10 UTC, DiegoCardoso commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +    const [person] = await getPeople(1);
This is using the old `getPeople` API. You can see on the change the new one.

There seems to be that after merging, the changes got messed up and the older versions of the files got picked in favor of the new changes. You can also see below the leading comas being removed. And, in some other TS files, the imports are being reverted to the old format when we didn't have the `Frontend` alias.

2021-03-23 13:20 UTC, jouni commented on frontend/demo/component/avatar/avatar-menu-bar.ts
> +    const [person] = await getPeople(1);
I’ll see what I can do – I’ll try rebasing and fixing the conflicts.

2021-03-23 14:57 UTC, jouni approved these changes

2021-03-23 15:15 UTC, merged