Tabs: Java examples
vaadin/docs pull request #263
Opened 2021-03-12 13:32 UTC by anezthes

Note:
- Badges (Java) example isn't working. Tried the usual approach:

```
@CssImport(value = "tabs-badges.css", include = "lumo-badge")
@JsModule("@vaadin/vaadin-lumo-styles/badge")
```

If this needs to be hacked, it doesn't offer much value to devs. Alternatively, we move it to Cookbook.

2021-05-05 12:30 UTC, sosa-vaadin requested changes
Fix an import that's breaking the netlify deployment at line 7 in `tabs-content.ts`. Everything else looks good.
The badges example works on my machine, I don't know if you fixed it and didn't update the comment on this PR but I don't see it failing.

2021-05-05 12:30 UTC, sosa-vaadin commented on frontend/demo/component/tabs/tabs-content.ts
> +import { applyTheme } from 'generated/theme';
```suggestion
import { applyTheme } from 'Frontend/generated/theme';
```

2021-05-19 08:42 UTC, anezthes commented on frontend/demo/component/tabs/tabs-content.ts
> +import { applyTheme } from 'generated/theme';
Fixed, thanks! Great if the badges work now.

2021-05-19 08:46 UTC, anezthes commented on frontend/demo/component/tabs/tabs-content.ts
> +import { applyTheme } from 'generated/theme';
Badges look good in the Java examples, but not in the TS ones:

<img width="396" alt="Screenshot 2021-05-19 at 11 45 24" src="https://user-images.githubusercontent.com/7125728/118783505-ce8f4380-b897-11eb-9d90-a3ae63c2436d.png">

2021-05-19 10:30 UTC, sosa-vaadin approved these changes

2021-06-03 13:24 UTC, merged