ListBox: Java examples
vaadin/docs pull request #265
Opened 2021-03-12 18:46 UTC by anezthes

## Notes

### Selection

`ListBoxCustomItemPresentation.java` and `ListBoxMultiSelection.java` use the following approach for selecting items:
```
List<Person> items = DataService.getPeople(20);
listBox.setItems(items);
listBox.select(items.get(0), items.get(3));
```
That last line seems a bit random. Is there a better way?

### Disabled items

I might have over-engineered `ListBoxDisabledItems.java`. Using constants (see `ListBoxSingleSelection.java`) didn't seem right considering the example.

2021-05-03 13:36 UTC, sosa-vaadin requested changes
- There's a repeated method in `Person.java` file.
- Some imports are missing `Frontend/` in the TS samples.
Other than these, looks good to me.

2021-05-03 13:41 UTC, jouni commented on articles/ds/components/list-box/index.asciidoc
> +section-nav: incomplete
```suggestion
```

2021-05-03 13:41 UTC, jouni commented on articles/ds/components/list-box/index.asciidoc
> +In the meantime, you can view the previous examples for the Java/Flow component.
Remove this admonition block, as both TS and Java examples are now available.

2021-05-03 13:41 UTC, jouni commented on frontend/demo/component/listbox/list-box-custom-item-presentation.ts
> +      <vaadin-list-box multiple .selectedValues=${[0, 2]}>
```suggestion
      <vaadin-list-box multiple .selectedValues="${[0, 2]}">
```

2021-05-03 13:41 UTC, jouni commented on frontend/demo/component/listbox/list-box-custom-item-presentation.ts
> +                  .name=${`${person.firstName} ${person.lastName}`}
```suggestion
                  .img="${person.pictureUrl}"
                  .name="${`${person.firstName} ${person.lastName}`}"
```

2021-05-03 13:41 UTC, jouni commented on frontend/demo/component/listbox/list-box-multi-selection.ts
> +      <vaadin-list-box multiple .selectedValues=${[0, 3]} style="height: 200px">
```suggestion
      <vaadin-list-box multiple .selectedValues="${[0, 3]}" style="height: 200px">
```

2021-05-04 06:55 UTC, anezthes commented on src/main/java/com/vaadin/demo/domain/Person.java
> +
Thanks, fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-multi-selection.ts
> +      <vaadin-list-box multiple .selectedValues=${[0, 3]} style="height: 200px">
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-custom-item-presentation.ts
> +                  .name=${`${person.firstName} ${person.lastName}`}
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-custom-item-presentation.ts
> +      <vaadin-list-box multiple .selectedValues=${[0, 2]}>
Fixed!

2021-05-04 07:27 UTC, anezthes commented on articles/ds/components/list-box/index.asciidoc
> +In the meantime, you can view the previous examples for the Java/Flow component.
Removed!

2021-05-04 07:27 UTC, anezthes commented on articles/ds/components/list-box/index.asciidoc
> +section-nav: incomplete
Removed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-single-selection.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-separators.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-multi-selection.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-disabled-items.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-custom-item-presentation.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:27 UTC, anezthes commented on frontend/demo/component/listbox/list-box-basic.ts
> +import { applyTheme } from 'generated/theme';
Fixed!

2021-05-04 07:51 UTC, sosa-vaadin approved these changes
Fix conflicts with `latest` branch and we're good to go.

2021-05-04 09:40 UTC, merged