feat: add react form guides
vaadin/docs pull request #2723
Opened 2023-08-22 14:02 UTC by taefi

2023-08-25 08:51 UTC, cromoteca commented on articles/lit/guides/forms/binder.adoc
> +view:
While nothing changes from the reader point of view, I think it is more readable to have a single `if` for the whole sentence.

2023-08-25 09:42 UTC, Artur- requested changes

2023-08-25 09:42 UTC, Artur- commented on articles/lit/guides/forms/binder.adoc
> +- The [methodname]`field()` directive to bind the field components in React form views
It does not seem necessary to repeat "React" in many places when you are looking at React docs

2023-08-25 09:43 UTC, Artur- commented on articles/lit/guides/forms/binder.adoc
> +      <section className="flex p-m gap-m items-baseline flex-wrap">
This is also repeated in a lot of other examples. It just makes it more complicated when the reader starts thinking "What does a <section> even do? Why are these class names here? How does flexbox work again?"

2023-08-25 09:45 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +When creating forms in TypeScript with {teckstack} and the `Binder` API, all data model constraints are automatically applied to your form fields.
techstack?

2023-08-25 09:45 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +  const field = originalField as <M extends AbstractModel<any>>(model: M) => FieldDirectiveResult;
This `as` should not be here?

2023-08-25 09:46 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +import {Button} from "@hilla/react-components/Button.js";
formatting seems off here

2023-08-25 09:46 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +  const field = originalField as <M extends AbstractModel<any>>(model: M) => FieldDirectiveResult;
no no no

2023-08-25 09:46 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +  useEffect(() => {
Why is useEffect needed to add a validator?

2023-08-25 09:48 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +  useEffect(() => {
I see, React is React... I wonder if there is a better way that Hilla could handle this

2023-08-25 09:48 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +  const field = originalField as <M extends AbstractModel<any>>(model: M) => FieldDirectiveResult;
no

2023-08-25 10:14 UTC, taefi commented on articles/lit/guides/forms/binder.adoc
> +      <section className="flex p-m gap-m items-baseline flex-wrap">
Well, I'd say this might be a good and a bad thing at the same time. 
Some, like myself, prefer to see a nice looking outcome rather than a barebone looking bunch of fields on the page when I try and Copy/Paste stuff from the docs, however your argument is also valid as this part is not about the styling. 
Anyway, I'm completely open to suggestions since, TBH, while converting articles to include React documentations, my focus wasn't really on sanitizing the contents and examples, otherwise it would take much more time. 
Another, approach is to postpone the sanitizing, as this is not a blocker for the preliminary DX tests...

2023-08-25 10:16 UTC, Artur- requested changes

2023-08-25 10:16 UTC, Artur- commented on articles/react/guides/forms/binder-validation.adoc
> +description: Validating user input using Bean Validation together with Lit and the Binder API.
Should it say "Lit" here?

2023-08-25 10:16 UTC, Artur- commented on articles/react/guides/forms/binder.adoc
> +description: Binding data to UI components in TypeScript forms.
Is "TypeScript" needed here?

2023-08-25 10:16 UTC, Artur- commented on articles/react/guides/forms/binding-arrays.adoc
> +description: Working with arrays when building TypeScript form views using form binding.
"When building TypeScript form" and "using form binding" is what the whole section is about? Sounds like it would need something more descriptive about the actual contents

2023-08-25 10:18 UTC, Artur- commented on articles/lit/guides/forms/binder.adoc
> +      <section className="flex p-m gap-m items-baseline flex-wrap">
I would aim to keep the focus on form binding and remove anything that distracts from that

2023-08-25 10:20 UTC, taefi commented on articles/lit/guides/forms/binder-validation.adoc
> +When creating forms in TypeScript with {teckstack} and the `Binder` API, all data model constraints are automatically applied to your form fields.
I must admit another variable name such as "framework" that holds the literals of either "Lit" or "React" sound better than techstack :) 
It is variable name after all, it doesn't show up in the output anyway.

2023-08-25 10:20 UTC, Artur- commented on articles/lit/guides/forms/binder-validation.adoc
> +When creating forms in TypeScript with {teckstack} and the `Binder` API, all data model constraints are automatically applied to your form fields.
Ah, the point was just to change teck to tech

2023-08-25 10:20 UTC, taefi commented on articles/lit/guides/forms/binder-validation.adoc
> +  const field = originalField as <M extends AbstractModel<any>>(model: M) => FieldDirectiveResult;
Good catch! 
The whole line is redundant after latest changes to the API. I'll remove it.

2023-08-25 10:26 UTC, taefi commented on articles/react/guides/forms/binder-validation.adoc
> +description: Validating user input using Bean Validation together with Lit and the Binder API.
Not anymore IMO!

2023-08-25 10:30 UTC, taefi commented on articles/react/guides/forms/binding-arrays.adoc
> +description: Working with arrays when building TypeScript form views using form binding.
I guess these are from the era that fusion was shoulder to shoulder to flow and it was emphasizing on the fact that there these stuff should be placed in the Typescript forms, and please don't try them at home in your flow views ;)

2023-08-25 10:36 UTC, taefi commented on articles/lit/guides/forms/binder-validation.adoc
> +When creating forms in TypeScript with {teckstack} and the `Binder` API, all data model constraints are automatically applied to your form fields.
Didn't realize that the spelling is off :)

2023-08-25 10:41 UTC, taefi commented on articles/react/guides/forms/binding-arrays.adoc
> +description: Working with arrays when building TypeScript form views using form binding.
Would either of the following be any better?

- Working with arrays and form binding APIs
- Manipulating arrays with form binding APIs

2023-08-25 11:11 UTC, taefi commented on articles/react/guides/forms/binding-arrays.adoc
> +description: Working with arrays when building TypeScript form views using form binding.
Changed it "Working with arrays using form binding API". Feel free to suggest any better titles 👍

2023-08-25 11:11 UTC, taefi commented on articles/lit/guides/forms/binder.adoc
> +      <section className="flex p-m gap-m items-baseline flex-wrap">
Done.

2023-08-25 11:15 UTC, Artur- commented on articles/lit/guides/forms/vaadin-components.adoc
> +const selectItems = [{label: "True", value: "true"}, {label: "False", value: "false"}];
Is this correct that the value should be strings and not actually true / false ?

2023-08-25 11:17 UTC, Artur- commented on articles/lit/guides/forms/vaadin-components.adoc
> +const { model, field } = userBinder(MyEntityModel);
```suggestion
const { model, field } = useBinder(MyEntityModel);
```

2023-08-25 11:17 UTC, Artur- commented on articles/lit/guides/forms/vaadin-components.adoc
> +const { model, field } = userBinder(MyEntityModel);
```suggestion
const { model, field } = useBinder(MyEntityModel);
```

2023-08-25 11:18 UTC, Artur- commented on articles/lit/guides/forms/vaadin-components.adoc
> +const { model, field } = userBinder(MyEntityModel);
```suggestion
const { model, field } = useBinder(MyEntityModel);
```

2023-08-25 11:27 UTC, taefi commented on articles/lit/guides/forms/vaadin-components.adoc
> +const selectItems = [{label: "True", value: "true"}, {label: "False", value: "false"}];
When I try it with the actual boolean values, it compiles but fails at runtime, but there is high chance that I'm making a mistake in how to feed the items to a Select.

2023-08-25 11:29 UTC, taefi commented on articles/lit/guides/forms/vaadin-components.adoc
> +const selectItems = [{label: "True", value: "true"}, {label: "False", value: "false"}];
When I try it with the actual boolean values it fails to compile with:

> TS2322: Type '{ label: string; value: boolean; }[]' is not assignable to type 'SelectItem[]'.
>   Type '{ label: string; value: boolean; }' is not assignable to type 'SelectItem'.
>     Types of property 'value' are incompatible.
>       Type 'boolean' is not assignable to type 'string'.

2023-08-25 11:33 UTC, Artur- commented on articles/lit/guides/forms/vaadin-components.adoc
> +const selectItems = [{label: "True", value: "true"}, {label: "False", value: "false"}];
Ok, sounds like `SelectItem` is made for attributes then and not properties..

2023-08-25 11:35 UTC, taefi commented on articles/lit/guides/forms/vaadin-components.adoc
> +const { model, field } = userBinder(MyEntityModel);
Well spotted! 💯

2023-08-25 11:35 UTC, Artur- approved these changes

2023-08-25 11:46 UTC, Artur- approved these changes

2023-08-25 11:59 UTC, merged

2023-08-25 18:13 UTC, jouni commented
Was there a rush to merge these updates? In general, please avoid merging PRa with the `Language not checked` label.

2023-08-25 18:15 UTC, jouni commented
And make sure you've read https://vaadin.com/docs/latest/contributing/docs (you can skip the Word List page, though, that's only for reference).

2023-08-26 16:08 UTC, tarekoraby commented
Yes, there was a rush so that we can have the DX tests early next week, so that we can release beta on Wednesday.

2023-08-26 16:12 UTC, tarekoraby commented
And for the record, I'm the one who explicitly asked for this PR to be merged without a language check.

2023-08-28 07:25 UTC, jouni commented
If we had the preview builds working, would that have sufficed for the DX test?

2023-08-28 07:49 UTC, tarekoraby commented
I think so, yes. WDYT, @platosha / @Legioth?

(We should have previews working anyway. Especially for me as a Windows user, it's a pain in the back to review PRs when I need to run things on my local machine).

2023-08-28 09:12 UTC, Legioth commented
A preview build is good enough for DX tests since we don't need to test how they find the Hilla or Flow documentation itself but only how they find stuff within the documentation