docs: Form Filler article included
vaadin/docs pull request #2724
Opened 2023-08-22 22:39 UTC by mgarciavaadin

Documentation for the Form Filler addon created into the Tools section.

2023-08-22 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=2724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=2724) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=2724) it.</sub>

2023-08-22 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=2724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=2724) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=2724) it.</sub>

2023-08-23 06:28 UTC, tarekoraby requested changes

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> += [since:com.vaadin:vaadin@V24.1]#AI Form Filler#
Is it really since 24.1? Or can it be used with any 24.x version?
```suggestion
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +The Form Filler Addon is an experimental feature that provides an easy way for Flow users to create forms filled automatically from natural language input sources using GPT technologies.
```suggestion
The AI Form Filler addon is an experimental feature that provides an easy way for Flow users to create forms that are filled automatically from natural language input sources using GPT technologies.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +[NOTE]
```suggestion
[WARNING]
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +Form Filler Addon has the following features in this experimental preview:
```suggestion
AI Form Filler addon has the following features in this experimental preview:
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +- MultiSelectComboBox
```suggestion
- Email Field
- Password Field
- Number Field
- Integer Field
- BigDecimal Field
- Date Picker
- Time Picker
- Date Time Picker
- Text Area
- Checkbox
- Checkbox Group
- Radio Button Group
- ComboBox
- MultiSelect ComboBox
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +Built in prompt engineering do the job of generating a request containing the information related to the target components that works out of the box for most of the cases. Once you have defined your
```suggestion
Built-in prompt engineering performs the job of generating a request containing the information related to the target components that works out of the box for most cases. Once you have defined your form, only a couple of lines are required to use the Form Filler. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +API to add more context instructions for the AI module i.e.: target language, vocabulary explanation, source context, etc... Use these instructions to give extra information to the AI module about th
```suggestion
API to add more context instructions for the AI module, i.e., target language, vocabulary explanation, source context, etc... Use these instructions to give extra information to the AI module about the context of the input source in general.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +API to add more component instructions for the AI module (i.e.: field format, field explanation, field actions, etc...). Use these instructions to give extra information to the AI module about a spec
```suggestion
API to add more component instructions for the AI module (i.e., field format, field explanation, field actions, etc...). Use these instructions to give extra information to the AI module about a specific field when the built-in request/response of the form filler is not accurate enough.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +Form Filler is implemented as an addon. It can be used in any Flow 24.1 application and to use it you need to add the maven dependency to your project.
Avoid explicitly stating the version in text.
```suggestion
Form Filler is implemented as an addon. To use it you need to add the Maven dependency to your project. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +In the demo project you can see an example of all the supported components with some raw text sources included. Then in the addon project you have some experiments with more advanced use cases like d
```suggestion
If you prefer to first test the addon with an example see https://github.com/vaadin/form-filler-demo[demo project]. Also, some demos and advanced example use cases are included in the https://github.com/vaadin/form-filler-addon[addon project]. 

In the demo project, you can see an example of all the supported components with some raw text sources included. Then in the addon project, you have some experiments with more advanced use cases like document inputs through OCR. New content and examples (e.g., using other LLM models than ChatGPT or improving OCR results) could be included in the addon project in the future. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +OpenAI ChatGPT is the LLM model behind this feature but any model can be adapted using the LLMService interface.
```suggestion
OpenAI ChatGPT is the large language model (LLM) model used by default with this feature. But any LLMmodel can be adapted using the `LLMService` interface. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +To enable the Form Filler there is only one requirement. You have to set meaningful IDs to the fields(Components) that you want to be filled by the Form Filler. The target can be just one component o
```suggestion
To enable the Form Filler, there is only one requirement. You have to set meaningful IDs to the fields(Components) that you want to be filled by the Form Filler. The target can be just one component or a group of components (container). Usually, you would use the Form Filler with a Form Layout, but any kind of Layout can be used. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +_componentInstructions:_ extra instructions for the AI module related to a specific component/field (i.e.: field format, field explanation, etc...). Use these instructions to give extra information t
```suggestion
==== API Review

===== Constructors

Form Filler has 6 constructors, all of them based on the same one, but each one provides default values when a parameter of the base constructor is not provided. 

These parameters are:

_target:_ the target component or group of components (layouts) to fill. This is the only mandatory parameter without a default value. 

_componentInstructions:_ extra instructions for the AI module related to a specific component/field (i.e., field format, field explanation, etc...). Use these instructions to give extra information to the AI module about a specific field when the response of the form filler is not accurate enough. By default, this structure is initialized empty.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +_componentInstructions:_ extra instructions for the AI module related to a specific component/field (i.e.: field format, field explanation, etc...). Use these instructions to give extra information t
> By default, this structure is initialized empty

What is "structure" referring to here?

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +_llmService:_ the AI module service to use. By default, this service would use OpenAI ChatGPT with chat/completion end point and the "gpt-3.5-turbo-16k-0613" model. There is another built in service
```suggestion
_llmService:_ the AI module service to use. By default, this service would use OpenAI ChatGPT with chat/completion endpoint and the "gpt-3.5-turbo-16k-0613" model. There is another built-in service using also ChatGPT but with the /completion endpoint and the "text-davinci-003" model. About ChatGPT models, the newest models could not be better for the specific task of the Form Filler. The testing phase has not identified the best model, so don't hesitate to test both services and give feedback about your results. More models and other LLM providers could be added to the addon in the future. If you want to create your own provider service, you need to extend the interface LLMService and add it as a parameter to the Form Filler. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +- Target fields are descendants of the same container (layout) passed to the FormFiller. The best way is to integrate all the fields in a FormLayout but any kind of Layout can be used. Also all the d
```suggestion
=== Best Practices & Limitations

To make a set of components ready to be filled by the FormFiller the only requirements are:

- Target fields are descendants of the same container (layout) passed to the FormFiller. The best way is to integrate all the fields in a Form Layout, but any kind of Layout can be used. Also, all the descendants of the passed container are going to be included so several containers can be used inside the main container. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +- Every field has an ID (Component::setId). The ID should be meaningful about the data contained by the field. Grid columns are a special case as they are not input fields, they are inspected directl
```suggestion
- Every field has an ID (Component::setId). The ID should be meaningful about the data contained by the field. Grid columns are a special case as they are not input fields. They are inspected directly from the Bean of the Grid so use meaningful names for the Bean fields.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +Anyways remember that later you can add extra information about any component to help the AI module if the Id is not enough to understand what data you are looking for. Of course you can use a senten
```suggestion
Anyways remember that later you can add extra information about any component to help the AI module if the Id is not enough to understand what data you are looking for. Of course, you can use a sentence as an Id, but for cleaner code, it is recommended to use Ids in combination with extra instructions, but it is up to the developer to choose. For most cases, a 2/3 word Id is enough for the AI module to understand the target. i.e.:
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +Some limitations exist for some fields specially the ones containing dates the FormFiller has its own standard formatting requirement so be careful manipulating them.
```suggestion
Some limitations exist for some fields especially the ones containing dates the FormFiller has its own standard formatting requirement so be careful manipulating them.
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +- MultiSelectComboBox
```suggestion
- Text Field
- Email Field
- Password Field
- Number Field
- Integer Field
- BigDecimal Field
- Date Picker
- Time Picker
- DateTime Picker
- Text Area
- Checkbox
- Checkbox Group
- Radio Button Group
- ComboBox
- MultiSelect ComboBox
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +You can visualize all these structures like this (example from the addon demo):
```suggestion
The _FormFiller::fill_ method returns a _FormFillerResult_ that contains the request sent and the response received by the AI module. The request is a prompt in natural language containing all the instructions, including the target JSON object and the target types. The response has to be a valid JSON object with components' Ids as keys and values. 
Through the FormFiller object, you can access the internal structures used for mapping. 

You can visualize all these structures like this (example from the addon demo):
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +The Form Filler provides two built-in LLM implementations using ChatGPT services. Both models are quite good understanding and processing natural language. In any case it is advised to try yourself b
```suggestion
The Form Filler provides two built-in LLM implementations using ChatGPT services. Both models are quite good at understanding and processing natural language. In any case, it is advised to try both implementations to find out which one fits better with your requirements. Even if ChatGPTChatCompletionService, using gpt-3.5-turbo-16k-0613 model, is more advanced, the LLM world is not something 100% predictable. You never know what model could work better. 
```

2023-08-23 06:28 UTC, tarekoraby commented on articles/tools/formfiller/index.asciidoc
> +You can implement your own AI model adapter for ChatGPT or any other LLM provider. It is advised to use one of the existing implementations as template if you want to create a new adaptor. Internal p
```suggestion
==== Implementing your own AI Model Adapter

You can implement your own AI model adapter for ChatGPT or any other LLM provider. It is advised to use one of the existing implementations as a template if you want to create a new adaptor. Internal parameters such as the model name, temperature, or max tokens are up to the developer to be chosen and parametrized. The methods that are mandatory to be implemented are the ones described by the LLMService interface. 
```

2023-08-23 08:23 UTC, mgarciavaadin commented on articles/tools/formfiller/index.asciidoc
> += [since:com.vaadin:vaadin@V24.1]#AI Form Filler#
Not tested but it should work. We are going to test it but so far I accept your review and we can change it later if there is any problem.

2023-08-23 11:04 UTC, mgarciavaadin commented on articles/tools/formfiller/index.asciidoc
> +_componentInstructions:_ extra instructions for the AI module related to a specific component/field (i.e.: field format, field explanation, etc...). Use these instructions to give extra information t
It means the data structure so the field of the FormFiller class. I can rewrite it

2023-08-23 11:07 UTC, mgarciavaadin commented on articles/tools/formfiller/index.asciidoc
> +_componentInstructions:_ extra instructions for the AI module related to a specific component/field (i.e.: field format, field explanation, etc...). Use these instructions to give extra information t
Actually I'm removing it as it is not providing any value.

2023-08-23 12:13 UTC, tarekoraby approved these changes

2023-08-23 12:13 UTC, merged