Fusion CRM tutorial
vaadin/docs pull request #273
Opened 2021-03-17 00:34 UTC by marcushellberg

Here's the Fusion CRM tutorial. It has been reviewed by Tatu and Olli, and gone through Ruth for edits. 

I would like a second pair of eyes on: 
* The actual technical implementation/asciidoc
* Titles. Chapter and tutorial. 

Also, I need help figuring out how to add SEO metadata.

2021-03-17 06:21 UTC, jouni commented
> Also, I need help figuring out how to add SEO metadata.

What exactly do you need? I don’t think we currently have any means of defining those explicitly. Each page uses the first page paragraph as the description and one of the images in the page as the preview image.

2021-03-17 07:04 UTC, jouni commented
I’ll try to resolve the conflict, and fix the broken cross references that prevent the build from passing.

2021-03-17 07:12 UTC, web-padawan requested changes

2021-03-17 07:12 UTC, web-padawan commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +== An introduction to LitElement
This part is now covered by "LitElement basics" article, see #245. Do we need to duplicate it also here?

Or is the purpose of this tutorial to cover everything without linking to other docs articles?

2021-03-17 07:12 UTC, web-padawan commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +The Vaadin Lumo theme comes with a https://github.com/vaadin/vaadin-lumo-styles/pull/103[proposed^] set of CSS utility classes to simplify layouting and styling. Instead of having to write your own C
Do we recommend using a feature that is not officially part of Vaadin (yet) and skip DX tests and PiT for it?

2021-03-17 07:34 UTC, jouni commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +== An introduction to LitElement
Marcus asked about this in Slack. The purpose of a tutorial usually is to be standalone, and not require the reader to bounce back and forth between articles. But it’s just a guideline.

Alternatively, we could try to include the relevant pieces from the LitElement article in here (using `include::[]`)

2021-03-17 07:34 UTC, jouni commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +The Vaadin Lumo theme comes with a https://github.com/vaadin/vaadin-lumo-styles/pull/103[proposed^] set of CSS utility classes to simplify layouting and styling. Instead of having to write your own C
We have a meeting about this today, and have been talking about what to do with them for a while already.

2021-03-17 07:38 UTC, web-padawan commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +The Vaadin Lumo theme comes with a https://github.com/vaadin/vaadin-lumo-styles/pull/103[proposed^] set of CSS utility classes to simplify layouting and styling. Instead of having to write your own C
Good to know, thanks.

2021-03-17 08:04 UTC, web-padawan commented on articles/fusion/tutorials/full-stack/creating-views.adoc
> +== An introduction to LitElement
Thanks. It would be good to include the relevant pieces indeed.

2021-03-17 08:06 UTC, web-padawan reviewed
Resolved my comments to unlock merging. 

But let's try to reuse "LitElement basics" article, if possible.

2021-03-17 08:16 UTC, jouni commented
Some observations:

- Vale errors and warnings:
  - All errors should be fixed, for example:
    - All headings should be converted to Title Case (watch out for four letter words like "from" and "with", those are also capitalized)
   - Warnings would be great to address if possible, but not required.
     - All filenames should be written as `[filename]#file.java#`, or at least as `` `file.java` ``
     - Admonitions (notes, warnings, etc.) should have a title, so it’s easier for the reader to decide whether or not it is important for them. And before adding an admonition, consider if it should rather be part of the normal document flow.
- Any links to our components should point to the DS docs, not vaadin.com/componens
- Double check all lists that they format correctly. You need an empty line before and after the list items. Here’s [an example](https://6051b2e5206c1c000787dcbc--vaadin-docs-preview.netlify.app/fusion/tutorials/full-stack/endpoints/#an-introduction-to-spring-boot)
- If you want to make certain images smaller (for example [the one at the end of this article](https://6051b2e5206c1c000787dcbc--vaadin-docs-preview.netlify.app/fusion/tutorials/full-stack/forms-and-validation/#maximizing-the-form-on-narrow-viewports)), use `image::image.png[width=250]` (a suitable pixel width).

2021-03-17 14:58 UTC, jouni commented
We can also agree to merge this as is, and continue fixing the Vale errors/warnings from there on.

2021-03-17 17:26 UTC, marcushellberg commented
> > Also, I need help figuring out how to add SEO metadata.
> 
> What exactly do you need? I don’t think we currently have any means of defining those explicitly. Each page uses the first page paragraph as the description and one of the images in the page as the preview image.

A way of explicitly defining the meta description would be enough for now. It's not a blocker for going live, but it will affect SEO negatively if the search results in Google don't have a clear summary.

2021-03-17 18:05 UTC, jouni commented
> A way of explicitly defining the meta description would be enough for now.

We’ve been planning on adding a way to define the description for an article, as we have other uses for that as well. Haven’t had time to work on it yet, though.

> I was planning on doing it, but I not sure how to do it. 

You need to add special comments, aka tags, around the content that you want to reuse, and then use those tags with with `include::[]` directive. Here are the relevant docs: https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/

2021-03-18 02:42 UTC, marcushellberg commented
I think that most relevant stuff is passing now. 

I couldn't get the LitElement chapter include to work, so I just linked it. 

I'm still not sure what the tutorial name should be. Full-stack tutorial is pretty meh.

2021-03-18 07:05 UTC, jouni commented on articles/fusion/tutorials/_reactive-intro.adoc
> +.Avoid element references in reactive views
```suggestion
.Avoid element references in reactive views
[TIP]
```
The Vale check expects the title to be before the block itself.

2021-03-18 07:07 UTC, jouni commented on articles/fusion/tutorials/full-stack/creating-components.adoc
> +pass:[<!-- vale Vale.Spelling = NO -->]
Why do we need to disable spell checking here? If it’s nagging something about the file name, wrap that in `[filename]#...#` or `` `...` `` to allow Vale to ignore the contents.

2021-03-18 15:09 UTC, marcushellberg commented on articles/fusion/tutorials/full-stack/creating-components.adoc
> +pass:[<!-- vale Vale.Spelling = NO -->]
It was nagging about the lowercase css in the filename. I'll update the filename captions to add backticks.

2021-03-18 17:46 UTC, merged