Add LoginOverlay custom fields and footer examples
vaadin/docs pull request #2764
Opened 2023-09-04 12:31 UTC by web-padawan

## Description

Depends on https://github.com/vaadin/flow-components/pull/5390

Added TS and Java examples for `vaadin-login-overlay` custom content.

2023-09-18 13:35 UTC, rolfsmeds requested changes
LGTM otherwise :)

2023-09-18 13:35 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +description: How to use the Login component to authenticate users.
@russelljtdyer I'm not a fan of this style of description. Component pages are _not_ "how to" pages, they're broad descriptions of the features and usage of a certain components, so this type of descriptions seems misleading. I would prefer that we stick to the descriptions already provided in the tag::description[] block below.

2023-09-18 13:35 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +Login is a Vaadin component that contains a log-in form. You can use it to authenticate the user with a username and password.
@russelljtdyer do we need to specify _Vaadin_ here? These are _all_ Vaadin components, after all. We want to keep these descriptions brief since they are used in the thumbnail index at https://vaadin.com/docs/latest/components. I don't think anybody expect these components to be, say, Apple components.

2023-09-18 13:35 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +Overlay provides a custom form area for adding fields in addition to username and password. This area is placed above the "Submit" button. Use `name` attribute to ensure custom field `value` is submi
```suggestion
The overlay provides a custom form area for adding fields in addition to username and password. This area is placed above the "Submit" button. Use `name` attribute to ensure custom field `value` is submitted with the form.
```

2023-09-18 13:35 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +Footer can be used for placing additional custom content, such as text, buttons, etc. Adding components after the overlay is opened is not supported.
```suggestion
The footer area can be used for placing additional custom content, such as text, buttons, etc. Adding components after the overlay is opened is not supported.
```

2023-09-18 13:37 UTC, web-padawan commented on articles/components/login/index.asciidoc
> +description: How to use the Login component to authenticate users.
This change is unrelated to the PR which is about new features. Maybe we should revert it?

2023-09-19 06:45 UTC, web-padawan commented on articles/components/login/index.asciidoc
> += Login Component
None of other components have `Component` in the title. I'd suggest to revert this change as well.

2023-09-19 08:54 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +description: How to use the Login component to authenticate users.
Thanks for the overview, that helps us understand what's going on. But that doesn't really seem to address the fact that the new description indicates a "How to" page about a specific function while the contents of the page are much broader than that. In fact, this page hardly answers that question _at all_. The Flow documentation has a page about how to actually perform the authentication in Flow: https://vaadin.com/docs/latest/tutorial/login-and-authentication

2023-09-19 08:58 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> +Login is a Vaadin component that contains a log-in form. You can use it to authenticate the user with a username and password.
The same could be said of most of our components: Button, Text Field, etc. Or perhaps you mean that the word "login" on its own doesn't indicate that we're talking about a login _UI component_, and I could agree with that. But then "Vaadin" is not the keyword at all, but "UI", so we could change it to say _"Login is a UI component"_ rather than _"Login is a Vaadin component"_.

2023-09-19 09:06 UTC, rolfsmeds commented on articles/components/login/index.asciidoc
> += Login Component
Seems like the same could be said of many others as well, such as Select, CRUD, Cookie Consent, Details, Message Input, Notification, and Upload. Would you suffix those with "Component" as well then, as well as the links to the pages in the navigation column, and on the component thumbnail index page?

2023-09-19 10:40 UTC, web-padawan commented on articles/components/login/index.asciidoc
> += Login Component
What Rold said. Also, as a developer looking for an example of using a component, I think `Component` would be rather redundant - especially in the navigation column and thumbnail.

2023-09-21 06:26 UTC, web-padawan commented on articles/components/login/index.asciidoc
> += Login Component
Reverted this change for now so we can proceed. Let's consider it in a separate PR.

2023-09-21 06:26 UTC, web-padawan commented on articles/components/login/index.asciidoc
> +Login is a Vaadin component that contains a log-in form. You can use it to authenticate the user with a username and password.
Reverted this change for now so we can proceed. Let's consider it in a separate PR.

2023-09-21 11:51 UTC, jouni commented on articles/components/login/index.asciidoc
> +description: How to use the Login component to authenticate users.
I suppose I didn't mention this clear to @russelljtdyer some days ago, but I did go and revert/replace the "How to" version of the descriptions to the ones we have inside the `tag::description[]` tags (on the component pages).

Let’s keep that consistent here as well, and use the same text for both the `description` frontmatter attribute, and the `tag::description[]` tag.

2023-09-21 11:54 UTC, web-padawan commented on articles/components/login/index.asciidoc
> +description: How to use the Login component to authenticate users.
Thanks, I already restored the original description in [96d3310](https://github.com/vaadin/docs/pull/2764/commits/96d3310d5913d5cbae19397ddd58ad242f70a474).

2023-09-21 18:44 UTC, rolfsmeds approved these changes

2023-09-22 07:09 UTC, merged