docs: update Icons documentation and add examples
vaadin/docs pull request #2804
Opened 2023-09-15 12:36 UTC by DiegoCardoso

Update the Icons documentation page to move the current list to a new tab and use the main page to describe the new features added as part of the 6WP.

2023-09-19 09:43 UTC, rolfsmeds requested changes

2023-09-19 14:48 UTC, DiegoCardoso reviewed
Addressed comments on the main doc page. Gonna address the changes in the default icons page now.

2023-09-19 14:48 UTC, DiegoCardoso commented on articles/components/icons/index.asciidoc
> +.Example using FontAwesome
Done.

2023-09-19 14:48 UTC, DiegoCardoso commented on articles/components/icons/index.asciidoc
> +The Default Icons tab contains a listing of the full Lumo Icons collection.
Done.

2023-09-19 14:48 UTC, DiegoCardoso commented on articles/components/icons/index.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/component/icons/FontAwesomeIcons.java[group=Java]
Added an usage example:
![image](https://github.com/vaadin/docs/assets/262432/3f6e4051-44cb-4aad-b762-4b5fe2449633)

2023-09-19 15:51 UTC, tomivirkki approved these changes

2023-09-20 06:58 UTC, DiegoCardoso commented on articles/components/icons/index.asciidoc
>  [discussion-id]`47B97C93-9646-4D2A-882F-C4F709D3D099`
BTW, this has the same id as the `defaul-icons` tab. Should there be another discussion id for both? Which tab should keep the currend it?

2023-09-20 10:42 UTC, tomivirkki approved these changes

2023-09-21 12:44 UTC, jouni commented on articles/components/icons/index.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/component/icons/FontAwesomeIcons.java[group=Java]
Unnecessary example group (Java).

2023-09-21 18:45 UTC, rolfsmeds approved these changes

2023-09-22 06:54 UTC, DiegoCardoso commented on articles/components/icons/index.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/component/icons/FontAwesomeIcons.java[group=Java]
Removed.

2023-09-22 07:34 UTC, merged