Docs for Custom Theme feature support in Designer
vaadin/docs pull request #281
Opened 2021-03-18 16:18 UTC by tanbt

Related to https://github.com/vaadin/designer-internal/issues/1817

2021-03-19 19:58 UTC, jouni requested changes

2021-03-19 19:58 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> +Vaadin Designer supports theming the same way as Flow (see <<{articles}/theming/creating-a-custom-theme, Custom Theme>> for more information).
Outdated cross reference/link. This has been moved under design system / customization.

2021-03-23 08:52 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> + * Modifies `package.json` file to add utility libraries. These changes should be commited to your version control system.
```suggestion
 * Modifies `package.json` file to add utility libraries. These changes should be committed to your version control system.
```

2021-03-23 08:52 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> +When switching the theme under @Theme, all Designer visual editors need to be re-opened to apply the new theme. Also in Preview mode, the browser isn't auto reloaded when styles are changed, you will
```suggestion
When switching the theme under @Theme, all Designer visual editors need to be re-opened to apply the new theme. Also in Preview mode, the browser isn't auto reloaded when styles are changed, you need to refresh the browser manually.
```

2021-03-23 08:52 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> + * Static resources (images, fonts, ...) of the currently using theme are resolved.
```suggestion
 * Static resources (images, fonts, ...) of the theme are resolved.
```

2021-04-01 13:00 UTC, tanbt commented on articles/tools/designer/using-designer/theming.asciidoc
> +Vaadin Designer supports theming the same way as Flow (see <<{articles}/theming/creating-a-custom-theme, Custom Theme>> for more information).
Fixed.

2021-04-01 16:03 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> +Vaadin Designer supports theming the same way as Flow (see <<{articles}/ds/customization/custom-theme, Custom Theme>> for more information).
Cross references need be appended with `#`, otherwise they are interpreted as in-page references.
```suggestion
Vaadin Designer supports theming the same way as Flow (see <<{articles}/ds/customization/custom-theme#, Custom Theme>> for more information).
```

2021-04-01 16:08 UTC, jouni commented on articles/tools/designer/using-designer/theming.asciidoc
> +When switching the theme under @Theme, all Designer visual editors need to be re-opened to apply the new theme. Also in Preview mode, the browser isn't auto reloaded when styles are changed, you need
```suggestion
When updating the `@Theme` annotation value, all Designer visual editors need to be re-opened to apply the new theme. Also in Preview mode, you need to refresh the browser manually.
```

2021-04-01 16:08 UTC, jouni approved these changes

2021-05-04 12:04 UTC, merged