docs: add AutoGrid article
vaadin/docs pull request #2836
Opened 2023-09-27 12:48 UTC by platosha

2023-09-28 12:57 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +layout: tabbed-page
No need for a tabbed page since we only have one tab.
```suggestion
```

2023-09-28 12:57 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +title: Auto Grid
Show on top of components list.
```suggestion
title: Auto Grid
order: 10
```

2023-09-28 12:57 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +In the example below, the data in Auto Grid is filered using the contains matcher for the `name` property.
```suggestion
In the example below, the data in Auto Grid is filtered using the contains matcher for the `name` property.
```

2023-09-28 12:57 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +----
``` suggestion
## Basic Usage

Auto Grid requires a Java service that implements the `dev.hilla.CrudService<T, ID>` interface. In this example, the `ProductService` class implements the interface based on a Spring Data JPA repository.

[.example]
--
[source,java]
.ProductService.java
----
include::{root}/src/main/java/com/vaadin/demo/fusion/crud/ProductService.java[tags=snippet,indent=0]
----
[source,java]
.Product.java
----
include::{root}/src/main/java/com/vaadin/demo/fusion/crud/Product.java[tags=snippet,indent=0]
----
[source,java]
.ProductRepository.java
----
include::{root}/src/main/java/com/vaadin/demo/fusion/crud/ProductRepository.java[tags=snippet,indent=0]
----
--

Hilla automatically generates TypeScript objects for each `@BrowserCallable` service implementing the `CrudService<T, ID>` interface. These TypeScript objects have callable methods that execute the corresponding Java service methods, enabling CRUD operations on the data.

For the `ProductService` example, you can import the generated TypeScript object in your React view, and use it as a value for the `<AutoGrid service={}/>` property to display the data in a lazy-loaded sortable grid with columns for all the properties of the `Product` entity.

[source,typescript]
----
include::{root}/frontend/demo/component/auto-grid/react/auto-grid-basic.tsx[tags=snippet,indent=0,group=React]
----

The Auto Grid component will render a grid with columns for all the properties of the `Product` entity, loading the data lazily from the backend by calling the `CrudService<T, ID>.list(Pageable pageable, @Nullable Filter filter)` method.

This is what the rendered grid looks like:

[source,typescript]
----
include::{root}/frontend/demo/component/auto-grid/react/auto-grid-basic.tsx[render,tags=snippet,indent=0,group=React]
----
```

2023-09-28 12:57 UTC, tarekoraby commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
> +export default reactExample(Example); // hidden-source-line
```suggestion
import { reactExample } from 'Frontend/demo/react-example'; // hidden-source-line
import React from 'react'; // hidden-source-line
// tag::snippet[]
import { AutoGrid } from '@hilla/react-grid';
// tag::apply-backend[]
import { ProductService } from 'Frontend/generated/endpoints';
import ProductModel from 'Frontend/generated/com/vaadin/demo/fusion/crud/ProductModel';

function Example() {
  return <AutoGrid service={ProductService} model={ProductModel} />;
}
// end::apply-backend[]
// end::snippet[]

export default reactExample(Example); // hidden-source-line
```

2023-09-28 12:57 UTC, tarekoraby commented on src/main/java/com/vaadin/demo/fusion/crud/Product.java
> +}
```suggestion
//tag::snippet[]
@Entity
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String category;
    private double price;
    private LocalDate dateAdded;

    // getters and setters omitted for brevity
    //end::snippet[]

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public LocalDate getDateAdded() {
        return dateAdded;
    }

    public void setDateAdded(LocalDate dateAdded) {
        this.dateAdded = dateAdded;
    }
//tag::snippet[]
}
//end::snippet[]
```

2023-09-28 12:57 UTC, tarekoraby commented on src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
> +@Service
```suggestion

//tag::snippet[]
@BrowserCallable
```

2023-09-28 13:33 UTC, sissbruecker commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +function Example() {
Could also add an example with enabled `headerFilters`. Would make sense to put this before the external filtering example IMO.

2023-09-28 13:33 UTC, sissbruecker commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
We should check how the component examples sync script works. Would the article and examples be removed the next time it runs?

2023-09-28 14:23 UTC, tarekoraby commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +function Example() {
@tomivirkki, do you know the answer?

2023-09-28 14:23 UTC, tarekoraby commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
@tomivirkki, do you know the answer?

2023-09-28 14:41 UTC, tomivirkki commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
Running [this command](https://github.com/vaadin/docs/blob/latest/scripts/pick/cherry-pick-config-hilla-react-components.js#L2) in the `latest` branch will create the cherry-pick commit.

2023-09-29 06:07 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +Auto Grid requires a Java service that implements the `dev.hilla.CrudService<T, ID>` interface. In this example, the `ProductService` class implements the interface based on a Spring Data JPA reposit
```suggestion
Auto Grid requires a Java service that implements the `CrudService<T>` interface. In this example, the `ProductService` class extends `CrudRepositoryService<T, ID>`, which in turn implements the `CrudService<T>` .
```

Now the sentence is accurate. But the whole example is very complicated and confusing now.

2023-09-29 06:26 UTC, tomivirkki commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
I'd assume the new example path needs to be added to [this](https://github.com/vaadin/docs/blob/f976a27681b7f5bf718a5d17b32c264978f3fe28/scripts/pick/cherry-pick-config-hilla-react-components.js#L69) list

2023-09-29 09:48 UTC, platosha commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +function Example() {
There is no pre-release with this feature yet. :-(

2023-10-03 13:17 UTC, taefi requested changes

2023-10-03 13:17 UTC, taefi commented on src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
> +}
```suggestion
public class ProductService extends CrudRepositoryService<Product, Long, ProductRepository> {
    
}
```

2023-10-03 13:17 UTC, taefi commented on src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
> +}
Or
```suggestion
import dev.hilla.crud.ListRepositoryService;

//tag::snippet[]
@BrowserCallable
@AnonymousAllowed
public class ProductService extends ListRepositoryService<Product, Long, ProductRepository> {

}
```

2023-10-03 13:17 UTC, taefi commented on src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
> +}
You can ignore this and use the next suggestion instead.

2023-10-04 11:49 UTC, platosha commented on frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
See https://github.com/vaadin/docs/pull/2863

2023-10-04 12:46 UTC, sissbruecker approved these changes
Small code style issue, otherwise looks good.

2023-10-04 12:46 UTC, sissbruecker commented on frontend/demo/component/auto-grid/react/auto-grid-selection.tsx
> +  from "Frontend/generated/com/vaadin/demo/fusion/crud/Product";
```suggestion
import Product
  from "Frontend/generated/com/vaadin/demo/fusion/crud/Product";
```

Unused import. Could also run prettier over the newly added examples once.

2023-10-05 06:11 UTC, taefi commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +    };
How about a compound filter example such as:
```jsx
const firstNameFilter: any = {
    t: 'propertyString',
    propertyId: 'firstName',
    matcher: 'CONTAINS',
    filterValue: filterValue,
};
const lastNameFilter: any = {
    t: 'propertyString',
    propertyId: 'lastName',
    matcher: 'CONTAINS',
    filterValue: filterValue,
};
return {t: 'or', children: [firstNameFilter, lastNameFilter]};
```

2023-10-05 06:14 UTC, taefi commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +    };
In fact, I don't know whether there's an example elsewhere to help the developers figuring out how to use `and` and `or` to create more complex filters.

2023-10-05 06:15 UTC, taefi commented on frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
> +        noHeaderFilters={true}
```suggestion
        noHeaderFilters
```

2023-10-05 06:15 UTC, taefi commented on frontend/demo/component/auto-grid/react/auto-grid-no-header-filters.tsx
> +      noHeaderFilters={true}
```suggestion
      noHeaderFilters
```

2023-10-05 10:50 UTC, taefi approved these changes

2023-10-05 11:17 UTC, merged