Add TS examples for badge component
vaadin/docs pull request #288
Opened 2021-03-19 14:34 UTC by Lodin

2021-03-19 15:09 UTC, jouni commented
I wonder, if the data types should actually be defined in Java (like the previous Person and Card objects, so that the same things can be used for the eventual Java examples?

2021-03-24 18:26 UTC, yuriy-fix requested changes
Badges styles are not actually applied in the demos, so for me in the demos there are just `span`s displayed 😅 
![Screen Shot 2021-03-24 at 20 06 36](https://user-images.githubusercontent.com/29372419/112361895-84954180-8cdc-11eb-98e5-6bb4076f096c.png)
I have tried a small trick to use `badge` styles in the examples. You can take a look onto https://github.com/vaadin/docs/blob/39cafb82efdba084028c88f38aabe65d75ab1fbd/frontend/demo/component/tabs/tabs-badges.ts#L11. Probably we can come up with smth better for this one.

2021-03-24 18:26 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-color.ts
> +      <section class="container">
We could use `vaadin-horizontal-layout` over here instead of `div.container`

2021-03-24 18:26 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-counter.ts
> +  static styles = css`
Nit: could probably be better to use inline styles instead of this one to align with other examples.

2021-03-24 18:26 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-highlight.ts
> +  @internalProperty() private _items: readonly Report[] = [];
Nit: no need to use underscore. In addition let's add new line:
```
@internalProperty()
private items: Person[] = [];
```
Example: https://github.com/vaadin/docs/blob/39cafb82efdba084028c88f38aabe65d75ab1fbd/frontend/demo/component/gridpro/grid-pro-basic.ts#L20

2021-03-24 18:26 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-highlight.ts
> +          <vaadin-grid-column header="Due Date" .renderer=${renderDate}></vaadin-grid-column>
Example of setting renderer inline in other examples: https://github.com/vaadin/docs/blob/39cafb82efdba084028c88f38aabe65d75ab1fbd/frontend/demo/component/gridpro/grid-pro-editors.ts#L45
Probably should be aligned 🤔

2021-03-24 18:26 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/domain/Profession.java
> +package com.vaadin.demo.domain;
I guess there is no need in creating specifically `Profession` class as we can get those from `Person` (`people` data with smth like `${[...new Set(this.people.map(i => i.profession))]}`)

2021-03-25 05:15 UTC, Lodin commented
> Badges styles are not actually applied in the demos, so for me in the demos there are just spans displayed 😅

@yuriy-fix, that's strange... They are displayed correctly in the [netlify build](https://deploy-preview-288--vaadin-docs-preview.netlify.app/ds/components/badge).

2021-03-25 05:25 UTC, Lodin commented on frontend/demo/component/badge/badge-counter.ts
> +  static styles = css`
Is it only about `badge-counter`, or about all the styles? I see that `styles` approach is widely used across examples, e.g. in `app-layout`, in `confirm-dialog`, or in `upload`

2021-03-25 09:06 UTC, Lodin commented on frontend/demo/component/badge/badge-color.ts
> +      <section class="container">
Well, this change is ok for me though the grid looks like a better solution because it requires only one container for both lines.

2021-03-29 10:05 UTC, yuriy-fix requested changes
You are right, seems to be working properly now.

2021-03-29 10:05 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-interactive.ts
> +      <section class="container">
Nit: can we use `ordered-layout`s instead? 😅

2021-03-29 10:05 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-icons.ts
> +      <section class="container">
Same as with the comment for `colors` example.

2021-03-29 10:05 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +      <section class="container">
Nit: do we really need `container` over here?

2021-03-29 10:05 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +const renderBoolean = (
Nit: probably we can also move these renders to align with the example above.

2021-03-29 12:17 UTC, Lodin commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +const renderBoolean = (
For this render, it would require repeating the function three times. That's why I left it moved out.

2021-03-29 14:16 UTC, Lodin commented on frontend/demo/component/badge/badge-interactive.ts
> +      <section class="container">
Just checked: unfortunately, no.
![image](https://user-images.githubusercontent.com/8037479/112849718-fe00ab80-90b1-11eb-9490-1e1e4518645b.png)

It is necessary to have a tag list that wraps when the line is over but `vaadin-horizontal-layout` does not have that functionality. So it would be better to use a container with custom styles here.

2021-03-30 06:52 UTC, Lodin commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +const renderBoolean = (
I solved it by wrapping the `render()` internals with `// tag::snippet[]` and putting the `renderBoolean` function into it.

2021-04-01 08:00 UTC, yuriy-fix reviewed
One nit. 
If possible, let's rebase it on top of `latest`, so Vale check won't be broken.

2021-04-01 08:00 UTC, yuriy-fix commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +import '@vaadin/vaadin-ordered-layout';
Nit: Extra import.

2021-04-01 10:28 UTC, yuriy-fix approved these changes

2021-04-01 10:29 UTC, Haprog commented
Please wait a bit before merging. I have some comments on the way.

2021-04-01 10:35 UTC, Haprog requested changes
Also the theme names in the "Theme name" column (table in Color section) should be all lowercase. Now they're capitalized.

2021-04-01 10:35 UTC, Haprog commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +import '@vaadin/vaadin-lumo-styles/icons';
Unnecessary import of Lumo icons as only Vaadin icons are used here.
```suggestion
import '@vaadin/vaadin-icons/vaadin-icons';
```

2021-04-01 10:35 UTC, Haprog commented on frontend/demo/component/badge/badge-highlight.ts
> +                icon = 'lumo:cog';
I see there doesn't seem to be such an icon in Vaadin icons or Lumo icons than what is in the design doc for this, but I think `vaadin:progressbar` might be more suitable for this. Also this file is missing the import for Lumo icons (and Vaadin icons if you update this to use one).

I don't have a strong opinion about the icon used here, but at least the missing import needs to be added.

2021-04-01 10:35 UTC, Haprog commented on frontend/demo/component/badge/badge-interactive.ts
> +import '@vaadin/vaadin-lumo-styles/icons';
Unnecessary import of Vaadin icons since only Lumo icons is used here.
```suggestion
import '@vaadin/vaadin-lumo-styles/icons';
```

2021-04-01 10:35 UTC, Haprog commented on frontend/demo/component/badge/badge-interactive.ts
> +              <span theme="badge contrast">
Should be using pill style as in design doc.
```suggestion
              <span theme="badge pill contrast">
```

2021-04-01 10:35 UTC, Haprog commented on frontend/demo/component/badge/badge-counter.ts
> +            <span theme="badge error primary pill">1</span>
This badge should have some `aria-label` indicating that there's some error or something needs attention as mentioned in the text that is shown under this example.

> Consider the last item in the example above. For sighted users, it’s clear something requires their attention. To make sure it’s obvious for people using screen readers, set the badge’s `aria-label` attribute.

2021-04-01 10:54 UTC, Haprog commented
Btw at the top of the Badge page there is a note:
> Badge styles need to be imported separately. The code examples show how to import them for Flow (Java) and/or Fusion (TypeScript).

But it's actually not showed in any of the TS examples how to import them. Technically it comes through `applyTheme(this.shadowRoot);` for TS but it also requires adding the `lumoImports` in `theme.json` which is currently not documented anywhere (`lumoImports` property is not documented in custom theme docs either, or at least wasn't last I checked).

But imo this should not block this PR. After this is merged we should create another issue for documenting how to get badge imported as it requires writing some new content.

2021-04-01 10:59 UTC, Lodin commented on frontend/demo/component/badge/badge-highlight.ts
> +                icon = 'lumo:cog';
I would probable leave lumo icon here because vaadin icon requires additional styles to make it smaller while lumo already has the proper size.

2021-04-01 11:04 UTC, Haprog commented
This part in `index.asciidoc`
```
page-links:
  - https://github.com/vaadin/vaadin-lumo-styles/blob/v{moduleNpmVersion:vaadin-lumo-styles}/badge.html[Source]
```
needs to be updated to:
```
page-links:
  - https://github.com/vaadin/web-components/blob/v{moduleNpmVersion:vaadin-lumo-styles}/packages/vaadin-lumo-styles/badge.js[Source]
```

2021-04-01 11:19 UTC, Lodin commented
@Haprog, I guess I can add a `theme.json` file to each example. That would follow the @jouni's recommendation in [Board PR](https://github.com/vaadin/docs/pull/310) that we should have any source used for this example creation displayed.

2021-04-01 12:01 UTC, Haprog commented
> I guess I can add a `theme.json` file to each example. That would follow the @jouni's recommendation in [Board PR](https://github.com/vaadin/docs/pull/310) that we should have any source used for the example creation displayed.

I think it would be a bit confusing without extra explanation since the preview snippet also doesn't show the path to where `theme.json` needs to be and it's not directly used in the example sources. There should be some new section about this imo as it's about theme configuration. But you can ignore it for this PR.

2021-04-01 12:02 UTC, Haprog commented on frontend/demo/component/badge/badge-highlight.ts
> +                icon = 'lumo:cog';
Ok, makes sense. Just add the missing import then.

2021-04-01 12:06 UTC, Lodin commented on frontend/demo/component/badge/badge-counter.ts
> +            <span theme="badge error primary pill">1</span>
I have used a following approach: 
```html
<span aria-label="Settings require attention!" theme="badge error primary pill">
  1
</span>
```
Is it ok?

2021-04-01 12:12 UTC, Haprog commented on frontend/demo/component/badge/badge-counter.ts
> +            <span theme="badge error primary pill">1</span>
Seems ok to me.

2021-04-01 12:19 UTC, Haprog approved these changes

2021-04-01 12:42 UTC, merged

2021-04-01 13:28 UTC, tomivirkki commented on frontend/demo/component/badge/badge-interactive.ts
> +        <div class="professions">
Unclosed tag.

<img width="679" alt="Screenshot 2021-04-01 at 16 26 17" src="https://user-images.githubusercontent.com/1222264/113300866-0e5d9400-9307-11eb-9605-c694a1767747.png">

2021-04-01 13:36 UTC, tomivirkki commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +    const renderBoolean = (
Redefining the renderer function on every render will effectively make the bound `renderer` properties reassign on every render also. Move this function as a class function instead and assign as `.renderer="${this.renderBoolean}"`.

2021-04-02 03:39 UTC, Haprog commented on frontend/demo/component/badge/badge-interactive.ts
> +        <div class="professions">
I wonder if there's some tooling we could use to automatically lint markup in html tagged template literals, and fail the build (and not rely on manual checking of IDE warnings). I've used `htmlhint` before, but only with plain HTML files. I'm not sure if it can be made to work in template literals.

2021-04-08 13:09 UTC, Lodin commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +    const renderBoolean = (
Yuriy suggested inlining helper functions, and I also aware that re-creating listeners is not a problem for `lit-html` (comparing to React, for example). Wouldn't it be more confusing for a user to have different approaches in the example?