docs: add new input fields theming properties docs
vaadin/docs pull request #2930
Opened 2023-10-30 14:35 UTC by web-padawan

Part of https://github.com/vaadin/web-components/issues/2954

This PR covers input field components (i.e. those that use `vaadin-input-container` internally).

2023-10-31 10:25 UTC, rolfsmeds requested changes

2023-10-31 10:25 UTC, rolfsmeds commented on articles/components/_styling-section-theming-props.adoc
> +== Style Properties
This section could have its own tag so that it can be used with non-input-fields as well.
(As the "input field components shared styles" admonition is the only part specific to input fields)

2023-10-31 10:25 UTC, rolfsmeds commented on articles/components/_styling-section-theming-props.adoc
> +// tag::label[]
Maybe the label, helper and error sections could all be in a single tag, so they could be inclued with a single include? They're shared by all input fields after all, the only part that needs to be separate is input surface and icons (and I guess icons could be part of input surface section since they're rendered inside the surface).

Then there's the detail that some input fields have extra features in the surface, like toggle buttons. So ideally we'd like to _extend_ that section with component-specific properties for those. I suppose that would require keeping the table block "open"?

2023-10-31 11:14 UTC, web-padawan commented on articles/components/_styling-section-theming-props.adoc
> +== Style Properties
There is the `"the appearance of Vaadin input field components."` statement in the first sentence. Should we rephrase it to something like `"the appearance of this component"` instead?

2023-10-31 11:16 UTC, web-padawan commented on articles/components/_styling-section-theming-props.adoc
> +// tag::label[]
Combined label, helper and error to `label-helper-error` include.

As for other features, I'd prefer to avoid unclosed tables if possible. After all, we don't currently have any custom CSS properties that cover these individual component-specific properties at this pointl.

2023-11-01 06:53 UTC, rolfsmeds commented on articles/components/_styling-section-theming-props.adoc
> +== Style Properties
Ah, indeed, yes!

2023-11-01 06:55 UTC, rolfsmeds commented on articles/components/_styling-section-theming-props.adoc
> +// tag::label[]
Yeah, I suppose we can add those to a separate section once we get there. It's not ideal, but everything's a compromise :)

2023-11-01 09:42 UTC, web-padawan commented on articles/components/_styling-section-theming-props.adoc
> +== Style Properties
Extracted "Style Properties" into separate include block so it can be used iwth other components too.

2023-11-02 07:25 UTC, rolfsmeds approved these changes

2023-11-02 08:30 UTC, merged