Add form change example
vaadin/docs pull request #2940
Opened 2023-11-03 11:47 UTC by tarekoraby

2023-11-03 20:56 UTC, taefi requested changes

2023-11-03 20:56 UTC, taefi commented on frontend/demo/fusion/forms/formchange/CompanyOfficeView.tsx
> +      OfficeService.loadCity(form.value.country).then((cities) => {
```suggestion
      OfficeService.loadCities(form.value.country.name).then((cities) => {
```

2023-11-03 20:56 UTC, taefi commented on src/main/java/com/vaadin/demo/fusion/forms/formchange/OfficeService.java
> +    }
I suggest to change the input to `countryName` instead of the `Country` object, and simplify implementation:

```suggestion
    public List<City> loadCities(String countryName) {
        // Find the cities by country
        return countries.stream()
                .filter(country -> country.getName().equals(countryName))
                .findFirst()
                .map(Country::getCities)
                .orElseThrow(() -> new IllegalArgumentException("No such country"));
    }
```

2023-11-03 20:56 UTC, taefi commented on articles/lit/guides/forms/form-status-tracking.adoc
>  // end::content[]
I guess the following tag should be moved to the end of the file:
```suggestion
// end::content[]
```

2023-11-04 11:02 UTC, tarekoraby commented on articles/lit/guides/forms/form-status-tracking.adoc
>  // end::content[]
Moved

2023-11-06 07:08 UTC, taefi approved these changes

2023-11-10 19:42 UTC, merged