Java: Tree Grid examples
vaadin/docs pull request #295
Opened 2021-03-22 14:01 UTC by anezthes

2021-03-23 19:35 UTC, DiegoCardoso requested changes
I think after these changes I pointed out, it mostly looks good to me. One thing, though, is that we should be using the `DataService` methods to get the hierarchical data. If the API is not good for that matter, it should be adjusted, I believe. What do you think, @tomivirkki?

2021-03-23 19:35 UTC, DiegoCardoso commented on articles/ds/components/tree-grid/index.asciidoc
> + ----
There's an extra space on the beginning and that's making the code not showing properly.
```suggestion
----
```

2021-03-23 19:35 UTC, DiegoCardoso commented on articles/ds/components/tree-grid/index.asciidoc
> +include::../../../../src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java[render,tags=snippet,indent=0,group=Java]
NIT: here and in all the other files being included, we can use `{root}` instead.
```suggestion
include::{root}/src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java[render,tags=snippet,indent=0,group=Java]
```

2021-03-23 19:35 UTC, DiegoCardoso commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +            </vaadin-grid-tree-toggle>
While checking the code produced by the Java example, I came to realise that `<vaadin-grid-tree-toggle>` has a default slot, so to make it aligned with the counterpart, I would suggest to remove the outer `<vaadin-horizontal-layout>` and make everything a child of the tree-toggle element.

2021-03-23 19:35 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java
> +        treeGrid.addColumn(Person::getEmail);
The headers are missing:
```suggestion
        treeGrid.addHierarchyColumn(Person::getFirstName).setHeader("First name");
        treeGrid.addColumn(Person::getLastName).setHeader("Last name");
        treeGrid.addColumn(Person::getEmail).setHeader("Email");
```

2021-03-23 19:35 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java
> +        });
The header is missing:
```suggestion
        }).setHeader("Employee");
```

2021-03-23 19:35 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java
> +        });
The header is missing:
```suggestion
        }).setHeader("Contact");
```

2021-03-23 19:40 UTC, DiegoCardoso commented
Forgot to mention that the WIP admonition can be removed.

2021-04-19 08:03 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +            </vaadin-grid-tree-toggle>
I think I did what you asked. :D

2021-04-20 12:25 UTC, DiegoCardoso commented
All suggestions pointed by me are done, except about this one:

> One thing, though, is that we should be using the DataService methods to get the hierarchical data. If the API is not good for that matter, it should be adjusted, I believe.

The views are using their own filtering logic for the hierarchical data, but it could use the `DataService` instead. As pointed on the original comment, maybe the API as it is atm doesn't work properly and can be adjusted.

2021-05-03 08:41 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        .expandedItems=${this.expandedItems}
Can I ask why the quotes are removed?

I’ve specifically asked for us to always quote binding values, so that the syntax highlighting on the website works as expected.

2021-05-03 08:42 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        .expandedItems=${this.expandedItems}
My assumption is that this might be an accident when fixing merge conflicts.

2021-05-03 08:43 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +              </vaadin-vertical-layout>
Missing quotes around attribute values here as well.

2021-05-03 10:20 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        .expandedItems=${this.expandedItems}
Not intentional. Fixed.

2021-05-03 10:20 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +              </vaadin-vertical-layout>
Updated. LGTY?

2021-05-03 13:24 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +            .expanded=${!!model.expanded}
```suggestion
            @expanded-changed="${(e: GridTreeToggleExpandedChanged) => {
              if (e.detail.value) {
                this.expandedItems = [...this.expandedItems, person];
              } else {
                this.expandedItems = this.expandedItems.filter((p) => p.id !== person.id);
              }
            }}"
            .expanded="${!!model.expanded}"
```

2021-05-03 13:24 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        <vaadin-button @click=${() => (this.expandedItems = [])}>Collapse All</vaadin-button>
```suggestion
        <vaadin-button @click="${() => (this.expandedItems = [])}">Collapse All</vaadin-button>
```

2021-05-03 13:25 UTC, jouni commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        <vaadin-button @click=${() => (this.expandedItems = [...this.managers])}>
```suggestion
        <vaadin-button @click="${() => (this.expandedItems = [...this.managers])}">
```

2021-05-04 06:52 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +            .expanded=${!!model.expanded}
Fixed!

2021-05-04 06:53 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        <vaadin-button @click=${() => (this.expandedItems = [])}>Collapse All</vaadin-button>
Fixed!

2021-05-04 06:53 UTC, anezthes commented on frontend/demo/component/tree-grid/tree-grid-column.ts
> +        <vaadin-button @click=${() => (this.expandedItems = [...this.managers])}>
Fixed!

2021-05-04 12:39 UTC, DiegoCardoso approved these changes

2021-05-04 14:26 UTC, merged