docs: update articles for access denied error feature
vaadin/docs pull request #2956
Opened 2023-11-10 11:48 UTC by tltv

Updates exceptions.asciidoc example to be not mixed with build-in AccessDeniedException. Updates enabling-security.adoc to document how to customize access denied error page and how to use new AccessDeniedErrorRouter annotation to reroute to different error page for unauthorized route.

Related-to: vaadin/flow#11335

2023-11-10 13:03 UTC, mcollovati requested changes

2023-11-10 13:03 UTC, mcollovati commented on articles/security/enabling-security.adoc
> +[role="since:com.vaadin:vaadin@V23.3"]
Should it be 24.3?
```suggestion
[role="since:com.vaadin:vaadin@V24.3"]

```

2023-11-10 13:17 UTC, mshabarov requested changes

2023-11-10 13:17 UTC, mshabarov commented on articles/routing/exceptions.asciidoc
> +            throw new CustomAccessDeniedException(
Not clear from where `CustomAccessDeniedException` originates, I propose to add it's declaration to these docs.

2023-11-10 13:17 UTC, mshabarov commented on articles/security/enabling-security.adoc
> +Following example reroute unauthorized admin view to [classname]`RouteNotFoundError` view which is default view for [classname]`NotFoundException` type.
```suggestion
Following example reroutes unauthorized admin view to [classname]`RouteNotFoundError` view which is default view for [classname]`NotFoundException` type.

```

2023-11-10 13:23 UTC, tltv commented on articles/routing/exceptions.asciidoc
> +            throw new CustomAccessDeniedException(
you mean like renaming it to `org.test.CustomAccessDeniedException`? then I think we could just keep the old name and use `org.test.AccessDeniedException` in this example. I renamed it to avoid mistaking it with the new class `com.vaadin.flow.router.AccessDeniedException`.

2023-11-10 13:27 UTC, mshabarov commented on articles/routing/exceptions.asciidoc
> +            throw new CustomAccessDeniedException(
Adding a package to highlight that this is something created in examples codes, or add these lines:
```java
 public class CustomAccessDeniedException extends RuntimeException {
 }
```

2023-11-10 14:07 UTC, mcollovati approved these changes

2023-11-10 14:43 UTC, mshabarov approved these changes

2023-11-13 07:59 UTC, mshabarov approved these changes

2023-11-13 07:59 UTC, merged