Update Upload docs/demos based on review
vaadin/docs pull request #300
Opened 2021-03-23 14:07 UTC by Haprog

Handle post-merge review issues from https://github.com/vaadin/docs/pull/248.

Refactor some of the file list and request mocking setup to have cleaner demos and hide the irrelevant parts from the code snippet previews.

2021-03-23 14:11 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
This is a way I found to be able to hide attributes/bindings from both the unexpanded and expanded code snippet previews. `hidden-full-source-line` only hides it from the expanded preview. Wrapping with `end::snippet[]`/`tag::snippet[]` was needed but sadly there was no cleaner syntax that would work since no normal comments seem to be allowed within a start tag's `<` and `>`.

2021-03-23 14:14 UTC, Haprog commented on pom.xml
> +        </dependency>
This was added to be able to use the notification helper:
```ts
import { showErrorNotification } from '@vaadin/flow-frontend/a-notification';
```

This is also included in start.vaadin.com projects. Imo this type of helper should be part of the notification component in the future. However we could also just copy the implementation into this project if we want to avoid the dependency. The source is here: https://github.com/Artur-/a-vaadin-helper/blob/master/src/main/resources/META-INF/resources/frontend/a-notification.ts

2021-03-23 16:21 UTC, jouni commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
It's possible to exclude nested tagged regions, as an alternative. For example `tags=outer;!inner"`

https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/#tag-filtering

2021-03-23 16:26 UTC, jouni commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
But it seems like we should have a clear way of having code thst can be omitted from both collapsed and expanded code. The current hide-full-source-line could be hidden in the collapsed version as well, IMO.

2021-03-24 06:34 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
Yeah I was surprised that `hide-full-source-line` only hid it from one. I can't think of any case where it would be needed to show something in collapsed but hide it from expanded. If we can make `hide-full-source-line` hide it from both, then we could get rid of these two dummy lines here.

2021-03-24 07:29 UTC, Haprog commented
I can rebase this on latest after this has been reviewed and approved. Currently latest is one commit ahead (which only adds Avatar Java demos and does not conflict).

2021-03-24 07:30 UTC, jouni commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
https://github.com/vaadin/docs-app/pull/253

2021-03-24 08:21 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
With @jouni's above PR to docs-app this can be simplified to:
```html
      <!-- hidden-source-line --><!-- prettier-ignore -->
      <vaadin-upload
        no-auto
        .files=${this.files /* hidden-source-line */}
      ></vaadin-upload>
```
Now the prettier-ignore line for the `<vaadin-upload>` tag is needed to prevent prettier from forcing the tag to a single line since is has less code now. At least this seems cleaner than two dummy property bindings.

2021-03-24 08:26 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
Actually would be nice if `prettier-ignore` lines would also be automatically hidden so the first line here could be just `<!-- prettier-ignore -->` instead of `<!-- hidden-source-line --><!-- prettier-ignore -->`

2021-03-24 08:27 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
At least I don't think we want to show any `prettier-ignore` comments in the snippets intentionally.

2021-03-24 10:40 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .__dummy2=${'' /* tag::snippet[] */}
This has now been simplified (in all the files where this syntax was used) since above docs-app PR was merged. This now requires the latest version of `docs-app`.

2021-03-24 14:00 UTC, yuriy-fix requested changes

2021-03-24 19:10 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +  @internalProperty() // hidden-full-source-line
Good point. I guess `@internalProperty` would only be needed in case we would need to update the value (and have it trigger a render)? It's probably not needed for any of the private properties that are basically constant.

2021-03-24 19:22 UTC, Haprog commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
Would that be only used for the Java demo or can it somehow be used for TS demos too? If it's only for the Java demo I guess it should be implemented with the Java demos se it could be outside the scope of this PR.

2021-03-24 19:24 UTC, Haprog commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
The class should probably be called `UploadFile` so it matches the TS interface from `vaadin-upload`.

2021-03-24 19:27 UTC, Haprog commented on frontend/demo/component/upload/upload-basic.ts
> +        .files=${this.files /* hidden-source-line */}
In my original version this wasn't a problem when I was setting `files` in `firstUpdated` with `querySelector`. Otherwise I like being able to just bind it here, but would be nice to have a syntax for trimming all the whitespace around a `hidden-source-line` so this could become just `<vaadin-upload></vaadin-upload>` in the preview.

I think I'll experiment with implementing such trimming in `docs-app`.

2021-03-24 20:04 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +  @internalProperty() // hidden-full-source-line
Update: removed unnecessary use of `@internalProperty`.

2021-03-24 20:06 UTC, Haprog commented on pom.xml
> +        </dependency>
Update: removed the dependency and copied the implementation to a local file `demo/notification-helper.ts` (made minor changes to satisfy prettier and fixed some TS types in it).

2021-03-24 20:35 UTC, Haprog commented on frontend/demo/component/upload/upload-basic.ts
> +        .files=${this.files /* hidden-source-line */}
Here's a PR to docs-app that can fix this: https://github.com/vaadin/docs-app/pull/257.

If that gets merged, we could use `hidden-source-line-trim` here and the result in the preview would be a clean `<vaadin-upload></vaadin-upload>`.

2021-03-25 10:53 UTC, tomivirkki commented on frontend/demo/component/upload/upload-all-files.ts
> +        .files=${this.files /* hidden-source-line */}
You probably don't need the `files` property in the class if you use:
`.files=${createFakeFilesUploadAllFiles()}`

2021-03-25 11:04 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .files=${this.files /* hidden-source-line */}
Good idea. Will update these.

2021-03-25 11:07 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .files=${this.files /* hidden-source-line */}
This change also makes the line just long enough that we don't need the `prettier-ignore` line either.

2021-03-25 11:17 UTC, Haprog commented on frontend/demo/component/upload/upload-basic.ts
> +        .files=${this.files /* hidden-source-line */}
Update: Now this is using the new feature `hidden-source-line-trim` and the result in the preview is a clean `<vaadin-upload></vaadin-upload>`.

2021-03-25 11:18 UTC, Haprog commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
@tomivirkki @yuriy-fix Should I do something about this in the scope of this PR?

2021-03-25 11:19 UTC, Haprog commented on frontend/demo/component/upload/upload-all-files.ts
> +        .files=${this.files /* hidden-source-line */}
Updated.

2021-03-25 11:36 UTC, tomivirkki commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
If this is a big change, it could be revisited when the Java-examples are created?

2021-03-25 11:41 UTC, Haprog commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
I'm not sure what exactly this would require or what @yuriy-fix had in mind.

2021-03-26 11:44 UTC, yuriy-fix commented on frontend/demo/component/upload/upload-demo-mock-files.ts
> +import { createFakeUploadFiles } from './upload-demo-helpers';
I guess we can implement it later when working on Java examples. Not blocking this PR.

2021-03-26 11:53 UTC, yuriy-fix approved these changes

2021-03-26 13:36 UTC, merged