docs: implementing custom services for auto grid / form / crud
vaadin/docs pull request #3008
Opened 2023-11-29 15:52 UTC by sissbruecker

Adds documentation for working with non-JPA Java classes in `AutoGrid`, `AutoForm` and `AutoCrud`. For now, only covers implementing custom services.

2023-11-29 16:12 UTC, cromoteca commented on src/main/java/com/vaadin/demo/fusion/crud/ProductDtoCrudService.java
> +        return productRepository.findById(id).map(ProductDto::fromEntity).orElse(null);
Let's consider https://github.com/vaadin/hilla/pull/1829 before committing to this API

2023-11-29 16:16 UTC, cromoteca commented on src/main/java/com/vaadin/demo/fusion/crud/ProductDtoCrudService.java
> +        return ProductDto.fromEntity(product);
The DTO should be created from the product as returned by `save`

2023-11-29 16:17 UTC, cromoteca commented on src/main/java/com/vaadin/demo/fusion/crud/ProductDtoListService.java
> +        Specification<Product> spec = jpaFilterConverter.toSpec(filter, Product.class);
As above, filter is nullable

2023-11-29 16:19 UTC, cromoteca commented on articles/react/components/auto-crud/_shared.adoc
> +** `OrFilter` contains a list of nested filters (`AndFilter.getChildren()`) of which at least one should match.
```suggestion
** `OrFilter` contains a list of nested filters (`OrFilter.getChildren()`) of which at least one should match.
```

2023-11-29 16:22 UTC, cromoteca commented on articles/react/components/auto-crud/index.asciidoc
> +The `get`, `save` and `delete` method implementations should be straight-forward to adapt.
```suggestion
The `get`, `save` and `delete` method implementations should be straightforward to adapt.
```

2023-11-29 16:23 UTC, cromoteca commented on articles/react/components/auto-form/index.asciidoc
> +Auto Form supports working with plain, non-JPA beans. This can be useful, for example if you want to use the Data Transfer Object (DTO) pattern to decouple your domain from your presentation logic, o
`client-side` looks like a compound adjective, but here it's not used as such

2023-11-29 16:23 UTC, cromoteca commented on articles/react/components/auto-crud/index.asciidoc
> +Auto CRUD supports working with plain, non-JPA beans. This can be useful, for example if you want to use the Data Transfer Object (DTO) pattern to decouple your domain from your presentation logic, o
`client-side` looks like a compound adjective, but here it's not used as such

2023-11-29 16:24 UTC, cromoteca commented on articles/react/components/auto-grid/index.asciidoc
> +Auto Grid supports working with plain, non-JPA beans. This can be useful, for example if you want to use the Data Transfer Object (DTO) pattern to decouple your domain from your presentation logic, o
`client-side` looks like a compound adjective, but here it's not used as such

2023-12-04 08:59 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/fusion/crud/ProductDtoCrudService.java
> +    public List<ProductDto> list(Pageable pageable, Filter filter) {
Decided to remove the filter implementation from the CrudService implementation to keep it focused on the editing part. Was planning to just add a link to the `AutoGrid` docs for more advanced `list` implementations.

2023-12-05 10:05 UTC, cromoteca requested changes
Very good PR, clear and not too long.

2023-12-05 10:41 UTC, cromoteca approved these changes

2023-12-05 12:22 UTC, sissbruecker commented on articles/react/components/auto-grid/index.asciidoc
> +== Working with Plain Java Beans
Indeed, I wasn't quite sure which term to use. DTO was a bit too specific, so I went with bean. But I can see how that is a vague term with different interpretations as well. I would suggest "Working with Plain Java Classes" then.

Adding a note to the intro makes sense, can do it after we agree on the terminology.

2023-12-05 12:34 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +The following example shows a basic implementation of a custom `ListService` that wraps a JPA repository. The service only exposes DTO instances to the client and maps between the DTO instances and J
```suggestion
The following example shows a basic implementation of a custom `ListService` that wraps a JPA repository. The service only exposes DTO instances to the client and maps between the DTO instances and JPA entities internally. It also reuses the Hilla `JpaFilterConverter` for the filter implementation. In order for sorting and filtering to work, the DTO class and the JPA entity class must have the same structure, which means all properties that are sorted and filtered-by should have the same name and are at the same path in the data structure.
```

2023-12-05 12:34 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +== Working with Plain Java Beans
As a title, "Working with Plain Java Classes" makes sense to me. 

In the introductory section, I suggest adding something like the following at line #65:

> Auto Grid supports working with plain, non-JPA classes, which can be useful, for example, if you want to use the Data Transfer Object (DTO) pattern. See the <<working-with-plain-java-classes, Working with Plain Java Classes>> section.

2023-12-05 12:35 UTC, tarekoraby commented on articles/react/components/auto-grid/index.asciidoc
> +== Working with Plain Java Beans
As a title, "Working with Plain Java Classes" makes sense to me.

In the introductory section, I suggest adding something like the following at line #65:

> Auto Grid supports working with plain, non-JPA classes, which can be useful, for example, if you want to use the Data Transfer Object (DTO) pattern. See the <<working-with-plain-java-classes, Working with Plain Java Classes>> section.

2023-12-05 14:36 UTC, sissbruecker commented on articles/react/components/auto-grid/index.asciidoc
> +== Working with Plain Java Beans
Thanks, updated all three articles accordingly.

2023-12-05 19:55 UTC, tarekoraby approved these changes

2023-12-06 07:40 UTC, cromoteca requested changes

2023-12-06 07:40 UTC, cromoteca commented on articles/react/components/auto-crud/index.asciidoc
> +`CrudService` is a common interface shared with other components such as <<../auto-crud#,Auto CRUD>> and as such requires implementing a `list` method for fetching items. If you intend to use the ser
Now that https://github.com/vaadin/hilla/pull/1852 is merged, this should be rephrased

2023-12-06 08:05 UTC, sissbruecker commented on articles/react/components/auto-crud/index.asciidoc
> +`CrudService` is a common interface shared with other components such as <<../auto-crud#,Auto CRUD>> and as such requires implementing a `list` method for fetching items. If you intend to use the ser
It looks like this would require a lot more changes, including rephrasing the introduction and updating the examples to use a `FormService`. I would suggest to merge as is so the content is available for the DX tests. I would prepare a follow up PR to make the requested changes today.

2023-12-06 08:07 UTC, cromoteca commented on articles/react/components/auto-crud/index.asciidoc
> +`CrudService` is a common interface shared with other components such as <<../auto-crud#,Auto CRUD>> and as such requires implementing a `list` method for fetching items. If you intend to use the ser
OK. I can take care of the follow up too.

2023-12-06 08:38 UTC, cromoteca approved these changes

2023-12-06 08:45 UTC, merged