fix: Add a reference to rerouteToError annotation parameter
vaadin/docs pull request #3015
Opened 2023-12-01 12:56 UTC by mshabarov

Fixes https://github.com/vaadin/docs/issues/3013

2023-12-01 13:04 UTC, mcollovati requested changes

2023-12-01 13:04 UTC, mcollovati commented on articles/routing/exceptions.adoc
> +@PermitAll
I think this should be `@AnonymousAllowed`. This error handler is not handling a security exception, so the error view should be public

2023-12-01 13:04 UTC, mcollovati commented on articles/routing/exceptions.adoc
> +Re-routing to a custom access denial views is also possible with annotation [annotationname]`@AccessDeniedErrorRouter`, see <<{articles}/advanced/custom-error-handler#, Customizing Error Messages for
Should this note maybe be moved to the previous paragraph?

2023-12-18 12:26 UTC, mshabarov commented on articles/routing/exceptions.adoc
> +@PermitAll
Agree.

2023-12-18 12:47 UTC, mshabarov commented on articles/routing/exceptions.adoc
> +@PermitAll
Changed

2023-12-18 12:53 UTC, mshabarov commented on articles/routing/exceptions.adoc
> +Re-routing to a custom access denial views is also possible with annotation [annotationname]`@AccessDeniedErrorRouter`, see <<{articles}/advanced/custom-error-handler#, Customizing Error Messages for
Yes, done.

2023-12-18 12:59 UTC, mcollovati approved these changes

2023-12-18 13:00 UTC, merged