feat: [autogrid/autoform] add section about autogrid filter options a…
vaadin/docs pull request #3041
Opened 2023-12-12 08:30 UTC by krissvaa

Add sections about the Autogrid filter options and the Autoform field custom validators.

Features documented:
https://github.com/vaadin/hilla/issues/1797
https://github.com/vaadin/hilla/issues/1492

2023-12-12 11:13 UTC, taefi requested changes

2023-12-12 11:13 UTC, taefi commented on articles/react/components/auto-form/index.asciidoc
> +==== Customizing field client-side validation
```suggestion
==== Customizing Field Client-side Validation
```

2023-12-12 11:13 UTC, taefi commented on articles/react/components/auto-grid/index.asciidoc
> +You can customize the filter options by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime` or `filterMinLength`
```suggestion
You can customize the filter options by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime` or `filterMinLength`:
```

2023-12-12 11:13 UTC, taefi requested changes

2023-12-12 11:13 UTC, taefi commented on articles/react/components/auto-grid/index.asciidoc
> +You can customize the filter options by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime` or `filterMinLength`:
```suggestion
You can customize the filter options by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime`, or `filterMinLength`:
```

2023-12-12 11:14 UTC, taefi requested changes

2023-12-12 11:14 UTC, taefi commented on articles/react/components/auto-form/index.asciidoc
> +==== Customizing Field Client-side Validation
```suggestion
==== Customizing Field Client-Side Validation
```

2023-12-12 11:15 UTC, taefi approved these changes
LGTM

2023-12-12 14:48 UTC, jouni commented on articles/react/components/auto-form/index.asciidoc
> +include::{root}/frontend/demo/component/auto-form/react/auto-form-field-custom-validator.tsx[render,frame,tags=snippet,indent=0]
Any particular reason why this example needs to be rendered inside an `<iframe>`?

2023-12-12 14:50 UTC, jouni commented on articles/react/components/auto-form/index.asciidoc
> +include::{root}/frontend/demo/component/auto-form/react/auto-form-field-custom-validator.tsx[render,frame,tags=snippet,indent=0]
Oh, I see. All examples on this page are. Though, I’m not sure they all need to. Only the ones where the responsive layout behavior is demonstrated benefit from it. The other examples suffer from it, as they are scaled down, and quite difficult to see on narrow viewport sizes.

2023-12-12 14:50 UTC, jouni commented on articles/react/components/auto-form/index.asciidoc
> +include::{root}/frontend/demo/component/auto-form/react/auto-form-field-custom-validator.tsx[render,frame,tags=snippet,indent=0]
I would revise all examples on this page.

2023-12-12 15:06 UTC, taefi commented on articles/react/components/auto-form/index.asciidoc
> +include::{root}/frontend/demo/component/auto-form/react/auto-form-field-custom-validator.tsx[render,frame,tags=snippet,indent=0]
I think the reason to use the scaling was that we wanted them to be rendered in two column layout instead of shrinking automatically to a one column layout. Maybe there is a better way to do it.

2023-12-13 07:52 UTC, sissbruecker requested changes

2023-12-13 07:52 UTC, sissbruecker commented on articles/react/components/auto-form/index.asciidoc
> +==== Customizing Field Client-Side Validation
Note that there is already a PR for adding a section about validation: https://github.com/vaadin/docs/pull/3027

2023-12-13 10:55 UTC, sissbruecker commented on articles/react/components/auto-grid/index.asciidoc
> +You can customize the filter options by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime`, or `filterMinLength`:
```suggestion
=== Filter Options

You can customize the filter behavior by using additional `columnOptions` properties like: `filterPlaceholder`, `filterDebounceTime`, or `filterMinLength`:
```

2023-12-14 10:24 UTC, taefi approved these changes

2023-12-20 11:52 UTC, sissbruecker approved these changes

2023-12-20 11:56 UTC, krissvaa commented on articles/react/components/auto-form/index.asciidoc
> +include::{root}/frontend/demo/component/auto-form/react/auto-form-field-custom-validator.tsx[render,frame,tags=snippet,indent=0]
Validations already implemented with: https://github.com/vaadin/docs/pull/3027

2024-01-08 08:28 UTC, merged