docs: update MenuBar docs to use CSS class
vaadin/docs pull request #3048
Opened 2023-12-12 18:26 UTC by DiegoCardoso

Update MenuBar documentation to use CSS classes instead of the theme API

Fixes #3030

2023-12-13 07:17 UTC, rolfsmeds requested changes

2023-12-13 07:17 UTC, rolfsmeds commented on frontend/themes/docs/menu-bar-styling.css
>      text-transform: uppercase;
We could change the styling to something people actually might notice, like background color?

2023-12-13 07:17 UTC, rolfsmeds commented on articles/components/menu-bar/index.adoc
> +Individual menu items can be styled by [since:com.vaadin:vaadin@V24.3]##applying custom classnames to them##, and writing CSS style blocks targeting those classnames. Note that root-level menu items
Apparently we've decided to go with "class names" instead of "classnames" in docs, so let's change all occurrences to that.

2023-12-13 19:03 UTC, DiegoCardoso commented on frontend/themes/docs/menu-bar-styling.css
>      text-transform: uppercase;
Changed to use Lumo utility classes and removed this file.

2023-12-13 19:03 UTC, DiegoCardoso commented on articles/components/menu-bar/index.adoc
> +Individual menu items can be styled by [since:com.vaadin:vaadin@V24.3]##applying custom classnames to them##, and writing CSS style blocks targeting those classnames. Note that root-level menu items
Done.

2023-12-14 07:01 UTC, rolfsmeds approved these changes

2023-12-19 17:31 UTC, merged