include common security content from flow to fusion
vaadin/docs pull request #306
Opened 2021-03-24 20:23 UTC by haijian-vaadin

2021-03-25 09:52 UTC, jouni requested changes

2021-03-25 09:52 UTC, jouni commented on .github/styles/Vocab/Docs/accept.txt
> +[uU]nsecure
I think the correct term is "insecure".

2021-03-25 09:52 UTC, jouni commented on articles/flow/security/best-practices.asciidoc
> +Generally, it is recommended that the developer double-checks user identity and access rights for each call from the client. This can be automated with for example, Spring Security and view-based aut
```suggestion
Generally, it is recommended that the developer double-checks user identity and access rights for each call from the client.
This can be automated with, for example, Spring Security and view-based authentication using roles.
What typically can’t be automated by these frameworks is data-based access rights, such as limiting access to specific entities.
```

2021-03-25 09:52 UTC, jouni commented on articles/flow/security/best-practices.asciidoc
> +As an example, if the server receives an ID of a User object to be displayed in for example, a URL request parameter (`{yourapp.com}/users/4/edit`), then the ID in question can be freely changed by a
```suggestion
As an example, if the server receives an ID of a User object to be displayed in, for example, a URL request parameter (`{yourapp.com}/users/4/edit`), then the ID in question can be freely changed by an attacker.
The application needs to be aware of this and check if the currently logged in user has access rights to this entity.
This is something that is common for all UI frameworks, and not specific to Vaadin.
```

2021-03-25 09:52 UTC, jouni commented on .github/styles/Vocab/Docs/accept.txt
> +[uU]nsecure
Actually, both are valid, and apparently "unsecure" is more common in tech.

2021-03-25 09:53 UTC, jouni reviewed
Just some quick formatting notes.

Edit: hmm, I wanted to clear my “request changes” review, to not block merging. Not sure how to do that.

2021-03-25 10:29 UTC, haijian-vaadin commented
> Just some quick formatting notes.

Thanks, wonder I missed them

2021-03-29 14:53 UTC, platosha approved these changes

2021-03-30 07:04 UTC, merged