chore: bump Hilla version to 2.5.1
vaadin/docs pull request #3072
Opened 2023-12-15 13:22 UTC by sissbruecker

Depends on https://github.com/vaadin/docs-app/pull/407

2023-12-15 14:56 UTC, cromoteca requested changes
Tried the application locally and everything works fine.

2023-12-15 14:56 UTC, cromoteca commented on articles/lit/guides/security/spring-stateless.adoc
> +include::{root}/articles/lit/guides/security/SecurityConfig.java[tags="stateless-configure"]
Instead of moving this file, consider doing what I did in https://github.com/vaadin/docs/pull/3018: 

- remove `@ComponentScan` from `Application.java`
- replace `@ExcludeDemoSpringComponent` with `@Profile("this-is-just-a-demo-class")` in `SecurityConfig.java`
- remove `ExcludeDemoSpringComponent.java` as it is no longer used.

This basically puts the example into a Spring profile which will never be used. This can be a permanent solution: it can be seen as a trick, but it's effective and doesn't require any additional configuration. Feel free to select the solution you prefer.

2023-12-18 07:43 UTC, sissbruecker commented on articles/lit/guides/security/spring-stateless.adoc
> +include::{root}/articles/lit/guides/security/SecurityConfig.java[tags="stateless-configure"]
Thanks, updated it to use your solution.

2023-12-18 07:59 UTC, taefi approved these changes

2023-12-18 08:23 UTC, cromoteca approved these changes

2023-12-18 08:32 UTC, merged