docs: Hilla article edits
vaadin/docs pull request #3079
Opened 2023-12-18 13:24 UTC by sissbruecker

Picks Russell's edits from https://github.com/vaadin/docs/pull/2991 into a separate PR. The version bump changes are not needed anymore, and we also decided to keep the inline code example for custom column ordering.

2023-12-18 15:49 UTC, taefi requested changes

2023-12-18 15:49 UTC, taefi commented on articles/react/components/auto-grid/index.adoc
> +To add a custom column that joins the values of multiple properties and displays them in a single column, use the `customColumns` property. This property takes an array of `GridColumn` instances and
I personally believe the existing version communicates the meaning better. The suggested edit implies that the `customColumns` is for joining the values of multiple properties and displays them in a single column, while that is only one of the possibilities.

2023-12-19 09:22 UTC, sissbruecker commented on articles/react/components/auto-grid/index.adoc
> +To add a custom column that joins the values of multiple properties and displays them in a single column, use the `customColumns` property. This property takes an array of `GridColumn` instances and
Reverted the edit

2023-12-19 09:34 UTC, taefi approved these changes

2023-12-19 10:14 UTC, merged