docs: reduce use of Tabs in AppLayout examples
vaadin/docs pull request #3084
Opened 2023-12-18 17:30 UTC by DiegoCardoso

Replace `Tabs` in `AppLayout` samples to use `SideNav`.

Also, replace `Tabs` in the bottom navbar sample with `HorizontalLayout` + `RouterLink`.

Fix #3055

2023-12-19 09:13 UTC, vursen commented on frontend/demo/component/app-layout/app-layout-basic.ts
> +            <vaadin-icon icon="vaadin:dashboard"></vaadin-icon>
Consider placing icons in prefix slot. It seems it would remove the need to wrap the content in span and also remove the need for this CSS:

```css
vaadin-icon {
  box-sizing: border-box;
  margin-inline-end: var(--lumo-space-m);
  margin-inline-start: var(--lumo-space-xs);
  padding: var(--lumo-space-xs);
}
```

2023-12-19 09:41 UTC, vursen commented on frontend/demo/component/app-layout/app-layout-basic.ts
> +    patchSideNavNavigation(this.shadowRoot!.querySelector('vaadin-side-nav')!); // hidden-source-line
This helper doesn't work? 

https://github.com/vaadin/docs/assets/5039436/db1575de-3726-4036-bce8-700e7eef049e

2023-12-19 10:24 UTC, vursen commented on src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java
> +    private SideNav getTabs() {
```suggestion
    private SideNav getSideNav() {
```

2023-12-19 11:56 UTC, rolfsmeds requested changes

2023-12-19 11:56 UTC, rolfsmeds commented on src/main/java/com/vaadin/demo/component/applayout/AppLayoutBasic.java
> +        addToDrawer(nav);
The SideNav looks a bit ugly placed directly into the drawer, as it has no built-in padding around the contents.
Start templates wrap the SideNav inside a Scroller, and applies `--lumo-space-s` padding on the Scroller, so that it's scrollable on overflow and the icons line up nicely with the hamburger icon. I think it would be good to do the same here, on all of the samples, so that it looks better and people know it needs to be in a Scroller to be scrollable. (`LumoUtility.Padding.SMALL` could be used to apply the padding.)

(We really should consider adding a padding API to Scroller, but until then...)

2023-12-19 16:04 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/applayout/AppLayoutBasic.java
> +        addToDrawer(nav);
Added the Scroller with padding in the samples.

2023-12-19 16:04 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java
> +    private SideNav getTabs() {
Done.

2023-12-19 16:04 UTC, DiegoCardoso commented on frontend/demo/component/app-layout/app-layout-basic.ts
> +            <vaadin-icon icon="vaadin:dashboard"></vaadin-icon>
Changed to use the prefix slot and removed styles.

2023-12-19 18:10 UTC, rolfsmeds requested changes
Some minor details still to fix, as commented separately. Also noticed Navbar vs Drawer sample still uses tabs – should be replaced with RouterLinks

2023-12-19 18:10 UTC, rolfsmeds commented on frontend/demo/component/app-layout/app-layout-basic.ts
>                <vaadin-icon icon="vaadin:dashboard"></vaadin-icon>
Still missing slot="prefix" in this sample.

2023-12-19 18:10 UTC, rolfsmeds commented on frontend/demo/component/app-layout/react/app-layout-basic.tsx
> +      <Scroller slot="drawer">
Padding missing on Scroller in React basic sample

2023-12-20 19:08 UTC, DiegoCardoso reviewed
Removed `Tabs` from remaining samples.

2023-12-20 19:08 UTC, DiegoCardoso commented on frontend/demo/component/app-layout/react/app-layout-basic.tsx
> +      <Scroller slot="drawer">
Done.

2023-12-20 19:08 UTC, DiegoCardoso commented on frontend/demo/component/app-layout/app-layout-basic.ts
>                <vaadin-icon icon="vaadin:dashboard"></vaadin-icon>
Done.

2023-12-20 19:09 UTC, DiegoCardoso commented
Also, I decided to use use Lumo utility classes more heavily to style the horizontal navigation samples.

2023-12-20 19:54 UTC, rolfsmeds approved these changes

2023-12-20 20:02 UTC, merged