docs: add instructions to disable component tracker
vaadin/docs pull request #3095
Opened 2023-12-22 10:44 UTC by mcollovati

Part of vaadin/flow#18130

2023-12-22 10:45 UTC, mcollovati commented
Requires https://github.com/vaadin/flow/pull/18355 to be merged

2023-12-22 11:51 UTC, tarekoraby commented on articles/configuration/development-mode/dev-tools/component-locator.adoc
> +== Disable Component Tracking
```suggestion
[since:com.vaadin:vaadin@V24.4]
== Disable Component Tracking
```

2023-12-29 08:07 UTC, tltv requested changes

2023-12-29 08:07 UTC, tltv commented on articles/configuration/properties.adoc
> +|Enables the <<development-mode/dev-tools/component-locator#, Component Locator>> tracker utility. Set to `false` to disable component tracking. This applies only to development mode.
I assume that disabling component tracker also affects Component Locator feature somehow, probably component locator can't find the selected component anymore. If this assumption is correct, consider adding a note here and also in the other article that component locator feature requires tracking to work properly.

2023-12-29 08:12 UTC, tltv commented on articles/configuration/properties.adoc
> +|Enables the <<development-mode/dev-tools/component-locator#, Component Locator>> tracker utility. Set to `false` to disable component tracking. This applies only to development mode.
> consider adding a note

I mean just a plain text. not necessarily styled as a note.

2023-12-29 08:21 UTC, mcollovati commented on articles/configuration/properties.adoc
> +|Enables the <<development-mode/dev-tools/component-locator#, Component Locator>> tracker utility. Set to `false` to disable component tracking. This applies only to development mode.
added note

2023-12-29 08:23 UTC, tltv approved these changes

2024-01-10 14:33 UTC, tarekoraby commented
Please consider re-targeting this PR to branch next, or remember to cherry-pick to next.

2024-01-11 09:00 UTC, merged