Add Board component article + TS examples
vaadin/docs pull request #310
Opened 2021-03-25 11:04 UTC by Lodin

2021-03-31 13:49 UTC, jouni commented on articles/ds/components/board/index.asciidoc
> +| 2 or 3*
Use a footnote instead of the asterisk: https://docs.asciidoctor.org/asciidoc/latest/macros/footnote/

2021-04-01 07:16 UTC, tomivirkki commented on frontend/demo/component/board/board-breakpoints.ts
> +        }
These seem relevant to the example and should show in the initial code snippet (without having to expand to show the example full source)

2021-04-01 07:16 UTC, tomivirkki commented on frontend/demo/component/board/board-breakpoints.ts
> +        <board-resize-info style="20%"></board-resize-info>
The `style="20%"` isn't valid

2021-04-01 07:16 UTC, tomivirkki commented on articles/ds/components/board/index.asciidoc
> +----
All the Java examples should be commented out for now

2021-04-01 07:19 UTC, Lodin commented on frontend/demo/component/board/board-breakpoints.ts
> +        <board-resize-info style="20%"></board-resize-info>
Oh, that's the typo, thanks

2021-04-01 07:25 UTC, Lodin commented on frontend/demo/component/board/board-breakpoints.ts
> +        }
Hmm, is there any way in the asciidoc to put two parts of the code into the initial snippet? Or should I put the whole class into the snippet?

2021-04-01 07:37 UTC, tomivirkki commented on frontend/demo/component/board/board-breakpoints.ts
> +        }
There are examples of this in other demos

2021-04-01 09:01 UTC, Lodin commented
I have a concern that the last example that shows the ability to style elements basing on the current breakpoint is not very demonstrative. The font and padding change is not obvious and might be missed by the user. Probably, I need to make it more impactful by using smaller/bigger font/padding? Or change another style, like cell color?

2021-04-01 12:50 UTC, tomivirkki requested changes

2021-04-01 12:50 UTC, tomivirkki commented on frontend/demo/component/board/board-basic.ts
> +          </board-card>
Using slots for "current" and "differnece" adds a lot of verbosity to the examples. If you used properties instead, this would look as:
```html
<board-card current="745" change="33.7" text="Current users"></board-card>
<board-card current="54.6" change="112.45" text="View events"></board-card>
<board-card current="18" change="3.9" text="Custom metric"></board-card>
<board-card current="-123.45" change="0" text="Custom metric"></board-card>
```

2021-04-01 12:50 UTC, tomivirkki commented on frontend/demo/component/board/utils/board-card.ts
> +  public type = '+';
The `type` property is redundant information. If the Web Component was changed to use properties (as suggested above) instead of slots, you can determine the type from the sign of the `change` property.

2021-04-01 12:50 UTC, tomivirkki commented on frontend/demo/component/board/board-breakpoints.ts
> +    applyTheme(this.shadowRoot!);
For some reason, some examples have added non-null assertions.

<img width="837" alt="Screenshot 2021-04-01 at 15 16 21" src="https://user-images.githubusercontent.com/1222264/113296264-e7e92a00-9301-11eb-89b4-36a291d8183a.png">

2021-04-01 12:52 UTC, tomivirkki commented on frontend/demo/component/board/board-basic.ts
> +          </board-card>
"board-card" isn't a very descriptive name for such a custom element. It should be something more specific to the domain where "current", "change" and "text" are relevant.

2021-04-01 13:52 UTC, tomivirkki commented on frontend/demo/component/board/utils/board-chart.ts
> +  private events: readonly ViewEvent[] = [];
What is the readonly modifier here for? I haven't seen it used in other examples.

2021-04-01 15:37 UTC, jouni commented
> I have a concern that the last example that shows the ability to style elements basing on the current breakpoint is not very demonstrative. The font and padding change is not obvious and might be missed by the user. Probably, I need to make it more impactful by using smaller/bigger font/padding? Or change another style, like cell color?

Yeah, I think I didn’t notice the difference either when I was trying out the examples. Changing the background color would probably be the most obvious thing to notice.

2021-04-06 11:19 UTC, Lodin commented on frontend/demo/component/board/board-basic.ts
> +          </board-card>
> "board-card" isn't a very descriptive name for such a custom element

Would the `board-indicator` be better then?

> Using slots for "current" and "differnece" adds a lot of verbosity to the examples

Well, I would say that this is a case when slots shine (especially comparing to React). However, I agree, examples should have as less code as possible.

2021-04-06 11:41 UTC, tomivirkki commented on frontend/demo/component/board/board-basic.ts
> +          </board-card>
> Would the board-indicator be better then?

The name shouldn't have "board" in it as the component isn't board-specific.

> Well, I would say that this is a case when slots shine

The primary purpose of slots is to support presenting any arbitrary (HTML) content in a specific place inside the host Web Component's shadow root. Using a slot would require you to take care that, for example, a slotted `<vaadin-text-area>` works nicely inside the slot of the card. Properties on the other hand are more suitable for passing single values of known type. In this case, you just want to pass one numeric value to the card component.

2021-04-07 06:02 UTC, tomivirkki commented on frontend/demo/component/board/board-basic.ts
> +            change="+33.7%"
Why did you decide to use string type for `change` (instead of number)?

2021-04-07 12:01 UTC, tomivirkki commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
https://github.com/vaadin/docs/pull/311#pullrequestreview-628734775

2021-04-07 12:06 UTC, tomivirkki commented
The PR adds controls for trying out the component responsiveness using a split layout but the appearance is very different from what we already have in form-layout.

Board:

![Screenshot 2021-04-07 at 14 56 47](https://user-images.githubusercontent.com/1222264/113863601-8964f580-97b2-11eb-9270-ba10b0e8680d.png)

Form-layout:

![Screenshot 2021-04-07 at 15 04 51](https://user-images.githubusercontent.com/1222264/113863786-c335fc00-97b2-11eb-841c-a9661c63ae23.png)

Shouldn't these be aligned somehow?

2021-04-07 12:10 UTC, tomivirkki commented
Bumped into some issues on mobile devices. Please make sure the examples look and feel as you'd expect on mobile devices also.

2021-04-07 12:42 UTC, tomivirkki commented
When working on the examples, please follow patterns already used in the existing examples. This also applies to the internal structure.

<img width="303" alt="Screenshot 2021-04-07 at 15 40 49" src="https://user-images.githubusercontent.com/1222264/113867888-bcf64e80-97b7-11eb-95f3-d9fd2cdb1b83.png">

vs

<img width="305" alt="Screenshot 2021-04-07 at 15 38 45" src="https://user-images.githubusercontent.com/1222264/113867704-8b7d8300-97b7-11eb-8f62-4a9dc4705f26.png">

2021-04-07 14:58 UTC, Lodin commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
Just checked: if I remove `applyTheme`, component loses the badge styling.

![image](https://user-images.githubusercontent.com/8037479/113888229-d359d580-97ca-11eb-9a86-20dd5c66454f.png)

2021-04-08 05:02 UTC, Haprog commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
Would be great if we could import just the needed styles (Lumo badge) here, but I think we don't yet have any very nice way to do that into LitElement since the Lumo styles are Polymer style modules.

Easiest way I can think of is extending the experimental [ThemableElement](https://github.com/vaadin/component-mixins/tree/master/packages/themable-element) and then using [registerStyles()](https://github.com/vaadin/vaadin-themable-mixin#styling-in-javascript) with the `include` option like:
```ts
import { ThemableElement } from '@vaadin/themable-element/themable-element.js';
import { registerStyles } from '@vaadin/vaadin-themable-mixin/register-styles.js';

export class ExampleIndicator extends ThemableElement {
  static is = 'example-indicator';
  /*...*/
}
registerStyles('example-indicator', undefined, {include: ['lumo-badge']});
```
I didn't try this but I think it should work. What do you think @tomivirkki, would it be ok to do this here instead of `applyTheme()`?

Imo main issue is that `ThemableElement` is not really documented or findable, but maybe this is ok for this kind of demo?

2021-04-08 05:28 UTC, Haprog commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
Slightly off-topic but here's some recent discussion about ThemableElement in our Slack https://vaadin.slack.com/archives/C3TGRP4HY/p1617098815150800 (for reference)

2021-04-08 08:14 UTC, Lodin commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
Hmm, the idea looks interesting but I don't think we should introduce undocumented approaches in documentation examples.

2021-04-12 06:47 UTC, tomivirkki commented on articles/ds/components/board/index.asciidoc
> +You can apply different styles for each breakpoint, for example to change the font size and space between components.
Related to https://github.com/vaadin/docs/pull/310#issuecomment-814860291

This looks better now, but the admonition (in the asciidoc) is still needed

![Screenshot 2021-04-12 at 9 46 49](https://user-images.githubusercontent.com/1222264/114352053-11148080-9b74-11eb-97d2-15d11aefe3f5.png)

2021-04-12 06:49 UTC, Lodin commented on articles/ds/components/board/index.asciidoc
> +You can apply different styles for each breakpoint, for example to change the font size and space between components.
Ah, I missed that, thanks!

2021-04-12 12:20 UTC, tomivirkki commented on frontend/demo/component/board/utils/example-indicator.ts
> +    applyTheme(this.shadowRoot!);
> Just checked: if I remove applyTheme component loses the badge styling

Ah, good point. Then it's good as it is.

2021-04-12 12:21 UTC, Lodin commented on articles/ds/components/board/index.asciidoc
> +You can apply different styles for each breakpoint, for example to change the font size and space between components.
Fixed

2021-04-12 12:42 UTC, tomivirkki approved these changes
Approved. It still has some style flaws on mobile though, like this one:

<img width="374" alt="Screenshot 2021-04-12 at 15 29 30" src="https://user-images.githubusercontent.com/1222264/114395896-95332c00-9ba5-11eb-9fa3-64b2bf26d812.png">

2021-04-13 10:49 UTC, Lodin commented
Thanks, @tomivirkki, I forgot to update imports for the Column Span section. Fixed now.

2021-04-13 11:34 UTC, merged