Made clear that RouteScopeOwner is a mandatory qualifier.
vaadin/docs pull request #3120
Opened 2024-01-11 11:01 UTC by thigg

We struggled a bit because we were not realizing that RouteScopeOwner is a Qualifier and thus mandatory for lookups.
Also added an example for programmatic lookup.

Feel free to change this to your needs. This is the text that would have helped us.

2024-01-11 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=3120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=3120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=3120) it.</sub>

2024-01-11 11:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=3120) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=3120) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=3120) it.</sub>

2024-01-12 12:09 UTC, jouni commented
Thanks for the help! We’ll take it from here 👍

2024-02-02 13:55 UTC, mshabarov reviewed
The first part makes sense to me except "Beans that are `RouteScoped` are in the `RouteScope`". What is "RouteScope" ?

The second part misses some explanations about the use case.

Let me discuss with the team if this addition is clear enough for broad auditory of readers, because I might miss some details.

2024-02-07 10:09 UTC, mcollovati requested changes

2024-02-07 10:09 UTC, mcollovati commented on articles/integrations/cdi/contexts.asciidoc
> +To resolve `RouteScoped` beans programmatically, you'll need to instantiate the `RouteScopeOwner` qualifier on some matching Route.  For example, if you have an interface that lets controllers vote o
Programmatic lookup of beans is a standard CDI feature, so I'm not 100% sure it needs to be added to our documentation.
If we want to add it, as an additional quick help for users, I would try to make it more explicit that it is an optional approach, e.g. by replacing `To resolve ...` with `If you need to programmatically lookup a RouteScoped bean, ....`.

I would probably also remove the `For example ....` part and simplify the example code:

* the `AnnotationLiteral` class
* its instantiation, but using `MainLayout.class` instead of `previousRoute`, to be consistent with the other examples
* the `Instance<...>` part, but using `PreservedBean` instead of `RouteLeaveVoter`, to be consistent with the other examples

2024-03-14 10:19 UTC, mcollovati commented
Closing as reworked in #3291

2024-03-14 10:19 UTC, closed without merging