WIP: Add Role-Based Access Control article to Fusion Security
vaadin/docs pull request #313
Opened 2021-03-26 08:26 UTC by platosha

2021-04-01 12:16 UTC, joheriks requested changes

2021-04-01 12:16 UTC, joheriks commented on articles/fusion/security/role-based-access.asciidoc
> +Roles are, in the nutshell, a set of string attributes representing authorities that are assigned for a user.
```suggestion
Roles are, in the nutshell, a set of string attributes representing authorities that are assigned to a user.
```

2021-04-01 12:16 UTC, joheriks commented on articles/fusion/security/role-based-access.asciidoc
> +For using roles for access control of TypeScript views, it is convenient add a Fusion endpoint, that obtains user information with roles from Java during authentication.
```suggestion
For using roles for access control of TypeScript views, it is convenient to add a Fusion endpoint that obtains user information with roles from Java during authentication.
```

2021-04-01 12:16 UTC, joheriks commented on src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfo.java
> +        this.authorities = authorities;
As an example of good practices, would it make sense to wrap the collection into e.g. `Collections.unmodifiableSet(authorities)`.

2021-04-01 12:16 UTC, joheriks commented on articles/fusion/security/role-based-access.asciidoc
> +The above also defines `isUserInRole` helper, which enables role-based access control checks for the UI.
```suggestion
The above also defines the `isUserInRole` helper, which enables role-based access control checks for the UI.
```

2021-04-06 06:44 UTC, haijian-vaadin requested changes
Based on the feedback, having the offline functionality in this and another authentication article seems to make code more complex than it's expected. We can split the offline support part into a separate article under the Security section.

2021-04-09 09:10 UTC, joheriks commented on articles/fusion/security/role-based-access.asciidoc
> +After successful authentication, the `GrantedAuthority` objects returned `Authentication.getAuthorities()` represent those.
```suggestion
After successful authentication, the `GrantedAuthority` objects returned by `Authentication.getAuthorities()` represent those.
```

2021-04-12 06:47 UTC, joheriks requested changes

2021-04-12 06:47 UTC, joheriks commented on src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfoEndpoint.java
> +    public UserInfo getUserInfo() {
Access is now denied by default (https://github.com/vaadin/flow/pull/10526), this would need to have `@PermitAll` annotation.

2021-04-12 06:48 UTC, haijian-vaadin requested changes

2021-04-12 06:48 UTC, haijian-vaadin commented on articles/fusion/security/role-based-access.asciidoc
> +Then, change the authentication implementation in TypeScript to get the user information from the endpoint and store it in the browser’s `localStorage`.
The code examples in spring-login seem doesn't have the offline features in this PR, we can remove the reference to localStorage?

2021-04-12 06:48 UTC, haijian-vaadin commented on articles/fusion/security/spring-login.asciidoc
>  Using localStorage allows navigating to sub views without having to check authentication from the backend on every navigation so that the authentication check could also work offline.
The code examples in spring-login seem doesn't have the offline features in this PR, we can remove the reference to localStorage?

2021-04-12 10:08 UTC, haijian-vaadin commented
Just a confict to resolve, otherwise, looks good to me.

2021-04-12 10:53 UTC, haijian-vaadin approved these changes

2021-04-12 10:56 UTC, joheriks approved these changes

2021-04-12 10:56 UTC, merged