docs: Hilla file-based router usage
vaadin/docs pull request #3288
Opened 2024-03-14 07:45 UTC by platosha

Fixes #3164

2024-03-15 15:55 UTC, cromoteca requested changes
I think that it's important to find the best name for this router and stick to it. In the current version of the document, I can see "file-system based router", "file-based router", and "file-system router". Maybe "file router", as it is called in the source code.

2024-03-15 15:55 UTC, cromoteca commented on articles/hilla/guides/routing.adoc
> +Hilla React applications are using a file-system based router, which is built on top of https://reactrouter.com/en/main[React Router], a popular routing library for React applications. This documenta
```suggestion
Hilla React applications are using a filesystem-based router, which is built on top of https://reactrouter.com/[React Router], a popular routing library for React applications. This documentation can guide you through the basics of using routing in your application.
```
Or "file-system-based". See https://en.wikipedia.org/wiki/File_system, both alternatives are possible, but for sure you need a hyphen before "based".

Concerning the URL, why point to a specific page? That could change in future.

2024-03-15 15:55 UTC, cromoteca commented on articles/hilla/guides/routing.adoc
> +The structure of application routes is naturally closely related with navigation menus. The main menu is often directly lists the same items as the routes define, thus it could be created from the ro
```suggestion
The structure of application routes is naturally closely related with navigation menus. The main menu often directly lists the same items as the routes define, thus it could be created from the routes.
```

2024-03-15 15:55 UTC, cromoteca commented on articles/hilla/guides/routing.adoc
> +In this example, a page title is added to the example route.
The example is a bit confusing since it actually uses the title in the body and also deals with the page title. I'd remove the code that sets the page title.

2024-03-18 16:53 UTC, platosha commented
> I think that it's important to find the best name for this router and stick to it. In the current version of the document, I can see "file-system based router", "file-based router", and "file-system router". Maybe "file router", as it is called in the source code.

Good point. I've settled on using "the file router", and, occasionally, more general "file-based routing", as in the title. Any thoughts? @cromoteca

2024-03-26 14:36 UTC, mshabarov commented on articles/hilla/guides/routing.adoc
> +The file router is using the `.tsx` files in the `frontend/views/` directory and its subdirectories as routes.
Should be replaced by `src/main/frontend/views/`, or noted that frontend means folder inside `src/main/`.

2024-03-26 14:36 UTC, mshabarov commented on articles/hilla/guides/routing.adoc
> +The file router is using the `.tsx` files in the `frontend/views/` directory and its subdirectories as routes.
Same for other mentions of frontend path.

2024-04-15 12:37 UTC, mshabarov commented
This tutorial misses the recently added `RouterConfigurationBuilder` API, can we include it here?

2024-04-17 05:57 UTC, jouni commented on articles/hilla/guides/routing.adoc
> +  );
We should recommend our Side Nav component instead of NavLink for creating your main menu, using the `onNavigate` and `location`. E.g.

```tsx
const navigate = useNavigate();
const location = useLocation();

return <SideNav onNavigate={({ path }) => path && navigate(path)} location={location}>
  {createMenuItems().map(({ to, icon, title }) => (
    <SideNavItem path={to} key={to}>
      <Icon icon={icon} slot="prefix"/>
      {title}
    </SideNavItem>
  )}
</SideNav>
```

2024-04-17 06:28 UTC, jouni commented on articles/hilla/guides/routing.adoc
> +
Missing the `loginRequired` option.

2024-04-17 08:13 UTC, jojule commented
IMO we should have documentation for Routing in `Vaadin` not in `Hilla` or in `Flow`. Routing is a topic that integrates the frameworks and it is overly complicated to understand if we do not explain this for `Vaadin applications`.

We should not refer to `Hilla applications` or `Flow applications`.

2024-04-17 08:14 UTC, jojule commented
@petrixh how should we structure guides for topics shared between `Flow` and `Hilla`?

2024-04-17 08:16 UTC, jojule commented
Routing should cover also how routes are listed in menu

2024-04-30 10:35 UTC, taefi commented on articles/hilla/guides/routing.adoc
> +The file router is using the `.tsx` files in the `src/main/frontend/views/` directory and its subdirectories as routes.
Is it only `.tsx` files or `.jsx` files are also included?

2024-04-30 13:15 UTC, taefi commented on articles/hilla/guides/routing.adoc
> +    Set to true to explicitly exclude a view from the automatically populated menu.
Here, we could either exclude all the `?` or have the for all the nullable properties.

2024-05-03 15:34 UTC, platosha commented on articles/hilla/guides/routing.adoc
> +<NavLink to="/products/123">Show product details</NavLink>
Let's omit the parameter combinations, they are not supported at the moment.

I've mentioned the convention for optional parameters. The usage, apart from the naming convention, is exactly the same as with required parameters, so another example does not bring much value IMO.

2024-05-06 08:02 UTC, taefi approved these changes

2024-05-06 08:08 UTC, merged