ConfirmDialog: Java examples
vaadin/docs pull request #334
Opened 2021-04-06 13:07 UTC by anezthes

2021-04-15 14:36 UTC, sosa-vaadin reviewed
I checked the Netlify deploy and noticed that with **Java samples**, the code is showing but the working examples **are not being rendered**.

2021-04-15 18:26 UTC, jouni commented
Hes, that's expected and a known limitation, unfortunately. We don't have preview builds for rendered Java examples. You need to test them locally.

2021-04-16 06:42 UTC, sosa-vaadin requested changes
Fix the exception thrown at the "confirm dialog confirm button" example and you're good to go.

2021-04-16 06:42 UTC, sosa-vaadin commented on src/main/java/com/vaadin/demo/component/confirmdialog/ConfirmDialogConfirmButton.java
> +      new Html("An error occurred while exporting <b>Report Q4</b>. Please try again. If the problem persists, please contact <a href=\"mailto:support@company.com\">support@company.com</a>.")
An exception is thrown at this line because of having both the `<a>` and `<b>` nodes at the parent level. Wrap the entire content in a `<span>` to fix this. Replacing the `Html` object with a `Span` object won't work because these tags will be escaped.
```suggestion
      new Html("<span>An error occurred while exporting <b>Report Q4</b>. Please try again. If the problem persists, please contact <a href=\"mailto:support@company.com\">support@company.com</a>.</span>")
```

2021-04-19 07:48 UTC, anezthes commented on src/main/java/com/vaadin/demo/component/confirmdialog/ConfirmDialogConfirmButton.java
> +      new Html("An error occurred while exporting <b>Report Q4</b>. Please try again. If the problem persists, please contact <a href=\"mailto:support@company.com\">support@company.com</a>.")
Ah, good catch! Changed to paragraph.

2021-04-19 07:51 UTC, sosa-vaadin approved these changes
Good to go.

2021-04-19 08:59 UTC, merged