Create section for Control Center
vaadin/docs pull request #3420
Opened 2024-05-10 04:52 UTC by tamasmak

- Creates section for Control Center
- Adds overview and basic getting started

2024-06-27 05:26 UTC, peholmst approved these changes

2024-06-27 09:18 UTC, heruan requested changes

2024-06-27 09:18 UTC, heruan commented on articles/control-center/overview/index.adoc
> +
I would add a `[CAUTION]` admonition here like we have in the project repository README:
```suggestion
CAUTION: This project is still under active development and is not yet suitable for production use.
```

2024-06-27 09:35 UTC, tamasmak commented on articles/control-center/overview/index.adoc
> +
Added the caution.

2024-07-05 07:30 UTC, heruan approved these changes

2024-07-05 07:31 UTC, merged