GridPro & TreeGrid - PR 3371 & 3378
vaadin/docs pull request #3446
Opened 2024-05-22 09:59 UTC by russelljtdyer

Pull requests 3371 and 3378 were merged and closed without the language being checked. This PR covers the documents affected by those earlier PRs.

2024-05-22 13:52 UTC, web-padawan requested changes

2024-05-22 13:52 UTC, web-padawan commented on articles/components/grid-pro/index.adoc
> +Grid Pro has a few modes: edit on single-click; single cell edit; enter next row; and edit column. These are described in the sub-sections that follow.
Please note that "Edit column" isn't a sub-section of "Modes" but a standalone feature of GridPro, so it shouldn't be listed here.

2024-05-22 13:52 UTC, web-padawan commented on articles/components/grid-pro/index.adoc
> +Basically, Single Cell Edit is a mode that allows tabbing from one cell to another without exiting from edit mode.
This isn't accurate. In fact, "tabbing without exiting from edit mode" is the default behavior, whereas "single cell edit" changes the logic so that tabbing from edited cell also exits edit mode.

2024-05-22 13:52 UTC, web-padawan commented on articles/components/grid-pro/index.adoc
> +Pressing kbd:[Enter] or kbd:[Shift+Enter] saves any changes and exits edit mode, by default. However, kbd:[Enter] can be made to shift focus to the editable cell in the next row, by using the Enter N
Consider replacing "shift focus" with "move focus" as that's the wording that we generally use.

2024-05-30 11:29 UTC, jouni approved these changes

2024-05-30 11:29 UTC, merged