docs: add Popover documentation and live examples
vaadin/docs pull request #3587
Opened 2024-08-07 12:41 UTC by web-padawan

Work in progress, two examples still missing:

- Notification Panel (also used as basic example)
- Anchored Modal Dialog

2024-08-12 11:53 UTC, web-padawan commented
Vale complains about some words e.g. `mouseout`, `listbox`, `autofocus`.

2024-08-13 12:41 UTC, rolfsmeds requested changes
### Dropdown field example
- Missing aria-label
- Doesn't open on focus
- Closes on selections except on to-field?

### User Menu
- Doesn't open on kbd-click

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +The maximum width of popovers is limited to the width of the viewport, minus a small margin that can be customized with CSS by overriding the *inset* property of the *vaadin-popover-overlay* element.
```suggestion
The maximum width of popovers is limited to the width of the viewport, minus a small margin that can be customized with CSS by overriding the `inset` property of the `vaadin-popover-overlay` element.
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +By default, the Popover overlay has the ARIA role *dialog*. This can be changed to another role to provide appropriate semantics for the type of content and interaction in the popover (see <<typical-
```suggestion
By default, the Popover overlay has the ARIA role `dialog`. This can be changed to another role to provide appropriate semantics for the type of content and interaction in the popover (see <<typical-use-cases, Typical Use Cases>> for examples).
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- *menu*: when the content is a list of actions or links
```suggestion
- `menu:` when the content is a list of actions or links
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- *listbox*: when the content is a list form which you can select one or more items
```suggestion
- `listbox:` when the content is a list form which you can select one or more items
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- *grid*: when the content is a tabular structure from which you select an item
```suggestion
- `grid:` when the content is a tabular structure from which you select an item
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- *tree*: when the content is a hierarchical list
```suggestion
- `tree:` when the content is a hierarchical list
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- Modal, no modality curtain (dropdown fields typically don’t have curtains)
```suggestion
- Modal, no modality curtain (drop-down fields typically don’t have curtains)
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- Autofocused
```suggestion
- Auto-focused
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- ARIA role=”dialog”
```suggestion
- ARIA role `dialog`
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- aria-label “Select a date range”
```suggestion
- ARIA label _“Select a date range”_
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- ARIA role=”menu” (the overlay’s content is a menu; although there are non-list elements, they are not interactive, nor do they need to be announced by screen readers)
```suggestion
- ARIA role `menu` (the overlay’s content is a menu; although there are non-list elements, they are not interactive, nor do they need to be announced by screen readers)
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- aria-label “User menu”
```suggestion
- ARIA label _“User menu”_
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- ARIA role=”dialog” (although mainly a list, there interactive non-list elements as well)
```suggestion
- ARIA role `dialog` (although mainly a list, there interactive non-list elements as well)
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- aria-labelledby pointing to heading in overlay
```suggestion
- ARIA labelled-by pointing to heading in overlay
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- ARIA role=”dialog” (“tooltip” would be invalid due to interactive contents)
```suggestion
- ARIA role `dialog` (`tooltip` would be invalid due to interactive contents)
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- aria-labelledby pointing to heading in overlay
```suggestion
- ARIA labelled-by pointing to heading in overlay
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- Autofocused
```suggestion
- Auto-focused
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- ARIA role=”dialog”
```suggestion
- ARIA role `dialog`
```

2024-08-13 12:41 UTC, rolfsmeds commented on articles/components/popover/index.adoc
> +- aria-labelledby pointing to heading in the overlay
```suggestion
- ARIA labelled-by pointing to heading in the overlay
```

2024-08-14 10:45 UTC, web-padawan commented
> Doesn't open on focus

Looks like we have a problem with `focus` trigger combined with nested components like `vaadin-select`: opening the `vaadin-select-overlay` makes focus leave `vaadin-popover-overlay` and then the popover closes.

Reported https://github.com/vaadin/web-components/issues/7652 and updated the description to only use "click" for now.

2024-09-04 09:09 UTC, rolfsmeds approved these changes

2024-09-04 09:25 UTC, merged