Remove step no longer needed to deploy Vaadin app to Control Center
vaadin/docs pull request #3589
Opened 2024-08-08 05:38 UTC by sosa-vaadin

- [x] Remove instruction to add a boostrap.yml file in Vaadin apps to be deployed through Control Center.
- [x] Add warning about adding `bootstrap.yml` file or application name to a Vaadin application to be deployed through Control Center.

2024-08-08 09:10 UTC, heruan approved these changes

2024-08-13 08:21 UTC, jouni commented on articles/control-center/application-discovery/index.adoc
> +If your application has its own `bootstrap.yml` file or a name defined (i.e. the property `spring.application.name`) it may cause unexpected side-effects when trying to deploy it through Control Cent
What are the unexpected side-effects? Let's not leave the reader wondering and guessing what those might be, but rather explain everything we know could happen.

2024-08-14 06:44 UTC, heruan commented on articles/control-center/application-discovery/index.adoc
> +If your application has its own `bootstrap.yml` file or a name defined (i.e. the property `spring.application.name`) it may cause unexpected side-effects when trying to deploy it through Control Cent
Good point. On a recent commit we also removed the bootstrap file, so no need to mentioned it here, let's only mention that Control Center will set the `SPRING_APPLICATION_NAME` environment variable with the name choose in the deployment dialog and that will override any application name set in the application properties. Maybe this can be a `NOTE` instead of a `WARNING`?

2024-08-14 09:01 UTC, heruan requested changes

2024-08-14 09:01 UTC, heruan commented on articles/control-center/application-discovery/index.adoc
> +Control Center will set the `SPRING_APPLICATION_NAME` environment variable with the name chosen in the deployment dialog and that will override any application name set in the application's propertie
A lint warning recommends to avoid using "will", let's rephrase:
```suggestion
Control Center sets the `SPRING_APPLICATION_NAME` environment variable with the name chosen in the deployment dialog and that might override any application name set in the application's properties.
```

2024-08-14 10:05 UTC, heruan approved these changes

2024-08-14 10:06 UTC, merged