Document how to wrap a field React component into Flow component
vaadin/docs pull request #3600
Opened 2024-08-14 09:35 UTC by AlainaFaisal

Document of an example in [React integration docs](https://vaadin.com/docs/next/flow/integrations/react) how to wrap a React component as a Field Flow component with AbstractSinglePropertyField

Targets #3421

2024-08-14 10:15 UTC, vursen commented on articles/flow/integrations/react.adoc
> +getElement().synchronizeProperty("value", "value-changed");
Just noticed that AbstractSinglePropertyField already sets up the property synchronization in its [constructor](https://github.com/vaadin/flow/blob/29e2e4adff260516c3d75789f52600d7e10543dd/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L250-L251), so this part is probably unnecessary?

2024-08-14 11:01 UTC, AlainaFaisal commented on articles/flow/integrations/react.adoc
> +getElement().synchronizeProperty("value", "value-changed");
@vursen Thank you for your comment! I had added this as 'value-changed', in this case, was a custom event emitted by the React component to communicate changes back to the Vaadin server component. And I thought that the default behavior of AbstractSinglePropertyField does not automatically capture custom events unless explicitly instructed to do so. This is why I included the getElement().synchronizeProperty("value", "value-changed") call to ensure that the server-side state remains in sync with the client-side state whenever this particular event is fired. However, if this is not the case then I can remove this.

2024-08-14 11:41 UTC, vursen commented on articles/flow/integrations/react.adoc
> +getElement().synchronizeProperty("value", "value-changed");
Could you try the example without it to see if it works? 

Based on what I see, AbstractSinglePropertyField not only updates the model value when the property changes but also performs some other logic like checking if the new value is valid:

https://github.com/vaadin/flow/blob/29e2e4adff260516c3d75789f52600d7e10543dd/flow-server/src/main/java/com/vaadin/flow/component/AbstractSinglePropertyField.java#L350-L354

2024-08-21 11:12 UTC, caalador requested changes

2024-08-21 11:12 UTC, caalador commented on articles/flow/integrations/react.adoc
> +import ReactDOM from 'react-dom';
```suggestion

```

2024-08-21 11:12 UTC, caalador commented on articles/flow/integrations/react.adoc
> +                <span>{value.length} characters</span>
```suggestion
                <span>{value?.length} characters</span>
```
Error running if value is undefined/null so use conditional if value exists.

2024-08-21 11:12 UTC, caalador commented on articles/flow/integrations/react.adoc
> +}
```suggestion
}

customElements.define('react-text-input', ReactTextInputElement);
```
Define element to be able to use it.

2024-08-22 03:47 UTC, caalador commented on articles/flow/integrations/react.adoc
> +== Wrapping a React component into Flow component
```suggestion
== Wrapping a React Component Into a Flow Component
```
I'm not certain about these heading cases, but I guess something like this.

2024-08-22 03:47 UTC, caalador commented on articles/flow/integrations/react.adoc
> +}
```suggestion
    constructor() {
        super();
    }
```
Minor formatting.

2024-08-22 03:47 UTC, caalador commented on articles/flow/integrations/react.adoc
> +}
```suggestion
public class ReactTextField extends AbstractSinglePropertyField<ReactTextField, String> {
    public ReactTextField() {
        super("value", "", false);
    }
}
```
Formatting

2024-08-22 07:20 UTC, caalador approved these changes

2024-08-22 07:22 UTC, merged

2024-08-22 07:27 UTC, mshabarov commented on articles/flow/integrations/react.adoc
> +== Wrapping a React Component Into a Flow Component
This should be like "Wrapping a React Input Component Into a Flow Field Component".

Sorry for commenting on a closed PR, but just noticed one small remark. Could you change it in another PR ?

@AlainaFaisal