docs: control center localization feature
vaadin/docs pull request #3608
Opened 2024-08-21 13:43 UTC by sissbruecker

Adds documentation for the localization feature in Control Center.

2024-10-01 06:37 UTC, rolfsmeds requested changes
Some minor changes, otherwise looks good!

2024-10-01 06:37 UTC, rolfsmeds commented on articles/control-center/localization/index.adoc
> +To edit translations for a message or row, click on one of the cells in a language column. Using the keyboard, you can also focus one of the cells and press kbd:[Enter]. This starts the inline editin
```suggestion
To edit translations for a message, click on one of the cells in a language column. Using the keyboard, you can also focus one of the cells and press kbd:[Enter]. You can now change the translation text for one or more languages in the edited row. To save changes, you must explicitly commit them by pressing kbd:[Enter] or clicking the `Confirm` icon button in the last column. When the last translation on a row has been commited with kbd:[Enter], focus moves automatically down to the first translation on the next row.
```

2024-10-01 06:37 UTC, rolfsmeds commented on articles/control-center/localization/index.adoc
> +Translators can preview changes they made in an actual deployment of the application. They might do this to verify that text fits into the space of its container, or if a translation makes sense in t
```suggestion
Translations edited in Control Center can be previewed in a special instance of the deployed application. This can be useful for verifying that text fits into the space of its container, or to confirm that a translation makes sense in the context where it's used.
```

2024-10-01 06:37 UTC, rolfsmeds commented on articles/control-center/localization/index.adoc
> +To preview translations, click on [guibutton]*Start preview* in the sidebar of the [guilabel]*Translations* view. This creates a copy of the currently selected application that's configured to load t
```suggestion
To preview translations, click on [guibutton]*Start preview* in the sidebar of the [guilabel]*Translations* view. This starts a new instance of the application configured to load translations from Control Center instead of the application's own `translations` resource bundle. Once the preview is ready, click on [guibutton]*Open preview* to open the preview in a new browser tab.
```

2024-10-01 06:43 UTC, MatthewVaadin requested changes

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +
Add commercial feature banner

```suggestion

:commercial-feature: Localization
include::{articles}/_commercial-banner.adoc[opts=optional]

```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +description: Use Control Center to localize Vaadin applications.
Add commercial feature side nav icon

```suggestion
description: Use Control Center to localize Vaadin applications.
section-nav: commercial
```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +The Localization feature in Control Center provides support for translating Vaadin applications. First, it allows uploading of translation files from a Vaadin application. Translators can then add ne
"allows uploading of translation files from a Vaadin application" sounds like they are coming directly from the application itself. Consider rephrasing:
```suggestion
The Localization feature in Control Center provides support for translating Vaadin applications. First, it allows uploading of translation files for a Vaadin application. Translators can then add new translations or update existing ones. While translators are working on them, they can preview updated translations directly in the application. Finally, translations can be downloaded again in order to sync them back into the application.
```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +Click on [guibutton]*Enable Localization* to enable the feature. If all goes well, you should be redirected to the [guilabel]*Translations* view.
Why suggest that it might not work?

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +First, select the file type that you want to upload. Control Center supports two types of uploads: multiple [filename]`.properties` files; a zipped data package.
I think the semicolon here makes it harder to read.
```suggestion
First, select the file type that you want to upload. Control Center supports two types of uploads: multiple [filename]`.properties` files, or a zipped data package.
```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +The zipped data package can be generated from the [guilabel]*Internationalization* panel in Vaadin Copilot. This package contains the same [filename]`.properties` files that you would select with the
Since this is the first mention of Copilot in the page, it may be worth making this a link to the documentation for it.

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +The [guilabel]*Translations* view is the central view of the localization feature (see screenshot here). It allows users to view, filter and edit translations. The view has a toolbar at the top, and
```suggestion
The [guilabel]*Translations* view is the central view of the localization feature (see screenshot below). It allows users to view, filter and edit translations. The view has a toolbar at the top, and a grid with all messages and their translations below that. Next to the grid is a panel showing details for the currently selected message.
```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +The language select allows to configure which languages are shown in the grid. This allows translators to focus on the languages that are relevant for their work.
```suggestion
The language select allows configuration of the languages that are shown in the grid. This allows translators to focus on the languages that are relevant for their work.
```

2024-10-01 06:43 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +To preview translations, click on [guibutton]*Start preview* in the sidebar of the [guilabel]*Translations* view. This creates a copy of the currently selected application that's configured to load t
```suggestion
To preview translations, click on [guibutton]*Start preview* in the sidebar of the [guilabel]*Translations* view. This creates a copy of the currently selected application that's configured to load translations from Control Center (instead of the application's own `translations` resource bundle). Once the preview is ready, click on [guibutton]*Open preview* to open the preview in a new browser tab.
```

2024-10-01 12:38 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +The zipped data package can be generated from the [guilabel]*Internationalization* panel in Vaadin Copilot. This package contains the same [filename]`.properties` files that you would select with the
Done

2024-10-01 12:38 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +
Added

2024-10-01 12:39 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +The Localization feature in Control Center provides support for translating Vaadin applications. First, it allows uploading of translation files from a Vaadin application. Translators can then add ne
Done

2024-10-01 12:39 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +Click on [guibutton]*Enable Localization* to enable the feature. If all goes well, you should be redirected to the [guilabel]*Translations* view.
Rephrased it to state that the redirect happens after enabling the feature.

2024-10-01 12:39 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +First, select the file type that you want to upload. Control Center supports two types of uploads: multiple [filename]`.properties` files; a zipped data package.
Done

2024-10-01 12:39 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +The zipped data package can be generated from the [guilabel]*Internationalization* panel in Vaadin Copilot. This package contains the same [filename]`.properties` files that you would select with the
Done

2024-10-01 12:40 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +The [guilabel]*Translations* view is the central view of the localization feature (see screenshot here). It allows users to view, filter and edit translations. The view has a toolbar at the top, and
Done

2024-10-01 12:40 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +To preview translations, click on [guibutton]*Start preview* in the sidebar of the [guilabel]*Translations* view. This creates a copy of the currently selected application that's configured to load t
Used Rolf's suggestion.

2024-10-01 12:40 UTC, sissbruecker commented on articles/control-center/localization/index.adoc
> +The language select allows to configure which languages are shown in the grid. This allows translators to focus on the languages that are relevant for their work.
Done

2024-10-02 04:09 UTC, MatthewVaadin requested changes
Other than the spelling mistake, looks good!

2024-10-02 04:09 UTC, MatthewVaadin commented on articles/control-center/localization/index.adoc
> +To edit translations for a message, click on one of the cells in a language column. Using the keyboard, you can also focus one of the cells and press kbd:[Enter]. You can now change the translation t
```suggestion
To edit translations for a message, click on one of the cells in a language column. Using the keyboard, you can also focus one of the cells and press kbd:[Enter]. You can now change the translation text for one or more languages in the edited row. To save changes, you must explicitly commit them by pressing kbd:[Enter] or clicking the `Confirm` icon button in the last column. When the last translation on a row has been committed with kbd:[Enter], focus moves automatically down to the first translation on the next row.
```

2024-10-02 06:36 UTC, MatthewVaadin approved these changes

2024-10-02 07:03 UTC, rolfsmeds approved these changes

2024-10-02 07:28 UTC, merged