feat: Document @Layout
vaadin/docs pull request #3618
Opened 2024-08-27 11:12 UTC by caalador

Add documentation on using
`@Layout` auto layouting in
Flow and using server side
layout for Hilla views.

2024-08-30 11:03 UTC, mshabarov requested changes

2024-08-30 11:13 UTC, caalador commented on articles/flow/integrations/hilla.adoc
> +public class MainView extends RouterLayout {
added note

2024-08-30 12:30 UTC, mshabarov requested changes
These two articles should mention that officially the auto main layout is implied to be either in React (Hilla) or in Java (Flow), not both.

We can admit that both layouts are possible with some efforts, e.g. by wrapping React layout into Flow component, but at the moment it's a undocumented feature.

2024-09-02 08:15 UTC, mshabarov approved these changes

2024-09-02 08:15 UTC, merged