Add TS examples for cookie-consent component
vaadin/docs pull request #363
Opened 2021-04-13 15:13 UTC by Lodin

2021-04-15 07:55 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +Some examples change their behavior also based on your browser viewport size.
If we are going to reuse this content, we should extract it to a shared file and include it from there.

2021-04-15 07:55 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +Some examples change their behavior also based on your browser viewport size.
Regarding the CSS, not all of these are used on this page (no `.mobile` or `.desktop` classes used).

For the scale, 0.8 would be enough for Cookie Consent. If we extract the CSS into a shared include, we can parametrize the scale value using an Asciidoc attribute.

2021-04-15 07:55 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
Should we show this part of the source code? I assume it’s not needed in a regular Vaadin application, and therefore not necessary for developers to be able to copy paste into their project. It could end up confusing readers more than being helpful, I think.

Though, the example does use the mixin, but maybe we could add a code comment that says you can safely delete the import and the `extends ExampleMixin(...)` and just use `extends LitElement`. Would be great if there was some other way to bring in the shared functionality, so that we could hide it completely from the source code examples.

2021-04-15 07:55 UTC, jouni commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
These should rather go into the [docs theme](https://github.com/vaadin/docs/tree/latest/frontend/themes/docs) `styles.css` or `document.css`.

2021-04-15 08:06 UTC, yuriy-fix requested changes

2021-04-15 08:06 UTC, yuriy-fix commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +        background-color: var(--lumo-base-color);
Probably need to be confirmed with @anezthes, the styles specified by him in the doc don't look the same as "primary" notification. Compared to the `Primary` example on [CDN](https://cdn.vaadin.com/vaadin-notification/1.6.1/demo/#notification-theme-variants-demos).

2021-04-15 08:09 UTC, yuriy-fix commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
I am not sure that we actually need that functional part from `ExampleMixin`. Would it be enough just to show the component itself. So there will be no need in adding extra logic with mixin? 🤔

2021-04-15 08:10 UTC, tomivirkki commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
...preferably as an `@import` of a separate file specific to this example

2021-04-15 08:14 UTC, tomivirkki commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
Using mixins or a custom superclass with an example generally makes it less copy-pasteable so we've intentionally tried avoiding it.

2021-04-15 09:04 UTC, jouni commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
Yeah, true. I can update the Notification examples to do that as well (also noticed that those examples aren’t even using `applyTheme` for some reason).

2021-04-15 09:05 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
> Would it be enough just to show the component itself. So there will be no need in adding extra logic with mixin? 🤔

My assumption is that it’s needed so that the popup shows even if you’ve dismissed it before.

2021-04-15 10:28 UTC, Lodin commented on articles/ds/components/cookie-consent/index.asciidoc
> +  --scale: 0.58;
If it is not scaled, it take a mobile shape, unfortunately
![image](https://user-images.githubusercontent.com/8037479/114855240-66f45d00-9dee-11eb-84fd-3aa8ce0bda87.png)

2021-04-15 10:46 UTC, Lodin commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
Hmm, should I add this file to examples then?

2021-04-15 10:49 UTC, Lodin commented on articles/ds/components/cookie-consent/index.asciidoc
> +include::{root}/frontend/demo/component/cookieconsent/example-base.ts[group=TypeScript]
Removed. I made a shared init part instead

2021-04-15 10:50 UTC, Lodin commented on articles/ds/components/cookie-consent/index.asciidoc
> +Some examples change their behavior also based on your browser viewport size.
I applied scale 0.8, it fits perfectly. However, I'm not sure I fully understand how I can make a shared include that parametrizes with an Asciidoc attribute

2021-04-15 12:11 UTC, jouni commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
Yes, then that external style sheet should be included as a part of the examples source includes.

2021-04-15 12:12 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +Some examples change their behavior also based on your browser viewport size.
I’ll try to do that once I finish updating/fixing the Notification examples.

2021-04-15 13:24 UTC, jouni commented on frontend/demo/component/cookieconsent/cookie-consent-theming.ts
> +    document.body.appendChild(style);
Before you do it, I suggest you update from latest (or rebase), as I modified the styles.css file a short while ago.

2021-04-15 13:46 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +Some examples change their behavior also based on your browser viewport size.
I pushed an update that extracts the shared parts and makes the example scale an attribute that can be customized.

2021-04-15 13:47 UTC, jouni commented on articles/ds/components/cookie-consent/index.asciidoc
> +  --scale: 0.58;
Small amount of scaling is okay. We are using 0.8 now.

2021-04-16 14:01 UTC, jouni approved these changes
Good enough for me :+1:

2021-04-19 08:58 UTC, yuriy-fix approved these changes

2021-04-19 10:24 UTC, merged