Add Fusion offline authentication article
vaadin/docs pull request #364
Opened 2021-04-13 16:15 UTC by platosha

Fixes #349

2021-04-13 18:51 UTC, haijian-vaadin requested changes
Could add a link to the new article in [Security Overview](https://vaadin.com/docs/latest/fusion/security/overview)

The link to spring-login in [Security Aspects of Offline Authentication Checks](https://vaadin.com/docs/latest/fusion/pwa/offline-authentication-check)

2021-04-14 12:35 UTC, magi42 requested changes

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +Let us use that to store the authentication.
Could say: "This article describes how to use that to store authentication."

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +The `localStorage` API is an easy way to store some data in the browser, that also works offline.
* "some" is unnecessary
* No comma before "that".

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +It is a good idea to expire authentication after a certain time limit, but the data in `localStorage` does not expire automatically.
* "good idea" -> "good practice"
* "certain" is somewhat unnecessary

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +Also define the string key for `localStorage`, and the max age limit constant.
* "Also, "
* No comma before "and" (Oxford comma only used in lists of three or more)

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +Add the timestamp property to the TypeScript definition for the authentication object:
* "...as follows:"

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +Then, in your login method, make the object with the timestamp upon successful login result, and save it using `localStorage.setItem()`:
* Difficult to understand where the object of the sentence is. Rephrase: "Then, in your login method, upon successful login, create the object with the timestamp, and save it..."

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +If the authentication is expired, or when the user logs out, remove the stored authentication from `localStorage`:
* "... as follows:"

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/authentication-offline.asciidoc
> +Here is the complete client-side authentication code example with offline support:
* Avoid "here", rather use: "In the following"

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/role-based-access.asciidoc
> +Add a method for checking access for the given route by iterating `rolesAllowed` using `isUserInRole`:
* "... as follows:"

2021-04-14 12:35 UTC, magi42 commented on articles/fusion/security/role-based-access.asciidoc
> +Then use the method added in the route action to redirect on unauthorized access:
* "... as follows:"

2021-04-15 06:58 UTC, haijian-vaadin approved these changes

2021-04-15 08:48 UTC, magi42 requested changes

2021-04-15 08:48 UTC, magi42 commented on articles/fusion/pwa/offline-authentication-check.asciidoc
> +Do you need to protect the local user's data on the device from whoever else may have access to the same device? If that is a requirement, then you will end up adding a `passcode` in addition to the
```suggestion
Do you need to protect the local user's data on the device from whoever else may have access to the same device?
If that is a requirement, you need to add a `passcode` in addition to the regular online login (or use fingerprint/face ID authentication through the WebAuthn API on the devices that support those).
This is what many mobile bank apps do.
```

2021-04-15 08:48 UTC, magi42 commented on articles/fusion/pwa/offline-authentication-check.asciidoc
> +The <<../security/authentication-offline.asciidoc#, Offline Support for Authentication>> article describes how to do that.
```suggestion
The <<../security/authentication-offline#, Offline Support for Authentication>> article describes how to do that.
```

2021-04-15 08:48 UTC, magi42 commented on articles/fusion/security/role-based-access.asciidoc
> +Define an extended type `ViewRoute` that `rolesAllowed` string to enable specifying allowed roles on the view routes:
```suggestion
To enable specifying allowed roles on the view routes, define an extended type `ViewRoute` that has a `rolesAllowed` string as follows:
```

2021-04-16 09:47 UTC, magi42 approved these changes

2021-04-16 12:14 UTC, magi42 approved these changes

2021-04-16 12:21 UTC, merged