Add article for Control Center Development Mode
vaadin/docs pull request #3668
Opened 2024-09-15 13:43 UTC by heruan

This adds documentation on how to run a Vaadin app in development mode with Control Center.

Closes https://github.com/vaadin/control-center/issues/459

2024-09-16 09:58 UTC, MatthewVaadin requested changes
Need to add "Telepresence" to the dictionary.

2024-09-16 09:58 UTC, MatthewVaadin commented on articles/control-center/dev-mode/index.adoc
> +* https://www.telepresence.io/docs/latest/howtos/ports/[Managing Ports with Telepresence]
URL leads to a 404 page. I'm not sure what would replace this.

2024-09-16 11:54 UTC, heruan commented on articles/control-center/dev-mode/index.adoc
> +For detailed installation options, refer to the https://www.telepresence.io/docs/latest/install/cluster/[Telepresence Cluster Installation documentation].
Fixed.

2024-09-16 11:54 UTC, heruan commented on articles/control-center/dev-mode/index.adoc
> +[source,yaml,subs="+quotes,verbatim"]
What do you mean adding a version?

2024-09-16 11:56 UTC, heruan commented on articles/control-center/dev-mode/index.adoc
> +Replace `'my-vaadin-app'` with the actual name of your application and `'control-center'` with the namespace where Control Center is deployed.
We already have some admonitions, I don't want to have too much. Using `my-vaadin-app` should be clear enough to be an example value.

2024-09-16 11:56 UTC, heruan commented on articles/control-center/dev-mode/index.adoc
> +* https://www.telepresence.io/docs/latest/howtos/ports/[Managing Ports with Telepresence]
Fixed all the broken links.

2024-09-16 11:57 UTC, MatthewVaadin commented on articles/control-center/dev-mode/index.adoc
> +[source,yaml,subs="+quotes,verbatim"]
Like we do in (for example) Kubernetes Kit documentation:
```
[.example]
--
.application.properties
[source,properties]
----
vaadin.kubernetes.hazelcast.service-name=hazelcast-service
vaadin.kubernetes.hazelcast.namespace=namespace
----

.application.yaml
[source,yaml]
----
vaadin:
  kubernetes:
    hazelcast:
      service-name: hazelcast-service
      namespace: namespace
----
--
```

2024-09-16 14:47 UTC, heruan commented on articles/control-center/dev-mode/index.adoc
> +[source,yaml,subs="+quotes,verbatim"]
Oh right, I thought you meant adding a version like `vaadin.version=1.2.3` 😅 Done!

2024-09-17 04:51 UTC, MatthewVaadin approved these changes

2024-09-17 04:51 UTC, merged