Improve and restructure Control Center articles
vaadin/docs pull request #3669
Opened 2024-09-15 21:02 UTC by heruan

This improves and restructure the existing Control Center articles, by:

- [x] Merge the overview article with the index page of the section
- [x] Update screenshots in the Getting Started article and rewrite the content to be more elaborated
- [x] Update screenshots in the Application Deployment article and rewrite the content to be more elaborated
- [x] Update screenshots in the Identity Management article and rewrite the content to be more elaborated
- [x] Add an article for the Hostname Guidelines

Closes vaadin/control-center#519

2024-09-16 11:10 UTC, MatthewVaadin requested changes

2024-09-16 11:30 UTC, MatthewVaadin requested changes

2024-09-16 11:30 UTC, MatthewVaadin commented on articles/control-center/index.adoc
> +* **Multi-Factor Authentication (MFA)**: Increase security by enabling MFA, allowing users to authenticate using an authenticator app for an additional layer of protection.
Provide some indication that this feature is premium.

2024-09-16 11:30 UTC, MatthewVaadin commented on articles/control-center/index.adoc
> +== Robust Localization Support
Provide some indication that this feature is premium.

2024-09-16 14:55 UTC, heruan commented on articles/control-center/application-deployment/index.adoc
> +- Building a container image for the application.
Good point. In the overall documentation both are used, but the most used is "Docker image" and it's also more clean to the user I guess. Let's stick with that!

2024-09-16 14:57 UTC, heruan commented on articles/control-center/application-deployment/index.adoc
> +. Select the **Discovery** tab on the left, and then click on the **Deploy** button in the top-right corner of the Application Discovery pane.
Removed.

2024-09-16 14:58 UTC, heruan commented on articles/control-center/getting-started/index.adoc
> +After the installation completes, click the **Go to Dashboard** button. You will be redirected to the Keycloak login page.
Applied.

2024-09-16 14:59 UTC, heruan commented on articles/control-center/getting-started/index.adoc
> +At this point, the dashboard will notify you that no applications are available.
Already addressed.

2024-09-16 15:26 UTC, heruan commented on articles/control-center/index.adoc
> +* **Multi-Factor Authentication (MFA)**: Increase security by enabling MFA, allowing users to authenticate using an authenticator app for an additional layer of protection.
Not sure how to indicate that properly here, in a bulleted list. Premium features would be the external OIDC Provider (not social ones) and MFA. I would leave this for later to add.

2024-09-16 15:27 UTC, heruan commented on articles/control-center/index.adoc
> +== Robust Localization Support
Since this feature is entirely for Premium, I have added the commercial banner in a similar fashion as it's done for other products i.e.

```adoc
:commercial-feature: Localization
include::{articles}/_commercial-banner.adoc[opts=optional]
```

Hope this works also here.

2024-09-17 04:49 UTC, MatthewVaadin requested changes

2024-09-17 04:49 UTC, MatthewVaadin commented on articles/control-center/identity-management/index.adoc
> +image::images/app-selector.png[App Selector]
This image link is broken. The image file is under the application-deployment/images folder.
```suggestion
image::../application-deployment/images/app-selector.png[App Selector]
```

2024-09-17 07:04 UTC, MatthewVaadin approved these changes

2024-09-17 09:40 UTC, merged