Button docs
vaadin/docs pull request #370
Opened 2021-04-15 09:56 UTC by sosa-vaadin

Complete documentation page for vaadin-button along with TS samples.

2021-04-16 09:11 UTC, jouni requested changes

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-disable-long-action.ts
> +      button.disabled = true;
```suggestion
      button.disabled = true;  // <1>
```

Add a noticeable callout here, to make it easier to spot the relevant part of the code.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-disable-long-action.ts
> +        button.disabled = false;
```suggestion
        button.disabled = false;  // <2>
```

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-grid.ts
> +      </div>
Use vaadin-horizontal-layout

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-grid.ts
> +        <h2 style="margin: 0 0 var(--lumo-space-m) 0; font-size: 1.5em; font-weight: bold;">
Should use suitable --lumo-font-size, and rely on the global Lumo typography styles to set the font weight. Margin bottom should be set on the wrapping layout IMO, or use spacing on another wrapping vertical layout.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-grid.ts
> +        ?hidden="${this.selectedItems.length !== 1}"
I would like to keep at least the "Delete" button visible when there are multiple items selected.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-labels.ts
> +          <vaadin-button arial-label="Remove primary email address" @click=${this.clearPrimaryEmail}
Check that quotes are added around all attribute values.

```suggestion
          <vaadin-button arial-label="Remove primary email address" @click="${this.clearPrimaryEmail}"
```

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-labels.ts
> +    const field = this.shadowRoot?.querySelector('#primary-email') as TextFieldElement;
I would assume `internalProperty` would be preferred to explicit DOM access. This applies to other examples as well.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-tertiary-inline.ts
> +      <vaadin-button theme="tertiary-inline">Tertiary Inline</vaadin-button>
```suggestion
      <vaadin-button theme="tertiary-inline">Tertiary inline</vaadin-button>
```

"Sentence case" is used for example UI texts.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-focus.ts
> +      <vaadin-button>Perform Action</vaadin-button>
```suggestion
      <vaadin-button>Perform action</vaadin-button>
```

Use "Sentence case” for example UI texts.

2021-04-16 09:11 UTC, jouni commented on frontend/demo/component/button/button-disable-long-action.ts
> +      <vaadin-button @click=${this.performAction}>Perform Action</vaadin-button>
```suggestion
      <vaadin-button @click=${this.performAction}>Perform action</vaadin-button>
```

2021-04-16 09:32 UTC, tomivirkki requested changes

2021-04-16 09:32 UTC, tomivirkki commented on frontend/demo/component/button/button-disable-long-action.ts
> +  progressBarValue = 0;
```suggestion
  private progressBarValue = 0;
```

2021-04-16 09:32 UTC, tomivirkki commented on frontend/demo/component/button/button-disable-long-action.ts
> +      button.disabled = true;
Rather than manually toggling the button's disabled property, you should bind it to the state of your UI. Quickly looking at the logic, the button should be disabled when the progress isn't running. You could indicate non-started progress for example by having the `progressBarValue` undefined.

So the state binding could looks something like `<vaadin-button .disabled="${this.progressBarValue !== undefined}"`

2021-04-16 09:32 UTC, tomivirkki commented on frontend/demo/component/button/button-disable-long-action.ts
> +      setTimeout(() => {
This second timeout that happens to magically match the timing of the interval (5000 / 25 * 0.005 = 1) looks flaky. Remove the timeout and check if the progress has reached 1.0 inside the interval and then clear itself.

2021-04-16 10:17 UTC, sosa-vaadin commented on frontend/demo/component/button/button-disable-long-action.ts
> +      setTimeout(() => {
Great suggestion! Will implement.

2021-04-16 10:20 UTC, sosa-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +[aA]uto[fF]ocus
Done.

2021-04-16 10:20 UTC, sosa-vaadin commented on articles/ds/components/button/index.asciidoc
> +=== AutoFocus
Done.

2021-04-16 10:20 UTC, sosa-vaadin commented on articles/ds/components/button/index.asciidoc
> +Buttons can be assigned keyboard shortcuts that are either *global*, which work regardless of where focus is currently, or *scoped* to a certain component or container.
Done.

2021-04-16 10:20 UTC, sosa-vaadin commented on articles/ds/components/button/index.asciidoc
> +* The label should clearly indicate the action, preferably using active verbs, such as _"View details"_ rather than just _"Details"_.
Done.

2021-04-16 10:20 UTC, sosa-vaadin commented on frontend/demo/component/button/button-labels.ts
> +          <vaadin-button arial-label="Remove primary email address" @click=${this.clearPrimaryEmail}
Done.

2021-04-16 10:20 UTC, sosa-vaadin commented on frontend/demo/component/button/button-tertiary-inline.ts
> +      <vaadin-button theme="tertiary-inline">Tertiary Inline</vaadin-button>
Done.

2021-04-16 11:32 UTC, sosa-vaadin commented on frontend/demo/component/button/button-labels.ts
> +    const field = this.shadowRoot?.querySelector('#primary-email') as TextFieldElement;
Changed.

2021-04-16 11:33 UTC, sosa-vaadin commented on frontend/demo/component/button/button-disable-long-action.ts
> +  progressBarValue = 0;
Done.

2021-04-16 12:09 UTC, tomivirkki commented on frontend/demo/component/button/button-disable-long-action.ts
> +  private progress: number | undefined = undefined;
```suggestion
  private progress?: number;
```

2021-04-16 12:40 UTC, tomivirkki commented on frontend/demo/component/button/button-focus.ts
> +  }
The purpose is to showcase the component's own focus-ring. See and align with https://vaadin.com/docs/latest/ds/components/input-fields#focus (not that the code should not be visible for the example)

2021-04-16 12:42 UTC, tomivirkki commented on frontend/demo/component/button/button-labels.ts
> +        <vaadin-horizontal-layout theme="spacing">
Separate the compoents for readability. Same applies to all the examples.

```suggestion
        </vaadin-horizontal-layout>
        
        <vaadin-horizontal-layout theme="spacing">
```

2021-04-16 12:58 UTC, sosa-vaadin commented on frontend/demo/component/button/button-focus.ts
> +  }
Removed the css class and added the `focus-ring` attribute to the button example. Also changed the button's label.

2021-04-16 12:59 UTC, sosa-vaadin commented on frontend/demo/component/button/button-labels.ts
> +        <vaadin-horizontal-layout theme="spacing">
Added one empty line between layouts and components that span more than 1 line.

2021-04-16 13:00 UTC, sosa-vaadin commented on frontend/demo/component/button/button-disable-long-action.ts
> +  private progress: number | undefined = undefined;
Changed the list of types for optional parameter syntax.

2021-04-16 13:07 UTC, sosa-vaadin commented on articles/ds/components/button/index.asciidoc
> +
I agree. I'm removing this one.

2021-04-16 13:30 UTC, jouni approved these changes
My concerns were addressed :+1:

2021-04-16 14:03 UTC, tomivirkki commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
Using `&nbsp;` isn't ideal for spacing. The most straightforward solution would be to use a horizontal layout with spacing. It will also be easier to implement in the Java-example in the future.

2021-04-16 14:07 UTC, tomivirkki commented on frontend/demo/component/button/button-focus.ts
> +  }
> note that the code should not be visible for the example

!!!!

2021-04-19 06:26 UTC, rolfsmeds commented on articles/ds/components/button/index.asciidoc
> +=== Prevent Multiple Clicks
I feel that it belongs under "Disabled", as it's about disabling the button in a special way -- they're very closely related, rather than two distinct features.

2021-04-19 06:32 UTC, rolfsmeds commented on frontend/demo/component/button/button-dialog.ts
> +      </div>
Would be good to have a built-in solution for this actually. I'll add it to the notes about introducing dedicated header and footer areas in Dialog. For now though... I suppose we'll just live with it.

2021-04-19 06:38 UTC, sosa-vaadin commented on frontend/demo/component/button/button-focus.ts
> +  }
The code is no longer visible for the example.

2021-04-19 06:39 UTC, sosa-vaadin commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
I removed the spacing but did not add a horizontal layout since it messes up the alignment of the text. This is the result:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/76832183/115192202-29941600-a0f3-11eb-8fe9-02d98b410ad7.png">

2021-04-19 06:56 UTC, tomivirkki commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
Hmm...maybe we should apply a custom align-items property for it, the same as you've used in the button-labels example:

```html
<vaadin-horizontal-layout theme="spacing" style="align-items: baseline">
  <vaadin-button @click=${() => this.counter++}>Vaadin Button</vaadin-button>
  <div>Clicked ${this.counter} times</div>
</vaadin-horizontal-layout>
```

Currently, the spacing still relies on the arbitrary white-space in the HTML:

![Screenshot 2021-04-19 at 9 55 12](https://user-images.githubusercontent.com/1222264/115193872-6103c200-a0f5-11eb-87bd-b3389b6f1be0.png)


With, for example, the Java examples, the white-space isn't there so there would be no spacing either. You can toggle between TS/Java in the [Avatar examples](https://vaadin.com/docs/latest/ds/components/avatar) to see how this manifests.

2021-04-19 10:54 UTC, sosa-vaadin commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
I changed the sample to use a layout similar to the button-labels example.

2021-04-19 10:54 UTC, sosa-vaadin commented on articles/ds/components/button/index.asciidoc
> +[source,html]
Done.

2021-04-19 12:31 UTC, tomivirkki commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
The same issue applies to all the examples that show multiple elements next to each other; they are currently spaced by the whitespace (linebreak) in the HTML. Should use a layout with proper Lumo spacing.

2021-04-19 12:37 UTC, tomivirkki commented on frontend/demo/component/button/button-disable-long-action.ts
> +        style="display: inline-block; width: 350px;"
The fixed 350px width doesn't work on narrow screen devices (the progress bar overflows the example area and creates an unwanted scrollbar):

![Screenshot 2021-04-19 at 15 33 04](https://user-images.githubusercontent.com/1222264/115237078-cc18bd00-a124-11eb-853f-a43de9bbe921.png)

Spotted some layout issues on other examples also:

![Screenshot 2021-04-19 at 15 33 12](https://user-images.githubusercontent.com/1222264/115237250-071af080-a125-11eb-8e59-f851e91dd454.png)

2021-04-19 12:41 UTC, jouni commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
> but did not add a horizontal layout since it messes up the alignment of the text

How does it mess up the alignment?

2021-04-19 12:43 UTC, jouni commented on articles/ds/components/button/index.asciidoc
> +=== Prevent Multiple Clicks
I just thought that by having it as a second level heading makes it appear in the TOC of the page, and easier to discover.

2021-04-19 12:44 UTC, sosa-vaadin commented on frontend/demo/component/button/button-basic.ts
> +      &nbsp; Button has been clicked ${this.counter} times
The text would appear misaligned with regard to the button. A bit higher than the button. Adding the mentioned style and putting the text inside a `div` fixed that issue.

2021-04-19 19:54 UTC, jouni commented on frontend/demo/component/button/button-disable-long-action.ts
> +        style="display: inline-block; width: 350px;"
I provided a suggestion for this in my review. Apparently not all of those were picked up / accepted. 

https://github.com/vaadin/docs/pull/370#discussion_r614674105

2021-04-19 19:55 UTC, jouni commented on frontend/demo/component/button/button-disable-long-action.ts
> +        style="display: inline-block; width: 350px;"
And for the second issue: https://github.com/vaadin/docs/pull/370#discussion_r614664694

2021-04-20 06:03 UTC, sosa-vaadin commented on frontend/demo/component/button/button-disable-long-action.ts
> +        style="display: inline-block; width: 350px;"
I changed both layouts according to @jouni's suggestions.

2021-04-20 09:52 UTC, tomivirkki commented on frontend/demo/component/button/button-grid.ts
> +        ?hidden="${this.selectedItems.length !== 1}"
I think this still hasn't been addressed?

2021-04-20 10:34 UTC, sosa-vaadin commented on frontend/demo/component/button/button-grid.ts
> +        ?hidden="${this.selectedItems.length !== 1}"
The buttons on the left are now in their own `vaadin-horizontal-layout` that only shows when there's 1 item selected. The `Delete` button is in a `div` with `flex-grow: 1` (so the `div` takes all remaining space) that is only hidden if there are no items selected. This shows the same result as it was previously with the added benefit of keeping the "Delete" button visible when there are multiple items selected.

2021-04-20 11:06 UTC, tomivirkki approved these changes

2021-04-20 11:30 UTC, merged