refactor: add simple-import-sort ESLint plugin
vaadin/docs pull request #3703
Opened 2024-09-20 05:51 UTC by vursen

2024-09-20 10:23 UTC, web-padawan requested changes

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/textarea/text-area-basic-features.ts
> -import { customElement } from 'lit/decorators.js';
nit: could also sort imports below alphabetically (text-area after icons).

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/textfield/text-field-basic-features.ts
> -import { customElement } from 'lit/decorators.js';
nit: could also sort imports below alphabetically (text-field after icons).

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/timepicker/time-picker-basic-features.ts
> -import { customElement } from 'lit/decorators.js';
nit: could also sort imports below alphabetically (time-picker after icons).

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/tree-grid/tree-grid-rich-content.ts
> +import { columnBodyRenderer } from '@vaadin/grid/lit.js';
```suggestion
import { columnBodyRenderer, type GridColumnBodyLitRenderer } from '@vaadin/grid/lit.js';
```

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/tree-grid/tree-grid-scroll-to-index.ts
> -import { customElement, query, state } from 'lit/decorators.js';
nit: could also sort imports below (grid after button).

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/component/virtuallist/virtual-list-basic.ts
> +import { virtualListRenderer } from '@vaadin/virtual-list/lit.js';
Could combine this with `import type` above.

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/foundation/lumo-tokens.ts
> +// end::color[]
This comment seems to be off, please move it to where it was.

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/foundation/material-tokens.ts
> +import { colorDark } from '@vaadin/vaadin-material-styles/color'; // hidden-source-line
Same as in Lumo version, the `end: color` seems to be off.

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/fusion/authentication/auth.ts
> +import type UserInfo from 'Frontend/generated/com/vaadin/demo/fusion/security/authentication/UserInfo';
I thnk this import should be inside of `tag::userinfo[]`.

2024-09-20 10:23 UTC, web-padawan commented on frontend/demo/fusion/forms/field-strategy/my-binder.ts
> +import type {
Could combine this with `Binder` import below into single statement.

2024-09-23 07:39 UTC, vursen commented on frontend/demo/component/badge/badge-highlight.ts
> +import type Report from 'Frontend/generated/com/vaadin/demo/domain/Report'; // hidden-source-line
Good point. I think I'll create a separate PR for these changes.

2024-09-23 07:39 UTC, vursen commented on frontend/demo/component/badge/badge-icons-only-table.ts
> +import type UserPermissions from 'Frontend/generated/com/vaadin/demo/domain/UserPermissions'; // hidden-source-line
I'll create a separate PR for these changes.

2024-09-23 07:39 UTC, vursen commented on frontend/demo/component/badge/badge-interactive.ts
> +import { getPeople } from 'Frontend/demo/domain/DataService'; // hidden-source-line
I'll create a separate PR for these changes.

2024-09-23 07:39 UTC, vursen commented on frontend/demo/component/board/example-chart.ts
> +import type ViewEvent from 'Frontend/generated/com/vaadin/demo/domain/ViewEvent'; // hidden-source-line
I'll create a separate PR for these changes.

2024-09-23 07:42 UTC, vursen commented on frontend/demo/component/combobox/combo-box-presentation.ts
> +import { comboBoxRenderer } from '@vaadin/combo-box/lit.js';
I'll create a separate PR for these changes.

2024-09-23 07:54 UTC, vursen commented on frontend/demo/fusion/authentication/auth.ts
> +import type UserInfo from 'Frontend/generated/com/vaadin/demo/fusion/security/authentication/UserInfo';
Good catch, fixed.

2024-09-23 07:54 UTC, vursen commented on frontend/demo/foundation/material-tokens.ts
> +import { colorDark } from '@vaadin/vaadin-material-styles/color'; // hidden-source-line
Good catch, fixed.

2024-09-23 07:54 UTC, vursen commented on frontend/demo/foundation/lumo-tokens.ts
> +// end::color[]
Good catch, fixed.

2024-09-23 07:55 UTC, vursen commented on frontend/demo/fusion/forms/field-strategy/my-binder.ts
> +import type {
I'll create a separate PR for these changes.

2024-09-24 12:22 UTC, vursen commented
Closing in favor of #3714

2024-09-24 12:22 UTC, closed without merging