Brought v14 docs for production mode in par with the latest branch
vaadin/docs pull request #373
Opened 2021-04-15 20:26 UTC by mstahv

2021-04-15 20:27 UTC, mstahv commented
Cherry picking didn't seem like an option so just copy pasted changes from latest branch and left out couple of things that might still be relevant for v14.

2021-04-16 08:00 UTC, jouni commented
Cherry picking should work in general, put I suppose in this case there were some conflicts?

A broken cross reference is failing the build:
> error Broken cross reference /flow/integrations/spring/configuration in guide/production/spring-boot.asciidoc

2021-04-16 08:01 UTC, jouni commented
@magi42, do you wanna have a look? If you spot any issues, I think we should fix those in the latest branch as well.

2021-04-29 12:54 UTC, magi42 approved these changes
Looks rather OK, maybe too much trouble to fix the couple small issues.

2021-04-30 10:04 UTC, jouni commented on articles/guide/production/cloud-providers.asciidoc
> +Even though the deployment itself varies from provider to provider, the <<.#, Production Mode>> article is recommended reading before delving into the tutorials, as it explains some common things, su
I don’t remember exactly, but maybe you can change it to `<<index#, Production Mode>>` instead.

2021-04-30 10:54 UTC, magi42 commented on articles/guide/production/cloud-providers.asciidoc
> +Even though the deployment itself varies from provider to provider, the <<.#, Production Mode>> article is recommended reading before delving into the tutorials, as it explains some common things, su
Ah right, so it's to the index, I was a bit confused about that. Maybe it should be referenced by some other name than an article with the section title. Maybe call it "overview" instead of article here, and have the tab-title "Overview" as well.

2021-04-30 10:55 UTC, magi42 commented on articles/guide/production/cloud-providers.asciidoc
> +Even though the deployment itself varies from provider to provider, the <<.#, Production Mode>> article is recommended reading before delving into the tutorials, as it explains some common things, su
```suggestion
Even though the deployment itself varies from provider to provider, the <<.#, Production Mode>> overview is recommended reading before delving into the tutorials, as it explains some common things, such as what a production build is and how to do such a build.
```

2021-04-30 10:56 UTC, magi42 commented on articles/guide/production/index.asciidoc
> +tab-title: Production Mode
```suggestion
tab-title: Overview
```

2021-05-04 16:19 UTC, magi42 approved these changes

2021-05-04 16:19 UTC, magi42 commented on articles/guide/production/spring-boot.asciidoc
> +See <<{articles}/flow/integrations/spring/configuration#using-spring-boot-properties,Using Spring Boot Properties>> for additional details.
```suggestion
See <<{articles}/flow/integrations/spring/tutorial-spring-configuration#using-spring-boot-properties,Using Spring Boot Properties>> for additional details.
```

2021-05-05 11:50 UTC, magi42 requested changes
Couple of tiny changes.

2021-05-05 11:50 UTC, magi42 commented on articles/guide/production/spring-boot.asciidoc
>  - no need for a server binary install, a Java Runtime is all that is needed
```suggestion
- No need for a server binary install, a Java Runtime is all that is needed.
```

2021-05-05 11:50 UTC, magi42 commented on articles/guide/production/spring-boot.asciidoc
>  - bigger package size
```suggestion
- Bigger package size.
```

2021-05-07 15:22 UTC, magi42 approved these changes

2021-05-07 15:24 UTC, merged