Document how to deploy Control Center with a custom ingress
vaadin/docs pull request #3754
Opened 2024-10-01 06:41 UTC by tamasmak

This documents how to deploy Control Center with a custom ingress configuration and separates the instructions into development and production environment parts.

2024-10-01 07:30 UTC, MatthewVaadin requested changes
Address Vale comments

2024-10-01 07:30 UTC, MatthewVaadin commented on articles/control-center/getting-started/index.adoc
> +<4> Configures a custom ingress configuration (see  below)
```suggestion
<4> Configures a custom ingress configuration (see below)
```

2024-10-01 07:57 UTC, MatthewVaadin approved these changes

2024-10-04 19:35 UTC, jojule commented on articles/control-center/getting-started/index.adoc
> +      secretName: "control-center-tls"
If I do have such a certificate, how do I share the secret? (lets document that)

2024-10-04 19:36 UTC, jojule commented on articles/control-center/getting-started/index.adoc
> +  tls:
I likely do not have a certificate yet. Thus I should probably redirect local port to communicate securely with control center at installation phase? Documentation needed.

2024-10-04 19:37 UTC, jojule commented on articles/control-center/getting-started/index.adoc
> +helm install control-center oci://docker.io/vaadin/control-center \ # (1)
Should I `--set service.type=LoadBalancer` to get cluster assigning an IP for it?

2024-10-04 19:44 UTC, jojule requested changes
Documentation seems incomplete (see comments), but even addressing these there is a related [blocker](https://github.com/vaadin/control-center/issues/645)

2024-10-11 09:21 UTC, heruan commented on articles/control-center/getting-started/index.adoc
> +helm install control-center oci://docker.io/vaadin/control-center \ # (1)
For production you should prefer to create a `Ingress` where you can specify also a certificate. Most cloud providers allow to reserve an IP address on before hand for an Ingress, e.g. in Google Cloud you add this annotation to use a reserved IP address:
```
kubernetes.io/ingress.global-static-ip-name: "my-static-ip"
```

2024-10-11 09:26 UTC, heruan commented on articles/control-center/getting-started/index.adoc
> +  tls:
If you're deploying to production, you probably have a certificate already. If you're not deploying to production, you can create one with a tool like `mkcert`:
```
mkcert control-center.example.com
```
Let's document this.

2024-10-11 09:28 UTC, heruan commented on articles/control-center/getting-started/index.adoc
> +      secretName: "control-center-tls"
Agree, let's document how to create a secret for the certificate:
```
kubectl create secret tls control-center-tls --cert=cert.pem --key=key.pem
```

2024-10-11 09:29 UTC, heruan commented
> Documentation seems incomplete (see comments), but even addressing these there is a related [blocker](https://github.com/vaadin/control-center/issues/645)

This happens only if you install with a port forward, should be addressed at some point by I wouldn't consider it a blocker.

2024-10-14 11:04 UTC, tamasmak commented on articles/control-center/getting-started/index.adoc
> +  tls:
I documented how to create a certificate.

2024-10-25 06:43 UTC, merged