Changed http links to https in the v23 branch
vaadin/docs pull request #3793
Opened 2024-10-10 10:00 UTC by edler-san

2024-10-10 12:05 UTC, manolo approved these changes

2024-10-10 12:08 UTC, manolo commented on articles/configuration/node-js.asciidoc
> +https-proxy=https://myusername:s3cr3tpassw0rd@proxyserver1:8086"
I dont think this might work, probably 8085 and 8086 ports are not proper https services but http

2024-10-10 12:09 UTC, manolo requested changes

2024-10-10 12:09 UTC, manolo commented on articles/configuration/node-js.asciidoc
> +https-proxy=https://myusername:s3cr3tpassw0rd@proxyserver1:8086"
Actually there are multiple `:80*` coincidences from here, they should be kept in http

2024-10-15 11:48 UTC, edler-san commented on articles/configuration/node-js.asciidoc
> +https-proxy=https://myusername:s3cr3tpassw0rd@proxyserver1:8086"
Reverted those

2024-10-22 07:42 UTC, merged