feat: add initial Full-stack Signals documentation
vaadin/docs pull request #3797
Opened 2024-10-10 15:58 UTC by taefi

Part of #3762

2024-10-16 15:48 UTC, cromoteca requested changes

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +When building a modern web application, you often need to synchronize the state between the server and clients. For example, you might want to notify all connected clients in a chat application when
The three examples are a when, a verb and another when, there's no consistency.
Check "when you this updates".
Real-time is not an adjective here, so no dash.

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +A full-stack signal can be seen as a special data-type that holds the shared state, and enables the clients to subscribe to it for receiving real-time updates when the state changes. The state can be
```suggestion
A full-stack signal can be seen as a special data type that holds the shared state, and enables the clients to subscribe to it for receiving real-time updates when the state changes. The state can be updated by any client, and the changes are automatically propagated to all other clients that are subscribed to the signal.
```

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +At the moment, the implementation of full-stack signals are only available for Vaadin Hilla applications that use the **React** library for rendering the user interfaces.
```suggestion
At the moment, the implementation of full-stack signals is only available for Vaadin Hilla applications that use the **React** library to render the user interfaces.
```

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +The purpose of a full-stack signal is to share and synchronize the state between the server and clients in real-time. In Vaadin Hilla applications, you can do that by creating an instance of one of t
```suggestion
The purpose of a full-stack signal is to share and synchronize the state between the server and clients in real time. In Vaadin Hilla applications, you can do that by creating an instance of one of the available full-stack signal types and returning it from your [classname]`@BrowserCallable` annotated services. In the following example an instance of a [classname]`ValueSignal` is created and returned from a server-side endpoint:
```
The word "endpoint" should be avoided.

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +<3> Toggling (changing) the state by setting the `value` property of the signal.
```suggestion
<3> Toggle (change) the state by setting the `value` property of the signal.
```

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +The full-stack signals are designed to be used in various scenarios, and based on the requirement different types of full-stack signals are used. The server-side signal types are available in the `co
```suggestion
The full-stack signals are designed to be used in various scenarios, and based on the requirement different types of full-stack signals are used. The server-side signal types are available in the `com.vaadin.hilla.signals` package, and their client-side counterparts are available in `@vaadin/hilla-react-signals`. As this is currently under active development, more signal types are added at each new release, but, at the moment, the available ones are:
```

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +<1> Subscribe to the `started` signal and set the default value to `false`.
I'd explain that this default value is for this client and not sent to the server.

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +<1> Subscribing to the `sharedPerson` signal and setting the default value to an empty person. This client-side default value is used when rendering the component before the first update from the ser
This is the explanation I was expecting above. It is probably redundant to duplicate, so we should make a choice about where to explain it. Other notes are partially duplicated too.

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +- `replace(expected: T, newValue: T): void`: Replaces the value with a new one only if the current value is equal to the expected value. This means that a state change request is sent to the server a
```suggestion
- `replace(expected: T, newValue: T): void`: Replaces the value with a new one only if the current value is equal to the expected value. This means that a state change request is sent to the server asking it to _"compare and set"_. At the time of processing this requested change on the server, if the current value is not equal to the expected value, the update is rejected by the server.
```

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +- `update(updater: (current: T) => T): OperationSubscription`: Tries to update the value by applying the callback function to the current value. When the new value is calculated, a "compare and set"
It can be useful to underline that the "compare and set" is based on Java equality, so the value class should implement it.

2024-10-16 15:48 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +As [classname]`NumberSignal` is a [classname]`ValueSignal` only with additional atomic operations, it inherits all the methods such as `replace` and `update`, so if there is no need for supporting at
Isn't `replace` atomic also? Can the value change between compare and set?

2024-10-16 17:02 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +              >{votingStarted.value ? 'Stop' : 'Start'} Voting
Let's use comments to render callouts properly:

```suggestion
      <span>Is voting in progress: {votingStarted.value ? 'Yes' : 'No'}</span> {/* <2> */}
      <Button
        onClick={() => (votingStarted.value = !votingStarted.value) /* <3> */}
        theme={votingStarted.value ? 'error' : ''}
      >
        {votingStarted.value ? 'Stop' : 'Start'} Voting
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +                    new ValueSignal<>(false, Boolean.class); <1>
```suggestion
                    new ValueSignal<>(false, Boolean.class); // <1>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +        return started; <2>
```suggestion
        return started; // <2>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +          PersonService.sharedPerson({ defaultValue: { name: '', age: 0 } }); <1>
```suggestion
          PersonService.sharedPerson({ defaultValue: { name: '', age: 0 } }); // <1>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +      <span>Name: {sharedPerson.value.name}</span> <2>
```suggestion
      <span>Name: {sharedPerson.value.name}</span> {/* <2> */}
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +          sharedPerson.value = { <3>
```suggestion
         sharedPerson.value = { // <3>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +    private final NumberSignal counter = new NumberSignal(1.0); <1>
```suggestion
    private final NumberSignal counter = new NumberSignal(1.0); // <1>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +    public NumberSignal counter() { <2>
```suggestion
    public NumberSignal counter() { // <2>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +const counter = CounterService.counter(); <1>
```suggestion
const counter = CounterService.counter(); // <1>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +      <Button onClick={() => counter.value = 0}>Reset</Button> <5>
```suggestion
      <span>Counter: {counter}</span> {/* <2> */}
      <Button onClick={() => counter.incrementBy(5)}>Increase by 5</Button> {/* <3> */}
      <Button onClick={() => counter.incrementBy(-3)}>Decrease by 3</Button> {/* <4> */}
      <Button onClick={() => counter.value = 0}>Reset</Button> {/* <5> */}
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +    public NumberSignal voteOptionSignal(String option) { <1>
```suggestion
    public NumberSignal voteOptionSignal(String option) { // <1>
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +import { Button } from "@vaadin/react-components/Button.js";
```suggestion
import { Button, VerticalLayout } from '@vaadin/react-components';
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +import { CounterService } from "Frontend/generated/endpoints.js";
```suggestion
import { CounterService } from 'Frontend/generated/endpoints.js';
```

2024-10-16 17:25 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +import { VerticalLayout } from "@vaadin/react-components/VerticalLayout.js";
```suggestion
import { Button, VerticalLayout } from '@vaadin/react-components';
```

2024-10-16 17:31 UTC, web-padawan commented on articles/hilla/guides/full-stack-signals.adoc
> +import type Person from "Frontend/generated/com/example/application/services/PersonService/Person.js";
```suggestion
import { ValueSignal } from '@vaadin/hilla-react-signals';
import { PersonService } from 'Frontend/generated/endpoints.js';
import type Person from 'Frontend/generated/com/example/application/services/PersonService/Person.js';
```

2024-10-17 07:47 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +As [classname]`NumberSignal` is a [classname]`ValueSignal` only with additional atomic operations, it inherits all the methods such as `replace` and `update`, so if there is no need for supporting at
Well, the usage of the word "atomic" was a bit unfortunate maybe. The server-side block of code that is responsible for applying all the operations is blocking, so a `replace` also compare and set the value atomically.

But, what is different for `incrementBy` operation is that no current value is sent to the server based on the client-side "current" state, so even reading of current value of and applying the change on top of it is done in the same blocking code. so there's no chance of failure for "incrementBy", but a "replace" could be rejected.

Maybe we can call it "special" operation. I'm open to ideas.

2024-10-17 07:51 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +- `update(updater: (current: T) => T): OperationSubscription`: Tries to update the value by applying the callback function to the current value. When the new value is calculated, a "compare and set"
I was a bit hesitant to include it due to the on-going discussion we had around the idea of holding the initial value as JSON instead, and the impact it has on the way of checking equality. But, since this feature is behind a feature flag, behavioural changes like this could be acceptable(?)

2024-10-17 07:53 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +<1> Subscribing to the `sharedPerson` signal and setting the default value to an empty person. This client-side default value is used when rendering the component before the first update from the ser
I'd move it to the comment on the above, and remove it from here.

2024-10-17 08:40 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +As [classname]`NumberSignal` is a [classname]`ValueSignal` only with additional atomic operations, it inherits all the methods such as `replace` and `update`, so if there is no need for supporting at
I "discussed" this topic with ChatGPT and its final proposal is:

- `replace` is a "conditional atomic operation" (or "strict atomic operation");
- `incrementBy` is an "incremental atomic operation" (or "progressive atomic operation"), and `update` should also be one of those.

I like "conditional" and "incremental" more than the alternatives.

2024-10-17 10:48 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +As [classname]`NumberSignal` is a [classname]`ValueSignal` only with additional atomic operations, it inherits all the methods such as `replace` and `update`, so if there is no need for supporting at
I avoided using the the "conditional atomic" since it sounded a bit confusing whether it refers to "a conditional atomicity when the change is applied" or "an atomic operation that can succeed conditionally". But, adopted the "incremental" one. Rephrased the sentences in multiple places of the document (e.g. in setting the value part of ValueSignal section), and removed the unnecessary confusing stuff from the above sentence. Hope it's better now.

2024-10-17 10:48 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +- `update(updater: (current: T) => T): OperationSubscription`: Tries to update the value by applying the callback function to the current value. When the new value is calculated, a "compare and set"
Added.

2024-10-17 10:48 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +<1> Subscribing to the `sharedPerson` signal and setting the default value to an empty person. This client-side default value is used when rendering the component before the first update from the ser
done.

2024-10-17 10:48 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +<1> Subscribe to the `started` signal and set the default value to `false`.
done.

2024-10-17 10:49 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +When building a modern web application, you often need to synchronize the state between the server and clients. For example, you might want to notify all connected clients in a chat application when
done.

2024-10-17 14:56 UTC, cromoteca requested changes

2024-10-17 14:56 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +Full-stack signals are still under active development and is not yet suitable for production use. Thus, to use them in your Vaadin projects, you need to explicitly enable the experimental feature in
```suggestion
Full-stack signals are still under active development and are not yet suitable for production use. Thus, to use them in your Vaadin projects, you need to explicitly enable the experimental feature in Copilot, or by manually adding `com.vaadin.experimental.fullstackSignals=true` to the [filename]`src/main/resources/vaadin-featureflags.properties` file.
```

2024-10-17 14:56 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +For a client to receive real-time updates when the state of a full-stack signal changes, it needs to subscribe to the signal. This can be done as simple as calling any normal Vaadin endpoint. The fol
Avoid using "endpoint".

2024-10-17 14:56 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +Having a [classname]`@BrowserCallable` annotated service with a method that returns a [classname]`ValueSignal` instance similar to the above example, enables the client-side code to subscribe to it b
```suggestion
Having a [classname]`@BrowserCallable`-annotated service with a method that returns a [classname]`ValueSignal` instance similar to the above example, enables the client-side code to subscribe to it by calling the service method:
```

2024-10-18 08:02 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +For a client to receive real-time updates when the state of a full-stack signal changes, it needs to subscribe to the signal. This can be done as simple as calling any normal Vaadin endpoint. The fol
Done.

2024-10-22 07:46 UTC, cromoteca approved these changes

2024-10-22 07:49 UTC, merged