chore: Add a link to Playwright examples with Vaadin 24
vaadin/docs pull request #3813
Opened 2024-10-16 08:59 UTC by mshabarov

We recently updated the hybrid example project to use Playwright, would be nice to share these insights publicly.

2024-10-17 09:07 UTC, edler-san requested changes

2024-10-17 09:07 UTC, edler-san commented on articles/flow/testing/playwright.adoc
> +Also see Vaadin Hybrid example project in https://github.com/vaadin/flow-hilla-hybrid-example/tree/v24[GitHub] that gives hands-on examples for testing Vaadin UI written in https://github.com/vaadin/
Either 'testing Vaadin UIs' or 'testing a Vaadin UI' imho.

2024-10-17 09:28 UTC, mshabarov commented on articles/flow/testing/playwright.adoc
> +Also see Vaadin Hybrid example project in https://github.com/vaadin/flow-hilla-hybrid-example/tree/v24[GitHub] that gives hands-on examples for testing Vaadin UI written in https://github.com/vaadin/
Done, thanks!

2024-11-19 10:06 UTC, jouni approved these changes

2024-11-19 10:08 UTC, jouni commented
@edler-san, please don't remove the "Language unchecked" label/tag. We use it to keep track of PRs that haven't gone through language review.

2024-11-19 10:08 UTC, merged