Add instructions for production installation of Control Center
vaadin/docs pull request #3820
Opened 2024-10-17 06:56 UTC by MatthewVaadin

This adds a page that details how to manually install Control Center's prerequisites without using a cluster-wide admin role.

2024-10-17 09:26 UTC, edler-san requested changes

2024-10-17 09:26 UTC, edler-san commented on articles/control-center/getting-started/production-installation.adoc
> +This guide explains how to install Control Center in a production environment, specifically how to install the required dependencies and Control Center itself without utilizing cluster-wide admin per
"admin permissions" sounds a tad colloquial, maybe "administrator" or "administrative" permissions instead - up to the author :)

2024-10-17 09:26 UTC, edler-san commented on articles/control-center/getting-started/production-installation.adoc
> +Now that the dependencies are installed, you can proceed to install Control Center. To do this without cluster-wide admin privileges, run the following Helm command:
"admin permissions" sounds a tad colloquial, maybe "administrator" or "administrative" permissions instead - up to the author :)

2024-10-17 09:26 UTC, edler-san commented on articles/control-center/getting-started/index.adoc
> +Granting cluster-wide administrative privileges enables automatic installation of required dependencies. If you choose not to grant these privileges, though, you'll need to install necessary resource
_the_ automatic installation of _the_ required...
Maybe 'automated' instead of 'automatic'.
install _the_ necessary resources...
No comma before _manually_.

2024-11-01 11:02 UTC, tamasmak commented on articles/control-center/getting-started/production-installation.adoc
> +== Keycloak
Do we need instructions for the Keycloak? The [ticket](https://github.com/vaadin/control-center/issues/608) mentions that it is not needed because the Keycloak Operator can still be installed by Control Center without cluster-wide admin privileges, since it's scoped to the target namespace.

2024-11-04 07:23 UTC, MatthewVaadin commented on articles/control-center/getting-started/production-installation.adoc
> +== Keycloak
Some of the resources created (CRDs, ClusterRole) are not namespaced and can't be installed by CC with the current permissions.

2024-11-04 07:58 UTC, tamasmak commented on articles/control-center/getting-started/production-installation.adoc
> += Production Installation
Should we change the `<<production-installation#,Production Installation>>` page and file names to `<<manual-installation#,Manual Installation>>` [here](https://github.com/vaadin/docs/pull/3820/files#diff-15dda06831f3b89eebec430141add4ee277dd82bb29bfec6b0deee37ce769397R65) and [here](https://github.com/vaadin/docs/pull/3820/files#diff-15dda06831f3b89eebec430141add4ee277dd82bb29bfec6b0deee37ce769397R87)?

2024-11-04 09:28 UTC, tamasmak approved these changes

2024-11-05 08:26 UTC, merged

2024-11-19 10:21 UTC, jouni commented
I’m sure Matthew has the English language covered, but I’d like @russelljtdyer to go through the formatting and writing style.