feat: add ListSignal section to the Signals documentation
vaadin/docs pull request #3844
Opened 2024-10-23 15:42 UTC by taefi

2024-10-24 09:26 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +The [classname]`ListSignal<T>` is a full-stack signal that holds a list of values of an arbitrary type. The type should necessarily be a JSON-serializable one that is supported by the Hilla framework
While not strictly related, I wonder if adhering to the [RFC keywords specification](https://www.rfc-editor.org/rfc/rfc2119) (without uppercase, of course) could be a good rule of thumb in documentation. @russelljtdyer what do you think?

2024-10-24 09:31 UTC, cromoteca commented on articles/hilla/guides/full-stack-signals.adoc
> +The client-side APIs of the [classname]`ListSignal` provides methods to insert and remove items. The [classname]`ListSignal` is a sequential organization of [classname]`ValueSignal` entries. Therefor
```suggestion
The client-side APIs of the [classname]`ListSignal` provides methods to insert and remove items. The [classname]`ListSignal` is a sequence of [classname]`ValueSignal` entries. Therefore, its APIs are about how the entries are added to or removed from the list, and how the concurrent operations regarding the structure of the entries is handled.
```
Also, I think that API is supposed to be singular in this context.

2024-11-20 09:08 UTC, cromoteca requested changes

2024-11-20 09:12 UTC, taefi commented on articles/hilla/guides/full-stack-signals.adoc
> +When building a modern web application, you may often need to synchronize the state between the server and clients. You might want to notify all connected clients in a chat application when a new mes
I believe this change was part of the language checking changes, but anyway, your suggestion clearly makes sense.

2024-11-20 09:36 UTC, merged