Update Live reload configuration page to include Copilot
vaadin/docs pull request #3924
Opened 2024-11-18 15:05 UTC by MarcinVaadin

Fixes: https://github.com/vaadin/copilot-internal/issues/3838

2024-11-18 15:06 UTC, MarcinVaadin commented
> Would make sense to have the live reload docs in Copilot instead and refer to that

@Artur- do you still think all of those subpages should be moved to Copilot? They are pretty generic and IMO fit in Configuration section.

I've updated pages to include information about Copilot.

2024-11-25 09:00 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +== Using Vaadin Copilot and Vaadin IDE Plugin
the page should start from the preferred way, not from a manual way mostly don't need

2024-12-04 07:34 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +=== `HotSwapAgent`
I think only the logo use a capital S and everywhere else the name is written as `HotswapAgent`

2024-12-04 07:35 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +=== `HotSwapAgent`
```suggestion
=== `HotswapAgent`
```

2024-12-04 07:35 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +You can download HotSwapAgent from the https://github.com/HotswapProjects/HotswapAgent/releases[HotswapAgent GitHub release page]. You'll need version 1.4.2 or later.
```suggestion
You can download HotswapAgent from the https://github.com/HotswapProjects/HotswapAgent/releases[HotswapAgent GitHub release page]. You'll need version 1.4.2 or later.
```

2024-12-04 16:44 UTC, Artur- requested changes

2024-12-04 16:44 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +Vaadin IDE Plugin also provides a *Compile on save* option, which can be enabled in the IDE settings. This may differ depending on your IDE.
And what does this thing that may or may not exist do, and how is it related to hotswapping and HotswapAgent?

2024-12-04 16:44 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +When debugging applications using *Debug using HotSwap Agent* from Vaadin IDE, the plugin checks if you're using the proper JDK, if HotSwap Agent is available, and applies additional required JVM arg
There is nothing called "Vaadin IDE" so this and below need to be rephrased

2024-12-04 16:44 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +Depending on your project and the IDE used, Copilot can download the proper version of JDK and suggest a Vaadin plugin for your IDE.
This sounds super vague, like "maybe if you have some project and some IDE, then something might do something". Can we say more like "If you are using IntelliJ and the Vaadin plugin, you can launch your application using the 'Debug using HotswapAgent' option without any additional configuration"

2024-12-04 16:44 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +All of the above can be done automatically using Vaadin Copilot together with Vaadin IDE Plugin.
But you don't need Vaadin Copilot for this at all?

2024-12-04 16:45 UTC, Artur- commented on articles/flow/configuration/live-reload/hotswap-agent.adoc
> +Depending on your project and the IDE used, Copilot can download the proper version of JDK and suggest a Vaadin plugin for your IDE.
If we want to mention the VS Code plugin also, then mention that also specifically

2024-12-12 16:38 UTC, Artur- approved these changes

2024-12-13 08:10 UTC, merged