feat: Design System Publisher documentation
vaadin/docs pull request #394
Opened 2021-04-22 12:21 UTC by jouni

Resolves https://github.com/vaadin/docs-app/issues/107

2021-04-23 08:09 UTC, tomivirkki approved these changes

2021-04-23 13:25 UTC, magi42 requested changes

2021-04-23 13:25 UTC, magi42 commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +To speed up the start process the Design System Publisher caches some resources internally.
```suggestion
To speed up the start process, the Design System Publisher caches some resources internally.
```

2021-04-23 13:25 UTC, magi42 commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +But if you use “layout: tabbed-page” in the page front-matter, the tabbed page heading is actually obtained from the front-matter's title field so you need to update that instead.
I noticed that in several places these unusual double quotes are used: “layout: tabbed-page”. Maybe it's better to avoid those, as normal quotes are used almost everywhere.

2021-04-23 13:25 UTC, magi42 commented on articles/tools/dspublisher/ui-examples.asciidoc
> +Examples of Java based components (for the Flow framework) are placed in sub-folders inside [filename]#src/main/java/com/vaadin/demo/component#.
```suggestion
Examples of Java-based components (for the Flow framework) are placed in sub-folders inside [filename]#src/main/java/com/vaadin/demo/component#.
```

2021-04-23 13:25 UTC, magi42 commented on articles/tools/dspublisher/ui-examples.asciidoc
> +Whenever changes to a TypeScript example are saved, Publisher rebuilds the example and automatically refresh the page after a couple of seconds.
```suggestion
Whenever changes to a TypeScript example are saved, Publisher rebuilds the example and automatically refreshes the page after a couple of seconds.
```

2021-04-23 13:25 UTC, magi42 commented on articles/tools/dspublisher/ui-examples.asciidoc
> +For TypeScript examples this means that code tagged with `[source,html]` must use HTML comments within an HTML literal in the code.
```suggestion
For TypeScript examples, this means that code tagged with `[source,html]` must use HTML comments within an HTML literal in the code.
```

2021-04-23 13:38 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +|Width of the page sidebar / TOC
Or just "table of contents" in full

2021-04-23 13:42 UTC, jouni commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +To speed up the start process the Design System Publisher caches some resources internally.
Should we use "the" here? Should it rather just be "…start process, Design System Publisher caches some…"?

2021-04-23 13:42 UTC, jouni commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +But if you use “layout: tabbed-page” in the page front-matter, the tabbed page heading is actually obtained from the front-matter's title field so you need to update that instead.
Yes, agreed. I actually have a pending commit that changes these across the whole repo (from smart quotes to dumb quotes).

2021-04-23 13:58 UTC, magi42 commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +To speed up the start process the Design System Publisher caches some resources internally.
I think so, it doesn't seem to fall to any exceptions to using an article. I suppose you could also say: "To speed up starting the service" or something like that.

2021-04-23 14:03 UTC, jouni commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +But if you use “layout: tabbed-page” in the page front-matter, the tabbed page heading is actually obtained from the front-matter's title field so you need to update that instead.
Oh, actually, I assumed AsciiDoctor would transform these double quotes automatically (from dumb to smart), but apparently you need to use a special syntax if you want smart quotes: https://docs.asciidoctor.org/asciidoc/latest/text/quotation-marks-and-apostrophes/

In that case, I would rather keep these. But not in this particular case, as these are marking source code snippets. I’ll update this article.

2021-04-23 14:09 UTC, magi42 commented on articles/tools/dspublisher/troubleshooting.asciidoc
> +But if you use “layout: tabbed-page” in the page front-matter, the tabbed page heading is actually obtained from the front-matter's title field so you need to update that instead.
Ah, didn't know about the smart quote syntax. Maybe it can't be used if you want to have code inside double quotes like "`foo`". But normally you don't use double quotes for those.

2021-04-23 14:10 UTC, jouni commented on articles/tools/dspublisher/custom-theme.asciidoc
> +.Application Theme vs Website Theme
Oh, yes, that’s what we’ve used in other places.

2021-04-23 14:11 UTC, jouni commented on articles/tools/dspublisher/custom-theme.asciidoc
> +.Application Theme vs Website Theme
```suggestion
.Application theme vs website theme
```

2021-05-03 09:39 UTC, rolfsmeds requested changes

2021-05-03 13:27 UTC, jouni commented on articles/tools/dspublisher/editing.asciidoc
> +|image::path/to/image.png[Alt text]
I thought it would be fine like this, that you get the idea how to show an image. But sure, could add a dummy image.

2021-05-03 13:29 UTC, jouni commented on articles/tools/dspublisher/custom-theme.asciidoc
> += Applying a Custom Design System Theme
Maybe we reserve the term “theme” just for the Vaadin theme, and use some other terminology for the docs website “styling”?

2021-05-03 13:31 UTC, jouni commented on articles/tools/dspublisher/start.asciidoc
> +
Yeah, I omitted that on purpose. Sorry for not mentioning it explicitly. To me, it feels out of place. The commercial/license part is already mentioned in the Overview, with a link to start a license. Also, I believe you get a notice if you try to use the tool without a license, so I’m not sure why we need it here again. IMO it makes it hard for us to maintain the docs, as there are so many places to update if our trial flow changes.

2021-05-03 13:33 UTC, jouni commented on articles/tools/dspublisher/start.asciidoc
> +
Also, I noticed that you likely copied the instructions from Designer docs. We should likely have this trial/license flow documented, but I would put it somewhere under "Get Started” which we can refer to from other docs, and not duplicate it.

2021-05-03 13:33 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +The website's theme can be defined in the [filename]#global.css# stylesheet in the [filename]#dspublisher/docs-theme# folder.
```suggestion
The website's theme can be defined in the [filename]#global.css# style sheet in the [filename]#dspublisher/docs-theme# folder.
```

2021-05-03 13:34 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +|Max width of the page's body (excluding sidebar/TOC)
```suggestion
|Max width of the page's body (excluding sidebar/table of contents)
```

2021-05-03 13:36 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +You can add custom content inside the top header using the "[filename]#dspublisher/docs-theme/header.ts#" file.
```suggestion
You can use the empty top-level header element (`<dspublisher-header>`) on the documentation site, above the application header, to add custom content inside it using the "[filename]#dspublisher/docs-theme/header.ts#" file.
```

2021-05-03 13:36 UTC, jouni commented on articles/tools/dspublisher/editing.asciidoc
> +To add a new component page, create a folder inside [filename]#articles/ds/components", add a new [filename]#index.asciidoc# file inside it, and configure its metadata.
```suggestion
To add a new component page, create a folder inside [filename]#articles/ds/components#, add a new [filename]#index.asciidoc# file inside it, and configure its metadata.
```

2021-05-04 19:53 UTC, rolfsmeds commented on articles/tools/dspublisher/start.asciidoc
> +
Ok, makes sense.

2021-05-04 19:54 UTC, rolfsmeds commented on articles/tools/dspublisher/editing.asciidoc
> +|image::path/to/image.png[Alt text]
Yeah I mean it looks like the docs are broken :)
Or just omit the example altogether.

2021-05-04 19:54 UTC, rolfsmeds commented on articles/tools/dspublisher/custom-theme.asciidoc
> += Applying a Custom Design System Theme
That's actually a good idea! Needs changes in multiple places unfortunately.

2021-05-06 12:09 UTC, tomivirkki commented on articles/tools/dspublisher/start.asciidoc
> +vaadin ds-init
```suggestion
vaadin dsp-init
```

2021-05-24 11:39 UTC, rolfsmeds commented on articles/tools/dspublisher/custom-theme.asciidoc
> += Applying a Custom Design System Theme
I would still rename this to "application theme"

2021-05-24 11:43 UTC, rolfsmeds approved these changes

2021-05-24 11:43 UTC, rolfsmeds commented on articles/tools/dspublisher/custom-theme.asciidoc
> +A design system theme is used from a Maven repository, such as Maven Central or a local repository.
Would still call this "application theme"

2021-05-25 12:40 UTC, jouni commented on articles/tools/dspublisher/custom-theme.asciidoc
> += Applying a Custom Design System Theme
```suggestion
= Applying a Custom Application Theme
```

2021-05-25 12:40 UTC, jouni commented on articles/tools/dspublisher/custom-theme.asciidoc
> +A design system theme is used from a Maven repository, such as Maven Central or a local repository.
```suggestion
An application theme is used from a Maven repository, such as Maven Central or a local repository.
```

2021-05-25 12:40 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +A <<custom-theme#,custom design system theme>> can also be applied, which affects the theme of rendered UI examples within the documentation pages.
```suggestion
A <<custom-theme#,custom application theme>> can also be applied, which affects the theme of rendered UI examples within the documentation pages.
```

2021-05-25 12:40 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +.Design system theme
```suggestion
.Application theme
```

2021-05-25 12:40 UTC, jouni commented on articles/tools/dspublisher/customization.asciidoc
> +See <<custom-theme#,Applying a Custom Design System Theme>> for instructions how to apply a theme which is used in <<ui-examples#,UI examples>>.
```suggestion
See <<custom-theme#,Applying a Custom Application Theme>> for instructions how to apply a theme which is used in <<ui-examples#,UI examples>>.
```

2021-05-25 12:43 UTC, merged