docs: enhance dialog component documentation with positioning and sizing details
vaadin/docs pull request #3946
Opened 2024-11-25 14:23 UTC by DiegoCardoso

Create new "Position" and "Size" sections and move "Draggable" and "Rezizable" sections to the corresponding ones. 

Also add code snippets showing the new API for programmatically sizing and positioning.

2024-11-26 13:32 UTC, vursen commented on articles/components/dialog/index.adoc
> +=== Position
```suggestion
== Position
```

Otherwise it doesn't appear in the navigation menu:

![image](https://github.com/user-attachments/assets/652df66d-73f9-48ad-bced-09cf6405c46f)

2024-11-26 13:32 UTC, vursen commented on articles/components/dialog/index.adoc
> +. By allowing the user to drag them (see <<Draggable>>)
This gave me the impression that these two ways are mutually exclusive, but that's not the case, if I understand correctly. You can set the initial position using the `top` and `left` properties and still enable dragging, right? The same goes for resizing.

2024-11-27 07:45 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +. By allowing the user to drag them (see <<Draggable>>)
Yeah, both cases can work at the same time. I don't have the same impression, but I can be a bit biased. I can try to improve it to remove any misunderstanding.

2024-11-27 07:46 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +=== Position
Thanks!

2024-11-29 06:48 UTC, rolfsmeds requested changes

2024-11-29 06:48 UTC, rolfsmeds commented on articles/components/dialog/index.adoc
> +. By allowing the user to drag them (see <<Draggable>>)
Not sure if I'm getting a mutually exclusive impression, but it does feel a bit strange to present those as two parallel options. How about something like this instead?

```suggestion
By default, dialogs open in the center of the viewport. [since:com.vaadin:vaadin@V24.6]##A different positioning can be set programmatically##. Dialogs can also be made draggable, allowing the end user to move them around.
```

2024-11-29 06:48 UTC, rolfsmeds commented on articles/components/dialog/index.adoc
> +. By allowing the user to drag them (see <<Draggable>>)
(not sure I got the version tag syntax right there, so please check)

2024-11-29 06:48 UTC, rolfsmeds commented on articles/components/dialog/index.adoc
> +. By making the dialog resizable (see <<Resizable>>)
A bit same as above, feels like resizability is presented as an alternative. Also, I think it's best to mention content-based sizing already at the top, like so:

```suggestion
The Dialog size can be set in two ways:

. By setting width and height on the Dialog itself (__since V24.6 for React and Lit__)
. By setting the size of the Dialog's contents, whereby the Dialog scales to accommodate it

In both cases, the Dialog can also be made resizable.
```

2024-11-29 06:48 UTC, rolfsmeds commented on articles/components/dialog/index.adoc
> +The dialog's default size adjusts automatically based on its content. Fixed dimensions could be used when you need precise control over the dialog's size, for example, when displaying a form or grid
Then we can remove this paragraph.

2024-11-29 06:48 UTC, rolfsmeds commented on articles/components/dialog/index.adoc
>  Dialogs aren't resizable by default.
Let's rewrite this weird old sentence while we're at it 😅 

```suggestion
The Dialog can be configured to allow the end user to resize it by dragging from its edges.
```

2024-11-29 07:25 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +. By making the dialog resizable (see <<Resizable>>)
In this case, the paragraph about content-based sizing after the code snippets should be removed, right?

2024-11-29 07:26 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +. By making the dialog resizable (see <<Resizable>>)
NVM. I just saw the comment below.

2024-11-29 07:26 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +The dialog's default size adjusts automatically based on its content. Fixed dimensions could be used when you need precise control over the dialog's size, for example, when displaying a form or grid
```suggestion
```

2024-11-29 07:32 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +. By allowing the user to drag them (see <<Draggable>>)
It's working:
<img width="751" alt="image" src="https://github.com/user-attachments/assets/15e8353d-2461-4ea9-bd65-cd86d1b5237e">

2024-12-02 09:11 UTC, rolfsmeds approved these changes

2024-12-02 09:48 UTC, DiegoCardoso commented on articles/components/dialog/index.adoc
> +The Dialog size can be set with the width and height on the Dialog itself (__since V24.6 for React and Lit__). You can also set the size of the content of Dialog, whereby the Dialog scales to accommo
Missing dot:
```suggestion
The Dialog size can be set with the width and height on the Dialog itself (__since V24.6 for React and Lit__). You can also set the size of the content of Dialog, whereby the Dialog scales to accommodate it. In both cases, the Dialog can also be made resizable.
```

2024-12-02 09:55 UTC, merged