docs: DatePicker fallback parser
vaadin/docs pull request #3948
Opened 2024-11-26 07:32 UTC by vursen

Fixes #3930

2024-11-26 10:30 UTC, sissbruecker commented on articles/components/date-picker/date-formats.adoc
> +Additionally, Date Picker allows you to provide a server-side parser that is used as a fallback when user input cannot be parsed using methods described in the previous sections. The parser is a func
Technically, the function always needs to return a `Result` that then either contains a date or an error. Though it could be confusing to read either way if you are not familiar with `Result` yet. Maybe don't mention that class at all and only state that it either returns the parsed date or an error.

2024-11-26 10:30 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/datepicker/DatePickerFallbackParser.java
> +                return Result
```suggestion
                // Handle input such as "+1"
                return Result
```
Could also remove the `else if` / `else` branches and move the comments above the respective `if` statements where they would be more appropriate.

2024-11-26 10:30 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/datepicker/DatePickerFallbackParser.java
> +                return Result
```suggestion
                // Handle input such as "-1"
                return Result
```

2024-11-26 10:39 UTC, vursen commented on src/main/java/com/vaadin/demo/component/datepicker/DatePickerFallbackParser.java
> +                return Result
Thanks, applied.

2024-11-26 10:39 UTC, vursen commented on src/main/java/com/vaadin/demo/component/datepicker/DatePickerFallbackParser.java
> +                return Result
Thanks, applied.

2024-11-26 10:40 UTC, sissbruecker approved these changes

2024-11-29 06:55 UTC, rolfsmeds requested changes

2024-11-29 06:55 UTC, rolfsmeds commented on articles/components/date-picker/date-formats.adoc
> +Additionally, Date Picker allows you to provide a server-side parser that is used as a fallback when user input cannot be parsed using methods described in the previous sections. The parser is a func
```suggestion
Additionally, the Flow version of Date Picker allows you to provide a server-side parser that is used as a fallback when user input cannot be parsed using the methods described above. The parser is a function that receives the user-entered string and returns either a parsed date or an error message. Successfully parsed dates are displayed in the field using the same pattern as other dates.
```

2024-12-02 09:10 UTC, rolfsmeds approved these changes

2024-12-02 10:11 UTC, merged