docs: upload folder drag and drop
vaadin/docs pull request #3949
Opened 2024-11-26 10:52 UTC by sissbruecker

Document that upload now supports drag and drop of folders.

2024-11-29 06:50 UTC, rolfsmeds requested changes

2024-11-29 06:50 UTC, rolfsmeds commented on articles/components/upload/index.adoc
> +Upload also allows to drag & drop folders. This recursively uploads all files from the folder and its sub-folders. Note that the folder structure will be flattened and the names of uploaded files wil
```suggestion
Upload can be configured to allow drag & drop uploading of folders. This uploads all files from the folder and its sub-folders recursively. Note that the folder structure will be flattened and the names of uploaded files will not indicate in which folder they were in. Uploading folders is currently only supported by drag & drop, not through the native file picker opened through the upload button.
```

2024-11-29 06:59 UTC, sissbruecker commented on articles/components/upload/index.adoc
> +Upload also allows to drag & drop folders. This recursively uploads all files from the folder and its sub-folders. Note that the folder structure will be flattened and the names of uploaded files wil
@rolfsmeds We don't have a config option for this, it just works out of the box.

2024-11-29 07:11 UTC, rolfsmeds commented on articles/components/upload/index.adoc
> +Upload also allows to drag & drop folders. This recursively uploads all files from the folder and its sub-folders. Note that the folder structure will be flattened and the names of uploaded files wil
Ah, indeed, lemme rephrase it.

```suggestion
Upload supports uploading folders via drag & drop. This uploads all files from the folder and its sub-folders recursively. Note that the folder structure will be flattened and the names of uploaded files will not indicate in which folder they were in. Uploading folders is currently not supported through the native file picker.
```

2024-11-29 07:12 UTC, sissbruecker commented on articles/components/upload/index.adoc
> +Upload also allows to drag & drop folders. This recursively uploads all files from the folder and its sub-folders. Note that the folder structure will be flattened and the names of uploaded files wil
Thanks!

2024-12-03 13:50 UTC, rolfsmeds approved these changes

2024-12-10 11:51 UTC, merged