doc: add section about wrapping to horizontal and vertical layouts
vaadin/docs pull request #3970
Opened 2024-12-02 14:54 UTC by DiegoCardoso

Adds "Wrapping" section with examples for Vertical Layout and Horizontal Layout.

2024-12-02 15:46 UTC, rolfsmeds requested changes
just a snippet tweak, otherwise looks good imo

2024-12-02 15:46 UTC, rolfsmeds commented on src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
> +        layout.setWrap(true);
IMO the snippet could be just this line, since it's the one most relevant to showcase how to use the feature.
(And something corresponding for React & Lit)

2024-12-02 15:58 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
> +        layout.setWrap(true);
Like this?
<img width="465" alt="image" src="https://github.com/user-attachments/assets/99fed9fa-b0eb-4bad-920a-374dab7d6054">
<img width="458" alt="image" src="https://github.com/user-attachments/assets/a4b2d40e-83d3-454a-b408-06a79dc3dc45">
<img width="440" alt="image" src="https://github.com/user-attachments/assets/cdc0cb37-d863-4f8e-ac6b-7c282f92dbcd">

2024-12-02 15:59 UTC, rolfsmeds commented on src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
> +        layout.setWrap(true);
yeah, something like that

2024-12-03 08:55 UTC, web-padawan commented on articles/components/horizontal-layout/index.adoc
> +By default, components in a layout will either shrink or overflow when there isn't enough horizontal space. Enable wrapping to make components flow onto the next line when there's insufficient width,
Consider adding `since` either in the text or next to the heading to indicate `theme="wrap"` is a new feature.

2024-12-03 09:11 UTC, DiegoCardoso commented on articles/components/horizontal-layout/index.adoc
> +By default, components in a layout will either shrink or overflow when there isn't enough horizontal space. Enable wrapping to make components flow onto the next line when there's insufficient width,
Good catch. I had that in mind when I was writing the section, but ended up missing it. Added.
![image](https://github.com/user-attachments/assets/c58e2747-bed9-4a04-acc4-87a270cdd138)

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import '@vaadin/radio-group';
Unused import.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import { customElement, state } from 'lit/decorators.js';
The `state` decorator is unused.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import type { RadioGroupValueChangedEvent } from '@vaadin/radio-group';
Unused import.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +  type RadioGroupValueChangedEvent,
These imports are also unused.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +import { useSignal } from '@vaadin/hilla-react-signals';
Unused import.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +  useSignals(); // hidden-source-line
I think this can be also removed as there are no signals in the example.

2024-12-03 09:22 UTC, web-padawan commented on frontend/demo/component/basiclayouts/react/basic-layouts-vertical-layout-wrapping.tsx
> +  useSignals(); // hidden-source-line
I think this can be also removed as there are no signals in the example.

2024-12-03 09:31 UTC, DiegoCardoso reviewed
Thanks.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-vertical-layout-wrapping.tsx
> +  useSignals(); // hidden-source-line
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +  useSignals(); // hidden-source-line
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +  type RadioGroupValueChangedEvent,
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +import { useSignal } from '@vaadin/hilla-react-signals';
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import type { RadioGroupValueChangedEvent } from '@vaadin/radio-group';
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import { customElement, state } from 'lit/decorators.js';
Removed.

2024-12-03 09:31 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +import '@vaadin/radio-group';
Removed.

2024-12-03 09:43 UTC, web-padawan approved these changes

2024-12-03 10:33 UTC, sissbruecker commented on articles/components/horizontal-layout/index.adoc
> +[source,typescript]
```suggestion
[source,html]
```
This renders better, since the snippet only contains HTML.

2024-12-03 10:33 UTC, sissbruecker commented on articles/components/vertical-layout/index.adoc
> +[source,typescript]
```suggestion
[source,html]
```
This renders better, since the snippet only contains HTML.

2024-12-03 10:33 UTC, sissbruecker commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +        style="align-items: stretch; width: 350px;"
I'm currently updating related examples, and it seems `align-items: stretch` is not required.

2024-12-03 10:33 UTC, sissbruecker commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +    <>
Nit: The fragment is not necessary as there is only a single child.

2024-12-03 10:33 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
> +        HorizontalLayout layout = new HorizontalLayout();
```suggestion
        HorizontalLayout layoutWithWrap = new HorizontalLayout();
```
Nit: Would be a bit more consistent and provides some context which of the two layouts it represents.

2024-12-03 11:37 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +    <>
There are two children here, maybe you meant to add this comment on the React example for the VerticalLayout where indeed there's only one child.

2024-12-03 11:41 UTC, sissbruecker commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +    <>
Yep, my bad. I had the comment on the other file first, then moved it to the file above assuming it would apply as well.

2024-12-03 11:43 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
> +        style="align-items: stretch; width: 350px;"
Yeah, removed.

2024-12-03 11:43 UTC, DiegoCardoso commented on frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
> +    <>
No problem. I removed the fragment at the other file

2024-12-03 11:43 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
> +        HorizontalLayout layout = new HorizontalLayout();
Done for both Java examples.

2024-12-11 08:45 UTC, merged