[Control Center] Remove references to the 1.0 installation process
vaadin/docs pull request #3976
Opened 2024-12-04 07:50 UTC by MatthewVaadin

Removes references to the Control Center 1.0 installation process, which has changed in 1.1.0. This includes the page about dependency installation, images from the startup wizard and certain parts of the security considerations page.

Issue #3965 removes references to the dependency installation page from the getting started page, so this issue depends on that one.

Fixes https://github.com/vaadin/control-center/issues/764

2024-12-05 12:23 UTC, MatthewVaadin commented on articles/control-center/security/index.adoc
> +Control Center creates a Keycloak administrator during installation. It's important to keep this user's credentials secure, as they provide full access to the Keycloak instance, including users, grou
There is a Keycloak administrator user created though, which has the name `admin` and a password stored in the `control-center-keycloak-initial-admin` secret. We don't mention this anywhere in the documentation, but it is a potential security concern if the details are shared.

We could take the decision not to mention it at all and then this section could be completely removed. On the other hand, if we decide to keep it, perhaps it needs to be explained better.

2024-12-10 09:08 UTC, heruan commented on articles/control-center/security/index.adoc
> +Control Center creates a Keycloak administrator during installation. It's important to keep this user's credentials secure, as they provide full access to the Keycloak instance, including users, grou
Good point. Let's keep the sentence with the additional information of the secret where the credentials are stored, with a warning about the risk of breaking Control Center features by applying manual changes from the Keycloak admin dashboard.

2024-12-18 08:00 UTC, heruan requested changes

2024-12-18 08:00 UTC, heruan commented on articles/control-center/security/index.adoc
> +Control Center creates a Keycloak administrator during installation. This can be used to access the Keycloak instance directly. The username is `admin` and the password is stored in a base 64 encoded
> The username is `admin`

This is not the case anymore, in Keycloak 24.6 it's now `temp-admin`. Since this might change, better document that both username and password are stored in the secret and those should be used.

2024-12-19 07:16 UTC, heruan approved these changes

2024-12-19 07:41 UTC, jouni approved these changes

2024-12-19 07:42 UTC, merged