add instructions to upgrade Control Center from 1.0 to 1.1
vaadin/docs pull request #4043
Opened 2024-12-20 13:56 UTC by sosa-vaadin

Add instructions to guide users through the process of upgrading Control Center from version 1.0.X to 1.1.X.
It's one extra page of documentation. I added it to the "Getting Started" section, but we might decide to put it somewhere else.

2024-12-31 12:47 UTC, tamasmak requested changes

2024-12-31 12:47 UTC, tamasmak commented on articles/control-center/getting-started/upgrade.adoc
> +To successfully upgrade Control Center from 1.0.X version to 1.1.X, you must perform three actions:
```suggestion
To successfully upgrade Control Center from 1.0.x version to 1.1.x, you must perform three actions:
```

2024-12-31 12:47 UTC, tamasmak commented on articles/control-center/getting-started/upgrade.adoc
> +Control Center 1.1.0 uses a configuration property that did not exist in 1.0.
```suggestion
Control Center 1.1 uses a configuration property that did not exist in 1.0.
```

2024-12-31 12:47 UTC, tamasmak commented on articles/control-center/getting-started/upgrade.adoc
> +Edit the configmap for control center, adding the following under the `data` segment:
```suggestion
Edit the configmap for Control Center, adding the following under the `data` segment:
```

2025-01-09 09:21 UTC, jouni commented on articles/control-center/getting-started/upgrade.adoc
> +meta-description: How to get upgrade Vaadin Control Center version 1.0 to 1.1.
I would avoid version numbers in the title and description, and keep this page version agnostic, so that we can reuse it for all future upgrade guides.

Also, `meta-description` is not needed if it’s the same as `description`.

```suggestion
title: Upgrading
page-title: Upgrading Vaadin Control Center
description: How to upgrade Vaadin Control Center from an older version to the latest version.
```

2025-01-09 09:21 UTC, jouni commented on articles/control-center/getting-started/upgrade.adoc
> +To upgrade Control Center from version 1.0.x to 1.1.x, you'll need to perform three tasks:
No need to explicitly imply patch/maintenance versions in my opinion. Omitting them implies all patch/maintenance versions.

```suggestion
To upgrade Control Center from version 1.0 to 1.1, you'll need to perform three tasks:
```

2025-01-15 08:12 UTC, tamasmak approved these changes

2025-01-16 08:40 UTC, merged