Update Fusion login view setup instructions
vaadin/docs pull request #406
Opened 2021-04-26 11:32 UTC by Artur-

2021-04-26 12:13 UTC, haijian-vaadin requested changes
The login-view.ts could be updated as in https://github.com/vaadin/spring/blob/master/vaadin-spring-tests/test-spring-security-fusion/frontend/views/login-view.ts#L14-L26

Also, logout could be updated to use a button instead of link as in https://github.com/vaadin/spring/pull/778

2021-04-26 12:23 UTC, Artur- commented
Updated some more

2021-04-26 12:39 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +```
```suggestion
[source,java]
----
  @Override
  protected void configure(HttpSecurity http) throws Exception {
    super.configure(http);
    setLoginView(http, "/login");
  }
----
```

2021-04-26 12:40 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +```
```suggestion
[source,html]
----
<vaadin-button @click="${() => logout()}">Logout</vaadin-button>
----
```

2021-04-26 12:41 UTC, jouni commented
Build errors:

```
3:33:53 PM: [ERROR] ERROR in /opt/build/repo/frontend/demo/fusion/authentication/login-view.ts
3:33:53 PM: [ERROR] [tsl] ERROR in /opt/build/repo/frontend/demo/fusion/authentication/login-view.ts(21,14)
3:33:53 PM: [ERROR]       TS2339: Property 'redirectUrl' does not exist on type 'LoginResult'.
3:33:53 PM: [ERROR]
3:33:53 PM: [ERROR] ERROR in /opt/build/repo/frontend/demo/fusion/authentication/login-view.ts
3:33:53 PM: [ERROR] [tsl] ERROR in /opt/build/repo/frontend/demo/fusion/authentication/login-view.ts(21,54)
3:33:53 PM: [ERROR]       TS2339: Property 'defaultUrl' does not exist on type 'LoginResult'.
```

2021-04-26 12:46 UTC, Artur- commented
>Build errors:
Maybe the build is using an old version?

2021-04-26 15:05 UTC, jouni commented
20.0.0.alpha7

2021-04-27 08:21 UTC, haijian-vaadin approved these changes

2021-04-27 08:22 UTC, haijian-vaadin commented
It depends on a new v20 release (to be released soon), shall I update the version in this PR or a separate one?

2021-04-28 13:11 UTC, jouni commented
Still failing on this error:

```
3:09:29 PM: /opt/build/repo/frontend/demo/fusion/authentication/login-view.ts
3:09:29 PM:   20:27  error  Replace `⏎······result.redirectUrl·||·this.returnUrl·||·result.defaultUrl·||·"/"` with `·result.redirectUrl·||·this.returnUrl·||·result.defaultUrl·||·'/'`  prettier/prettier
```

2021-04-28 13:12 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +To handle logging out, you can use the `logout()` helper defined in `auth.ts` above. You typically want to use a button for handling logout and not navigation and a route to avoid timing issues betwe
```suggestion
To handle logging out, you can use the `logout()` helper defined in `auth.ts` above.
You typically want to use a button for handling logout and not navigation and a route to avoid timing issues between rendering views and logging out.
You can, for example, do the following:
```

2021-04-30 06:48 UTC, merged