Update Theme articles with Application Theme
vaadin/docs pull request #41
Opened 2020-11-13 07:36 UTC by tanbt

Resolves https://github.com/vaadin/flow/issues/9284.

2020-11-13 11:41 UTC, jouni commented
Sorry about polluting the commit log with attempts to try and fix the linting process (I thought it would be simple). I’ll stop now, and continue doing that in another branch.

2020-11-13 13:58 UTC, tanbt commented
> polluting the commit log 

Not an issue, we can "squash and merge" them all.

2020-11-13 21:19 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +Figure 1 illutrates the contents of a theme:
```suggestion
Figure 1 illustrates the contents of a theme:
```

2020-11-18 13:06 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +=== Theme Folder
Perhaps explain the folders as in the image e.g.
`theme` should be located under `./frontend` and contains all application themes in theme name folders.
`my-theme` contains all files associated with the theme my-theme
`components` is for component specific themes, style sheets need to match the component tag name.
`theme.json` theme configuration for assets etc.
`images` and `webfonts` are folders for static resources
`global.css` contains theme changes that affect the whole page.

Or else move the figure after the explanation of the different parts with the topic sample theme setup...

2020-11-19 09:04 UTC, caalador requested changes

2020-11-19 09:04 UTC, caalador commented on articles/themes/src/main/java/com/vaadin/flow/tutorial/theme/UsingComponentThemes.java
>      public class LumoApplication extends Div {
Theme annotation should only be on a AppShellConfigurator class.
No `@Route()`

2020-11-19 09:04 UTC, caalador commented on articles/themes/src/main/java/com/vaadin/flow/tutorial/theme/UsingComponentThemes.java
> +    @Theme(value = "my-theme", variant = Lumo.DARK)
Should this be left as `themeClass = Lumo.class`

2020-11-23 11:51 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +For example, in Figure 1, `global.css` file can have `background: url("theme/my-theme/images/bg.jpg");`
https://github.com/vaadin/flow/pull/9451 will change the url format to be `url('./images/bg.jpg');`

2020-11-24 10:39 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +=== Theme Folder
I updated contents in the picture. I'd prefer to put it before the detail explanation so users can have a quick visualization.

2020-11-24 10:39 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +For example, in Figure 1, `global.css` file can have `background: url("theme/my-theme/images/bg.jpg");`
Fixed. "the resource location is relative to the CSS file location". (or is it relative to the app theme folder?)

2020-11-24 10:39 UTC, tanbt commented on articles/themes/src/main/java/com/vaadin/flow/tutorial/theme/UsingComponentThemes.java
> +    @Theme(value = "my-theme", variant = Lumo.DARK)
Reverted.

2020-11-24 10:39 UTC, tanbt commented on articles/themes/src/main/java/com/vaadin/flow/tutorial/theme/UsingComponentThemes.java
>      public class LumoApplication extends Div {
Fixed.

2020-11-24 10:53 UTC, caalador commented on articles/themes/importing-style-sheets.asciidoc
> +NOTE: Using an <<application-theme, application theme>>, a component-specific style sheet is imported when the CSS file name matches the component name. For example,  `my-theme/components/vaadin-butt
> `my-theme/components/vaadin-button.css`
Perhaps it should have the full path `frontent/theme/my-theme/components/vaadin-button.css`

2020-11-24 10:53 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +For example, in Figure 1, `global.css` file can have `background: url("theme/my-theme/images/bg.jpg");`
Realtive to the css file, but should still be inside the theme folder.
e.g. 
theme
|--> out-scope.png
|  |--> my-theme
|  |--> global.css
|  |--> img
|  |   |--> bg.jpg
|  |--> components
|     |--> vaadin-button.css

To use the bg image for global.css it would be `url('./img/bg.jpg')` and for button `url('../img/bg.jpg')`
Where as trying to get `out-scope.png` with either `url('../out-scope.png')` for global or `url('../../out-scope.png')`  for baadin-button would result in no rewrite and would fail on the server if it wouldn't be externally served.

2020-11-24 11:35 UTC, tanbt commented on articles/themes/importing-style-sheets.asciidoc
> +NOTE: Using an <<application-theme, application theme>>, a component-specific style sheet is imported when the CSS file name matches the component name. For example,  `my-theme/components/vaadin-butt
Fixed.

2020-11-24 11:35 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +For example, in Figure 1, `global.css` file can have `background: url("theme/my-theme/images/bg.jpg");`
Fixed.

2020-11-24 13:10 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +WARNING: The resource and the CSS file must be in the same applicatin theme.
```suggestion
NOTE: The resource and the CSS file must be in the same application theme to be handled, else it should be available with the given URL.
```

2020-11-25 06:46 UTC, mshabarov requested changes

2020-11-25 06:46 UTC, mshabarov commented on articles/themes/application-theme.asciidoc
> +You must set the annotation on an https://vaadin.com/api/platform/com/vaadin/flow/component/page/AppShellConfigurator.html[AppShellConfigurator] class.
Exception is being thrown otherwise?

2020-11-25 06:46 UTC, mshabarov commented on articles/themes/application-theme.asciidoc
> +To make at-rules work for components embedded into non-Vaadin applications (for example <<../flow/embedding-flow-applications/tutorial-webcomponent-intro,WebComponentExporter>>), add a file called `d
Couldn't open this link in IntellJIDEA preview, it says the `file doesn't resolve`. And for some other links, for instance, `<<css-custom-properties#,CSS custom properties>>` it says `Anchor doesn't resolve`. Please double check.  But it can be only me who has it, or IntelliJIDEA preview issue.

2020-11-25 06:46 UTC, mshabarov commented on articles/themes/importing-style-sheets.asciidoc
> +NOTE: Using an <<application-theme, application theme>>, a component-specific style sheet is imported when the CSS file name matches the component name. For example, `frontent/theme/my-theme/componen
Otherwise, it the CSS file name does not match the component tag, the CSS would not be recognised and not be applied?

2020-11-25 06:46 UTC, mshabarov commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#global-styles, global styles>> in an application theme can override the global variants.
Would be great to give a code example

2020-11-25 06:46 UTC, mshabarov commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#components-styles, Component styles>> in an application theme can override the component variants.
Would be great to give a code example

2020-11-25 07:29 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +WARNING: The resource and the CSS file must be in the same application theme.
Also need to mention external URL won't be touch.

2020-11-25 09:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +==== Extend an Application Theme
This should be removed and added in another PR after we have the parent theme feature implemented.

2020-11-25 09:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +==== Assets
Assets shoul be in another PR that is merged after we have implemented the feature.

2020-11-26 06:49 UTC, mshabarov commented on articles/themes/application-theme.asciidoc
> +Application themes are placed under the `frontend/theme/` folder.
First approach is better IMO. Thanks!

2020-11-26 06:56 UTC, mshabarov commented on articles/themes/application-theme.asciidoc
> +  "importCss": ["@foo/bar/baz.css"]
Ok

2020-11-26 07:06 UTC, caalador requested changes

2020-11-26 07:06 UTC, caalador commented on articles/themes/importing-style-sheets.asciidoc
> +NOTE: Using an <<application-theme, application theme>>, component-specific style sheets are imported and will be applied to components that have their tag names matches with the CSS file names. For
```suggestion
NOTE: When using an <<application-theme, application theme>>, component-specific style sheets are imported from the components folder and will be applied to components where the CSS file name match the component tag. For example, `frontent/theme/my-theme/components/vaadin-button.css` will be the same as `@CssImport` with `themeFor="vaadin-button"`.
```

2020-11-26 07:08 UTC, mshabarov commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#global-styles, global styles>> in an application theme can override the global variants.
Could you give a link? I can't find it

2020-11-26 07:08 UTC, mshabarov commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#components-styles, Component styles>> in an application theme can override the component variants.
Could you give a link? I can't find it

2020-11-26 07:39 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +WARNING: The static resource should be in the same theme with the CSS file. Otherwise, it will be served as external resources by the web server instead of webpack.
Thanks. Updated.

2020-11-26 07:39 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +==== Assets
Removed.

2020-11-26 07:39 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +==== Extend an Application Theme
Removed.

2020-11-26 07:39 UTC, tanbt commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#global-styles, global styles>> in an application theme can override the global variants.
The link is already `<<applicatioin-theme#global-styles, global styles>>`. This NOTE is moved to that section.

2020-11-26 07:39 UTC, tanbt commented on articles/themes/theme-variants.asciidoc
> +NOTE: <<applicatioin-theme#components-styles, Component styles>> in an application theme can override the component variants.
It's `<<applicatioin-theme#components-styles, Component styles>>` already.

2020-11-26 08:41 UTC, mshabarov approved these changes

2020-11-26 08:50 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +NOTE: Global styles can override <<theme-variants#global-variants, global variants>> styles. For example, `Lumo.DARK` variant defines a `--lumo-base-color` which can be overridden by `global.css` fil
```suggestion
NOTE: Global styles can override <<theme-variants#global-variants, global variants>> styles.
For example, `Lumo.DARK` variant defines a `--lumo-base-color` which can be overridden by `global.css` file.
```

2020-11-26 08:51 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +NOTE: Component styles can override <<theme-variants#component-variants, component variants>> styles. For example, styles in `vaadin-button.css` file can override styles from `ButtonVariant.LUMO_ERRO
```suggestion
NOTE: Component styles can override <<theme-variants#component-variants, component variants>> styles.
For example, styles in `vaadin-button.css` file can override styles from `ButtonVariant.LUMO_ERROR` variant of a Vaadin Button component.
```

2020-11-26 08:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +Each theme is in a separate folder, the folder name is also the theme name.
Should we have a couple examples here like 
- For `@Theme("alpaca")` the files should be in `frontend/theme/alpaca` 
- For `@Theme("frost-bite")`  the files should be in `frontend/theme/frost-bite`

2020-11-26 08:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +This location is fixed.
```suggestion
The theme folder location is not configurable.
```
Might sound better.

2020-11-26 08:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +The file name must match the component name that you want to style.
```suggestion
The file name must match the tag name of the component that you want to style.
```

2020-11-26 08:52 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +==== Use at-rules for Components in non-Vaadin Applications
Embedded components do not yet have the application theme support. This could also be moved to a new PR that the adds the information when the feature has been released.

2020-11-27 06:52 UTC, caalador reviewed
I'm sad to say that the node_modules assets part that was removed because the functionality wasn't there was merged yesterday so the assets documentation could be added back =_=

2020-11-27 07:13 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +==== Use at-rules for Components in non-Vaadin Applications
Removed.

2020-11-27 07:13 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +Each theme is in a separate folder, the folder name is also the theme name.
Added.

2020-11-27 08:58 UTC, tanbt commented
> I'm sad to say that the node_modules assets part that was removed because the functionality wasn't there was merged yesterday so the assets documentation could be added back =_=

Added it back. The example code is now using fontawesome instead of foobar.

2020-11-27 09:35 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
```suggestion
background-image: url('./fortawesome/icons/address-book.svg');	
```

2020-11-27 09:35 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
Except I'm not certain that this will work so it might be that it needs `VAADIN/static/fortawesome/icons/...` should be added as a test that how do node assets work inside the css files.

At the moment we only test like: `        Image snowFlake = new Image("VAADIN/static/fortawesome/icons/snowflake.svg", "snowflake");`

2020-11-27 12:06 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
Is it on purpose “fort” and not “font”?

2020-11-27 12:33 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
It's "fort". I checked the library: https://www.npmjs.com/package/@fortawesome/fontawesome-free .

2020-11-27 12:37 UTC, tanbt commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
Added `VAADIN/static/`.

2020-11-27 12:41 UTC, caalador approved these changes

2020-11-27 12:48 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +background-image: url('fortawesome/icons/address-book.svg');
It's FontAwesome by [FortAwesome ](https://github.com/FortAwesome)
I just set it in the feature test to 'fortawesome/icons' as in they are icons from fortawesome, could be something else also.

2020-11-27 12:48 UTC, merged