Grid docs and TS examples.
vaadin/docs pull request #411
Opened 2021-04-28 06:31 UTC by sosa-vaadin

All documentation content for `vaadin-grid` as well as TypeScript examples and some Java examples.

2021-04-29 07:57 UTC, tomivirkki commented on frontend/demo/component/grid/grid-content.ts
> +    });
You can remove this explicit call to `recalculateColumnWidths` (and the `grid` reference class property) if you don't provide an initial value for the `items` array: `private items?: Person[];`.

Same in the column-freezing example.

2021-04-29 08:07 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-content.ts
> +    });
I removed the call from both files.

2021-04-29 12:11 UTC, jouni commented on frontend/demo/component/grid/grid-column-alignment.ts
> +      <!-- end:snippet[] -->
```suggestion
      <!-- tag::snippet[] -->
      <vaadin-grid .items="${this.items}">
        <vaadin-grid-column path="displayName"></vaadin-grid-column>
        <vaadin-grid-column
          header="Due"
          .renderer="${guard([], () => (root: HTMLElement) =>
            render(html`<span>${this.randomDate()}</span>`, root)
          )}"
        ></vaadin-grid-column>
        <vaadin-grid-column
          header="Amount"
          text-align="end"
          .renderer="${guard([], () => (root: HTMLElement) => {
            render(
              html`<span style="font-variant-numeric: tabular-nums">${this.randomAmount()}</span>`,
              root
            );
          })}"
        ></vaadin-grid-column>
      </vaadin-grid>
      <!-- end::snippet[] -->
```

2021-04-29 12:16 UTC, jouni commented on frontend/demo/component/grid/grid-column-freezing.ts
> +// end::snippet[]
I think this would be the most important part to highlight, and move the important attribute as the first one. Could benefit from a "callout" as well (`<!-- (1) -->`), but I’m not sure we can add those here in between attribute values. Would need to test.

```suggestion
@customElement('grid-column-freezing')
export class Example extends LitElement {
  constructor() {
    super();
    // Apply custom theme (only supported if your app uses one)
    applyTheme(this.shadowRoot);
  }

  @internalProperty()
  private items?: Person[];

  async firstUpdated() {
    const { people } = await getPeople();
    this.items = people;
  }

  render() {
    return html`
      <vaadin-grid .items="${this.items}">
        <!-- tag::snippet[] -->
        <vaadin-grid-column
          frozen
          header="Name"
          .renderer="${this.nameRenderer}"
          auto-width
          flex-grow="0"
        ></vaadin-grid-column>
        <!-- end::snippet[] -->
        <vaadin-grid-column path="email" auto-width></vaadin-grid-column>
        <vaadin-grid-column path="address.phone" auto-width></vaadin-grid-column>
        <vaadin-grid-column path="profession" auto-width></vaadin-grid-column>
        <vaadin-grid-column path="address.street" auto-width></vaadin-grid-column>
      </vaadin-grid>
    `;
  }

  private nameRenderer = (root: HTMLElement, _: HTMLElement, model: GridItemModel) => {
    const person = model.item as Person;
    render(
      html`
        <vaadin-horizontal-layout style="align-items: center;">
          <vaadin-avatar
            style="height: var(--lumo-size-m)"
            img="${person.pictureUrl}"
            name="${person.firstName} ${person.lastName}"
            alt="User avatar"
          ></vaadin-avatar>
          <div>${person.firstName} ${person.lastName}</div>
        </vaadin-horizontal-layout>
      `,
      root
    );
  };
}
```

2021-04-29 12:24 UTC, jouni commented on articles/ds/components/grid/index.asciidoc
> +----
Should include the CSS file in the sources as well.

2021-04-29 12:32 UTC, jouni commented
@magi42, could you help clean up the index.asciidoc style issues?

2021-04-29 12:33 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +----
I added a reference to the `vaadin-grid-styling.css` file.

2021-04-29 13:00 UTC, magi42 commented
OK yeah.

2021-04-29 14:17 UTC, yuriy-fix requested changes

2021-04-29 14:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-column-visibility.ts
> +          .hidden="${!this.visibleColumns.firstName}"
Can we use `contextMenuItems` here to avoid creating the `visibleColumns` prop? 🤔

2021-04-29 14:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-column-visibility.ts
> +          @item-selected="${(e: ContextMenuItemSelected) => {
Nit: would it be easier to use menu-bar here? 🤔

2021-04-29 14:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +    render(html`<vaadin-grid-sorter path="lastName">Birthdate</vaadin-grid-sorter>`, root);
Nit: I guess `birthday` column shouldn't be sorted by `lastname` as it's confusing and the text mentions only the first column to be sorted by `lastname`

2021-04-29 15:36 UTC, magi42 requested changes

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +Place filters outside the Grid when
```suggestion
Place filters outside the grid when:
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +* a bigger field or more complex filter UI is needed, which wouldn’t comfortably fit in a column
```suggestion
* A bigger field or more complex filter UI is needed, which wouldn’t comfortably fit in a column.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +* The filter is based on multiple columns
```suggestion
* The filter is based on multiple columns.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +You can use a Context Menu to provide shortcuts to the user.
```suggestion
You can use Context Menu to provide shortcuts to the user.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +Please note that using a Context Menu should not be the only way of accomplishing a task.
```suggestion
Please note that using a context menu should not be the only way of accomplishing a task.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +Grid supports drag and drop, for example to reorder rows and to drag rows between Grids.
```suggestion
Grid supports drag and drop, for example to reorder rows and to drag rows between grids.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +A Grid’s drop mode determines where a drop can happen.
```suggestion
The drop mode of a grid determines where a drop can happen.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +|Drops can occur on the Grid as whole, not on top of or between individual rows. Use this option when the order is unimportant.
```suggestion
|Drops can occur on the grid as a whole, not on top of or between individual rows. Use this option when the order is unimportant.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +Rows can be dragged from one Grid to another, for example to move, copy or link items from different datasets.
```suggestion
Rows can be dragged from one grid to another, for example to move, copy or link items from different datasets.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +The `compact` theme variant makes the Grid more dense by reducing the header and row heights, as well as the spacing between columns.
```suggestion
The `compact` theme variant makes a grid more dense by reducing the header and row heights, as well as the spacing between columns.
```

2021-04-29 15:36 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +The `no-border` theme variant removes Grid’s outer border.
```suggestion
The `no-border` theme variant removes the outer border of the grid.
```

2021-04-30 08:42 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +// TODO: Java example for component renderer goes here
Even though a Java file was created for each example, the contents are the same in all of them; in other words, no examples have been implemented. As we're focusing on the TS examples, I thought of removing all references to those Java files and leave a reminder (and placeholder) to add those files later.

2021-04-30 09:18 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +    render(html`<vaadin-grid-sorter path="lastName">Birthdate</vaadin-grid-sorter>`, root);
It is now sorted by `birthday`.

2021-04-30 09:20 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-column-visibility.ts
> +          .hidden="${!this.visibleColumns.firstName}"
Removed the `visibleColumns` property, added the `@internalProperty()` decorator to the `contextMenuItems` property and used its values to handle the different columns' visibility.

2021-04-30 09:20 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +Consider the following example:
Commented out line 94.

2021-04-30 09:21 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +This can be useful for keeping the most important columns always visible in Grids with a large number of columns.
Removed the empty line between these two so they appear in the same paragraph.

2021-04-30 09:21 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-content.ts
> +        <vaadin-button theme="tertiary">
Added `icon` theme to the button.

2021-04-30 09:21 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-content.ts
> +// tag::snippet[]
Moved the snippet down to the first property.

2021-04-30 09:22 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-basic.ts
Moved the snippet tag down to the first property.

2021-04-30 09:23 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-dynamic-height.ts
> +              this.invitedPeople = [...this.invitedPeople, person];
Refactored the code so it properly adds or removes the items from both lists, re-assign it every time so the component gets refreshed. Nice catch.

2021-04-30 09:23 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-single-selection-mode.ts
> +  private selectedPerson: Person[] = [];
Changed variable name to `selectedItems`.

2021-04-30 09:24 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-single-selection-mode.ts
> +// tag::snippet[]
Moved the snippet tag down to the first property.

2021-04-30 09:44 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +In multi-select mode, a checkbox column is used to select and deselect rows.
I implemented your suggestion.

2021-04-30 09:44 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +In addition to setting any fixed or relative value, the Grid’s height can be set by the number of items in the dataset, meaning the Grid will grow and shrink based on the row count.
I implemented your suggestion.

2021-04-30 09:44 UTC, sosa-vaadin commented on articles/ds/components/grid/index.asciidoc
> +Component Renderers are easy to build but slow to render.
I implemented your suggestion.

2021-04-30 11:04 UTC, sosa-vaadin commented
@jouni Vale is complaining about the word 'scannability', how should I handle this?

2021-04-30 11:57 UTC, jouni commented
I’ll deflect that question to @magi42 😅

2021-04-30 15:11 UTC, magi42 commented
@sosa-vaadin Scannability looks like a valid word there together with readability, so just add it to `.github/styles/Vocab/Docs/accept.txt`.

2021-05-04 09:34 UTC, magi42 approved these changes

2021-05-05 10:27 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-column-header-footer.ts
> +        <iron-icon
I wrapped them inside a `vaadin-horizontal-layout` with `style="align-items: center;"` so it should be good now.

2021-05-05 12:17 UTC, yuriy-fix requested changes

2021-05-05 12:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-drag-rows-between-grids.ts
> +      .grid1,
Nit: no need to use `class`. You can target both with `vaadin-grid`

2021-05-05 12:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-drag-drop-filters.ts
> +        @grid-drop="${(event: CustomEvent) => {
Drag and drop logic is not working properly. In the example, I am trying to drag `Abigail`, but instead dragging `Isaac` (as nodes were already closed):
![drag-broken](https://user-images.githubusercontent.com/29372419/117139222-a8a47200-adb4-11eb-9404-eb858e4fcbe4.gif)

2021-05-05 12:17 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-drag-drop-filters.ts
> +    this.grid.clearCache();
`this.grid.clearCache()` feels hacky. No need to have `managers` or `items` internal properties. Everything can be moved to dataProvider from `firstUpdated`.

Example:
```
private dataProvider = async (
    params: GridDataProviderParams,
    callback: GridDataProviderCallback
  ) => {
    const { people } = await getPeople();
    const { page, pageSize, parentItem } = params;
    const startIndex = page * pageSize;
    const endIndex = startIndex + pageSize;

    const result = parentItem
      ? people.filter((item) => item.managerId === (parentItem as Person).id)
      : people.filter((item) => item.manager).slice(startIndex, endIndex);

    callback(result, result.length);
  };
```

2021-05-05 13:34 UTC, tomivirkki commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +        <vaadin-grid-column
This example is also be doable with `<vaadin-grid-sort-column>`:

 `<vaadin-grid-sort-column path="lastName" header="Employee">`

2021-05-06 07:11 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-filter.ts
> +            this.filteredItems = this.items.filter(({ displayName, email, profession }) =>
None of those examples showcase the same use case. In this case, there is a single field used for filtering multiple columns. I can't think of any way to update the grid with a dataProvider using this approach.

2021-05-06 07:48 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-drag-rows-between-grids.ts
> +          @grid-drop="${(event: CustomEvent) => {
I can take the dragStart and dragEnd listeners out to methods since they are indeed identical. However, the drop listeners should stay separate. Mixing both would need additional logic to check the target grid to the according arrays appropriately and would not improve readability or performance.

2021-05-06 08:07 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +        <vaadin-grid-column
I changed it. I kept the birthayHeaderRenderer to showcase at least one example of using `vaadin-grid-sorter`.

2021-05-06 08:13 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-drag-drop-filters.ts
> +    this.grid.clearCache();
By keeping a reference to the list of items (and managers), I can keep track of the changes the user makes when dropping an item. If I load the items with the dataProvider, it will always be a new list.

2021-05-06 08:17 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-drag-drop-filters.ts
> +        @grid-drop="${(event: CustomEvent) => {
The expandedItems list must be refreshed when the (expanded-items-changed) event is called. Problem solved.

2021-05-06 08:25 UTC, tomivirkki commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +        <vaadin-grid-column
I don't see a change here.

2021-05-06 08:53 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-built-in-filtering.ts
> +// tag::snippet[]
Done.

2021-05-06 08:53 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-built-in-filtering.ts
> +          flex-grow="0"
Set `width: 230px`.

2021-05-06 08:53 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-filter.ts
> +            flex-grow="0"
Set `width: 230px`

2021-05-06 08:56 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-filter.ts
> +          @keyup="${(e: KeyboardEvent) => {
Done.

2021-05-06 08:56 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-context-menu.ts
> +            const eventContext = this.grid.getEventContext(sourceEvent) as GridEventContext;
Done.

2021-05-06 08:57 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-context-menu.ts
> +// tag::snippet[]
Done.

2021-05-06 08:57 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-row-reordering.ts
> +        @grid-dragstart="${(event: CustomEvent) => {
Done.

2021-05-06 08:57 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-row-reordering.ts
> +        @grid-drop="${(event: CustomEvent) => {
Done.

2021-05-06 08:57 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-drag-rows-between-grids.ts
> +          @grid-dragstart="${(event: CustomEvent) => {
Done.

2021-05-06 08:57 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-drag-rows-between-grids.ts
> +      .grid1,
Done.

2021-05-06 09:00 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +        <vaadin-grid-column
I just pushed them, sorry for commenting before that 😅

2021-05-06 10:12 UTC, tomivirkki commented on frontend/demo/component/grid/grid-rich-content-sorting.ts
> +        <vaadin-grid-column
>  I kept the birthayHeaderRenderer to showcase at least one example of using vaadin-grid-sorter

nit: I don't see why mix two different approaches in one example. It adds unnecessary complexity and confuses the user about which one we recommend as the best practice. If we wanted to showcase the low-level `<vaadin-grid-sorter>` element, it could be done in an example dedicated for it. Not blocking the PR for this though.

2021-05-06 11:50 UTC, yuriy-fix commented on frontend/demo/component/grid/grid-drag-drop-filters.ts
> +    this.grid.clearCache();
I see. I guess comment should be enough, WDYT @tomivirkki ?

2021-05-07 05:44 UTC, merged