fix: using custom web components in form fields
vaadin/docs pull request #421
Opened 2021-05-02 20:49 UTC by vlukashov

- code snippets are updated so that they actually compile and work
 - the text content is rephrased to clarify the purpose and the general principles behind using custom web components with the client-side form binder API.

2021-05-03 12:11 UTC, jcgueriaud1 commented
I think this PR https://github.com/vaadin/docs/pull/418 fixes the same issue: https://github.com/vaadin/docs/issues/410

I think only one should be merged and the other closed. (Mine doesn't change the text, only fixes and externalize the examples)

2021-05-03 12:19 UTC, haijian-vaadin requested changes

2021-05-03 12:19 UTC, haijian-vaadin commented on articles/fusion/forms/appendix-web-component-field-strategy.asciidoc
> += Using Custom Web Components in a Form
Maybe it's better to also update the title here to `Binding Data to Custom Components` keep it in sync with the menu item?

2021-05-03 13:54 UTC, vlukashov commented
> I think this PR #418 fixes the same issue: #410
> 
> I think only one should be merged and the other closed. (Mine doesn't change the text, only fixes and externalize the examples)

I should have checked the open issues and PRs before starting to fix this on my own :(
Now both me and @jcgueriaud1 have done the same work twice.

I would probably take the PR with the changes to the text content. Would you like to suggest changes to the code samples in this PR, @jcgueriaud1?

2021-05-03 13:54 UTC, vlukashov commented on articles/fusion/forms/appendix-web-component-field-strategy.asciidoc
> += Using Custom Web Components in a Form
👍

2021-05-04 12:27 UTC, haijian-vaadin approved these changes

2021-05-04 12:28 UTC, merged