Add Basic Layouts docs and TS examples
vaadin/docs pull request #435
Opened 2021-05-04 14:56 UTC by yuriy-fix

2021-05-07 06:25 UTC, sosa-vaadin commented
<img width="490" alt="image" src="https://user-images.githubusercontent.com/76832183/117406599-f4226180-af15-11eb-9cc6-a0225950ab2f.png">
In small screens, the content overflows the container for this example. Maybe wrapping should be enabled here.

2021-05-07 07:25 UTC, sosa-vaadin requested changes
Replace `hidden-full-source-line` comments with `hidden-source-line` and fix snippet tags placements.

2021-05-07 07:25 UTC, sosa-vaadin commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
> +  }
Same issue about mixing TS and HTML content.

2021-05-07 07:25 UTC, sosa-vaadin commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts
> +  }
Same issue about mixing TS and HTML content.

2021-05-07 07:25 UTC, sosa-vaadin commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout.ts
> +import 'Frontend/demo/init'; // hidden-full-source-line
```suggestion
import 'Frontend/demo/init'; // hidden-source-line
```
Change this comment wherever it appears in every example.
https://github.com/vaadin/docs-app/pull/256

2021-05-10 13:32 UTC, yuriy-fix commented on articles/ds/components/basic-layouts/index.asciidoc
> +You can position components at the top, middle, or bottom. Items can alternatively be made to stretch vertically or positioned along the layout’s text baseline.
Done.

2021-05-10 13:32 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts
> +  }
Updated.

2021-05-10 13:32 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts
> +  }
Updated.

2021-05-10 13:32 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
> +  }
Updated.

2021-05-10 13:32 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-vertical-alignment.ts
> +  }
Updated.

2021-05-10 13:32 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-individual-alignment.ts
> +  }
Updated.

2021-05-10 13:33 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-horizontal-alignment.ts
> +  }
Updated.

2021-05-10 13:33 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-expanding-items.ts
> +  }
Updated.

2021-05-10 13:33 UTC, yuriy-fix commented on frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout.ts
> +import 'Frontend/demo/init'; // hidden-full-source-line
Updated.

2021-05-10 13:44 UTC, sosa-vaadin approved these changes

2021-05-12 07:47 UTC, merged