feat: add view based access control documentation
vaadin/docs pull request #458
Opened 2021-05-11 23:08 UTC by taefi

## Description

This documentation is demonstrating how to use
@AnonymousAllowed, @PermitAll, @RolesAllowed,
and @DenyAll on the Flow views in a Spring Boot
based vaadin application. This feature is based
on the ViewAccessChecker in flow and related
changes in vaadin-spring add-on.

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes: part of related PRs for fixing https://github.com/vaadin/flow/issues/10609

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-05-18 15:30 UTC, magi42 requested changes
Didn't complete the review yet.

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> += View Based Authorization
```suggestion
= View-Based Authorization
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +Vaadin applications that are based on Spring Boot, can leverage from a view based authorization mechanism out of the box, which can be enabled by using a set of annotations and with minimum Spring Se
```suggestion
Vaadin applications that are based on Spring Boot can use a view-based authorization mechanism out of the box.
You can enable it by using a set of annotations and with minimum Spring Security configurations.
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +At a glance, this mechanism is based on using `@AnonymousAllowed`, `@PermitAll`, `@RolesAllowed`, and `@DenyAll` annotations on view classes to define the access control rules.
```suggestion
The view-based authorization mechanism uses the `@AnonymousAllowed`, `@PermitAll`, `@RolesAllowed`, and `@DenyAll` annotations on view classes to define the access control rules.
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +This approach is also based on Vaadin's Spring Boot and Spring Security Auto-Configuration.
```suggestion
This approach is also based on Vaadin's Spring Boot and Spring Security autoconfiguration.
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +If you are not using Spring Boot in your Vaadin Flow application, you may need extra configurations to enable this authorization mechanism. `??? the last sentence needs further discussions`
```suggestion
If you are not using Spring Boot in your Vaadin Flow application, you may need extra configurations to enable the authorization mechanism.
// TODO ??? the last sentence needs further discussions
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +.Vaadin Fusion Tip:
```suggestion
.Use of the annotations in Vaadin Fusion
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +.Where to Find the Source Codes
```suggestion
.Source for the complete example code
```

2021-05-18 15:30 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +As mention in the <<Introduction,Introduction>>, this mechanism is based on Spring Security and Vaadin's Spring Boot Auto-Configuration.
```suggestion
As mentioned in the <<introduction,Introduction>>, the mechanism is based on Spring Security and Vaadin's Spring Boot autoconfiguration.
```

2021-05-19 11:48 UTC, magi42 requested changes

2021-05-19 11:48 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +As mentioned in the <<Introduction,introduction>>, the mechanism is based on Spring Security and Vaadin's Spring Boot autoconfiguration.
```suggestion
As mentioned in the <<introduction,Introduction>>, the mechanism is based on Spring Security and Vaadin's Spring Boot autoconfiguration.
```

2021-05-19 11:48 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +To enable this mechanism in a Vaadin Flow Spring Boot application without any security, the followings should be added to the project (if not exist already):
```suggestion
To enable the mechanism in a Vaadin Flow Spring Boot application without any security, the following should be added to the project (if not exist already):
```

2021-05-19 11:51 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +The traditional Spring Security's URL based `HttpSecurity` configurations should not be considered as the security mechanism for securing the views at all, except for the static resources as there is
```suggestion
The traditional Spring Security's URL-based `HttpSecurity` configurations should not be considered as the security mechanism for securing the views at all, except for the static resources as there is no way to load them other than URLs.
```

2021-05-19 11:52 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +The traditional Spring Security's URL based `HttpSecurity` configurations should not be considered as the security mechanism for securing the views at all, except for the static resources as there is
```suggestion
The traditional Spring Security's URL-based [classname]#HttpSecurity# configurations should not be considered as the security mechanism for securing the views at all, except for the static resources as there is no way to load them other than URLs.
```

2021-05-19 12:17 UTC, taefi commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +As mentioned in the <<Introduction,introduction>>, the mechanism is based on Spring Security and Vaadin's Spring Boot autoconfiguration.
I think the first part of <<[first],[second]>> should point to another title in this document (the same case, otherwise shows error), and the second one is the text shown in the text.

2021-05-19 12:24 UTC, magi42 commented
@taefi I hope you're not too confused about our activity here, we're doing a bit language review training with @dougjewsbury.

2021-05-19 12:27 UTC, taefi commented
> @taefi I hope you're not too confused about our activity here, we're doing a bit language review training with @dougjewsbury.

No, that's great! Thanks for the review! 
I just changed the case of `i` to `I` for the <<Introduction,Introduction>> anchor, as the first part of the anchor should be in exact same case of the title it is referring to.

2021-05-19 12:45 UTC, magi42 commented on articles/flow/integrations/spring/view-based-authorization.asciidoc
> +As mentioned in the <<Introduction,introduction>>, the mechanism is based on Spring Security and Vaadin's Spring Boot autoconfiguration.
I think anchor references should be in lower case. AsciiDoc creates IDs automatically from the heading by making it lower case and replacing spaces with dashes, as in https://vaadin.com/docs/latest/guide/running/#running-with-maven . I'd recommend not using the automatic IDs though, but specify the ID manually with [[introduction]], so that changing the title doesn't invalidate the ID.

Well, in this case it's fine and maybe better to use "in the introduction". The normal recommendation is to refer to articles and sections by title, which is a name, such as: "as described in Running with Maven". In this case either is fine.

2021-05-19 19:57 UTC, dougjewsbury approved these changes

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +A complete example project including the source codes of this documentation is available https://github.com/vaadin-learning-center/crm-tutorial/tree/latest[here].
```suggestion
A complete example project, including the source code from this document, is available https://github.com/vaadin-learning-center/crm-tutorial/tree/latest[here].
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Having a login view is one of the basic requirements of many authentication and authorization mechanisms to be able to redirect the anonymous users to that page before giving the access of viewing an
```suggestion
Having a login view is a basic requirement of many authentication and authorization mechanisms, in order to be able to redirect anonymous users to that page before giving access to view any protected resources.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Usage of Vaadin's LoginForm Component
```suggestion
.Usage of Vaadin's LoginForm component
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +In this example, Vaadin's `LoginForm` component is used to make the implementation more brief, but there is no obligation to do so, feel free to implement your own Login view, as you wish.
```suggestion
In this example, we use Vaadin's `LoginForm` component for the sake of brevity in this implementation.
However, there is no obligation to do so; feel free to implement your own Login view, as you wish.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +_As this part of the documentation is based on a Spring Boot project, adding the following dependency is recommended_:
```suggestion
_As this part of the documentation is based on a Spring Boot project, we recommend adding the following dependency_:
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Next step is to have a Spring Security Configuration class that extends `VaadinWebSecurityConfigurerAdapter`.
```suggestion
The next step is to have a Spring Security Configuration class that extends `VaadinWebSecurityConfigurerAdapter`.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +No convention exists for naming this class, so in this documentation it is named as `SecurityConfiguration`, but pay attention to Spring Security annotations.
```suggestion
There is no convention for naming this class, so in this documentation it is named `SecurityConfiguration`.
However, take care with Spring Security annotations.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +A minimal implementation of such class is as follows:
```suggestion
Here is a minimal implementation of such a class:
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Before going any further it worth noticing the presence of `@EnableWebSecurity` and `@Configuration` on top of the above class.
```suggestion
Before we go any further, it is worth noticing the `@EnableWebSecurity` and `@Configuration` annotations on top of the above class.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +As their name imply, they tell the Spring to enable its security features.
```suggestion
As their names imply, they tell Spring to enable its security features.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Next thing to notice is the parent class: `VaadinWebSecurityConfigurerAdapter`.
```suggestion
The next thing to notice is the parent class: `VaadinWebSecurityConfigurerAdapter`.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +As you might be familiar with Spring Boot and Spring Security, you may have seen that you can extend Spring's `WebSecurityConfigurerAdapter` directly and configure a lot of things from scratch, but b
```suggestion
If you are familiar with Spring Boot and Spring Security, you may be aware that you can extend Spring's `WebSecurityConfigurerAdapter` directly and configure a lot of things from scratch.
However, there are some benefits to extending from `VaadinWebSecurityConfigurerAdapter`.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- Default implementation of `configure` methods would take care of all the Vaadin related configurations, for example ignoring the static resources, or to enable the `CSRF` checking while ignoring th
```suggestion
- The default implementation of the `configure` methods takes care of all the Vaadin-related configurations, for example ignoring static resources, or enabling `CSRF` checking while ignoring unnecessary checking for Vaadin internal requests, etc.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +By looking at the implementation of `userDetailsService` method, it is obvious that this is just an in-memory implementation for the sake of briefness in this documentation.
```suggestion
The implementation of `userDetailsService` method is obviously just an in-memory implementation for the sake of brevity in this documentation.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +In a real-world application You can change the Spring Security configuration to use an authentication provider for LDAP, JAAS, and other real world sources. https://dzone.com/articles/spring-security
```suggestion
In a real-world application, you can change the Spring Security configuration to use an authentication provider for LDAP, JAAS, and other real-world sources. https://dzone.com/articles/spring-security-authentication[Read more about Spring Security authentication providers].
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +The most important configuration in the above example, is the call to the `setLoginView(http, LoginView.class);` inside the first configure method.
```suggestion
The most important configuration in the above example is the call to the `setLoginView(http, LoginView.class);` inside the first configure method.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +This is how the view based Access Control mechanism knows where to redirect the users once they attempt to navigate to a protected view.
```suggestion
This is how the view-based access control mechanism knows where to redirect the users when they attempt to navigate to a protected view.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Before providing a usage examples of the access annotations, it would be beneficial to have a closer look at the annotations, and their meaning when applied on a view:
```suggestion
Before we provide some usage examples of the access annotations, it would be useful to have a closer look at the annotations, and their meaning when applied to a view:
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +This is the default, which means if a view is not annotated at all, the `@DenyAll` logic would be applied.
```suggestion
- `@AnonymousAllowed` permits anyone to navigate to the view without any authentication or authorization.
- `@PermitAll` allows any *authenticated* user to navigate to the view.
- `@RolesAllowed` grants access to users having the roles specified in the annotation value.
- `@DenyAll` disallows everyone from navigating to the view.
This is the default, which means that, if a view is not annotated at all, the `@DenyAll` logic is applied.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Therefore, none of the views are accessible, until one of the above annotations (except the `@DenyAll`) is applied to them.
```suggestion
Therefore, none of the views are accessible until one of the above annotations (except `@DenyAll`) is applied to them.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @AnonymousAllowed to enable all users navigating to this view
```suggestion
.Example of using @AnonymousAllowed to enable all users to navigate to this view
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @PermitAll to allow only authenticated users (with any role) navigating to this view
```suggestion
.Example of using @PermitAll to allow only authenticated users (with any role) to navigate to this view
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @RolesAllowed to enable only the users with `ADMIN` role navigating to this view
```suggestion
.Example of using @RolesAllowed to enable only the users with `ADMIN` role to navigate to this view
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +If multiple annotations specified on a single view, the following rules are applied:
```suggestion
If multiple annotations are specified on a single view, the following rules are applied:
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +However, specifying more than one of the above access annotations on a view class in not recommended, as it is confusing and probably has no logical reason to do so.
```suggestion
However, specifying more than one of the above access annotations on a view class is not recommended, as it is confusing and there is probably no logical reason to do so.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +== View Based Access Control in Spring Based Applications
```suggestion
== View-Based Access Control in Spring-Based Applications
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +The configuration steps for a Vaadin Flow Spring application would be quite similar to some steps of the Vaadin Flow application which is based on Spring Boot.
```suggestion
The configuration steps for a Vaadin Flow Spring application are quite similar to those of a Vaadin Flow application which is based on Spring Boot.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- The application obviously should have a login view, an example login view can be found <<Login View,here>>.
```suggestion
- The application should obviously have a login view; you can see an example login view <<Login View,here>>.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Direct Spring Security dependencies that should be added to `pom.xml` file:
```suggestion
.Direct Spring Security dependencies that should be added to the `pom.xml` file:
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +//TODO: provide extra steps for a Spring based application
```suggestion
//TODO: provide extra steps for a Spring-based application
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Again, this is completely similar to the <<Annotating the View Classes,provided examples>> for a Vaadin Flow application based on Spring Boot.
```suggestion
Again, this is very similar to the <<Annotating the View Classes,provided examples>> for a Vaadin Flow application based on Spring Boot.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Mixing any of the view access annotations with Spring's URL based HTTP security (which probably are existing in older Vaadin Spring Boot applications) may result in unwanted access configurations or
```suggestion
Mixing any of the view access annotations with Spring's URL-based HTTP security (which probably exist in older Vaadin Spring Boot applications) may result in unwanted access configurations or unnecessary complications.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Do not mix Spring's URL based HTTP security and View based Access Control on a single view
```suggestion
.Do not mix Spring's URL-based HTTP security and view-based access control on a single view
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Vaadin strongly recommends *not* to mix Spring's URL Pattern based HTTP security and this View-based Access Control mechanism targeting same views, since it may lead to unwanted access configurations
```suggestion
Vaadin strongly recommends *not* mixing Spring's URL-pattern-based HTTP security and this view-based access control mechanism targeting the same views, since it may lead to unwanted access configurations, or at the very least an unnecessary complication in the authorization of views.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +Vaadin Flow applications can use a view-based Access Control mechanism out of the box.
```suggestion
Vaadin Flow applications can use a view-based access control mechanism out of the box.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +The approach of the <<View Based Access Control in Spring Boot Based Applications,first part of this documentation>> is based on Vaadin's Spring Boot and Spring Security autoconfiguration.
```suggestion
The approach of the <<View-Based Access Control in Spring Boot-Based Applications,first part of this documentation>> is based on Vaadin's Spring Boot and Spring Security autoconfiguration.
```

2021-05-19 19:57 UTC, dougjewsbury commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Spring Boot Starter Security dependency that should be added to `pom.xml` file:
```suggestion
.Spring Boot Starter Security dependency that should be added to the `pom.xml` file:
```

2021-05-19 21:14 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- By adding View-Based Access Control mechanism
It is supposed to be this view-based access control, not just `a` view-based access control.

2021-05-20 09:11 UTC, magi42 commented
@taefi You seem to have marked all of Doug's suggestions as resolved, not committed them.

Maybe this PR should have been marked as draft, as it's been evolving quite a bit after opening it. You also don't need to create a PR immediately when you create a feature branch, but make the PR only when it's time for review. Of course in some cases, you'd maybe want to get early comments.

2021-05-20 09:18 UTC, magi42 commented
Oops sorry, I was looking at wrong commit. They are there.

2021-05-20 16:06 UTC, pleku requested changes

2021-05-20 16:06 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +[NOTE]
Use `WARNING:` or `IMPORTANT:` instead

2021-05-20 16:06 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +[role="since:com.vaadin:vaadin@V20 standalone"]
Wrong version, we're building 21 not 20

2021-05-20 16:06 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +Vaadin Flow comes with a built-in view-based access control that can be used as the main access control mechanism, but as mentioned in <<Authentication and Authorization,Authentication and Authorizat
```suggestion
Since Vaadin 21, it is possible to use built-in view-based access control mechanism to secure Flow navigation targets, but as mentioned in <<Authentication and Authorization,Authentication and Authorization>> it is not mandatory to use it, so it is not enabled by default.
```

2021-05-20 16:06 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +            login
Non-blocking nit: extra whitespace that makes IMO no sense

2021-05-20 16:06 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +        .getQueryParameters()
Non-blocking nit: the indent is weird

2021-05-20 18:49 UTC, taefi commented on articles/flow/security/best-practices.asciidoc
> +        .getQueryParameters()
Done.

2021-05-20 18:49 UTC, taefi commented on articles/flow/security/best-practices.asciidoc
> +            login
Done.

2021-05-20 18:49 UTC, taefi commented on articles/flow/security/best-practices.asciidoc
> +[role="since:com.vaadin:vaadin@V20 standalone"]
Thanks! Done.

2021-05-20 18:49 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +[NOTE]
Done.

2021-05-20 18:50 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +[NOTE]
Done.

2021-05-20 18:50 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +
I think since the codes are available in some repository (mentioned somewhere up there) it makes sense to add those numbered bullets.

2021-05-20 18:54 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +However, there are some benefits to extending from `VaadinWebSecurityConfigurerAdapter`.
Yeah, I guess it changed to a `.` in one of the accepted suggestions. Changed it back to `:`.

2021-05-20 18:54 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +            login
Done.

2021-05-20 18:54 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +        .containsKey("error")) {
Done.

2021-05-20 18:54 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +[role="since:com.vaadin:vaadin@V20 standalone"]
Done.

2021-05-20 20:30 UTC, magi42 commented
Since this is still evolving quite a lot, it's maybe quite not ready for review. Please set it ready for review when you think you have finished.

2021-05-20 21:47 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +
Done.

2021-05-21 08:21 UTC, pleku requested changes

2021-05-21 08:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +order: 25
I think the ordering is now weird - IMO this should be after `Routing`. So please move it between `Routing` and `Scopes`.

2021-05-21 08:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- The default implementation of the `configure` methods takes care of all the Vaadin-related configurations, for example ignoring static resources, or enabling `CSRF` checking while ignoring unnecess
Why is this sentence not numbered with code on `configure()` method, like above? IMO it should be

2021-05-21 08:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- The login view can be configured simply via the provided `setLoginView` method.
Why is this sentence not numbered with code like above? IMO it should be

2021-05-21 08:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +<2> The next thing to notice is the parent class: `VaadinWebSecurityConfigurerAdapter`.
I would add the following points as numbered bullets too, but the text needs to be worked still. Maybe some parts moved to after the numbered bullets.

2021-05-21 08:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +public class SecurityConfiguration extends VaadinWebSecurityConfigurerAdapter { // <2>
This should be on two lines as the code line is too long

2021-05-21 09:52 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- The default implementation of the `configure` methods takes care of all the Vaadin-related configurations, for example ignoring static resources, or enabling `CSRF` checking while ignoring unnecess
The idea of indented bullets was that this benefit can be used as the result of inheriting `VaadinWebSecurityConfigurerAdapter`.

Rewrote it in a numbered style, but it has the potential to improve the language.

2021-05-21 09:56 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +public class SecurityConfiguration extends VaadinWebSecurityConfigurerAdapter { // <2>
Done.

2021-05-21 09:56 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +<2> The next thing to notice is the parent class: `VaadinWebSecurityConfigurerAdapter`.
Done, may need some improvements.

2021-05-21 09:56 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +- The login view can be configured simply via the provided `setLoginView` method.
Done.

2021-05-21 09:56 UTC, taefi commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +order: 25
Hmm... Makes more sense. 
Done.

2021-05-24 06:21 UTC, pleku requested changes

2021-05-24 06:21 UTC, pleku commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
>  <2> The next thing to notice is the parent class: `VaadinWebSecurityConfigurerAdapter`.
I would change the lines for bullet two to just:
```suggestion
<2> `VaadinWebSecurityConfigurerAdapter` is a helper class that extends Spring's `WebSecurityConfigurerAdapter` and configures the common Vaadin related Spring security settings. By extending it the view-based access control mechanism is enabled automatically, and no further configurations are needed to enable it. Other of benefits are covered as follows.
```

2021-05-24 09:14 UTC, pleku approved these changes
In my opinion we can merge this and then continue later with additions on how the annotations work with abstract classes and parent layouts.

2021-05-24 09:14 UTC, pleku commented
@magi42 does this need still further review or ?

2021-05-26 10:22 UTC, magi42 commented
@dougjewsbury Could you take a second look at this? There were quite a bit additions to this after your practice review.

In the "Files changed" tab, you should be able to select "Show changes since your last review" in the commits selection.

2021-05-28 13:33 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
>  This is something that is common for all UI frameworks, and not specific to Vaadin.
```suggestion
This is something that is common to all UI frameworks, and not specific to Vaadin.
```

2021-05-28 13:36 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +Since Vaadin 21, it is possible to use built-in view-based access control mechanism to secure Flow navigation targets, but as mentioned in <<Authentication and Authorization,Authentication and Author
```suggestion
Since Vaadin 21, it is possible to use a built-in view-based access control mechanism to secure Flow navigation targets.
However, as mentioned in <<Authentication and Authorization,Authentication and Authorization>>, it is not mandatory to use it, so it is not enabled by default.
```

2021-05-28 13:38 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +To enable and use this mechanism, the following should be added to a Vaadin Flow application (if not exist already):
```suggestion
To enable and use this mechanism, the following should be added to a Vaadin Flow application (if it does not exist already):
```

2021-05-28 13:39 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +- A Service Provider under `META-INF/services` to load above custom ServiceInitListener via Java SPI loading mechanism.
```suggestion
- A Service Provider under `META-INF/services` to load above the custom ServiceInitListener via the Java SPI loading mechanism.
```

2021-05-28 13:41 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +Having a login view is one of the basic requirements of many authentication and authorization mechanisms to be able to redirect the anonymous users to that page before giving the access of viewing an
```suggestion
Having a login view is one of the basic requirements of many authentication and authorization mechanisms.
It serves to redirect anonymous users to that page before granting access to view any protected resources.
```

2021-05-28 13:43 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +In this example, Vaadin's `LoginForm` component is used to make the implementation more brief, but there is no obligation to do so, feel free to implement your own Login view, as you wish.
```suggestion
In this example, Vaadin's `LoginForm` component is used for the sake of brevity.
However, feel free to implement your own login view, if you wish.
```

2021-05-28 13:46 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +To be able to restrict the access to the views, a `BeforeEnterListener` must be registered for the `VaadinService` which initialize and enable the `ViewAccessChecker`:
```suggestion
In order to restrict access to views, a `BeforeEnterListener` must be registered for the `VaadinService`, to initialize and enable the `ViewAccessChecker`:
```

2021-05-28 13:49 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +Now it is ready to intercept the attempts for entering to all views.
```suggestion
<1> `ViewAccessChecker`, which is at the core of this access control mechanism, is instantiated.
<2> `ViewAccessChecker` is enabled. Note that it is not enabled by default.
<3> `LoginView` class is set to the `viewAccessChecker` instance. Now it knows where to redirect unauthenticated users.
<4> The `viewAccessChecker` instance is set as the `BeforeEnterListener` in the overridden `serviceInit` method.
Now it is ready to intercept attempts to enter all views.
```

2021-05-28 13:50 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +However, the above class still needs to be loaded, so it is recommended to follow the instructions of the next step.
```suggestion
However, the above class still needs to be loaded, so we recommend following the instructions in the next step.
```

2021-05-28 13:51 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +To enable Java SPI loading mechanism to load the above `ViewAccessCheckerInitializer` as the `VaadinServiceInitListener`, it is needed to do the following:
```suggestion
To enable the Java SPI loading mechanism to load the above `ViewAccessCheckerInitializer` as the `VaadinServiceInitListener`, do the following:
```

2021-05-28 13:52 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +- Under `resources/META-INF/services` directory, create a file named exactly as:
```suggestion
- Under `resources/META-INF/services` directory, create a file named exactly:
```

2021-05-28 13:53 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +For example, if `ViewAccessCheckerInitializer` class is in `org.vaadin.example.security` package, the following value should be in the file:
```suggestion
For example, if the [classname]#ViewAccessCheckerInitializer# class is in the `org.vaadin.example.security` package, the following value should be in the file:
```

2021-05-28 13:54 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +This Service Provider config file would trigger Java SPI loading mechanism to load `ViewAccessCheckerInitializer` during the application startup.
```suggestion
This Service Provider config file triggers the Java SPI loading mechanism to load `ViewAccessCheckerInitializer` during application startup.
```

2021-05-28 13:55 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +Before providing a usage examples of the access annotations, it would be beneficial to have a closer look at the annotations, and their meaning when applied on a view:
```suggestion
Before we see some examples of access annotations, it is worth having a closer look at the annotations, and their meaning when applied to a view:
```

2021-05-28 13:58 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +This is the default, which means if a view is not annotated at all, the `@DenyAll` logic would be applied.
```suggestion
- [classname]#@AnonymousAllowed# permits anyone to navigate to the view without any authentication or authorization.
- [classname]#@PermitAll# allows any *authenticated* user to navigate to the view.
- [classname]#@RolesAllowed# grants access to users having the roles specified in the annotation value.
- [classname]#@DenyAll# disallows everyone from navigating to the view.
This is the default, which means that, if a view is not annotated at all, the [classname]#@DenyAll# logic is applied.
```

2021-05-28 13:58 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @AnonymousAllowed to enable all users navigating to this view
```suggestion
.Example of using @AnonymousAllowed to enable all users to navigate to this view
```

2021-05-28 13:59 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @PermitAll to allow only authenticated users (with any role) navigating to this view
```suggestion
.Example of using @PermitAll to allow only authenticated users (with any role) to navigate to this view
```

2021-05-28 13:59 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @RolesAllowed to enable only the users with `ADMIN` role navigating to this view
```suggestion
.Example of using @RolesAllowed to enable only users with the `ADMIN` role to navigate to this view
```

2021-05-28 14:00 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +However, by navigating to `http://localhost:8080/private` or `http://localhost:8080/admin` the user would be redirected to the specified `LoginView`.
```suggestion
Now, if the application is started by navigating to `http://localhost:8080`, `PublicView` contents should be available without any authentication.
However, by navigating to `http://localhost:8080/private` or `http://localhost:8080/admin`, the user is redirected to the specified `LoginView`.
```

2021-05-28 14:01 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +// TODO: Consider adding more details and snippet codes to showcase how the followings can be achieved:
```suggestion
// TODO: Consider adding more details and snippet code to showcase how the following can be achieved:
```

2021-05-28 14:03 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
> +However, specifying more than one of the above access annotations on a view class in not recommended, as it is confusing and probably has no logical reason to do so.
```suggestion
However, we do not recommend specifying more than one of the above access annotations on a view class.
It is confusing and probably has no logical purpose.
```

2021-05-28 14:04 UTC, dougjewsbury commented on articles/flow/security/best-practices.asciidoc
>  The server is always aware of your application state. Compared to client side applications, this means that the server is aware of what is currently visible on the end-user's screen. Hence Vaadin den
```suggestion
The server is always aware of your application state. 
Compared to client-side applications, this means that the server is aware of what is currently visible on the end user's screen. 
Hence, Vaadin denies actions to components that are not currently visible on the screen, or those that have been disabled on the server.
```

2021-06-01 13:26 UTC, mshabarov approved these changes

2021-06-01 13:28 UTC, mshabarov commented
@magi42 @dougjewsbury do you have any more comments? Otherwise I believe we can merge this PR.

2021-06-03 13:38 UTC, magi42 requested changes

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +If your Vaadin Flow application is based on Spring Boot, we strongly recommend following the dedicated documentation on using <<{articles}/flow/integrations/spring/view-based-access-control#, View-Ba
```suggestion
See <<{articles}/flow/integrations/spring/view-based-access-control#, View-Based Access Control>> for detailed information about enabling the access control mechanism in Vaadin Flow Spring Boot applications.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +- A Login view.
```suggestion
- A login view.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +- A Service Provider under `META-INF/services` to load above the custom ServiceInitListener via the Java SPI loading mechanism.
```suggestion
- A Service Provider under `META-INF/services` to load above the custom [classname]#ServiceInitListener# via the Java SPI loading mechanism.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.`LoginView.java`
```suggestion
.[filename]#LoginView.java#
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +However, feel free to implement your own login view, if you wish.
```suggestion
In this example, Vaadin's Login Form component is used for the sake of brevity.
However, feel free to implement your own login view, if you wish.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.ViewAccessCheckerInitializer.java
```suggestion
.[filename]#ViewAccessCheckerInitializer.java#
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +
```suggestion
+
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +
```suggestion
+
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.Text value that should be the `com.vaadin.flow.server.VaadinServiceInitListener` file:
```suggestion
.Text value that should be in the `com.vaadin.flow.server.VaadinServiceInitListener` file:
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +More information on this can be found <<{articles}/flow/advanced/service-init-listener#,here>>.
```suggestion
More information on this can be found in <<{articles}/flow/advanced/service-init-listener#,VaadinServiceInitListener>>.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @AnonymousAllowed to enable all users to navigate to this view
```suggestion
.Example of using [classname]#@AnonymousAllowed# to enable all users to navigate to this view
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @PermitAll to allow only authenticated users (with any role) to navigate to this view
```suggestion
.Example of using [classname]#@PermitAll# to allow only authenticated users (with any role) to navigate to this view
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +.Example of using @RolesAllowed to enable only users with the `ADMIN` role to navigate to this view
```suggestion
.Example of using [classname]#@RolesAllowed# to enable only users with the `ADMIN` role to navigate to this view
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +title: View Based Access Control
```suggestion
title: View-Based Access Control
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +You can find out more about security in a Vaadin Fusion application <<{articles}/fusion/security/configuring#,here>>.
```suggestion
It is described in <<{articles}/fusion/security/configuring#,Configuring Security>> in Fusion documentation.
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +A complete example project, including the source code from this document, is available https://github.com/vaadin-learning-center/crm-tutorial/tree/latest[here].
```suggestion
A complete example project, including the source code from this document, is available at https://github.com/vaadin-learning-center/crm-tutorial/tree/latest[`github.com/vaadin-learning-center/crm-tutorial`].
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +[TIP]
```suggestion
```
Too many admonitions in the page.

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.`LoginView.java`
```suggestion
.[classname]#LoginView.java#
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.`SecurityConfiguration.java`
```suggestion
.[filename]#SecurityConfiguration.java#
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @AnonymousAllowed to enable all users to navigate to this view
```suggestion
.Example of using [classname]#@AnonymousAllowed# to enable all users to navigate to this view
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @PermitAll to allow only authenticated users (with any role) to navigate to this view
```suggestion
.Example of using [classname]#@PermitAll# to allow only authenticated users (with any role) to navigate to this view
```

2021-06-03 13:38 UTC, magi42 commented on articles/flow/integrations/spring/view-based-access-control.asciidoc
> +.Example of using @RolesAllowed to enable only the users with `ADMIN` role to navigate to this view
```suggestion
.Example of using [classname]#@RolesAllowed# to enable only the users with `ADMIN` role to navigate to this view
```

2021-06-03 16:04 UTC, magi42 approved these changes

2021-06-03 16:06 UTC, merged