feature: add scroller examples
vaadin/docs pull request #46
Opened 2020-11-18 15:27 UTC by yuriy-fix

2020-11-19 09:48 UTC, tomivirkki commented on frontend/demo/component/scroller/scroller-both.ts
> +          <img src="https://cdn2.hubspot.net/hubfs/1840687/Pages/index/taskmob-laptop-mockup.png" alt="Application">
IIRC external resources shouldn't be used (the self-hosted docs should work even without internet access). That means the image should be added to the Java project resources and used through StreamResource. The TS demo should use dynamic import for the image file (so it only gets loaded once this example is accessed).

The element should probably also have default height/width so the example doesn't depend on the image bounds once it's loaded.

2020-11-19 15:06 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-both.ts
> +          <img src="https://cdn2.hubspot.net/hubfs/1840687/Pages/index/taskmob-laptop-mockup.png" alt="Application">
Updated.
Have hidden the logic for importing the image on TS example to hide the long path to the image from user.

2020-11-20 09:20 UTC, tomivirkki requested changes

2020-11-20 09:20 UTC, tomivirkki commented on frontend/demo/component/scroller/scroller-basic.ts
> +        <div id="header">
`<vaadin-horizontal-layout>` would be ideal for header & footer (and vertical layout for the body?). Using Vaadin layouts we could avoid much of the css now required for the padding & spacing effect. Not a blocker for this PR.

2020-11-20 09:20 UTC, tomivirkki commented on frontend/demo/component/scroller/scroller-both.ts
> +      <vaadin-scroller style="height: 300px; width: 300px;">
Width could be 100%

2020-11-20 09:20 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/scroller/ScrollerMobile.java
> +    auditBtn.getStyle().set("margin", "2px");
Use a horizontal layout with spacing

2020-11-20 14:21 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-basic.ts
> +      <style>
Updated.

2020-11-20 14:21 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-basic.ts
> +          width: 50%;
Used `lumo` variable for that one.

2020-11-20 14:21 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-mobile.ts
> +        <div style="width: 450px;">
Good point! Updated.

2020-11-20 14:21 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-both.ts
> +      <vaadin-scroller style="height: 300px; width: 300px;">
Updated.

2020-11-20 14:21 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/component/scroller/ScrollerMobile.java
> +    auditBtn.getStyle().set("margin", "2px");
Updated.

2020-11-23 08:20 UTC, tomivirkki commented on frontend/demo/component/scroller/scroller-basic.ts
> +          width: 50%;
Fixed width will make the container overflow on narrow viewports
<img width="333" alt="Screenshot 2020-11-23 at 10 08 02" src="https://user-images.githubusercontent.com/1222264/99940002-03509100-2d74-11eb-917b-2fb037efabd1.png">

Same thing with "Mobile" example. Note that this example uses fixed px value (300px) while basic uses lumo-size with a multiplier.
<img width="328" alt="Screenshot 2020-11-23 at 10 17 22" src="https://user-images.githubusercontent.com/1222264/99940583-1b74e000-2d75-11eb-9dc2-0df13806976b.png">


For both cases, use `max-width: 100%;` to avoid overflowing (and having two scrollbars). In the latter example, you can drop the CSS padding from the scroller and use the `margin` variant on the horizontal layout.

2020-11-23 10:11 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/component/scroller/ScrollerBoth.java
> +            () -> getFileStream("src/main/resources/images/scroller-both-img.png"));
Can't use "/src/main/..." because it only exists dev-time. You can see the result with `npm run build && npm run serve`.

NIT: The name of the image is specific to this one example. It should have a generic name so it could be used anywhere

2020-11-23 11:23 UTC, jouni commented
I would prefer something like a photograph for the image (vs the laptop with taskmob running on it). Makes it more likely to be suitable for custom design systems as well.

Perhaps [something from Turku](https://unsplash.com/photos/t4aQJwzlDi0), or [northern lights](https://unsplash.com/photos/FdEb6KaVIq4), or a [reindeer](https://unsplash.com/photos/5AJIcop-l84)?

2020-11-30 12:28 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/component/scroller/ScrollerBoth.java
> +            () -> getFileStream("src/main/resources/images/scroller-both-img.png"));
Good point! Updated to use `getResourceAsStream` which is working in production as well. 
In addition, have checked the TS import and that one works in both cases.

2020-11-30 12:29 UTC, yuriy-fix commented on frontend/demo/component/scroller/scroller-basic.ts
> +          width: 50%;
`max-width` applied and `margin` theme added

2020-11-30 13:20 UTC, tomivirkki commented on articles/design-system/components/scroller/index.asciidoc
> +https://github.com/vaadin/vaadin-ordered-layout/releases/tag/v{moduleNpmVersion:vaadin-ordered-layout}[{moduleNpmVersion:vaadin-ordered-layout}]
Page links should be updated to aligh with latest master, see https://github.com/vaadin/docs/commit/83fdb81ece9d97809bd6f939f401e668aa0a5146

2020-11-30 13:36 UTC, yuriy-fix commented on articles/design-system/components/scroller/index.asciidoc
> +https://github.com/vaadin/vaadin-ordered-layout/releases/tag/v{moduleNpmVersion:vaadin-ordered-layout}[{moduleNpmVersion:vaadin-ordered-layout}]
Updated.

2020-11-30 13:46 UTC, tomivirkki commented on articles/design-system/components/scroller/index.asciidoc
> +https://github.com/vaadin/vaadin-ordered-layout/releases/tag/v{moduleNpmVersion:vaadin-ordered-layout}[{moduleNpmVersion:vaadin-ordered-layout}]
The Flow version link still links to 404. It should link to the vaadin-flow-components repo

2020-11-30 15:01 UTC, jouni commented
Should still update the smaller screenshot image, on the design-system/index page.

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +When the scroll position is set to vertical, the user can scroll vertically if the content overflows the container vertically.
```suggestion
When the scroll position is vertical, the user can scroll vertically if the content overflows the container vertically.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +When the scroll position is set to horizontal, the user can scroll horizontally if the content overflows the container horizontally.
```suggestion
When the scroll position is horizontal, the user can scroll horizontally if the content overflows the container horizontally.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +Content that overflows horizontally is clipped and inaccessible, so the width of the content should be set to 100%.
```suggestion
Content that overflows horizontally is clipped and inaccessible, so the width of the content should be 100%.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +Content that overflows vertically is clipped and inaccessible, so the height of the content should be set to 100%.
```suggestion
Content that overflows vertically is clipped and inaccessible, so the height of the content should be 100%.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +Horizontal scrolling should be used with caution, as it is much less common and may be difficult for users to recognize and use, especially on non-mobile devices.
```suggestion
Use horizontal scrolling with caution, as it is much less common and may be difficult for users to recognize and use, in particular on non-mobile devices.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +We recommend using Buttons to help users notice and navigate horizontally scrollable sections.
```suggestion
It is recommended to use Buttons to help users notice and navigate horizontally scrollable sections.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +For horizontally scrollable lists, it is considered good practice to indicate how many list items there are and which items the user is currently viewing.
```suggestion
For horizontally scrollable lists, it is considered good practice to display how many list items there are and which items the user is viewing at the moment.
```

2020-12-01 08:58 UTC, anezthes commented on articles/design-system/components/scroller/index.asciidoc
> +When the scroll position is set to *Both* (default), the user can scroll vertically and horizontally if the content overflows in both directions.
```suggestion
When the scroll position is *Both* (default), the user can scroll vertically and horizontally if the content overflows in both directions.
```

2020-12-01 15:01 UTC, tomivirkki approved these changes

2020-12-01 15:03 UTC, merged