chore: adapt TS examples and templates to Lit 2
vaadin/docs pull request #461
Opened 2021-05-14 08:09 UTC by denis-anisimov

fixes vaadin/flow#10872

2021-05-27 06:59 UTC, haijian-vaadin requested changes

2021-05-27 06:59 UTC, haijian-vaadin commented on articles/guide/upgrading.asciidoc
> +=== Lit Templates are using Lit 2
Change to title case? Lit Templates Are Using Lit 2, as reported by Vale?

2021-05-27 13:08 UTC, magi42 requested changes
Reviewed `upgrading.asciidoc`. A bit delicate to do without preview, so need to check that carefully.

2021-05-27 13:08 UTC, magi42 commented on articles/guide/upgrading.asciidoc
> +The new Lit 2.0 is used for Lit templates in the latest Vaadin version.
```suggestion
New Lit 2.0 is used for Lit templates in the latest Vaadin version.
```

2021-05-27 13:08 UTC, magi42 commented on articles/guide/upgrading.asciidoc
> +----
```suggestion
Most of the necessary changes are with imports.

You need to change imports of `html` and [classname]#LitElement# from:

[source,typescript]
----
import { html, LitElement } from 'lit-element';
----

to:

[source,typescript]
----
import { html, LitElement } from 'lit';
----

Change `customElement` and `property` decorator imports from:

[source,typescript]
----
import { customElement, property } from 'lit-element';
----

to

[source,typescript]
----
import { customElement, property } from 'lit/decorators.js';
----

If you are using `repeat` directive imports, change them from:

[source,typescript]
----
import { repeat } from 'lit-html/directives/repeat.js';
----

to

[source,typescript]
----
import { repeat } from 'lit/directives/repeat.js';
----
```

2021-05-27 13:08 UTC, magi42 commented on articles/guide/upgrading.asciidoc
>  These instructions apply when upgrading from a version before Vaadin 20.
```suggestion
The following instructions apply when upgrading from a version before Vaadin 20.
```

2021-05-28 09:39 UTC, Haprog commented on articles/guide/upgrading.asciidoc
> +----
These imports are just examples of different type of imports and how they should be changed. This is not an exhaustive list so mentioning only "Change `customElement` and `property` decorator imports" or "If you are using `repeat` directive imports" explicitly is not good.

I'll use your suggestion as a basis but make some changes to the text content to make it more clear.

2021-05-28 09:41 UTC, magi42 commented on articles/guide/upgrading.asciidoc
> +----
OK, the main point was that the text was formatted like it was a really long sentence with code examples in between.

2021-05-28 10:34 UTC, Haprog commented on articles/guide/upgrading.asciidoc
> +----
Updated.

2021-05-28 10:36 UTC, Haprog commented
@magi42 Thanks for the AsciiDoc review! I applied most of your suggestions directly and did some minor updates to the text content about updating the Lit imports.

2021-05-28 10:47 UTC, haijian-vaadin approved these changes

2021-05-28 11:05 UTC, magi42 requested changes
Just couple of commas missing there. Otherwise looks great.

2021-05-28 11:05 UTC, magi42 commented on articles/guide/upgrading.asciidoc
> +For example change imports of `html` and [classname]#LitElement# from:
```suggestion
For example, change imports of `html` and [classname]#LitElement# from:
```

2021-05-28 11:05 UTC, magi42 commented on articles/guide/upgrading.asciidoc
> +For example change `customElement` and `property` decorator imports from:
```suggestion
For example, change `customElement` and `property` decorator imports from:
```

2021-05-28 11:14 UTC, Haprog commented
@magi42 I committed your latest suggestions.

2021-05-28 11:16 UTC, magi42 approved these changes

2021-05-28 11:27 UTC, Haprog approved these changes

2021-05-28 11:57 UTC, merged