feat: Add @RouteScope docs for Spring add-on
vaadin/docs pull request #469
Opened 2021-05-17 12:04 UTC by pleku

Fixes vaadin/flow#10900

2021-05-18 08:54 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +The owner is specified wit the `@RouteScopeOwner` _qualifier_ which takes as an argument the routing component that the bean has its lifecycle tied into.
```suggestion
The owner is specified with the `@RouteScopeOwner` _qualifier_ which takes as an argument the routing component that the bean has its lifecycle tied into.
```

2021-05-18 08:56 UTC, denis-anisimov requested changes

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +With Spring Boot, you need to mark your Vaadin related bean classes with the https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Component.html[`@Component
Since `Component` exists in Flow there is a `SpringComponent` which worth to mention here.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Unlike with earlier Vaadin versions 7 and 8, `UIScope` beans are not preserved when the `@PreserveOnRefresh` annotation is used and the browser is refreshed.
It's worth to shortly mention may be why: because `UI` instance is not preserved (so UI scoped beans mapped to it are also lost).

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +To be able to preserve the beans, you need to use `@RouteScope` instead, as described in <<routescope.preserve, the next chapter>>.
This is a workaround.
I would recommend do not give a false impression that this is just a direct replacement for UIScope which is preserved in refresh.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
This example uses a bean (not a component) and it requires an explicit injection point.

Another example which ( I would say even more important) is to annotate e.g. the bottom navigation target which allows to reuse the navigation target component even though the intermediate layouts may be recreated.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +This allows you to inject a bean to a routing component once, and keep the bean the same for the lifecycle of the component.
This is confusing for me.
As I understand this sentence describes missing owner qualifier behavior.
And this is prototype scope.
As a result : it has no sense to use route scope without owner since there is already prototype scope (at least without my latest PR).

`This allows you to inject a bean to a routing component once, and keep the bean the same for the lifecycle of the component.` : it's confusing since this has no relation to the scope. Something injected is managed by Java object reference rules.
It's a direct reference to the object. So it may not disappear (and GCed as a result) until the instance which refers to it is alive.
This is just regular Java objects behavior and this description makes a wrong impression at least for me.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +This makes sense when you don't want to keep the beans in the memory when the route component is not active because it for example is not opened frequently or consumes a lot of memory on the server.
I would say : it doesn't make any sense considering routing.
There is ready-made prototype scope . If prototype scope semantic is needed it should be used directly instead route scope with confusing behavior.

(again : assuming my PR is not merged).

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Thus using `@RouteScope` without clarifying an owner makes it possible to replace the `@ViewScope` from Vaadin 7 or 8.
I'm not sure : does it assume my latest PR is merged ?

Without PR the prototype scope is not a replacement for `ViewScope` .
With the PR the prototype scope may not be mentioned here and should be removed.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Thus using `@RouteScope` without clarifying an owner makes it possible to replace the `@ViewScope` from Vaadin 7 or 8.
It's possible to get a bean via `ApplicationContext` :

```

@Autowired
private ApplicationContext context;

private void someMethod(){

context.getBeanByType(SomeBean.class);
}
```

Prototype scope: every time `context.getBeanByType(SomeBean.class)` returns a new instance
`ViewScope` : until we are inside the same view the instance will be the same.

So prototype scope (and route scope without owner) is not a replacement anyhow for `ViewScope`.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +*Example*: `@RouteScope` without owner behaves like legacy Vaadin `@ViewScope`
No, it doesn't without my PR.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +        this.presenter = presenter;
It has no any relation to the scopes (unless they are too wide, like UIScope).
Prototype scope will give the same result.

2021-05-18 08:56 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +** In this example, a new `UserProfilePresenter` bean is created every time when the `UserProfileView` view is opened.
Like with prototype scope.

If I use `ApplicationContext::getBeanByType` instead direct injection the example will be broken.

2021-05-18 09:11 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +The owner is specified wit the `@RouteScopeOwner` _qualifier_ which takes as an argument the routing component that the bean has its lifecycle tied into.
Done

2021-05-18 09:11 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +With Spring Boot, you need to mark your Vaadin related bean classes with the https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Component.html[`@Component
Done

2021-05-18 09:14 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +Unlike with earlier Vaadin versions 7 and 8, `UIScope` beans are not preserved when the `@PreserveOnRefresh` annotation is used and the browser is refreshed.
Done

2021-05-18 09:15 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +To be able to preserve the beans, you need to use `@RouteScope` instead, as described in <<routescope.preserve, the next chapter>>.
Done - it is explained more later on and this is now a note linking to it

2021-05-18 09:16 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
Done

2021-05-18 09:22 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +This allows you to inject a bean to a routing component once, and keep the bean the same for the lifecycle of the component.
It was outdated since it was not updated after the decision from later on to not require the owner. And you're right that it misses the point. Fixed to highlight the semantics and usage better

2021-05-18 09:25 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +This makes sense when you don't want to keep the beans in the memory when the route component is not active because it for example is not opened frequently or consumes a lot of memory on the server.
Done (removed)

2021-05-18 09:27 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +Thus using `@RouteScope` without clarifying an owner makes it possible to replace the `@ViewScope` from Vaadin 7 or 8.
Yes and no - in case of constructor injection and then storing the instance - it is replacement, but it is not the same.
Fixed (taking into account that your PR is merged).

2021-05-18 09:29 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +** In this example, a new `UserProfilePresenter` bean is created every time when the `UserProfileView` view is opened.
True, but it is not used in the example (and not sure how much it would be used anyway).
But it makes sense to merge your PR as I think it clearly improves things.

2021-05-18 09:32 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +        this.presenter = presenter;
The code example is based on the pattern from the legacy bakery and it works by happenstance due to prototype scope... but like pointed out elsewhere it would be broken in case something relied on injecting the bean elsewhere via application context or using method injection or in case it depends on destruction - so it is again proof to your PR

2021-05-18 09:51 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +*Example*: `@RouteScope` without owner behaves like legacy Vaadin `@ViewScope`
Yes and it should be merged.

2021-05-18 10:05 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +When the `@RouteScope` bean itself is a router component, the owner can be any parent `RouterLayout` in the route chain hierarchy, or the bean itself.
Is it worth to mention that the `@RouteScopeOwner` is optional for router components?

2021-05-18 10:27 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Without the owner qualifier, the owner is the currently active routing component at the time of injection.
> Without the owner qualifier, the owner is the currently active routing component at the time of injection.

This feature is not merged yet, so may be temporary disable this sentence?

2021-05-18 10:33 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +If you store a `RouteScope` bean into a wider scope bean, the stored bean instance is not automatically replaced.
> the stored bean instance is not automatically replaced.

This sounds like a limitation and may raise a feeling that Flow wants automatically replace it, but it can't. Would it be better to just say that the 'narrower-scoped' bean would extend its lifespan to 'wider-scoped' bean it is being injected to.

2021-05-18 14:33 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Without the owner qualifier, the owner is the currently active routing component at the time of injection.
However, skip this comment, as other comment says we are about to merge PR revealing this.

2021-05-18 14:34 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +When the `@RouteScope` bean itself is a router component, the owner can be any parent `RouterLayout` in the route chain hierarchy, or the bean itself.
It is described in other section, so maybe not needed.

2021-05-19 06:19 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
Am I missing something or it's not committed ?
I cannot find any route chain component annotated with `RouteScopeOwner`

2021-05-19 06:19 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +The bean remains in scope for as long as the routing component stays active.
>as the routing component

to avoid confusion which we already have  I suggest to emphasize that this is a route navigation target (not some component in the routing chain).

2021-05-19 09:05 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +The bean remains in scope for as long as the routing component stays active.
Done

2021-05-19 09:05 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +If you store a `RouteScope` bean into a wider scope bean, the stored bean instance is not automatically replaced.
Actually it will not go like that with the most recent changes after not requiring the owner - since the route scoped bean will not be in prototype scope but always have an owner, it should be destroyed once the owner is removed.

2021-05-19 09:05 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +Without the owner qualifier, the owner is the currently active routing component at the time of injection.
I think it is so clear that we merge it (based on other discussions in this PR) that I won't remove it.

2021-05-19 09:05 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +When the `@RouteScope` bean itself is a router component, the owner can be any parent `RouterLayout` in the route chain hierarchy, or the bean itself.
I can't imagine why would you make a routing component `@RouteScope` without any owner. I sense this will only lead into problems in the end. I would not mention anything about this, reformatted the existing text a bit.

2021-05-19 09:13 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
Sorry I meant that there is an explicit injection point for the bean in the components.

> Another example which ( I would say even more important) is to annotate e.g. the bottom navigation target which allows to reuse the navigation target component even though the intermediate layouts may be recreated.

Yes, this might be better, maybe I could introduce it here

2021-05-19 09:37 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
Now it is done - I think it works fine here to showcase the difference between the child views

2021-05-19 10:01 UTC, mshabarov requested changes
As discussed, let's marks route scope sections as available since V21

2021-05-19 10:01 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +=== RouteScope and RouteScopeOwner
```suggestion
[role="since:com.vaadin:vaadin@V21"]
=== RouteScope and RouteScopeOwner
```

2021-05-19 10:01 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +To be able to preserve the beans on refresh, you need to use `@RouteScope` instead, as described in <<routescope.preserve, the next chapter>>.
```suggestion
To be able to preserve the beans on refresh, you need to use `@RouteScope` instead (available since V21), as described in <<routescope.preserve, the next chapter>>.
```

2021-05-19 11:16 UTC, mshabarov approved these changes

2021-05-19 14:15 UTC, denis-anisimov commented on articles/flow/integrations/spring/scopes.asciidoc
> +@RouteScopeOwner(ParentView.class)
I still don't see any component annotated with `@RouteScope` and `@RouteScopeOwner` .
Only autowired CTOR parameters.

2021-05-20 10:32 UTC, mshabarov approved these changes

2021-05-20 10:52 UTC, merged