chore: explain how RouteScope can be used instead of ViewScope
vaadin/docs pull request #495
Opened 2021-05-21 10:56 UTC by denis-anisimov

part of vaadin/spring#508

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-05-28 09:59 UTC, magi42 requested changes
Fixed some formatting a bit, but there were a couple of sentences that I couldn't understand. Please try to explain somehow more clearly.

2021-05-28 09:59 UTC, magi42 commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +of course explicitly but that requires one extra line.
```suggestion
The easiest way to migrate Spring views is to wrap them in `MprRouteAdapter<? extends View>` and then define a Flow navigation target for them with [classname]#@Route#.
There is no need to annotate Flow navigation target or `View` anyhow.
Starting from Vaadin 21, [classname]#@RouteScope#  without [classname]#@RouteScopeOwner# annotation can be used as a replacement for [classname]#@ViewScope#.
The bean within [classname]#@RouteScope# (without specified [classname]#@RouteScopeOwner#) stays preserved until the current navigation target/view is active (attached).
It is possible to use [classname]#@RouteScopeOwner# explicitly, but that requires an extra line.
```
Edited to one-sentence-per-line, but I don't understand the meaning of the "no need to annotate ... anyhow" sentence. "Anyhow" looks really odd there. I couldn't understand the first line either, but here's my wild guess. Please check and correct. Vaadin version references should be avoided and the version tag used. You may need to restructure the text to use one.

2021-05-28 09:59 UTC, magi42 commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +Here is an example of using `@RouteScope`:
```suggestion
In the following is an example of using [classname]#@RouteScope#:
```

2021-05-28 14:21 UTC, mshabarov requested changes

2021-05-28 14:21 UTC, mshabarov commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +component which wraps the view via `MprRouteAdapter<? extends View>`. There is no
> There is no need to annotate Flow navigation target or `View` anyhow.

But it requires at least `@Route` annotation, or what is the purpose of this sentence? Could you please clarify more.

2021-06-03 07:24 UTC, mshabarov commented
@denis-anisimov did you have a chance to take a look on comments? Please let me know your opinion, so as we can proceed further with this PR.

2021-06-18 06:42 UTC, denis-anisimov commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +of course explicitly but that requires one extra line.
First line:
- there are several ways to use old FW8 views in Flow (along with Navigator). This sentence is based on an existing sentence above : Any @SpringView should be updated to a Flow Route by wrapping them as a MprRouteAdapter<? extends View> or re-writing it to be a Flow Component. See Upgrading Views to Flow Routes for details.
- it just chooses the one way of migrating as the simplest.

`anyhow`: my English skills are terrible so it might be that this word cannot be used here. It's fine.
What I wanted to say : there is no need to add some extra annotation to a Flow navigation target or View.

2021-06-18 06:44 UTC, denis-anisimov commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +component which wraps the view via `MprRouteAdapter<? extends View>`. There is no
It says that there is no need to use _EXTRA_ annotations.
As it requires in FW8 case.

2021-06-18 06:48 UTC, denis-anisimov commented on articles/tools/mpr/introduction/3-spring-boot.asciidoc
> +The easiest way to migrate Spring views is to use Flow `@Route` navigation target
_should be updated_ means that we suggest the _most preferable_ or the only one way of doing the things.

The previous sentence suggest  `MprRouteAdapter` as one way and then there is _OR_.

I'm trying to explain here that the first suggestion is the _easiest_.

2021-06-18 06:51 UTC, denis-anisimov commented
Sorry, docs PR produces a lot of spam so I have filter from them and I'm missing the updates from docs PRs.
Also I don't understand the validation errors at all and the review starts after quite a long of time so as a result PR stays abandoned.

2021-06-18 07:45 UTC, mshabarov approved these changes

2021-06-21 11:17 UTC, pleku commented
@magi42 please take a look again if the changes are enough.

2021-06-21 12:43 UTC, magi42 commented
Sorry, I got stuck with this because I can't understand what the text tries to say.

2021-06-21 13:18 UTC, magi42 approved these changes

2021-06-21 13:20 UTC, magi42 commented
@mshabarov OK I rewrote the two sentences so that they are maybe more understandable. Please check that it's factually correct, and go ahead and merge.

2021-06-21 14:31 UTC, mshabarov approved these changes

2021-06-22 11:11 UTC, merged