Update configuring.asciidoc
vaadin/docs pull request #497
Opened 2021-05-21 15:32 UTC by dougjewsbury

## Description

Minor cosmetic edits

Fixes # (issue)

## Type of change

Minor cosmetic edits

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

2021-05-21 20:06 UTC, magi42 approved these changes
Maybe the name of the PR could be something more descriptive, such as "Language fixes to configuring Fusion security".

Note that more typically you want to edit a bunch of files, such as the entire Fusion security section. This is OK as well, as long as it doesn't cause too many PRs.

Ah, I couldn't comment on the Vale error lines, but the one sentence per line errors come from the period in the file names. File names should be given with the `filename` style, such as `[filename]#CounterEndpoint.java#`.

2021-05-21 20:08 UTC, magi42 commented
I left the AsciiDoc label not-OK so that this doesn't accidentally get merged before resolving the discussion.

2021-05-24 16:44 UTC, dougjewsbury reviewed
Response to reviewer comments.

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
> +if not specified in Java code explicitly, before invoking an endpoint method, the presence of a `Principal` object in the request is required.
```suggestion
if not specified in Java code explicitly, a `Principal` object must be present in the request before invoking an endpoint method.
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
>  * `@PermitAll`
```suggestion
* [classname]#@PermitAll#
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
>  * `@RolesAllowed`
```suggestion
* [classname]#@RolesAllowed#
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
>  * `@DenyAll`
```suggestion
* [classname]#@DenyAll#
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
>  * `@AnonymousAllowed`
```suggestion
* [classname]#@AnonymousAllowed#
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
> +If it is required to know, on the client side, whether a user is authenticated, please read the <<authentication#, Checking Authentication>> article.
```suggestion
If it is required to know, on the client side, whether a user is authenticated, please read <<authentication#, Checking Authentication>>.
```

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
> +If it is required to know, on the client side, whether a user is authenticated, please read the <<authentication#, Checking Authentication>> article.
Yup. That makes good sense to me.

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
>  * `@PermitAll`
Yes, fine. I hope I've done that correctly.

2021-05-24 16:44 UTC, dougjewsbury commented on articles/fusion/security/configuring.asciidoc
> +Vaadin endpoints are protected from CSRF attacks using the same approach as the rest of Vaadin. See the <<{articles}/flow/security/vulnerabilities#cross-site-request-forgery-csrf-xsrf, Cross-Site Req
```suggestion
Vaadin endpoints are protected from CSRF attacks using the same approach as the rest of Vaadin. See <<{articles}/flow/security/vulnerabilities#cross-site-request-forgery-csrf-xsrf, Cross-Site Request Forgery>> in the security guide for more details.
```

2021-05-26 09:53 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +For example, [methodname]#VaadinWebSecurityConfigurerAdapter.configure(http)# requires all requests but to be authenticated, except the Vaadin internal ones.
There’s something wrong with this sentence ("...all request but to be authenticated, except...").

2021-05-26 09:53 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +In an analogous way, the matcher for static resources to be ignored is available as [methodname]#VaadinWebSecurityConfigurerAdapter.getDefaultWebSecurityIgnoreMatcher()#:
Wouldn't "similarly" be good enough?

2021-05-26 09:55 UTC, jouni commented on articles/fusion/security/spring-login.asciidoc
> +It utilises a Fusion [methodname]#login()# helper method for Spring-Security-based authentication.
Should it be "Spring Security -based" instead? Looks weird to spell it as "Spring-Security".

2021-05-27 09:40 UTC, magi42 requested changes
Note that filenames in example titles are still giving warnings; you could mark them with [filename]#...#.

Also, CSRF mentions will probably give warnings in some files, so you'd need to define them like here.

2021-05-27 09:40 UTC, magi42 commented on articles/fusion/security/spring-login.asciidoc
> +For example, [methodname]#VaadinWebSecurityConfigurerAdapter.configure(http)# requires all requests but to be authenticated, except the Vaadin internal ones.
```suggestion
For example, [methodname]#VaadinWebSecurityConfigurerAdapter.configure(http)# requires all requests to be authenticated, except the Vaadin internal ones.
```

2021-05-27 09:40 UTC, magi42 commented on articles/fusion/security/spring-login.asciidoc
> +The next example shows how to configure authentication by using an LDAP repository.
```suggestion
The following example shows how to configure authentication by using an LDAP repository.
```

2021-05-27 09:40 UTC, magi42 commented on articles/fusion/security/authentication.asciidoc
> +The next example exposes a method that checks whether a user is an admin user.
```suggestion
The following example exposes a method that checks whether a user is an admin user.
```

2021-05-28 11:06 UTC, dougjewsbury commented on articles/fusion/security/spring-login.asciidoc
> +In an analogous way, the matcher for static resources to be ignored is available as [methodname]#VaadinWebSecurityConfigurerAdapter.getDefaultWebSecurityIgnoreMatcher()#:
Agreed. "Similarly" isn't exactly the same as "in an analogous way", but its simplicity wins here.

2021-05-28 11:11 UTC, dougjewsbury commented on articles/fusion/security/authentication.asciidoc
> +However, you can expose an endpoint on the server side that checks user privileges and returns the status.
Yes, it could be a little ambiguous. I think "a server-side endpoint that checks" is good.

2021-05-28 11:19 UTC, dougjewsbury commented on articles/fusion/security/authentication.asciidoc
> +The authenticated user is returned as null if the request is not authenticated.
Of course, you're right technically. How about "A null value in place of the authenticated user indicates that the request is not authenticated"?

2021-05-28 11:21 UTC, dougjewsbury commented on articles/fusion/security/authentication-offline.asciidoc
> +== Complete Example with Offline Support
I have no strong feelings about it. We could leave it as it is, I think.

2021-05-28 12:50 UTC, dougjewsbury reviewed
Changes in response to reviewer comments

2021-05-28 12:50 UTC, dougjewsbury commented on articles/fusion/security/role-based-access.asciidoc
> +In a nutshell, roles are a set of string attributes representing the authorities that are assigned to a user.
```suggestion
Roles are a set of string attributes representing the authorities that are assigned to a user.
```

2021-05-28 12:50 UTC, dougjewsbury commented on articles/fusion/security/spring-login.asciidoc
> +It utilises a Fusion [methodname]#login()# helper method for Spring-Security-based authentication.
Or "authentication via Spring Security"?

2021-05-28 12:50 UTC, dougjewsbury commented on articles/fusion/security/spring-login.asciidoc
> +In an analogous way, the matcher for static resources to be ignored is available as [methodname]#VaadinWebSecurityConfigurerAdapter.getDefaultWebSecurityIgnoreMatcher()#:
```suggestion
Similarly, the matcher for static resources to be ignored is available as [methodname]#VaadinWebSecurityConfigurerAdapter.getDefaultWebSecurityIgnoreMatcher()#:
```

2021-05-28 14:58 UTC, magi42 commented on articles/fusion/security/spring-login.asciidoc
> +It utilises a Fusion [methodname]#login()# helper method for Spring-Security-based authentication.
I've usually recommended against Latinisms like via (and Latin abbreviations).

2021-05-28 18:53 UTC, magi42 requested changes

2021-05-28 18:53 UTC, magi42 commented on articles/fusion/security/authentication.asciidoc
> +The authenticated user is returned as null if the request is not authenticated.
"in place of" is a bit wordy, and not quite exact since null reference isn't an object like user is, but means "nothing".

Looks like there's a problem in the text. It doesn't actually tell how to get the authenticated user, which is with getUserPrincipal().
So you could say more exactly: "Calling [methodname]#getUserPrincipal()# for the request returns the authenticated user, or null if the request is not authenticated." Well, a bit wordy as well.

2021-08-12 13:35 UTC, jouni approved these changes

2021-08-12 13:35 UTC, jouni commented on articles/fusion/security/configuring.asciidoc
> +In order to change the default behavior, a security Java annotation should be placed either on the endpoint class or on the endpoint method.
```suggestion
To change the default behavior, place a security Java annotation on either the endpoint class or on the endpoint method.
```

2021-08-12 13:35 UTC, jouni commented on articles/fusion/security/handle-session-expiration.asciidoc
> +Indicates whether or not the login attempt has failed.
```suggestion
Indicates whether the login attempt has failed.
```

2021-08-12 13:37 UTC, merged

2021-08-12 13:37 UTC, jouni commented
I thought we’d clear this longstanding PR out of the way. Further fixes on another day 🙂