Add "Importing projects to VSCode" tab and Commonly used IDEs table
vaadin/docs pull request #512
Opened 2021-05-27 14:46 UTC by HerbertsVaadin

## Description

Adds "Importing projects to VSCode". It also includes a "Commonly used IDEs" section in the "Overview" section of "Importing projects to an IDE".

Fixes #489 (issue)

2021-05-27 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=512) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=512) it.</sub>

2021-05-27 16:28 UTC, magi42 requested changes
Looks good. Rephrased some long sentences a bit.

2021-05-27 16:28 UTC, magi42 commented on articles/guide/importing/index.asciidoc
> +To help you decide whether to use your prefered IDE or one that is better suited for work you will be doing, we have created the following table to illustrate support for both Java and TypeScript in
```suggestion

Different IDEs have varying support for Java and TypeScript.
The following table gives a rough evaluation of language support in the most commonly used IDEs.
```

2021-05-27 16:28 UTC, magi42 commented on articles/guide/importing/vscode.asciidoc
> +. A notification might appear asking you whether you would like to import Java projects contained in this workspace. Click "Yes" or "Always".
```suggestion
. A notification may appear asking you whether you would like to import Java projects contained in this workspace.
Click [guibutton]#Yes# or [guibutton]#Always#.
```
It doesn't always appear? It's a bit odd to say "may" in such case... Oh well.

2021-05-27 16:28 UTC, magi42 commented on articles/guide/importing/vscode.asciidoc
> +VS Code might suggest that you install additional extensions, here are the ones recommended for Vaadin:
```suggestion
VS Code may suggest that you install additional extensions.
The following ones are recommended for Vaadin:
```
Again, "may" is a bit oddly vague.

2021-05-28 06:36 UTC, HerbertsVaadin commented on articles/guide/importing/vscode.asciidoc
> +. A notification might appear asking you whether you would like to import Java projects contained in this workspace. Click "Yes" or "Always".
Yes, it doesn't appear if you don't have the java extension pack (or some specific java extension) installed.

2021-05-28 06:39 UTC, HerbertsVaadin commented on articles/guide/importing/vscode.asciidoc
> +VS Code might suggest that you install additional extensions, here are the ones recommended for Vaadin:
Well, if you have them installed already, it's not going to suggest them. It may suggest new ones, even though you installed all the recommended ones before.

2021-05-28 07:18 UTC, merged