fix: Address route scope DX comments
vaadin/docs pull request #524
Opened 2021-06-02 05:43 UTC by mshabarov

## Description

Supplements RouteScope documentation in accordance with DX test feedback.

Fixes https://github.com/vaadin/flow/issues/11083

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-06-02 19:03 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +Usually `@RouteScopeOwner` qualifier has to be placed on top of bean class and injection point of the bean.
```suggestion
Usually `@RouteScopeOwner` qualifier has to be placed on top of the bean class and in the injection point of the bean.
```

2021-06-04 06:30 UTC, pleku requested changes

2021-06-04 06:30 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +When changing scope annotations, the application server needs to be restarted to apply the new scopes, since the Spring IoC Container doesn't apply it on the fly even with enabled live reload.
The ordering of words is a bit funky, how about
```suggestion
When changing the scope annotations, the application server needs to be restarted to apply the new scopes. Restart is required even when live reload is enabled.
```

2021-06-04 06:30 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +Usually `@RouteScopeOwner` qualifier has to be placed on top of the bean class and in the injection point of the bean.
```suggestion
The `@RouteScopeOwner` qualifier has to be placed both on top of the bean class and on the injection point of the bean.
```

2021-06-04 06:30 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +In some certain cases, when a bean implementation can be resolved unambiguously by Spring IoC Container (as in the example above), `@RouteScopeOwner` annotation can be omitted in the injection point.
```suggestion
But, when the bean implementation can be resolved unambiguously by Spring (as in the example above), the `@RouteScopeOwner` annotation can be omitted in the injection point.
```

2021-06-04 06:30 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +It can be decoupled by splitting the bean class into an interface and its implementation class, and then using the interface in the view class and marking a concrete bean's implementation class with
```suggestion
It can be decoupled for example by splitting the bean class into an interface and its implementation class, and then using the interface in the view class and marking a concrete bean's implementation class with `@RouteScopeOwner`.
```

2021-06-04 09:32 UTC, pleku approved these changes

2021-06-04 11:09 UTC, magi42 approved these changes
Some minor cleanup and rewording, but looks rather OK as is.

2021-06-04 11:09 UTC, magi42 commented on articles/flow/integrations/spring/scopes.asciidoc
> +It can be decoupled for example by splitting the bean class into an interface and its implementation class, and then using the interface in the view class and marking a concrete bean's implementation
These are maybe a bit complex sentences.
```suggestion
Having an owner view class as a value in the `@RouteScopeOwner` for a model/business logic bean class ties application's view layer to a model/business layer.
It can be decoupled, for example, by splitting the bean class into an interface and its implementation class, and then using the interface in the view class and marking a concrete bean's implementation class with `@RouteScopeOwner`.
```

2021-06-04 12:04 UTC, merged