chore: Add Vaadin Spring scopes diagram
vaadin/docs pull request #526
Opened 2021-06-03 09:49 UTC by mshabarov

## Description

Add a simple diagram to represent visually a Vaadin Scopes overview.

Related-to https://github.com/vaadin/flow/issues/11083

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-06-04 06:41 UTC, pleku approved these changes

2021-06-04 12:07 UTC, magi42 reviewed
I get a bit confused for which class the annotations are for? Are they both annotations for a URL or the ProductView class? Should "URL" rather be "Route"?

2021-06-04 12:59 UTC, mshabarov commented
> I get a bit confused for which class the annotations are for? Are they both annotations for a URL or the ProductView class? Should "URL" rather be "Route"?

Thanks for your question, @magi42 ! Making this diagram, I aimed to show visually the following:
1. Bean lifecycle scopes are 'nested', i.e. the 'wider' scope overlaps the 'narrower' scope, for example, beans annotated with `@VaadinSessionScope` live longer (or at least equally) than the other beans annotated with`@UIScope`.
2. While the scope meaning is more or less abstract term, there are 'physical' counterparts for them: application running on the server, user's session created on the server (which is an object in the memory), opened browser page and finally the URL typed in the address bar by the user. So, showing these APPLICATION, USER'S SESSION, ... on the left side of squares, and the corresponding annotations on the left side, I was trying to tell the reader that those annotation are bound to a 'physical' things, that's IMO easier to understand, especially for those who uses it for the first time.
3. For `@RouteScope` it's not that easy to show only an empty square...Because this scope always bound to some navigation target (i.e. class annotatated with `@Route`, `@RouterLayout` or `HasErrorParameter`), even if no owner is set. This forced me to show the view hierarchy of the imaginary application and pass round some sub-set of the views.

> I get a bit confused for which class the annotations are for?

This is unfortunately not shown in this picture and not described in the title. All the annotations showed in the picture are targeted to the bean classes, which can be a navigation targets, or other non-UI related classes considered as managed beans in the application (for instance, controllers/services). These bean classes are not show in the picture.

> Are they both annotations for a URL or the ProductView class?

They can be an annotations for `ProductView` technically, but this example says that `ProductView` is an owner (i.e. the scope) for annotated bean. That means, the same like `VaadinSession` means for `@VaadinSessionScope` annotated beans - it limits the lifecycle of the beans.

> Should "URL" rather be "Route"?

It might be a 'Route', but the `Route` is more a 'Vaadin-specific' term, whereas the 'URL' is more commonly used thing (and more clear).  

What I would propose to fix is to change the description of the picture to explain that those annotations are for bean classes.

2021-06-21 11:58 UTC, pleku requested changes

2021-06-21 11:58 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +.Overview of Vaadin Spring scopes annotations for bean classes
This diagram is a tricky one to describe, since it has some example case that is not shown in code. I would go with:
```suggestion
.Overview of how Vaadin specific scopes relate to each other when used in navigation targets
```

2021-06-21 11:58 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +image::images/spring-scopes.png[Overview of Vaadin Spring scopes annotations for bean classes (including navigation targets) and their binding to app, session, page and url]
```suggestion
image::images/spring-scopes.png[Overview of Vaadin specific scopes for bean classes (including navigation targets) and their binding to app, session, page and URL]
```

2021-06-21 11:58 UTC, pleku commented on articles/flow/integrations/spring/scopes.asciidoc
> +.Overview of Vaadin Spring scopes annotations for bean classes
Non-blocking comment: I would change the diagram to use `/PATH` instead of `URL` and maybe `BROWSER WINDOW/TAB`. But it is probably fine as-is. The comment about "url is more common than path" doesn't apply IMO since this is highly Vaadin context dependent and you need to understand routes + paths at this point.

2021-07-09 19:46 UTC, magi42 reviewed
Maybe the diagram is good enough, even if there's some issues. Better put this forward.

2021-07-09 19:46 UTC, magi42 commented on articles/flow/integrations/spring/scopes.asciidoc
> +image::images/spring-scopes.png[Overview of Vaadin Spring scopes annotations for bean classes (including navigation targets) and their binding to app, session, page and url]
Notice that you can't have commas in the Alt text for images, you need to quote the text in ".

2021-07-09 19:46 UTC, magi42 commented on articles/flow/integrations/spring/scopes.asciidoc
> +.Overview of Vaadin Spring scopes annotations for bean classes
You could avoid that very image captions, and rather explain it in an introducing sentence before the diagram.

2021-08-10 06:31 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +.Overview of Vaadin Spring scopes annotations for bean classes
I've improved the image caption as suggested, but kept the caption, instead of separate sentence, because IMO the scopes are well-described in the existing sub sections. This diagram is just a visual representation what was written before.

2021-08-10 06:32 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +image::images/spring-scopes.png[Overview of Vaadin Spring scopes annotations for bean classes (including navigation targets) and their binding to app, session, page and url]
Fixed the alt text and wrapped it to `"`.

2021-08-10 06:34 UTC, mshabarov commented on articles/flow/integrations/spring/scopes.asciidoc
> +.Overview of Vaadin Spring scopes annotations for bean classes
Looking at this after a while, I agree that the `path` is better fit to Vaadin `route`, so renamed it.

2021-08-10 06:36 UTC, pleku approved these changes

2021-08-10 06:42 UTC, mshabarov commented
@magi42 `deploy-netlify` failure is a know issue with webpack/workbox incompatible versions:

```
9:28:51 AM: [ERROR] /opt/build/repo/node_modules/.pnpm/webpack-cli@3.3.11_webpack@4.46.0/node_modules/webpack-cli/bin/cli.js:93
9:28:51 AM: [ERROR] 				throw err;
9:28:51 AM: [ERROR] 				^
9:28:51 AM: [ERROR]
9:28:51 AM: [ERROR] Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
```

It has been fixed in V20 and will be fixed in V21 as soon as a new flow release will be done. So, to fix it, you need to use https://github.com/vaadin/platform/releases/tag/20.0.6

2021-08-10 13:53 UTC, merged