Docs for MessageConfigurator
vaadin/docs pull request #528
Opened 2021-06-03 14:11 UTC by tulioag

Fixes: vaadin/collaboration-engine-internal#594
WIP: Needs vaadin 21.0.0.alpha3

2021-06-03 15:35 UTC, tulioag commented on src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
> +    private void messageConfigurator() {
@muse-dev ignore

2021-06-11 07:39 UTC, magi42 requested changes

2021-06-11 07:39 UTC, magi42 commented on articles/ce/collaboration-message-list.asciidoc
> +----
```suggestion
The following example shows how to use a message configurator to add a custom style to the current user's messages:

[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java[tags=message-list-configurator;message-list-configurator-style;!*,indent=0]
----

Please refer to <<{articles}/ds/components/messages#theming, Theming>> in Messages documentation for details on how to style messages based on the theme.
```

2021-06-11 07:39 UTC, magi42 commented on articles/ce/collaboration-message-list.asciidoc
> +The message configurator can also be used to change the message's text, for example censoring certain words in messages.
```suggestion
The message configurator can also be used to change the text content of messages, for example, to censor certain words in messages, as is done in the following example.
```

2021-06-17 11:49 UTC, tulioag commented
@magi42 Is anything missing?

2021-06-17 12:15 UTC, magi42 approved these changes

2021-06-17 12:18 UTC, magi42 commented
At least the text looks OK, someone else should check the Java part. One minor thing there is code formatting in the two code examples. If possible, rather have
```
CollaborationMessageList collaborationMessageList =
        new CollaborationMessageList(userInfo, topicId);
```
No prob if it's difficult because of automatic formatting or something.

2021-06-17 13:51 UTC, tulioag commented
> At least the text looks OK, someone else should check the Java part. One minor thing there is code formatting in the two code examples. If possible, rather have
> 
> ```
> CollaborationMessageList collaborationMessageList =
>         new CollaborationMessageList(userInfo, topicId);
> ```
> 
> No prob if it's difficult because of automatic formatting or something.

Fixed

2021-06-17 16:22 UTC, merged