docs: add grid cell focus docs
vaadin/docs pull request #530
Opened 2021-06-04 06:26 UTC by sissbruecker

## Description

Adds documentation about the grids cell focus mangement with examples on how to get notified when the user switches focus between cells.

Fixes https://github.com/vaadin/web-components/issues/337

## Type of change

- [X] Feature

2021-06-04 06:31 UTC, sissbruecker commented on articles/ds/components/grid/index.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java[render,tags=snippet,indent=0,group=Java]
This is would be the only Java example on the page so far, but we agreed in DS team that it's OK to add them piece by piece.

2021-06-04 06:31 UTC, sissbruecker commented on frontend/demo/component/grid/grid-cell-focus.ts
> +          const eventContext = this.grid.getEventContext(e) as GridEventContext<Person>;
Added an explicit cast here since the return type is hard to use ATM. I fixed the corresponding type [here](https://github.com/vaadin/web-components/pull/2081#discussion_r644050677) and can update this after next release of the component.

2021-06-04 08:24 UTC, sosa-vaadin requested changes
1. Set TextArea's `readonly` property to `true` in both TS and Java examples.
2. Fix a conditional check.
3. ???
4. Profit.

2021-06-04 08:24 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-cell-focus.ts
> +            eventContext?.item?.firstName && eventContext?.item?.firstName
I guess your intention was to check for both `firstName` and `lastName`.

2021-06-04 08:24 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-cell-focus.ts
> +        <vaadin-text-area
If you're using this text-area as a placeholder for the information about the focused cell, why not make it `readonly`?

2021-06-04 08:24 UTC, sosa-vaadin commented on frontend/demo/component/grid/grid-cell-focus.ts
> +        <vaadin-text-area
Maybe even remove its borders and add some padding, but that's just me pressing on the aesthetics.

2021-06-04 08:24 UTC, sosa-vaadin commented on src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java
> +        TextArea textArea = new TextArea();
Same thing here about making it `readonly`.
```suggestion
        TextArea textArea = new TextArea();
        textArea.setReadonly(true);
```

2021-06-04 08:46 UTC, sissbruecker commented on frontend/demo/component/grid/grid-cell-focus.ts
> +        <vaadin-text-area
Good idea, done. Readonly textarea seems to have a different style already (dashed-border). Also removed the placeholder as that is not used in the readonly textarea.

2021-06-04 08:46 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/grid/GridCellFocus.java
> +        TextArea textArea = new TextArea();
Fixed.

2021-06-04 09:12 UTC, sosa-vaadin approved these changes

2021-06-10 07:05 UTC, magi42 requested changes

2021-06-10 07:05 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +* +++<kbd>End</kbd>+++ - Moves focus to the last cell in a row
```suggestion
[cols="1,5"]
|====
| kbd:[Tab] | Switches focus between sections of the grid (header, body, footer)
| kbd:[←], kbd:[↑], kbd:[→], kbd:[↓] | Moves focus between cells within a section of the grid
| kbd:[Page Up] | Moves cell focus up by one page of visible rows
| kbd:[Page Down] | Moves cell focus down by one page of visible rows
| kbd:[Home] | Moves focus to the first cell in a row
| kbd:[End] | Moves focus to the last cell in a row
|====
```

2021-06-10 07:05 UTC, magi42 commented on articles/ds/components/grid/index.asciidoc
> +[NOTE]
```suggestion
```

2021-06-11 12:01 UTC, jouni commented
Assuming David’s approval concerns Java and TypeScript code.

2021-06-11 12:03 UTC, merged