fix: use timestamp to check if session is still alive
vaadin/docs pull request #534
Opened 2021-06-07 14:05 UTC by yuriy-fix

2021-06-15 09:22 UTC, tomivirkki requested changes

2021-06-15 09:22 UTC, tomivirkki commented on frontend/demo/example-resources.ts
> +window.addEventListener('update-timestamp', updateTimestamps);
Will this event be dispatched when you end up in this state? https://github.com/vaadin/docs-app/issues/273#issuecomment-853597932

2021-06-15 09:22 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/DemoExporter.java
> +      UI.getCurrent().addPollListener(e -> emitUpdateTimestamp());
These listeners keep adding up as you visit more examples and you end up with multiple "update-timestamp" events firing at once.

2021-06-15 09:22 UTC, tomivirkki commented on frontend/demo/example-resources.ts
> +// Stores the last time UI polls the server
Can you move this logic to a separate file that you import here.

2021-06-15 13:39 UTC, yuriy-fix commented on frontend/demo/example-resources.ts
> +window.addEventListener('update-timestamp', updateTimestamps);
I wasn't able to get into that exact state.
However, this logic should prevent getting there when the server and user are online. If one of those is offline, the reloading should happen at the point they are getting back online (if the session is presumably destroyed = after timeout).

2021-06-15 13:39 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/DemoExporter.java
> +      UI.getCurrent().addPollListener(e -> emitUpdateTimestamp());
Good catch! Checking for the existing poll interval now.
Visiting other examples will still trigger the event as it's considered to be a round-trip that keeps the session alive and the timestamp should be updated 🤔

2021-06-15 13:39 UTC, yuriy-fix commented on frontend/demo/example-resources.ts
> +// Stores the last time UI polls the server
Moved it.

2021-06-21 10:21 UTC, tomivirkki commented on frontend/demo/session-verification.ts
> +  if (Date.now() - timestamp > 2 * sessionTimeout) {
What happens if the user re-opens the page after `1.5 * sessionTimeout`?

2021-06-21 10:24 UTC, tomivirkki commented on frontend/demo/session-verification.ts
> +    fetch(withPrefix('/vaadin/index.html')).then((serverData) => {
`/vaadin/index.html` [seems to get redirected](https://vaadin.com/docs/latest/vaadin/index.html) to `/vaadin/index` so better use the latter.

2021-06-21 10:27 UTC, tomivirkki commented on frontend/demo/session-verification.ts
> +const sessionTimeout = 20 * 60 * 1000;
This is a magic number. Could it be delivered in the event payload?

2021-06-21 10:27 UTC, tomivirkki commented on src/main/java/com/vaadin/demo/DemoExporter.java
> +      UI.getCurrent().setPollInterval((int) Duration.ofMinutes(20).toMillis());
This is a magic number. Could it be obtained programmatically instead?

2021-06-23 10:21 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/DemoExporter.java
> +      UI.getCurrent().setPollInterval((int) Duration.ofMinutes(20).toMillis());
It's semi-random (`maxInectiveInterval` - 10 minutes) now: poll should happen at some point before the max inactive interval is reached. Cannot do it at the same time as there could be some delay within roundtrips.

2021-06-23 10:22 UTC, yuriy-fix commented on frontend/demo/session-verification.ts
> +const sessionTimeout = 20 * 60 * 1000;
Getting value from the event now.

2021-06-23 10:22 UTC, yuriy-fix commented on frontend/demo/session-verification.ts
> +    fetch(withPrefix('/vaadin/index.html')).then((serverData) => {
Changed.

2021-06-23 10:22 UTC, yuriy-fix commented on frontend/demo/session-verification.ts
> +  if (Date.now() - timestamp > 2 * sessionTimeout) {
Nothing as `pollInterval` is supposed to keep the session alive.

2021-06-23 14:16 UTC, tomivirkki approved these changes

2021-06-23 14:16 UTC, tomivirkki commented on frontend/demo/example-resources.ts
> -      localStorage.setItem('reloadTimestamp', Date.now().toString());
Noticed you decided to remove the "safety net". I assume it was intentional?

2021-06-24 10:50 UTC, yuriy-fix commented on frontend/demo/example-resources.ts
> -      localStorage.setItem('reloadTimestamp', Date.now().toString());
Yes, with the new approach we are not relying on heartbeats checks. The only case it will get into the reloading loop is if we would provide incorrect `sessionTimeout`.

2021-06-24 11:37 UTC, merged