fix: emphasize not to include generated theme file
vaadin/docs pull request #535
Opened 2021-06-08 13:36 UTC by pleku

Related to vaadin/flow#11180

2021-06-08 14:01 UTC, chetex commented
Thank you very mucho @Pekka. I have just remove this file. Then clean-install the theme project. Clean-install my project. I also tested in my ".m2" directory in local, that the theme-generated file is not added. Run my project, but still got this error.... I tried deleting the theme-generated files also moving to "frontend/generated" folder. Any idea?

2021-06-11 07:51 UTC, magi42 requested changes

2021-06-11 07:51 UTC, magi42 commented on articles/flow/styling/custom-theme-packaging.asciidoc
> +The file is automatically created in the application project that uses the theme.
```suggestion
.Do not include generated theme file
[IMPORTANT]
Do not include the automatically generated [filename]`<theme-name>.generated.js` file inside the packaged theme artifact.
The file is automatically created in an application project that uses the theme.
Including it in the theme can cause errors for such a project.
```

2021-06-11 08:12 UTC, magi42 approved these changes

2021-06-17 07:10 UTC, caalador approved these changes

2021-06-17 07:23 UTC, merged