docs: virtual-list docs and examples
vaadin/docs pull request #538
Opened 2021-06-10 15:41 UTC by tomivirkki

Closes https://github.com/vaadin/docs/issues/436
Closes https://github.com/vaadin/docs/issues/437

2021-06-11 08:58 UTC, magi42 requested changes
Note the question in the first suggestion.

The file was very short so is it still a draft? If so, please mark it as a draft.

2021-06-11 08:58 UTC, magi42 commented on articles/ds/components/virtual-list/index.asciidoc
> +Each item is rendered per need basis as the user scrolls the list, which makes the component especially suitable for displaying long item lists without sacrificing performance.
```suggestion
Each item is rendered on the fly as the user scrolls the list, which makes the component especially suitable for displaying long lists of items without sacrificing performance.
```
I wrote "rendered" here, but should it rather be "generated"? Is the actual data generated or just rendering?

2021-06-11 08:58 UTC, magi42 commented on articles/ds/components/virtual-list/index.asciidoc
> +[.example]
The example doesn't include the sources for the data source, and it is not trivial to figure out what they should be like.

2021-06-11 08:58 UTC, magi42 commented on articles/ds/components/virtual-list/index.asciidoc
> +To use the component, you need to assign it a set of data items and a renderer that's used for rendering each individual data item.
```suggestion
To use the component, you need to assign it a set of data items and a _renderer_ that is used for rendering each individual data item.
```

2021-06-11 09:11 UTC, jouni commented on articles/ds/components/virtual-list/index.asciidoc
> +:components-path-prefix: ../
Is this attribute used anywhere on this page?

2021-06-11 09:35 UTC, tomivirkki commented on articles/ds/components/virtual-list/index.asciidoc
> +Each item is rendered per need basis as the user scrolls the list, which makes the component especially suitable for displaying long item lists without sacrificing performance.
Rendered is better since that's what it's about

2021-06-11 09:56 UTC, tomivirkki commented on articles/ds/components/virtual-list/index.asciidoc
> +[.example]
Aligned with other similar examples and included the Person.java / Person.ts files

2021-06-11 10:30 UTC, yuriy-fix commented on articles/ds/components/index.asciidoc
> +image::{components-path-prefix}virtual-list/virtual-list.png["", role="icon screenshot"]
nit: all other examples seems to include `opts=inline`. Should it be added here as well? 🤔

2021-06-11 10:30 UTC, yuriy-fix commented on frontend/demo/component/virtuallist/virtual-list-basic.ts
> +@customElement('tree-grid-basic')
```suggestion
@customElement('virtual-list-basic')
```

2021-06-11 10:30 UTC, yuriy-fix commented on frontend/demo/component/virtuallist/virtual-list-basic.ts
> +            @click="${(e: CustomEvent) => {
nit: we can use `MouseEvent` over here.

2021-06-11 10:47 UTC, tomivirkki commented on articles/ds/components/index.asciidoc
> +image::{components-path-prefix}virtual-list/virtual-list.png["", role="icon screenshot"]
Good catch. Not sure how I missed it here. Done.

2021-06-11 10:47 UTC, tomivirkki commented on frontend/demo/component/virtuallist/virtual-list-basic.ts
> +            @click="${(e: CustomEvent) => {
Done

2021-06-11 10:50 UTC, yuriy-fix approved these changes

2021-06-11 11:05 UTC, jouni commented
@yuriy-fix, always update the Java/TypeScript/Asciidoc labels to indicate which of those your approval concerns. I assume in this case it's for the Java and TypeScript source code. If yes, replace the `Java` and `TypeScript` labels with `Java OK` and `TypeScript OK`.

2021-06-11 12:46 UTC, magi42 commented on articles/ds/components/index.asciidoc
> +image::{components-path-prefix}virtual-list/virtual-list.png["", role="icon screenshot"]
OK, now the Person is there, but shouldn't the data service be as well? I understand that the fake data service is rather unusual for a business case, so for the sake of abstraction we might not want to show it, but it feels like there's a missing link there.

2021-06-11 14:15 UTC, tomivirkki commented on articles/ds/components/index.asciidoc
> +image::{components-path-prefix}virtual-list/virtual-list.png["", role="icon screenshot"]
The [fake data service ](https://github.com/vaadin/docs/blob/latest/src/main/java/com/vaadin/demo/domain/DataService.java) isn't included in _any_ of the examples. Before it could be included in public examples, it would need some preparation work including documentation and clean up and that falls out of the scope of this PR.

2021-06-11 19:42 UTC, magi42 commented on articles/ds/components/index.asciidoc
> +image::{components-path-prefix}virtual-list/virtual-list.png["", role="icon screenshot"]
OK yeah, no worries. The reason why I'm thinking about that is a very frustrated hour a year ago trying to use TreeGrid, where the documentation just used the data source that defined the hierachy, but it wasn't described anywhere. But OK, this was just something to think about.

2021-06-14 07:18 UTC, tomivirkki commented
@magi42 The PR still blocked due to the change request

2021-06-14 08:57 UTC, magi42 approved these changes
Odd, I didn't notice any pending change request, or do I actually need to approve... Ok I'll approve...

2021-06-14 08:58 UTC, merged