Updated getting started links
vaadin/docs pull request #542
Opened 2021-06-12 05:43 UTC by samie

- Link to start.vaadin.com presets
- Added back Spring Initializr as an option

2021-06-12 05:45 UTC, samie commented
We discussed the hasty removal of Spring Initializr links [in previous PR](https://github.com/vaadin/docs/pull/523#issuecomment-854863560), and as our Spring support is now [fixed on right level at Spring Initializr](https://github.com/spring-io/start.spring.io/commit/f4656e99a757b76a0e81d4a110eaf2a3f68042c7), it should be ok.

2021-06-14 12:54 UTC, jouni commented on articles/flow/integrations/spring/tutorial-spring-basic.asciidoc
> +The easiest way to create an application with Spring Boot and Vaadin is to start with a template application created by https://start.vaadin.com/?preset=lts[start.vaadin.com], but you can also config
```suggestion
https://start.vaadin.com/?preset=lts[Vaadin Start] is the easiest way to create an application with Spring Boot and Vaadin.
You can also configure and download a Vaadin project using
pass:[<!-- vale Vale.Spelling = NO -->]
https://start.spring.io/#!type=maven-project&language=java&packaging=jar&jvmVersion=11&groupId=org.vaadin&artifactId=example-app&name=example-app&description=Vaadin%20project%20for%20Spring%20Boot&packageName=org.vaadin.example-app&dependencies=vaadin[Spring Initializr]
pass:[<!-- vale Vale.Spelling = YES -->]
or add the required dependencies manually to your project.
```

2021-06-15 14:04 UTC, magi42 requested changes
Need to add auto-configuration to dictionary.

2021-06-15 14:04 UTC, magi42 commented on articles/flow/integrations/spring/tutorial-spring-basic.asciidoc
> +https://start.spring.io/#!type=maven-project&language=java&packaging=jar&jvmVersion=11&groupId=org.vaadin&artifactId=example-app&name=example-app&description=Vaadin%20project%20for%20Spring%20Boot&pa
```suggestion
You can also configure and download a Vaadin project using https://start.spring.io/#!type=maven-project&language=java&packaging=jar&jvmVersion=11&groupId=org.vaadin&artifactId=example-app&name=example-app&description=Vaadin%20project%20for%20Spring%20Boot&packageName=org.vaadin.example-app&dependencies=vaadin[Spring Initializr] or add the required dependencies manually to your project.
```

2021-06-15 14:04 UTC, magi42 commented on articles/flow/integrations/spring/tutorial-spring-basic.asciidoc
> +Like many other tech stacks on Spring Boot, Vaadin provides a starter dependency that provide all essential modules and autoconfiguration. Only the `vaadin-spring-boot-starter` dependency is needed,
```suggestion
Like many other tech stacks on Spring Boot, Vaadin provides a starter dependency that provides all essential modules and auto-configuration. Only the `vaadin-spring-boot-starter` dependency is needed, but it is suggested to also declare `vaadin-bom` if you need additional Vaadin dependencies. For production builds, it is also suggested to add `vaadin-maven-plugin`, which generates the optimized JavaScript packages.
```

2021-06-16 09:39 UTC, jouni commented
@magi42, your previous GH review is still blocking ("request changes"). I’ll merge it now regardless.

2021-06-16 09:40 UTC, merged