Fix: Update documentation
vaadin/docs pull request #55
Opened 2020-12-10 11:19 UTC by caalador

Updated documentation to match the
actual state of the project.
Removed image and replaced it with a ascii map
as the image is hard to update with all the constant
changes.

Fixes vaadin/flow#9595

2020-12-10 13:13 UTC, jouni commented
…kicking the preview build, let’s see if it works now 🤞

2020-12-10 13:14 UTC, jouni approved these changes

2020-12-10 13:40 UTC, jouni requested changes

2020-12-10 13:40 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +```
```suggestion
[source, filesystem]
----
theme/                             | contains all application themes
└── my-theme/                      | contais files for 'my-theme'
    ├── components                 | contains component specific themes
    │   ├── vaadin-button.css      | component themes need to match the tag name
    │   └── vaadin-text-field.css  |
    ├── images                     | static resource folder
    ├── webfonts                   | static resource folder
    ├── document.css               | css always applied to the root of the page
    ├── global.css                 | contains theme changes, may be targeted
    ├── my-theme.generated.js      | auto-generated configuration file
    └── theme.json                 | configuration for assets etc.
----
```

There’s a [bug in the doc builder](https://github.com/vaadin/docs-app/issues/194), which makes this content disappear if the listing block language is not defined.

2020-12-10 13:40 UTC, jouni commented on articles/themes/application-theme.asciidoc
>  Figure 1 illustrates a sample theme setup for "my-theme" application theme.
```suggestion
The following describes a sample file system structure for "my-theme".
```

2020-12-11 09:44 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +----
Actually, this doesn’t work that great, since the text wraps on new lines, and makes it hard to follow.

We could try using callouts instead: https://asciidoctor.org/docs/user-manual/#callouts

2020-12-11 09:45 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +----
Another option is to use a table, with minimal styling (remove outer frame and inner grid lines): https://docs-app-preview.netlify.app/styling-test/tables/

2020-12-11 10:05 UTC, caalador commented on articles/themes/application-theme.asciidoc
> +----
Callouts seem better than table in this instance. Updated.

2020-12-11 13:42 UTC, pleku approved these changes

2020-12-11 13:44 UTC, jouni commented on articles/themes/application-theme.asciidoc
> +----
Thanks. Just one problem: callouts are currently broken: https://github.com/vaadin/docs-app/issues/179

But we’ll get those fixed.

2020-12-11 13:49 UTC, pleku commented on articles/themes/application-theme.asciidoc
> +----
I saw that too from the preview, but I guess it is fine for now.

2020-12-11 13:51 UTC, merged