feat: Add a login/logout example for View-based access control chapter
vaadin/docs pull request #558
Opened 2021-06-15 13:56 UTC by mshabarov

## Description

Add an example how to pass Login Form credentials to the security context and how to implement a logout capability.

Fixes #548

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-06-15 18:52 UTC, mshabarov commented on articles/flow/security/best-practices.asciidoc
> +=== Logout capability
```suggestion
=== Logout Capability
```

2021-06-16 08:07 UTC, pleku requested changes

2021-06-16 08:07 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +@VaadinServiceScoped
How is this supposed to work ? I don't think there is a mention of CDI anywhere. This will not work with standard Java DI.

Maybe you should store the user details to the `VaadinSession` with `setAttribute(Class<UserInfo>, UserInfo)` instead ?

2021-06-16 08:50 UTC, mshabarov commented on articles/flow/security/best-practices.asciidoc
> +    @Inject
Not sure I understand the comment. `@Inject` works here, I tested with demo project. And I believe `@Inject` is a pretty much basic thing and should be knows for devs who start trying security features with Java EE.

2021-06-16 08:52 UTC, mshabarov commented on articles/flow/security/best-practices.asciidoc
> +    public LoginView(SecurityService securityService) {
Yep, it's better to show it first

2021-06-16 09:01 UTC, mshabarov commented on articles/flow/security/best-practices.asciidoc
> +@VaadinServiceScoped
Well, to avoid the CDI here in these examples, I could make this service an util class instead with static methods.
`ViewAccessChecker` relies on `HttpServletRequest::isUserInRole` by default, thus, I don't see how putting the attribute to a session will then let `isUserInRole` to work.

2021-06-16 09:11 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +    @Inject
Yes, `@Inject` works but it may not be obvious for everyone.

But since you added `@VaadinServiceScoped` it this actually doesn't work or would not work like intended

2021-06-16 09:25 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +@VaadinServiceScoped
Right - well not sure which is better. One thing to note is that `VaadinServletReqquest.getCurrent` will not work for any background thread so the pattern would be a bit fragile if it is just a static utility class. A lot of explaining would be needed to be done to explain how it is not actually recommended

2021-06-16 09:27 UTC, pleku commented on articles/flow/security/best-practices.asciidoc
> +@VaadinServiceScoped
Oh well, that applies to the whole `ViewAccessChecker` and that should be documented here somewhere too. Probably missed out from the initial code review but I think documenting this is enough

2021-06-16 10:51 UTC, mshabarov commented on articles/flow/security/best-practices.asciidoc
> +@VaadinServiceScoped
> One thing to note is that VaadinServletReqquest.getCurrent will not work for any background thread so the pattern would be a bit fragile if it is just a static utility class

ViewAccessChecker itself won't work if no request is available: https://github.com/vaadin/flow/blob/d17359acea9f0ef42c2f0d751bb92028ae047d0d/flow-server/src/main/java/com/vaadin/flow/server/auth/ViewAccessChecker.java#L128-L133

I propose to use an utility class and add comments/explanations there that it works like this. Artur suggests using a Shiro, but for the purpose of this chapter it will extra. But mention it might be fine.

2021-06-17 08:10 UTC, pleku approved these changes

2021-06-17 08:56 UTC, merged

2021-06-17 09:57 UTC, magi42 requested changes

2021-06-17 09:57 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +- Logout the user by invalidating the http session and redirecting to the home page.
```suggestion
=== Handle User's Login and Logout

There are many ways to handle login and logout, and how to get the authenticated user for a request.
The View-based access control implementation in Vaadin uses [methodname]#getUserPrincipal()# and [methodname]#isUserInRole(String)# in [classname]#HttpServletRequest# to check whether the currently authenticated user has access to the view.
Therefore, you need a way to put the user information into the request.

The example below uses the currently active Vaadin servlet request.
It shows how to:

- Check whether the user is currently authenticated to the application or not.
The request is not available in background threads, so the [methodname]#isAuthenticated()# method shows authentication state only in Vaadin request processing threads, otherwise it would always return `false`.
- Authenticate the user with the given credentials.
The [methodname]#authenticate()# method fails if is called from a background thread.
- Logout the user by invalidating the HTTP session and redirecting to the home page.
```

2021-06-17 09:57 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +        return false;
Consider returning false in the beginning if getCurrent() == null. Maybe more clear structure.

2021-06-17 09:57 UTC, magi42 commented on articles/flow/security/best-practices.asciidoc
> +Here is a basic implementation of logout button shown on the main layout's header:
```suggestion
You typically let the user to log out by using a logout button.

The following example shows a basic implementation of a logout button shown on the header of the main layout:
```