Add RTE flow examples
vaadin/docs pull request #571
Opened 2021-06-18 12:34 UTC by yuriy-fix

2021-06-21 15:27 UTC, DiegoCardoso requested changes

2021-06-21 15:27 UTC, DiegoCardoso commented on src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
> +    rte.asHtml().addValueChangeListener(e -> textArea.setValue(e.getValue()));
There's something strange happening here. 

If I start typing on RTE, everything works, but if I at any point use the toolbar, then the focus starts to move.

You can see on the example below that from the point I clicked on the bold button, the RTE started to misbehave. You can also notice that the textarea starts receiving the change value indicating that a change event is happening on RTE.


https://user-images.githubusercontent.com/262432/122787408-fa9a4c00-d2bd-11eb-9440-83fc6203cba2.mp4

2021-06-22 12:53 UTC, yuriy-fix commented on src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
> +    rte.asHtml().addValueChangeListener(e -> textArea.setValue(e.getValue()));
Good catch!
Was happening because interaction with toolbar emits `change` event and textarea was resetting value on rte. Fixed by checking if the html value is still the same.

2021-06-23 07:31 UTC, DiegoCardoso approved these changes
LGTM 💯

2021-06-23 10:16 UTC, merged