docs: make focus outline always visible in grid cell focus example
vaadin/docs pull request #572
Opened 2021-06-21 08:19 UTC by sissbruecker

## Description

Modifies the grid cell focus example to always show the focus outline for demonstration purposes, and adds a hint to the asciidoc about differences to the default behaviour.

Based on feedback from DX testing of the grid cell focus event.

2021-06-22 08:26 UTC, jouni requested changes
No need for tagged regions if the all the contents of the file are shown. We could use tags if we put the CSS of multiple examples in one file, but I think having individual files per example makes it slightly less confusing for the reader.

No need for `render` in any other source code includes than TS and Java examples that export a web component that can be rendered. CSS files obviously don't do that.

Any source code includes that apply for both TS and Java examples should not define a `group` attribute, so that they are shown under both TS and Java groups. Think of the groups as a collection if source files that are needed to accomplish the rendered example, not a grouping by programming language. It’s more about Fusion/Flow than TS/Java, but we are for now using the more easily recognizable terms.

2021-06-22 08:26 UTC, jouni commented on frontend/themes/docs/components/vaadin-grid-cell-focus.css
> +/* end::snippet[] */
```suggestion
:host([theme~='force-focus-outline']) [part~='cell']:focus::before {
    content: '';
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    pointer-events: none;
    box-shadow: inset 0 0 0 2px var(--lumo-primary-color-50pct);
}
```

2021-06-22 08:26 UTC, jouni commented on articles/ds/components/grid/index.asciidoc
> +include::{root}/frontend/themes/docs/components/vaadin-grid-cell-focus.css[render,tags=snippet,indent=0,group=CSS]
```suggestion
include::{root}/frontend/themes/docs/components/vaadin-grid-cell-focus.css[]
```

2021-06-22 08:42 UTC, fhdhsni commented on articles/ds/components/grid/index.asciidoc
> +For demonstration purposes the example below uses custom styles to also show the focus outline when clicking on cells.
`For demonstration purposes, ...`?

2021-06-22 09:13 UTC, sissbruecker commented on articles/ds/components/grid/index.asciidoc
> +For demonstration purposes the example below uses custom styles to also show the focus outline when clicking on cells.
Done

2021-06-22 09:59 UTC, fhdhsni approved these changes

2021-06-23 06:17 UTC, jouni approved these changes

2021-06-23 06:18 UTC, merged