feat: make docs reflecting latest nullability changes.
vaadin/docs pull request #586
Opened 2021-06-24 13:29 UTC by Lodin

* Collection type nullability is supported
* Endpoint function parameters are non-omittable

2021-06-24 13:59 UTC, haijian-vaadin requested changes

2021-06-24 13:59 UTC, haijian-vaadin commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +It can be nullable, but it cannot be omitted. If you have that parameter and want it to be `null` in Java, you must send an `undefined` there during the function call.
one sentence per line, i.e. put If you ... in a new line.

2021-06-24 13:59 UTC, haijian-vaadin commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the data class, there are one thing that can be nullable:
For the data class, one thing can be nullable:

2021-06-24 13:59 UTC, haijian-vaadin commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the collection types, there are one thing that can be nullable:
For the collection types, one thing can be nullable:

2021-06-24 13:59 UTC, haijian-vaadin commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the endpoint function, there are two things that can be nullable:
two things can be nullable

2021-06-24 14:40 UTC, haijian-vaadin approved these changes

2021-06-24 18:33 UTC, platosha requested changes

2021-06-24 18:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the data class, one thing can be nullable:
For me this literal “one thing” mention and the list feel redundant. I’d suggest to remove the list, and only keep the paragraph that says that class properties are nullable.

2021-06-24 18:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the endpoint function, two things can be nullable:
“Nullable” implies the ability, “can be” feels redundant.

```suggestion
For the endpoint function, two things are nullable:
```

2021-06-24 18:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +It can be nullable, but it cannot be omitted.
A bit mixing the parameters (the receiving variables) and the arguments (values that are being send) here, let’s clarify.

```suggestion
Arguments cannot be omitted even when the parameter types are nullable.
```

2021-06-24 18:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +If you have that parameter and want it to be `null` in Java, you must send an `undefined` there during the function call.
```suggestion
To receive a `null` parameter value in Java, send an `undefined` argument in the endpoint function call.
```

2021-06-24 18:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the collection types, one thing can be nullable:
Also redundant “one thing” list here.

2021-08-11 08:49 UTC, haijian-vaadin approved these changes

2021-08-11 11:33 UTC, platosha approved these changes

2021-08-11 11:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +* **Properties**.
```suggestion
```

2021-08-11 11:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +For the data class, nullable elements are:
Looks redundant to have a list with just one item, I’d remove the list and describe the item right away.

```suggestion
Properties of the data classes are nullable.
```

2021-08-11 11:33 UTC, platosha commented on articles/fusion/advanced/endpoints-generator.asciidoc
> +* **Item type**.
```suggestion
The collection item type is nullable.
```

2021-08-11 11:35 UTC, platosha commented
Approved with some non-blocking suggestions. Feel free to skip them and merge as is.

2021-08-11 11:56 UTC, platosha approved these changes

2021-08-11 12:04 UTC, merged