Update licensing
vaadin/docs pull request #616
Opened 2021-07-05 07:18 UTC by tulioag

2021-07-05 12:30 UTC, magi42 requested changes

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-binder.asciidoc
> +image::images/collaboration-binder-example.png[A form, where the email field is currenlty being edited by another user, width=387]
```suggestion
image::images/collaboration-binder-example.png["A form where the email field is currently being edited by another user", width=387]
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-binder.asciidoc
> +you will be presented with the field values that the previous user might have left there.
```suggestion
Even after a long time has passed since someone has visited a form and you open the form again, you will be presented with the field values that the previous user may have left there.
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-binder.asciidoc
> +In this scenario, you might want the field values to be re-populated from the backend instead.
```suggestion
In this scenario, you may rather want the field values to be re-populated from the backend.
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-binder.asciidoc
> +again to populate the fields.
```suggestion
If there hasn't been any connected users for the set period of time, binder will call the bean supplier callback (provided in `setTopic()`) again to populate the fields.
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-binder.asciidoc
> +without having to start over with the form editing.
```suggestion
You can use `Duration.ZERO` to reset the fields immediately when there's a moment with no connected users.
However, it may be a good idea to have a small time window.
This enables, for example, a user to recover from a temporary network issue without having to start over with editing the form.
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-message-list.asciidoc
> +`CollaborationMessageList` and `CollaborationMessageInput` components.
```suggestion
You can add a real-time chat to your application by using the `CollaborationMessageList` and `CollaborationMessageInput` components.
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-message-list.asciidoc
> +image::images/collaboration-messages-example.png[A Chat with three messages, and controls for typing in new messages, width=399]
```suggestion
image::images/collaboration-messages-example.png["A Chat with three messages, as well as controls for typing in new messages", width=399]
```

2021-07-05 12:30 UTC, magi42 commented on articles/ce/components/collaboration-message-list.asciidoc
> +Here's an example of setting them up:
```suggestion
They enhance the regular `MessageList` and `MessageInput` components by automatically synchronizing the messages for all users connected to the same topic.
The message list only renders the submitted messages, while the message input provides controls for submitting new messages.

The following example shows how to set them up:
```

2021-07-06 08:33 UTC, dougjewsbury commented on articles/ce/collaboration-message-list.asciidoc
> +user in this view sees each others' messages.
```suggestion
user in this view sees the other users' messages.
```

2021-07-06 08:49 UTC, dougjewsbury commented on articles/ce/collaboration-message-list.asciidoc
> +- Fetch all messages in a given topic, which have been submitted after a given timestamp.
```suggestion
- Fetch all messages in a given topic which have been submitted after a given timestamp.
```

2021-07-06 08:51 UTC, dougjewsbury commented on articles/ce/collaboration-message-list.asciidoc
> +you take a risk of skipping some inserted messages in rare edge cases.
```suggestion
you risk skipping some inserted messages in rare edge cases.
```

2021-07-06 08:51 UTC, dougjewsbury commented on articles/ce/collaboration-message-list.asciidoc
> +You can set the message persister in the message list's constructor:
```suggestion
You can set the message persister in the constructor of the message list:
```

2021-07-06 08:52 UTC, dougjewsbury commented on articles/ce/collaboration-message-list.asciidoc
> +(making a `FetchQuery` with Unix epoch as the `getSince()` timestamp).
```suggestion
(doing a `FetchQuery` with Unix epoch as the `getSince()` timestamp).
```

2021-07-06 16:01 UTC, tulioag commented
@magi42 In the preview for this PR, I get a `404` when I try to select `Vaadin 14` in the menu. Is this expected?
![chrome-capture](https://user-images.githubusercontent.com/28783969/124631856-74b8fc00-de8c-11eb-9871-2dbac157d5e7.gif)

2021-07-09 14:28 UTC, tulioag commented on src/main/java/com/vaadin/demo/ce/MessageListDocumentation.java
> +        CollaborationMessageList messageList = new CollaborationMessageList(
@Lift-dev ignore

2021-07-09 15:58 UTC, magi42 commented
@tulioag Well the preview just shows one branch, so you can't change the branch there. Maybe it doesn't get the version number from the current branch, but just shows a default.

2021-07-09 16:13 UTC, magi42 approved these changes

2021-07-09 18:07 UTC, merged