mention the scroll to index issue in TreeGrid
vaadin/docs pull request #636
Opened 2021-07-08 07:34 UTC by sosa-vaadin

## Description

Add a mention and workaround to an issue with the `scrollToIndex(index)` method in TreeGrid.

Related issue: https://github.com/vaadin/flow-components/issues/1016

2021-07-08 12:09 UTC, sissbruecker commented on articles/ds/components/tree-grid/index.asciidoc
> +Without the knowledge of the complete hierarchy, TreeGrid can't reliably calculate an exact scroll index.
```suggestion
TreeGrid uses lazy loading for performance reasons and does not know about the complete hierarchy.
Without the knowledge of the complete hierarchy, TreeGrid can't reliably calculate an exact scroll position.
```

2021-07-09 15:16 UTC, magi42 approved these changes
The "pre-order traverse" is a pretty deep technical term, so I simplified it. Please check that it's still technically correct.

2021-07-09 15:16 UTC, magi42 commented on articles/ds/components/tree-grid/index.asciidoc
> +
```suggestion
The [methodname]#scrollToIndex()# method in [classname]#TreeGrid# works by traversing through the Tree Grid according to their hierarchical order as they would be displayed on the screen, row by row.
However, Tree Grid uses lazy loading for performance reasons and does not know about the complete hierarchy.
Without the knowledge of the complete hierarchy, Tree Grid cannot reliably calculate an exact scroll position.
Therefore, the effective index of an item depends on the complete hierarchy of the tree.

.Index of items can vary
CAUTION: Items in a Tree Grid are not guaranteed to hold a specific index exclusively.
The behavior of the [methodname]#scrollToIndex()# method in Tree Grid *is not deterministic* and *should be avoided*.

```

2021-07-12 10:28 UTC, rolfsmeds requested changes

2021-07-12 10:28 UTC, rolfsmeds commented on articles/ds/components/tree-grid/index.asciidoc
> +=== Avoid Using Scroll to Index
This feels like an unncessarily detailed explanation of _why_ scrollToIndex is problematic. We really just need to explain that scrollToIndex is not reliable and thus should be avoided.

2021-07-12 10:28 UTC, rolfsmeds commented on articles/ds/components/tree-grid/index.asciidoc
> +.Index of items can vary
This admonition title doesn't do a very good job of summarizing the problem, which is that scrollToIndex is not reliable.

I propose omitting the long explanation above in favor of an admonition like:

> .scrollToIndex not reliable
> CAUTION: The behavior of the scrollToIndex method in Tree Grid is *not deterministic* due to lazy loading hierarchical data. Usage of this method is not recommended.

2021-07-14 07:30 UTC, rolfsmeds approved these changes

2021-07-14 07:52 UTC, merged