Revised Fusion application basics
vaadin/docs pull request #640
Opened 2021-07-10 05:55 UTC by magi42

2021-08-13 06:34 UTC, haijian-vaadin requested changes

2021-08-13 06:34 UTC, haijian-vaadin commented on frontend/demo/fusion/application/basic/my-view.ts
> +      </vaadin-notification>
`<vaadin-notification>` component doesn't work in the demo, better to replace with a simple alert, as in https://vaadin.com/docs/latest/fusion/application/events.

2021-08-13 06:34 UTC, haijian-vaadin commented on articles/fusion/application/basics.asciidoc
> +[source,java]
For some reason, the java example doesn't work, it only shows blank.

2021-08-13 06:34 UTC, haijian-vaadin commented on articles/fusion/application/basics.asciidoc
> +The routing configuration also starts a server session and loads any server-side views implemented with Vaadin Flow.
It kinda indicates that Fusion would always create a session. It only creates one if there are server-side views, if not, it would stateless (from v22).

2021-08-18 10:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=640) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=640) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=640) it.</sub>

2021-08-18 10:35 UTC, magi42 commented on articles/fusion/application/basics.asciidoc
> +The routing configuration also starts a server session and loads any server-side views implemented with Vaadin Flow.
Rephrased.

2021-08-18 10:35 UTC, magi42 commented on frontend/demo/fusion/application/basic/my-view.ts
> +      </vaadin-notification>
Ok, using that.

2021-08-18 19:28 UTC, haijian-vaadin approved these changes

2021-08-19 07:10 UTC, merged