Document the CSS loading order
vaadin/docs pull request #66
Opened 2020-12-15 12:31 UTC by mshabarov

Fixes: https://github.com/vaadin/flow/issues/9530

2020-12-15 12:33 UTC, jouni commented
Should rebase to master, the `themes` folder was renamed to `theming`.

2020-12-15 12:34 UTC, jouni requested changes
Rename to `articles/theming/css-loading-order.asciidoc`

2020-12-15 12:45 UTC, jouni requested changes

2020-12-15 12:45 UTC, jouni commented on articles/themes/css-loading-order.asciidoc
> +[source,css]
```suggestion
[source, CSS]
```

The source code language will be visible as written in the docs site (but converted to lowercase for syntax highlighting libraries).

2020-12-15 12:45 UTC, jouni commented on articles/themes/css-loading-order.asciidoc
> +    --lumo-font-size-m: 10px;
```suggestion
    --lumo-font-size-m: 0.875rem;
```
Let’s not give users examples that would give them poor results (10px is too small size in general for main text).

2020-12-15 12:45 UTC, jouni commented on articles/themes/css-loading-order.asciidoc
> +layout: page
```suggestion
```
Unnecessary attribute.

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +[source,css]
```suggestion
[source, CSS]
```
The source code language will be visible as written in the docs site (but converted to lowercase for syntax highlighting libraries).

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +    --lumo-font-size-m: 10px;
```suggestion
    --lumo-font-size-m: 0.875rem;
```
Let’s not give users examples that would give them poor results (10px is too small size in general for main text, and using fixed pixel sizes is also discouraged).

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +layout: page
```suggestion
layout: page
```
Unnecessary attribute.

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +. Parent theme (_if used_)
Is Lumo always loaded, regardless of how I configure my app – even if I decide to use the Material theme? Also, I assumed Lumo would be a parent theme by itself.

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +. Styles added on Java side via `Page::addStylesheet` (_if used_)
This only describes the Flow/Java side of things. If this article is only about that, then it should be mentioned somewhere that this does not apply to Fusion.

2020-12-15 12:45 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +For example, the following style if placed in `global.css` within application theme folder `frontend/themes/my-theme` will override the default `Lumo` font size `1rem` to `10px`:
```suggestion
For example, the following style, if placed in `global.css` within the application theme folder `frontend/themes/my-theme`, will override the default `Lumo` font size `1rem` with `0.875rem`:
```

2020-12-15 13:27 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +layout: page
GH says there are no changes. Should I remove the line completely? `layout: page`

2020-12-15 13:41 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +layout: page
Yes, remove the line completely.

2020-12-15 14:00 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Parent theme (_if used_)
Right, if you use `@Theme(themeClass = Material.class)` or another custom theme class `@Theme(themeClass = CustomTheme.class)`, then the Lumo won't be loaded. Lumo is loaded, if
- No `@Theme` provided
- No `themeClass` provided, but `themeName` provided in `@Theme` parameters.

Thus, I believe I should remove the first item (Lumo) and make a note for Parent theme, that the Lumo is always a parent theme, if the application theme is used (`@Theme("my-theme")`).

2020-12-15 14:04 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Styles added on Java side via `Page::addStylesheet` (_if used_)
Good catch! The Fusion theming is only planned to be done so far. So, I will add a note that this chapter is only for Java-side views. This chapter can be supplemented then, as soon as we conclude the Fusion theming.

2020-12-16 06:34 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Parent theme (_if used_)
done

2020-12-16 06:34 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Styles added on Java side via `Page::addStylesheet` (_if used_)
done

2020-12-16 10:00 UTC, jouni requested changes

2020-12-16 11:15 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +layout: page
done

2020-12-17 07:33 UTC, tanbt commented on articles/theming/css-loading-order.asciidoc
> +A theme is the recommended way to organize styles in a Vaadin application.
> A theme

Should it be "An application theme" or something more specific?
The term "theme" is quite broad, and I confuse between "Lumo" theme or [Custom theme](https://vaadin.com/docs/v14/themes/creating-a-custom-theme.html).

2020-12-17 07:34 UTC, tanbt commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
Since I don't see a specific mention about "application theme", I'm not sure what is the "current theme".

2020-12-17 07:37 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +A theme is the recommended way to organize styles in a Vaadin application.
Initially, it was `application theme`, but then replaced by just `theme` as per Jouni's comment:
>We are still discussing how to write about this new feature, but the current assumption is that it will not be “application theme”.

2020-12-17 07:39 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
Would it be clearer to replace it with `Custom theme`?

2020-12-17 07:44 UTC, tanbt commented on articles/theming/css-loading-order.asciidoc
> +. Parent theme (_if used_)
A bit more details about "Parent theme" maybe helpful ((parent of what, how to make it), maybe a link to a related content.

2020-12-17 07:52 UTC, tanbt reviewed
By the way, do we have any docs about theme hierarchy? Something likes
![image](https://user-images.githubusercontent.com/4935326/102458461-f4948b80-404c-11eb-9215-95b74ab6e594.png)

The hierarchy may related to implementation instead of order loading (isn't it?). But should it be mentioned somewhere somehow (maybe not in this CSS loading page) to give users a better picture and less confusing?

2020-12-17 07:53 UTC, tanbt commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
So "current theme" here is a [custom theme](https://vaadin.com/docs/v14/themes/creating-a-custom-theme.html) but not "application theme"?

2020-12-17 08:20 UTC, tanbt commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
So it's the "application theme", but the term we use in this article is "custom theme" or just "theme".
I guess a link to the related content for "current theme" is also helpful.

2020-12-17 08:39 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
Yep, I propose to add a brief explanation about `Current theme` and add a link to `application-theme.asciidoc` chapter, where the general description is provided.

2020-12-17 08:40 UTC, mshabarov commented
> By the way, do we have any docs about theme hierarchy? Something likes

> The hierarchy may related to implementation instead of order loading (isn't it?). But should it be mentioned somewhere somehow (maybe not in this CSS loading page) to give users a better picture and less confusing?

Good idea to add this hierarchy visualisation! I believe the general chapter (`application-theme.asciidoc`) is a better place for it, and here we can just put the link.

2020-12-17 08:43 UTC, mshabarov commented
@tanbt BTW, what is the `Custom Theme creating-a-custom-theme.html` on the picture? I would maybe replace it with `Parent theme`

2020-12-17 09:29 UTC, tanbt commented
> @tanbt BTW, what is the `Custom Theme creating-a-custom-theme.html` on the picture? I would maybe replace it with `Parent theme`

It's about custom theme in this paper https://vaadin.com/docs/v14/themes/creating-a-custom-theme.html .
It's confused if we use `custom theme` as the term for "application theme" in this paper.

2020-12-17 10:39 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +A theme is the recommended way to organize styles in a Vaadin application.
Yeah, I would like us to avoid introducing new terminology with this feature, it we can avoid it.

2020-12-17 10:40 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +NOTE: `Lumo` theme won't be loaded and applied if another theme class is provided, like this `@Theme(themeClass = MyCustomTheme.class)`, or if
I think either use a proper admonition block (`[NOTE]`), or leave out the `NOTE: ` prefix.

2020-12-18 09:15 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Current theme
done

2020-12-18 09:15 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Parent theme (_if used_)
done

2020-12-18 09:15 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +NOTE: `Lumo` theme won't be loaded and applied if another theme class is provided, like this `@Theme(themeClass = MyCustomTheme.class)`, or if
done

2020-12-18 11:44 UTC, jouni requested changes

2020-12-18 11:44 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +. Application-specific unbundled CSS added via <<importing-style-sheets, @Stylesheet>> (_if used_)
These cross references (links) do not work.

2020-12-18 11:44 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +The <<application-theme#extending-an-existing-application-theme, Parent Theme>> is an existing theme, which styles and variables are inherited in the Current theme.
```suggestion
The <<application-theme#extending-an-existing-application-theme, parent theme>> is an existing theme, whose styles and variables are inherited by the current theme.
```
"Parent theme" and “current theme” are not a proper nouns.

2020-12-18 11:44 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +The Current Theme is a theme used in your application.
```suggestion
"Current theme" is the theme used in your application.
```

2020-12-18 11:44 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +It can be a theme created locally (as described in <<application-theme, Application Theme>> chapter), <<application-theme#creating-a-reusable-applicationtheme, Reusable Theme>> packed as a `jar` depe
The first and last cross references (links) here do not work. Cross references need to include the `#` before the comma, e.g. `<<article/path#, Article Name>>`.

2020-12-18 11:44 UTC, jouni commented on articles/theming/css-loading-order.asciidoc
> +It can be a theme created locally (as described in <<application-theme, Application Theme>> chapter), <<application-theme#creating-a-reusable-applicationtheme, Reusable Theme>> packed as a `jar` depe
You can use the preview deployment to check that the links work.

2020-12-18 12:55 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +It can be a theme created locally (as described in <<application-theme, Application Theme>> chapter), <<application-theme#creating-a-reusable-applicationtheme, Reusable Theme>> packed as a `jar` depe
done

2020-12-18 12:55 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Application-specific unbundled CSS added via <<importing-style-sheets, @Stylesheet>> (_if used_)
done

2020-12-18 12:59 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +It can be a theme created locally (as described in <<application-theme, Application Theme>> chapter), <<application-theme#creating-a-reusable-applicationtheme, Reusable Theme>> packed as a `jar` depe
Not done, still does not work...

2020-12-18 12:59 UTC, mshabarov commented on articles/theming/css-loading-order.asciidoc
> +. Application-specific unbundled CSS added via <<importing-style-sheets, @Stylesheet>> (_if used_)
Not done, still does not work...

2020-12-21 08:20 UTC, mshabarov commented
@tanbt , for the theme hierarchy you were proposing, I've created a separate ticket https://github.com/vaadin/flow/issues/9700 and suggest to handle it separately to not keep this PR hanging.

2020-12-21 10:29 UTC, tanbt approved these changes

2020-12-21 10:41 UTC, jouni approved these changes
Good enough for now. We can improve it iteratively from here on.

2020-12-21 10:41 UTC, merged