Update quick-start-tutorial.asciidoc
vaadin/docs pull request #681
Opened 2021-08-06 11:29 UTC by enver-haase

start.vaadin.com does not have a TODO view and most configurations do not result in a H2 dependency as discussed further down in the article.

2021-08-11 05:32 UTC, tarekoraby commented
@gilberto-torrezan: we need to make sure that Fusion quick-start tutorial and the preset are in sync.

2021-08-19 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=681) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=681) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=681) it.</sub>

2021-08-19 10:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=681) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=681) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=681) it.</sub>

2021-08-20 18:09 UTC, tarekoraby requested changes

2021-08-20 18:09 UTC, tarekoraby commented on articles/fusion/tutorials/quick-start-tutorial.asciidoc
> +Download a starter project from  https://start.vaadin.com/?preset=fusion-tutorial&dl[`start.vaadin.com/?preset=fusion-tutorial&dl`^]. Make sure you click the link rather than configuring a starter pr
I think it would be simpler and more elegant to change this to 
```
Download a https://start.vaadin.com/?preset=fusion-tutorial&dl[`starter project`^].
```

2021-08-24 14:08 UTC, magi42 commented on articles/fusion/tutorials/quick-start-tutorial.asciidoc
> +Download a starter project from  https://start.vaadin.com/?preset=fusion-tutorial&dl[`start.vaadin.com/?preset=fusion-tutorial&dl`^]. Make sure you click the link rather than configuring a starter pr
```suggestion
Download a https://start.vaadin.com/?preset=fusion-tutorial&dl[preconfigured starter project for the Fusion Tutorial^].
(Make sure you click the link to the preconfigured project rather than configuring a project yourself.)
```
I'd avoid complex URLs in text.

2021-09-01 09:24 UTC, magi42 approved these changes

2021-09-02 09:01 UTC, tarekoraby approved these changes

2021-09-02 09:01 UTC, merged