feat: add information about readonly types in generated TypeScript
vaadin/docs pull request #692
Opened 2021-08-11 16:09 UTC by Lodin

Updates the documentation according to the latest Fusion changes.

2021-08-12 05:54 UTC, haijian-vaadin requested changes

2021-08-12 05:54 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +`City.java`
Since these are newly added source code, it's better to put the code into separate files and reference to them via `include::`,  e.g.
```
.`SecurityConfig.java`
[source,java]
----
include::{root}/src/main/java/com/vaadin/demo/fusion/security/authentication/SecurityConfigDemo.java[tags=public-resources]
----
```
in https://github.com/vaadin/docs/edit/latest/articles/fusion/security/spring-login.asciidoc

2021-08-12 10:45 UTC, Lodin commented on articles/fusion/application/accessing-backend.asciidoc
> +`City.java`
Looks like code moved to a separate file is compiled as an executable code while my examples are only visual. So I guess it is better to leave inlined.

2021-08-13 08:58 UTC, haijian-vaadin requested changes

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +`City.ts`
Could remove this, it looks redundant on the page.
![Screenshot 2021-08-13 at 11 01 13](https://user-images.githubusercontent.com/30408303/129324646-632f10cf-9a58-4588-8e3d-04df9bb387d7.png)

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +`CountryEndpoint.java`
Could remove this, it looks redundant on the page.

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +`CountryEndpoint.ts`
Could remove this, it looks redundant on the page.

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +Endpoint methods can return or receive as a parameter any data structure (entity).
```suggestion
An Endpoint method can return or receive a parameter as an entity (non-primitive type).
```

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +In this case, the TypeScript generator creates a TypeScript interface for it.
```suggestion
In this case, the generator also creates a TypeScript interface for the entity.
```

2021-08-13 08:58 UTC, haijian-vaadin commented on src/main/java/com/vaadin/demo/fusion/accessingbackend/CountryEndpoint.java
> +    }
Maybe we can simplify it a bit the endpoint by only showing the `getCityName()` method? The page is getting long with all the source code.
I understand the point of showing one method using it as param the other as return value, but still maybe one is enough.

2021-08-13 08:58 UTC, haijian-vaadin commented on articles/fusion/application/accessing-backend.asciidoc
> +`CountryEndpoint.ts`
Or maybe we could return the whole CountryEndpoint source code? It's kinda repetitive since we showed the CountEndpoint.
Might be better to keep the Entity section about Entity interface generation, not to repeat the Endpoint generation.

2021-08-13 10:49 UTC, Lodin commented on articles/fusion/application/accessing-backend.asciidoc
> +`CountryEndpoint.ts`
I wanted to show how the endpoint with an entity is generated. I believe it is better to show the code here because only the code for an entity might look unclear.

2021-08-13 10:51 UTC, Lodin commented on articles/fusion/application/accessing-backend.asciidoc
> +`City.ts`
Oh, nice catch. Why they appeared this way, I wonder.

2021-08-13 10:51 UTC, Lodin commented on src/main/java/com/vaadin/demo/fusion/accessingbackend/CountryEndpoint.java
> +    }
Right. I'll try to combine everything in one method then

2021-08-13 13:43 UTC, Lodin commented on src/main/java/com/vaadin/demo/fusion/accessingbackend/CountryEndpoint.java
> +    }
@haijian-vaadin, I replaced unnecessary second method with an internal class. I believe it is another good usecase to show for the user. Unfortunately, the amount of code increased. What do you think about it?

2021-08-16 06:48 UTC, haijian-vaadin commented
I think it looks good to me now, just in the read-only part, we could mention one thing, that is, instead of mutating the data, it's better to create a new object, as you showed in the slack discussion.

> you shouldn't mutate any of your data implicitly. Especially if the data you're working with came from the backend. So the best approach here is to create a new object over the clone of a previous one:
> ```
> let user: User = {first: "John", last: "Doe"};
> user = {...user, someOptionalThing: 123};
> ```

2021-08-16 11:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=692) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=692) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=692) it.</sub>

2021-08-16 12:02 UTC, haijian-vaadin commented
Looks good, as discussed in the daily, should we update the upgrading guide here https://github.com/vaadin/docs/blob/latest/articles/guide/upgrading.asciidoc?

2021-08-16 13:02 UTC, Lodin commented
Oh, sure

2021-08-17 05:58 UTC, haijian-vaadin approved these changes

2021-08-17 06:58 UTC, merged