Quarkus
vaadin/docs pull request #737
Opened 2021-09-10 12:27 UTC by denis-anisimov

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-09-10 12:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=737) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=737) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=737) it.</sub>

2021-09-13 05:16 UTC, caalador requested changes
Also I think add `Quarkus` and `CDI` to .github/styles/Vocab/Docs/accept.txt
to not get the nagging `did you really mean`

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +- <<../cdi/events#, Observable Vaadin Eventss>>
```suggestion
- <<../cdi/events#, Observable Vaadin Events>> 
```

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +Check the CDI documentation for these features:
```suggestion
See the documentation for Vaadin CDI features:
```

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +- <<../cdi/nstantiated-beans#, Using CDI Beans>>
```suggestion
- <<../cdi/instantiated-beans#, Using CDI Beans>>
```

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> += Vaadin add-ons in Quarkus Application
```suggestion
== Vaadin add-ons In Quarkus Applications
```
Deployment seems to not accept main headers inside the text...

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +The Vaadin add-on used in Quarkus should have jandex index. This can be done via `jandex-maven-plugin`.
```suggestion
Any Vaadin add-on used in a Quarkus application should contain a jandex index.
This is generated using the `jandex-maven-plugin`.
See https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index[How to Generate a Jandex Index]
```

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +entries to your application.properties:
```suggestion
If you can’t modify the dependency, you can still get Quarkus to index it by adding `quarkus.index-dependency` 
entries to your application.properties:
```

2021-09-13 05:16 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +Websockets Push doesn't work currently in Vaadin integration for Quarkus.
```suggestion
WebSockets Push doesn't work currently in the Vaadin extension for Quarkus.
```

2021-09-13 06:07 UTC, denis-anisimov commented on articles/flow/integrations/quarkus/basic.asciidoc
> +To be able to run Quarkus  the `vaadin-quarkus` and `vaadin-core-jandex` dependencies
I have no idea

I've just checked the base starter structure and put here the vaadin plugins which I found there.
If you say that it's not needed let's remove it.
Should I just remove it or replace with something ?

2021-09-13 06:07 UTC, denis-anisimov commented
> Also I think add `Quarkus` and `CDI` to .github/styles/Vocab/Docs/accept.txt
> to not get the nagging `did you really mean`

done

2021-09-13 06:14 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +To be able to run Quarkus  the `vaadin-quarkus` and `vaadin-core-jandex` dependencies
well at the moment it is needed as I don't think it's part of the vaadin(-core) dependencies, but perhaps we should just say vaadin-jandex as it works with both (vaadin/vaadin-core) cases and doesn't have an impact on the size of the compiled project.

2021-09-13 06:23 UTC, denis-anisimov commented on articles/flow/integrations/quarkus/basic.asciidoc
> +To be able to run Quarkus  the `vaadin-quarkus` and `vaadin-core-jandex` dependencies
done

2021-09-13 07:14 UTC, caalador submitted a review, later dismissed
`jandex` `Jandex` could also be in the accepted file.
Then just the list issue so that they wouldn't be after each other withouth new lines.

2021-09-13 07:14 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +- <<../cdi/instantiated-beans#, Using CDI Beans>>
```suggestion
* <<../cdi/contexts#, Vaadin CDI Scopes>> 
* <<../cdi/events#, Observable Vaadin Events>> 
* <<../cdi/service-beans#, Vaadin Service Interfaces as CDI Beans>>
* <<../cdi/instantiated-beans#, Using CDI Beans>>
```
I guess these should be with `*`s as they are not getting a new line in the preview: https://deploy-preview-737--vaadin-docs-preview.netlify.app/flow/integrations/quarkus/basic/#vaadin-cdi-features

2021-09-13 07:19 UTC, denis-anisimov commented
> `jandex` `Jandex` could also be in the accepted file.
> Then just the list issue so that they wouldn't be after each other withouth new lines.

done

2021-09-13 09:11 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +* <<../cdi/contexts#, Vaadin CDI Scopes>>
```suggestion
See the documentation for Vaadin CDI features:

* <<../cdi/contexts#, Vaadin CDI Scopes>> 
```
Need new line else seen as one line?

2021-09-13 09:11 UTC, caalador commented on articles/flow/integrations/quarkus/basic.asciidoc
> +as a starting point for your own application.
```suggestion
The https://github.com/vaadin/base-starter-flow-quarkus/[Quarkus base starter] project can be used
as a starting point for your own application.
There is also the https://github.com/vaadin/base-starter-flow-quarkus/tree/gradle[base starter for gradle].
```

2021-09-14 06:16 UTC, magi42 approved these changes

2021-09-16 08:24 UTC, merged