feat: add offline docs
vaadin/docs pull request #75
Opened 2020-12-21 12:00 UTC by haijian-vaadin

Fixes https://github.com/vaadin/flow/issues/9640

2020-12-21 12:19 UTC, joheriks submitted a review, later dismissed

2020-12-21 12:19 UTC, joheriks commented on articles/fusion/advanced/fusion-advanced-connection-indicator.asciidoc
> +import {getConnectionIndicator} from '@vaadin/flow-frontend';
After the [API update](https://github.com/vaadin/flow/pull/9706), this should read:
```javascript
import {connectionIndicator} from '@vaadin/flow-frontend';
```

2020-12-21 12:19 UTC, joheriks commented on articles/fusion/advanced/fusion-advanced-connection-indicator.asciidoc
> +const connectionIndicator = getConnectionIndicator();
This line can be removed after the API change.

2020-12-21 12:40 UTC, jouni requested changes

2020-12-21 12:40 UTC, jouni commented on .github/styles/Vocab/Docs/accept.txt
> +viewport
Keep these in alphabetical order.

2020-12-21 12:40 UTC, jouni commented on .github/styles/Vocab/Docs/accept.txt
> +viewport
```suggestion
favicon
Workbox
[vV]iewports?
```

2020-12-21 12:40 UTC, jouni commented on articles/flow/pwa/pwa-offline.asciidoc
> +Vaadin supports two alternative ways of building offline experience:
```suggestion
Vaadin supports two alternative ways of building offline experiences:
```

2020-12-21 12:40 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-connection-indicator.asciidoc
> +layout: page
```suggestion
```
Remove redundant front matter attribute.

2020-12-21 12:46 UTC, jouni commented
Please check and correct the lint errors and warnings at https://github.com/vaadin/docs/compare/haijian/add-offline-doc#diff-0c166d7f725591cdc40fdf4dffb3bf4cf321e7f76ef05b781e86d5e8b9302fcc

2020-12-21 12:47 UTC, jouni commented
Also, please rebase or update from master, to get all latest writing style checks.

2020-12-21 21:57 UTC, haijian-vaadin commented on articles/fusion/advanced/fusion-advanced-connection-indicator.asciidoc
> +import {getConnectionIndicator} from '@vaadin/flow-frontend';
done

2020-12-21 21:57 UTC, haijian-vaadin commented on articles/fusion/advanced/fusion-advanced-connection-indicator.asciidoc
> +const connectionIndicator = getConnectionIndicator();
done

2020-12-21 21:57 UTC, haijian-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +viewport
done

2020-12-21 21:57 UTC, haijian-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +viewport
done

2020-12-21 21:57 UTC, haijian-vaadin commented on articles/flow/pwa/pwa-offline.asciidoc
> +Vaadin supports two alternative ways of building offline experience:
done

2020-12-22 07:29 UTC, jouni commented on articles/flow/pwa/pwa-offline.asciidoc
> +include::{root}/frontend/demo/pwa/offline/ts-view-with-endpoint.ts[render,tags=snippet,indent=0,group=TypeScript]
```suggestion
include::{root}/frontend/demo/pwa/offline/ts-view-with-endpoint.ts[]
```

`render` is only useful if your example file exports a custom element that you want to render in the article.

Use `tags` to only show part of the source code initially (while still allowing the user to expand to see the full source). The `ts-view-with-endpoint.ts` file does not specify any tags, so it is not needed here. Also `indent=0` is mainly useful together with `tags`, as it removes extra white space from the beginning of lines (e.g. if you show a nested snippet from within a class).

Omit `group=...` if you only have either Java/Flow or TypeScript/Fusion example. Groups are only needed if you have an alternative way of implementing the same thing.

2020-12-22 07:30 UTC, jouni commented on articles/theming/application-theme.asciidoc
> +]
Could this actually be defined in the project, and we could include it from the actual `theme.json` file?

2020-12-22 07:32 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .contact-form.ts
```suggestion
```

The file name does not need to be defined when using `include::[]`. It is picked up from the include automatically.

2020-12-22 07:34 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/frontend/demo/fusion/forms/contact-form.ts[render,tags=snippet,indent=0,group=TypeScript]
We might want to consider showing just the most relevant part of the source code using tags. But if you feel the full source code is what the reader needs to see at this point, then that’s fine as well.

Remove `group`, as there is no Flow counterpart for this example.
```suggestion
include::{root}/frontend/demo/fusion/forms/contact-form.ts[render,tags=snippet,indent=0]
```

2020-12-22 07:34 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .Contact.java
```suggestion
```

2020-12-22 07:35 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/fusion/forms/Contact.java[render,tags=snippet,indent=0,group=Java]
```suggestion
include::{root}/src/main/java/com/vaadin/demo/fusion/forms/Contact.java[]
```

2020-12-22 07:35 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .ContactEndpoint.java
```suggestion
```

2020-12-22 07:36 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/fusion/forms/Contact.java[render,tags=snippet,indent=0,group=Java]
This looks like it’s importing the wrong file. Should it be `ContactEndpoint.java` instead?

2020-12-22 07:37 UTC, jouni commented on src/main/java/com/vaadin/demo/fusion/forms/Contact.java
> +  }
This should be a fully functional class, no code should be omitted from the source files within `src` and `frontend` folders. The example should be functional.

2020-12-22 07:37 UTC, jouni commented on src/main/java/com/vaadin/demo/fusion/forms/ContactEndpoint.java
> +}
Please implement the functionality, or at least include a helpful comment how to implement the save functionality in a real project.

2020-12-22 07:38 UTC, jouni commented on src/main/java/com/vaadin/demo/pwa/offline/DataEndpoint.java
> +        return "";
Should this return some example data?

2020-12-22 07:38 UTC, jouni commented
Hmm, I suppose the `feature/offline` branch in the main repo should also be rebased/updated from master, so we wouldn’t see the unnecessary file changes here?

2020-12-28 14:23 UTC, joheriks commented on articles/flow/pwa/pwa-offline.asciidoc
> +include::{root}/frontend/demo/pwa/offline/ts-view-with-endpoint.ts[render,tags=snippet,indent=0,group=TypeScript]
Done. Also updated the example to compile without `@ts-ignore`.

2020-12-28 14:23 UTC, joheriks commented on articles/theming/application-theme.asciidoc
> +]
Seems like a good idea. Though this commit originates from master, so maybe should be refactored via a PR targeting `master` instead of being applied only to `feature/offline` branch.

2020-12-28 14:24 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .contact-form.ts
Done.

2020-12-28 14:27 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .Contact.java
Done.

2020-12-28 14:48 UTC, joheriks commented on src/main/java/com/vaadin/demo/pwa/offline/DataEndpoint.java
> +        return "";
Probably not needed to return something, as it is only there for the generated endpoint TS so that the snippet (`ts-view-with-endpoint.ts` ) compiles.

2020-12-28 16:26 UTC, joheriks commented on src/main/java/com/vaadin/demo/fusion/forms/ContactEndpoint.java
> +}
Added a comment.

2020-12-28 16:26 UTC, joheriks commented on src/main/java/com/vaadin/demo/fusion/forms/Contact.java
> +  }
Implemented functionality.

2020-12-28 16:26 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/fusion/forms/Contact.java[render,tags=snippet,indent=0,group=Java]
Done.

2020-12-28 16:26 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
>  .ContactEndpoint.java
Done.

2020-12-29 09:15 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/frontend/demo/fusion/forms/contact-form.ts[render,tags=snippet,indent=0,group=TypeScript]
Removed the `render` as the form submission does not work well as a live demo at the moment.

2020-12-29 09:16 UTC, joheriks commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/src/main/java/com/vaadin/demo/fusion/forms/Contact.java[render,tags=snippet,indent=0,group=Java]
Done.

2020-12-30 15:28 UTC, jouni commented on articles/fusion/forms/appendix-form-images.asciidoc
> +include::{root}/frontend/demo/fusion/forms/contact-form.ts[render,tags=snippet,indent=0,group=TypeScript]
Hmm, that sounds like a problem, if the endpoint is not responding. I believe @tomivirkki had a working test example of this at some point (early this year). We should investigate that, make it work.

Not blocking the PR for this.

2020-12-30 15:32 UTC, jouni commented on pom.xml
> +        <vaadin.version>19.0-SNAPSHOT</vaadin.version>
Could we use a named release (alpha/beta)?

2020-12-30 15:32 UTC, jouni approved these changes

2020-12-31 07:45 UTC, joheriks commented on pom.xml
> +        <vaadin.version>19.0-SNAPSHOT</vaadin.version>
This is a bit tricky at the moment, as we can't use `19.0.0.alpha1` with latest Flow 6.0 due to recent incompatible changes in the Spring add-on. So we need to wait for the next V19 alpha.

2020-12-31 07:50 UTC, jouni commented on pom.xml
> +        <vaadin.version>19.0-SNAPSHOT</vaadin.version>
Okay, thanks. Then we need to wait for that before we merge this to master. We can use a snapshot in the feature branch.

2020-12-31 10:06 UTC, merged