Add maven documentation and doc for nodeAutoUpdate
vaadin/docs pull request #770
Opened 2021-09-27 10:28 UTC by caalador

Add documentation for Maven plugin properties.
Add documentation for auto update of node version
installed to `~/vaadin`.

part of vaadin/flow#9864

2021-09-27 14:22 UTC, magi42 requested changes

2021-09-27 14:22 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +This doesn't necessarily execute `npm install` is everything seems to be up to date.
```suggestion
This doesn't necessarily execute `npm install` if everything seems to be up to date.
```

2021-09-27 14:22 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +Whether to generate embeddable web components from WebComponentExporter inheritors.
```suggestion
Whether to generate embeddable web components from [classname]#WebComponentExporter# inheritors.
```

2021-09-27 14:22 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +Default to `true`.
```suggestion
Defaults to `true`.
```

2021-09-27 14:22 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +Defines the project frontend directory from where resources should be copied from for use with webpack.
```suggestion
Defines the project frontend directory from where resources should be copied from for using with webpack.
```

2021-09-27 16:28 UTC, magi42 requested changes

2021-09-27 16:28 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +==== Build Frontend Goal Parameters
```suggestion
=== Build Frontend Goal Parameters
```

2021-09-27 16:28 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +For production, the frontend is transpiled for older browsers and optimized, as described in <<../../production#,Deploying to Production>>.
```suggestion
For production, the frontend is transpiled for older browsers and optimized, as described in <<../production#,Deploying to Production>>.
```

2021-09-28 03:48 UTC, caalador commented on articles/shared/guide/configuration/_maven.asciidoc
> +Defaults to `false`.
Vaadin home node is nodejs installed into ` /.vaadin`

Globally installed node is usually in `"program files"`/`"/usr/local/lib"`

And the locally installed node is node that is installed in the root of the maven project.

2021-09-28 03:49 UTC, caalador commented on articles/shared/guide/configuration/_maven.asciidoc
> +True if defined or if it's set to true.
We should just change the sentence to `Defaults to false`

2021-09-28 05:15 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +True if defined or if it's set to true.
OK. But what if someone sets the value to "false"? Does the sentence mean that if it's defined with value "false", it's true?

2021-09-28 05:23 UTC, caalador commented on articles/shared/guide/configuration/_maven.asciidoc
> +True if defined or if it's set to true.
No it will be false. the code that returns the state is:

```
    default boolean isUseDeprecatedV14Bootstrapping() {

        String useDeprecatedV14Bootstrapping = getUseDeprecatedV14Bootstrapping();
        if (useDeprecatedV14Bootstrapping == null) {
            return false;
        }
        if (useDeprecatedV14Bootstrapping.isEmpty()) {
            return true;
        }
        return Boolean.parseBoolean(useDeprecatedV14Bootstrapping);
    }
```

2021-09-28 07:05 UTC, magi42 requested changes
A link still wrong, committing myself.

2021-09-28 07:05 UTC, magi42 commented on articles/shared/guide/configuration/_maven.asciidoc
> +These can be set either as <<../#system-properties, system properties>> or configuration parameters for the plugin.
```suggestion
These can be set either as <<./#system-properties, system properties>> or configuration parameters for the plugin.
```

2021-09-28 07:51 UTC, magi42 approved these changes

2021-09-28 08:07 UTC, merged