feat: introduce API migration instructions
vaadin/docs pull request #772
Opened 2021-09-28 06:56 UTC by pleku

- lists out incompatible/changed API per each legacy component class
- lists out unsupported API per each legaacy component class and instructions how to migrate

Closes vaadin/flow-legacy-components#72

2021-09-28 08:25 UTC, magi42 commented
I'll go through the changes in this PR as well as try to fix other issues in the file as well.

2021-09-28 08:33 UTC, DiegoCardoso requested changes
Spelling issues I found so far.

2021-09-28 12:10 UTC, magi42 reviewed
Did a round of language review and fixed a number of issues, but now noticed that there's still some TODO. Maybe do another round later or give to Doug.

2021-09-28 13:03 UTC, rolfsmeds approved these changes

2021-09-28 13:03 UTC, rolfsmeds commented on articles/flow/upgrading/legacy-component-pack.asciidoc
> +Each component either does ot have a corresponding component available with Flow, or the behavior and API has changes so significantly that it would require much effort to modify the code to migrate
```suggestion
These components either lack counterparts in Flow entirely, or have significantly different APIs, requiring a lot of modifications when migrating.
```

2021-09-28 14:35 UTC, magi42 commented
As there are "TODO" sections, converted to draft to prevent accidental merging.

2021-09-29 06:04 UTC, pleku commented
> As there are "TODO" sections, converted to draft to prevent accidental merging.

@magi42 please note that this is not targeting `latest` branch but `feat/legacy-component-pack` so the idea is to merge it there. We'll make a PR to `latest` once everything is in place.

2021-09-29 07:20 UTC, magi42 commented
@pleku Ah right, OK then.

2021-09-29 07:57 UTC, merged