docs: port grid docs to 14
vaadin/docs pull request #861
Opened 2021-10-27 13:01 UTC by sissbruecker

## Description

Ports grid component docs to v14.

Noteworthy changes to asciidoc or demos:
- asciidoc: commented out references to non-existing documentation, added TODO
- asciidoc: commented out cell focus section, and temp. removed demos - feature is being back-ported ATM
- `GridColumnBorders`: use TemplateRenderer instead of LitRenderer
- `GridColumnFiltering`: use ListDataProvider instead of GridListDataView
- `GridColumnFreezing`: use TemplateRenderer instead of LitRenderer
- `GridContent`: use TemplateRenderer instead of LitRenderer
- `GridDragRowsBetweenGrids`: use ListDataProvider instead of GridListDataView
- `GridExternalFiltering`: use ListDataProvider instead of GridListDataView, use TemplateRenderer instead of LitRenderer
- `GridItemDetailsToggle`: use TemplateRenderer instead of LitRenderer
- `GridNoBorder`: use TemplateRenderer instead of LitRenderer
- `GridNoRowBorder`: use TemplateRenderer instead of LitRenderer
- `GridRichContentSorting`: use TemplateRenderer instead of LitRenderer
- `GridRowReordering`: use ListDataProvider instead of GridListDataView, use TemplateRenderer instead of LitRenderer
- `GridRowStripes`: use TemplateRenderer instead of LitRenderer
- `GridWrapCellContent`: use TemplateRenderer instead of LitRenderer

2021-11-04 19:58 UTC, fhdhsni requested changes

2021-11-04 19:58 UTC, fhdhsni commented on src/main/java/com/vaadin/demo/component/grid/GridDragRowsBetweenGrids.java
> +        grid1.addDropListener(e -> {
to avoid duplicating items when an item is dropped on the same grid it's belong to
```
if(dataProvider1.getItems().contains(draggedItem)) {
    return;
}
```
same with `grid2`

2021-11-04 19:58 UTC, fhdhsni commented on articles/ds/components/grid/index.asciidoc
> +  - 'API: https://cdn.vaadin.com/vaadin-grid/{moduleNpmVersion:vaadin-grid}/#/elements/vaadin-grid[Web Component] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/f
don't know where the version is coming from but [Web Component link](https://cdn.vaadin.com/vaadin-grid/5.8.4/#/elements/vaadin-grid) goes to 5.8.4 which gets `Resource not found`

2021-11-04 19:58 UTC, fhdhsni commented on frontend/demo/init.ts
> +console.log('###apply theme init.ts')
remove the 🪵

2021-11-08 09:16 UTC, sissbruecker commented on src/main/java/com/vaadin/demo/component/grid/GridDragRowsBetweenGrids.java
> +        grid1.addDropListener(e -> {
Done

2021-11-08 09:16 UTC, sissbruecker commented on frontend/demo/init.ts
> +console.log('###apply theme init.ts')
Done

2021-11-08 09:18 UTC, sissbruecker commented on articles/ds/components/grid/index.asciidoc
> +  - 'API: https://cdn.vaadin.com/vaadin-grid/{moduleNpmVersion:vaadin-grid}/#/elements/vaadin-grid[Web Component] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/f
My guess is that the docs have not been deployed correctly when releasing the version. The link should be correct, the same link can be found in the release notes: https://cdn.vaadin.com/vaadin-grid/5.8.4/#/elements/vaadin-grid

I would suggest to move ahead with this PR, I'll raise the issue about the missing docs in Slack

2021-11-08 09:25 UTC, sissbruecker commented on articles/ds/components/grid/index.asciidoc
> +  - 'API: https://cdn.vaadin.com/vaadin-grid/{moduleNpmVersion:vaadin-grid}/#/elements/vaadin-grid[Web Component] / https://vaadin.com/api/platform/{moduleMavenVersion:com.vaadin:vaadin}/com/vaadin/f
Deployed the docs through magi-cli to the CDN, maybe it takes a while for them to show up. I'll check back later.

2021-11-08 10:09 UTC, fhdhsni approved these changes

2021-11-08 10:14 UTC, merged