fix: Add clarification to Quarkus chapter
vaadin/docs pull request #876
Opened 2021-11-01 19:26 UTC by mshabarov

## Description

Fixes https://github.com/vaadin/quarkus/issues/47

## Type of change

- [ ] Bugfix
- [ ] Feature

## Checklist

- [ ] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [ ] New and existing tests are passing locally with my change.
- [ ] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-11-03 10:33 UTC, caalador requested changes

2021-11-03 10:33 UTC, caalador commented on articles/flow/integrations/quarkus.asciidoc
> +https://github.com/vaadin/base-starter-flow-quarkus/[Quarkus base starter] has all the needed dependencies to start developing your application.
This line is extra and the `Adding Dependencies` should be renamed to `Manual Setup` or something as just before this "chapter" there is the line `It is a project template with the necessary configuration and dependencies included for starting to build your own application.` saying exactly this. It shouldn't need duplicating.

2021-11-03 10:33 UTC, caalador commented on articles/flow/integrations/quarkus.asciidoc
> +----
This is the default production mode profile and should just link to https://vaadin.com/docs/latest/flow/guide/production/#enabling-the-production-mode with the addition of if you didn't start from the starter.

2021-11-03 12:30 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +[source,bash]
Let’s use "terminal" as the general term for command line snippets.

```suggestion
[source,terminal]
```

2021-11-04 11:48 UTC, mshabarov commented on articles/flow/integrations/quarkus.asciidoc
> +[source,bash]
done

2021-11-04 11:48 UTC, mshabarov commented on articles/flow/integrations/quarkus.asciidoc
> +----
done

2021-11-04 11:48 UTC, mshabarov commented on articles/flow/integrations/quarkus.asciidoc
> +https://github.com/vaadin/base-starter-flow-quarkus/[Quarkus base starter] has all the needed dependencies to start developing your application.
done

2021-11-04 12:12 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +Quarkus base starter already includes the needed maven configuration for running application in production mode.
```suggestion
Quarkus base starter already includes the needed Maven configuration for running the application in production mode.
```

2021-11-05 04:44 UTC, caalador commented on articles/flow/integrations/quarkus.asciidoc
> +```
To keep the same format as used before, should we have this as
```suggestion
[source,terminal]
----
$ mvn package -Pproduction
$ java -jar target/quarkus-app/quarkus-run.jar
----
```

2021-11-05 09:50 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +```
I think we shouldn't use the `$` symbol in terminal commands. Doesn't that make it difficult to copy paste?

2021-11-05 09:52 UTC, caalador commented on articles/flow/integrations/quarkus.asciidoc
> +```
That would be good too. I expect the whole documentation should be looked through to not have them even for single line commands.

2021-11-05 13:45 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +```
I’ll unify these in the latest branch.

2021-11-05 14:08 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +```
Updated everything else except this Quarkus article.

2021-11-09 08:51 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +If you use a project not based on the starter, it needs the configuration described in https://vaadin.com/docs/latest/flow/guide/production/#enabling-the-production-mode[Enabling the Production Mode]
```suggestion
If you use a project not based on the starter, it needs the configuration described in <<{articles}/flow/guide/production#enabling-the-production-mode, Enabling the Production Mode>>.
```

2021-11-09 08:52 UTC, jouni commented on articles/flow/integrations/quarkus.asciidoc
> +$ mvn package quarkus:dev
```suggestion
mvn package quarkus:dev
```

2021-11-10 10:47 UTC, caalador approved these changes

2021-11-10 14:01 UTC, merged