docs(upgrade): add a note note about TypeScript catch type change
vaadin/docs pull request #888
Opened 2021-11-02 16:05 UTC by platosha

Fixes vaadin/fusion#108

2021-11-09 10:54 UTC, Haprog requested changes

2021-11-09 10:54 UTC, Haprog commented on frontend/demo/fusion/errorhandling/catch-error.ts
> +      console.warn(error.message); // "Not implemented"
Was this line moved intentionally? We can now also remove the `any` from the catch line right?

2021-11-09 11:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/docs?pullRequest=888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/docs?pullRequest=888) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: platosha<br/>:x: Haprog<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/docs?pullRequest=888) it.</sub>

2021-11-10 13:08 UTC, dougjewsbury commented on articles/shared/upgrading/_changes.asciidoc
> +In practice, the error handling code that did not involve `instanceof` guards needs changes.
```suggestion
As a result, there need to be changes to the error handling code that did not involve `instanceof` guards.
```

2021-11-12 12:32 UTC, platosha commented on frontend/demo/fusion/errorhandling/catch-error.ts
> +      console.warn(error.message); // "Not implemented"
Yes, intentional, as `instanceof` type guard . Let me remove it.

2021-11-15 09:46 UTC, Haprog approved these changes

2021-11-15 10:56 UTC, jouni commented
@Haprog, when you update the labels, remember to remove the corresponding "not OK" label. For example, when you add `TypeScript OK` label, remember to remove the `TypeScript` label.

2021-11-15 11:14 UTC, merged

2021-11-15 11:21 UTC, Haprog commented
> @Haprog, when you update the labels, remember to remove the corresponding "not OK" label. For example, when you add `TypeScript OK` label, remember to remove the `TypeScript` label.

Ok, thanks. I thought the other label means "requires TS review" so it didn't make sense to me to remove it. I can follow your advice for the future.

2021-12-09 10:30 UTC, jouni commented
FYI, note that this same article is currently used for both the Flow and Fusion upgrading guides. Changes only relevant for Fusion should be shown only inside the `ifdef::fusion[]` ... `endif::fusion[]` tags, and similarly with Flow `ifdef::flow[]`.

I noticed this today, and updated it so that the section added by this PR is only shown in the Fusion upgrading guide.