docs: port radio button component docs to 14
vaadin/docs pull request #900
Opened 2021-11-08 10:03 UTC by sissbruecker

## Description

Ports radio button docs to v14.

Noteworthy changes to asciidoc or demos:
- asciidoc: commented out references to non-existing documentation, added TODO

2021-11-09 15:42 UTC, sosa-vaadin requested changes
There's only a few lines with multiple sentences which should be split into one line per sentence. Other than that, it looks good.

2021-11-09 15:42 UTC, sosa-vaadin commented on articles/ds/components/radio-button/index.asciidoc
> +Use read-only when content needs to be accessible but not editable. Read-only elements cannot be edited, but they do participate in the tabbing order and can thus receive focus. The contents of a rea
Write one sentence per line.
```suggestion
Use read-only when content needs to be accessible but not editable.
Read-only elements cannot be edited, but they do participate in the tabbing order and can thus receive focus.
The contents of a read-only input can be selected and copied.
```

2021-11-09 15:42 UTC, sosa-vaadin commented on articles/ds/components/radio-button/index.asciidoc
> +Disable a field to mark it as currently unavailable. Disabled state is used for fields that are not editable and do not need to be readable. Disabled elements cannot be focused and may be inaccessibl
Write one sentence per line.
```suggestion
Disable a field to mark it as currently unavailable.
Disabled state is used for fields that are not editable and do not need to be readable.
Disabled elements cannot be focused and may be inaccessible to assistive technologies like screen readers.
```

2021-11-09 15:42 UTC, sosa-vaadin commented on articles/ds/components/radio-button/index.asciidoc
> +To enable the user to enter a custom option instead of picking one from the list, use an “Other” radio button at the bottom of the list with an associated Text Field for entry. The field should be hi
Write one sentence per line.
```suggestion
To enable the user to enter a custom option instead of picking one from the list, use an “Other” radio button at the bottom of the list with an associated Text Field for entry.
The field should be hidden or disabled until the “Other” option is selected.
```

2021-11-09 15:42 UTC, sosa-vaadin commented on articles/ds/components/radio-button/index.asciidoc
> +It is generally recommended to set the most common option as the default value for Radio Button Groups. Place the default option at the top of the list.
Write one sentence per line.
```suggestion
It is generally recommended to set the most common option as the default value for Radio Button Groups.
Place the default option at the top of the list.
```

2021-11-09 15:42 UTC, sosa-vaadin commented on articles/ds/components/radio-button/index.asciidoc
> +// TODO split this into two examples, do and dont
Any reason why not do it in this PR?

2021-11-09 16:22 UTC, sissbruecker commented
@sosa-vaadin In general I would prefer to keep the content untouched for the initial back-porting. In order to keep the docs in sync, it makes more sense to tackle this in `latest` first, and then back-port it.

2021-11-10 06:56 UTC, sosa-vaadin approved these changes

2021-11-10 07:36 UTC, merged