docs: restore cross-references in component docs
vaadin/docs pull request #922
Opened 2021-11-12 10:25 UTC by sissbruecker

## Description

Restores cross-references in component docs. Note that there are still some remaining TODOs that can only be resolved after porting the foundation docs, or porting certain features.

2021-11-12 10:51 UTC, sissbruecker commented
Waiting for https://github.com/vaadin/docs/pull/914

2021-11-15 12:14 UTC, fhdhsni requested changes

2021-11-15 13:04 UTC, sissbruecker commented on articles/ds/components/accordion/index.asciidoc
> +(The <<../details#,Details>> component can be used to allow multiple simultaneously expanded sections.)
Done

2021-11-15 13:05 UTC, fhdhsni approved these changes

2021-11-15 16:05 UTC, merged