feat: add doc for typescript auth helpers
vaadin/docs pull request #94
Opened 2021-01-07 11:49 UTC by haijian-vaadin

2021-01-11 08:27 UTC, jouni commented
@haijian-vaadin, please update from master, to get the Vale check running correctly. Do a rebase preferably, if possible. Otherwise you need to touch each .asciidoc file to trigger the check for them.

2021-01-11 09:25 UTC, joheriks requested changes

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +}
Since this is pretty much self-contained, would it make sense to have here embedded code isntead of inline to ensure that it compiles now and in the future?

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +After the login view is defined, you should also define a route for the login view component, for example in the `index.ts` file. Note, the `path` for the login view component should be the same as w
"should be the same as what you defined in" could be reworded as "should match the one defined in".

May need a newline after this as the below snippet is not rendered correctly:
<img width="719" alt="rndr" src="https://user-images.githubusercontent.com/2838896/104163079-797d8580-53fe-11eb-82d0-61016278c7db.png">

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +Instead of using the <<fusion-security-spring-login#, default Spring login form>>, you may want to use your own customized form. This article describes how to do that.
One sentence per line.

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +a `loggedIn` variable stored in the https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage[localStorage] to check if the user is logged in. The `loggedIn` variable needs to be reset whe
One sentence per line.

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +title: Appendix: Handle session expiration in TypeScript
Is it intended to be an appendix? Seems other sections don't have appendices.

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +The `InvalidSessionMiddleWare` requires a `OnInvalidSessionCallback` as a constructor parameter. The `OnInvalidSessionCallback` is a function that takes no parameters and should return a promise of `
One sentence per line.

2021-01-11 09:25 UTC, joheriks commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +----
Could these two be embedded code instead of snippet?

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +After the login view is defined, you should also define a route for the login view component, for example in the `index.ts` file. Note, the `path` for the login view component should be the same as w
good catch, done

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +Instead of using the <<fusion-security-spring-login#, default Spring login form>>, you may want to use your own customized form. This article describes how to do that.
done

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +a `loggedIn` variable stored in the https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage[localStorage] to check if the user is logged in. The `loggedIn` variable needs to be reset whe
done

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +title: Appendix: Handle session expiration in TypeScript
done, removed the Appendix prefix

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +The `InvalidSessionMiddleWare` requires a `OnInvalidSessionCallback` as a constructor parameter. The `OnInvalidSessionCallback` is a function that takes no parameters and should return a promise of `
done

2021-01-18 07:24 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +----
good point moved them to separate src files

2021-01-18 09:09 UTC, joheriks commented on articles/fusion/security/fusion-security-custom-spring-login.asciidoc
> +a `loggedIn` variable stored in the https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage[localStorage] to check if the user is logged in. The `loggedIn` variable needs to be reset whe
Seems there still two sentences per line in some places. Also the other Vale errors could be good to fix.

2021-01-18 11:49 UTC, jouni requested changes
It pains me a little bit, that there are two `login-view.ts` files that have some amount of the same code.

I wonder if there’s a way to avoid the duplication? I didn’t look in detail if that would make sense, though – maybe the examples are different enough that the copy-pasted code doesn’t hurt.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +title: Handle session expiration in TypeScript
```suggestion
title: Handling Session Expiration
```
No need to explicitly state “in TypeScript”, as we are writing documentation for Fusion.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> += Handle session expiration in TypeScript
```suggestion
= Handling Session Expiration
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +Vaadin provides a built-in <<../advanced/fusion-advanced-client-middleware#, middleware>> `InvalidSessionMiddleWare` that you can use to detect session expiration, for example, to show a login view t
```suggestion
Use the built-in <<../advanced/fusion-advanced-client-middleware#, middleware>> `InvalidSessionMiddleWare` to detect session expiration, for example, to show a login view to the user.
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +----
```suggestion
.Example using `InvalidSessionMiddleWare`
[.example]
--
[source, typescript]
----
include::{root}/frontend/demo/fusion/authentication/handle-session-expiration/connect-client.ts[]
----

[source, typescript]
----
include::{root}/frontend/demo/fusion/authentication/handle-session-expiration/login-view.ts[]
----
--
```

2021-01-18 11:49 UTC, jouni commented on frontend/demo/fusion/authentication/handle-session-expiration/login-view.ts
> +      <vaadin-login-overlay opened .error=${this.error} @login="${this.login}">
```suggestion
      <vaadin-login-overlay opened .error="${this.error}" @login="${this.login}">
```

Consistency with quotes.

2021-01-18 11:49 UTC, jouni commented on frontend/demo/fusion/authentication/login-view.ts
> +      <vaadin-login-overlay opened .error=${this.error} @login="${this.login}">
```suggestion
      <vaadin-login-overlay opened .error="${this.error}" @login="${this.login}">
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +title: PWA offline authentication checks
```suggestion
title: Offline Authentication Checks
```
IMO “PWA” is not something we should have in the article titles. It’s a technical umbrella term, and I feel it doesn’t add value.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> += Security aspects of Offline authentication checks
```suggestion
= Security Aspects of Offline Authentication Checks
```

Not sure about this, but it feels the page title could start with the same terms as are used in the navigation title.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +It is possible to do authentication checks offline. The article describes the security aspects of offline authentication checks that are good to take into account for PWAs.
```suggestion
Take the following security aspects into account when you do authentication checks while the user is offline
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +Arguably, not many apps would need to securely verify the user authenticity offline, and most can simply check if an online login happened in the not-so-distant past.
```suggestion
Arguably, not many apps would need to securely verify the user authenticity offline, and most can simply check if an online login happened in the not-so-distant past.

```

Lists do not render as expected unless they are separated from the paragraph before it.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> + - And if you need to add a more reliable expiration mechanism, you could use signed tokens (for example, JWT) so that the client can strongly verify the timestamp of the last login. Though, it is st
```suggestion
- For that the simplest approach would be set a local storage flag after a user has successfully logged in online (and clear it when the user logs out).
During offline navigation, the user auth then would be checked from the local storage.
The <<../security/fusion-security-custom-spring-login#, Adding a Custom Login Form with Spring Security>> article describes how to do that.
It is worth to classify that this as a UX improvement, not as a security feature, because it is easy to bypass through the browser dev tools.

- And if you need to add a more reliable expiration mechanism, you could use signed tokens (for example, JWT) so that the client can strongly verify the timestamp of the last login.
Though, it is still not bulletproof because the user may change the date on the device.
```

No need to indent the list dashes. Also, each sentence on their own line.

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +When it comes to authorization (checking roles), in reality, it is only feasible on the backend. The reason is simple - the backend is the only place that can reliably guard the data the user is not
```suggestion
When it comes to authorization (checking roles), in reality, it is only feasible on the backend.
The reason is simple – the backend is the only place that can reliably guard the data the user is not authorized to view/modify.
Once some data has reached the client, you have to assume it may be tampered with.
So when it comes to, for example, checking whether or not a user has a role to access a certain view, the client-side implementation is mostly about the UX.
You would need a way to check if the user has the permissions to navigate to a view, but this way does not need to be a particularly secure one.
In case if the user tampers with the permission on their device, they may end up navigating to that view anyway, but they will not see any sensitive data because that would be securely guarded by the backend.
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +So, what you may end up doing in case when you want to keep more than a plain `isLoggedIn` flag, is keeping a list of user roles in plain text in the local storage, and checking against that list in
```suggestion
What you may end up doing in case when you want to keep more than a plain `isLoggedIn` flag, is keeping a list of user roles in plain text in the local storage, and checking against that list in offline navigation. 
```

2021-01-18 11:49 UTC, jouni commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +Using secure tokens, like JWT, makes the list of roles secure - it is cryptographically signed and the client app may verify that it has not been tampered with. While such tokens are extremely useful
```suggestion
Using secure tokens, like JWT, makes the list of roles secure – it is cryptographically signed and the client app may verify that it has not been tampered with.
While such tokens are extremely useful when accessing the backend because they allow the backend to be stateless, there are no particular benefits for client-side offline authentication.
```

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +title: Handle session expiration in TypeScript
Good comment, done.
Regarding the 2 login-views. good comment, one focuses on the overlay part, renamed that one into login-overlay.ts, and removed some duplicated code.

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> += Handle session expiration in TypeScript
done

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +Vaadin provides a built-in <<../advanced/fusion-advanced-client-middleware#, middleware>> `InvalidSessionMiddleWare` that you can use to detect session expiration, for example, to show a login view t
done

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/security/fusion-security-handle-session-expiration.asciidoc
> +----
done

2021-01-18 13:38 UTC, haijian-vaadin commented on frontend/demo/fusion/authentication/handle-session-expiration/login-view.ts
> +      <vaadin-login-overlay opened .error=${this.error} @login="${this.login}">
done

2021-01-18 13:38 UTC, haijian-vaadin commented on frontend/demo/fusion/authentication/login-view.ts
> +      <vaadin-login-overlay opened .error=${this.error} @login="${this.login}">
done

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +title: PWA offline authentication checks
Good point, done

2021-01-18 13:38 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> += Security aspects of Offline authentication checks
done

2021-01-18 13:39 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +It is possible to do authentication checks offline. The article describes the security aspects of offline authentication checks that are good to take into account for PWAs.
done

2021-01-18 13:39 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +Arguably, not many apps would need to securely verify the user authenticity offline, and most can simply check if an online login happened in the not-so-distant past.
done

2021-01-18 13:40 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> + - And if you need to add a more reliable expiration mechanism, you could use signed tokens (for example, JWT) so that the client can strongly verify the timestamp of the last login. Though, it is st
done

2021-01-18 13:40 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +When it comes to authorization (checking roles), in reality, it is only feasible on the backend. The reason is simple - the backend is the only place that can reliably guard the data the user is not
done

2021-01-18 13:40 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +So, what you may end up doing in case when you want to keep more than a plain `isLoggedIn` flag, is keeping a list of user roles in plain text in the local storage, and checking against that list in
done

2021-01-18 13:40 UTC, haijian-vaadin commented on articles/fusion/pwa/pwa-offline-authentication-check.asciidoc
> +Using secure tokens, like JWT, makes the list of roles secure - it is cryptographically signed and the client app may verify that it has not been tampered with. While such tokens are extremely useful
done

2021-01-18 13:56 UTC, haijian-vaadin commented
Oh, finally it's all green, no more Vale errors.

2021-01-18 14:56 UTC, joheriks commented
Got this TS error when running `mvn spring-boot:run`:
```
ERROR in [at-loader] ./frontend/demo/fusion/authentication/handle-session-expiration/login-overlay.ts:10:11 
    TS6133: 'onSuccess' is declared but its value is never read.
```

2021-01-19 08:05 UTC, joheriks commented
I noticed an error in the build:
```
error /Users/joheriks/vaadin/docs/articles/fusion/security/fusion-security-custom-spring-login.asciidoc, line 9 - level 0 sections can only be used when doctype is book
```
Seems to be because of the line just before:
```
ifdef::env-github[:outfilesuffix: .asciidoc]
```
What is this for, is it needed?

2021-01-19 10:12 UTC, haijian-vaadin commented
Confirmed with the doc team, it's not needed, I removed it.

2021-01-19 10:29 UTC, joheriks commented
> Confirmed with the doc team, it's not needed, I removed it.

There are some other Vale errors in that file now reported that could be fixed (Vale errors blink because they are cleared between checks and only reported for files touched in the last commit).

2021-01-19 13:10 UTC, joheriks approved these changes

2021-01-19 20:18 UTC, jouni approved these changes

2021-01-20 10:38 UTC, jouni requested changes

2021-01-20 10:38 UTC, jouni commented on .github/styles/Vocab/Docs/accept.txt
> +src
We should not introduce this change. Where is this causing problems? I believe all occurences of this “word” should either be inside code snippets or `[filename]##` classes, and therefore not part of the linting checks.

2021-01-20 10:40 UTC, haijian-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +src
I don't remember, I think I got a Vale error. I can remove this and let's see.

2021-01-20 10:44 UTC, haijian-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +src
Yes, this one https://github.com/vaadin/docs/pull/94/files#annotation_853322011

2021-01-20 13:05 UTC, jouni requested changes

2021-01-20 13:21 UTC, haijian-vaadin commented on .github/styles/Vocab/Docs/accept.txt
> +LDAP
thanks for the comment, done

2021-01-20 14:20 UTC, jouni approved these changes

2021-01-20 20:14 UTC, merged