Add description for themes hierarchy
vaadin/docs pull request #95
Opened 2021-01-07 17:00 UTC by tanbt

Resolves https://github.com/vaadin/flow/issues/9700

2021-01-08 11:56 UTC, caalador requested changes

2021-01-08 11:56 UTC, caalador commented on articles/theming/overview.asciidoc
> +A theme is created in a separate folder under the `frontend/themes/`, `src/main/resources/static` or `src/main/resources/META-INF/resources/themes`.
I feel we should stay only on frontend/themes and not bring the reusable folders into the overview explanation.

2021-01-08 11:56 UTC, caalador commented on articles/theming/overview.asciidoc
> +Themes can be packaged as a JAR file and reused in multiple applications. A theme can also extend and overwrite an existing "parent theme".
Here we could mention that in this case the theme files should be located in either of the resources folders

2021-01-08 11:56 UTC, caalador commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
I don't see why is this server-side only?

2021-01-08 11:56 UTC, caalador commented on articles/theming/overview.asciidoc
> +<7> A theme is the recommended way to style a Vaadin application. It can extend a parent theme. Themes are based on Lumo built-in theme. See <<application-theme#, Theme>>.
Why are these under lumo specifically? stylesheet and cssimport don't have to depend on lumo at all.
Parent theme also is only relevant for custom-theme and we shouldn't promote the old way of extending lumo or material

2021-01-10 10:24 UTC, tanbt commented on articles/theming/overview.asciidoc
> +A theme is created in a separate folder under the `frontend/themes/`, `src/main/resources/static` or `src/main/resources/META-INF/resources/themes`.
Fixed.

2021-01-10 10:24 UTC, tanbt commented on articles/theming/overview.asciidoc
> +Themes can be packaged as a JAR file and reused in multiple applications. A theme can also extend and overwrite an existing "parent theme".
Added.

2021-01-10 10:24 UTC, tanbt commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
I saw https://vaadin.com/docs/v14/themes/creating-a-custom-theme.html mentions `This documentation applies only to server-side (Java) applications.`
Is it correct?

2021-01-10 10:24 UTC, tanbt commented on articles/theming/overview.asciidoc
> +<7> A theme is the recommended way to style a Vaadin application. It can extend a parent theme. Themes are based on Lumo built-in theme. See <<application-theme#, Theme>>.
Fixed.

2021-01-11 06:54 UTC, caalador commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
V14 theme is quite different for what the Application theme is as it's available for use with fusion and can be used for client side theme things also.

2021-01-11 07:41 UTC, caalador commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
Also I don't think the custom-theme should be mentioned anymore as it's not a feature we want to promote @pleku

2021-01-11 08:25 UTC, jouni commented
The Vale check is again running as expected. Please fix all errors and hopefully all warnings as well 🤗

2021-01-11 10:45 UTC, tanbt commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
This hierarchy is meant to structure and connect all the ways of styling an app.
That's why I mentioned custom-theme here, so users won't ask e.g. "why don't just use custom theme instead of application?".

Should custom-theme be marked as `deprecated` or `not recommended`?

2021-01-12 08:17 UTC, caalador commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
@pleku Now that the new theme is called Custom Theme what should be done about this legacy custom theme? should it get the legacy label on this document?

2021-01-12 09:57 UTC, jouni commented on articles/theming/overview.asciidoc
> +│   └── Material theme (deprecated) <8>
I’ve seen this “deprecated” notice twice now. When was this decided? @rolfsmeds, can you elaborate?

2021-01-12 10:01 UTC, jouni commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
The whole “Theming” sections would benefit from a holistic rewrite. I’ve added that to my backlog, but I can’t promise when I would have the time to start drafting that.

2021-01-12 10:10 UTC, jouni commented on articles/theming/overview.asciidoc
> +NOTE: In case styles of an element are defined in multiple places (by `@CssImport` and `@StyleSheet` and a theme, for example) with the same selector, the styles will be applied following this <<css-
```suggestion
If multiple style sheets define styles for an element (for example, imported with `@CssImport`, `@StyleSheet`, and by a theme), the styles are applied in a specific order. See <<css-loading-order#, CSS Loading Order>> for details.
```

2021-01-12 13:24 UTC, pleku commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
There has been some back-and-worth with this, but to my understanding, the way things go now is:
1) Vaadin has two inbuilt themes for the components: Lumo and Material.
2) Lumo is the default theme you get when building apps with Vaadin
3) Starting from v19, we have a new _custom theme feature_ for Vaadin applications which improves theming experience by
- providing a unified way to do all theming related things
- being able to reuse and extend your custom themes in other applications
4) When you want to do any styling of your application, using a custom theme is the way to go.
5) Anything we used to have for theming before v19, like `@StyleSheet` or `@CssImport` does still work and is not deprecated to be removed but it is secondary to creating a custom theme. These are supported and documented, but not "highlighted" anymore due to 4).

If I've misinterpreted this, please correct me.

I think we've done a good effort overall, but when I look at the whole theming documentation chapter at the moment, I don't think it reflects the points 1-5 from above. This is not in particular anyone's fault, it is just what has evolved for number of reasons like: not having clear idea on what to call the new feature (now it is custom theme, used to be application theme), lacking design for the theming docs structure, combining flow, fusion and component theming in to one chapter, unclear ownership for the theming docs ... 

As we're now going out with the new custom theme feature, it is obvious that the theming documentation needs a larger overhaul. But it is an open question that who does it and when ? Should the flow team just get on with it ? @jouni @rolfsmeds

2021-01-12 13:51 UTC, jouni commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
Thanks, Pekka, for the comprehensive overview of the situation. I agree with all that you said.

I also want to emphasize that this isn’t anyones fault, there’s not even anything to consider as a failure. Well, perhaps communication is the thing that always fails 😄, but this is a good effort to fix that.

I’’m mentally prepared to do this work. But since I’m also caught up in a much larger restructure design of the docs, I would appreciate any help.

2021-01-12 14:09 UTC, rolfsmeds commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
Fwiw, I've also had _"Rewrite theming documentation with Jouni"_ on my backlog for some time already, so I'd say it's mostly a matter of scheduling some time for us to do that (preferrably before V19 GA), possibly with some help from the Flow team as needed.

2021-01-13 08:55 UTC, tanbt commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
My big concern is that "custom theme" term is already used by https://vaadin.com/docs/themes/creating-a-custom-theme.html which will likely to appear on Google search.

Now "application theme" is also called "custom theme". Then how to deal with that old "custom theme"? Deprecate, remove, hide or redirect it or something?

2021-01-13 09:32 UTC, pleku commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
When I look at that  https://vaadin.com/docs/themes/creating-a-custom-theme.html I feel that it is something that nobody should do anymore for any new project. So that leaves couple of options:
a) remove the outdated custom theme doc completely and rename application theme doc -> _Custom theme_  or _Creating a custom theme_
b) "deprecate" the outdated _creating a custom theme_ doc with notices in the doc saying that it does not apply after v19, linking to the new docs. Move it to be the last document page under theming, change the header to "Custom themes before v19" (later on Custom themes before Vaadin 14.5 & 19). The application theme doc would still be renamed to Custom Theme.

I would be fine with going with A) immediately as it is not needed even after reworking things - it is very rarely used feature and someone can probably find it from the old docs site if needed (?). WDYT @jouni @rolfsmeds 

I think would help a lot already now.

2021-01-13 09:55 UTC, jouni commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
I would replace the current “Creating a Custom Theme” article with a new one (and have it at the same place in the nav as the current “Application Theme” article), that explains how to use the new feature. We are, after all, writing documentation for Vaadin 19, not for Vaadin 14. The previous version of the article is still available in the v14 docs – we don’t need to drag it with us in the latest docs.

2021-01-13 16:16 UTC, tanbt commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
> replace the current “Creating a Custom Theme” article with a new one

Done. Please check.

2021-01-13 16:25 UTC, jouni commented
> Please fix all errors and hopefully all warnings as well

As a clarification: you don’t need to fix the warnings and errors for content that you haven’t modified. But avoid introducing more content that has warnings and/or errors.

2021-01-13 17:21 UTC, jouni commented on articles/theming/overview.asciidoc
> +└── custom theme (server-side only)  <9>
Works as expected 👍

I’m not reading the content with a super critical eye, as the expectation is that parts of it will be rewritten. I believe it serves it’s purpose decently until we have the time for that.

2021-01-14 07:25 UTC, merged