apply suggested improvements from app theme DX part2
vaadin/docs pull request #96
Opened 2021-01-08 07:36 UTC by taefi

Fixes: #9737

2021-01-08 13:04 UTC, caalador requested changes

2021-01-08 13:04 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +Now besides to overriding parent theme's styles, new styles can be added also through the local theme folder and its configurations.
```suggestion
The extending theme can override parent theme styles as well as add its own.
```

2021-01-08 13:04 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +│       │       └── example
com.example is bad from the spring perspective.
com.vaadin.flow.component would be better

2021-01-08 13:04 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +. Remove `src/test` as well as `App.java` from `src/main/java/`. (Optional)
As the App.java is not used it shouldn't be added to the generated jar and thus should be removed.

2021-01-08 13:42 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +<1> Activating multiple application themes at the same time.
The idea was from one DX tester who wanted to use a set of styles from one theme, and another set of styles from another theme. So he wanted to add 2 theme jars to the project and activating them by something like: 
```
@Theme("theme-A", "theme-B")
```
or 
```
@Theme("theme-A")
@Theme("theme-B")
public class Something { }
```
And OFC the API and a runtime exception would inform him those possibilities are not in the picture, but it would be much nicer to have them directly in docs.

2021-01-08 13:48 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +        ├── some-fonts <5>
I think the explanation below the figure is clear enough to show they are optional. Also, in another part of this doc, there is an example of using relative path used in CSS which refers to images inside "some-images". Although that example is not update from "images" to "some-images".

2021-01-08 14:01 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +Component-specific style sheets should be placed under the `components` folder.
This is something suggested by grammarly to change the passive tone of the sentence. ;-) 
It suggests to convert "are placed in ..." into "should be placed in ... by [developer]" and "[developer]" is omitted everywhere since it is obvious.

2021-01-08 14:41 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +. Remove `src/test` as well as `App.java` from `src/main/java/`. (Optional)
Since not everybody may create the project using that maven archetype, thus there is no `App.java` to be removed. I think changing `Optional` to `Recommended` would make a clear point, since it is not actually that mandatory and having `App.java` would not harm anything.

2021-01-08 14:41 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +│       │       └── example
Just wanted to keep the path shorter in the Figure. Also wanted to avoid "vaadin" to prevent any possible confusion about name of this package, since someone may infer it should have some "vaadin" inside it or to be exactly that `com.vaadin.flow.component`. 

Changed it to `org.brandname.theme`

2021-01-08 14:41 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +. In the `theme.json` add the parent theme's name, with the key `parent`:
Done.

2021-01-08 14:42 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +Process of extending from a parent theme is similar to having a theme folder except for the fact of adding "parent" key to the `theme.json`, so:
That sentence supposed to say the same thing which obviously doesn't! I rephrased it!

2021-01-08 14:42 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +NOTE: `assets` block is not accepting array of mappings. For defining each mapping, a separate `assets` block should be defined.
Nice one! I added this to the docs as separate example.

2021-01-08 14:42 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +Application-wide styles which are used across multiple views shall be defined in `styles.css`. Since this is an automatically loaded CSS file it should be named as `styles.css`, located directly unde
Done.

2021-01-11 06:46 UTC, caalador requested changes

2021-01-11 06:46 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +        ├── some-fonts <5>
Could just be some-folder and the explanation could mention that it can be used  for structuring the theme files.
As now it sort of leaves out the chance of having css inside folders.

2021-01-11 06:46 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +<1> Activating multiple application themes at the same time.
Then this should not be under the `not currently available` as as such it will never be implemented.

2021-01-11 06:46 UTC, caalador commented on articles/theming/application-theme.asciidoc
>  . Create a new maven project using either IDE or Maven. Example maven command:
I wouldn't merge create with IDE and create with maven archetype as the steps are for using archetype where as the create with IDE is IDE specific and should just say to create the shown structure. So there should be 2 paths to follow until `Create the folders ...` point.

2021-01-11 06:46 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +. Add the theme's assets and resources to a new theme folder under `themes/`.
```suggestion
. Add the theme files to the reusable theme folder.
```
As you created it just above you shouldn't create a new theme folder here.

2021-01-11 06:46 UTC, caalador commented on articles/theming/application-theme.asciidoc
>  . Create the folders `src/main/resources/META-INF/resources/themes/` and the reusable theme folder.
```suggestion
. Create the folders `src/main/resources/META-INF/resources/themes/[reusable-theme]`.
```

2021-01-11 08:05 UTC, jouni commented
I was trying to make the Vale check run properly, but apparently it doesn’t check files that have already been modified in previous commits. I’ll make a small change in the asciidoc file to trigger the checks for it.

2021-01-11 08:09 UTC, jouni commented
Okay, now we got a helpful error message, about the Vale configuration. I’ll work on fixing those.

2021-01-11 08:24 UTC, jouni commented
Alright, now the Vale checks seem to be running as expected. Please fix all errors and hopefully all warnings as well 🤗

2021-01-11 10:27 UTC, jouni commented on articles/theming/application-theme.asciidoc
> +<1> Activating multiple application themes at the same time.
We should remove the “currently”. If we have plans on addressing some of these limitations in the future, add a link to a relevant issue in GitHub instead.

2021-01-11 11:31 UTC, taefi commented on articles/theming/application-theme.asciidoc
>  . Create a new maven project using either IDE or Maven. Example maven command:
I think it is better not to go into details about **how to create an empty maven project** since this document is not about helping users to find out how to use/create maven projects. I would also exclude the second step (removing the App.java file) since that file's existence is dependant on how users are creating that maven project. To wrap up, I would merge/modify first to steps: like this:
```
1. Create a new empty maven project (using either your preferred IDE's wizard or through Maven CLI) and 
make sure no unused java classes or resources exist in the project, then continue with the next steps. 
```

2021-01-11 11:49 UTC, caalador requested changes

2021-01-11 11:49 UTC, caalador commented on articles/theming/application-theme.asciidoc
> +The easiest way to create a reusable theme jar is to create a maven project with the following structure:
This is a bit missleading as it's not the easiest way it's the way with maven.
```suggestion
To create a reusable theme jar with maven, create a project with the following structure:
```

2021-01-11 11:49 UTC, caalador commented on articles/theming/application-theme.asciidoc
>  . Create a new maven project using either IDE or Maven. Example maven command:
I would in this instance remove all the steps and just show the contents of the pom. as everything else is in the figure.
Also the header `=== Creating the theme jar` should be renamed to something else.. perhaps `=== Reusable theme project structure` or `=== Reusable theme contents`

2021-01-11 11:58 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +        ├── some-fonts <5>
Done. 

I kept `/some-images` there since it's been referenced in another example. But changed the `/some-fonts` to `some-folders` and changed the description to a more general statement to include all sorts of files.

2021-01-11 11:58 UTC, taefi commented on articles/theming/application-theme.asciidoc
> +<1> Activating multiple application themes at the same time.
Done.

Changed the title completely from `not currently available` to `not available`.

2021-01-11 13:04 UTC, caalador approved these changes

2021-01-11 13:11 UTC, taefi commented on articles/theming/application-theme.asciidoc
>  . Create a new maven project using either IDE or Maven. Example maven command:
Done.

2021-01-11 13:15 UTC, jouni requested changes
Please fix all Vale errors and preferable the warnings as well.

2021-01-11 13:45 UTC, taefi commented
> Please fix all Vale errors and preferable the warnings as well.

I applied those comments that could be applied. Now, the remaining errors are about:

- The spelling checks for `css`, `html`, etc. Should I use `CSS` and `HTML` instead?
- Another error is: **Punctuation should be inside the quotes.** This is not applicable, since those quotes are there to show a string literal, not some indirect speech from a third person.
- Another error is: **Commas and periods go inside quotation marks.** This is not applicable, same as above.
- Most of the warnings are about using `my` or `we` which are not applicable here, those are folder names or part of another word (such as we in fonta**we**some). 

What should I do about these?

2021-01-11 15:19 UTC, jouni commented
> The spelling checks for css, html, etc. Should I use CSS and HTML instead?

Yes.

> Another error is: Punctuation should be inside the quotes.

I would perhaps remove the quotes, and use something like `[filename]#my-theme#` instead. That will render the text using monospace font, and allows us to target file/folder names within documentation text in general.

> Most of the warnings are about using `my` or `we` which are not applicable here

There are valid cases of those there as well. If those are part of filenames, then we might want to use formatting that is escaped from those checks (similar to my previous comment).

2021-01-11 15:20 UTC, jouni commented
> those are folder names or part of another word (such as we in fonta**we**some).

I didn’t notice this particular case.

2021-01-11 21:48 UTC, merged