docs: document TS custom events typings
vaadin/docs pull request #98
Opened 2021-01-11 09:12 UTC by web-padawan

Added some documentation for custom events typings and removed the corresponding section from "limitations".

2021-01-11 09:28 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +NOTE: as of Vaadin 19, type definitions for custom events are available for these components:
Is this line needed, as there is already [role="since:com.vaadin:vaadin@V19"] above?

2021-01-11 09:39 UTC, web-padawan commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +NOTE: as of Vaadin 19, type definitions for custom events are available for these components:
Thanks, updated.

2021-01-11 10:10 UTC, jouni commented
Update the main heading of the page:

`== TypeScript Definitions of Components` → `= TypeScript Definitions of Components`

2021-01-11 10:50 UTC, web-padawan commented
@jouni thanks, done.

2021-01-12 08:03 UTC, tomivirkki approved these changes

2021-01-12 08:03 UTC, tomivirkki commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +NOTE: type definitions for custom events are currently available for these components:
NIT: This listing would age quickly. Need to remember to update it regularly, or alternatively, not have it list the components separately.

2021-01-12 08:04 UTC, web-padawan commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +NOTE: type definitions for custom events are currently available for these components:
I didn't have any ideas how to make it better but hopefully for V20 we will be able to remove it altogether.

2021-01-12 10:49 UTC, jouni requested changes

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +NOTE: type definitions for custom events are currently available for these components:
```suggestion
Type definitions for custom events are available for these components:
```
Avoid unnecessary admonitions. 

If you do use them, prefer to use the `[NOTE]` syntax, as that doesn’t trip the Vale check for “use lowercase letter after semicolon”. And always add a title for the admonition to improve scan-ability. And lastly, admonitions should be standalone in the sense that a user should not be required to read them to understand what follows before or after them.

For example:

```asciidoc
.Not available for all components
[NOTE]
Type definitions for custom events are not available for all components. See ... for more information.

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +=== Custom Events [[custom-events]]
```suggestion
[role="since:com.vaadin:vaadin@V19"]
=== Custom Events [[custom-events]]
```

These versioning badge roles do not work standalone. They need to be attached to a heading, paragraph, sentence, or an open block (asciidoc concept). See https://github.com/vaadin/docs/wiki/Authoring-articles#indicating-new-and-deprecated-features for examples.

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +[role="since:com.vaadin:vaadin@V19"]
```suggestion
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  [source, typescript]
```suggestion
[source, TypeScript]
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  Vaadin components come with TypeScript definitions helping to use web components in TypeScript views.
```suggestion
[role="com.vaadin:vaadin@V17"]#Vaadin components come with TypeScript definitions# helping to use web components in TypeScript views.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +Support for TypeScript definitions is added in Vaadin 17. In most of cases, it does not require any changes to the code.
```suggestion
In most of cases, TypeScript support does not require any changes to the code.
```

Avoid having explicit mentions about Vaadin versions in the content – _write content with the mindset that a feature has always been in the product and will be there forever_. Use the versioning badges to indicate when a certain feature has been added or deprecated.

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +At the same time, using proper types for the web components helps to make the client side views more reliable.
```suggestion
At the same time, using proper types for the web components helps making the client side views more reliable.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +Support for TypeScript definitions is added in Vaadin 17. In most of cases, it does not require any changes to the code.
As a side note, it would be good to give some pointers about the cases where it could require changes to the code. Now the reader is left with a question, that will I need to make changes to my code?

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +Depending on the IDE you use, TypeScript definitions can also give additional benefits like better code completion and auto import.
```suggestion
Depending on the IDE you use, TypeScript definitions can also enable better code completion and auto import.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  syntax highlighting and type checking support for LitElement templates. You can also use
```suggestion
syntax highlighting and type checking support for LitElement templates. 
You can also use
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +They are removed during `webpack` compilation step and will not end up in the resulting JavaScript bundle.
```suggestion
They are removed during `webpack` compilation step and do not end up in the resulting JavaScript bundle.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +Below you will find examples of how to improve developer experience in such cases by applying proper types.
```suggestion
The following examples show how to improve the developer experience in such cases by applying proper types.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  [source, typescript]
```suggestion
[source, TypeScript]
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  [source, typescript]
```suggestion
[source, TypeScript]
```

Prefer writing the language as it should appear in the content.

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +This way we are telling the TypeScript compiler that `dialog` property is initialized indirectly, and therefore it does not need a default value.
```suggestion
This tells the TypeScript compiler that the `dialog` property is initialized indirectly and does not need a default value.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +This API is not compatible with lit-html, so in LitElement-based views we recommend using `renderer` functions instead.
```suggestion
This API is not compatible with lit-html. Use `renderer` functions in LitElement-based views instead.
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +In order to access them without TypeScript warnings, you need to get them properly typed by importing and using corresponding type declarations:
```suggestion
To access them without TypeScript warnings, you need to get them typed by importing and using the corresponding type declarations:
```

2021-01-12 10:49 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
>  [source, typescript]
```suggestion
[source, TypeScript]
```

2021-01-12 11:53 UTC, web-padawan commented
@jouni thanks for the review, much appreciated 🙇‍♂️  Updated the PR and accepted all the suggestions.

2021-01-12 13:21 UTC, jouni requested changes

2021-01-12 13:21 UTC, jouni commented on articles/fusion/advanced/fusion-advanced-components-definitions.asciidoc
> +[role="com.vaadin:vaadin@V17"]#Vaadin components come with TypeScript definitions# helping to use web components in TypeScript views.
```suggestion
[since:com.vaadin:vaadin@V17]#Vaadin components come with TypeScript definitions# helping to use web components in TypeScript views.
```

Oops, I accidentally used incorrect syntax here.

2021-01-12 13:52 UTC, jouni approved these changes

2021-01-12 13:59 UTC, merged